### ISSUE TITLE
ARRig and AR Wizard missing from Sample

### ISSUE THREAD

**Issue by ironandsilk** [Unity-Technologies/arfoundation-samples#1]
The AR Foundation package sample is missing the ARRig.
It is also missing the AR Wizard when right clicking from the Game Object > AR > Set up.
![screen shot 2018-06-16 at 9 39 34 am](https://user-images.githubusercontent.com/4619122/41499119-443801b0-7149-11e8-9e3d-ebd5e7631117.png)

**Comment by timm-unity** [comment]
Unfortunately, an outdated version of the documentation was initially published. Updated docs here https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0 should be accurate.

`ARRig` is now `ARSessionOrigin`.
