### ISSUE TITLE
Plane texture not visible

### ISSUE THREAD

**Issue by Aupuma** [Unity-Technologies/arfoundation-samples#10]
Hi, I wanted to change the plane texture to an opaque seamless texture of my choice, but when I change the material only its base color is visible, not the texture.
Does this API work with plane materials differently or I'm missing something?

**Comment by timm-unity** [comment]
You can use whatever material you'd like. The `ARPlaneManager` will instantiate whatever prefab you assign to its "Plane Prefab" field. The plane prefab used in the sample (which is the same one you get with the menu item GameObject > XR > AR Default Plane) uses a material with an orange color set on its [Mesh Renderer](https://docs.unity3d.com/Manual/class-MeshRenderer.html). It's a simple material which uses a shader with a solid color, but you can create a new material with your texture and assign that to the prefab's Mesh Renderer instead.

**Comment by Aupuma** [comment]
I have tried with the planeGrid material that comes with the ARCore unity package, and the same is happening, the material is semitransparent but the grid texture is not visible.

**Comment by Aupuma** [comment]
A user from the Unity forum found the solution: uv's are not assigned when the mesh is generated. This code from Unity documentation fixed it:

`Vector3[] vertices = mesh.vertices;
Vector2[] uvs = new Vector2[vertices.Length];
 
for (int i = 0; i < uvs.Length; i++)
{
         uvs[i] = new Vector2(vertices[i].x, vertices[i].z);
}
mesh.uv = uvs;`

With this code, textures are visible (they move when new vertices are added to the plane, but for me is enough) I think it should be fixed in the next update, more users could need it.

**Comment by timm-unity** [comment]
Ah, I understand. The `ARPlaneMeshVisualizer` does not compute UVs, that's true. I've added this for the next version (and they won't move when new vertices are added).

**Comment by timm-unity** [comment]
We published version `1.0.0-preview.13` of `ARFoundation` today (and updated the sample project to use it). The `ARPlaneMeshVisualizer` now computes UVs for the mesh. Let me know if that works for you.

To update, go to Window > Package Manager > AR Foundation > Update to 1.0.0-preview.13

**Comment by gameboyJ3** [comment]
> A user from the Unity forum found the solution: uv's are not assigned when the mesh is generated. This code from Unity documentation fixed it:
> 
> ```
> Vector3[] vertices = mesh.vertices;
> Vector2[] uvs = new Vector2[vertices.Length];
>  
> for (int i = 0; i < uvs.Length; i++)
> {
>          uvs[i] = new Vector2(vertices[i].x, vertices[i].z);
> }
> mesh.uv = uvs;
> ```
> With this code, textures are visible (they move when new vertices are added to the plane, but for me is enough) I think it should be fixed in the next update, more users could need it.
Hi mate,
My goal is to apply textures with cubemap for getting reflection.I am currently using planegrid material and shader , can you please help me how i can replace this plane shader with my vertex shader whih has a ubemap refletion property whih will work well.
