### ISSUE TITLE
How to get ARFace mesh coordinates on the ARcamera cpu image (Unity/ARFoundation)

### ISSUE THREAD

**Issue by AMMAS1** [Unity-Technologies/arfoundation-samples#1001]
I'm trying to use AR camera with face tracking to capture some vertices from the facemesh(and mask the area), and pass the image to opencv for unity to do further processing. 
```
Vector3 screenPosition = arCamera.GetComponent<Camera>().WorldToScreenPoint(face.transform.position + face.vertices[0])
```

I'm using this but this returns the position relative to the screen which has a different aspect ratio than the image from "cameraManager.TryAcquireLatestCpuImage". (2340 x 1080) vs (640 x 480)

I tried looking every where how to transform the position from world to cpu image and tried to map the screen coordinates to the cpu image using displaymatrix and projectionmatrix but no luck.

Any solution would be appreciated!!

**Comment by AMMAS1** [comment]
Bump

**Comment by andyb-unity** [comment]
Hi @AMMAS1, we aren't able to help you with this issue as this is beyond the scope of this repository. Feel free to ask your question on the forums or other community sites.
