### ISSUE TITLE
ARAnchor is not loading in ARWorldMap

### ISSUE THREAD

**Issue by Gold1010** [Unity-Technologies/arfoundation-samples#1005]
I have tried to save/load ARAnchor from ARWorldMap sample scene.
It is working well for ARPlane, but it is not working ARAnchor.
I attached screenshot I did for this.

**Additional context**
<img width="942" alt="Screen Shot 2022-09-07 at 11 15 28" src="https://user-images.githubusercontent.com/79176935/188840601-4c771998-4086-4e6a-9c9f-bff72bfbcd0e.png">

**Comment by tdmowrer** [comment]
How do you know it isn't loading the anchors? You don't have a prefab for the anchor manager, so unless you are debug logging in anchor added event, you probably wouldn't see anything.

**Comment by Gold1010** [comment]
Thank you so much.
When I added the prefab for anchor manager, it worked
