### ISSUE TITLE
[Bug] Point cloud and anchors floating

### ISSUE THREAD

**Issue by hasionerin** [Unity-Technologies/arfoundation-samples#1006]
After the point cloud is detected , then shake the mobile phone , point cloud floating , sometings the point cloud will return in a few minutes, sometimes can't . 
i add some anchors on point cloud.   anchors will floating with these  point clouds.
It happens more frequently on lower end devices and less on higher end .
so i wonder if there is any solution to this problem . looking forward to your reply !thanks
@DavidMohrhardt

**Comment by andyb-unity** [comment]
From our [docs](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/index.html): AR Foundation allows you to work with augmented reality platforms in a multi-platform way within Unity. This package presents an interface for Unity developers to use, but doesn't implement any AR features itself.

Questions about point cloud tracking performance are in the domain of platform providers:

Google: https://github.com/google-ar/arcore-android-sdk
Apple: https://developer.apple.com/forums/

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
