### ISSUE TITLE
The CpuImage of the Camera returns only a low resolution texture

### ISSUE THREAD

**Issue by valantano** [Unity-Technologies/arfoundation-samples#1009]
When accessing the XRCpuImage I only get a resolution of 640,480.
Is there a way to access the full resolution camera image.

```
bool successful = cameraManager.TryAcquireLatestCpuImage(out XRCpuImage image);
Debug.Log("#################### Background" + image.dimensions); //Info Unity #################### Background(640, 480)

```
I could not find anything in the Sample below:
https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/CpuImageSample.cs

Thanks in advance.

**Comment by DavidMohrhardt** [comment]
You may want to look into your current camera configuration. https://github.com/Unity-Technologies/arfoundation-samples#cpuimages

**Comment by valantano** [comment]
Thank you.

I was able to get a resolution of 1440x1080. Its still smaller than the actual Screen image (2280x1080) but it will do.
Do you know where the right place is to set this configuration? I did it very clumsy in an Update function which tries do set it until it was successful.

For me it seems that the cameraManager takes a low resolution copy of the real camera image and uses this to do anything AR related but then displays the real camera image on the screen and over it the AR stuff. Am I correct?

And does this also influence the quality of the environment depth map and all other AR functionalities?

Thank you in advance.

**Comment by andyb-unity** [comment]
From our [docs](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/index.html):

> AR Foundation allows you to work with augmented reality platforms in a multi-platform way within Unity. This package presents an interface for Unity developers to use, but doesn't implement any AR features itself.

So the `ARCameraManager` does not perform any AR-related calculations. It only mediates data to and from ARKit (or your other installed provider(s)), nor does it alter images given by the provider.

Your CPU image size is solely dependent on camera configuration regardless of screen resolution.

**Comment by andyb-unity** [comment]
Realizing I missed part of your question when I answered a couple days ago.

Instead of Update, you can use a Coroutine on Start to query available camera configurations and select one. I posted an example like this to the forums a while back that you can use as reference:

https://forum.unity.com/threads/can-we-use-arkit-6.1293639/#post-8272695

**Comment by valantano** [comment]
Thank you very much, for your help :)
I think this Topic can be closed now.
