### ISSUE TITLE
how to develop watch try on

### ISSUE THREAD

**Issue by unknownamea** [Unity-Technologies/arfoundation-samples#1013]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidMohrhardt** [comment]
You may find more help on the forums https://forum.unity.com/forums/ar.161/

**Comment by unknownamea** [comment]
Thank you very much! This is very useful.









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Unity-Technologies/arfoundation-samples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 上午6:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Unity-Technologies/arfoundation-samples] how to develop watch try on (Issue #1013)





 
You may find more help on the forums https://forum.unity.com/forums/ar.161/

**Comment by ankur-unity** [comment]
Closing this issue since there are no follow-up questions. Feel free to re-open it if you have additional questions.
