### ISSUE TITLE
AR Foundation and MARS

### ISSUE THREAD

**Issue by ugacode** [Unity-Technologies/arfoundation-samples#1016]
Should these samples work with the latest version of MARS?
I've been trying both the stable release (4.2) and the latest code and it seems impossible to get the body tracking 3D sample to work with MARS.
Am I doing something wrong or is this not meant to work?

Thanks for your help!

**Comment by andyb-unity** [comment]
Hi @ugacode, if you are still experiencing issues with body tracking and MARS, please file a bug: https://unity3d.com/unity/qa/bug-reporting

We aren't able to help you further with this issue without a bug report, but if you do file a bug feel free to re-open this issue and share the bug number for reference.

**Comment by andyb-unity** [comment]
To answer your question to the best of my ability as a developer who does not work on MARS: AR Foundation body tracking is expected to work on platforms that support body tracking. (currently, iOS only)
