### ISSUE TITLE
QR Code as Image Tracking

### ISSUE THREAD

**Issue by nextechar-hardik** [Unity-Technologies/arfoundation-samples#1018]
Hello Everyone , 

I am using QR Code (512*512 Px Image) as marker, and adding that in runtime image library. When i am scanning that image i am able to get Tracking event and instantiate Gameobject with Anchor on word Position relative to that image tracking pose. 

After that i am disabling AR Image Tracking manager and reference lib assign null and disable all trackable image. 

After that i am trying to scan same kind of QR code image and AR Foundation Reset my session or Anchor position to that image position i had check at that time i am not getting any image tracking event.  

How can i stop this kind of behaviour ?

**Comment by andyb-unity** [comment]
Can you clarify what you mean here?

> After that i am trying to scan same kind of QR code image and AR Foundation Reset my session or Anchor position to that image position i had check at that time i am not getting any image tracking event.

- What are you trying to accomplish?
- How are you trying to do that?
- Are you reporting a bug or is this strictly a "how to" question?

**Comment by nextechar-hardik** [comment]
For now its simple How to Question. 

- I am trying to add QR As Image target and all work as expected.
-  After that I am scanning that image as Marker using AR Foundation that also work fine
- Assume I am scanning same marker or similar marker 10 feet away. 
- then All AR session space move at that location. 

My problem is Session Space moving when found similar Image.

**Comment by nextechar-hardik** [comment]
For example When I am Scanning Marker (QR Image) First time then My AR Session Space Position = 0.1,0.1,0.1 and when I am scanning Another marker (10 feet away) then my session Space position change to 10,10,10.

**Comment by nextechar-hardik** [comment]
Thank you , AR Foundation 5.0 resolve my issue.
