### ISSUE TITLE
Instantiate a 3D model on face detection

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#1019]
As the title suggests, I want to make a 3D model as a mask over the user's face, is this achievable on both iOS and Android?

I do not need blendshapes, it would just be a model that covers the face and moves as it moves.

Any help is kindly appreciated as I am just starting with Face Tracking,

**Comment by tdmowrer** [comment]
Both ARKit (iOS) and ARCore (Android) provide a pose for the face (usually near the center of the head) and a mesh that represents the face. Some caveats for making it cross-platform:
* The pose likely varies slightly between ARCore and ARKit; that is, the "center of the head" is probably not the same between the two SDKs, so you may need to adjust the final transform if your "mask" is relative to this pose.
* The face mesh is like a mask for the user's face, which may be similar to your use case, but there are differences in the face mesh provided by each SDK: ARCore provides a "solid" mesh, where the eyes and mouth are filled in, while there are holes for these features on ARKit. There is no API to identify which triangles correspond to the eyes and mouth.

There are some samples in this repo that should get you started:
* [Face Pose](https://github.com/Unity-Technologies/arfoundation-samples#facepose)
* [Face Mesh](https://github.com/Unity-Technologies/arfoundation-samples#facemesh)

**Comment by ankur-unity** [comment]
Closing this issue as it has been resolved. Feel free to reopen it if you have follow-up questions.
