### ISSUE TITLE
Shader Unsupported warnings on compile

### ISSUE THREAD

**Issue by jBachalo** [Unity-Technologies/arfoundation-samples#102]
Receiving the following Shader warnings when compiling in Xcode.
Can these be safely ignored?

WARNING: Shader Unsupported: 'Lightweight Render Pipeline/Lit' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Unlit/ARCoreBackgroundLWRP' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Unlit/ARCoreBackgroundLWRP' - Setting to default shader.

**Comment by mdurand42** [comment]
Please update to 4.0.0-preview.1 and see whether these warnings persist.
