### ISSUE TITLE
How to open project in Unity

### ISSUE THREAD

**Issue by hsnnL** [Unity-Technologies/arfoundation-samples#1020]
How do I...
It's not clear in the instructions how to open the project in Unity. There is no ~.unitypackage file. What do you mean by "load the project at the root..." ? And can I import it to an already existing project? 
Thanks in advance.

**Comment by tdmowrer** [comment]
This samples repo is a complete, standalone Unity project. It is not intended to be imported into an existing project.

If you want to add AR Foundation to an existing project, you can install it via the package manager.

**Comment by nextechar-hardik** [comment]
Steps : 
1- Download repository from git
2- Open Unity Hub
3 - Click on Arrow beside "Open" button 
4 - Click Add Project from Disk
5 - Select downloaded path 
6 - Done

**Comment by andyb-unity** [comment]
Closing this issue as resolved by the answers above. Thanks tdmowrer and nextechar-hardik! Feel free to re-open this issue if you have further questions.
