### ISSUE TITLE
How to get arcamera RenderTexture contain ARObjects.

### ISSUE THREAD

**Issue by Sjaeseok** [Unity-Technologies/arfoundation-samples#1022]
i tried this code

`        Graphics.Blit(null, renderTexture, m_ARCameraBackground.material);
        var activeRenderTexture = RenderTexture.active;
        RenderTexture.active = renderTexture;

        if (m_LastCameraTexture == null)
            m_LastCameraTexture = new Texture2D(renderTexture.width, renderTexture.height, TextureFormat.ARGB32, true);

        m_LastCameraTexture.ReadPixels(new Rect(0, 0, renderTexture.width, renderTexture.height), 0, 0);
        m_LastCameraTexture.Apply();
        RenderTexture.active = activeRenderTexture;
        // Write to file
        var bytes = m_LastCameraTexture.EncodeToPNG();
        var path = Application.persistentDataPath + "/camera_texture.png";
        File.WriteAllBytes(path, bytes);`

but i cant get texture contain ar objects.
how can i get the texture contain ar obejcts?

**Comment by nextechar-hardik** [comment]
AR camera also work like normal camera component in Unity so, 
i haven't try this. but this should work 

1. Create a new Render Texture in you Project Folder
2.  Assign that render texture in main camera "Target Texture" Field. 
3.  Assign same render texture in material or Canvas Raw Texture 
4. done 

You can see All Thing in render texture what camera see....

**Comment by Sjaeseok** [comment]
> AR camera also work like normal camera component in Unity so, i haven't try this. but this should work
> 
> 1. Create a new Render Texture in you Project Folder
> 2. Assign that render texture in main camera "Target Texture" Field.
> 3. Assign same render texture in material or Canvas Raw Texture
> 4. done
> 
> You can see All Thing in render texture what camera see....

Thanks reply.
I tried that way.
ARCamera not showing display after assign render texture in 'AR Camera'.
but only could just show render texture and without ARObject. 
Is there another way?

**Comment by DavidMohrhardt** [comment]
You may want to simply perform a [Graphics.Blit(yourRenderTexture, null, null);](https://docs.unity3d.com/ScriptReference/Graphics.Blit.html) after all rendering has completed for a given frame to write the render texture to the back buffer.
