### ISSUE TITLE
Support 90 fps (and beyond) rendering

### ISSUE THREAD

**Issue by tvkamara** [Unity-Technologies/arfoundation-samples#1029]
I'm aware that the tracking part is limited to 30 or 60 (selected devices) frames per second when using ARCore. However unticking the Match framerate button allows to use 60 fps rendering with only 30 fps tracking.

I would like to use 60 fps for tracking (the current maximum I believe), but use 90 fps or more for content rendering. I have a quite a special use case where matching the camera content to rendered objects is not crucial.

Is there already a way to unlock 90Hz or more when using ARCore? It seems that the maximum refresh rate is 60Hz even without vsync and setting Application.targetFrameRate to 90. The flagship phones already offer 120Hz displays and even non-flagship phones have 90Hz displays. Falling back to 60 seems quite ancient at this point.

**Comment by shoukailiang** [comment]
@tvkamara Is ARKit the same?

**Comment by andyb-unity** [comment]
@tvkamara Once you have unchecked the AR Session's **Match Framerate** property, AR Foundation does not control your app's frame rate. I would recommend that you follow up in Unity's Android forum if you still have questions about your app's maximum frame rate.

One helpful-looking post I found while checking on this: https://forum.unity.com/threads/set-screen-refresh-rate-on-android-11.997247/#post-6474920

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open the issue if you have further questions.
