### ISSUE TITLE
ARCameraBackground doesn't work with LWRP in 2019.1.0b7

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/arfoundation-samples#103]
2019.1.0b7 requires LWRP package version 5.6.1, while this sample project lwrp branch is currently set to package version 4.8.0-preview and editor 2018.3.0f2.

found with master branch commit 32ada6ac176295e0a58a2e8558f8c60577a03711
and lwrp_support branch commit df0c4c0908d2bc7118c61e17d0fbe560b42d476d (after fixing the include errors)

**Comment by philmaas** [comment]
It would be great to update the lwrp support branch to work with 2019

**Comment by UnityEQ** [comment]
agreed

**Comment by UnityEQ** [comment]
related https://drive.google.com/file/d/1J8ChJIsAXdXdmOPtNF_FIqd9exYD0kql/view?usp=sharing

**Comment by UnityEQ** [comment]
update: https://forum.unity.com/threads/2019-arfoundation-lwrp-crisis-thread.663448/

**Comment by tdmowrer** [comment]
ARFoundation 3.0 provides much improved support for LWRP/Universal RP. Step-by-step instructions can be found [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html).
