### ISSUE TITLE
5.0.2 How to hide or disable the ARFoundation ARKit/ARCore Camera background rendering

### ISSUE THREAD

**Issue by Phantomxm2021** [Unity-Technologies/arfoundation-samples#1031]
ARF 5.0.2
Unity 2021.3.13f1
When I set ARBackground enable to false, ARKit doesn't work.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/82647748/203228760-aaa9e38c-e34c-46b0-b6e8-17a6e4fbafab.png">

**Comment by tdmowrer** [comment]
What exactly doesn't work? Can you provide more details? What is your expectation vs what happens?

**Comment by Phantomxm2021** [comment]
> What exactly doesn't work? Can you provide more details? What is your expectation vs what happens?

Sorry, I didn't express myself clearly.
When I set ARBackground enable to false. The screen is stucking, Not 3Dof or 6Dof. All xr-subsystems do not work, such as point cloud manager or plane manager.

**Comment by Phantomxm2021** [comment]
Bug case id: IN-23721  @tdmowrer

**Comment by ankur-unity** [comment]
@Phantomxm2021 - It was a known issue in AR Foundation 5.0.2 and has been fixed in 5.0.3
https://issuetracker.unity3d.com/issues/ios-disabling-ar-camera-background-kills-position-tracking-on-ios-in-arfoundation-4-dot-2-6
