### ISSUE TITLE
[Bug] Ar face mask for iOS is flickering while using custom material for face mask.

### ISSUE THREAD

**Issue by shoib-akthar** [Unity-Technologies/arfoundation-samples#1034]
Add custom material for the face mask and try moving the face the flickering starts and eventually crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new scene add Arsession and Arsession origin OR open arfacemesh sample scene and replace the default materials with custom material.

**Smartphone (please complete the following information):**
 - Device: [iPad Pro devices]
 - OS: [e.g. iOS 14]
 - Unity version 2021.3.8f1
 - ARFoundation version 4.2.3

**Comment by yosun** [comment]
which custom material are you using?

**Comment by shoib-akthar** [comment]
not the one provided by arfoundation

**Comment by DavidMohrhardt** [comment]
@shoib-akthar can you recreate the issue while using the default material? If not, can you post your bug number here?

**Comment by ankur-unity** [comment]
@shoib-akthar - Closing this issue since we haven't heard from you in a while. Feel free to re-open it, If you continue to reproduce this issue.
