### ISSUE TITLE
ARFoundation v5 and URP always black screen

### ISSUE THREAD

**Issue by creativewax** [Unity-Technologies/arfoundation-samples#1037]
I have tried a few different ways now, I have converted to URP, I have setup new projects and imported everything from scratch, but no matter what I do, If I use v5 and URP I always get a black screen and weird artefacts going on around 3D objects in the view, if I run the the CPU Images example, you still get all the image data coming through for them, its the main camera feed I am having constant hassle with. Has anyone successfully done this? is it a Unity version thing maybe?

I really want the latest ARFoundation features mixed with the VFX Graph features

**Comment by therussmorris** [comment]
What version of Unity are you using?

**Comment by creativewax** [comment]
@therussmorris 2022.1.2.3f1

**Comment by creativewax** [comment]
ah ok, ill got back to that and give it a go, sound what version of ARFoundation are you running?

**Comment by creativewax** [comment]
Nice, right ill give it a go now

**Comment by creativewax** [comment]
I can confirm URP 12.1 did the trick in 2021 so annoying problems like this

**Comment by ankur-unity** [comment]
@creativewax - there is a bug in URP on 2022.1 and 2022.2 that we're working to resolve. As a workaround, we have added a  new `AfterOpaques` background rendering mode in `ARCameraManager`. More here: https://forum.unity.com/threads/ar-foundation-pre-5-0-and-urp-background-not-rendering.1302213/#post-8388111

**Comment by novavision** [comment]
There is the same black background bug with errors on play (Windows) with XR Simulation if you use Linear color space, not Gamma. ARFoundation 5.0.4, Unity 2022.2.7f1, URP 14.0.6
