### ISSUE TITLE
Doesn't compile with recent versions of LWRP

### ISSUE THREAD

**Issue by jBachalo** [Unity-Technologies/arfoundation-samples#104]
Hi
Any chance there is an eta on when this will work with more recent versions of LWRP?
558 compile errors when trying to open using LWRP 5.2.1

**Comment by tdmowrer** [comment]
ARFoundation 3.0 provides much improved LWRP/Universal RP support. Step-by-step guide [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html).
