### ISSUE TITLE
[Bug] Undefined Objective-C symbol errors preventing iOS builds

### ISSUE THREAD

**Issue by WarrenHullStunts** [Unity-Technologies/arfoundation-samples#1042]
**Description**
Builds of the ARFoundation samples are failing with "undefined symbol" errors. Here are the first 3 of 99 for reference:

Undefined symbols for architecture arm64:
  "_objc_msgSend$copyFrom:withStride:toDestination:trackingState:", referenced from:
      -[TrackableProvider copyFromChanges:withStride:toAdded:toUpdated:toRemoved:] in libUnityARKit.a(TrackableProvider.o)
  "_objc_msgSend$deallocNativePtr:", referenced from:
      -[TrackableProvider copyFromChanges:withStride:toAdded:toUpdated:toRemoved:] in libUnityARKit.a(TrackableProvider.o)
      ___28-[TrackableProvider dealloc]_block_invoke in libUnityARKit.a(TrackableProvider.o)
  "_objc_msgSend$copyFrom:toDestination:trackingState:nativePtr:", referenced from:
      -[TrackableProvider copyFrom:withStride:toDestination:trackingState:] in libUnityARKit.a(TrackableProvider.o)

<img width="610" alt="image" src="https://user-images.githubusercontent.com/82109378/207708474-0c9de810-aa94-429f-93b1-71f929b997a7.png">

**To Reproduce**
- git clone the 5.0 arfoundation-samples repository
- open in Unity
- change platform to iOS in build settings and build
- open newly created Xcode project
- in the "signing & capabilities" tab on the "Unity-iPhone" target, set signing to "automatic" and choose a team
- connect an iOS device and choose it as the device target
- build the project with the play button

**Expected behavior**
The project should build successfully.

**Actual behavior**
The project fails with 99 errors of the type "Undefined symbol: _objc_msgSend$..." 

**Smartphone**
 - Device: iPhone 12 Pro Max
 - OS: 15.5
 - Unity 2022.2.0f1
 - XCode Version 13.4.1
 - ARFoundation 5.0.3

**Comment by andyb-unity** [comment]
You are required to build with Xcode 14 starting with com.unity.xr.arkit version 5.0.3. See the changelog for more information: https://docs.unity3d.com/Packages/com.unity.xr.arkit@5.0/changelog/CHANGELOG.html

This change is necessary for your app to behave correctly on iOS 16 devices, as Apple does not support iOS 16 API's in Xcode 13.

**Comment by WarrenHullStunts** [comment]
Thank you for the help. That solved the issue.
