### ISSUE TITLE
These namespaces wont register and I have no clue why, please help. 

### ISSUE THREAD

**Issue by Connorpate** [Unity-Technologies/arfoundation-samples#1044]
I am trying to run a sample scene from the ar foundation samples but these error codes are being thrown and I haven't been able to find anything on the internet that can point me to a solution. 
If you know why or how to fix this problem it would help a ton. Thank you.
![Unity error codes](https://user-images.githubusercontent.com/120766571/209570314-b40155f8-485f-4794-9990-186f7e30176d.png)

![Error code](https://user-images.githubusercontent.com/120766571/209570331-a8f928cc-c646-458b-b556-adae559ab1ff.png)

**Comment by andyb-unity** [comment]
Have you modified the sample project at all? It looks to me like you may have cloned the sample project from the main branch and then changed the AR Foundation version to 4.2?

`XRDepthSubsystem` and associated classes were renamed to `XRPointCloudSubsytem` in 5.0: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/version-history/migration-guide-5-x.html#xrdepthsubsystem-is-now-xrpointcloudsubsystem

If you are looking for an AR Foundation 4.2-compatible sample project, check out the `4.2` branch of this repo. Or if this doesn't fix your issue, please provide more information. Happy new year!

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open if you have further questions.
