### ISSUE TITLE
Framerate locked to 30fps on android???

### ISSUE THREAD

**Issue by shoukailiang** [Unity-Technologies/arfoundation-samples#1048]
version:unity2020.3.x lts
arfoundation：4.1.10
![image](https://user-images.githubusercontent.com/24668909/212604577-736ea1b7-56e7-4210-9bdb-2869ac65f686.png)
In my Xiaomi 13 and Xiaomi 8 ,the framerate locked to 30fps.
But in my iphoneX ,the framerate is 60fps.
I don't quite understand why Android is locked at 30fps

**Comment by tdmowrer** [comment]
ARCore only supports 30 fps on most Android devices. A few support higher frame rates; see https://developers.google.com/ar/devices

By default, AR Foundation sets the application frame rate to match the ARCore frame rate (30 fps on most devices). You can disable this on the ARSession component, which would allow your app fps to be higher; however the ARCore frame will no longer be synced with the app frame, which may cause the passthrough to appear less smooth.

**Comment by shoukailiang** [comment]
Thank you for your reply. It seems that ARKit can reach 60fps.
I have another question. Can it exceed 60fps in iPad Pro 2021 (m1, 120hz)?

**Comment by tdmowrer** [comment]
ARKit has been 60 Hertz since launch. I don't know whether newer devices support higher frame rates.

**Comment by shoukailiang** [comment]
Thanks.
