### ISSUE TITLE
Multiple MutableRuntimeReferenceImageLibrary 

### ISSUE THREAD

**Issue by nextechar-hardik** [Unity-Technologies/arfoundation-samples#1056]
Is that possible to add 2 different MutableRuntimeReferenceImageLibrary in AR foundation and switch them as per requirement ? 

i have try that by using this code but after switch only 1 library work second not work even switch called... 

`
void switchImageLibrary() {
  curLibIndex = curLibIndex == 0 ? 1 : 0;
  Debug.Log("setting lib with index " + curLibIndex);
  manager.enabled = false;
  var lib = curLibIndex == 0 ? firstLibrary : secondLibrary;
  manager.referenceLibrary = manager.CreateRuntimeLibrary(lib);
  manager.enabled = true;
}
`

**Comment by Unity3D-Hardik** [comment]
https://forum.unity.com/threads/switching-multiple-mutable-runtimereferenceimagelibrary-is-possible.1396903/

**Comment by nextechar-hardik** [comment]
Now i am able to switch without any issue so closing this, If any one required will share public repo.
