### ISSUE TITLE
Get raw ARFoundation camera image without instantiated objects or GUI

### ISSUE THREAD

**Issue by romanvanderaa** [Unity-Technologies/arfoundation-samples#1058]
I'm trying to get the camera image of my ARFoundation IOS application, without augmented 3D objects and without the UI buttons. I'm trying to get this done by using TryAcquireLatestCpuImage. I'm wondering if this is the most efficient way, if it's even a correct way to achieve what I want. Maybe someone has had success with this or other methods, I can't find a lot of documentation on this!

Looking forward to hear from you all!

**Comment by ankur-unity** [comment]
@romanvanderaa - You can access the camera background image either on the CPU or GPU?

For GPU: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/index.html#copying-the-camera-texture-to-a-render-texture-when-accessing-the-camera-image-on-the-gpu

CPU: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/index.html#accessing-the-camera-image-on-the-cpu
