### ISSUE TITLE
Body Tracking with Front Camera

### ISSUE THREAD

**Issue by andreobvio** [Unity-Technologies/arfoundation-samples#1059]
Hello guys! I am developing an app that uses face tracking and I would love to use the body-tracking 2D together. But I could not make it run using the Front camera, is it possible? 

I've tried to make body tracking work with the front camera but without results =/

**Comment by ankur-unity** [comment]
Body tracking is only supported with rear camera. See [ARKit's ARBodyTrackingConfiguration](https://developer.apple.com/documentation/arkit/arbodytrackingconfiguration?language=objc).

**Comment by andreobvio** [comment]
thanks

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
