### ISSUE TITLE
[Bug] Links to image and object tracking manual are broken

### ISSUE THREAD

**Issue by mrwellmann** [Unity-Technologies/arfoundation-samples#1060]
**Describe the bug**
As you don't accept pull request see https://github.com/Unity-Technologies/arfoundation-samples/compare/main...mrwellmann:arfoundation-samples:main

**Comment by andyb-unity** [comment]
Thanks for this report. Will be fixed with the release of AR Foundation 5.1.0-pre.4.

**Comment by andyb-unity** [comment]
The fixed links were released for both AR Foundation 5.1 and 5.0. Thanks again for reporting.
