### ISSUE TITLE
Display captured XRCpuImage

### ISSUE THREAD

**Issue by romanvanderaa** [Unity-Technologies/arfoundation-samples#1062]
I want to capture images, and display them "anchored" to the place where they're taken. My code causes an infinite loop that makes pictures and saves them to gallery, which makes the app freeze. Can someone tell me whats wrong with my code? I've been trying a lot of different things, but i can't figure out why it keeps looping. 

Edit: for some reason part of my code beneath is plain text, and sorry in acvance for the bad code.. I started developing recently!

`public void GetImageAsync()
    {
        Debug.Log("Camera manager state: " + cameraManager.enabled);
        // Get information about the device camera image.
        if (cameraManager.TryAcquireLatestCpuImage(out XRCpuImage image))
        {
            Debug.Log("XRCpuImage format: " + image.format);
            // If successful, launch a coroutine that waits for the image
            // to be ready, then apply it to a texture.
            image.ConvertAsync(new XRCpuImage.ConversionParams
            {
                // Get the full image.
                inputRect = new RectInt(0, 0, image.width, image.height),

                // Downsample by 2.
                outputDimensions = new Vector2Int(image.width / 2, image.height / 2),

                // Color image format.
                outputFormat = TextureFormat.RGB24,

                // Flip across the Y axis.
                transformation = XRCpuImage.Transformation.MirrorX

                // Call ProcessImage when the async operation completes.
            }, ProcessImage);
            // It's safe to dispose the image before the async operation completes.
            image.Dispose();
        }
    }

    bool imageProcessed = false;

    void ProcessImage(XRCpuImage.AsyncConversionStatus status, XRCpuImage.ConversionParams conversionParams, NativeArray<byte> data)
    {

        Debug.Log("ProcessImage running...");

        if (status != XRCpuImage.AsyncConversionStatus.Ready)
        {
            Debug.LogErrorFormat("Async request failed with status {0}", status);
            return;
        }

        Debug.Log("Data: " + data);
        Debug.Log("Status: " + status);
        Debug.Log("Conversion params: " + conversionParams);

        m_Texture = new Texture2D(conversionParams.outputDimensions.x, conversionParams.outputDimensions.y, conversionParams.outputFormat, false);

        Texture2D rotatedTexture = RotateTexture(m_Texture, 315);
        rotatedTexture.LoadRawTextureData(data);
        rotatedTexture.Apply();
        targetByte = rotatedTexture.EncodeToPNG();

        string name = ("Image" + imageCount + ".png"); 

        NativeGallery.SaveImageToGallery(targetByte, "CaptureR", name);
        imageCount++;
        counterText.text = imageCount + "/50";

        imageProcessed = true;

        if(imageProcessed)
        {
            DisplayImage(rotatedTexture);
            Debug.Log("IMAGE SHOULD DISPLAY");
            imageProcessed = false;
        }

        data.Dispose();
    }

    public void DisplayImage(Texture2D texture)
    {
        GameObject quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
        quad.transform.position = Camera.main.transform.position + Camera.main.transform.forward * 2.5f;
        quad.transform.forward = Camera.main.transform.forward;
        quad.transform.localScale = new Vector3(1f, texture.height / (float)texture.width, 1f);
        quad.transform.LookAt(quad.transform.position + camera.transform.rotation * Vector3.forward, camera.transform.rotation * Vector3.up);

        Renderer renderer = quad.GetComponent<Renderer>();
        if (!renderer)
        {
            return;
        }

        Material material = quad.GetComponent<Renderer>().material;
        if (!material.shader.isSupported) // happens when Standard shader is not included in the build
            material.shader = Shader.Find("Legacy Shaders/Diffuse");

        material.mainTexture = texture;
    }

    public byte[] targetByte;
    Texture2D m_Texture;

    private Texture2D RotateTexture(Texture2D texture, float angle)
    {
        // Create a new texture with the same size as the input texture.
        Texture2D rotatedTexture = new Texture2D(texture.width, texture.height, texture.format, false);

        // Calculate the pivot point of the texture.
        float pivotX = 960 * 0.5f;
        float pivotY = 720 * 0.5f;

        // Loop through all the pixels in the texture.
        for (int x = 0; x < texture.width; x++)
        {
            for (int y = 0; y < texture.height; y++)
            {
                // Calculate the angle between the pivot point and the current pixel.
                float rad = Mathf.Atan2(y - pivotY, x - pivotX);

                // Rotate the angle by the specified amount.
                rad += angle * Mathf.Deg2Rad;

                // Calculate the new position of the pixel.
                int rotatedX = Mathf.RoundToInt(pivotX + Mathf.Cos(rad) * (x - pivotX) - Mathf.Sin(rad) * (y - pivotY));
                int rotatedY = Mathf.RoundToInt(pivotY + Mathf.Sin(rad) * (x - pivotX) + Mathf.Cos(rad) * (y - pivotY));

                // If the new position is inside the texture bounds, set the pixel color.
                if (rotatedX >= 0 && rotatedX < texture.width && rotatedY >= 0 && rotatedY < texture.height)
                {
                    rotatedTexture.SetPixel(rotatedX, rotatedY, texture.GetPixel(x, y));
                }
            }
        }

        // Apply the changes to the texture.
        rotatedTexture.Apply();

        return rotatedTexture;

    }`

**Comment by andyb-unity** [comment]
Hi @romanvanderaa,

We can't help you debug your code via GitHub issues. Note our Community and Feedback guidelines:

> The intention of this reposititory is to provide a means for getting started with the features in AR Foundation. The samples are intentionally simplistic with a focus on teaching basic scene setup and APIs. If you you have a question, find a bug, or would like to request a new feature concerning any of the AR Foundation packages or these samples please [submit a GitHub issue](https://github.com/Unity-Technologies/arfoundation-samples/issues). New issues are reviewed regularly.

If the third-party Native Gallery plugin in your project is causing your app to freeze when you save images to the gallery, I encourage you to file an issue with the owner of that repo (which appears to be at this link: https://github.com/yasirkula/UnityNativeGallery/issues).

You are also welcome to post your issue to our AR Forum where other users might be able to help you: https://forum.unity.com/forums/ar.161/

Hope that helps!

**Comment by romanvanderaa** [comment]
Hii @andyb-unity , no sorry I was not aware of that! Thanks for the reply anyways!
