### ISSUE TITLE
[Bug] ARFoundation not full detect plane

### ISSUE THREAD

**Issue by Camper-code** [Unity-Technologies/arfoundation-samples#1067]
[IN-33824](https://unity3d.atlassian.net/servicedesk/customer/portal/2/IN-33824)

1. What happened
ARFoundation ARKit cant detect plane on edge of room

2. How can we reproduce it using the example you attached
Follow next steps:
Open app on IOS device (IPhone 12 Pro)
Go to Plane Detection
Choose Feathered Planes
Try to scan all edges of the room
 - Device: iPhone 12 Pro
 - OS: iOS 16
 - Unity 2021.3.17
 - ARFoundation 4.2.7

**Comment by Camper-code** [comment]
[UUM-29273](https://issuetracker.unity3d.com/issues/ios-arfoundation-arkit-does-not-full-detect-plane-on-iphone-12-pro)

**Comment by ankur-unity** [comment]
We did some investigations and as noted in the bug resolution, the data from AR Foundation reflects the underlying plane data we get from Apple's ARKit Framework. You can see the same behavior when using the ARKit sample from Apple.
https://developer.apple.com/documentation/arkit/content_anchors/tracking_and_visualizing_planes

You will need to get in touch with Apple to get further support on this issue: https://developer.apple.com/forums/tags/arkit
