### ISSUE TITLE
Bring in Onboarding UX from AR Foundation Demos

### ISSUE THREAD

**Issue by ROBYER1** [Unity-Technologies/arfoundation-samples#1071]
**Is your feature request related to a problem? Please describe.**
Bring back the onboarding UX sample from AR Foundation samples to help users have a framework for scanning for the floor/setting up AR first time

**Describe the solution you'd like**
Port the onboarding UX sample from AR Foundation Demos linked below

**Describe alternatives you've considered**
From here: https://github.com/Unity-Technologies/arfoundation-demos#ux

![image](https://user-images.githubusercontent.com/10745594/224060505-fd5dc05b-5e6f-4731-b8d9-9923e3fd3246.png)

**Comment by andyb-unity** [comment]
Thanks for this request. Dan did some great work in the AR Foundation Demos project. We are unable to port this scene into the AR Foundation Samples app at this time, but we are teeing up some significant Samples work for Q3-Q4 of this year that will hopefully address your concerns.

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. We will not port the AR Foundation Demos work into the samples project, but the repo is still available for folks who want to use it. Future announcements related to samples / templates will come from the official Unity blog.
