### ISSUE TITLE
libUnityARKit for Simulator

### ISSUE THREAD

**Issue by NikKovIos** [Unity-Technologies/arfoundation-samples#1076]
Hi)

I build unity for simulator like this:
![telegram-cloud-photo-size-2-5269559899212335613-x](https://user-images.githubusercontent.com/16647690/228754313-46cc97ee-818b-44fb-83e0-663c0cf7bc21.jpg)

And libraries libil2cpp, baselib, libiPhone-lib builded for x86_64 arch. But libUnityARKit.a is still for arm64 arch. And when building to simulator there is an error while linking:

> /Libraries/libUnityARKit.a, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64 

I've found [topic](https://answers.unity.com/questions/1852003/how-to-turn-off-unityarkit-with-ios-simulator-buil.html) with same theme.

Also found that camera is not supported on simulator https://forum.unity.com/threads/symbol-not-found-_unityarkitxrplugin_pluginload.841729/  
It's strange if you make build for simulator and it's not working in simulator.

Question: How to build libUnityARKit for iOS Simulator-x86_64 in order to run it on simulator?

**Comment by andyb-unity** [comment]
Apple does not support ARKit in the iOS simulator, so we don't support our ARKit plugin in the simulator either. (https://developer.apple.com/forums/thread/92311)

**Comment by NikKovIos** [comment]
@andyb-unity 
I just want you to support a mock library when you build to simulator.
Their methods will do nothing, but it would provide availability to build and run unity projects that supports ar - to simulator without any crunches.

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. We do not support this use case.
