### ISSUE TITLE
samples won't compile

### ISSUE THREAD

**Issue by sergiosolorzano** [Unity-Technologies/arfoundation-samples#108]
hey all, 

I can't get to run any samples scene after cloning from git.

I'm using 2019.2.0a9.

Warning: Assembly for Assembly Definition File 'Packages/com.unity.xr.arfoundation/Tests/Runtime/Unity.XR.ARFoundation.Runtime.Tests.asmdef' will not be compiled, because it has no scripts associated with it.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)

Error: Copying assembly from 'Temp/com.unity.multiplayer-hlapi.Runtime.dll' to 'Library/ScriptAssemblies/com.unity.multiplayer-hlapi.Runtime.dll' failed

Any guidance much appreciated.

Thank you for your help, Sergio

**Comment by sergiosolorzano** [comment]
doh, realized it says only compatible with 2018.3, please ignore. Cheers

**Comment by tdmowrer** [comment]
While it's true the samples are only 2018.3 compatible, there is a version of ARFoundation that will work with 2019.1+:

- Version 1.1 of ARFoundation will work with 2019.1+
- The ARCore and ARKit preview packages will work with 2019.1 but not 2019.2a8+. We are working on releasing versions that will.

**Comment by sergiosolorzano** [comment]
Thank you @tdmowrer , 1.1 worked :)
