### ISSUE TITLE
Exporting an application using Unity 2020.3.29f1

### ISSUE THREAD

**Issue by Giorgio-020399** [Unity-Technologies/arfoundation-samples#1080]
Hello everyone, i am a struggling university student. For an AR project we are required to use this specific version of Unity, the version 2020.3.29f1. I am using Mars but every time i try to export the application i get a blank screen on the android phone. (I am using a macbook m1 pro fyi). If someone was willing to help I would be so happy pls help the poor struggling uni student thx!

Attached you can find the list of some issues I get. I already enabled AR core in the XR plug-in management. the rest is gibberish to me.
<img width="1159" alt="Screenshot 2023-05-02 at 23 19 29" src="https://user-images.githubusercontent.com/132404434/235788585-f360a054-1a38-4fa5-bb78-75ad15cf1488.png">

**Comment by andyb-unity** [comment]
This issue is not part of AR Foundation. Please file a bug so that we can get this assigned to the right team: https://unity3d.com/unity/qa/bug-reporting.
