### ISSUE TITLE
[Bug] Using Nature Manufacturer with Unity AR

### ISSUE THREAD

**Issue by Hawaii66** [Unity-Technologies/arfoundation-samples#1087]
**Unity bug report case number**
CASE IN-45372

**Describe the bug**
i have a problem with Unity. I'm building for android which means that the build target is switched to android and building to my android phone. I'm also using the NatureManufacturer package from the unity asset store for some trees. The trees shader compiles at first. When I also download and use Unity AR Foundation package from unity asset store the tree shader stops compiling and gives a vague error about some symbol cant come after another symbol

Error message:
Shader error in 'NatureManufacture Shaders/Trees/Tree_Leaves_Specular': Non system-generated input signature parameter () cannot appear after a system generated value. at line 247 (on gles3)

The error does only appear if you are using Unity AR Foundation and Nature Manufacturer

**To Reproduce**
1. Open a new project using Unity 2021.3.5.f1 (the version I am using)
2. Import this package (https://assetstore.unity.com/packages/3d/vegetation/forest-environment-dynamic-nature-150668)
3. Import the Unity AR Foundation package
4. Switch the build target to Android
5. Try building
6. It doesn't work
7. The error says something about one symbol not being allowed after another symbol

**Expected behavior**
The build works

**Actual behavior**
The build fails

**Smartphone (please complete the following information):**
 - Device: Android phone
 - OS: ?
 - Unity version: 2021.3.5f1
 - ARFoundation version: 4.2.3 - May 02, 2022

**Comment by andyb-unity** [comment]
The source of this error is the asset from the Asset Store, not AR Foundation. I encourage you to reach out to the author of this asset.

**Comment by andyb-unity** [comment]
Closing this as a third-party issue. Feel free to re-open this if you discover any issues from AR Foundation.
