### ISSUE TITLE
Can Unity make a ShaderGraph version of the ARBackground Shader? Please...

### ISSUE THREAD

**Issue by peteski** [Unity-Technologies/arfoundation-samples#1088]
Just wondering if Unity could make a shader graph version of the ARBackground shader?
It would just be really handy to have something like that as a base to modify. 

Thanks, 
Pete

**Comment by andyb-unity** [comment]
Hi @peteski,

This is a nice suggestion, but unfortunately not something that we are able to prioritize at this time. If a member of the community makes a shader like this please let us know!
