### ISSUE TITLE
[Bug] [IN-47249] No XR platforms included in ubuntu command line build

### ISSUE THREAD

**Issue by camnewnham** [Unity-Technologies/arfoundation-samples#1090]
**Unity bug report case number**
IN-47249

**Describe the bug**
Building on unbutu CI results in ARCore not being loaded, no permissions requested, and a black screen.
There is no mention of ARPresto in the android logs, and no ARSession is loaded.

**To Reproduce**
Run an ubuntu build on github actions for the [attached basic project](https://github.com/camnewnham/unity-ubuntu-ci-repro), or alternatively [I have these publicly available here](https://github.com/camnewnham/unity-ubuntu-ci-repro/actions/runs/5515423858).
Sideload the APK artifact. 

**Expected behavior**
Back camera feed is displayed, XRSession is normally initialized

**Actual behavior**
Black screen, no reference of arPresto in the logs. Build is ~15mb smaller than a normal build.

**Smartphone**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Unity version: 2022.3.4f1
 - ARFoundation version: 5.0.6

**Other Notes**
Manually including the XR related preloaded assets (shaders, XRGeneralSettings, etc.)  in source control (ProjectSettings) resolves the issue (but then building for iOS doesn't work, or visa versa with iOS preloaded assets)

Context: https://forum.unity.com/threads/issue-with-android-skipped-rendering-frame-because-gfxdevice-is-in-invalid-state-device-lost.1449145/#post-9136096

**Comment by camnewnham** [comment]
Temporary workarounds for anyone coming across this issue: Create a separate branch for iOS and Android, containing the platform-specific preloaded assets in ProjectSettings. Use these branches in your ubuntu-based CI.

From the build log, it actually looks like the build preprocessor (`IPreProcessBuild`) is not being called at all.

**Comment by camnewnham** [comment]
Confirming that `IPreprocessBuildWithReport` is not running. https://github.com/camnewnham/unity-ubuntu-ci-repro/actions/runs/5550212286/jobs/10135097037

**Comment by cjwills** [comment]
I looked at the example project and the issue was that ARCore was not enabled in XR Plug-in Management.  After enabling it I got a working apk from the github action CI.

Please let us know if this is still an issue for you.
