### ISSUE TITLE
Vulkan rendering support timeline

### ISSUE THREAD

**Issue by AdamBursill-SV** [Unity-Technologies/arfoundation-samples#1092]
ARCore SDK added support for rendering via Vulkan in 1.37. Is Unity planning on supporting this so we can finally target Vulkan on Android when using ARFoundation? And is there a timeline for this support?

Cheers

**Comment by andyb-unity** [comment]
We are currently working on it. No timeline to share at this time.

**Comment by ankur-unity** [comment]
https://forum.unity.com/threads/vulkan-and-arcore.1440505/#post-9047053

**Comment by andyb-unity** [comment]
Hi all,

I'm happy to share that Unity has revamped our XR roadmaps: https://unity.com/roadmap/unity-platform/arvr.

You'll note that ARCore Vulkan support is one of the issues on the AR Foundation road map, and you can vote on the issue to receive notifications, as well as create new issues. The new road map site is our official feature request tool, so I'm closing this issue accordingly.
