### ISSUE TITLE
[Bug] Assets/Scripts/MakeAppearOnPlane.cs(43,37): error CS1061: 'ARSessionOrigin' does not contain a definition for 'MakeContentAppearAt' and no accessible extension method 'MakeContentAppearAt' accepting a first argument of type 'ARSessionOrigin' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by clearsitedesigns** [Unity-Technologies/arfoundation-samples#1093]
The main seen in ARFoundation testing with unity latest foundation, This was a fresh setup.

1. Load up the project in AR 2023.2 
2. Open SIMPLE AR scene, 

error occurs:

m_SessionOrigin.MakeContentAppearAt(content, hitPose.position, m_Rotation);

**Comment by andyb-unity** [comment]
Hi @clearsitedesigns, `ARSessionOrigin` was deprecated in AR Foundation 5.0. We now use the new `XROrigin` as our origin type in AR Foundation 5.0 and newer. The minimum version of AR Foundation in Unity 2023.2 is 5.0, so if you are upgrading a project from AR Foundation 4.2, you must upgrade your scenes as well.

More information available here: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/version-history/migration-guide-5-x.html

The `main` and `5.0` branches of this repo are compatible with Unity 2023.2, but note also that TextMeshPro has been recently deprecated and its contents have been merged into `com.unity.ugui` version 2.0. To use this repo in its current state in Unity 2023.2, you must re-import the TextMeshPro Essentials when prompted. (The prompt appears when you open any scene that uses TextMeshPro, such as `Menu`).

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.

**Comment by WANHEDA666** [comment]
Can't follow guide bc https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/XROriginExtensions.cs is missing please help

**Comment by andyb-unity** [comment]
Thanks for the reminder to update the docs. The file is still there; it's just been moved to a new directory. https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/Runtime/XROriginExtensions.cs
