### ISSUE TITLE
Assets\arfoundation-samples-main\Assets\Scripts\Runtime\UI\Requirements\RequiresCamera.cs(63,51): error CS1061: 'XRCameraSubsystemDescriptor' does not contain a definition for 'supportsExifData' and no accessible extension method 'supportsExifData' accepting a first argument of type 'XRCameraSubsystemDescriptor' could be found (are you missing a using directive or an assembly reference?)[Bug]

### ISSUE THREAD

**Issue by mirror-own** [Unity-Technologies/arfoundation-samples#1094]
Assets\arfoundation-samples-main\Assets\Scripts\Runtime\UI\Requirements\RequiresCamera.cs(63,51): error CS1061: 'XRCameraSubsystemDescriptor' does not contain a definition for 'supportsExifData' and no accessible extension method 'supportsExifData' accepting a first argument of type 'XRCameraSubsystemDescriptor' could be found (are you missing a using directive or an assembly reference?)

**Comment by tdmowrer** [comment]
The path suggests that you cloned this repo into an existing project. This repo is a standalone Unity project meant to demonstrate the AR Foundation packages.

If you want to check out these samples, clone this repo, and open it as a separate Unity project. If you want to import AR Foundation into an existing project, do so via the package manager.

**Comment by andyb-unity** [comment]
@mirror-own It sounds like you are using the main branch of this repository with an older version of AR Foundation. `supportsExifData` was added in AR Foundation 5.1. If you are looking for samples that are compatible with AR Foundation 5.0 or 4.2, use the corresponding branch of this repo.

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
