### ISSUE TITLE
Image Tracking with different colour not working with AR kit

### ISSUE THREAD

**Issue by nextechar-hardik** [Unity-Technologies/arfoundation-samples#1095]
I am using Unity 2021.3.17 with AR Foundation latest version. I am using Image tracking functionality and adding Image runtime. 
After that I am trying to scan same image with same colour working fine. but if I am changing colour its not working fine. 

1. Create Sample project with AR Foundation image tracking and add QR code as Texture
2. Print that QR code as it is, and print same QR code with different colour no style change only colour change black to red 
3. Try to scan and check behaviour
4. Working fine in Android but not working in iOS

**Expected behavior**
Image tracking should work even we change colour and marker should trigger as found for both case. 

**Actual behavior**
Able to scan Black and White marker but not able to scan Color one.

 - Device: iPhone XR and almost on all iPhone including tab
 - OS: 16.6
 - Unity version 2023.3.17
 - ARFoundation version 5.1.0 (Pre 4)

![jolokia-domain 2 (1)](https://github.com/Unity-Technologies/arfoundation-samples/assets/105841943/465a730f-73be-45cf-b7f5-1fdcbd869ed2)
![jolokia-domain 2](https://github.com/Unity-Technologies/arfoundation-samples/assets/105841943/f5223bb7-3498-4b2a-9081-6d57045a39b8)

**Comment by andyb-unity** [comment]
Changing the color of an image constitutes a change in the image. AR Foundation does not do any image processing-- we just pass the textures to ARCore or ARKit. I'm not surprised that Apple does not recognize this as the same image. It is in fact a different image.

**Comment by nextechar-hardik** [comment]
I was thinking Image tracking dose not recognise colour  its work on grey scale image or on base of feature point. so if we use Colour or Black and white it same for AR Core and AR kit.

**Comment by andyb-unity** [comment]
ARCore does not use color information: https://developers.google.com/ar/develop/augmented-images#best_practices

ARKit's image tracking algorithm, however, does use color. Unfortunately it appears that Apple has taken down their video "What's new in ARKit 2", but you can find a summary of the points at this blog: https://nilotic.github.io/2018/08/13/Understanding-ARKit-Tracking-and-Detection.html

Note that ARKit tracks images best if they have the following characteristics:

* High texture
* High local constrast
* Well distributed histogram (color)
* No repetitive structures

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
