### ISSUE TITLE
Correct ARSessionState

### ISSUE THREAD

**Issue by i-vakula** [Unity-Technologies/arfoundation-samples#1099]
How do I get correct ARSessionState?

At my low-lvl device I use ARSession.CheckAvailability() and get ARSessionState.NeedsInstall.
Calling ARSession.Install() leads me to Google ARCore services page at play store, but I cannot update services, because "Device isn`t compatible".
So, how can I get correct  ARSessionState.Unsupported state?

**Comment by andyb-unity** [comment]
If you are sideloading your app onto an incompatible device, you'll never see ARSessionState.Unsupported. ARCore assumes by virtue of not being able to download the app from Google Play Store that your app would never run on this device, and does not check for unsupported in this case.

**Comment by i-vakula** [comment]
Ok. Thanks for answer)
