### ISSUE TITLE
Plane type detection

### ISSUE THREAD

**Issue by azoff15** [Unity-Technologies/arfoundation-samples#11]
Hi guys! How can I change plane detection (horizontal, vertical, both or none)?

**Comment by timm-unity** [comment]
Plane detection is either off or on. When on, it's both vertical and horizontal. We don't currently expose a way to only do horizontal detection. An ranked ARPlaneManager turns plane detection on. Disabling it turns it off.

**Comment by tdmowrer** [comment]
Support for specifying horizontal vs vertical was added in [1.0.0-preview.21](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/changelog/CHANGELOG.html#100-preview21---2018-12-13).

**Comment by ArCoreDxb** [comment]
Hi , Just a question , 

Can't we dynamically change the detection from vertical to horizontal and vice versa through code in ARFoundation ? I mean why only to be able to set in the property panel.

Plus, currently I'm building app which is doing vertical and horizontal detection , able to augment objects on detected planes BUT tracking both horizontal and vertical is causing issues , like the objects move away from their original location. 

This doesn't seem to be typical normal behavior. any help??

**Comment by tdmowrer** [comment]
> Can't we dynamically change the detection from vertical to horizontal and vice versa through code in ARFoundation ?

Sure. The [`ARPlaneManager` API](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARPlaneManager.html#UnityEngine_XR_ARFoundation_ARPlaneManager_detectionMode) lets you do this.

> Plus, currently I'm building app which is doing vertical and horizontal detection , able to augment objects on detected planes BUT tracking both horizontal and vertical is causing issues , like the objects move away from their original location.

I need more information to diagnose a problem like that. Please [log a bug](https://unity3d.com/unity/qa/bug-reporting) with a project that reproduces the problem.

**Comment by ArCoreDxb** [comment]
> > Can't we dynamically change the detection from vertical to horizontal and vice versa through code in ARFoundation ?
> 
> Sure. The [`ARPlaneManager` API](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARPlaneManager.html#UnityEngine_XR_ARFoundation_ARPlaneManager_detectionMode) lets you do this.
> 
> > Plus, currently I'm building app which is doing vertical and horizontal detection , able to augment objects on detected planes BUT tracking both horizontal and vertical is causing issues , like the objects move away from their original location.
> 
> I need more information to diagnose a problem like that. Please [log a bug](https://unity3d.com/unity/qa/bug-reporting) with a project that reproduces the problem.

Thanks for the reply.

Can a sample code or atleast bear minimum few code lines would really help. At the moment I'm not sure how to use this planedetection mode in my code.

Suppose I want to change it to any mode type , how will I use this property.

Really and seriously appreciate your help in this.

**Comment by tdmowrer** [comment]
Here's an example for how you might change the plane detection mode at runtime from a MonoBehaviour:

```csharp
public ARPlaneManager planeManager;
void OnGUI()
{
    if (GUILayout.Button("Enable Horizontal"))
    {
        planeManager.detectionMode |= PlaneDetectionMode.Horizontal;
    }

    if (GUILayout.Button("Enable Vertical"))
    {
        planeManager.detectionMode |= PlaneDetectionMode.Vertical;
    }

    if (GUILayout.Button($"{(planeManager.enabled ? "Disable" : "Enable")} plane detection"))
    {
        // toggle plane detection
        planeManager.enabled = !planeManager.enabled;
    }
}
```
