### ISSUE TITLE
Does android devices support Plane Classification?

### ISSUE THREAD

**Issue by tonyabracadabra** [Unity-Technologies/arfoundation-samples#1102]
I can find the documentation on plane classification in ARKit but not in ARCore so I’m concerned…

**Comment by andyb-unity** [comment]
ARCore does not support plane classification. You can check for this at runtime on any device by reading `ARPlaneManager.descriptor.supportsClassification`:

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/api/UnityEngine.XR.ARSubsystems.XRPlaneSubsystemDescriptor.html#UnityEngine_XR_ARSubsystems_XRPlaneSubsystemDescriptor_supportsClassification

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
