### ISSUE TITLE
How to spawn just one object and have it selected always using XR Interaction Toolkit 2.5.1

### ISSUE THREAD

**Issue by ROBYER1** [Unity-Technologies/arfoundation-samples#1104]
Using XR Interaction Toolkit 2.5.1 AR Starter Assets , how do I just spawn one object and have it selected by default always (even if the user taps off of it) - the scenario for this is a simple AR product viewer app for one product where the user scans the floor, taps to place the object then is able to quickly rotate/scale/move the object.

There is no requirement to spawn multiple objects which is what the XRI 2.5.1 AR Starter Assets AR Demo Scene does.

I was trying to use a workaround suggested here which was for AR Foundation, but these new XRI 2.5.1 components are mostly very different and I can't find a way to automatically select and force the selection of a single spawned AR Object?
https://forum.unity.com/threads/how-to-place-object-with-ar-select-interactor-in-a-selected-state.1316028/#post-8338452

I also posted on the Unity forum about this here, in case there is a reply in only one place https://forum.unity.com/threads/how-to-spawn-just-one-object-and-have-it-selected-always-using-xr-interaction-toolkit-2-5-1.1496339/

**Comment by andyb-unity** [comment]
Hi there @ROBYER1, the XRI team does not monitor our GitHub issues over here. Thanks for posting in the XRI forum-- that's the best way to reach them. Let us know if your post lingers too long and we can help summon them, but they do monitor their forum and should get back to you.

**Comment by andyb-unity** [comment]
Closing this issue as answered by the XRI team in their forum: https://forum.unity.com/threads/how-to-spawn-just-one-object-and-have-it-selected-always-using-xr-interaction-toolkit-2-5-1.1496339/#post-9371894
