### ISSUE TITLE
[Bug] Flickering on AROcclusionManager Human Occlusion, when virtual asset is too complex

### ISSUE THREAD

**Issue by dganzella** [Unity-Technologies/arfoundation-samples#1109]
**Unity bug report case number**
CASE IN-56139 and CASE IN-56140

(its duplicated because the first has more data but crashed the uploader so I didn't know if it was sent, but now I received two emails)

**Describe the bug**
Human Segmentation provided by AROcclusionManager seem to be flickering, if there is an asset behind that has too many vertices.

**To Reproduce**
Create an AROcclusionManager with human occlusion on, Environment occlusion off,  and add a big asset with many vertices and triangles.

**Expected behavior**
Human Should not be flickering.

**Actual behavior**
Human is flickering.

**Smartphone :**
 - Device: Both Iphone 12 pro, 14 pro and 15 pro
 - OS: iOS 17
 - Unity version - 2023.1.10f
 - ARFoundation version - Both on 5.1.0 and on 6.0.0-pre.3

Video:

https://github.com/Unity-Technologies/arfoundation-samples/assets/30127664/63593f52-3847-4bf5-99fd-122ca76c50f7

**Comment by dganzella** [comment]
hey @andyb-unity I think this was fixed.

i dont know if it was arkit 5.1.1 or maybe ios 17.1.2, but something fixed it, it does not happen anymore

**Comment by andyb-unity** [comment]
Hm, an iOS fix I would guess. I don't think we've changed anything about iOS Occlusion for a year or more. Feel free to re-open this issue if you see this issue pop up again.
