### ISSUE TITLE
[Bug] Bool - Exclude UI Touches (AR foundation 5.0, Unity 2022.3.4f1)

### ISSUE THREAD

**Issue by HonzaFuri** [Unity-Technologies/arfoundation-samples#1110]
**Describe the bug**
Exclude UI Touches doest work in AR placement Interactable  ( Interaction sample (AR foundation 5.0)

I cannot figure out how to ignore touches on UI by using Exclude UI Touches in AR Placement Interactable,
If I open my app and touch the UI element for first time I will instantiated prefab  If I press UI second time i do not instantiated.. seems to be work properly only on second UI touch.
The first tap on screen will instantiate prefab and I can't be block. Also If you select and diselect  the object you can instantiate prefab on "blocked UI"

**Comment by HonzaFuri** [comment]
So I found out that UI blocking works well the problem was coming from setting prefab into placementPrefab. If I touch UI button whitch replace current placementPrefab I also instantiate this prefab.

**Comment by HonzaFuri** [comment]
I fixed that by overriding CanStartManipulationForGesture in ARPlacementInteractable. 

`protected override bool CanStartManipulationForGesture(TapGesture gesture)
    {
        if (gesture.startPosition.IsPointOverUIObject())
        {
            return false;
        }
        
        if (gesture.targetObject == null || gesture.targetObject.layer == 9)
            return true;

        return false;
    }` 

` public static bool IsPointOverUIObject(this Vector2 pos)
   {
      PointerEventData eventDataCurrentPosition = new PointerEventData(EventSystem.current);
      eventDataCurrentPosition.position = new Vector2(pos.x, pos.y);
      
      List<RaycastResult> results = new List<RaycastResult>();
      EventSystem.current.RaycastAll(eventDataCurrentPosition, results);
      return results.Count > 0;
   }`

**Comment by andyb-unity** [comment]
Closing this issue as the code in question is not part of AR Foundation. For questions about XR Interaction Toolkit, you can reach out on their forums: https://forum.unity.com/forums/xr-interaction-toolkit-and-input.519/
