### ISSUE TITLE
Build it to Windows

### ISSUE THREAD

**Issue by AndreScapinelli** [Unity-Technologies/arfoundation-samples#1112]
How do I...

Hey guys, can I build an AR foundation face tracking, and image tracking on a windows build?

**Comment by andyb-unity** [comment]
No. You can find the list of supported platforms in our docs: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/index.html#platform-support

Microsoft supports AR Foundation for HoloLens on the Universal Windows Platform, but Windows is not supported as a target platform. (Microsoft does not have an AR Framework for Windows that we could use even if we wanted to.)

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
