### ISSUE TITLE
Blackscreen when exporting AR Foundation project to Android Studio

### ISSUE THREAD

**Issue by JonFaull** [Unity-Technologies/arfoundation-samples#1114]
I have a big project that uses AR Foundation that is exported to a native Android Studio parent app and run from there. I have been updating it from Unity 2019 to Unity 2022.3.11f1. I have it all working when I build it directly to an APK from Unity but when I export it I get a black screen when launched from Android Studio. I have the other non AR parts working from Android Studio but can not get AR Core on Android to render the room around me. I have the camera permissions working and have everything as it was before but just not getting anything. It worked fine with Unity 2019 but nothing now. I have AR Core selected in the unity settings. 

Any ideas?

**Comment by andyb-unity** [comment]
I responded to you on the forums. Let's keep this conversation over there: https://forum.unity.com/threads/black-screen-in-ar-foundation-when-exported-and-launched-with-android-studio.1508957/#post-9429356

**Comment by andyb-unity** [comment]
Closing this as you reported the issue as resolved on the forums. Feel free to re-open this issue if you have further issues.
