### ISSUE TITLE
[Bug, github] Discrepancy in Alpha / Beta in repo 

### ISSUE THREAD

**Issue by wes-kay** [Unity-Technologies/arfoundation-samples#1115]
With the https://github.com/Unity-Technologies/arfoundation-samples#which-version-should-i-use

There seems to be a discrepancy between what is said to be [6.0](https://github.com/Unity-Technologies/arfoundation-samples/tree/6.0) and what is actually [5.1](https://github.com/Unity-Technologies/arfoundation-samples/tree/5.1)

I have Alpha installed, but it's saying I need Beta from the current main repo

![Screenshot_9](https://github.com/Unity-Technologies/arfoundation-samples/assets/40011470/470e9403-50c7-4d96-adda-daa7defbcd03)

**Comment by andyb-unity** [comment]
The table of contents in this repo is simply a recommendation of which AR Foundation version to use for a given version of Unity. Currently we are developing AR Foundation 6.0 (which is in pre-release) using the 2023.2 beta, which is why you see this when you open the project. When AR Foundation 6 is officially released, it will be the official version of AR Foundation for Unity 2023.3 (which is currently in alpha). Hope that helps.

**Comment by wes-kay** [comment]
> The table of contents in this repo is simply a recommendation of which AR Foundation version to use for a given version of Unity. Currently we are developing AR Foundation 6.0 (which is in pre-release) using the 2023.2 beta, which is why you see this when you open the project. When AR Foundation 6 is officially released, it will be the official version of AR Foundation for Unity 2023.3 (which is currently in alpha). Hope that helps.

Okay thank you, to confirm is there a reason I would go with 2023 over 2021 in the case of OpenXR? IF I understand this correctly 2021 only supports 4.2?
![image](https://github.com/Unity-Technologies/arfoundation-samples/assets/40011470/57e988a7-edc8-462f-9096-2a3fee685733)

**Comment by andyb-unity** [comment]
AR Foundation 4.2 is the verified package version for Unity 2021. While not verified, you can install AR Foundation 5.1 in Unity 2021 as we explain here: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/project-setup/edit-your-project-manifest.html.

OpenXR has no bearing on Editor selection. You would need to be more specific about which devices you intend to target via OpenXR, as each device may require additional packages which would then have an impact on Editor selection.

For example, our Unity OpenXR: Meta package requires Unity 2022.3 or newer as noted here: https://docs.unity3d.com/Packages/com.unity.xr.meta-openxr@1.0/manual/index.html#requirements

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
