### ISSUE TITLE
Switch from normal to wide-angle camera from the AR app

### ISSUE THREAD

**Issue by rroy-viewrail** [Unity-Technologies/arfoundation-samples#1119]
How do I... activate the wide-angle camera from the app to view the AR models? I am using AR Foundation 4.2.9

**Comment by andyb-unity** [comment]
There are no AR Foundation platforms that allow you to change between multiple cameras in a single facing-direction. You can change between user-facing and world-facing camera, but that's all you can do within the scope of an AR app. There is no ability at the platform level to "activate the wide-angle camera", so there's nothing Unity can do here.

**Comment by rroy-viewrail** [comment]
Understood! Thank you for the detailed response. I really appreciate it!
