### ISSUE TITLE
AR Tracking is slow

### ISSUE THREAD

**Issue by Tostifrosti** [Unity-Technologies/arfoundation-samples#112]
I've noticed that the tracking in Unity AR Foundation on Android is slow. Slower compared to iOS or ARCore/SceneForm. At first I thought that I've messed something up in my app, but the slow tracking seems to also happen in AR Foundation Samples. I've used AR Foundation for a while now and I remember that the tracking was way better compared to the latest release. Do you guys also experience this problem? Is there any solution/quick fix?

**Comment by interactivespace** [comment]
I have the same problem.
https://issuetracker.unity3d.com/issues/ar-android-arfoundation-noticeable-tracking-lag-on-android-devices

Does anyone has a workaround?

**Comment by Soorya-S** [comment]
I'm also facing the same issue.

**Comment by interactivespace** [comment]
Does this is still a problem with [ARFoundation 2.1](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.1/manual/index.html)? 

To work on with the project we had to downgrade the Unity Version to 2018.3.4f1

**Comment by Soorya-S** [comment]
Yes. I'm using unity 2019.1.2f1 and ARFoundation 2.1.
Does it work properly on 2018.3.4f1?

**Comment by interactivespace** [comment]
> Yes. I'm using unity 2019.1.2f1 and ARFoundation 2.1.
> Does it work properly on 2018.3.4f1?

I can only confirm ARFoundation v1. We also toggled in a script the UpdateType of the TrackedPoseDriver between BeforeRender and UpdateAndBeforeRender because of jittering during positioning an object. Next week I will check ARFoundation 2.1. 

When using the [ ARCore 1.9 Plugin ](https://github.com/google-ar/arcore-unity-sdk/releases)from Google in Unity 2019.1.0f2 the problem didn't occured

`poseDriver.updateType = TrackedPoseDriver.UpdateType.UpdateAndBeforeRender;`


![image](https://user-images.githubusercontent.com/16004009/57925804-c74c8e00-78a9-11e9-8971-6ea67b9b1095.png)

**Comment by Tostifrosti** [comment]
I've just upgraded to AR Foundation 2.1 and the tracking is waaaay better now.
I didn't know of the existence of the 2.1 version, before I posted this issue.

(Tested latest AR Foundation Samples on Samsung Galaxy S8)

**Comment by Soorya-S** [comment]
@Tostifrosti Thanks for the response.

But I have a strange issue in ARFoundation.

The detected plane is not stable. But, when I place the object above the plane (maybe +0.01 units) the object is stable but the plane is not. When I place the object over the plane or below the plane both the object and plane are not stable.
And, also the plane is not over the surface, it is raised a little bit from the surface.
Note: I'm not attaching the object with the plane, I'm using the plane to get the proper rotation.
I'hv tested my project in both unity 2018.3.x and in 2019.2.x
I'm using the latest version of ARCore and ARFoundation plugin. Still facing the issue.

Also, see this link [https://forum.unity.com/threads/arfoundation-place-on-plane-unstable.568270/](url) which is similar to my problem.
Let me know if you have any idea to fix this.

Thanks again!.

**Comment by Tostifrosti** [comment]
@Soorya-S Your issue does sound very strange indeed.
I'm not sure what you mean with 'stable'. If you mean that there is a small jittering going on, than you might want to check this issue: [jittering bug](https://github.com/google-ar/arcore-unity-sdk/issues/355) going on in ARCore.

If this is not the case, try building the AR Foundation Samples project and see if this 'stable' issue still persists. If not, checkout the code on how they place objects.

If the project seems laggy, try setting the fps to 60 using: `Application.targetFrameRate = 60;`

Also, you may want to check out the 2019.1.3 build as the 2019.2.x is still in beta.

**Comment by Tostifrosti** [comment]
I'm closing this issue as the problems described in the description are resolved.
