### ISSUE TITLE
mdrajak043@gmail.com

### ISSUE THREAD

**Issue by mdRaja987** [Unity-Technologies/arfoundation-samples#1125]
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13]
 - Unity version
 - ARFoundation version

**Comment by andyb-unity** [comment]
Closing this issue as you haven't reported anything.

**Comment by mdRaja987** [comment]
200000..Ok, thanks for the update.
