### ISSUE TITLE
[2019.2] Verified package and extensions package for 2.0.2

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/arfoundation-samples#113]
I have a couple of questions:
1-Will the samples be "ported" to the verified ar foundation package (foundation 2.0.2 for 2019.2+)
2-Where's the extensions package? Where's the CameraImageApi for the verified package? I see there's a `#if CAMERA_EXTENSIONS` defines in arcore/arkit packages, so I'm assuming the extensions package would be the one defining `CAMERA_EXTENSIONS`, but I don't see such package.

Thanks

**Comment by iBicha** [comment]
Ok I see https://github.com/Unity-Technologies/arfoundation-samples/commit/0b8fac368b088a15ef5a0105441e6c0a62ddec44 `Remove (temporarily) unsupported samples` so this is being redone I guess.

**Comment by shawmakesmusic** [comment]
@iBicha We were able to download the ARExtensions preview-8 package by Googling, although it's also available by manually entering the package into your manifest.json and adding staging url.
We had to fix a couple namespaces for casting, but everything seems to be working, GetNativePtrs and all :)

**Comment by tdmowrer** [comment]
@shawnmakesmusic ARExtensions is no longer necessary in ARFoundation 2.1 -- it was only ever a dependency of some other packages and you should never have needed to manually do anything with it.

**Comment by shawmakesmusic** [comment]
> @shawnmakesmusic ARExtensions is no longer necessary in ARFoundation 2.1 -- it was only ever a dependency of some other packages and you should never have needed to manually do anything with it.

... But that doesn't seem to be the case. I tried it in a blank project and in my current working project. The dependency isn't getting pulled in, doesn't exist in my cache and I have no access to any of the extensions or namespace unless I explicitly put it in my project. Once I dropped them in my project, I got access to the extensions again. I'm on latest 2019.2 beta, using 2.1-preview.

**Comment by shawmakesmusic** [comment]
> @shawnmakesmusic ARExtensions is no longer necessary in ARFoundation 2.1 -- it was only ever a dependency of some other packages and you should never have needed to manually do anything with it.

I think the problem here is that the documentation link for 2.1 is wrong / nonexistant, so we're all just guessing how this new functionality works. There's probably a #define or something, but since the documentation link is broken, I'm shooting in the dark :)

**Comment by tdmowrer** [comment]
You don't see it as a dependency because it isn't a dependency anymore. The extensions that were in ARExtensions are now simply part of the ARFoundation API, including the native pointers. See [ARPlane.nativePtr](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.0/api/UnityEngine.XR.ARFoundation.ARPlane.html#UnityEngine_XR_ARFoundation_ARPlane_nativePtr) for example.

**Comment by tdmowrer** [comment]
The documentation should have been published yesterday. I'll see what's going on. 2.0 is a subset of the 2.1 functionality, so you can find _some_ documentation there.

**Comment by shawmakesmusic** [comment]
ARPlane.nativePtr literally doesn't exist in a vanilla project with the
packages installed :-/
I'm going to try again, but if ya'll could please make sure the
documentation link posted with the release works, that would give us a
fighting chance of actually figuring this stuff out.

**Comment by tdmowrer** [comment]
The following compiles for me in 2019.1.1f1 when added to the `master` branch of this repo:

```
using UnityEngine;
using UnityEngine.XR.ARFoundation;

[RequireComponent(typeof(ARPlane))]
public class PlaneTest : MonoBehaviour
{
    void Update()
    {
        var plane = GetComponent<ARPlane>();
        Debug.Log($"Native pointer => {plane.nativePtr}");
    }
}
```

**Comment by iBicha** [comment]
@tdmowrer thank you for the clarification, I'm closing this issue since the `2.1-preview` branch works (and answers these questions)
Feel free to reopen if this issue is still relevant.
