### ISSUE TITLE
How to enable see-through AR for Quest 3

### ISSUE THREAD

**Issue by HanaaFariz** [Unity-Technologies/arfoundation-samples#1130]
I see that the Main Camera has a solid transparent background. How to display the camera feed instead?
Thanks,

**Comment by andyb-unity** [comment]
Refer to the docs: https://docs.unity3d.com/Packages/com.unity.xr.meta-openxr@1.0/manual/project-setup.html#camera-clear-flags

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.
