### ISSUE TITLE
Dynamic Quest plane detection

### ISSUE THREAD

**Issue by DairexLord1** [Unity-Technologies/arfoundation-samples#1135]
I am developing AR Quest app
I want to implement plane detection mechanics as in game :
<img width="218" alt="Снимок экрана 2023-12-22 в 14 34 47" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/9141f903-d2a7-4236-b4dd-976c3cd2a4da">

How to detect planes without setting  Room Setup in Quest ?  
Is there the way also to detect dynamic objects and create planes for them ?

**Comment by tdmowrer** [comment]
Quest does not support realtime plane _detection_ (and neither does First Encounters) but the ARPlaneManager will manage planes created during Space Setup.

What aspect of First Encounter that appears to use plane detection are you trying to replicate?

**Comment by DairexLord1** [comment]
I an trying to create both Ar project for mobile phones, Meta and Apple vision and the one of main points is to put objects on real world planes and dynamic objects, If i understood correct, only preseted in Oculus environment data can be processed in ar foundation?

**Comment by DairexLord1** [comment]
In  meta (first encounters game) it looks like planes are created from scanned in real time objects

**Comment by tdmowrer** [comment]
AR Foundation provides access to whatever plane data is available. On Quest, planes are defined during Space Setup. On mobile, planes are detected while the app is running.

First Encounters also requires the user to perform Space Setup. However, it makes use of the mesh, which allows for more complex uses of the environment. The mesh produced during Space Setup is not yet available in AR Foundation.

**Comment by andyb-unity** [comment]
@tdmowrer is exactly correct. You can vote on Quest Meshing Support in Unity's [XR Roadmap](https://unity.com/roadmap/unity-platform/xr) in the AR Foundation tab. This work is currently planned for next year.

I'm closing this issue as asked and answered, but feel free to re-open it if you have further questions.
