### ISSUE TITLE
How to manually define feature points / planes

### ISSUE THREAD

**Issue by ABHIJEET-SRIDHAR-M** [Unity-Technologies/arfoundation-samples#1137]
I am trying to put some sort of Anchor on vertical walls where the detection is not so good. Can I manually use buttons to record device position (mainCam.position) and provide it to ARPlaneManager or somewhere where it could start tracking/understanding the wall boundaries? I can get the device position fairly accurately, and capture the positions of the 4 points on the wall, but am not sure how to make them trackable. I just need a way to manually define a TrackableType.FeaturePoint or TrackableType.PlaneWithinPolygon with the coordinates and/or rotations.

**Comment by andyb-unity** [comment]
AR Foundation is a cross-platform wrapper for platform AR API's such as ARCore, ARKit, and the Meta OpenXR runtime. None of these platforms allow you to define your own planes-- their purpose is to detect and track planes using computer vision. You could of course implement your own plane tracking solution, which is what you are asking, but this is outside the scope of AR Foundation. Unity cannot offer you any guidance in this.

I'm going to close this issue as asked and answered, but feel free to re-open it if you have further questions.

**Comment by andyb-unity** [comment]
The category of feature that you are asking about is generally called "persistent anchors". Currently there is no AR Foundation API for persistent anchors, but we are currently designing one for release later next year.

For now you have to use platform implementations directly.

On ARCore, it's Google Cloud Anchors, which you can access via ARCore Extensions: https://developers.google.com/ar/develop/unity-arf/getting-started-extensions

ARKit has a feature called ARWorldMap that has a similar purpose. There is an ARWorldMap sample in this repo.

**Comment by andyb-unity** [comment]
Note that persistent anchors still require that the app can successfully track the space. Empty rooms with monocolored walls are famously difficult to track.
