### ISSUE TITLE
Crash on Oculus IN-64517 

### ISSUE THREAD

**Issue by DairexLord1** [Unity-Technologies/arfoundation-samples#1138]
IN-64517 - Crash bug on Oculus with animated model and plane manager

After second launch of app on Oculus2/3 app crashes and close

**To Reproduce**
1. Create unity (2022.3.16f) 3d project 
2. Add Ar/foundation, Meta xr, xr interaction toolkit 
3. Validate android build 
4. Use SimpleAr sample, 
5. Add animated  zombie character (https://assetstore.unity.com/packages/3d/characters/humanoids/zombie-30232)
6. Build and run on device 

**Expected behavior**
Mr android app with character for Oculus  (passthrough, interaction)

**Actual behavior**
On first run on Oculus2/3 all works, on second run app starts freeze for 2 - 3 seconds at the moment of character with animator appears and crashes (close)

**Smartphone (please complete the following information):**
 - Oculus 2/3
 - Android
 - Unity 2022.3.16
 - ARFoundation version 5.1.1
 - Ar foundation samples version 5.1 (from table)
  
<img width="359" alt="Снимок экрана 2023-12-28 в 11 06 31" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/c57321d3-32c7-4c1a-8f24-4413abea4c5e">
<img width="1098" alt="Снимок экрана 2023-12-27 в 15 27 44" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/d282340e-1f73-4bd5-9051-2f349ca801f5">
<img width="1091" alt="Снимок экрана 2023-12-27 в 15 27 27" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/49b5ef50-db45-4afc-9318-745198010d3b">
<img width="242" alt="Снимок экрана 2023-12-27 в 15 26 53" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/864a5369-b9d5-459d-a9e0-d87d65df875c">
<img width="702" alt="Снимок экрана 2023-12-27 в 15 26 16" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/7a2b7112-73c9-4486-b6dd-020a94c9ccf9">
<img width="407" alt="Снимок экрана 2023-12-28 в 11 08 35" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/0819ab66-6e81-4d9a-9eb0-5fe5d687e3ac">
<img width="408" alt="Снимок экрана 2023-12-28 в 11 08 44" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/33495809/e24347cb-9e42-4ec0-8fbe-c290f530753e">

**Comment by t3ddev** [comment]
Implemented  urp, now works

**Comment by andyb-unity** [comment]
Closing this issue because you did not respond to QA. For everyone else's benefit, here is what QA determined:

```
Thank you for reporting this issue!

I’ve tested and reproduced the issue, although It seems that the problem is within your “MeoPosition.cs” script because, after removing it we could not reproduce the issue. I’ve contacted the developers and asked them to investigate this script and find what exactly causes the crash on Android.

Until then it would be best if you could also review the “MeoPosition.cs” script to see if you can find what exactly causes the crash.

I’ll be waiting for your response!
```
