### ISSUE TITLE
Does AR Foundation support hand tracking on Quest 3 via OpenXR Meta

### ISSUE THREAD

**Issue by great04** [Unity-Technologies/arfoundation-samples#1139]
I was wonder if the latest AR foundation supports hand tracking/interaction? All the functions in my prototype only work with controllers at the moment. I use raycast to spawn object on AR planes. 
Issue: Hand's raycast doesn't reach AR planes. The raycast only reaches other (non-AR Plane) gameobjects. If I add an XRI simple interactable to AR Plane prefab, the raycast can reach the plane, but it doesn't spawn the object as the raycast by controller does. Thanks!

**Comment by andyb-unity** [comment]
Hand tracking is supported on Meta Quest 3 but not through AR Foundation. It comes from the XR Hands package. We recommend that you start from the Mixed Reality Template as discussed in our recent blog post: https://blog.unity.com/engine-platform/cross-platform-mixed-reality-development-on-meta-quest-3

The MR Template works with hands and/or controllers.

I'm closing this issue as asked and answered, but feel free to re-open it if you have further questions.

**Comment by great04** [comment]
> Hand tracking is supported on Meta Quest 3 but not through AR Foundation. It comes from the XR Hands package. We recommend that you start from the Mixed Reality Template as discussed in our recent blog post: https://blog.unity.com/engine-platform/cross-platform-mixed-reality-development-on-meta-quest-3
> 
> The MR Template works with hands and/or controllers.
> 
> I'm closing this issue as asked and answered, but feel free to re-open it if you have further questions.

I did have XR Hand package and the project was built upon MR Template, following the same link you shared. However, the problem was that the hand interaction (raycasting) doesn't work with AR Planes created with AR Foundation. Was it because of AR Foundation doesn't work with XR Hands, or did I do something wrong? Thanks!

**Comment by great04** [comment]
@andyb-unity, do you mind reopening this issue? I am not able to do that. Thanks

**Comment by andyb-unity** [comment]
> I am not able to do that.

Hm, thanks for bringing that to my attention. It seems that only collaborators on the repo can re-open issues. I'll let our team know.

>  hand interaction (raycasting) doesn't work with AR Planes created with AR Foundation.

We don't work on the hands package. This sounds like a question for them (https://forum.unity.com/forums/xr-interaction-toolkit-and-input.519/). From our perspective, the only supported way to raycast against AR Planes is to use the Raycast subsystem (https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/features/raycasts.html).

**Comment by andyb-unity** [comment]
Hi @great04, do you have any further questions here? I don't see any action items here for the AR Foundation team, so I'd like to close this issue.

**Comment by great04** [comment]
> Hi @great04, do you have any further questions here? I don't see any action items here for the AR Foundation team, so I'd like to close this issue.

Yes. You can close it. Thanks!
