### ISSUE TITLE
UnityGfxDeviceWorker (32): EXC_BAD_ACCESS (code=1, addres

### ISSUE THREAD

**Issue by kasivisweswarao** [Unity-Technologies/arfoundation-samples#114]
I'm using Xcode 10.1 and i'm build a app with AR. App is installing in my iPad but it crashing after installing I'm getting a called UnityGfxDeviceWorker (32): EXC_BAD_ACCESS (code=1, address)

**Comment by mdurand42** [comment]
Please retest with 4.0.0-preview.1 and reopen this issue if you can reproduce this using those packages. This could be another manifestation of #95
