### ISSUE TITLE
How can I determine if a coordinate point is inside of a plane? 

### ISSUE THREAD

**Issue by kenhuang1964** [Unity-Technologies/arfoundation-samples#1143]
Hey guys, happy new years! I am currently trying to figure out path planning with the RRT* algorithm. In order to implement it, I have to be able to figure out if a point is inside of any horizontal plane that's currently detected. My plan is to first flatten out all the horizontal classified planes into a 2D area and then determine if a 2D coordinate I sample is inside of a table, chair, etc. horizontal plane. If it is not, then I will add that point. Is there a way to do this?

**Comment by andyb-unity** [comment]
This is a math question. I recommend that you seek other resources on the internet to help you solve it. This question is unrelated to the AR Foundation API or the samples in this repo, so I'm going to close this issue.

**Comment by kenhuang1964** [comment]
Hey @andyb-unity, I think there is a little bit of misunderstanding. For the plane detection, do I only have access to the anchor of the plane in the code or is there some way to access the whole plane if you know what I mean.

**Comment by tdmowrer** [comment]
@kenhuang1964
> do I only have access to the anchor of the plane in the code or is there some way to access the whole plane if you know what I mean.

You can access the 2D boundary points with [ARPlane.boundary](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/api/UnityEngine.XR.ARFoundation.ARPlane.boundary.html).

If you want to know if an arbitrary point is inside the plane, you can use a point-in-polygon algorithm, see https://en.wikipedia.org/wiki/Point_in_polygon

AR Foundation supports raycasting against planes, which might also be useful to you: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/features/raycasts.html

**Comment by andyb-unity** [comment]
Yep. You get center, extents, and a list of boundary points. https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/api/UnityEngine.XR.ARFoundation.ARPlane.html#properties

**Comment by kenhuang1964** [comment]
Thank you @tdmowrer and @andyb-unity I really appreciate it! Happy new year!
