### ISSUE TITLE
Web AR

### ISSUE THREAD

**Issue by Adilxec** [Unity-Technologies/arfoundation-samples#1145]
How do I...
Im trying to make a augmented reality project with unity engine when i host it in GitHub its not accessing the camera permission can anyone please help me out i don't need  any plugins or sdks

**Comment by andyb-unity** [comment]
Unity does not support Web AR for AR Foundation. There may be third-party solutions that you could use to export your project to WebAR, but Unity employees cannot help you with this.

I'm closing this issue as asked and answered. Good luck on your project though!
