### ISSUE TITLE
Oculus2 pathThrough issue[Bug]

### ISSUE THREAD

**Issue by t3ddev** [Unity-Technologies/arfoundation-samples#1146]
**Describe the bug**
Oculus 2 pathThrough works only in left eye, on Oculus 3 works fine

**To Reproduce**
1. build and run AR Simple

**Expected behavior**
pathThrough in both eyes 

**Smartphone (please complete the following information):**
 - Device: Oculus 2
 - Unity version 2022.3.16
 - ARFoundation 5.0

**Comment by andyb-unity** [comment]
> To report a bug in AR Foundation, please [file a bug](https://unity3d.com/unity/qa/bug-reporting). You may also submit a GitHub issue, but we will close your GitHub issue if it does not contain an official bug ID number. The best way to ensure that your issue is addressed is to file a bug using Unity's official bug reporting process.

https://github.com/Unity-Technologies/arfoundation-samples?tab=readme-ov-file#ar-foundation-bug-reports

**Comment by andyb-unity** [comment]
Closing this issue because you did not file a bug. If you file a bug, please notify us and we can re-open this issue.
