### ISSUE TITLE
App Crashing on startup

### ISSUE THREAD

**Issue by NordyVlasman** [Unity-Technologies/arfoundation-samples#115]
When I try to run a sample from version 2.0, the app instantly crashes after running it on Android. With logcat I got a crash log which look like:

05-01 14:23:55.038 26973 26990 E CRASH   : 	#00  pc 002c6026  /data/app/com.unity.arfoundation.samples-hM163OA0MceIP-pp8NC8Fg==/lib/arm/libunity.so
05-01 14:23:55.039 26973 26990 E CRASH   : 	#01  pc 000045b4   ( (wrapper managed-to-native) Unity.Collections.LowLevel.Unsafe.UnsafeUtility:Malloc (long,int,Unity.Collections.Allocator) {0xcb3e6260} + 0x54 (0xf290f560 0xf290f60c) [0xf27edf00 - Unity Root Domain]+17844)
05-01 14:23:55.039 26973 26990 E CRASH   :
05-01 14:23:55.039 26973 26990 E CRASH   : code around pc:
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a004 e9cd4479 f1005100 92020108 22102001  yD...Q....... ."
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a014 fa50f083 48084604 44786025 f5846800  ..P..F.H%`xD.h..
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a024 6802ed58 f8414621 60042b04 b0044608  X..h!FA..+.`.F..
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a034 bf00bdb0 00ad9c80 00c2af22 4909b510  ........"......I
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a044 44791f04 46086809 ed42f584 68084601  ..yD.h.F..B..F.h
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a054 d1fb42a0 60086820 21204620 4010e8bd  .B.. h.` F !...@
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a064 b84ef082 00c2aefa 4604b570 e9d4460d  ..N.....p..F.F..
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a074 08406002 d20342a8 46294620 fb87f5e3  .`@..B.. F)F....
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a084 60a542ae 1ba8d215 6821d022 0286eb06  .B.`....".!h....
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a094 eb012303 22000182 f8013110 38012c10  .#.....".1...,.8
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a0a4 2303e941 2c04f841 f101600a d1f40114  A..#A..,.`......
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a0b4 d90de00e bf081b76 6820bd70 0185eb05  ....v...p. h....
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a0c4 0081eb00 f5ba3004 3014fddf d1fa3e01  .....0.....0.>..
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a0d4 b570bd70 460d4604 6002e9d4 42a80840  p.p..F.F...`@..B
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a0e4 4620d203 f0004629 42aef832 d20c60a5  .. F)F..2..B.`..
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a0f4 d02b1bad eb066820 eb001106 f7fa00c1  ..+. h..........
05-01 14:23:55.039 26973 26990 E CRASH   :
05-01 14:23:55.039 26973 26990 E CRASH   : code around lr:
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a004 e9cd4479 f1005100 92020108 22102001  yD...Q....... ."
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a014 fa50f083 48084604 44786025 f5846800  ..P..F.H%`xD.h..
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a024 6802ed58 f8414621 60042b04 b0044608  X..h!FA..+.`.F..
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a034 bf00bdb0 00ad9c80 00c2af22 4909b510  ........"......I
05-01 14:23:55.039 26973 26990 E CRASH   :     d204a044 44791f04 46086809 ed42f584 68084601  ..yD.h.F..B..F.h
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a054 d1fb42a0 60086820 21204620 4010e8bd  .B.. h.` F !...@
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a064 b84ef082 00c2aefa 4604b570 e9d4460d  ..N.....p..F.F..
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a074 08406002 d20342a8 46294620 fb87f5e3  .`@..B.. F)F....
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a084 60a542ae 1ba8d215 6821d022 0286eb06  .B.`....".!h....
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a094 eb012303 22000182 f8013110 38012c10  .#.....".1...,.8
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a0a4 2303e941 2c04f841 f101600a d1f40114  A..#A..,.`......
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a0b4 d90de00e bf081b76 6820bd70 0185eb05  ....v...p. h....
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a0c4 0081eb00 f5ba3004 3014fddf d1fa3e01  .....0.....0.>..
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a0d4 b570bd70 460d4604 6002e9d4 42a80840  p.p..F.F...`@..B
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a0e4 4620d203 f0004629 42aef832 d20c60a5  .. F)F..2..B.`..
05-01 14:23:55.040 26973 26990 E CRASH   :     d204a0f4 d02b1bad eb066820 eb001106 f7fa00c1  ..+. h..........
05-01 14:23:55.040 26973 26990 E AndroidRuntime: FATAL EXCEPTION: UnityMain
05-01 14:23:55.040 26973 26990 E AndroidRuntime: Process: com.unity.arfoundation.samples, PID: 26973
05-01 14:23:55.040 26973 26990 E AndroidRuntime: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
05-01 14:23:55.040 26973 26990 E AndroidRuntime: Build fingerprint: 'samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXS4ESB2:user/release-keys'
05-01 14:23:55.040 26973 26990 E AndroidRuntime: Revision: '9'
05-01 14:23:55.040 26973 26990 E AndroidRuntime: pid: 26973, tid: 26990, name: UnityMain  >>> com.unity.arfoundation.samples <<<
05-01 14:23:55.040 26973 26990 E AndroidRuntime:     r0 00000000  r1 d1c7fa38  r2 00000000  r3 00000008
05-01 14:23:55.040 26973 26990 E AndroidRuntime:     r4 c59fa090  r5 00000000  r6 00000004  r7 00000004
05-01 14:23:55.040 26973 26990 E AndroidRuntime:     r8 d1c7e870  r9 00000000  sl d1c7e854  fp d1c7dd20
05-01 14:23:55.040 26973 26990 E AndroidRuntime:     ip d2c68908  sp d1c7dbc8  lr d204a027  pc d204a026  cpsr cb2f3d80
05-01 14:23:55.040 26973 26990 E AndroidRuntime:
05-01 14:23:55.040 26973 26990 E AndroidRuntime: 	at libunity.002c6026(Native Method)
05-01 14:23:55.040 26973 26990 E AndroidRuntime: 	at Unknown.000045b4(Unknown Source:0)
05-01 14:23:55.044  3667  4984 D Debug   : !@DumpState : SHIP

**Comment by tdmowrer** [comment]
This is a [known issue](https://issuetracker.unity3d.com/issues/crash-on-non-development-build-when-unsafeutility-dot-malloc-with-allocator-dot-persitent-is-called) with [NativeArray](https://docs.unity3d.com/ScriptReference/Unity.Collections.NativeArray_1.html)s in Unity 2019.2a11 and a13 in non-development builds only. To workaround this, use a development build, or switch to Unity 2019.2a10.

A fix should be forthcoming soon.

**Comment by NordyVlasman** [comment]
Working, Thanks!
