### ISSUE TITLE
Can I use an iPad instead of an iPhone

### ISSUE THREAD

**Issue by ansrthy** [Unity-Technologies/arfoundation-samples#1152]
Can I use an iPad instead of an iPhone, and are there any specific configurations, such as the iOS version and XCode version, that I need to consider? Please help me...

**Comment by kenhuang1964** [comment]
Nope

**Comment by ansrthy** [comment]
> Nope, you can use an ipad instead of an iphone
Sorry, i did not understand what you mean by.

**Comment by kenhuang1964** [comment]
> > Sorry, i did not understand what you mean by.

Yes you can use an iPad instead of an iPhone for your app. Try building it to your iPad.

**Comment by ansrthy** [comment]
Thank you so  much
