### ISSUE TITLE
How to create ARFoundation's ARAnchor from ARKit's ARAnchor?

### ISSUE THREAD

**Issue by misterPitty** [Unity-Technologies/arfoundation-samples#1154]
I want to create [ARKit's ARGeoAnchor](https://developer.apple.com/documentation/arkit/argeoanchor?language=objc) like in [this ARFoundation sample](https://github.com/Unity-Technologies/arfoundation-samples/tree/v5.0.6#geo-anchors) and work with it in unity.
But, as i see, it just creates arkit's anchor. How can i get its arfoundation's representation?
As i understand, when we use ARAnchorManager (AddAnchor or AttachAnchor) arfoundation sends request to native plugin and then creates his unity representation (ARFoundation's ARAnchor) for us.
I think, i need also do it but by myself.

**Comment by andyb-unity** [comment]
You can't create an AR Foundation anchor using the existing API's. You would need to write your own provider for the XRAnchorSubsystem to achieve your desired functionality. If you'd like us to implement this, please add a note to our AR Foundation road map: https://unity.com/roadmap/unity-platform/xr

**Comment by andyb-unity** [comment]
Resolving this question as asked and answered. Feel free to comment if you have further questions, and we can re-open it.
