### ISSUE TITLE
为什么我发布成安卓程序，菜单都是灰色，用不了呢a

### ISSUE THREAD

**Issue by hquu** [Unity-Technologies/arfoundation-samples#1155]
为什么我发布成安卓程序，菜单都是灰色，用不了呢a

**Comment by andyb-unity** [comment]
Make sure that your device supports ARCore: https://developers.google.com/ar/devices. Note that there is a separate list of supported devices for the China region.

**Comment by andyb-unity** [comment]
Closing this question as asked and answered. Feel free to reply if you have further questions, and we can re-open it.
