### ISSUE TITLE
Support of MultiPeer for the visionOS platform

### ISSUE THREAD

**Issue by rubit0** [Unity-Technologies/arfoundation-samples#1156]
The (awesome) MultiPeer implementation of ARFoundation is currently not supported on visionOS.
When performing a build in Xcode it returns several errors about undefined symbols and linker command failings.

<img width="286" alt="Screenshot 2024-01-23 at 14 24 47" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/14140857/8c4d56be-7042-4420-81d2-4435cd022baa">

It would be great if the NativeCode could be recompiled to include visionOS target platform. 
According to the Apple developer docs MultiPeer is [supported on visionOS](https://developer.apple.com/documentation/multipeerconnectivity).

**Comment by andyb-unity** [comment]
Closing this question as asked and answered. We expect to add visionOS support in this repo later this year.

**Comment by rubit0** [comment]
@andyb-unity I went back to give it another try and I can confirm that it now works perfectly on AVP. Thank you all so much!
