### ISSUE TITLE
ARFoundation how to serializes ARWorldMap information for the specified region ?

### ISSUE THREAD

**Issue by hasionerin** [Unity-Technologies/arfoundation-samples#1157]
Unity2020.3.18
ARFoundation 4.2.2

when i serializes the ARWorldMap file , it will serializes the whole world of information 。 i just want to serializes  the specified region world information . 
so , is there any api to serializes ARWorldMap information for the specified region ?

**Comment by andyb-unity** [comment]
Hi @hasionerin, No this is not possible. I'm going to close this issue as Apple designs the ARKit API. Please direct further questions on this matter to Apple.
