### ISSUE TITLE
Persist ARAnchors in Unity for Hololens 2 application

### ISSUE THREAD

**Issue by leonieferdinand** [Unity-Technologies/arfoundation-samples#1159]
Hello everyone,
We make an application where we want to persist gameobjects in Unity with ARAnchors so that GameObjects stay on the same place between sessions of the application. We are building via UWP to the Hololens 2.

Problem: there is no documentaion on how to save and load (persist) ARAnchors between sessions. [Official ARFoundation documenation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/features/anchors.html) only explains how to create and delete the anchors. Does anyone know how we can reach persistence for the anchors? any documentations oder tutorials? it feels like i have already searched the entire internet but most sites build on android or IOS or dont cover persistence.

i downloaded the arfoundation sample project but for me its not clear which functions I need for persistence. and how to change them so that I can use them to anchor my own gameobjects between sessions. but creating the anchors was successfull.

Would be very thankful for every hint!

**Comment by andyb-unity** [comment]
Please do not double-post. It's the same people for both our GitHub issues and the forums. I am closing this issue in favor of your forum post: https://forum.unity.com/threads/persist-aranchors-in-unity-for-hololens-2-application.1549661/
