### ISSUE TITLE
LWRP 5.10.0 compatibility?

### ISSUE THREAD

**Issue by jBachalo** [Unity-Technologies/arfoundation-samples#116]
Any tips in getting this to work with LWRP 5.10.10?
Why?
I believe LWRP 5.10.10 is the earliest version that will work properly with Visual Effects graph.
https://youtu.be/O0OIMvpx3fo?t=575

**Comment by hectorC** [comment]
We are working on a project and would like to be able to use the latest LWRP and Shader Graph with AR Foundation.

**Comment by tdmowrer** [comment]
ARFoundation 3.0 includes better support for LWRP/Universal RP. Step by step instructions: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html

**Comment by ManjitBedi** [comment]
I am following the instructions above for AR Foundation 3.0 but they don't work for me.  

> In the Inspector with the Forward Renderer selected, add a ARBackgroundRendererFeature to the list of Renderer Features. 

The option is not present for me.  
<img width="314" alt="inspector" src="https://user-images.githubusercontent.com/2837803/67593619-69a15500-f717-11e9-8af3-64f668ba9ca4.png">
