### ISSUE TITLE
Stop URP Post Processing from affecting AR Camera Feed Background

### ISSUE THREAD

**Issue by faysalfdt** [Unity-Technologies/arfoundation-samples#1160]
How do I stop the URP Post Processing effect from impacting the AR Camera Background

For example we have the Bloom effect on our Volume Profile and we'd like it to ignore the actual camera feed, is this possible?

**Comment by andyb-unity** [comment]
Please direct your question to the Unity graphics forums: https://forum.unity.com/forums/general-graphics.76/
