### ISSUE TITLE
[Bug] Link to Adam Demo executable does not work

### ISSUE THREAD

**Issue by rafrafek** [Unity-Technologies/arfoundation-samples#1165]
https://blog.unity.com/games/adam-demo-executable-and-assets-released

<img width="578" alt="image" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/23004737/10415b6d-e126-4f0e-936d-5cd5ac18b07b">

Adam executable download (size: 3 GB; Windows DX11 only)

http://unity3d.com/adam-standalone

Not found / 404

<img width="376" alt="image" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/23004737/61c44968-144e-42c8-877a-d895c3a18ada">

Please provide a new working link. Thank you!

**Comment by andyb-unity** [comment]
This is the AR Foundation samples repository. We have nothing to do with the Adam demo, so I'm closing this issue.
