### ISSUE TITLE
Black screen with new Image Tracking demo in AR Foundation 2.1

### ISSUE THREAD

**Issue by jBachalo** [Unity-Technologies/arfoundation-samples#117]
Getting black screen after deploying to iPhone

**Comment by tdmowrer** [comment]
Just pulled down a fresh copy of `master` and ran the image tracking sample on an iPad Pro without issue. Can you provide more details:
- Unity version
- iPhone model and iOS version

**Comment by prasad-marne** [comment]
@tdmowrer Hi, i am facing similar issue. Black screen for image tracking in AR foundation 2.1 branch

Unity version 2019.3

Iphone model 8 and iOS version 12.3.1

**Comment by mdurand42** [comment]
Please try to reproduce this using the verified packages for 2019.3 and re-open the issue if you are able to reproduce it.
