### ISSUE TITLE
Can't build if GoogleARCore was previously added (then deleted)

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/arfoundation-samples#118]
If you added GoogleARCore and deleted the plugin later (to favor AR Foundation for example) the prebuild script will still prevent the build, saying `GoogleARCore detected. Google's "ARCore SDK for Unity" and Unity's "ARCore XR Plugin" package cannot be used together.` even **after deleting** GoogleARCore.

**As a workaround**, you can delete the `Library` folder to make Unity refresh it's asset database.

**Comment by tdmowrer** [comment]
Thanks for reporting. We'll look into it.

**Comment by s7ubborn** [comment]
I am running in the same issue. Any update? @tdmowrer

**Comment by tdmowrer** [comment]
This seems to be an artifact of the way Unity's asset database works. GoogleARCore's GUID is still in the database even after it is removed. This seems like a very special edge case and is easily worked around; is this really a blocking issue?

**Comment by iBicha** [comment]
I would suggest documenting the issue in the package (or adding the workaround in the exception message) and close this

**Comment by tdmowrer** [comment]
Just tested this again in 2019.2, and it looks like it just requires an Editor restart, not a full Library rebuild. I'll update the exception message to suggest that.

**Comment by tdmowrer** [comment]
Fixed in 3.0.0-preview.4

**Comment by nohina** [comment]
ルートフォルダーのみリネームして残っている状態で、フォルダ内のすべてのファイルが削除されている状態でも同じエラーが発生します。この場合、関連するファイルをすべて削除しきっている状態にしないとエラーが消えません。操作ミスでリネームしてしまった結果何時間も悩みました。
