### ISSUE TITLE
ARCore Scene Segmentation is ARKit Mesh Classification - Please add demo

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#1184]
Hi, I'm trying to get ARCore Scene Segmentation to work with ARFoundation Unity iOS - apparently there is support but it may make more sense to have it as an official example scene here

https://developers.google.com/ar/develop/scene-semantics

**Comment by andyb-unity** [comment]
ARCore Scene Semantics requires additional ARCore integrations that are not currently supported by AR Foundation. To request this feature, go to Unity's XR Roadmap, select AR Foundation, then scroll down to **Submit an Idea**! https://unity.com/roadmap/unity-platform/xr

Until Unity integrates this feature in our ARCore XR Plug-in, you should follow Google's instructions to set up via their ARCore Extensions package.

We don't track feature requests on this repo, so I'm going to close this issue. Feel free to respond if you have further questions.
