### ISSUE TITLE
[Bug] ARKitReferenceObjectEntry does not export properly to AssetBundles

### ISSUE THREAD

**Issue by Jerem-35** [Unity-Technologies/arfoundation-samples#1187]
I am trying to export ARKitReferenceObjectEntry objects into an assetbundle for tracking them later with an ARTrackedObjectManager.

I am using Unity 2022.3.30, ARFoundation 5.1.5 and ARFoundationARKit 5.1.5.

When creating the assetbundle, the assetbundlefile remains extremly small (1ko while the .arobject are > 1mo) and then fails to load at runtime :
ARArchive <0x302c30cd0>: Unable to read archive at path: ... 

The .arobject are still included in the manifest.

**Comment by andyb-unity** [comment]
You must call ARBuildProcessor.PreprocessBuild as documented here: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/manual/features/image-tracking.html#use-reference-image-libraries-with-assetbundles

**Comment by Jerem-35** [comment]
Thanks a lot, works like a charm. Would be a nice update to mention that in the page dedicated to object tracking.
