### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by niefun** [Unity-Technologies/arfoundation-samples#1192]
MakeAppearOnPlane类中，调用的ARSessionOrigin的MakeContentAppearAt方法，说过时了，让我用XROrigin类代替，但是XROrigin类中并没有MakeContentAppearAt方法，该怎么处理，我的unity版本是2022.3.20，东家要求这个版本

报错：
Assets\Scripts\MakeAppearOnPlane.cs(69,34): error CS1061: “ARSessionOrigin”未包含“MakeContentAppearAt”的定义，并且找不到可接受第一个“ARSessionOrigin”类型参数的可访问扩展方法“MakeContentAppearAt”(是否缺少 using 指令或程序集引用?)

**Comment by andyb-unity** [comment]
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/version-history/migration-guide-5-x.html#removal-of-arsessionoriginmakecontentappearat
