### ISSUE TITLE
inverts the view of the AR Camera

### ISSUE THREAD

**Issue by hyesoo613** [Unity-Technologies/arfoundation-samples#123]
I want inverts the view of the AR Camera. 
So I applied the scripts to ARCameraBackground.

camera.ResetWorldToCameraMatrix();
camera.ResetProjectionMatrix();
camera.projectionMatrix = camera.projectionMatrix * Matrix4x4.Scale(new Vector3(-1, 1, 1));

However, the view of the AR Camera was not reversed.
How can I reverse the AR Camera view?

**Comment by tdmowrer** [comment]
ARFoundation sets the camera's projection matrix each frame, so that is probably why your code does not have the desired effect.

Can you provide more details on why you want to do this?

**Comment by hyesoo613** [comment]
I want to reverse the screen of camera without affecting image tracking.
I was originally using Vuforia. Using the Vuforia Mirror feature, but we changed to ARFoundation.
So we are looking for functionality to replace Vuforia.

When using the vuforia, I used the following sources.

CameraDevice.Instance.Stop();

if(ms_bMirror)
{
    VuforiaConfiguration.Instance.Vuforia.MirrorVideoBackground = VuforiaRenderer.VideoBackgroundReflection.ON;
}
else
{
     VuforiaConfiguration.Instance.Vuforia.MirrorVideoBackground = VuforiaRenderer.VideoBackgroundReflection.OFF;
}

CameraDevice.Instance.Start();

**Comment by tdmowrer** [comment]
So you actually want the camera feed to be flipped along the Y axis? You could try negating the projection matrix in an `OnPreRender` callback, but I don't think that will work. The projection matrix should only affect virtual content.

There's no good way to mirror the camera feed in ARFoundation. You might be able to workaround this by copying the textures into a `RenderTexture`, manipulating them, and then blitting them back to the screen. See https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.1/manual/index.html and look for `Copying the Camera Texture to a Render Texture`.
