### ISSUE TITLE
Arkit detecting tables in room scale is much better than AR foundation.

### ISSUE THREAD

**Issue by AzadNezamdoust** [Unity-Technologies/arfoundation-samples#126]
In my experiment I found that AR kit detecting planes in room scale so much better than AR foundation. In AR foundation if we don't get a clear textured surface it won't be able to detect it but AR kit is so much better in detecting surfaces with little bit of texture also I tried to use estimated plane detection of AR foundation which is very jaggy most o the times do not detect properly.
Is there anyway to have a plane detection between polygon and estimated planes not so precise to exclude most of the surfaces and not so jaggy to have a lot of errors on detecting surfaces?

**Comment by AzadNezamdoust** [comment]
I believe this thing is a big issue for room scale AR.

**Comment by tdmowrer** [comment]
The behavior you describe could be attributed to frame rate. ARKit likes a 60 Hz frame rate, but Unity's default is 30 Hz. You can set it with [Application.targetFrameRate](https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html).

**Comment by wisockijunior** [comment]
can we use ARCore at 60fps ?

**Comment by tdmowrer** [comment]
> can we use ARCore at 60fps ?

You can set the target frame rate to 60 Hz on Android (we do this in the samples) but ARCore internally only updates at 30 Hz.
