### ISSUE TITLE
PackageManager Not Found!

### ISSUE THREAD

**Issue by paragkikani** [Unity-Technologies/arfoundation-samples#129]
Manifest ==>

{
  "dependencies": {
    "com.unity.ads": "3.0.3",
    "com.unity.collab-proxy": "1.2.16",
    
    "com.unity.package-manager-ui": "1.8.0",
	
	"com.unity.textmeshpro": "1.2.2",
    "com.unity.purchasing": "2.0.6",
    "com.unity.timeline": "1.0.0",
    "com.unity.xr.arcore": "2.1.0-preview.4",
    "com.unity.xr.arfoundation": "2.1.0-preview.2",
    "com.unity.xr.arkit": "2.1.0-preview.3",
    "com.unity.xr.arkit-face-tracking": "1.0.0-preview.4",
    "com.unity.xr.legacyinputhelpers": "2.0.2",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

Error show this ==>
Assembly has reference to non-existent assembly 'Windows.UI.Input.Spatial' (Packages/com.unity.xr.legacyinputhelpers/Runtime/LegacyInputHelpers.asmdef)

unity Version : 2018.3.10f1 

Please help.

**Comment by tdmowrer** [comment]
Legacy input helpers is only available in 2019.1+.

For Unity 2018.3/4, use ARFoundation 1.5 (it is the same as 2.1 except it is compatible with 2018.3). You should also remove the reference to `com.unity.xr.legacyinputhelpers` in your manifest.
