### ISSUE TITLE
How to use AR Tracked Image ? (Image Tracking)

### ISSUE THREAD

**Issue by RafaelSPBarbosa** [Unity-Technologies/arfoundation-samples#136]
Hey,
I'm using the latest ARFoundation 2.1.0-preview.2 | unity 2018.3.1f1
It's supposed to feature image tracking. I have setup a ReferenceImageLibrary correctly and have added ARTrackedImageManager to my ARSessionOrigin object. After that, I created an empty object and attached an ARTrackedImage component. I have searched everywhere but it seems like people aren't talking about this new feature yet, it doesn't even seem to be properly documented. I did find a resource about this earlier but can't seem to find it anymore.

Ever since vuforia changed it's pricing I've been tasked with changing it to another approach, ARFoundation is one of the other options I'm trying out to substitute Vuforia. EasyAR was another one but couldn't get it to work alongside arcore. 
Which brings me to my seconds question.

If a user's phone doesn't support ARCore, as in, doesn't have a gyroscope, etc. Can I still use this image tracking feature? This is what we were doing with vuforia. Image tracking for lower end devices and feature tracking for high end devices.

**Comment by tdmowrer** [comment]
**Documentation**
In general, you can find documentation from the Package Manager window (Window > Package Manager) in Unity. Click on a package, and there should be a "View Documentation" link.
For image tracking in particular, see
- [ARFoundation docs](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.1/manual/tracked-image-manager.html)
- [ARSubsystems docs](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@2.1/manual/image-tracking.html)

**Samples**
See the [ARFoundation Samples repo on GitHub](https://github.com/Unity-Technologies/arfoundation-samples). There is a sample scene demonstrating image tracking.

> If a user's phone doesn't support ARCore, as in, doesn't have a gyroscope, etc. Can I still use this image tracking feature?

ARFoundation uses ARCore on Android, so the phone must support ARCore.
