### ISSUE TITLE
Compiler Errors: 'ARSessionOrigin' does not contain definition for 'Raycast', and other errors

### ISSUE THREAD

**Issue by codepowder** [Unity-Technologies/arfoundation-samples#138]
Hi there,
We migrated to using the following packages:

1. AR Foundation 2.1.0 preview 2
2. ARKit XR 2.1.0 preview 3
3. Unity 2019.1.0f2

The following compiling errors keep appearing despite their references being correct.

- The name 'ARSubsystemManager' does not exist in the current context

- 'ARSessionOrigin' does not contain a definition for 'Raycast' and no accessible extension method 'Raycast'

- 'ARPlaneManager' does not contain a definition for 'GetAllPlanes' 

Have tried resetting the packages, but no joy, and our code is using the appropriate namespaces.

**Comment by codepowder** [comment]
Appears to be an issue affecting others as well:

https://forum.unity.com/threads/foundation-ar-arsessionorigin-doesnt-reconize-the-raycast-method.680296/

**Comment by nilsk123** [comment]
There is a migration guide that you should read

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.0/manual/migration-guide.html

**Comment by codepowder** [comment]
Thank you nils!

**Comment by tiago-peres** [comment]
Already manage to do it.

As we can read [in the documentation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.2/manual/migration-guide.html#arsubsystemmanager-removed),

> The ARSubsystemManager has been removed in 2.0.

Instead, I've used `ARSession.stateChanged += OnStateChanged;`
