### ISSUE TITLE
Light estimation not working

### ISSUE THREAD

**Issue by Aupuma** [Unity-Technologies/arfoundation-samples#14]
I have enabled light estimation on the AR session but it does not react to the lights. I'm using a Samsung Galaxy S8

**Comment by timm-unity** [comment]
The option enables it on the device, but you need to subscribe to the ARSubsystemManager's camerFrame event, which will provide lighting information. ARFoundation does not do anything automatically with this information other than provide it to you.

**Comment by sam598** [comment]
This code is based of ARKit's UnityARAmbient.cs and works for me:

`using UnityEngine;
using UnityEngine.XR.ARFoundation;

[RequireComponent(typeof(Light))]
public class ARLightAmbient : MonoBehaviour
{
    private Light l;

	void Start ()
    {
        l = GetComponent<Light>();
        ARSubsystemManager.cameraFrameReceived += OnCameraFrameReceived;
	}

    void OnCameraFrameReceived (ARCameraFrameEventArgs eventArgs)
    {
        l.intensity = eventArgs.lightEstimation.averageBrightness.Value;
        l.colorTemperature = eventArgs.lightEstimation.averageColorTemperature.Value;
    }

    void OnDisable ()
    {
        ARSubsystemManager.cameraFrameReceived -= OnCameraFrameReceived;
    }
}`

**Comment by sam598** [comment]
This is based on ARKit's UnityARAmbient and works for me:

```c#
using UnityEngine;
using UnityEngine.XR.ARFoundation;

[RequireComponent(typeof(Light))]
public class ARLightAmbient : MonoBehaviour
{
    private Light l;

    void Start ()
    {
        l = GetComponent<Light>();
        ARSubsystemManager.cameraFrameReceived += OnCameraFrameReceived;
    }

    void OnCameraFrameReceived (ARCameraFrameEventArgs eventArgs)
    {
        l.intensity = eventArgs.lightEstimation.averageBrightness.Value;
        l.colorTemperature = eventArgs.lightEstimation.averageColorTemperature.Value;
    }

    void OnDisable ()
    {
        ARSubsystemManager.cameraFrameReceived -= OnCameraFrameReceived;
    }
}
```

**Comment by nilsk123** [comment]
If I may suggest, add a null check

`using UnityEngine;
using UnityEngine.XR.ARFoundation;

[RequireComponent(typeof(Light))]
public class ARLightAmbient : MonoBehaviour
{
    private Light l;

    void Start ()
    {
        l = GetComponent<Light>();
        ARSubsystemManager.cameraFrameReceived += OnCameraFrameReceived;
    }

    void OnCameraFrameReceived (ARCameraFrameEventArgs eventArgs)
    {
        if(eventArgs.lightEstimation.averageBrightness.HasValue && eventArgs.lightEstimation.averageColorTemperature.HasValue)
        {
            l.intensity = eventArgs.lightEstimation.averageBrightness.Value;
            l.colorTemperature = eventArgs.lightEstimation.averageColorTemperature.Value;
        }
    }

    void OnDisable ()
    {
        ARSubsystemManager.cameraFrameReceived -= OnCameraFrameReceived;
    }
}`

**Comment by nilsk123** [comment]
`using UnityEngine;
using UnityEngine.XR.ARFoundation;

[RequireComponent(typeof(Light))]
public class ARLightAmbient : MonoBehaviour
{
    private Light l;

    void Start ()
    {
        l = GetComponent<Light>();
        ARSubsystemManager.cameraFrameReceived += OnCameraFrameReceived;
    }

    void OnCameraFrameReceived (ARCameraFrameEventArgs eventArgs)
    {
        if(eventArgs.lightEstimation.averageBrightness.HasValue && eventArgs.lightEstimation.averageColorTemperature.HasValue)
        {
            l.intensity = eventArgs.lightEstimation.averageBrightness.Value;
            l.colorTemperature = eventArgs.lightEstimation.averageColorTemperature.Value;
        }
    }

    void OnDisable ()
    {
        ARSubsystemManager.cameraFrameReceived -= OnCameraFrameReceived;
    }
}`
