### ISSUE TITLE
Building from PC for iOS breaks image/object reference libraries in AR foundation 

### ISSUE THREAD

**Issue by ethesham-communist** [Unity-Technologies/arfoundation-samples#145]
This may be connected to the other issues, but wanted to highlight the solution that helped us. We tried using the latest packages, we tried simplifying the project and build paths. The issue resolved instantly building on a Mac rather than building on a PC.

**Comment by olabrahammar** [comment]
I can confirm that the ObjectReferenceLibrary asset type is not working correctly in Unity/Windows, creating one and adding items simply does not work. "Nothing registers" kind of.  Works in Unity/MacOS Catalina though.

**Comment by tdmowrer** [comment]
I just tested the `latest-preview` branch of this repo (using the 4.1.0-preview.7 packages). I generated the Xcode project on Windows (Unity > Build Settings... > Build), then copied the output to a Mac and built it. Both image tracking and object tracking worked as expected.

Is this still an issue? If so, please [log a bug](https://unity3d.com/unity/qa/bug-reporting) and post the issue number here.
