### ISSUE TITLE
ARRaycastHit doesn't work in ARFoundation +2.1 (LWRP scene)

### ISSUE THREAD

**Issue by Amin-Montazeri** [Unity-Technologies/arfoundation-samples#146]
Hi... I have a problem with LWRP scene in mobile (after build)
No black screen and plane found but... when I touch that plane nothing happened (the cube doesn't appear)
In the previous project with ARfoundation 1.5 and LWRP 5.6.1, everything was ok.
Any help would be appreciated.

I used:
Unity 2019.1.4
ARfoundation +2.1 (v2.2 also tested)
LWRP 5.6.1 (upper version got an error, that's not weird!)
Samsung A7 2017

**Comment by cemreinanc** [comment]
I had the same issue on iOS too.

Then i realized that the game object `AR Session Origin` which holds the `PlaceOnPlane.cs` script; doesn't have AR Raycast Manager. 

You just need to add `ARRaycastManager.cs` to it. That's all.
