### ISSUE TITLE
Doesn't compile for iOS

### ISSUE THREAD

**Issue by reubenkcoutinho** [Unity-Technologies/arfoundation-samples#15]
I cloned this repo and tried to build the application for iOS but I got the following error:

> Failed running /Applications/Unity/Hub/Editor/2018.1.0f2/Unity.app/Contents/il2cpp/build/UnityLinker.exe --api=NET_2_0 -out="/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/tempStrip" -l=none -c=link --link-symbols -x="/Applications/Unity/Hub/Editor/2018.1.0f2/PlaybackEngines/iOSSupport/Whitelists/Core.xml" -f="/Applications/Unity/Hub/Editor/2018.1.0f2/Unity.app/Contents/il2cpp/LinkerDescriptors" -x "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/../platform_native_link.xml" -x "/var/folders/gk/02w1vv9n47v422v47dt2rtk40000gn/T/tmp27667db.tmp" -x "/var/folders/gk/02w1vv9n47v422v47dt2rtk40000gn/T/tmp594a621d.tmp" -x "/var/folders/gk/02w1vv9n47v422v47dt2rtk40000gn/T/tmp2514e7b2.tmp" -x "/Users/rkc/Projects/arfoundation-samples/Assets/link.xml" -d "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Unity.XR.ARKit.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Unity.XR.ARFoundation.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Unity.XR.ARExtensions.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/UnityEngine.SpatialTracking.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/UnityEngine.Analytics.dll"

Any help would be appreciated.

Build details:

`Unity Version: 2018.1.0f2`

`Xcode version: Version 9.4.1 (9F2000)`

`iOS Version: 11.4.1`

`Player Setting`
![gh](https://user-images.githubusercontent.com/1557519/42298297-83143b7a-8048-11e8-97d0-582ecdcf18e5.jpeg)

**Comment by timm-unity** [comment]
Did you symlink Unity libraries in the build settings? That doesn't work with packages at the moment.

**Comment by ManjitBedi** [comment]
I am seeing the same problem with Unity 2018.1.  The problem happens regardless of the the symlink setting. 

But if I create a new project (not using this repo)  and install the AR Foundation, AR Core & AR Kit package using the package manager,  it will generate the iOS project but the iOS app does not work at run-time.

**Comment by reubenkcoutinho** [comment]
![symlink](https://user-images.githubusercontent.com/1557519/42355532-e61cf25c-8110-11e8-80f8-e87bebabde7d.jpeg)
Is that correct?

**Comment by reubenkcoutinho** [comment]
It now builds for Xcode, but building in Xcode fails with the following error:

`lang: error: no such file or directory: '/Users/rkc/Projects/ARxDemo/Packages/com.unity.xr.arkit/Runtime/iOS/UnityARKit.m'
clang: error: no input files`

**Comment by ManjitBedi** [comment]
I think the new error is when the build setting symlink setting is on.

**Comment by timm-unity** [comment]
Looks like this was introduced when I added a `link.xml` to fix a different issue affecting 2018.2 (IL2CPP builds didn't always work correctly). This should now be fixed as of this changeset bde3fa75eaa7ad03b5ed48c1a8d8fdf1dc0109cc.

**Comment by reubenkcoutinho** [comment]
@timm-unity is this been included in the preview package 1.0.0-preview.12 for ARKit XR Plugin?
If so, I'm still facing the issue.

`Failed running /Applications/Unity/Hub/Editor/2018.1.0f2/Unity.app/Contents/il2cpp/build/UnityLinker.exe --api=NET_2_0_Subset -out="/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/tempStrip" -l=none -c=link --link-symbols -x="/Applications/Unity/Hub/Editor/2018.1.0f2/PlaybackEngines/iOSSupport/Whitelists/Core.xml" -f="/Applications/Unity/Hub/Editor/2018.1.0f2/Unity.app/Contents/il2cpp/LinkerDescriptors" -x "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/../platform_native_link.xml" -x "/var/folders/gk/02w1vv9n47v422v47dt2rtk40000gn/T/tmp433d1d44.tmp" -x "/var/folders/gk/02w1vv9n47v422v47dt2rtk40000gn/T/tmp6c692301.tmp" -x "/var/folders/gk/02w1vv9n47v422v47dt2rtk40000gn/T/tmp3345cea1.tmp" -x "/Users/rkc/Projects/arfoundation-samples/Assets/link.xml" -d "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Unity.XR.ARKit.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Unity.XR.ARFoundation.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/Unity.XR.ARExtensions.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/UnityEngine.UI.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/UnityEngine.SpatialTracking.dll" -a  "/Users/rkc/Projects/arfoundation-samples/Temp/StagingArea/Data/Managed/UnityEngine.Analytics.dll"`

**Comment by tdmowrer** [comment]
The `link.xml` workaround is no longer required.
