### ISSUE TITLE
HumanBodyTracking3D not triggering OnHumanBodiesChanged

### ISSUE THREAD

**Issue by juancabrera** [Unity-Technologies/arfoundation-samples#150]
HumanBodyTracking3D example is not triggering `OnHumanBodiesChanged`, started debugging `TestHumanBodyTracking.cs` and the last (and actually the only one) debug log I got is the one I put inside of `OnEnable` (line 136), but `OnHumanBodiesChanged` is never triggered, also no error at all.

Using:
* Unity 2019.2.0b3
* ARFoundation `2.2p2`
* ARkit XR Plugin `2.2p1`
* iOS 13 beta.
* XCode 11

**Comment by tdmowrer** [comment]
Human body tracking (2D, 3D, & segmentation) will only work on devices that have the A12 bionic chip. On all other devices, the samples would produce the behavior you described. On what device were you testing?

**Comment by juancabrera** [comment]
@tdmowrer I see, testing on a iPhone X.

**Comment by yosun** [comment]
Hi, I am experiencing this issue with the latest ARFoundation / ARKit from this repo on Unity 2019.1.7f1  on my latest generation iPad Pro 12.8" which uses the A12X... I am able to get the line renderer to render the body but not able to get your 3D demo to work.

**Comment by sottom** [comment]
You might try upgrading Unity. I had trouble getting anything to work until I upgraded unity to version 2019.2.x or higher.
