### ISSUE TITLE
Can I use Unity2018 for ARKit3.0?

### ISSUE THREAD

**Issue by crocoking** [Unity-Technologies/arfoundation-samples#152]

**Comment by tdmowrer** [comment]
Yes, [ARFoundation 1.5.0-preview.5](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.5/changelog/CHANGELOG.html) is compatible with Unity 2018.4 and includes support for the ARKit 3 features in [ARKit XR Plugin 2.2.0-preview.1](https://docs.unity3d.com/Packages/com.unity.xr.arkit@2.2/changelog/CHANGELOG.html).

The [`1.5-preview` branch](https://github.com/Unity-Technologies/arfoundation-samples/tree/1.5-preview) of this repo contains samples demonstrating new features in ARKit 3.

**Comment by crocoking** [comment]
> Yes, [ARFoundation 1.5.0-preview.5](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.5/changelog/CHANGELOG.html) is compatible with Unity 2018.4 and includes support for the ARKit 3 features in [ARKit XR Plugin 2.2.0-preview.1](https://docs.unity3d.com/Packages/com.unity.xr.arkit@2.2/changelog/CHANGELOG.html).
> 
> The [`1.5-preview` branch](https://github.com/Unity-Technologies/arfoundation-samples/tree/1.5-preview) of this repo contains samples demonstrating new features in ARKit 3.

Our game is using Unity 2017，We use Unity ARKit plugin before ARfoundation。We cannot upgrade
to Unity 2018 or 2019 for some reason。But we want to use ARKit 3.0. Is there any other way?

**Comment by crocoking** [comment]
> Yes, [ARFoundation 1.5.0-preview.5](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.5/changelog/CHANGELOG.html) is compatible with Unity 2018.4 and includes support for the ARKit 3 features in [ARKit XR Plugin 2.2.0-preview.1](https://docs.unity3d.com/Packages/com.unity.xr.arkit@2.2/changelog/CHANGELOG.html).
> 
> The [`1.5-preview` branch](https://github.com/Unity-Technologies/arfoundation-samples/tree/1.5-preview) of this repo contains samples demonstrating new features in ARKit 3.

I got this with Unity2018,4,2f1：
![image](https://user-images.githubusercontent.com/14910281/59325763-cf67e400-8d16-11e9-8fd9-0507eef21a03.png)

**Comment by rexxarM** [comment]
@tdmowrer 
Any possible back port to 2018.3? Unity version compatible is terrible trap in large project.

**Comment by tdmowrer** [comment]
2018.4 is the long term support version, so you should use 2018.4 LTS not 2018.3. 2018.4 gets bug fixes for 2 years.

That said, my previous comment is applicable to 2018.3 as well; ARFoundation works in 2018.3 & 2018.4.
