### ISSUE TITLE
2D Image tracking not working on IOS ARkit supported devices.

### ISSUE THREAD

**Issue by kanishkaCemtrex** [Unity-Technologies/arfoundation-samples#155]
I have been trying to get 2D Image tracking  working now for quite couple of days for IOS devices.
I have build the same scene as "ImageTracking" from this git repo for some reason when i build it for Android it works fine but for IOS it is not tracking the Image.
I am using ARkit : preview.5 - 2.1.0 & AR foundation : preview.3 - 2.1.0
Inside your git repo scene i cannot see any gameobject with "AR Tracked Image" scirpt as in it is not attached to any of it. do i have to attached it somewhere?
Please let me know if issues or queries.

**Comment by tdmowrer** [comment]
> I have been trying to get 2D Image tracking working now for quite couple of days for IOS devices.
> I have build the same scene as "ImageTracking" from this git repo for some reason when i build it for Android it works fine but for IOS it is not tracking the Image.
> I am using ARkit : preview.5 - 2.1.0 & AR foundation : preview.3 - 2.1.0
> Inside your git repo scene i cannot see any gameobject with "AR Tracked Image" scirpt as in it is not attached to any of it. do i have to attached it somewhere?
> Please let me know if issues or queries.

That definitely worked when it was released. What version of iOS are you using? We've seen several issues with iOS 13 beta compatibility.

**Comment by kanishkaCemtrex** [comment]
Ok so i am not using IOS 13 i am using IOS 12.3.1 & that is the reason also i am not using updated ARkit & ARfoundation as i know it works only for IOS 13. I am currently working on ARkit : preview.5 - 2.1.0 & AR foundation : preview.3 - 2.1.0.
We have deployed the same on Android it is working ie. tracking the image target but for IOS it is not tracking.

**Comment by artempinskiy** [comment]
Same to me. I migrate from ARKit plugin to ARfoundation, because it also works incorrectly.
Unity 2019.1.6f1
Using image tracking sample on this commit [ 596138b](https://github.com/Unity-Technologies/arfoundation-samples/commit/596138b62fa40837e2239859494f3d12fb7f8470)
ARFoundation preview.2 - 2.1.0.
ARKit XR Plugin preview.3 - 2.1.0.
IOS 12.3.1. 
Xcode 10.2.1
What I need to do to make it work?

**Comment by kanishkaCemtrex** [comment]
I have these same packages installed but it is not working for me.
ARFoundation preview.3 - 2.1.0.
ARKit XR Plugin preview.5 - 2.1.0.

Could you please send me screen shot or something so that i can understand ?

**Comment by artempinskiy** [comment]
[screen shot of imported packages](https://ibb.co/fDWr3rt)

**Comment by tdmowrer** [comment]
This was an issue with the version parsing of iOS "12.3.1" in ARKit XR Plugin 2.1.0-preview.3 and was fixed in 2.1.0-preview.5. See the ARKit XR Plugin [changelog](https://docs.unity3d.com/Packages/com.unity.xr.arkit@2.1/changelog/CHANGELOG.html).

**Comment by midopooler** [comment]
its 2021 and I'm still facing this issue, how?

**Comment by tdmowrer** [comment]
@midopooler Please open a new issue.
