### ISSUE TITLE
Crash on Android when running imagetarget example

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#156]
Hi, sometimes when running the imagetracking example found in the ARFoundation samples repository I encounter a crash on android, see crashlogs attached below.

This is using the 2.1 branch, running on Android 9 

Unity version 2019.1.6

https://pastebin.com/L7aCTFz9
https://pastebin.com/JrQdCzmU

Package manifest:

`{
  "dependencies": {
    "com.unity.ads": "3.1.1",
    "com.unity.analytics": "3.3.2",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.multiplayer-hlapi": "1.0.4",
    "com.unity.package-manager-ui": "2.1.2",
    "com.unity.purchasing": "2.0.6",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.0.0",
    "com.unity.xr.arcore": "2.1.0-preview.5",
    "com.unity.xr.arfoundation": "2.1.0-preview.3",
    "com.unity.xr.arkit": "2.1.0-preview.5",
    "com.unity.xr.arkit-face-tracking": "1.0.0-preview.6",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
`

**Comment by 60days** [comment]
I have the same problem, combined with the image tracking itself not working prior to the crash (which occurs after 20 seconds or so): https://pastebin.com/5bBY46Jz

I have found updating com.unity.xr.arfoundation via the package manager UI to the 2.2.0-preview.2 version prevented the crash, but now my content is missing from the tracked images (using a custom script to position them at the trackedImage.transform (not parenting)) - this is likely an unrelated issue though.

Device - Pixel 1 on Android 9

manifest: 

{
  "dependencies": {
    "com.unity.ads": "3.1.1",
    "com.unity.analytics": "3.3.2",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.multiplayer-hlapi": "1.0.4",
    "com.unity.package-manager-ui": "2.1.2",
    "com.unity.purchasing": "2.0.6",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.0.0",
    "com.unity.xr.arcore": "2.1.0-preview.5",
    "com.unity.xr.arfoundation": "2.1.0-preview.3",
    "com.unity.xr.arkit": "2.1.0-preview.5",
    "com.unity.xr.arkit-face-tracking": "1.0.0-preview.6",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

**Comment by nilsk123** [comment]
This issue still exists, and occurs every minute or so.. I made sure I have all the same player settings as the samples repo, but it still happens (2019.1.8)

Another log here:

https://pastebin.com/yE3KDcvb

@tdmowrer

**Comment by DavidMohrhardt** [comment]
I can't reproduce this crash, can you give me a little more information?  Is there a specific way you are able to get this crash to replicate such as tracking all three sample images at the same time?  Also, what version of ARCore does the device have?
