### ISSUE TITLE
easy access to face blend shapes 

### ISSUE THREAD

**Issue by edwonia** [Unity-Technologies/arfoundation-samples#158]
There's no clear/easy way to access blend shape information in here. I found ARKitBlendShapeVisualizer and the method GetBlendShapeCoefficients seems to be the key method, but it's extremely confusing to use. I just want an enum that I can pass in to get a specific blend shapes value.

**Comment by vlobanov** [comment]
This worked for me:

```csharp
var faceManager = FindObjectOfType<ARFaceManager>();
var face = GetComponent<ARFace>();
ARKitFaceSubsystem _faceSubsystem;
if (faceManager != null) {
    _faceSubsystem = (ARKitFaceSubsystem)faceManager.subsystem;
}
var ks = new Dictionary<ARKitBlendShapeLocation, float>();
using (var blendShapes = _faceSubsystem.GetBlendShapeCoefficients(face.trackableId, Allocator.Temp)) {
    foreach (var featureCoefficient in blendShapes) {
        ks[featureCoefficient.blendShapeLocation] = featureCoefficient.coefficient;
    }
}
```

**Comment by gilsunshine** [comment]
I'm trying to access just the JawOpen coefficient, using a strategy similar to what @vlobanov posted. When I log index 24 of the blendShapes native array, which I believe should be JawOpen, I get "0" for the coefficient and "BrowLeftDown" for the location. I tried this with a random index (5) and also get "0" for the coefficient and "BrowLeftDown" for the location. I'm new to Unity and C# so it's very possibly something obvious. Thanks.

`face = GetComponent<ARFace>();
if (faceManager != null)
{
    faceSubsystem = (ARKitFaceSubsystem)faceManager.subsystem;
}
using var blendShapes = faceSubsystem.GetBlendShapeCoefficients(face.trackableId, Allocator.Temp);
Debug.Log(blendShapes[24].coefficient);
Debug.Log(blendShapes[24].blendShapeLocation);
Debug.Log(blendShapes[5].coefficient);
Debug.Log(blendShapes[5].blendShapeLocation);`

Here is some of the log: 

BrowDownLeft
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
EventController:Update()

0
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
EventController:Update()

BrowDownLeft
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
EventController:Update()

0
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
EventController:Update()
