### ISSUE TITLE
Switching Reference Image Library Runtime

### ISSUE THREAD

**Issue by mimminito** [Unity-Technologies/arfoundation-samples#160]
What is the correct way to switch Reference Image Libraries at runtime? In one of our apps the user can select different trigger options and we want to be able to switch them at runtime, ensuring the old trackables are hidden / destroyed as well.

**Comment by Oneiros90** [comment]
Unfortunately, it is not as easy as it looks. At all.
See my post on the Unity forum: https://forum.unity.com/threads/dynamic-xrreferenceimagelibrary-in-ar-foundation.681901/

**Comment by mimminito** [comment]
@Oneiros90 Thanks, ill take a look.

**Comment by tcz** [comment]
Both ARKit and ARCore support dynamic target loading. Can we expect some feedback from the Unity developers when can we expect this to be implemented in ARFoundation?

**Comment by tdmowrer** [comment]
I'm not sure what the ask is here. You can switch reference image libraries at runtime by setting the [`referenceLibrary`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_referenceLibrary) on the ARTrackedImageManager. This has always been the case.

In ARFoundation 3.0, you can [add new images to a reference library](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/tracked-image-manager.html#adding-new-reference-images-at-runtime) if it supports mutable reference libraries.

**Comment by Unity3D-Hardik** [comment]
Sorry to reopen but I am trying to switch image libraries (MutableRuntimeReferenceImageLibrary) at runtime after switching I can see an update in eventArgs.added when added new image but after not being able to track(eventArgs.updated does not work) that image.

Any solution or way to do this?
