### ISSUE TITLE
ARHumanBodyManager does not have a "supported" variable

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/arfoundation-samples#164]
ARFaceManager has a boolean variable called supported which is used to check if a device supports face tracking.

ARHumanBodyManager should have a similar value, since it is unlikely that Apple will add a plist field for bodytracking/segmentation, and it would save developers from having to parse through several ios.device.generation enumerations.

**Comment by tdmowrer** [comment]
Generally, if an entire subsystem is unsupported, it doesn't get registered (I actually think the `supported` boolean should be removed from the face manager; the subsystem should simply be null in that case).

In the case of the human body manager, you can check which specific features within the human body subsystem are supported by looking at its [descriptor](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@2.2/api/UnityEngine.XR.ARSubsystems.XRHumanBodySubsystemDescriptor.html). Each manager has a `descriptor` property that gives you this information, e.g., `ARHumanBodyManager.descriptor`

**Comment by sam598** [comment]
The application will crash if ARHumanBodyManager is run on an unsupported device, but checking if the subsystem is null works. Marking this as closed for now.
