### ISSUE TITLE
Fixing focus does not work iOS 13 + AR Foundation 2.2.0-preview.2

### ISSUE THREAD

**Issue by algomystic** [Unity-Technologies/arfoundation-samples#166]
Setting Focus to Fixed on the AR Camera Manager has no effect. Auto focus still messes about. 

iOS13 (beta)
ARFoundation 2.2.0-preview.2
iPhoneXS Max

**Comment by rilez** [comment]
Also having this issue

iOS 13 (beta)
ARFoundation 2.2.0-preview.2
iPhone X

**Comment by HawkenKing** [comment]
iOS 12 here and fixed-focus doesn't seem to work

**Comment by tdmowrer** [comment]
Try setting it to autofocus and then back to fixed.

**Comment by StartNight** [comment]
Is this problem fixed in the new version?

**Comment by mdurand42** [comment]
Yes, this issue was fixed in ARKit XR plugin 3.0.4 and later.
