### ISSUE TITLE
i use unity 2019.1.7 to build ARFundation in ios

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#167]
this is error 

Showing All Messages
:-1: Undefined symbol: _OBJC_CLASS_$_ARCollaborationData

:-1: Undefined symbol: _OBJC_CLASS_$_ARSkeletonDefinition

:-1: Undefined symbol: _OBJC_CLASS_$_ARBodyAnchor

:-1: Undefined symbol: _OBJC_CLASS_$_ARBodyTrackingConfiguration

:-1: Undefined symbol: _OBJC_CLASS_$_ARMatteGenerator

:-1: Undefined symbol: ___isPlatformVersionAtLeast

**Comment by tdmowrer** [comment]
This happens when you try to build the `master` branch with Xcode 10. See https://github.com/Unity-Technologies/arfoundation-samples#warning-arkit-3-support for more details and solution.

**Comment by mw-felker** [comment]
@Arytes you need to use the ARFoundation 2.1 package, not the 2.2 one. 

1) Open up Package Manager (Window > Package Manager)
2) Find ARFoundation in list (make sure Advanced > Show preview package is selected)
3) Use the arrow next to the package name, click Show Previous versions and select 2.1
4) Install the 2.1 package
5) Profit
