### ISSUE TITLE
ReferenceImageLibrary not copied to Xcode

### ISSUE THREAD

**Issue by rinatkhanov** [Unity-Technologies/arfoundation-samples#169]
I'm trying to re-create an AR image tracking app from AR Foundation samples. I've created a new project and (it looks like) I've re-created everything from sample project including image reference library and custom script. However, image reference library is not copied over from Unity to Xcode project for some reason. So, `trackedImagesChanged` in the script is never called. Sample app itself works as intented with my setup.

<img width="1062" alt="Screenshot 2019-06-21 at 09 40 02" src="https://user-images.githubusercontent.com/4293969/59903048-a4614c80-9408-11e9-9070-85c142f133d2.png">

I'm new to Unity. What else am I missing? How can I debug this properly?

**Comment by tdmowrer** [comment]
Have you added the ARKit XR Plugin package from the Package Manager?

ARFoundation is platform agnostic, so you also need to add the specific platform support.
<img width="623" alt="Screen Shot 2019-06-20 at 11 49 19 PM" src="https://user-images.githubusercontent.com/4934281/59903529-13fa1c00-93b6-11e9-8b70-a5230236d509.png">

**Comment by rinatkhanov** [comment]
Yes, I had an earlier version of ARKit XR Plugin package installed. Updating to 2.2.0 preview helped. Thanks!
