### ISSUE TITLE
Camera background doesn't render when using LightWeight Render Pipeline

### ISSUE THREAD

**Issue by renaudbedard** [Unity-Technologies/arfoundation-samples#17]
The AR camera background doesn't appear to draw when using the LWRP. I reproduced reports in this thread (https://forum.unity.com/threads/ar-foundation-and-the-lightweight-render-pipeline.539038/) with 2018.2.0f2.

It looks as if the camera never clears, so the content of past frames smears everywhere on the frame. Pose tracking does seem to work though.

![screenshot_20180711-085500](https://user-images.githubusercontent.com/251134/42572761-33ee8416-84e8-11e8-9c29-5f52ba9a5c53.png)

**Comment by renaudbedard** [comment]
I just read that this is a known limitation of the LWRP so it's probably not up to you guys (AR Foundation team).

https://blogs.unity3d.com/2018/07/10/2018-2-is-now-available/#lwrp
>Please note that LWRP is currently not supported for handheld AR, like ARCore or ARKit, or HoloLens or Magic Leap devices. New product plans will be communicated at a future date.

**Comment by nscobie** [comment]
Here's a temporary solution until an official fix is released: https://nolanscobie.com/2018/07/unity-mobile-ar-with-lwrp/

**Comment by bitfabrikken** [comment]
@nscobie thanks for the fix! I've used it in a production app and it works really well. I've just created two issues for specific devices, links below. Do you think your fix might have something to do with the iPhone 6 issue? It seems weird that it works on all the other iOS devices though.

Black camera view on iPhone 6: https://github.com/Unity-Technologies/arfoundation-samples/issues/38
Detection not working on OnePlus 6: https://github.com/Unity-Technologies/arfoundation-samples/issues/39

**Comment by Ursanon** [comment]
You can check out [this branch - lwrp_support](https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp_support) too.

**Comment by renaudbedard** [comment]
@Ursanon I just tried it in Unity 2018.3 beta and... black screen :)
https://forum.unity.com/threads/2018-3-beta.567523/#post-3891697

**Comment by Ursanon** [comment]
@renaudbedard oh, weird, I'm using this branch with 2018.3, and camera's image is correct.
Did you add `LWRPBeforeCameraRender` on your camera and set `CustomRenderAsset` under `ARCameraBehaviour`with correct asset?

**Comment by renaudbedard** [comment]
As hinted here, it was because "Graphics Jobs (Experimental)" was ticked on in my player settings, turning it off makes it work!
https://forum.unity.com/threads/2018-3-beta.567523/#post-3891724
