### ISSUE TITLE
HumanBodyTracking3D - not working

### ISSUE THREAD

**Issue by sridevipavithra** [Unity-Technologies/arfoundation-samples#170]
Hi, while trying to build the HumanBodyTracking3D sample scene, I got an error - nw_connection_receive_internal_block_invoke [C6] Receive reply failed with error "Operation canceled"
Nothing happens after that.
I'm using XCode - 11 beta and iPhone XS Max with iOS 13 beta. 
I've attached the log for your reference. 
Also, I do have an active WiFi.
[nw_connection_error.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/3313926/nw_connection_error.txt)

**Comment by Eisenhuth** [comment]
getting the exact same error(s) on iPadOS 13 (iPad Pro 11") using xcode 11, cloned from the master branch. The build finishes and runs on the device, but the errors show up in xcode's debug log

**Comment by nishantkumar** [comment]
@sridevipavithra The errors being logged seem to be due to iOS13 being a Beta release and don't seem related to the Human body tracking functionality.

To confirm, if you point the back camera at a person (or a video of a person standing/walking) do you see the robot appear on the screen?
Also, are you using **iOS 13 Beta "2"** (released on Jun 17th)? If so, we are working on integrating the changes in iOS 13 Beta 2 and body tracking functionality might not work as expected.

**Comment by sridevipavithra** [comment]
@nishantkumar  Yes! I'm using iOS 13 Beta 2. The body tracking functionalities don't work in this. Any idea when I can expect a working version? 

Meanwhile, I'll also check with iOS 13 Beta 1 and get back to you regarding that.
I also have a question, does the application require an active internet connection?

**Comment by nishantkumar** [comment]
@sridevipavithra We are actively working on fixing the iOS 13 Beta 2 issues, but do not have an ETA to share at the moment.
The human body tracking sample should not require an active internet connection.

**Comment by LukePenkava** [comment]
@sridevipavithra @nishantkumar 
Hi, i am having the same error. Let me please know if IOS 13 Beta 1 worked for you. I cant find it in developer account for download anyway.
 Could this error be perhaps related to some settings in Unity ?

**Comment by yosun** [comment]
Hi, I am only able to get the line renderer screen space joint to work, by simply adding it to HumanBody3D scene. 

The robot in the HumanBody3D scene does not work. 

On device: Receive reply failed with error "Operation canceled"

**Comment by yosun** [comment]
> @sridevipavithra The errors being logged seem to be due to iOS13 being a Beta release and don't seem related to the Human body tracking functionality.
> 
> To confirm, if you point the back camera at a person (or a video of a person standing/walking) do you see the robot appear on the screen?
> Also, are you using **iOS 13 Beta "2"** (released on Jun 17th)? If so, we are working on integrating the changes in iOS 13 Beta 2 and body tracking functionality might not work as expected.

Can you show an example video that demonstrates how the robot should load?

**Comment by kebiao** [comment]
I also have this problem, I hope to fix it as soon as possible.

**Comment by yosun** [comment]
I'm starting to finally use Unity Pro support for these issues. Hoping they can help allocate more support here!

**Comment by sridevipavithra** [comment]
@nishantkumar - Just checked wit iOS 13 Beta v1, the body tracking works and the robot is placed as expected. But I'm noticing a lot of difference between this and the Apple's BodyDetection Xcode project. The unity implementations seems unstable. When two people are in the room, the tracking becomes unstable and sometimes unresponsive. Is there a fix available for this? I'm using Unity version 2019.1.7f1.

**Comment by sridevipavithra** [comment]
@nishantkumar  If it does not require an internet connection, may I know why I'm getting this log?! 

2019-06-25 12:21:53.830383+0530 3DhumanTracking[776:161020] Connection 1: received failure notification
2019-06-25 12:21:53.830590+0530 3DhumanTracking[776:161020] Connection 1: failed to connect 1:50, reason -1
2019-06-25 12:21:53.830665+0530 3DhumanTracking[776:161020] Connection 1: encountered error(1:50)
2019-06-25 12:21:53.840378+0530 3DhumanTracking[776:161020] Task <A96A62A9-5BDA-414E-9CF6-E37F78910F7A>.<1> HTTP load failed, 0/0 bytes (error code: -1009 [1:50])
2019-06-25 12:21:53.853770+0530 3DhumanTracking[776:160999] Task <A96A62A9-5BDA-414E-9CF6-E37F78910F7A>.<1> finished with error [-1009] Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x2832b87e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <A96A62A9-5BDA-414E-9CF6-E37F78910F7A>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <A96A62A9-5BDA-414E-9CF6-E37F78910F7A>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://config.uca.cloud.unity3d.com/, NSErrorFailingURLKey=https://config.uca.cloud.unity3d.com/, _kCFStreamErrorDomainKey=1}

**Comment by yosun** [comment]
> @nishantkumar - Just checked wit iOS 13 Beta v1, the body tracking works and the robot is placed as expected. But I'm noticing a lot of difference between this and the Apple's BodyDetection Xcode project. The unity implementations seems unstable when compared to the one in native. When two or more people are in the room, the tracking becomes unstable and sometimes unresponsive. There are also cases where the it doesn't recognise someone at all. Is there a fix available for this? I'm using Unity version 2019.1.7f1.

Hi! I'm surprised you are able to get the robot to place - though I see the line renderer for body segmentation, for 3D robot.... it seems that for me OnHumanBodiesChanged is never called?

**Comment by sridevipavithra** [comment]
> Hi, I am only able to get the line renderer screen space joint to work, by simply adding it to HumanBody3D scene. I am running on the latest Unity 2019.1.7f1 and XCode Version 11.0 beta 2 (11M337n) and iPadOS 13.0 (17A5508m)


@yosun  You're using iPadOS 13 beta v2. Try downgrading it to beta version 1 (17A5492t) . It works.

**Comment by smurfkiller** [comment]
@sridevipavithra How did you downgrade from Beta 2 to Beta 1? I tried googling it for 1 hour but every description and link leads to only Beta 2.

**Comment by sridevipavithra** [comment]
@smurfkiller I had the IPSW config file for beta 1 with me even before before beta 2 launched. So it was easier I guess.

**Comment by smurfkiller** [comment]
@sridevipavithra Ah I see, then I'm probably out of luck. Thx :)

**Comment by yosun** [comment]
@sridevipavithra  just tried the public beta - same issue 

2019-06-26 12:51:39.449680-0700 humanbody[1827:177660] [] nw_connection_receive_internal_block_invoke [C3] Receive reply failed with error "Operation canceled"

**Comment by yosun** [comment]
> @sridevipavithra The errors being logged seem to be due to iOS13 being a Beta release and don't seem related to the Human body tracking functionality.
> 
> To confirm, if you point the back camera at a person (or a video of a person standing/walking) do you see the robot appear on the screen?
> Also, are you using **iOS 13 Beta "2"** (released on Jun 17th)? If so, we are working on integrating the changes in iOS 13 Beta 2 and body tracking functionality might not work as expected.

Just a note that this issue occurs also with the iOS 13 public beta 
Please fix it...

**Comment by davidj-bbc** [comment]
Public Beta 1 is the same as Dev Beta 2 @yosun FYI.

+1 for this being fixed though :)

**Comment by smurfkiller** [comment]
I found the Beta 1 IPSW here: http://www.iphonehacks.com/2019/06/download-ipados-beta-for-ipad.html
Now I see the robot sometimes somewhere and very small on the screen but it does not track anything.

**Comment by ryanscottmurphy** [comment]
I'm also having this issue on iOS 13 Beta "2"

**Comment by yosun** [comment]
yup - likewise iOS 13 beta2 as well as the public beta

**Comment by crocoking** [comment]
> @nishantkumar - Just checked wit iOS 13 Beta v1, the body tracking works and the robot is placed as expected. But I'm noticing a lot of difference between this and the Apple's BodyDetection Xcode project. The unity implementations seems unstable when compared to the one in native. When two or more people are in the room, the tracking becomes unstable and sometimes unresponsive. There are also cases where the it doesn't recognise someone at all. Is there a fix available for this? I'm using Unity version 2019.1.7f1.

 Can you tell me where to download iOS 13 Beta v1？I am using Beta v2.Please.

**Comment by crocoking** [comment]
> @sridevipavithra We are actively working on fixing the iOS 13 Beta 2 issues, but do not have an ETA to share at the moment.
> The human body tracking sample should not require an active internet connection.

Do you have a date when to fix this bug on iOS 13 Beta 2？

**Comment by yosun** [comment]
@shawmakesmusic hey, looks like you might have time to look into this issue

**Comment by shawmakesmusic** [comment]
> @shawmakesmusic hey, looks like you might have time to look into this issue

Negative, the bug is in the native code side, which is inside the compiled plugin DLLs, there's no not incredibly painful way around this without backporting to the version before :-/ really wish Unity would OSS their bridges because even just the people on this thread here is probably a bigger team with more time to focus on bugs than what they've got.

**Comment by ryanscottmurphy** [comment]
An update since yesterday, (sorry to harp). I've also tested this on Beta "3" (released today) and the problem is identical. I was able to acquire a device with Beta "1" and it works as expected.

**Comment by Felix-Izarra-Bose** [comment]
> An update since yesterday, (sorry to harp). I've also tested this on Beta "3" (released today) and the problem is identical. I was able to acquire a device with Beta "1" and it works as expected.

Where can I get the Beta 1? I installed the Beta 2 and it's not working but I can't find a link for the Beta 1.

**Comment by crocoking** [comment]
> > An update since yesterday, (sorry to harp). I've also tested this on Beta "3" (released today) and the problem is identical. I was able to acquire a device with Beta "1" and it works as expected.
> 
> Where can I get the Beta 1? I installed the Beta 2 and it's not working but I can't find a link for the Beta 1.

I got it Here: https://www.macx.cn/thread-2223154-1-1.html. Hope can help you.

**Comment by Felix-Izarra-Bose** [comment]
> > > An update since yesterday, (sorry to harp). I've also tested this on Beta "3" (released today) and the problem is identical. I was able to acquire a device with Beta "1" and it works as expected.
> > 
> > 
> > Where can I get the Beta 1? I installed the Beta 2 and it's not working but I can't find a link for the Beta 1.
> 
> I got it Here: https://www.macx.cn/thread-2223154-1-1.html. Hope can help you.

Everything is in Chinese, I will try, thanks.

If anyone have another source please post it!.

**Comment by vladimirshlygin** [comment]
Same issue with the Beta 3.

**Comment by yosun** [comment]
Any update?

**Comment by mitdave95** [comment]
The re-released beta 3 also has the same issue

**Comment by priisc** [comment]
Running into the same issue. 
looking forward to seeing an update.

**Comment by yosun** [comment]
Please fix!

**Comment by priisc** [comment]
> Please fix!

Did you try to downgrade to Beta1 from the above link @yosun ?
I know this is not an optimal solution and a clean fix would be much better but i am looking for a temporary solution :/

**Comment by yosun** [comment]
> > Please fix!
> 
> Did you try to downgrade to Beta1 from the above link @yosun ?
> I know this is not an optimal solution and a clean fix would be much better but i am looking for a temporary solution :/

I'm actually not allowed to downgrade - as my client absolutely demands that the project works with the iOS 13 public beta. Still waiting for the fix from Unity and been over a month - but may have to just actually do iOS native instead of using Unity.

**Comment by mitdave95** [comment]
> > > Please fix!
> > 
> > 
> > Did you try to downgrade to Beta1 from the above link @yosun ?
> > I know this is not an optimal solution and a clean fix would be much better but i am looking for a temporary solution :/
> 
> I'm actually not allowed to downgrade - as my client absolutely demands that the project works with the iOS 13 public beta. Still waiting for the fix from Unity and been over a month - but may have to just actually do iOS native instead of using Unity.

is there any open-source project for native implementation for this? if yes, can you send the link?

**Comment by yosun** [comment]
> > > > Please fix!
> > > 
> > > 
> > > Did you try to downgrade to Beta1 from the above link @yosun ?
> > > I know this is not an optimal solution and a clean fix would be much better but i am looking for a temporary solution :/
> > 
> > 
> > I'm actually not allowed to downgrade - as my client absolutely demands that the project works with the iOS 13 public beta. Still waiting for the fix from Unity and been over a month - but may have to just actually do iOS native instead of using Unity.
> 
> is there any open-source project for native implementation for this? if yes, can you send the link?

Yes, the code sample is available fresh and official from Apple even. https://developer.apple.com/documentation/arkit/capturing_body_motion_in_3d?changes=latest_beta 

Check out the quick test demo below. I am on the latest iOS 13 public beta. Just build and run and this human segmentation runs. **Clearly, HumanSegmentation3D on native development ARKit3 is working, but Unity is just taking incredibly long to fix this. **  Every day I keep checking back here, like it's Christmas or something but I'm going to just have to skip Unity and go native for this project. 

<a href="http://www.youtube.com/watch?feature=player_embedded&v=qdHPoyfshb4
" target="_blank"><img src="http://permute.xyz/arkit3.bodysegmentation3D.yogatest.gif" 
alt="native arkit3, not using Unity" width="240" height="180" border="10" /></a>

**Comment by tdmowrer** [comment]
Packages have been updated. Latest [Packages/manifest.json](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Packages/manifest.json#L11-L14) should look like this:
```
"com.unity.xr.arcore": "2.2.0-preview.1",
"com.unity.xr.arfoundation": "2.2.0-preview.3",
"com.unity.xr.arkit": "2.2.0-preview.2",
"com.unity.xr.arkit-face-tracking": "1.1.0-preview.2"
```

ARKit libraries are compiled with Xcode 11 beta 3 and are compatible with iOS 13 beta 3. As before, the ARKit package is not (yet) backwards compatible with iOS 12.

**Comment by yosun** [comment]
> Packages have been updated. Latest [Packages/manifest.json](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Packages/manifest.json#L11-L14) should look like this:
> 
> ```
> "com.unity.xr.arcore": "2.2.0-preview.1",
> "com.unity.xr.arfoundation": "2.2.0-preview.3",
> "com.unity.xr.arkit": "2.2.0-preview.2",
> "com.unity.xr.arkit-face-tracking": "1.1.0-preview.2"
> ```
> 
> ARKit libraries are compiled with Xcode 11 beta 3 and are compatible with iOS 13 beta 3. As before, the ARKit package is not (yet) backwards compatible with iOS 12.

Thank you @tdmowrer  for finally fixing this month+ long issue. 

I really wish I got this message yesterday though, (esp being a Unity developer for the last 11 years). I truly wanted to deliver my project in Unity but had to choose a native solution instead. I spent the morning catching up with Apple's RealityKit and Pixar USDZ format and ended up delivering my client project using native iOS. It was surprisingly easy and even with out of the box render results (being my first RealityKit app), my client was very happy!

**Comment by priisc** [comment]
Quick question after updating the library to the solution above. (My manifest looks similar to yours) 
I get 19 errors similar to: 
"Library/PackageCache/com.unity.xr.arfoundation@2.2.0-preview.3/Runtime/AR/MeshQueue.cs(5,37): error CS0234: The type or namespace name 'MeshId' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)" 
I am not quite sure where to dig in to fix this. Any pointer? :)

**Comment by noxxomatik** [comment]
Can somebody confirm that the tracking now works with iOS 13 Beta 4, Xcode 11 Beta 4 and "com.unity.xr.arkit": "2.2.0-preview.3", "com.unity.xr.arkit-face-tracking": "1.1.0-preview.3"?

I updated to this versions, but now it doesn't work again.

**Comment by sridevipavithra** [comment]
> Packages have been updated. Latest [Packages/manifest.json](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Packages/manifest.json#L11-L14) should look like this:
> 
> ```
> "com.unity.xr.arcore": "2.2.0-preview.1",
> "com.unity.xr.arfoundation": "2.2.0-preview.3",
> "com.unity.xr.arkit": "2.2.0-preview.2",
> "com.unity.xr.arkit-face-tracking": "1.1.0-preview.2"
> ```
> 
> ARKit libraries are compiled with Xcode 11 beta 3 and are compatible with iOS 13 beta 3. As before, the ARKit package is not (yet) backwards compatible with iOS 12.

What about iOS beta 5? Also, is it iOS developer v3 or public v3?
