### ISSUE TITLE
Image Tracking false positive problem

### ISSUE THREAD

**Issue by yosi1202** [Unity-Technologies/arfoundation-samples#176]
I am trying the image tracking with standard faces images of different peoples, but all the images are detected together as if they are all the same image, how can i fix this?

example images:
https://i.ibb.co/HPsJZfg/02.jpg
https://i.ibb.co/s5YM10B/01.jpg
https://i.ibb.co/mNhS5D8/04.jpg

**Comment by ethermammoth** [comment]
Having similar Issue with 4 different QR Code Markers, tested on ARCore / Android.
Looking at the List of ARTrackedImage provided by ARTrackedImagesChangedEventArgs -> eventArgs.added - i can see that once I point my camera at the first QR Code it recognizes almost every time all of them, although they are different QR Codes. 
I hope its a bug. Haven't tried directly in ARCore yet.

Also it would be awesome to have some kind of tracking feedback / confidence measure...

**Comment by ethermammoth** [comment]
Ok so i did test this directly inside ARCore. It has the same problems. My best guess, since i did not find anything about it in the documentation, is that the tracking algorithm most likely is comparing interesting features in the image from the database with the live feed - most likely having some distance values to the compared point clouds. Probably a threshold determines that all of the images are under a certain distance threshold and it spits them all out. 
So the Problem most likely needs to be tackled by Google - maybe with a little sanity filter - checking if it makes sense that it detects X amount of images at the same position. Hopefully we will get a confidence value along the way so we can do our own filtering / UX feedback as well.

**Comment by tdmowrer** [comment]
I agree that sounds like the images are simply too similar. It's possible this has improved in more recent versions of ARCore (and therefore more recent versions of ARCore XR Plugin).

**Comment by hasionerin** [comment]
> I agree that sounds like the images are simply too similar. It's possible this has improved in more recent versions of ARCore (and therefore more recent versions of ARCore XR Plugin).

Hello,
I have a question about image tracking in Ar Foundation.
Is there a way to get some kind of "threshold" for the recognized image? For example, I have 2 different / similar looking reference images and I would like to see how many percent the respective image applies to the reference.
At the moment I can't find a way to do this, except for the Enum: Tracked, Limited and None...
Is there no exact float value or similar?

Many thanks in advance and greetings

**Comment by hasionerin** [comment]
@hasionerin 
Hello,
I have a question about image tracking in Ar Foundation.
Is there a way to get some kind of "threshold" for the recognized image? For example, I have 2 different / similar looking reference images and I would like to see how many percent the respective image applies to the reference.
At the moment I can't find a way to do this, except for the Enum: Tracked, Limited and None...
Is there no exact float value or similar?

Many thanks in advance and greetings

**Comment by hasionerin** [comment]
> I agree that sounds like the images are simply too similar. It's possible this has improved in more recent versions of ARCore (and therefore more recent versions of ARCore XR Plugin).
@tdmowrer 
Hello,
I have a question about image tracking in Ar Foundation.
Is there a way to get some kind of "threshold" for the recognized image? For example, I have 2 different / similar looking reference images and I would like to see how many percent the respective image applies to the reference.
At the moment I can't find a way to do this, except for the Enum: Tracked, Limited and None...
Is there no exact float value or similar?

Many thanks in advance and greetings

**Comment by hasionerin** [comment]
> I agree that sounds like the images are simply too similar. It's possible this has improved in more recent versions of ARCore (and therefore more recent versions of ARCore XR Plugin).

@tdmowrer 

i take a photo , use this photo as marker , then use arfoundation to track this , when i track the photo ,it tracked quick,but when i track the real world , on ios devices, it tracked quick too , but on android devices , it tracked hard . so i think is there exits some api to reduce the tracked percent . or is there a way to quickly identify real scenes . thanks !
