### ISSUE TITLE
HumanBodyTracking2D - position offset

### ISSUE THREAD

**Issue by kebiao** [Unity-Technologies/arfoundation-samples#177]
The position of the skeleton in the demo is offset, especially after the person stops moving, the skeleton and the real person stand side by side.

And the jitter is very serious.

Is this the original effect of ARKit?

IPhone XS MAX,  xcode11beta2, ios13beta2

**Comment by sridevipavithra** [comment]
@kebiao I did try out that sample and I did not find any offset added to the skeleton's position. Infact, the line is renderer over the body as expected. 

But I did find it to be too jittery. I also noticed that if you lay down your phone on a table and observe, there are no jitters. It was stable. Only when I hold it in my hand, it seems unstable. 

Need a fix for this!

**Comment by kebiao** [comment]
My test, the skeleton can't fit the body many times.

![QQ图片20190626213233](https://user-images.githubusercontent.com/2352650/60184386-8b1e2d00-985a-11e9-81e5-66aac693e788.jpg)
![QQ图片20190626213013](https://user-images.githubusercontent.com/2352650/60184388-8bb6c380-985a-11e9-8f5d-f40494c5c2fa.jpg)

**Comment by yosun** [comment]
Maybe try not wearing a d

> My test, the skeleton can't fit the body many times.
> 
> ![QQ图片20190626213233](https://user-images.githubusercontent.com/2352650/60184386-8b1e2d00-985a-11e9-81e5-66aac693e788.jpg)
> ![QQ图片20190626213013](https://user-images.githubusercontent.com/2352650/60184388-8bb6c380-985a-11e9-8f5d-f40494c5c2fa.jpg)

try having the subject not wearing a dress, pants instead

**Comment by kebiao** [comment]
I have tried other adults, passing pants and shirts, the same result. FPS=60

I tried the official robot-3d example of apple, which is much better.
