### ISSUE TITLE
ARFoundation Regression between 2019.1.3f1 and 2019.1.8f1

### ISSUE THREAD

**Issue by Katerpilet** [Unity-Technologies/arfoundation-samples#178]
The lwrp-support-2019.1-with-2.1 SampleLWRPScene works on 2019.1.3, but is broken in 2019.1.8. On 2019.1.8 the plane ends up being in the air, while the outline for the plane is on the floor.

**Comment by tdmowrer** [comment]
2019.8 is not a version of Unity. Did you mean something else?

**Comment by Katerpilet** [comment]
Meant to type 2018.1.3 and 2018.1.8.

**Comment by tdmowrer** [comment]
The minimum supported version of Unity is 2018.4, and the samples project should not be openable in 2018.1.x. Sorry, I'm still not sure which version(s) you mean.

**Comment by Katerpilet** [comment]
I had a typo in my reply, but I updated the original comment, my reply, and the title to all represent the correct versions.

**Comment by yosun** [comment]
I agree that there seem to be some major issues that just don't work with 2019.1.8 (and .7) - that probably seem to have worked with  earlier versions 

Can you guys please post which versions that you have tested your samples to work with?

**Comment by Goncharuk-Nikita** [comment]
https://forum.unity.com/threads/ar-foundation-parrent-object-incorrectly-displayed-in-unity-2019-1-5f-and-highter.701714/

**Comment by tdmowrer** [comment]
Is this limited to LWRP-based applications?

**Comment by Goncharuk-Nikita** [comment]
I checked only LWRP + AR Foundation.

**Comment by xendav** [comment]
I have seen this issue on 2019.3.0a8, 2019.3.0a5, and 2019.1.10f1.

2019.1.2f1 worked correctly.

When using LWRP with AR Foundation, it looks like all objects render at the AR Session Origin.  The Line Renderer shows the outlines of the planes in the correct location, but the Mesh Renderer renders every plane centered at the origin.  I placed multiple objects in the sample scene at different locations parented on the session origin, AR camera, and the world.  All of them centered themselves in the same origin when the AR app started.  When I remove LWRP, everything renders in the correct locations with AR Foundation alone.

![Screenshot_AR Foundation Samples](https://user-images.githubusercontent.com/31217906/61321587-71c12e80-a7d1-11e9-95d4-3e906f1c41c5.jpg)

**Comment by BikutaAnkuta** [comment]
Bumping this thread, seems like the same thing I posted in #212. 
@xendav did you find anything more about this?

**Comment by Goncharuk-Nikita** [comment]
@BikutaAnkuta  Working on 2019.1.4f (this is the last stable for AR, I think) and can't update Unity version, this is sad (

**Comment by xendav** [comment]
@BikutaAnkuta I haven't found a solution to get it to work on later releases.  They may not be attaching to the spawned gameObject.  From what I have experienced, the spawned gameObject and any other object just end up at the same position.  I made an object made out of multiple pieces and it showed up in the same place as the ARPlanes with all of its parts centered.  The images below are the same scene.  I displayed the transform of each object at the top of the screen.  When I changed to LWRP, the ARPlanes and all three objects center themselves at a single location.  The materials of the three objects render with the parent's material.  If I moved closer, the wireframe cube would disappear and the color would change to the color of the next child.  Also, the script would no longer display the position of the three objects.  @Goncharuk-Nikita I agree.  I'm stuck on 2019.1.2f1 to get things to display correctly with LWRP.

![AR_LWRP_Bug](https://user-images.githubusercontent.com/31217906/61583325-3fc70980-aafc-11e9-829d-1156395f8d6a.jpg)

**Comment by BikutaAnkuta** [comment]
@Goncharuk-Nikita @xendav I can confirm that 2019.1.4f1 works like a charm for LWRP, when started from the lwrp-support-2019.1-with-2.1 sample. 

@tdmowrer One thing I would note, if 2019.1.4f1 is the last stable for LWRP and AR, the sample project should likely default to asking for that version, not 2019.1.5f1.

**Comment by mdurand42** [comment]
Please use URP instead of LWRP:
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/ar-camera-background-with-scriptable-render-pipeline.html
