### ISSUE TITLE
AR foundation Object tracking and Image tracking not working 

### ISSUE THREAD

**Issue by prasad-marne** [Unity-Technologies/arfoundation-samples#179]
I am able to build and run my app on Iphone 8 but image and object tracking is doing nothing. Just start the camera thats it!!

AR Foundation  2.1.0 preview 3
ARkit XR plugin 2.1.0 preview 5
xcode 10

**Comment by schkolne** [comment]
i had the same experience, i printed out the cube and cylinder, even scanned and defined my own object using -- https://developer.apple.com/documentation/arkit/scanning_and_detecting_3d_objects?language=objc

none of them would track. no one else on the internet seems to be talking about this example. does it even work?

**Comment by Hypnotistas** [comment]
On Android doesn't work either with 3.1.0 ARFoundation.
