### ISSUE TITLE
Replace camera feed with video as input to AR session

### ISSUE THREAD

**Issue by ShoziX** [Unity-Technologies/arfoundation-samples#180]
I want to pass a video as an input instead of the camera feed. Is it possible? So that the face tracking is done according to the face in the video and not in the camera feed. Is there support for this in ARFoundation?

**Comment by tdmowrer** [comment]
Not using the platform support that we provide (ACore and ARKit). ARCore and ARKit have their own solution that does not allow you to submit your own camera frames. You can, however, implement your own [XRFaceSubsystem](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@2.1/api/UnityEngine.XR.ARSubsystems.XRFaceSubsystem.html) using your own solution or something like [OpenCV](https://opencv.org/).
