### ISSUE TITLE
ARF 2.1 Plane Count ?

### ISSUE THREAD

**Issue by ghus86** [Unity-Technologies/arfoundation-samples#181]
Hi 

In version 1.0 we have access to plane count in the AR Plane Manager.
But now in version 2.1 it doesn't seem to be available. 

This is useful to guide the user can someone help with this  ?
@tdmowrer can you clarify this point ?

**Comment by tdmowrer** [comment]
```csharp
planeManager.trackables.count```

See also https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.1/api/UnityEngine.XR.ARFoundation.ARTrackableManager-4.html#UnityEngine_XR_ARFoundation_ARTrackableManager_4_trackables

**Comment by ghus86** [comment]
@tdmowrer thanks a lot the quick response =)

other thing I am facing problems is how to delete cloud points ? 
I know to disable but the game object to delete the objects is no longer exposed

**Comment by tdmowrer** [comment]
In a similar way, you can get the collection of point clouds from the point cloud manager:

```csharp
foreach (var pointCloud in pointCloudManager.trackables)
{
   pointCloud.gameObject.SetActive(false);
}
```

**Comment by ghus86** [comment]
@tdmowrer Thanks all fine now
