### ISSUE TITLE
Multiple face tracking (iOS, iPhone X)

### ISSUE THREAD

**Issue by fpavletic** [Unity-Technologies/arfoundation-samples#182]
Hi, I'm trying to get the FaceMesh and/or ARKitFaceBlendShapes to detect multiple faces. I've changed the  MaximumFaceCount to 3 as that is the maximum number of faces ARKit 3 claims to be able to track simultaneously, however both scenes only apply the mask to one of the people in camera's view. Am I doing something wrong?

I'm using Unity 2019.1.8f, xCode 11 Beta 2 and the iPhone X I'm deploying to is on iOS 13 Beta 2

**Comment by sridevipavithra** [comment]
iPhone X is not supported for that. Try with iPhone XS, XS Max, XR, and 2019 versions of the iPad Air and iPad Mini.
