### ISSUE TITLE
HumanBodyTracking3D - for Avatar model

### ISSUE THREAD

**Issue by crocoking** [Unity-Technologies/arfoundation-samples#187]
I notice that for 3D detection, humans are represented by a hierarchy of ninety-three joints with world-space transforms. My question is how to correspond to the ninety-three joints if I use Unity avatar for my model.

**Comment by nikolahitek** [comment]
Anyone got a solution? 
When I replace it with my model with the same rigging pattern it gets very deformed when human tracking starts.

**Comment by mdurand42** [comment]
Unity has the capability to retarget animations. So you should be able to adapt the ARkit humanoid representation. 
https://docs.unity3d.com/Manual/Retargeting.html
