### ISSUE TITLE
ARF2.1 Branch holds ARF2.2. When downgraded errors

### ISSUE THREAD

**Issue by sergiosolorzano** [Unity-Technologies/arfoundation-samples#191]
Hi, ARF2.1 with LWRP Branch holds ARF2.2 version. When ARF version changed to 2.1 errors come up. 
How get a working branch from the outset with ARF 2.1 LWRP version ? 
Im on Unity2019.1.5, platform ios
Thanks
![ARF21](https://user-images.githubusercontent.com/24430655/60703817-a2b08200-9efa-11e9-8832-38cbc14e317d.png)
After downgraded to ARF 2.1 preview.3
![errors](https://user-images.githubusercontent.com/24430655/60703896-d2f82080-9efa-11e9-81b1-7311d8943634.png)

**Comment by mw-felker** [comment]
I can confirm this. Have Unity 2019.1.8f and my target is iOS device (11/12). Pulled the master branch down for the examples project and it looks like it came with ARFoundation 2.2. preview package. 

However, 2.2 only is supporting iOS13 devices and 2.1 is recommended for stable implementation. When I downgrade from 2.2 to 2.1, I also get the following errors:

<img width="1408" alt="Screen Shot 2019-07-07 at 6 17 21 PM" src="https://user-images.githubusercontent.com/851978/60774549-799f1580-a0e3-11e9-8efc-02f24a9289e4.png">

**Comment by sergiosolorzano** [comment]
Updating the manifest to 2.1 for both ARKIT and ARFoundation before opening leads to the errors on console highlighted above, can someone please shed some light how to open a working project on ARF2.1?
