### ISSUE TITLE
Not detecting floor properly and object gets stuck to the camera on Android device

### ISSUE THREAD

**Issue by santosh9604** [Unity-Technologies/arfoundation-samples#192]
Hi ,
Created this AR application using AR Foundation in unity for both : ios and android.
When built for ios everything was perfectly fine . also when built the same project for android with "Mono" back-end ( development build ) , everything was good , but when I built same thing using "IL2CPP" back-end , it gives following issues:'
1. Black Screen problem 
2. Not detecting floor properly and object gets stuck to the camera 

Please help me to resolve this issue.
thanks in Advance !

**Comment by enslaved2die** [comment]
Same issue here with the LWRP Branch

**Comment by tdmowrer** [comment]
Is this still an issue?
