### ISSUE TITLE
Foundation's ARCore does not support IOS device?

### ISSUE THREAD

**Issue by taurushz** [Unity-Technologies/arfoundation-samples#194]
Offical ARCore solution supports iOS device.
Why newest Foundation not support?
Cause I want to make just like iphone 6s - 8 facetracking work

**Comment by tdmowrer** [comment]
We have no plans to support face tracking on iOS via ARCore. If you want to support iOS devices that lack a TrueDepth camera, you might consider [OpenCV](https://opencv.org/) for face tracking.
