### ISSUE TITLE
Is there a demo same as iOS native demo "Occluding Virtual Content with People"?

### ISSUE THREAD

**Issue by crocoking** [Unity-Technologies/arfoundation-samples#198]
I have just have my unity AR foundation and IOS updated to the latest preview version. I tried to get the new fancy feature people occlusion works but have no idea where to start with.
I run the iOS demo "Occluding Virtual Content with People".I want to do the same as the iOS demo by ARFoundation.
So what I should do? Write my own shader? help...

**Comment by artistd36** [comment]
Any update on people occlusion?
How to use in untiy?

**Comment by MrMatthias** [comment]
Check the HumanSegmentationImages examples. Currently you can't use pose estimation and segmentation images at the same time though, might change in later iOS versions

**Comment by smxthereisonlyone** [comment]
> Check the HumanSegmentationImages examples. Currently you can't use pose estimation and segmentation images at the same time though, might change in later iOS versions

Are they both working together natively outside of Unity?

**Comment by tdmowrer** [comment]
The [AROcclusionManager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html) supports this feature. It is used by the SimpleAR sample, for example.
