### ISSUE TITLE
Duplicate planes

### ISSUE THREAD

**Issue by aidanwolf** [Unity-Technologies/arfoundation-samples#199]
Over a 2 minute session on iOS, I will easily get 2-4 planes on the same surface, all with slightly varying heights (1-10cm.) This cripples placing accuracy, making planes overall useless.

[https://imgur.com/invwIol.jpg](https://imgur.com/invwIol.jpg)

This doesn't happen while using the ARKit plugin in the same scenario.

Unity 2019.1.8f
ARFoundation 2.2.0

**Comment by tdmowrer** [comment]
I haven't experienced this. What exact versions of ARFoundation, ARKit XR Plugin package, Xcode, and iOS are you using? Also what device?

I also recommend upgrading from ARFoundation 2.2 to ARFoundation 3.0.
