### ISSUE TITLE
ARKit Package Import Fail

### ISSUE THREAD

**Issue by FoxtailGames** [Unity-Technologies/arfoundation-samples#20]
Updating to the new packages seems to give this error:

`Assertion failed: Removing Packages/com.unity.xr.arkit/npm-debug.log because the asset does not exist
`
Causing the package manager to uninstall the ARKit package. Running 2018.1.3f1 on mac.

**Comment by timm-unity** [comment]
Looks like a debug log metafile snuck into the package. However, that shouldn't cause the package manager to then uninstall the entire package (the error looks like it removed the metafile). Is it really removing the entire package?

**Comment by FoxtailGames** [comment]
Yeah it’s removing the whole thing, making it unusable
