### ISSUE TITLE
Some problems that I found in HumanSegmentationImages demo

### ISSUE THREAD

**Issue by boboEmily** [Unity-Technologies/arfoundation-samples#200]
Some problems that I found in HumanSegmentationImages demo:

1. Depth and stencil are flipped horizontally.

2. When holding phone in portrait mode, depth/stencil are not rotating accordingly.

3. Depth and stencil don’t have the same aspect ratio as the screen (they are sensing more information in vertical direction).

5. Only “Standard Resolution” can be selected for Human Segmentation Depth Mode (ARHumanBodyManager).

6. Even though “Full Screen Resolution” works for Human Segmentation Stencil Mode, it’s actually not full screen resolution. My screen is 2436 * 1125, and stencil texture is 1920 * 1440.

Unity 2019.1.8
iOS 17A5508m

**Comment by DiannaUnity** [comment]
It is in the backlog to better the samples repo, but for now it is in the user's hand to make the changes to rotation, flip, etc..
We are only exposing what's provided by the SDK.

We hope to provide a more refined samples repo in the future :)!

**Comment by SmileSbear** [comment]
In Human Segmentation Images, I only see human Stencil Texture and human Depth Texture. I would like to ask what is the way to achieve people occlusion?

**Comment by boboEmily** [comment]
Thank you for your reply, but this one I feel is hard to fix from the user side: 
Only “Standard Resolution” can be selected for Human Segmentation Depth Mode (ARHumanBodyManager). Resolution of depth texture is restricted to a very low mode.
