### ISSUE TITLE
Branch "lwrp-support-2019.1-with-2.1" Not Compatible with 2.1

### ISSUE THREAD

**Issue by JasonRTBond** [Unity-Technologies/arfoundation-samples#202]
This branch implies in its name that it is compatible with ARFoundation 2.1, but it is not. It includes samples which are only for ARFoundation 2.2.

**Comment by JasonRTBond** [comment]
Pardon me. Didn't realise issues aren't associated with branches. Added which branch I'm talking about in the title.

**Comment by tdmowrer** [comment]
Thanks for reporting. ARFoundation 3.0 includes much better support for LWRP/Universal RP, and that branch has been deleted.
