### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$_ARMatteGenerator

### ISSUE THREAD

**Issue by webloverand** [Unity-Technologies/arfoundation-samples#203]
unity Version : 2018.4
AFoundation Version : 1.5.0 preview.5
ARKit XR Plugins Version : 2.2.0 preview.1
XCode Version : 11 beta

Run error reporting after packaging:
dyld: Symbol not found: _OBJC_CLASS_$_ARMatteGenerator
  Referenced from: /var/containers/Bundle/Application/5D012AA5-7920-42FB-A5BF-E0FB5AEC203D/SpaceGo.app/SpaceGo
  Expected in: /System/Library/Frameworks/ARKit.framework/ARKit
 in /var/containers/Bundle/Application/5D012AA5-7920-42FB-A5BF-E0FB5AEC203D/SpaceGo.app/SpaceGo

Why is that?

**Comment by tdmowrer** [comment]
Xcode 11 beta requires iOS 13 beta. Please see https://github.com/Unity-Technologies/arfoundation-samples#warning-arkit-3-support
