### ISSUE TITLE
iPad OS Beta3 support ARFoundation?

### ISSUE THREAD

**Issue by artistd36** [Unity-Technologies/arfoundation-samples#204]
Just to clarify, iPad OS Beta3 support ARFoundation? In my case Unity HumanBodayTracking3D not working. Controlled Robot model not shown in build.

**Comment by yosun** [comment]
Yup, also confirmed

N.B. has been borked since dev beta 2 or public beta 1 - been over a month now. 

See here 
https://github.com/Unity-Technologies/arfoundation-samples/issues/170
