### ISSUE TITLE
ARFoundation and ARKit feature anchors - ML classifiers 

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#208]
It looks like ARKit natively lets you augment to objects its ML model classifies as tables, etc. Beyond just plane detection in Unity, is it possible in ARFoundation's ARKit3 wrap to also poll for anchorEntity classification? 

https://developer.apple.com/documentation/realitykit/anchoringcomponent/target/classification

**Comment by tdmowrer** [comment]
As far as I know, this only applies to [plane anchors in ARKit](https://developer.apple.com/documentation/arkit/arplaneanchor/classification). The anchor sharing in ARKit3 via [ARCollaborationData](https://developer.apple.com/documentation/arkit/arcollaborationdata?language=objc) does not support plane anchors.
