### ISSUE TITLE
CS0234 & CS0246 Errors w/ ARFoundation Samples

### ISSUE THREAD

**Issue by brianbatista** [Unity-Technologies/arfoundation-samples#210]
After downloading the Samples package and opening it in Unity, I got 19 errors. A few of them:

`Library\PackageCache\com.unity.xr.arfoundation@2.2.0-preview.3\Runtime\AR\MeshQueue.cs(13,49): error CS0246: The type or namespace name 'MeshInfo' could not be found (are you missing a using directive or an assembly reference?)`

`Library\PackageCache\com.unity.xr.arfoundation@2.2.0-preview.3\Runtime\AR\MeshQueue.cs(5,37): error CS0234: The type or namespace name 'MeshId' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)`

`Library\PackageCache\com.unity.xr.arfoundation@2.2.0-preview.3\Runtime\AR\ARMeshManager.cs(156,16): error CS0246: The type or namespace name 'XRMeshSubsystem' could not be found (are you missing a using directive or an assembly reference?)`

Any ideas on what I should do? Tried searching here but couldn't find anyone with the same problem..

Versions:
Unity: 2019.3.0a3
ARFoundation 2.2.0
ARCore 2.2.0
ARKit 2.2.0
ARKit Face Tracking 1.1.0

**Comment by brianbatista** [comment]
Apparently it solved itself. I have no idea how. Literally just reopened the project, and it was all fine. Go figure.

**Comment by brianbatista** [comment]
Fun of this closed button to glitch on me.
Anyhow, still having problems with this. Redownloading Unity / the Samples project didn't work either.

**Comment by tdmowrer** [comment]
The latest ARFoundation includes support for one new feature whose namespace will change in 2019.3. For now, either use 2019.1, 2019.2, or an earlier release of ARFoundation.

**Comment by LoryCool** [comment]
Hi.
Downgrade your AR Foundation version to 2.0.2 into the Package Manager. It's work for me.

**Comment by brianbatista** [comment]
> Going to Unity 2019.1 worked perfectly.
> Downgrading to AR Foundation V2.0.2 using Unity 2019.3 did NOT work. I just got different errors.

Thanks for the suggestions tho.

**Comment by leemuljadi** [comment]
If the ARFoundation could not be used in Unity 2019.3 for Android, is that means that ARFoundation cannot be used for both iOS and Android at the same time as the iOS need Unity 2019.3? Any solution for this?

Thanks!

**Comment by tdmowrer** [comment]
> If the ARFoundation could not be used in Unity 2019.3 for Android, is that means that ARFoundation cannot be used for both iOS and Android at the same time as the iOS need Unity 2019.3? Any solution for this?
> 
> Thanks!

ARFoundation is 2019.3 compatible. The samples in this repo can be opened in 2019.2 or 2019.3 and have been tested with Android and iOS.
