### ISSUE TITLE
Human Segmentation Depth Mode not working - no depth information

### ISSUE THREAD

**Issue by jBachalo** [Unity-Technologies/arfoundation-samples#211]
With HumanSegmentation Stencil Mode set to disabled and Human Segmentation Depth Mode set to Standard or half Screen or Full Screen Resolution on deploy to my iPhone XR I am only seeing a blank (white) inset window with no depth information.
If I set Stencil mode to anything other than disabled it seems to override the Depth Mode.

Following are my specs
"com.unity.xr.arcore": "2.2.0-preview.1",
"com.unity.xr.arfoundation": "2.2.0-preview.3",
"com.unity.xr.arkit": "2.2.0-preview.2",
"com.unity.xr.arkit-face-tracking": "1.1.0-preview.2"

Xcode 11 beta 4 used for compiling

iOS 13 beta 4 installed on my device

**Comment by tdmowrer** [comment]
com.unity.xr.arkit 2.2.0-preview.2 was compiled with Xcode 11 beta 3 and requires a device running iOS beta 3.

com.unity.xr.arkit 2.2.0-preview.3 is now available and supports Xcode 11 beta 4 and iOS beta 4.

**Comment by NumaNumaNuma** [comment]
I'm having the same problem with the xcode + ios 13 beta 5. Just blank images, textures come up as null no matter what segmentation setting I use.
@jBachalo did you manage to fix it?

**Comment by NumaNumaNuma** [comment]
@tdmowrer Any help? :) 
using com.unity.xr.arkit 2.2.0-preview.4 with the beta 5 xcode/ios

**Comment by tdmowrer** [comment]
This was probably an issue during the Xcode 11 beta. Is this still an issue in the latest ARFoundation?
