### ISSUE TITLE
ARPlanes are transparent except outline?

### ISSUE THREAD

**Issue by BikutaAnkuta** [Unity-Technologies/arfoundation-samples#212]
Using SimpleAR scene, ARPlanes are transparent except their outlines no matter what material I use on the sample plane prefab.

Unity Version: 2019.1.5
Project Branch: lwrp-support-2019.1-with-2.1
Scene: SimpleAR
Plane Prefab: AR LWRP Plane Debug Visualizer
Plane Material: LWRPPlane

Device: Galaxy S9+

Steps to reproduce: 
1. Download project from repo
2. Set custom renderer in ARCameraBackground (otherwise no camera image)
3. Set plane prefab in ARPlaneManager (for LWRP shader)
4. Build and run

Any detected planes will be outlined in black, but entirely transparent.

**Comment by tdmowrer** [comment]
This sounds like you haven't updated your materials to LWRP (now UniversalRP). See https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.2/manual/upgrading-your-shaders.html
