### ISSUE TITLE
HumanSegmentationImages

### ISSUE THREAD

**Issue by SmileSbear** [Unity-Technologies/arfoundation-samples#213]
In Human Segmentation Images, I only see human Stencil Texture and human Depth Texture. I would like to ask what is the way to achieve people occlusion?

**Comment by blurxs** [comment]
i guess somehow with a shader but i'm not very experienced writing shaders. anyone has an idea?

**Comment by tdmowrer** [comment]
The [AROcclusionManager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html) manager supports this out-of-the-box. It is used by the SimpleAR sample.
