### ISSUE TITLE
Send and receive ARCollaborationData by MultipeerConnectivity Framework 

### ISSUE THREAD

**Issue by crocoking** [Unity-Technologies/arfoundation-samples#214]
I am working with the ARCollaborationData. AF demo sends ARCollaborationData to other devices by TCP.
I want to send and receive ARCollaborationData by apple's MultipeerConnectivity Framework.
my problem is that how to send ARCollaborationData c#-> oc,  then oc ->c# with high efficiency?
byte[] -> string ->NSData ，NSData -> string->byte[] ？or anything else?
Hope for help，forgive me if you misunderstand, my English is poor.

**Comment by tdmowrer** [comment]
This was added a little while ago. The [collaborative session sample](https://github.com/Unity-Technologies/arfoundation-samples/tree/master/Assets/Scenes/ARCollaborationData) uses the MultipeerConnectivity framework.
