### ISSUE TITLE
Does AR Foundation support ARKit 3 Simultaneous Front and Back Camera?

### ISSUE THREAD

**Issue by boboEmily** [Unity-Technologies/arfoundation-samples#215]
Hi I wonder does the latest AR Foundation support ARKit 3 Simultaneous Front and Back Camera feature?

I checked RearCameraWithFrontCameraFaceMesh scene from AR Foundation samples, but it doesn't demonstrate how to use front camera to enable face tracking and at the same time using device full orientation and position information.

Does Unity plan to create a demo like that?

Also I am curious whether user can get human depth and stencil texture from front camera, just like the human occlusion demo, but depth is from front camera instead of back camera. I tried to attached both ARHumanBodyManager and ARFaceManager on ARSessionOrigin, and it seems like as long as ARHumanBodyManager is turned on, it's using back camera, not front.

Thanks!

**Comment by tdmowrer** [comment]
> I checked RearCameraWithFrontCameraFaceMesh scene from AR Foundation samples, but it doesn't demonstrate how to use front camera to enable face tracking and at the same time using device full orientation and position information.

This mode of operation uses the texture from the rear camera for the background renderer. The front camera is only used to detect faces.

You get the usual notifications from ARFaceManager, including the face position, mesh, blendshapes, etc. One possible use case is to puppet a virtual character in front of the rear camera.

> Also I am curious whether user can get human depth and stencil texture from front camera, just like the human occlusion demo, but depth is from front camera instead of back camera. I tried to attached both ARHumanBodyManager and ARFaceManager on ARSessionOrigin, and it seems like as long as ARHumanBodyManager is turned on, it's using back camera, not front.

The "rear camera with front camera face mesh" should support people occlusion, though I've not tried those together. You also need a device that supports the A12 bionic chip to use people occlusion.

**Comment by boboEmily** [comment]
Thank you for your reply!

So does Unity provide functionality that using the texture from the front camera for background renderer, at the same time provide full device orientation and position, and also people occlusion with front camera (providing human depth and stencil texture from front camera)?

A demo showing what I am looking for:
https://www.youtube.com/watch?v=9-h3GiF6TfI

**Comment by edwonia** [comment]
> > I checked RearCameraWithFrontCameraFaceMesh scene from AR Foundation samples, but it doesn't demonstrate how to use front camera to enable face tracking and at the same time using device full orientation and position information.
> 
> This mode of operation uses the texture from the rear camera for the background renderer. The front camera is only used to detect faces.
> 
> You get the usual notifications from ARFaceManager, including the face position, mesh, blendshapes, etc. One possible use case is to puppet a virtual character in front of the rear camera.
>

Yes I'm trying to do exactly that i.e. puppet a virtual character in front of the rear camera. No matter what I try though, the Face Manager changes it to render using the front camera, but I want it to rendere the rear camera WHILE use using the front camera for face data.

**Comment by rxmarcus** [comment]
@tdmowrer 
Will it ever be possible that we can get a video feed from both Rear and Front cameras simultaneously? Or is the Front camera only able to provide facial CV data while the Rear camera is providing a video stream?

**Comment by tdmowrer** [comment]
> @tdmowrer
> Will it ever be possible that we can get a video feed from both Rear and Front cameras simultaneously? Or is the Front camera only able to provide facial CV data while the Rear camera is providing a video stream?

That depends on Apple. Currently, each [ARConfiguration](https://developer.apple.com/documentation/arkit/arconfiguration) maps directly to one camera feed.
