### ISSUE TITLE
HumanBodyTracking3D  Bone rotation error

### ISSUE THREAD

**Issue by SmileSbear** [Unity-Technologies/arfoundation-samples#218]
怎么建立骨骼才能和ControlledRobot的旋转一样
How to build a skeleton is the same as the rotation of ControlledRobot

**Comment by crocoking** [comment]
我也在思考这个问题，项目里面的人物用到了Avatar，没办法，只能去一个个对应起来，但是对应起来发现还是有问题，看了这个帖子，发现有点帮助，你如果发现有更好的解决办法，可以贴出来啊。
https://forum.unity.com/threads/example-rig-for-3d-human-skeleton.696512/

**Comment by anyechushang** [comment]
也有相同的疑问？希望能有一个文档介绍。
Same question? I hope there is a document about it.

**Comment by tdmowrer** [comment]
Did the forum help? If you are trying to use a different asset, Unity has support for [animation retargeting](https://docs.unity3d.com/Manual/Retargeting.html), which may help..

**Comment by thornebrandt** [comment]
Why was this issue closed?  The linked forum is an open issue.
