### ISSUE TITLE
ARCollaboration Sync Information

### ISSUE THREAD

**Issue by blurxs** [Unity-Technologies/arfoundation-samples#219]
Is there any way to find out if the devices are in sync?
when i didn't scan enough information, the object does not show on the second device.
then when i scan more feature points it suddelny appears.
Can i somehow know before when they are synchron to show the users that they have to scan more.

thanks for any help

**Comment by blurxs** [comment]
achieved it by placing an invisible object with a syncObject tag and then sent back a custom message when it appears on the 2nd device

**Comment by crocoking** [comment]
> achieved it by placing an invisible object with a syncObject tag and then sent back a custom message when it appears on the 2nd device

There is a question you can find in ARKit according to apple. But I cannot find it in ARFoundation.
![image](https://user-images.githubusercontent.com/14910281/62516400-93a15480-b857-11e9-9916-33792820ac60.png)
[apple ARKit](https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/3152987-collaborationenabled)

**Comment by blurxs** [comment]
this seems like exactly i was looking for in arfoundation but i didn't find anything like that as well.
i'd prefer a proper solution instead of my "hack" as well.

**Comment by crocoking** [comment]
> this seems like exactly i was looking for in arfoundation but i didn't find anything like that as well.
> i'd prefer a proper solution instead of my "hack" as well.

What I think is that is it possible you can know other devices' location realtime?  Not just  Sync Information. It's an exciting ideal. What do you think?

**Comment by blurxs** [comment]
i don't understand the question. yes i think its possible with what we already have. not sure though.

**Comment by tdmowrer** [comment]
ARParticipantAnchors are supported as of [ARFoundation 3.0.0-preview.1](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/changelog/CHANGELOG.html#300-preview1---2019-08-21) and the [collaborative session sample](https://github.com/Unity-Technologies/arfoundation-samples/tree/master/Assets/Scenes/ARCollaborationData) has been updated to visualize them.
