### ISSUE TITLE
AR Foundation Face Tracking Support on Android

### ISSUE THREAD

**Issue by sai891215** [Unity-Technologies/arfoundation-samples#221]
Hi,
Does AR Foundation supports face tracking on Android devices? Since ARCore now officially support face tracking.

Best,
Shengzhi

**Comment by PetterGs** [comment]
bump

**Comment by PetterGs** [comment]
https://github.com/Unity-Technologies/arfoundation-samples#face-tracking

**Comment by tdmowrer** [comment]
Yes, face tracking is supported on iOS and Android.

**Comment by TheIntellify-Hardik** [comment]
> Yes, face tracking is supported on iOS and Android. On iOS, face tracking requires a device with a TrueDepth sensor.

Is there any way to render only face on Plane or cube, like Instagram filter ?? I am trying to create Face hole Filter using AR Foundation. 
for example https://i.pinimg.com/originals/51/b4/2f/51b42ff953939a025f687e2bc00942dd.png
