### ISSUE TITLE
RearCameraWithFrontCameraFaceMesh

### ISSUE THREAD

**Issue by artistd36** [Unity-Technologies/arfoundation-samples#222]
When we use both cameras on in our app, the front camera works fine with blendshape (morphing) but with the back camera, if we enable AR face script on the 3D model, it does not augment. And if we disable AR Face script it augments ok, but blend shape does not work properly.

I used RearCameraWithFrontCameraFaceMesh sample but it's not working.
Does any sample provide for this?

**Comment by SmileSbear** [comment]
Me too. Have you solved it?

**Comment by edwonia** [comment]
I'm having the same issue, thread on the unity forums about it as well: https://forum.unity.com/threads/does-ar-foundation-support-arkit-3-simultaneous-front-and-back-camera.711383/

**Comment by artistd36** [comment]
@edwonia Any success with the new update?

**Comment by edwonia** [comment]
> @edwonia Any success with the new update?

which update are you referring to?

**Comment by artistd36** [comment]
Xcode 5 support update

**Comment by edwonia** [comment]
I'm guessing this has more to do with the Unity plugin side of things, but I'll test Xcode beta 5 and see if it works

**Comment by artistd36** [comment]
Any update?

**Comment by tdmowrer** [comment]
iOS 13.1 and Xcode 11 are out of beta and supported by ARFoundation 3.0.0-preview.3. Is this still an issue using those versions? Note that face tracking with the rear camera requires a device with an A12 bionic chip.

**Comment by artistd36** [comment]
@tdmowrer 
Please provide an example scene to avoid this issue.
I have Ipad 2018

**Comment by tdmowrer** [comment]
Use of the rear camera with face tracking enabled (i.e., the `RearCameraWithFrontCameraFaceMesh` sample scene) requires an [A12 bionic chip](https://en.wikipedia.org/wiki/Apple_A12#Products_that_include_the_Apple_A12_Bionic) and therefore only works on certain devices. For instance the iPhone XS supports this feature, but not the iPhone X.

Does your iPad have an A12 chip?

To confirm blend shapes work in this mode, I put this script on the `FaceMeshPrefab` and ran the sample app:

```csharp
using System.Text;
using Unity.Collections;
using UnityEngine;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARKit;

[RequireComponent(typeof(ARFace))]
public class PrintBlendShapes : MonoBehaviour
{
    void Update()
    {
#if UNITY_IOS
        if (FindObjectOfType<ARFaceManager>() is ARFaceManager manager)
        {
            if (manager.subsystem is ARKitFaceSubsystem subsystem)
            {
                using (var blendShapeCoefficients = subsystem.GetBlendShapeCoefficients(GetComponent<ARFace>().trackableId, Allocator.Temp))
                {
                    var sb = new StringBuilder();
                    foreach (var coefficient in blendShapeCoefficients)
                    {
                        sb.Append($"\t{coefficient.blendShapeLocation}: {coefficient.coefficient}\n");
                    }
                    Debug.Log($"Blend shape coefficients:\n{sb.ToString()}");
                }
            }
        }
#endif
    }
}
```
Looking at the log in Xcode, the values appear reasonable. Others on this forum have also reported blendshapes are working correctly in this mode.

**Comment by artistd36** [comment]
Thanks for answering, Its working without augmenting ARface.
When using both cameras on in-app, the front camera works fine with blendshape (morphing) but with the back camera, if we enable AR face script on the 3D model, it does not augment. And if we disable AR Face script it augments ok, but blend shape does not work properly.

**Comment by tdmowrer** [comment]
Does your device have an A12 bionic chip?

**Comment by artistd36** [comment]
Yes, I am using iPad 2018

**Comment by tdmowrer** [comment]
What is the model number?

**Comment by artistd36** [comment]
A1934 is model number of My iPad

**Comment by tdmowrer** [comment]
> A1934 is model number of My iPad

Okay, that device should be supported.

> if we enable AR face script on the 3D model, it does not augment.

What does that mean exactly? I am able to get an ARFace with blend shapes using the script I posted above.
