### ISSUE TITLE
The type or namespace name 'ARCollaborationData' could not be found

### ISSUE THREAD

**Issue by ChakreyaYan** [Unity-Technologies/arfoundation-samples#225]
Hi, 
I'm using Unity 2019.1.8, AR foundation 2.2.0-preview 3 with ARKit XR plugin 2.1.0-preview 5 for developing AR app with iOS 12.3 and Xcode 10.2.1. 
I have downloaded AR foundation sample from github: https://github.com/Unity-Technologies/arfoundation-samples . 
when I opened AR foundation sample scene and updated ARKit XR plugin version 2.1.0- preview 5, it alerted some errors:
1. Assets\Scenes\ARCollaborationData\TCPConnection.cs(119,11): error CS0246: The type or namespace name 'ARCollaborationData' could not be found (are you missing a using directive or an assembly reference?)
2. Assets\Scenes\ARCollaborationData\TCPConnection.cs(121,11): error CS0246: The type or namespace name 'ARCollaborationData' could not be found (are you missing a using directive or an assembly reference?)

How can I solve above issues ? 
Thank you very much for you help. 

![unity](https://user-images.githubusercontent.com/25259233/61757083-017e6280-adfa-11e9-899f-2b1a452dbdd6.PNG)

**Comment by mdurand42** [comment]
> Hi,
> I'm using Unity 2019.1.8, AR foundation 2.2.0-preview 3 with ARKit XR plugin 2.1.0-preview 5 for developing AR app with iOS 12.3 and Xcode 10.2.1.
> I have downloaded AR foundation sample from github: https://github.com/Unity-Technologies/arfoundation-samples .
> when I opened AR foundation sample scene and updated ARKit XR plugin version 2.1.0- preview 5, it alerted some errors:
> 
> 1. Assets\Scenes\ARCollaborationData\TCPConnection.cs(119,11): error CS0246: The type or namespace name 'ARCollaborationData' could not be found (are you missing a using directive or an assembly reference?)
> 2. Assets\Scenes\ARCollaborationData\TCPConnection.cs(121,11): error CS0246: The type or namespace name 'ARCollaborationData' could not be found (are you missing a using directive or an assembly reference?)
> 
> How can I solve above issues ?
> Thank you very much for you help.
> 
> ![unity](https://user-images.githubusercontent.com/25259233/61757083-017e6280-adfa-11e9-899f-2b1a452dbdd6.PNG)

Please try the `2.1` branch of `arfoundation-samples` rather than the `master` branch. If that doesn't work then please update this issue.

-Mike

**Comment by ChakreyaYan** [comment]
Hi Mike, 
Thank you for your answer.
I not sure that, is it good idea or not, in that case I deleted some scripts in " ARCollaborationData"  folder, it solved above errors. 
![unitycode](https://user-images.githubusercontent.com/25259233/61836815-ede80000-aebc-11e9-8986-51b056cc3c1c.jpg)
