### ISSUE TITLE
AR Foundation 2.2.0-Preview 3

### ISSUE THREAD

**Issue by smxthereisonlyone** [Unity-Technologies/arfoundation-samples#228]
Following Error after updating to AR Foundation 2.2.0-Preview 3

Library/PackageCache/com.unity.xr.arkit@2.2.0-preview.1/Runtime/HumanBody/ARKitXRHumanBodySubsystem.cs(127,34): error CS0115: 'ARKitHumanBodySubsystem.Provider.TrySetHumanBodyPoseEstimationEnabled(bool)': no suitable method found to override

What to do?

**Comment by tdmowrer** [comment]
You must also update the ARKit package to at least [2.2.0-preview.2](https://docs.unity3d.com/Packages/com.unity.xr.arkit@2.2/changelog/CHANGELOG.html#220-preview2---2019-07-16), though I would recommend 2.2.0-preview.3. These correspond to different versions of the iOS 13 beta, which has meant breaking changes between versions.

**Comment by smxthereisonlyone** [comment]
Okay, would be great to pinpoint to that in the UI

**Comment by smxthereisonlyone** [comment]
Anyway, after updating I get the following error:

`Assets/Scenes/ARCollaborationData/TCPConnection.cs(235,43): error CS1061: 'ARCollaborationData' does not contain a definition for 'bytes' and no accessible extension method 'bytes' accepting a first argument of type 'ARCollaborationData' could be found (are you missing a using directive or an assembly reference?)
`

**Comment by smxthereisonlyone** [comment]
Any idea why? @tdmowrer  :)

**Comment by smxthereisonlyone** [comment]
@tdmowrer I did everything you said. I am on 2019.2.0f1, AR Foundation 2.2.0 Preview 3, ArKit XR Plugin 2.2.0 Preview 4, ARKit Face Tracking 1.1.0 Preview 4, AR Subsystems 2.2.0 Preview 3, ARCore XR Plugin 2.1.1 - what else do I need to do?? 

I still have this error:

`Assets/Scenes/ARCollaborationData/TCPConnection.cs(157,56): error CS1061: 'ARCollaborationData' does not contain a definition for 'bytes' and no accessible extension method 'bytes' accepting a first argument of type 'ARCollaborationData' could be found (are you missing a using directive or an assembly reference?)
`

**Comment by smxthereisonlyone** [comment]
Ah got it - I had an older version of the samples.

Really begs the questions why you guys are not putting the samples into the packages ... as a ... wait .. sample package - might be better for you internal qa, right? ..............

**Comment by tdmowrer** [comment]
We've experimented with that, as it would eliminate the need for multiple branches in this repo, but the package manager's support for built-in samples isn't robust enough yet.
