### ISSUE TITLE
19 Errors when i upgrade to AR Foundation 2.2.0-Preview 3 / ARkit 2.2.0-preview.3

### ISSUE THREAD

**Issue by priisc** [Unity-Technologies/arfoundation-samples#229]
I keep getting those 19 errors similar to the ones below: 
Any idea what is causing that ? 
Thank you! 

Library/PackageCache/com.unity.xr.arfoundation@2.2.0-preview.3/Runtime/AR/ARMeshManager.cs(6,37): error CS0234: The type or namespace name 'MeshId' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Library/PackageCache/com.unity.xr.arfoundation@2.2.0-preview.3/Runtime/AR/ARMeshManager.cs(156,16): error CS0246: The type or namespace name 'XRMeshSubsystem' could not be found (are you missing a using directive or an assembly reference?)

**Comment by tdmowrer** [comment]
What version of Unity?

**Comment by priisc** [comment]
2019.3.0a5

**Comment by tdmowrer** [comment]
We are changing the namespace in 2019.3. Try a more recent alpha release.

**Comment by priisc** [comment]
Solved the issue! Thanks a lot !!
