### ISSUE TITLE
Playing in Unity

### ISSUE THREAD

**Issue by dusanjencik** [Unity-Technologies/arfoundation-samples#23]
Hello, 

I've liked developing/playing in Unity project based on https://github.com/Unity-Technologies/experimental-ARInterface . Editing in Play mode right in the Unity without a need to build app on device every time.
Now, I would like to switch to ArFoundation, but these frameworks are not substitutes.
The main pain is a need to build app on device every time to see some new changes.
Are you planning to add support playing in Unity without building on device? Or can I achieve the similar behaviour like developing on ARInterface without writing all the supporting code? I mean viewing mocked AR surfaces and mooving camera by mouse and keyboard.

Thank you.

**Comment by bitfabrikken** [comment]
@timm-unity: Would love something like that- actually just the ARKit Remote.. Any idea when you'll have a release available with this?

**Comment by sergiosolorzano** [comment]
Hi ! I see here ARRemoteEditor is currently not available. 
I can't get to work Instant Preview (https://developers.google.com/ar/develop/unity/instant-preview) with ARFoundation though it worked fine with ARCore and ARInterface, am I missing something?

I can't tell where the app's functionality fails by just looking at the phone :) 
Thank you for your help, Sergio

**Comment by timm-unity** [comment]
Instant Preview is something Google provide for their plugin; it is separate from `ARFoundation`. "ARInterface" was code on top of Google's existing plugin, so that's why instant preview worked there.

Remoting for `ARFoundation` is in the works and will be delivered as an additional package.

**Comment by sergiosolorzano** [comment]
Thanks for clarifying @timm-unity , I was actually a bit mixed up with the two! I really appreciate the hard work you and team are doing, it's coming along great ! look forward to the package when it's good to go :)

**Comment by Excludos** [comment]
I understand this is being worked on, but I would like to re-stress the importance of this feature. It is very difficult to develop any app at any progress when you're not able to test in the editor. Can I humbly ask if there is an ETA on this?

**Comment by tdmowrer** [comment]
You can try out a very early version of this in [this branch](https://github.com/Unity-Technologies/arfoundation-samples/tree/mock).

**Comment by Excludos** [comment]
Tested Mock. Seems to work fine. Simulate scripts should make use of #if (UNITY_EDITOR) tags to avoid running on device. Prefabs should be added to the rightclick menu for XR alongside Session Origin, Session, Default Point Cloud and Default Plane.

I have not tested Remoting as I don't know how that is suppose to work. Are you required to set up a IP camera?

**Comment by tdmowrer** [comment]
Good feedback. The monobehaviours in the example scene are intended as examples only. The package contains the API. This is a very early preview -- we intend to have several editor-only tools for simulating AR data that won't requires polluting your scene with mock specific monobehaviours.

The utility currently is to test concepts like scale that would be very difficult to see what's going on when deployed to device.

This package will eventually support remoting but that is also a work in progress.

**Comment by kromley** [comment]
Working with Unity Remote seems like the real solution. Hopefully this will be available soon.

**Comment by rtlsilva** [comment]
The Mock XR tool is much appreciated and seems to work fine, apart from the fact that it's currently broken because someone forgot to `#define UNITY_IOS` and see if their IDE spat out any errors.  
Since I'd prefer not having to wait for it to come out of alpha (my team would rather have this feature in a basic workable state sooner than later) I tried fixing the errors myself by embedding the package on my project's Packages folder.  
Doing this made the UnityXRMock subsystems not being listed as available, and attempting to access anything that "goes native" crashes the editor.  

This led me to question: how does ARFoundation find subsystems exactly, and how can we make our own custom subsystem packages?

**Comment by aviggiano** [comment]
Any ETA on the Unity Remote support? This is really going to be a game changer for AR developers.

**Comment by FUBAR2077** [comment]
Hello, any news in the subject? Can I do something simmillar to ARCore Instant preview?

**Comment by knightcube** [comment]
Waiting for this support to roll out soon.

**Comment by PanMig** [comment]
I am also unable to locate the mock AR branch that was mentioned above. Can we actually have remote connection in the AR foundation 3.0 preview version ?

**Comment by sergiosolorzano** [comment]
No update here either https://forum.unity.com/threads/ar-remoting-simulation.720575/#post-4868660

**Comment by gblikas** [comment]
Any updates on when this is going to come through? It would save developers hours of time.

**Comment by mdurand42** [comment]
Please refer to this forum post for updates on AR Remoting. 
https://forum.unity.com/threads/ar-remoting-simulation.720575/page-2#post-5691868

**Comment by gblikas** [comment]
@mdurand42 That doesn't answer my question, now provide a comparable solution. I don't appreciate you closing this issue.

**Comment by tobeglad** [comment]
I developed a plugin that enable remote session data streaming from AR device to Editor. It currently has very limited set of features but still it tremendously reduces iteration time. Hope you'll find it handy.
https://stampedegames.net/ar-foundation-remote.html
