### ISSUE TITLE
ARParticipantAnchor in ARCollaborationData

### ISSUE THREAD

**Issue by crocoking** [Unity-Technologies/arfoundation-samples#230]
According to the apple doc, there is an "ARParticipantAnchor" while represents another user in a multiuser AR experience. You can see it [here](https://developer.apple.com/documentation/arkit/arparticipantanchor).
But where I can find in ARFoundation? Which class? Which Method.

**Comment by botaohu** [comment]
@tdmowrer  Please add this ARParticipantAnchor functionality in the multipeer example and arfoundation. It's very very important for multiuser AR experience.

**Comment by tdmowrer** [comment]
Support for participants was added in [3.0.0-preview.1](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/changelog/CHANGELOG.html#300-preview1---2019-08-21)
