### ISSUE TITLE
Please add a  better sample for People Occlusion.

### ISSUE THREAD

**Issue by crocoking** [Unity-Technologies/arfoundation-samples#234]
I had read the thread [https://forum.unity.com/threads/how-to-setup-people-occlusion.691789/](https://forum.unity.com/threads/how-to-setup-people-occlusion.691789/). But I have no idea about how to do people occlusion with ARFoundation. Please add a better sample for People Occlusion. I believe others have the same issues.

**Comment by artistd36** [comment]
Any update?

**Comment by yosun** [comment]
@tdmowrer

**Comment by tdmowrer** [comment]
Latest ARFoundation has an [`AROcclusionManager`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html?q=AROcclusionManager) which makes this feature easy to use, and the SimpleAR sample scene uses it.

There's a description of this feature [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/index.html#basic-setup) (search for "Automatic occlusion").
