### ISSUE TITLE
Reference Points in Image Tracking

### ISSUE THREAD

**Issue by edisyo** [Unity-Technologies/arfoundation-samples#235]
So I am trying to anchor 2 spawn points in specific position. The problem is that, the reference point and spawn points are in correct position, but it moves along with camera. Here's the code im using now: 
             `
             pos = cannon.transform.position; //same position and rotation as trackedImage
             rot = cannon.transform.rotation;
             
             Pose pose = new Pose(pos, rot);
             refPoint = aRReferencePointManager.AddReferencePoint(pose);
             refPoint.transform.position = new Vector3(pos.x - 2, pos.y + yValueChange, pos.z + 50);
             
             foreach (Boat go in battleshipsGameScript.spawnedBoatList)//each boat added as child of 
             refpoint
             {
                 //go.gameObject.transform.SetParent(refPoint.transform);
                 //go.gameObject.transform.localPosition = new Vector3(0f, 0f, 0f);
             }

            battleshipsGameScript.spawnPoints[0].transform.SetParent(refPoint.transform);          
            battleshipsGameScript.spawnPoints[1].transform.SetParent(refPoint.transform);
            `
Any help what im doing wrong?

**Comment by edisyo** [comment]
I also tried to set spawnpoints as children of ARSessionManager Trackables. And nothing anyway.

**Comment by tdmowrer** [comment]
Once you've created a reference point (now called "anchors"), the its transform is updated automatically by ARFoundation; you should not set its position or rotation directly. That means this line:
```csharp
refPoint.transform.position = new Vector3(pos.x - 2, pos.y + yValueChange, pos.z + 50);
```

will not have any effect. I'm not sure exactly what you are trying to accomplish. If this is still an issue, can you provide more details?

**Comment by mdurand42** [comment]
Please re-open this issue if you are still having issues @edisyo .
