### ISSUE TITLE
humanbodytracking - can we track multiple bodies?

### ISSUE THREAD

**Issue by FriskyBishop** [Unity-Technologies/arfoundation-samples#237]
Is it possible to track multiple bodies/skeletons on ARKit3?

The humanbodytracking2D and 3D samples work great but they will only track one human at a time (if there is more than one it just swaps between them)

**Comment by artistd36** [comment]
Hi,
only track one human at a time (if there is more than one it just swaps between them) as per my knowledge

**Comment by FriskyBishop** [comment]
@artistd36 id like to know if multiple tracking is possible or if its a planned feature etc

**Comment by sridevipavithra** [comment]
It's not possible to track more than one human as of now. They've not disclosed the future plans.
