### ISSUE TITLE
ARCollaborationData/MessageType clashes with UnityEditor.MessageType

### ISSUE THREAD

**Issue by rickpt** [Unity-Technologies/arfoundation-samples#238]
Your Type enum MessageType clashes with your Type UnityEditor.MessageType if you have this sample in project with other code which uses EditorGUILayout.HelpBox etc... please add namespace...

Thanks

**Comment by tdmowrer** [comment]
This has been removed in favor of  Apple's Multipeer Connectivity framework in current `master`.

**Comment by rickpt** [comment]
That's great! 

Any chance of an update to the 1.5 branch those of us on your latest LTS release are using?

Thanks

**Comment by tdmowrer** [comment]
We are working on backporting the sample now.

**Comment by mdurand42** [comment]
@rickpt we are not planning to perform any more backports to the 1.5 branch of AR Foundation samples. If you move to a newer version of AR Foundation this problem will not exist. Please re-open only if this is urgent. Thanks.
