### ISSUE TITLE
Face tracking using the rear camera? - possible?

### ISSUE THREAD

**Issue by FriskyBishop** [Unity-Technologies/arfoundation-samples#239]
Is it possible to do face tracking with the rear facing camera on AKit 3?

I want to track the faces of other people, not the user.
However whenever the ARFaceManager is enabled it switches to the front camera.

**Comment by thibautvdu** [comment]
@FriskyBishop 
Just saw this question searching for something else. For reference, there are some serious limitations to the last features of ARKit regarding which camera you can use :
- Face tracking is only available on truedepth selfie camera ( ref: https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration )
- Body tracking on the opposite is only available on the rear camera ( https://developer.apple.com/documentation/arkit/arbodyanchor )

**Comment by tdmowrer** [comment]
[The RearCameraWithFrontCameraFaceMesh sample](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/FaceTracking/RearCameraWithFrontCameraFaceMesh.unity) shows how to do this in ARFoundation.

**Comment by TheIntellify-Hardik** [comment]
The link has a 404 error !!

**Comment by tdmowrer** [comment]
There sample was renamed. Try this: https://github.com/Unity-Technologies/arfoundation-samples#worldcamerawithuserfacingfacetracking

**Comment by Nik3181** [comment]
This isn't the same, it still used front camera for face tracking.
