### ISSUE TITLE
Object Tracking is removed? (2.1.1)

### ISSUE THREAD

**Issue by TeorikDeli** [Unity-Technologies/arfoundation-samples#240]
Why the object tracking is removed in the latest version of AR Foundation? Only the document revision history says something about it "June 25, 2019 | Removed object tracking for 2019.3 verified package". No mentions in the changelog. Is there a reason for removing this feature completely? I don't understand the "for 2019.3 verified package", 2019.3 is in the alpha stage.

I was using 2.1.0.preview before in Unity 2019.2.

I don't want to use AR Foundation 2.2, because I don't want to use a beta Xcode. And also, will you remove object tracking in 2.2 too? Also, I think it is absurd to make master branch for a non-released (it's in beta) ARKit 3, iOS 13 and Xcode 11.

Well, I also want to mention about the LWRP support, but it is another subject.

**Comment by tdmowrer** [comment]
> Why the object tracking is removed in the latest version of AR Foundation?

Object tracking depends on an experimental Unity feature, hence it cannot be part of a verified package. It is still available in the latest preview versions, but, as you point out, those also contain the iOS 13 beta features.

**Comment by BrahimHadriche** [comment]
I'm on Foundation 2.2.0-preview.3 and ARKit Plugin 2.2.0-preview.4, yet ImageTracking and ObjectTracking scenes do have the missing scripts on the session object (I will assume these are image tracking and object tracking managers)
Am I missing something?

**Comment by tdmowrer** [comment]
> I'm on Foundation 2.2.0-preview.3 and ARKit Plugin 2.2.0-preview.4, yet ImageTracking and ObjectTracking scenes do have the "missing scripts" warnings on the session object (I will assume these are image tracking and object tracking managers)
> Am I missing something?

I think there was a minor refactor of the samples at some point that left removed MonoBehaviours on some GameObjects in a couple of scenes (should be fixed now). I don't think it's related to the removal of object tracking in 2.1.
