### ISSUE TITLE
CameraImage scene broken in ARFoundation 2.2

### ISSUE THREAD

**Issue by sbiche** [Unity-Technologies/arfoundation-samples#242]
Hi there,

I'm doing some image processing on the CPU using OpenCV. This worked fine in ARFoundation 2.1 when using the CameraImage scene, however it no longer seems to be supported in ARFoundation 2.2. I now receive this error when launching the CameraImage scene and see a blank white image in the top-left corner where the camera image was previously displayed:

`07-31 16:41:22.601 17146 17171 E Unity   : NotSupportedException: getting camera image is not supported by this implementation
07-31 16:41:22.601 17146 17171 E Unity   :   at UnityEngine.XR.ARSubsystems.XRCameraSubsystem+IProvider.TryAcquireLatestImage (UnityEngine.XR.ARSubsystems.XRCameraSubsystem+CameraImageCinfo& cameraImageCinfo) [0x00000] in <0cf40fa716e747f5809538caa82f9e9a>:0
07-31 16:41:22.601 17146 17171 E Unity   :   at UnityEngine.XR.ARSubsystems.XRCameraSubsystem.TryGetLatestImage (UnityEngine.XR.ARSubsystems.XRCameraImage& cameraImage) [0x00000] in <0cf40fa716e747f5809538caa82f9e9a>:0
07-31 16:41:22.601 17146 17171 E Unity   :   at UnityEngine.XR.ARFoundation.ARCameraManager.TryGetLatestImage (UnityEngine.XR.ARSubsystems.XRCameraImage& cameraImage) [0x00017] in <93239b88da614663bf0176ca334f19aa>:0
07-31 16:41:22.601 17146 17171 E Unity   :   at TestCameraImage.OnCameraFrameReceived (UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs eventArgs) [0x00006] in <997893f39ebe4f6893ba095bfd800f76>:0
07-31 16:41:22.601 17146 17171 E Unity   :   at (wrapper delegate-invoke) System.Action`1[UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs].invoke_void_T(UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs)
07-31 16:41:22.601 17146 17171 E Unity   :   at UnityEngine.XR.ARFoundation.ARCameraManager`

Is this no longer supported intentionally? If not, is there any guidance to fix this?

Using Unity 2019.2.0f1. Packages in use during error:
* AR Subsystems - preview.3 - 2.2.0
* AR Foundation - preview.3 - 2.2.0
* ARCore XR Plugin - 2.0.2
* ARKit XR Plugin - 2.0.1

Thanks,
Sebastian

**Comment by tdmowrer** [comment]
You are using version 2.0 of both the ARKit and ARCore packages, which did not support CPU camera image access. Try upgrading them to either 2.1 or 2.2.

**Comment by sbiche** [comment]
Ahh, gotcha. Thanks! It's working now.

Any chance we could get dependency versions in the README? Would be super helpful.

**Comment by sbiche** [comment]
Oops, I guess I could have just avoided this by looking at the package manifest for the samples. Will resolve this. Thanks again!
