### ISSUE TITLE
lwrp-support-2019.1-with-2.1. doesn't work - missing exact LWRP and ARF versions

### ISSUE THREAD

**Issue by tjukic** [Unity-Technologies/arfoundation-samples#244]
ARFoundation LWRP support is completely broken. It simply doesn't work with classic import.
I've manually edited manifest to use LWRP 5.6.2, ARF 2.1.0 ARC and ARK 2.1.0, but can't find the perfect match, errors are abudant.

Could you please be very specific on what setup the branch actually works and what is needed to force 2019.1.12f (or any latest supported version) to get a zero-error situation?

**Comment by tdmowrer** [comment]
Unity 2019.1.12/Unity 2019.2 silently updates the version of LWRP to a later version on project upgrade. We will update the readme in the short term. For the longer term, we are upgrading our support for LWRP in ARFoundation.

**Comment by tjukic** [comment]
Found traces of that in packages upgrade log, yes. Thanks.

> The following packages were updated:
>   com.unity.render-pipelines.core from version 5.6.1 to 5.7.2
>   com.unity.render-pipelines.lightweight from version 5.6.1 to 5.7.2
>   com.unity.shadergraph from version 5.6.1 to 5.7.2

While it might sound strange, there is a workaround: closing the project and manually switching back to 5.6.1 seems to fix the issue.
Not sure if this is possible with 2019.2.0. Will update if happens to be so.
