### ISSUE TITLE
Unity 2019.1.4 first time install with black Ar camera  background

### ISSUE THREAD

**Issue by unsuigo** [Unity-Technologies/arfoundation-samples#245]
When I install apk on android, with camera permission window comes issues and AR camera not working.
If I plug game directly from unity there is no issues.
The issue comes when I switched to IL2CPP
Unity 2019.4.1
AR Foundation 2.2
AR Core XR Plugin 2.1.1

**Comment by unsuigo** [comment]
![monitor_FnjcwguPcS](https://user-images.githubusercontent.com/30129369/62308762-5c612b00-b486-11e9-8b88-109861aad01c.png)

**Comment by muninger** [comment]
> When I install apk on android, with camera permission window comes issues and AR camera not working.
> If I plug game directly from unity there is no issues.
> The issue comes when I switched to IL2CPP
> Unity 2019.4.1
> AR Foundation 2.2
> AR Core XR Plugin 2.1.1

you can add a camera in scene,you will find the message. you device is not in the list of arcoe and the emum ARSessionState is not right.so buy a support phone and try

**Comment by tdmowrer** [comment]
This sounds like an issue which was fixed in [2.1.0-preview.5](https://docs.unity3d.com/Packages/com.unity.xr.arcore@2.1/changelog/CHANGELOG.html#210-preview5---2019-05-27) (well before 2.1.1).

You mentioned using
> Unity 2019.4.1

There is no such version. Can you clarify?
