### ISSUE TITLE
Strange placement occuring building to android

### ISSUE THREAD

**Issue by HyperLethalVector** [Unity-Technologies/arfoundation-samples#246]
Hi,

I'm experiencing some strange behaviour when using AR foundation
Starting with a new scene with: 
- 1 camera at position 0,0,0. Rotation Identity
- 1 sphere, position 0,0,-5 (infront of the camera)

In android, after the scene loads, the sphere moves to position 0,0,0
In the editor, the object stays where it is supposed to.

What could be causing this behaviour? It's severely crippling my between AR 3D scenes

My Editor:

Linux, 2019.1.12f1
Packages are as attached

![image](https://user-images.githubusercontent.com/8954571/62313627-270a0c80-b489-11e9-9abc-b7dd3ce51320.png)

**Comment by tdmowrer** [comment]
> In android, after the scene loads, the sphere moves to position 0,0,0

How do you know the sphere moves? Are you printing its position, or does it appear to be at the same location as the device's starting position?

**Comment by HyperLethalVector** [comment]
Hi,

I’ve printed the position of the object, and although it’s printed that the position is correct but the rendering returns to 0,0,0

After switching out the LWRP scene asset with a fresh one in the rendering settings, this issue resolved.
I guess it’s an issue with LWRP


------
From the software-ronin
Dr. Damien Rompapas.

Crazy engineer of the denki kitchen!

Facebook: https://www.facebook.com/ryu.uesugi
Google Mail: hyperlethalvector92@gmail.com
Web: www.denkikitchen.com

**Comment by tdmowrer** [comment]
Hmm, okay that does sound odd. Everything is working now, though?
