### ISSUE TITLE
Video Player AR Foundation

### ISSUE THREAD

**Issue by colkel01** [Unity-Technologies/arfoundation-samples#248]
AR Foundation scene added a simple plane with the video player component crashes IOS devices on launch, bad_access linking to the canvas manager and the video player.

Any work around for this?

**Comment by calebcarithers** [comment]
Any solution on this? Running into this problem currently as well (2019.2.9f1).

**Comment by mswbecod** [comment]
<img width="946" alt="Screenshot of Xcode (05-11-2019, 6-13-46 PM)" src="https://user-images.githubusercontent.com/46880771/68194254-0c02e780-fff8-11e9-9e00-2da29f1c70f9.png">

I have same issue (2019.2.11f1)

**Comment by mswbecod** [comment]
it works on 2019.3.0b9 (Beta)

**Comment by mswbecod** [comment]
same issue 2019.2.14f1

**Comment by sstachiw** [comment]
Same issue here. If I load a prefab with a video texture but turn off play on awake, it will load the prefab without crashing. but as soon as I play the video, it stutters, stumbles and crashes.

**Comment by Kimyko** [comment]
I had the same issue on 2019.2.17f1. Upgraded the project to 2019.3.0f6 and it worked.

**Comment by tdmowrer** [comment]
I could not reproduce this in 2019.3.2f1. It looks like there was indeed a bug in 2019.2 which could cause this. Closing as 2019.2 is no longer supported in favor of 2019.3.
