### ISSUE TITLE
xcode build fail

### ISSUE THREAD

**Issue by marad747** [Unity-Technologies/arfoundation-samples#249]
i download samples and want to build. How to fix it?
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ARSkeletonDefinition", referenced from:
      objc-class-ref in UnityARKit.a(ARKitXRHumanBodyProvider.o)
  "_OBJC_CLASS_$_ARBodyAnchor", referenced from:
      objc-class-ref in UnityARKit.a(ARKitXRHumanBodyProvider.o)
  "_OBJC_CLASS_$_ARMatteGenerator", referenced from:
      objc-class-ref in UnityARKit.a(ARKitXRHumanBodyProvider.o)
  "_OBJC_CLASS_$_ARBodyTrackingConfiguration", referenced from:
      objc-class-ref in UnityARKit.a(ARKitXREnvironmentProbeProvider.o)
      objc-class-ref in UnityARKit.a(ARKitXRHumanBodyProvider.o)
      objc-class-ref in UnityARKit.a(WorldMapManager.o)
      objc-class-ref in UnityARKit.a(ARKitXRImageTrackingProvider.o)
      objc-class-ref in UnityARKit.a(ARKitXRPlaneProvider.o)
      objc-class-ref in UnityARKit.a(ARKitXRSessionProvider.o)
      objc-class-ref in UnityARKit.a(ConfigurationManager.o)
      ...
  "___isPlatformVersionAtLeast", referenced from:
      _UnityARKit_Camera_AcquireConfigurations in UnityARKit.a(ARKitXRCameraProvider.o)
      _UnityARKit_Camera_TryGetCurrentConfiguration in UnityARKit.a(ARKitXRCameraProvider.o)
      _UnityARKit_Camera_TrySetCurrentConfiguration in UnityARKit.a(ARKitXRCameraProvider.o)
      (anonymous namespace)::ARKitXRCameraProvider::ResetLocalConfigurationState() in UnityARKit.a(ARKitXRCameraProvider.o)
      (anonymous namespace)::ARKitXRCameraProvider::HandleARKitEvent(UnityARKitEvent, void*, int) in UnityARKit.a(ARKitXRCameraProvider.o)
      _UnityARKit_EnvironmentProbeProvider_Construct in UnityARKit.a(ARKitXREnvironmentProbeProvider.o)
      _UnityARKit_EnvironmentProbeProvider_Destruct in UnityARKit.a(ARKitXREnvironmentProbeProvider.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DavidMohrhardt** [comment]
Are you running XCode 11 beta?  Those symbols only exist in the latest version of XCode.

**Comment by tdmowrer** [comment]
Yes, this looks like an Xcode 11 beta / iOS version mismatch. Xcode 11/iOS 13 are no longer in beta, and ARFoundation 3.0 simultaneously supports both Xcode 10 and 11, so this should no longer be an issue.

**Comment by HuuLinhDra** [comment]
I using Xcode version 11.6 and have same error
