### ISSUE TITLE
iOS - ARKit support forced under UIRequiredDeviceCapabilities in Info.plist

### ISSUE THREAD

**Issue by HidingGlass** [Unity-Technologies/arfoundation-samples#250]
Currently, it seems the ARFoundation automatically adds ARKit to the UIRequiredDeviceCapabilities in the Info.Plist even if "Requires ARKit support" is unchecked in PlayerPrefs.

We are looking into updating apps to ARFoundation. Because some are older apps, ARKit is not listed under UIRequiredDeviceCapabilities in the original build so adding ARKit to the list of required capabilities yields an automatic rejection when trying to update the app in the Apple App Store.

It's been on us a developers provide an alternative experience to users that want to use the app and do not have an ARKit supported device so they can still download the app even if ARFoundation has been added to the Unity project.

Currently the workaround is to manually change the Info.Plist in XCode after building which is not ideal.

Thank you. 

![RequiresARKit_PlayerPrefs](https://user-images.githubusercontent.com/11765663/62394567-98a29300-b53b-11e9-92ca-a2aea21080b4.png)
![RequiresARKit_InfoPlist](https://user-images.githubusercontent.com/11765663/62394568-98a29300-b53b-11e9-8ae3-e49c93beb6de.png)

**Comment by nilsk123** [comment]
I think this is covered already.

Go to edit>project settings, theres an 'XR' tab with an ARKit section which allows you to select 'optional' or 'required'. Works for us!

![Schermafbeelding 2019-08-05 om 09 17 45](https://user-images.githubusercontent.com/8883990/62446052-11833400-b762-11e9-81c2-e1458ad2e922.png)

**Comment by HidingGlass** [comment]
Aha! Sorry I missed that only looking around _Player_ XR settings and not the _Project_ XR settings.  Thanks for the info!
