### ISSUE TITLE
Sudden 30deg rotations in body.pose.rotation w/ good tracking

### ISSUE THREAD

**Issue by magik-chorne** [Unity-Technologies/arfoundation-samples#251]
Hello!
Unity version: 2019.1.5f1
ARFoundation version: 2.2 preview 3
ARKit XR Plugin: 2.2 preview 4
iOS Version: 13 beta 5
iPhone: XS Max

I'm using body.pose.rotation to control the overall rotation of a character. Under great tracking conditions I am seeing sudden 20-30 degree rotations between frames in body.pose.rotation. The data in body.pose.position is fine. For example with some real data: 

Frame 1:
Pos: (.02383055, -0,04075068, .3699032)
Rot: ( 14.869, -13.818, -11.26 )

Frame 2:
Pos: ( .03124638, -0.03956895, 0.3636541)
Rot:  ( 23.02, 22.522, -0.49 )

The person being tracked is barely moving between these frames (as you can see from the position vector). This issue happens very frequently and consistently, though I haven't figured out the pattern. I am not doing any other processing or conversions on the rotations:

```csharp
void OnHumanBodiesChanged(ARHumanBodiesChangedEventArgs args)
{
        (find right body. assign to arBody)
        .....
        ApplyCorrectedBodyTransform(arBody.pose.position, arBody.pose.rotation);
        .....
}
private void ApplyCorrectedBodyTransform(Vector3 position, Quaternion rotation)
        {
            gameObject.transform.localRotation = rotation;
            gameObject.transform.localPosition = (position * _positionScaleFactor) + _tposePos;
        }
````

This is the first time I've used body position/rotation so I unfortunately don't have any guidance on whether this is new to beta 5 or not. Hopefully you can repro it. Please let me know if I can provide any further information.

**Comment by DavidMohrhardt** [comment]
Does this rotation persist beyond Frame 2?  Like for Frames 3->n or is it corrected relatively quickly?

**Comment by magik-chorne** [comment]
It persists 3->n. At some point n+1 the sudden rotation happens again(in a different direction) and persists. It somewhat seems related to a certain yaw threshold being crossed - almost as if a new forward direction is being defined because yaw is > 45 degrees....or something. If the person stands still the sudden rotation doesn’t happen. During movement it does.

**Comment by DavidMohrhardt** [comment]
Have you checked what the tracking state for the body is while this is happening?  If it is limited and stays limited then the data has lost fidelity and could be the cause.

**Comment by magik-chorne** [comment]
It's probably easier if I just post a video of it:
https://www.youtube.com/watch?v=hMJ5h0LUafg

Basically I'm playing back a session in Unity -- you can see that when crossing a certain angle it suddenly rotates ~30 degrees. What's interesting is that also when coming BACK it rotates at the same threshold angle by the opposite amount.

Considering how specific it is + how high quality the tracking is across the board - I just dont think its a tracking issue. Feels more like an algorithm bug somewhere.

**Comment by DavidMohrhardt** [comment]
I am unable to reproduce this issue on my end.  Your psuedo code is a little ambiguous as well, could you explain exactly what it is you are doing?  I can see that you are applying the transform to the base body but are you also applying the skeleton as well?  If not, there is a potential that the root of the skeleton may accommodate for this rotational jump.

Also is there anyway you can also include the camera video?  iOS has a feature for recording the screen that you can use.

**Comment by DavidMohrhardt** [comment]
So with a little additional testing I have to conclude that this is just a tracking issue.  ARKit tends to have problems with profile views causing all sorts of weird rotations as most of what we are doing is exposing the data the platform is providing (especially when it comes to poses).

**Comment by sridevipavithra** [comment]
Same issue. Just a quick question. Does the rotation of the 3D character change when you rotate the camera?

**Comment by DavidMohrhardt** [comment]
It's shouldn't since this is all based on reference point tracking information.  Unless you parented the content to the camera and then rotated the camera through code I don't think it would have the resulting effect.  I have to say that these rotations are likely just poor tracking information being surfaced from the device.  My tests have these rotations too when there isn't a lot of full body information and we are not doing anything algorithmically complex that might cause these sort of issues.

**Comment by magik-chorne** [comment]
OOO. Sorry for the delay.

I was easily reproing in good tracking conditions. Joint rotations were all being correctly applied. Root nor hips have corrections for body pose in the rotations, so that's unnecessary. Fortunately(!?) I've since been unable to repro. My guess is it was some phone state/ios update that caused the issues. Sorry for the wild goose chase.
