### ISSUE TITLE
AR Foundation 2.2.0-Preview 3 Black camera feed on opening an AR scene for the second time

### ISSUE THREAD

**Issue by d3m3tr105** [Unity-Technologies/arfoundation-samples#254]
Reproduced on Unity 2019.1.11 and 2019.2.
I loaded the SimpleAR scene from a loader scene. First time everything is OK. 
I went back to the loader scene and loaded SimpleAR scene for the second time, and the camera preview is black.  This happens for the 3rd 4th etc time. Reset button does not do anything.
Config:
Legacy render pipeline, no IL2CPP, android build.
Tested on huawei mate 20 pro and one plus 6t.

**Comment by sam598** [comment]
Sounds like the same issue as: https://github.com/Unity-Technologies/arfoundation-samples/issues/217

This issue is not present in 2.2.0-Preview 1 but is present in every update since then.

**Comment by d3m3tr105** [comment]
Thanks for replying. Indeed I took a look at #217 . I tried to switch to 2.2.0-Preview 1, but I don't think the current sample project scripts are compatible with that anymore.  When switching to  2.2.0-Preview 1 I basically got the console full of errors. To be honest I don't know if it's worth the time to go and fix everything. 
@sam598  , Do you have any idea if 2.2.0-Preview 1 is LWRP & IL2CPP compatible? I need both of these in my project.

**Comment by sam598** [comment]
Unfortunately I do not know if they are compatible. I still had access to the preview 1 sample files so that is how I was able to avoid those errors.

I believe the “preview” designation means that the plugin is still in beta and is not ready to be used in released apps. In its current state preview 3 definitely cannot be used in released apps.

**Comment by d3m3tr105** [comment]
Yup! Anyway, thanks for replying!

**Comment by tdmowrer** [comment]
ARFoundation supports UniversalRP and IL2CPP; documentation [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/ar-camera-background-with-scriptable-render-pipeline.html). Please reopen this issue if you are still having problems getting them to work together.
