### ISSUE TITLE
How can I get aligned color image with human segmented depth?

### ISSUE THREAD

**Issue by bbico** [Unity-Technologies/arfoundation-samples#256]
Hi, I'm now using human depth image in HumanSegmentationImage Sample, but I got no idea with aligned color and depth. So in sample project, human depth resolution showed us 256 x 192 resolution, as is not aligned with ar color camera output (1224 x 2466 or something with iphone xs max). Is there any way to get aligned color and depth images?

**Comment by MrMatthias** [comment]
Have a look at the ARKitShader.shader that comes with the ARKit ARFoundation package.
In the vertex shader the camera uvs are transformed. 
So in the effect shader you pass two uv coordinates to the fragment shader.
