### ISSUE TITLE
PointManager trackables different behaviour on iOS and Android

### ISSUE THREAD

**Issue by areavisuale** [Unity-Technologies/arfoundation-samples#257]
When I reset the session with ARSession.Reset() I noticed that on Android a new PointCloud trackable is created, instead on iOS no, there's only one PointCloud trackable all the time.

**Comment by tdmowrer** [comment]
I can see how this would happen. It is fixable; I curious, though, how you are using or relying on this behavior. Can you elaborate?

**Comment by areavisuale** [comment]
I don' t remember exactly why I need it, but I suppose that I made a code that searched for the pointcloud trackable by name to show it when I reset the session and then hide it at the first plane recognition

**Comment by tdmowrer** [comment]
I see. On iOS and Android, there will only ever be one point cloud -- the reason ARFoundation supports multiple is that other platforms, like Magic Leap, have multiple point clouds, each with its own trackable id.

So the defined behavior is that
1. Each point cloud will have a unique trackable id AND
2. On Android and iOS there will only ever be one.

I don't think there are any strong guarantees regarding the behavior of a point cloud being removed and then re-added as a result of an `ARSession.Reset`. That sounds like an implementation detail that can vary by platform.
