### ISSUE TITLE
About HumanBodyTracking3D

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#260]

**Comment by Arytes** [comment]
qestion 1：the model support thin-gauge skin in “HumanBodyTracking3D”.
qestion 2：If i want to replace the model of “ControlledRobot”，How can i make model by myself to match the bone.
I hope i could get a answer quickly ，very much！！

**Comment by sridevipavithra** [comment]
The rigging of your model should match the controlledRobot rigging pattern.

**Comment by yosun** [comment]
would be neat if there is an auto conversion from standard mecanim biped to that
