### ISSUE TITLE
HumanBodyTracking3D - fix for iOS 13 v7?

### ISSUE THREAD

**Issue by nikolahitek** [Unity-Technologies/arfoundation-samples#262]
If I am informed well, HumanBodyTracking3D scene works on iOS 13 v3 and not on the newer versions (tested myself on v6 and v7 now), when can we expect a fix for this, maybe a new ARFoundation preview?

**Comment by tdmowrer** [comment]
The latest version of Xcode 11 is beta 5, which ARKit XR Plugin version 2.2.0-preview.4 was compiled against. This should work on iOS 13 betas 5, 6, & 7. What version are you using?

**Comment by nikolahitek** [comment]
> The latest version of Xcode 11 is beta 5, with which ARKit XR Plugin version 2.2.0-preview.4 was compiled. This should work on iOS 13 betas 5, 6, & 7. What version are you using?

I am using iOS 13 v7 and Xcode 11 beta 5, the robot is not showing up but there are not any errors. I tested it previously on iOS 13 v6 - the outcome was the same.
