### ISSUE TITLE
How to align depth map of Unity 3d object and depth map from ARKit

### ISSUE THREAD

**Issue by smalleight17** [Unity-Technologies/arfoundation-samples#263]
I can get the human occlusion working in fragment shader, but I realize the depth map of my 3d virtual object and the depth map returned by ARKit is not really aligned. As the depth is a bit off now my body occlusion it's working only kind of realistic.
Any idea on converting them to a same distribution?

**Comment by tdmowrer** [comment]
We're working on a better sample for this.

**Comment by smalleight17** [comment]
Ah! I had my own working version for this.
As 

>             
                float human_depth = tex2D(_HumanDepth, scale_uv).r;
                float unity_depth = tex2D(_CameraDepthTexture, uv_flip_x).r;
                unity_depth = Linear01Depth(unity_depth) * my_step(0., unity_depth);
                unity_depth *= _ProjectionParams.z;
            
                float my_step(float a, float x){
                    return x > a;
                }

This puts unity depth and arkit depth into same scale. I think. Let me know if this is right!

**Comment by todds-unity** [comment]
@smalleight17 ,

I have been working on the new occlusion functionality in ARFoundation.

The depth functionality in the shader includes are not accurate in the ARKit / Metal cases.

The new occlusion functionality with include calculations that will work better in the ARKit / Metal samples.


Todd

**Comment by tdmowrer** [comment]
This functionality is now available in the [AROcclusionManager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html?q=AROcclusionManager). The `SimpleAR` sample uses it.
