### ISSUE TITLE
if (foo) vs if (foo != null)

### ISSUE THREAD

**Issue by linojon** [Unity-Technologies/arfoundation-samples#267]
is this valid c# or is it a bug?

https://github.com/Unity-Technologies/arfoundation-samples/blob/c804370f0fe96751322ad9ab1a3a2e72e44ed914/Assets/Scripts/UX/UIManager.cs#L111

**Comment by tdmowrer** [comment]
If it was not valid C#, then it wouldn't compile :)

It is not generally true that reference types implicitly convert to `bool`, but `UnityEngine.Object` types do. See https://docs.unity3d.com/ScriptReference/Object-operator_Object.html

**Comment by linojon** [comment]
wow! thank you, i was searching for an answer to this :)
