### ISSUE TITLE
ARSubsystemManager.systemStateChanged in AR Foundation 2.1

### ISSUE THREAD

**Issue by Bergmam** [Unity-Technologies/arfoundation-samples#268]
I am currently in the process of updating an AR Foundation Unity application from AR Foundation 1.0 to AR Foundation 2.1.

In the old application, we added a function as an event on ARSubsystemManager as such:

`ARSubsystemManager.systemStateChanged += OnSystemStateChanged`

With `OnSystemStateChanged` taking a `ARSystemStateChangedEventArgs` as input.

What would be the 2.1 equivalent of this?

Thanks!

**Comment by tdmowrer** [comment]
See [`ARSession.stateChanged`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.1/api/UnityEngine.XR.ARFoundation.ARSession.html#UnityEngine_XR_ARFoundation_ARSession_stateChanged)
