### ISSUE TITLE
ARSession broken after first load

### ISSUE THREAD

**Issue by rgbddude** [Unity-Technologies/arfoundation-samples#269]
After updating I can only load a scene once and then have to force quit the app. There are no errors, ARKit just stops working and never comes back. My game is completely unusable in this state. It's been over a month now, is Unity aware of this issue?

**Comment by DavidMohrhardt** [comment]
What version of ARFoundation are you using and which did you switch from?  Additionally, what version of the ARKit package are you using?

**Comment by rgbddude** [comment]
I'm using the latest 2.2 previews. I upgraded from 2.2 preview 1.

I think everyone else has been having the same issues https://github.com/Unity-Technologies/arfoundation-samples/issues/254 https://github.com/Unity-Technologies/arfoundation-samples/issues/217

Can you please check and see if AR session will load in a new scene?

**Comment by mdurand42** [comment]
We have session restart included in our QA tests so we feel as though this one has been addressed by now. Please re-open if the issue persists for you.

**Comment by thornebrandt** [comment]
This is still happening for me.  Everything works the first load, then I need to go back to a menu.  I am destroying all gameobjects before resetting the scene on an application level, when I return to scene that was working before, it no longer tracks.    How do I find the singletons to destroy them?

**Comment by DavidMohrhardt** [comment]
@thornebrandt What versions of the editor and packages are you using and what game objects are you destroying?

Additionally, can you reproduce the issue using our samples (IE loading different scenes and still losing AR)?
