### ISSUE TITLE
ARSession disable/enable?

### ISSUE THREAD

**Issue by linojon** [Unity-Technologies/arfoundation-samples#270]
ARSession doc says "Enabling or disabling the ARSession will start or stop the session, respectively." Please clarify that this refers to the ARSession component, not the ARSession game object (to which the component is attached). E.g. as implemented in the SimpleAR scene's pause and resume buttons, and SupportChecker.cs does from script. Please note this will not cause the ARSession's OnEnable / OnDisable to be called, if that's what you intended.

**Comment by tdmowrer** [comment]
> ARSession doc says "Enabling or disabling the ARSession will start or stop the session, respectively." Please clarify that this refers to the ARSession component, not the ARSession game object (to which the component is attached).

The documentation means the ARSession _component_, but...

> E.g. as implemented in the SimpleAR scene's pause and resume buttons, and SupportChecker.cs does from script. Please note this will not cause the ARSession's OnEnable / OnDisable to be called, if that's what you intended.

Disabling the ARSession's GameObject will invoke `ARSession.OnDisable`. Have I misunderstood your question?
