### ISSUE TITLE
Change ControlledRobot Prefab with another model

### ISSUE THREAD

**Issue by nikolahitek** [Unity-Technologies/arfoundation-samples#272]
Has anyone successfully changed the ControlledRobot in HumanBodyTracking3D with another model?

When I try to, and I have the same rigging pattern, the same position and rotation of the object, it displays over the human body but completely deformed. 

My guess is that every bone/joint in my model has to have the same transforms as the bones in the ControlledRobot but there is no way to tell what they are because the model itself is removed from the project. Any suggestions?

**Comment by Pnailwal** [comment]
@tdmowrer 
Hi, 
I have been trying to replace my custom 3d character with the Robot 3d model. My character's rigging pattern is same as of Robot model and I have tried to build it from both .fbx and .usd but didn't find any success. 

my 3d model is also deforming on loading on mobile view, it is showing some tracking movement when the user moves the limbs but all the joints are way-off from the user's body. I have also tried to replace the model in native IOS sample projects but that is not even rendering anything. following are the errors I am getting on console and a snapshot  of unity app running on iPhone Xs max - : 
**in unity build - [Technique] World tracking performance is being affected by resource constraints [1] 
in IOS build - Neither element size > 1 nor attribute count > 1 are supported by 'constant' geometry attribute. Ignoring attribute 'geomNormal'. Element Size '1', Attribute Count: '1983'** 

I am not able to understand these errors. please help me out. 
Thanks 
![ARKit-3_HumanBodyTracking-Issue](https://user-images.githubusercontent.com/32863719/63745180-2e250e80-c8bf-11e9-8060-93ed9e3ad515.jpg)

**Comment by nikolahitek** [comment]
@Pn-io Still facing the sam issues, found any working solution?

**Comment by Pn-io** [comment]
I have resolved this issue, the hack is that every bone transform value(rotation, scale and position) should be same as of robot model, so I used the robot model's rig structure. and applied the skin to my 3d model on that rig. it worked for me. and yes there were some issue in blender exporter so I switched to for import/export.

**Comment by nikolahitek** [comment]
@Pn-io Great to hear that. How did you import the robots rig to unity? I am having trouble accessing it.

**Comment by RoshanJIX** [comment]
@Pn-io  yes please help us out..... how did you get the robot rig from unity. the mesh itself is deleted inside the project folder. 

even the demo scene for body tracking with robot model is not working great for me.

Please shed some light to us. Thanks..

**Comment by ge53** [comment]
i also would much appreciate your response to the above fr RoshanJIX to @Pn-io /thanks

**Comment by Pn-io** [comment]
@RoshanJIX @ge53 @nikolahitek 
I simply deleted the mesh from the controlled robot's fbx file and rigged my character onto that rig. I found this .fbx file from the Xcode project of the same ARKIT 3. Xcode project is also freely available on Github I guess.

**Comment by iguana02** [comment]
> @RoshanJIX @ge53 @nikolahitek
> I simply deleted the mesh from the controlled robot's fbx file and rigged my character onto that rig. I found this .fbx file from the Xcode project of the same ARKIT 3. Xcode project is also freely available on Github I guess.

I'm desperately looking for that model as I have the exact same problem, do you have a link for it?
Thanks!

**Comment by Pn-io** [comment]
actually, I got it from a colleague who is an IOS developer. he said that ARKIT 3 sample project(Xcode project) has that 3d model in FBX format which he gave to me. I have window pc so I never downloaded the Xcode project.

**Comment by iguana02** [comment]
> actually, I got it from a colleague who is an IOS developer. he said that ARKIT 3 sample project(Xcode project) has that 3d model in FBX format which he gave to me. I have window pc so I never downloaded the Xcode project.

I've found the XCODE Project but the robot is in USDZ format which can be exported only in OBJ, without Bones.

**Comment by mdinoulis** [comment]
Does anyone have a link to the rigged skeleton for the ControlledRobot please?
The ARKit 3 repository doesn't seem to exist on github and it doesn't look like there is any way to unpack the ControlledRobot prefab in ARFoundation into its constituent skeleton and mesh.

**Comment by SuhailRahman** [comment]
@mdinoulis you can use this [link](https://github.com/SuhailRahman/VirtualTrialRoom/blob/master/Template%20FBX/ControlledRobotReference.fbx) to download the fbx file with skeleton rigs.

**Comment by xuyixun21** [comment]
> I have resolved this issue, the hack is that every bone transform value(rotation, scale and position) should be same as of robot model, so I used the robot model's rig structure. and applied the skin to my 3d model on that rig. it worked for me. and yes there were some issue in blender exporter so I switched to for import/export.

can you teach me how to change another model?

**Comment by thornebrandt** [comment]
Why was this issue closed?  There doesn't seem to be any solution here. 

> you can use this [link](https://github.com/SuhailRahman/VirtualTrialRoom/blob/master/Template%20FBX/ControlledRobotReference.fbx) to download the fbx file with skeleton rigs.

This link behaves like this in blender: 
![image](https://user-images.githubusercontent.com/1588366/143673372-2d05a34a-fb85-4cb8-9f8b-ef590a00df29.png)

exporting the ControlledRobot prefab with unity fbx exporter yields even stranger results. 

<img width="600" alt="rotation" src="https://user-images.githubusercontent.com/1588366/143673345-0c917416-be03-4443-b28a-d7f9226a4eeb.png">

There still doesn't seem a way to export the controlledRobot or ace_ply mesh in a way that 3d programs can retrieve the bone orientations to port to another model. 

How is anyone using different rigs with this besides the demo?

**Comment by haosizheng** [comment]
I import the .fbx file you guys mentioned and replace the original mesh with my own, and export in Blender.
Unfortunately, some nodes(arms and legs) got different rotation value, so arms and legs are twisted.
I tried several export settings but no one work, maybe I should use a software support y-up axis originally.
Anyone made it on Blender?

**Comment by haosizheng** [comment]
> Why was this issue closed? There doesn't seem to be any solution here.
> 
> > you can use this [link](https://github.com/SuhailRahman/VirtualTrialRoom/blob/master/Template%20FBX/ControlledRobotReference.fbx) to download the fbx file with skeleton rigs.
> 
> This link behaves like this in blender: ![image](https://user-images.githubusercontent.com/1588366/143673372-2d05a34a-fb85-4cb8-9f8b-ef590a00df29.png)
> 
> exporting the ControlledRobot prefab with unity fbx exporter yields even stranger results.
> 
> <img alt="rotation" width="600" src="https://user-images.githubusercontent.com/1588366/143673345-0c917416-be03-4443-b28a-d7f9226a4eeb.png">
> 
> There still doesn't seem a way to export the controlledRobot or ace_ply mesh in a way that 3d programs can retrieve the bone orientations to port to another model.
> 
> How is anyone using different rigs with this besides the demo?

hi, have you tried the first fbx file you mentioned? did it work? I think the image you upload is right even it has a wired rigging visually.

**Comment by haosizheng** [comment]
> yes there were some issue in blender exporter so I switched to for import/export.

hello, how you done export on blender? my rig's rotation changed when I tried to export.

**Comment by mirko900** [comment]
You can download the plugin from unity register to export the prefabs and have the robot's fbx file
