### ISSUE TITLE
How to only detect one plane while scanning plane

### ISSUE THREAD

**Issue by jeremia11** [Unity-Technologies/arfoundation-samples#273]
i want to make plane detection only can scanning one plane. Can any one help me?

**Comment by b29b** [comment]
i have the same issue, i did set "Horizontal" on the session origin but it still scans both

**Comment by Organwolf** [comment]
One way of doing this is either assuming that the first plane you scan is the plane of interest for you and storing that away. Another way of achieving similar results is prompting the user to select the plane of interest. Both yielding similar results. 

Do you just want to detect one particular plane and place something directly afterwards or do you want to keep scanning that particular plane?

**Comment by jeremia11** [comment]
> One way of doing this is either assuming that the first plane you scan is the plane of interest for you and storing that away. Another way of achieving similar results is prompting the user to select the plane of interest. Both yielding similar results.
> 
> Do you just want to detect one particular plane and place something directly afterwards or do you want to keep scanning that particular plane?

i want to detect on particular plane and place object on that area

**Comment by Organwolf** [comment]
Without any actual code specifying what you are trying to do it's hard to help you.

**Comment by b29b** [comment]
[this](https://forum.unity.com/threads/ar-foundation-pausing-resuming-tracking.563272/) helped me  
`foreach (var trackable in planeManager.trackables)
{
    //keep track of initial plane, remove everything else
    trackable.gameObject.SetActive(false);
}`

**Comment by tdmowrer** [comment]
> i have the same issue, i did set "Horizontal" on the session origin but it still scans both

What platform and versions of Unity and packages?

**Comment by b29b** [comment]
> > i have the same issue, i did set "Horizontal" on the session origin but it still scans both
> 
> What platform and versions of Unity and packages?

it is working now, i set horizontal and the floor and ceiling was detected, now i know lol
