### ISSUE TITLE
Detected plane mesh issues

### ISSUE THREAD

**Issue by BrahimHadriche** [Unity-Technologies/arfoundation-samples#274]
Relates to #199 

In regards to issues with planes, I've captured quite a lot of weird behaviours, including duplicate/wrong planes, and/or not a well structured mesh for the plane.

Now I'm wondering what can be the root cause of this?

- ARKit implementation itself
- Bad marshalling from native to C#
- Bad registration of events on the plane manager side (not likely)

These test were made on 

- iPad Pro (iPad OS beta 8)
- Unity 2019.1.10f1
- AR Foundation 2.2.0-preview.3
- AR Kit Plugin 2.2.0-preview.4

Here's a few screenshots

![IMG_0082](https://user-images.githubusercontent.com/45071655/63613340-8ce04480-c5ae-11e9-8b88-cc2770d2361e.PNG)
<img width="1027" alt="Screen Shot 2019-08-23 at 1 57 45 PM" src="https://user-images.githubusercontent.com/45071655/63613341-8ce04480-c5ae-11e9-8c59-1c8ae5946dd8.png">
<img width="1026" alt="Screen Shot 2019-08-23 at 1 57 10 PM" src="https://user-images.githubusercontent.com/45071655/63613342-8ce04480-c5ae-11e9-8840-7d25d074ce0d.png">
![IMG_0083](https://user-images.githubusercontent.com/45071655/63613343-8ce04480-c5ae-11e9-9075-305660cd218f.PNG)
<img width="1027" alt="Screen Shot 2019-08-23 at 1 56 24 PM" src="https://user-images.githubusercontent.com/45071655/63613345-8ce04480-c5ae-11e9-8233-403a9fe2d9ed.png">

**Comment by tdmowrer** [comment]
> iPad Pro (iPad OS beta 8)

There were some oddities with the early iOS 13 betas, but I haven't seen anything like this recently. Are you still having issues after upgrading to iOS 13.1 (non-beta) and Xcode 11 (11A420a)?
