### ISSUE TITLE
Place on Plane and ground detection issue

### ISSUE THREAD

**Issue by grixti** [Unity-Technologies/arfoundation-samples#275]
Relates #274

I want to create a simple project similar to the original HelloAR in ARCore where the ground plane is detected and an object is placed on tap.

I managed to get this to work on my S8 using the 1.1 branch to combine AR foundations and LWRP.

When I switched to using the 2.1 branch however, when I detect the ground plane I get very strange results, like multiple plane detection and the plane colour goes outside the lines.

The worse part is when I tap to spawn the 3D model nothing happens. 

I have debugged to make sure the script PlaceOnPlane is running and getting to the part:

      `spawnedObject = Instantiate(m_PlacedPrefab, hitPose.position, hitPose.rotation);`

Even the hitpose position is changing the values correctly with each tap but the object never appears.

Could this be a limitation of the device (Galaxy S8) or is this a known issue on place on plane with this current branch?

Below I provided an image of the plane detection glitch.

![unity_ground](https://user-images.githubusercontent.com/54468368/63634851-7bee0c80-c65c-11e9-96f5-a60b8198b073.jpg)

**Comment by alter-sachin** [comment]
Were you able to solve this ?

**Comment by tdmowrer** [comment]
This artifact looks like the shaders have not been updated for the Universal Render Pipeline. See [this guide](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.0/manual/upgrading-your-shaders.html) for instructions.
