### ISSUE TITLE
ReferencePoints example with 2.1 branch?

### ISSUE THREAD

**Issue by violetforest** [Unity-Technologies/arfoundation-samples#276]
Any plans on adding the ReferencePoints example to the 2.1 branch? Tried to add it myself but the scripts weren't working, should it theoretically work ?

Thanks!

**Comment by tdmowrer** [comment]
Do you mean https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scripts/ReferencePointCreator.cs ? It should work in 2.1. What didn't work exactly?
