### ISSUE TITLE
Support for Grain, Motion Blur and Depth of Field

### ISSUE THREAD

**Issue by fsal-code** [Unity-Technologies/arfoundation-samples#277]
Are there any plans to support camera calibrated motion blur, depth field and grain like the ones in RealityKit?

**Comment by tdmowrer** [comment]
Yes, we are currently investigating these.

**Comment by fayezsalka** [comment]
Great!

**Comment by tdmowrer** [comment]
Following up on this old thread -- we've exposed these values on the `ARCameraFrameEventArgs` struct. See https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_cameraGrainTexture
