### ISSUE TITLE
Face Tracking Feature

### ISSUE THREAD

**Issue by ghus86** [Unity-Technologies/arfoundation-samples#281]
Hi @tdmowrer 

In version 2.1 of AR Foundation is it possible to get position of the forehead, eyes, mouth, nose ?

Additionally in the Face Pose scene what is the idea regarding the position of the prefab
because when we look forward to the camera it seems to be in the nose 
but if we look to the side it seems like it a position inside our head

best regards

**Comment by yosun** [comment]
Same question! It's possible to get the vertex positions but the eyes don't have a mesh representation. In the old ARKit plugin there was a transform for this...

**Comment by tdmowrer** [comment]
It depends on the platform. ARCore has a concept of [face regions](https://developers.google.com/ar/develop/java/augmented-faces/) while ARKit uses [blend shapes](https://developer.apple.com/documentation/arkit/arfaceanchor/2928251-blendshapes),

We've just released [ARFoundation 3.0](https://forum.unity.com/threads/arfoundation-v3-0.736148/), which includes support for ARKit eye tracking (which gives you positions of the eyes and a look direction).

**Comment by ghus86** [comment]
ok appreciate it thanks for your time
