### ISSUE TITLE
ImageTrackingState is always none

### ISSUE THREAD

**Issue by gweltaz-calori** [Unity-Technologies/arfoundation-samples#282]
When listening to the `trackedImagesChanged` event and by checking either `eventArgs.added`, `eventArgs.updated` or `eventArgs.removed`. The value for the trackingState of the tracked image is always `None`.

I use these packages (I only tested with arcore not arkit)

```
"com.unity.xr.arcore": "2.2.0-preview.2",
"com.unity.xr.arfoundation": "2.2.0-preview.3",
"com.unity.xr.arsubsystems": "2.2.0-preview.3",    
```

**Comment by tdmowrer** [comment]
Hmm, that's strange -- we actually fixed a bug where all tracked images were reported as `Tracking` even when they were not visible. Can you try a more recent release, such as 3.0.0-preview.3?
