### ISSUE TITLE
Is an external camera recognizable ?

### ISSUE THREAD

**Issue by PanMig** [Unity-Technologies/arfoundation-samples#283]
Hello all,

I have an app where I capture the camera's view and process it through a computer vision algorithm. For the time, I am using the phone's (android) native camera and extract the image.

Is it possible to connect to the phone another third-party camera (e.g usb, wifi camera) and have that camera recognized through the Unity application ?

Thank you in advance,
Panos

**Comment by tdmowrer** [comment]
Sounds like you might be looking for the [WebCamTexture](https://docs.unity3d.com/ScriptReference/WebCamTexture.html), though I'm confused by
> possible to connect to the phone another third-party camera

Do you want to connect a web cam to your phone or access a usb camera in the Editor?

**Comment by PanMig** [comment]
> Sounds like you might be looking for the [WebCamTexture](https://docs.unity3d.com/ScriptReference/WebCamTexture.html), though I'm confused by
> 
> > possible to connect to the phone another third-party camera
> 
> Do you want to connect a web cam to your phone or access a usb camera in the Editor?

Well to be exactly specific, I am having an android application made with Unity. The app uses the AR foundation camera, where I receive the camera image using this script (https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/manual/cpu-camera-image.html)
and does some preprocessing.

Now, what I want to achieve is rather than using the phone's native camera, I would like to connect a usb camera or wifi to the phone and use it as the main camera, so I can extract images from it. So is it possible to connect external cameras to the AR camera ?

**Comment by tdmowrer** [comment]
> Now, what I want to achieve is rather than using the phone's native camera, I would like to connect a usb camera or wifi to the phone and use it as the main camera, so I can extract images from it.

That might be possible, but you wouldn't be using any ARFoundation APIs, as those only access the camera associated with the camera used by ARKit or ARCore.

> So is it possible to connect external cameras to the AR camera ?

You can't tell ARKit/ARCore to use an arbitrary camera. The algorithms used by those SDKs require precise (and in some cases proprietary) information about the camera hardware, and there is no way to plug in a different camera.
