### ISSUE TITLE
Detected plane and the plane texture are not at the same position when using LWRP

### ISSUE THREAD

**Issue by RealMSHB** [Unity-Technologies/arfoundation-samples#284]
Hi
I want to use Ar foundation and LWRP at the same time. after spending one day to get the LWRP work with AR foundation, now I have a problem that the plane detection works correctly and I can see the generated lines around the detected plane but the texture of the plane is at the height and position of the camera.

this is without the LWRP assigned:
![photo_2019-08-29_16-21-56](https://user-images.githubusercontent.com/8512440/63948547-28732880-ca79-11e9-8ce2-b93a16574847.jpg)

this is with LWRP:
![photo_2019-08-29_16-21-47](https://user-images.githubusercontent.com/8512440/63948637-493b7e00-ca79-11e9-9a38-e5cc90efa8d8.jpg)

I have also tested the branch sample project that is available in one of the branches here and it has the same problem.

Unity 2019.1.14f1
![Annotation 2019-08-29 162553](https://user-images.githubusercontent.com/8512440/63948838-b222f600-ca79-11e9-8f3a-c14d70e76ba5.png)

**Comment by tdmowrer** [comment]
ARFoundation 3.0 has much better LWRP and UniversalRP support. Could you try that? Here are [step-by-step instructions](https://forum.unity.com/threads/configuring-ar-foundation-3-0-0-preview-to-work-with-lwrp-or-urp.736583/).

**Comment by apatelcgs** [comment]
same issue with 3.0

**Comment by apatelcgs** [comment]
> ARFoundation 3.0 has much better LWRP and UniversalRP support. Could you try that? Here are [step-by-step instructions](https://forum.unity.com/threads/configuring-ar-foundation-3-0-0-preview-to-work-with-lwrp-or-urp.736583/).

same issue with 3.0, unity 2019.3.0a11

**Comment by tdmowrer** [comment]
On what device(s) have you reproduced this issue? Is it limited to Android or iOS?

**Comment by mdurand42** [comment]
This looks as though it is a consequence of not updating shaders for scriptable pipelines. Please follow the instructions for configuring your project for URP and re-open the issue if needed. 

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/ar-camera-background-with-scriptable-render-pipeline.html
