### ISSUE TITLE
LWRP does not support

### ISSUE THREAD

**Issue by dushan555** [Unity-Technologies/arfoundation-samples#286]
Is the previous LWRP branch not supported now?

**Comment by tdmowrer** [comment]
https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp-support-2018.3-with-1.0 and https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp-support-2018.3-with-1.5 are still valid, but the 2019.1-specific branch has been removed. LWRP and UniversalRP support are supported out-of-the-box in 3.0. Instructions [here](https://forum.unity.com/threads/configuring-ar-foundation-3-0-0-preview-to-work-with-lwrp-or-urp.736583/).

**Comment by tdmowrer** [comment]
Linear color space is supported in 3.0.0-preview.3, which requires Unity 2019.2+.
