### ISSUE TITLE
Unable to add ARTrackedObjectManager at runtime

### ISSUE THREAD

**Issue by QuentinBrun2** [Unity-Technologies/arfoundation-samples#287]
Hi, 

I would like to explain my case:

- I am not starting the AR session at the begining. 
- I want to add ARTrackedObject manager to the origin session game object before starting the AR session
- I want to add a choosen XRReferenceObjectLibrary on the ARTrackedObjectManager (maybe we have N XRReferenceObjectLibrary available, one for each location and we need to configure it at runtime)
- Then the user start the AR session

I am unable to do that for now because:

- ARTrackedObjectManager will not have been "awaked" as the session is not yet started and the initialization of m_referenceObjects is done on awake. ARTrackedObjectManager try to m_ReferenceObjects.Clear() when we set the XRReferenceObjectLibrary. Maybe the code should not "UpdateReferenceObjects" if the ARSession as not started or we should init the m_referenceObjects at object creation.
- Also I cannot start the session without setting the XRReferenceObjectLibrary (Maybe I could have done it after starting the session)

I could do something else: 
 - create multiple prefab of ARSessionOrigin preconfigured with a ARTrackedObjectManager and the right XRReferenceObjectLibrary but that is difficult to maintain.

Do you know another way to achieve what I want to do? Or would a change in the ARFoundation code be possible?

Thank you.

**Comment by tdmowrer** [comment]
This was fixed in 3.0.0-preview.1. From the [change log](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/changelog/CHANGELOG.html#improvements):

> Previously, the `ARTrackedImageManager` and `ARTrackedObjectManager` would throw an exception if enabled without a valid reference library. These managers no longer throw; now, they disable themselves. This makes it possible to add one of these managers at runtime, since Unity will automatically invoke `OnEnable` before you have a chance to set a valid reference library. If you create one of these managers at runtime, you will need to set a valid reference library and then re-enable it.
