### ISSUE TITLE
Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements

### ISSUE THREAD

**Issue by TimmyBest** [Unity-Technologies/arfoundation-samples#289]
Just building the example completely untouched.

Previous ARFoundation version works fine.
Xcode Version 11.0 beta 4 
Unity Version 2019.2.0f1

`ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_UnityARKit in UnityARKit.a(ParticipantProvider.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_UnityARKit in UnityARKit.a(TrackableProvider.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_UnityARKit in UnityARKit.a(Utilities.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_UnityARKit in UnityARKit.a(EventSystem.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_UnityARKit in UnityARKit.a(TrackableChanges.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_UnityARKit)
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_UnityARKit in UnityARKit.a(ParticipantProvider.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_UnityARKit in UnityARKit.a(TrackableProvider.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_UnityARKit in UnityARKit.a(Utilities.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_UnityARKit in UnityARKit.a(EventSystem.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_UnityARKit in UnityARKit.a(TrackableChanges.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_UnityARKit)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

[SCREENSHOT](https://i.imgur.com/ZNTdxvc.png)

**Comment by TimmyBest** [comment]
Xcode Update to Version 11.0 beta 6 solved the issue

**Comment by acalism** [comment]
I'm using Xcode 11.4, and the error appears

**Comment by acalism** [comment]
Create an Empty Swift file using Xcode, and every issue will be solved by Xcode automatically.

**Comment by tdmowrer** [comment]
Sorry, issue was related to last year's Xcode beta. @acalism are you saying you are seeing this in the current version of Xcode (11.4)?

**Comment by acalism** [comment]
Xcode 11.4 works OK now. @tdmowrer thank you for your reply.

**Comment by HuuLinhDra** [comment]
I using Xcode 11.6 and have same error

**Comment by tdmowrer** [comment]
@HuuLinhDra This is an old issue and no longer relevant (we do not use Swift at all in the ARKit plugin). Could you please open a new issue with more details for your specific issue?
