### ISSUE TITLE
AR Foundation 3.0.0 Image Tracking not working

### ISSUE THREAD

**Issue by FDDdan** [Unity-Technologies/arfoundation-samples#290]
I can't get Image Tracking to work using AR Foundation 3.0.0 preview 1, not even the sample scene.

Unity 2019.2.3f1
ARFoundation 3.0.0 preview 1
ARCore XR Plugin 3.0.0 preview 1
ARKit XR Plugin 3.0.0 preview 1
Android 9

**Comment by bryanrtboy** [comment]
I'm having the same issue, with the same setup. Enabling 'Development Build' in the Build settings allows an ImageTracking scene to load, the background camera shows up but it does not seem to function. If I disable Development Build, the scene does not load and crashes the app with this error:

`09/04 17:07:23.600 22330 22347 Info native: arpresto_api.cc:68 ArPresto::ArPresto_checkApkAvailability
09/04 17:07:23.641 22330 22347 Error Unity: MarshalDirectiveException: Cannot marshal type 'UnityEngine.XR.ARCore.NativeView'1'.
09/04 17:07:23.641 22330 22347 Error Unity:   at UnityEngine.XR.ARCore.ARCoreImageDatabase.UnityARCore_ImageDatabase_deserialize (UnityEngine.XR.ARCore.NativeView'1[T] serializedDatabase, UnityEngine.XR.ARCore.NativeView'1[T] referenceImages) [0x00000] in <00000000000000000000000000000000>:0 
09/04 17:07:23.641 22330 22347 Error Unity:   at UnityEngine.XR.ARCore.ARCoreImageDatabase..ctor (UnityEngine.XR.ARSubsystems.XRReferenceImageLibrary serializedLibrary) [0x00000] in <00000000000000000000000000000000>:0 
09/04 17:07:23.641 22330 22347 Error Unity:   at UnityEngine.XR.ARCore.ARCoreImageTrackingProvider+Provider.CreateRuntimeLibrary (UnityEngine.XR.ARSubsystems.XRReferenceImageLibrary serializedLibrary) [0x00000] in <00000000000000000000000000000000>:0 
09/04 17:07:23.641 22330 22347 Error Unity:   at UnityEngine.XR.ARSubsystems.XRImageTrackingSubsystem.CreateRuntimeLibrary (UnityEngine.XR.ARSubsystems.XRReferenceImageLibrary serializedLibrary) [0x00000] in <00000000000000000000000000000000>:0 
09/04 17:07:23.641 22330 22347 Error Unity:   at UnityEngine.XR.ARFoundation.ARTrackedImageManager.OnBeforeStart () [0x00000] in <0000000000000000
`

**Comment by tdmowrer** [comment]
This was an issue on IL2CPP only and has been fixed in [3.0.0-preview.2](https://forum.unity.com/threads/arfoundation-v3-0.736148/)
