### ISSUE TITLE
Cannot build for Android in AR Foundation 3.0

### ISSUE THREAD

**Issue by hyperbting** [Unity-Technologies/arfoundation-samples#292]
Updating the Unity 2019 2.3 to try out this sample and not work anymore.
While the scripting backend set as Mono, it seems works; however, when scripting backend set as IL2CPP for arm64 it cannot be compiled anymore.  Using either NDK r16 or NDK Unity recommended doeat not work.

In the build log, it says 
> D:\Workbench\Unity\ARExplorer2019\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp16.cpp:13920: error: undefined reference to 'UnityMC_Delegate_getEnabled'

**Comment by dnnkeeper** [comment]
I'm getting similar error with 2019.3.0b1 when trying to compile IL2Cpp ARM64: 

> Failed running C:\Program Files\Unity\Hub\Editor\2019.3.0b1\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARM64" --configuration="Release" --outputpath="D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\assets\bin\Data\Native\arm64-v8a\libil2cpp.so" --cachedirectory="D:\Projects\UnitySamples\arfoundation-samples\Assets\..\Library\il2cpp_android_arm64-v8a/il2cpp_cache" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.3.0b1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.3.0b1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/Program Files/Unity/Hub/Editor/2019.3.0b1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --enable-debugger --profiler-report --map-file-parser="C:/Program Files/Unity/Hub/Editor/2019.3.0b1/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory=D:/Projects/UnitySamples/arfoundation-samples/Temp/StagingArea/assets/bin/Data/Managed --generatedcppdir=D:/Projects/UnitySamples/arfoundation-samples/Temp/StagingArea/Il2Cpp/il2cppOutput 
> 
> stdout:
> Building libil2cpp.so with AndroidToolChain
> 	Output directory: D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\assets\bin\Data\Native\arm64-v8a
> 	Cache directory: D:\Projects\UnitySamples\arfoundation-samples\Library\il2cpp_android_arm64-v8a\il2cpp_cache
> ObjectFiles: 326 of which compiled: 175
> 	Time Compile: 16399 milliseconds com.unity.multiplayer-hlapi.Runtime3.cpp
> 	Time Compile: 14365 milliseconds mscorlib4.cpp
> 	Time Compile: 14084 milliseconds UnityEngine.IMGUIModule.cpp
> 	Time Compile: 13485 milliseconds UnityEngine.UI1.cpp
> 	Time Compile: 12796 milliseconds com.unity.multiplayer-hlapi.Runtime2.cpp
> 	Time Compile: 12204 milliseconds UnityEngine.UI4.cpp
> 	Time Compile: 11737 milliseconds UnityEngine.UI3.cpp
> 	Time Compile: 11238 milliseconds com.unity.multiplayer-hlapi.Runtime4.cpp
> 	Time Compile: 10962 milliseconds System1.cpp
> 	Time Compile: 10791 milliseconds com.unity.multiplayer-hlapi.Runtime.cpp
> Total compilation time: 125332 milliseconds.
> il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files\Unity\Hub\Editor\2019.3.0b1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\Boris\AppData\Local\Temp\tmp48AE.tmp" -o "D:\Projects\UnitySamples\arfoundation-samples\Library\il2cpp_android_arm64-v8a\il2cpp_cache\linkresult_27AE9C3E6C8515554B6D0B03BB33BC2E\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "C:\Program Files\Unity\Hub\Editor\2019.3.0b1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\platforms\android-21\arch-arm64" -gcc-toolchain "C:\Program Files\Unity\Hub\Editor\2019.3.0b1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64" -target aarch64-none-linux-android -Wl,--wrap,sigaction -nostdlib++ -L "C:\Program Files\Unity\Hub\Editor\2019.3.0b1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\sources\cxx-stl\llvm-libc++\libs\arm64-v8a" -lc++_static -lc++abi -llog -rdynamic -fuse-ld=bfd.exe
> 
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_GetEnabled_m1352D3BB89F1E2288259E27BCC14B88DD28346F2':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7662: undefined reference to `UnityMC_Delegate_getEnabled'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7662: undefined reference to `UnityMC_Delegate_getEnabled'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_SetEnabled_m830C96BE43C42A8B773FD05F57EC29025739979B':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7652: undefined reference to `UnityMC_Delegate_setEnabled'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7652: undefined reference to `UnityMC_Delegate_setEnabled'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_InitWithName_m257A01B9CB52E17BF7C0E6FDB79CDD96A92F778E':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7608: undefined reference to `UnityMC_Delegate_initWithName'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_CreateWithString_m4A523330BA62F56ED54D62A4B8B47168BBD278C5':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9535: undefined reference to `UnityMC_NSString_createWithString'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_InitWithName_m257A01B9CB52E17BF7C0E6FDB79CDD96A92F778E':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7608: undefined reference to `UnityMC_Delegate_initWithName'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_SendToAllPeers_m7A1C02515DE2D594B1C43037937EAA6F150C2A7C':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7597: undefined reference to `UnityMC_Delegate_sendToAllPeers'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7597: undefined reference to `UnityMC_Delegate_sendToAllPeers'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_GetReceivedDataQueueSize_m6EE26BCCC6CE73C9DA140DA38B2DF20EEC743BE5':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7619: undefined reference to `UnityMC_Delegate_receivedDataQueueSize'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7619: undefined reference to `UnityMC_Delegate_receivedDataQueueSize'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_DequeueReceivedData_m25F571EB3FCAFF389F67A75EB85B0F077E5B1A18':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7630: undefined reference to `UnityMC_Delegate_dequeueReceivedData'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7630: undefined reference to `UnityMC_Delegate_dequeueReceivedData'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `MCSession_GetConnectedPeerCount_m98BAE00D4EE4F022B8BABB7A1B97223A23280702':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7641: undefined reference to `UnityMC_Delegate_connectedPeerCount'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:7641: undefined reference to `UnityMC_Delegate_connectedPeerCount'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NativeApi_CFRelease_m1D69A5F7B3E3CDFD8A058B0C7C9F01C460CE81ED':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9639: undefined reference to `UnityMC_CFRelease'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSData_GetLength_m11AFC2D90C32E1277E089E944DFEA5ADCDD8E62C':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8243: undefined reference to `UnityMC_NSData_getLength'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8243: undefined reference to `UnityMC_NSData_getLength'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSData_CreateWithBytes_mA4F8281A4AF67130166B0B40838C8D33B8CF2533':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8265: undefined reference to `UnityMC_NSData_createWithBytes'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8265: undefined reference to `UnityMC_NSData_createWithBytes'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSData_CreateWithBytesNoCopy_m1B67202E16C655012FD9A5D1E2026EB99073F426':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8276: undefined reference to `UnityMC_NSData_createWithBytesNoCopy'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8276: undefined reference to `UnityMC_NSData_createWithBytesNoCopy'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSData_GetBytes_m0053B74EC37B5E73C1B58D72FC24CE75A441C63F':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8254: undefined reference to `UnityMC_NSData_getBytes'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSData_GetLength_m11AFC2D90C32E1277E089E944DFEA5ADCDD8E62C':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8243: undefined reference to `UnityMC_NSData_getLength'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSData_GetBytes_m0053B74EC37B5E73C1B58D72FC24CE75A441C63F':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8254: undefined reference to `UnityMC_NSData_getBytes'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSError_GetCode_m55A658BC794E4DFB507E767634B6976BCBAA2111':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8754: undefined reference to `UnityMC_NSError_code'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSError_GetLocalizedDescription_mA40BFDB05AC0478CC263AA60425DB5266283BD4F':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8765: undefined reference to `UnityMC_NSError_localizedDescription'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSError_GetCode_m55A658BC794E4DFB507E767634B6976BCBAA2111':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8754: undefined reference to `UnityMC_NSError_code'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSError_GetLocalizedDescription_mA40BFDB05AC0478CC263AA60425DB5266283BD4F':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:8765: undefined reference to `UnityMC_NSError_localizedDescription'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_GetLengthOfBytes_mBA74DF41F322AB255A8061E5C553DA189897F085':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9546: undefined reference to `UnityMC_NSString_lengthOfBytesUsingEncoding'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_GetBytes_m2F6967C1BCD0C4FE14A5B10C7FB991EE18391114':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9568: undefined reference to `UnityMC_NSString_getBytes'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_CreateWithString_m4A523330BA62F56ED54D62A4B8B47168BBD278C5':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9535: undefined reference to `UnityMC_NSString_createWithString'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_Deserialize_m1CB46F2F5D4804B2972B4209F65A20ACDA4172BF':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9590: undefined reference to `UnityMC_NSString_deserialize'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9590: undefined reference to `UnityMC_NSString_deserialize'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_GetLength_mE3EB5C29E7E81492F249CA81C3282E0C263E44A5':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9557: undefined reference to `UnityMC_NSString_getLength'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9557: undefined reference to `UnityMC_NSString_getLength'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_GetLengthOfBytes_mBA74DF41F322AB255A8061E5C553DA189897F085':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9546: undefined reference to `UnityMC_NSString_lengthOfBytesUsingEncoding'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_GetBytes_m2F6967C1BCD0C4FE14A5B10C7FB991EE18391114':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9568: undefined reference to `UnityMC_NSString_getBytes'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NSString_Serialize_m4CBE73237C43761720E66E4D11EE97B4DF62B526':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9579: undefined reference to `UnityMC_NSString_serialize'
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9579: undefined reference to `UnityMC_NSString_serialize'
> D:/Projects/UnitySamples/arfoundation-samples/Library/il2cpp_android_arm64-v8a/il2cpp_cache/452AA188CFA22908F5DF52E88896342D.o: In function `NativeApi_CFRelease_m1D69A5F7B3E3CDFD8A058B0C7C9F01C460CE81ED':
> D:\Projects\UnitySamples\arfoundation-samples\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp1.cpp:9639: undefined reference to `UnityMC_CFRelease'
> clang++.exe: error: linker command faile<message truncated>

**Comment by DavidMohrhardt** [comment]
This is a mistake on our end.  We have native iOS multipeer code in our samples to show off some ARKit 3 specific features.  Unfortunately we didn't add the proper guards and now your android compiler is trying to link agains targets in Obj C native code (which won't compile for android) hence the undefined symbols.  We will work on getting this out to the samples to make sure that people don't run into this issue but for now you can use the following asmdef in the multipeer scripts folder as a workaround:

`{
    "name": "iOSUnityMultipeer",
    "references": [],
    "includePlatforms": [
        "Editor",
        "iOS"
    ],
    "excludePlatforms": [],
    "allowUnsafeCode": true,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": []
}`

**Comment by tdmowrer** [comment]
This was an issue with the samples and has now been fixed.
