### ISSUE TITLE
How to deactivate gameobject while detect plane in AR Foundation

### ISSUE THREAD

**Issue by jeremia11** [Unity-Technologies/arfoundation-samples#293]
Can any one help me with script or suggestion with this threat? i have been try edit script in ar plane manager but not work. I dont know why.....

**Comment by tdmowrer** [comment]
If you're just trying to deactivate the `GameObject`s associated with an `ARPlane`, you can use the usual `GameObject` API:

```csharp
ARPlane plane = ...
plane.gameObject.SetActive(false);
```

You can also disable the [`GameObject`s for all planes](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARTrackableManager-4.html#UnityEngine_XR_ARFoundation_ARTrackableManager_4_SetTrackablesActive_System_Boolean_).
