### ISSUE TITLE
TrackableId : how to match it with native ARKit anchors ?

### ISSUE THREAD

**Issue by thibautvdu** [Unity-Technologies/arfoundation-samples#294]
Dear all,

I'm manually retrieving the ML surface classifications from iOS as it isn't implemented in ARFoundation. Everything works fine (I share the ARKit session between Unity and a native swift delegate), but I would like to match the classification results I get with Unity's ARPlane trackable objects. In order to do so, I need to match the native anchor's UUID with ARFoundation's opaque 'TrackableId' structure.

There is not explanation in the documentation regarding how this TrackableId object is constructed from the native ARKit objects and ARfoundation closed sources doesn't allow me to dig in the code. It contains two ulong, would anyone have any insight around this issue ? Am I missing something ? I tried to look up the old Unity ARKit plugin, but it seems that the anchor's ID were handled completely differently back then so it is no help here.

side-note : I really wished ARfoundation was open source to avoid having to those counter-efficient tricks to get the latest features...

Many thanks !

**Comment by tdmowrer** [comment]
Please see the documentation on ["Extending AR Foundation"](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/extensions.html)

**Comment by thibautvdu** [comment]
@tdmowrer Thank you, I ended up implementing your suggestion. For reference, all you have to do is to create an objective c function such as : 

```
struct NativeARPlanePointer {
    int* version;
    ARPlaneAnchor* plane;
};

extern "C"{
    ARPlaneClassification ARKitBridge_getPlaneClassification(const NativeARPlanePointer *p) {
        return p->plane.classification;
    }
}
```
