### ISSUE TITLE
Light Estimation is not working in sample scene

### ISSUE THREAD

**Issue by chhuang76** [Unity-Technologies/arfoundation-samples#296]
Unity: 2018.4.4.f1
AR Foundation: 1.5.0-preview.6
AR Kit XR Plugin: 2.2.0-preview.5
AR Foundation Samples: 07df13d (branch 1.5-preview Aug 29, 2019)
Xcode: Version 11.0 beta 6 (11M392q)
Device: iPad Pro
OS: iOS 12.4

Steps to reproduce:

1. Open LightEstimation scene and make sure the "AR Camera Manager" component in the scene has "Light Estimation Mode" set to "Ambient Intensity"
2. Add the LightEstimation scene in Build Settings
3. Make a build and run on devices

Results:
On the UI overlay, "Color Temp" is showing the right values while "Brightness" and "Color Correct" are showing "Unavailable".

Expected Results:
"Brightness" should also show the correct value.

I've also added the following line to LightEstimation.FrameChanged:
`Debug.Log(args);`

And the result in the log is:
lightEstimation: (Avg. Brightness: , Avg. Color Temperature: 4588.105, Color Correction: )

**Comment by tdmowrer** [comment]
Generally, you should not mix Xcode 11 beta and pre-iOS 13. Either update your device to iOS 13.1 beta 2, or use ARKit XR Plugin 2.1 (which was built with Xcode 10).

That said, I just tried ARFoundation 3.0 (which hasn't changed wrt lighting estimation) building with Xcode 11 beta 7 and the ambient lighting estimation works on both an iPad Pro running iOS 13.1 and an iPhone 6S running iOS 12.1.

If you can reproduce this on an iOS 13.1 device or on iOS 12.4 with ARKit XR Plugin 2.1, please let us know.

**Comment by chhuang76** [comment]
Thank you for looking into this! I managed to reproduce the issue on iOS13.1.

Device: iPad Pro
OS: iOS 13.1 beta 2 (17A5831c)
Xcode: Version 11.0 (11M392r) (I'm not sure if this version is beta 6 or beta 7. It says beta 7 on https://developer.apple.com/download/ but beta 6 on Xcode > About Xcode)

Results:
Same as the original comment. Color Temp is working but Brightness and Color Correct are not.

**Comment by tdmowrer** [comment]
Managed to reproduce it. Looks like ARFoundation 1.5 was missing a feature from a later version. It'll be in the next 1.5 preview release.

**Comment by jasr88** [comment]
Unity: 2019.2.12.f1
AR Foundation: 3.0.0 preview.6
ARCore XR Plugin 3.0.0 preview.4
AR Foundation Samples: 32731a8(branch master Nov 16, 2019)
Device(s): Samsung Galaxy S9+, Motorola one Zoom, Xiaomi Mi MIX 2S (And any other random android device i´ve tested on the project)
OS: Android 9
Hello, well now the values are showed, but it can be correct, for example, the color correction values when i cover my camera and only can see a black screen are: 

**Color Correct RGBA(1.061, 1.000, 0.870, 0.189)**

But is imposible that those values make an RGBA color!.
A few monts ago this feature used to work just fine

**Comment by AlexSilva88** [comment]
So... no news about this issue?

**Comment by tdmowrer** [comment]
Those values look alright to me. The alpha channel corresponds to the brightness (it is the same as the reported "average brightness") and so I would expect it to be small if covering the camera. The values of the RGB are a _correction_ factor. See [ArLightEstimate_getColorCorrection](https://developers.google.com/ar/reference/c/group/light#group__light_1ga8f0beabc1aa0efcab66e71611978dc3c) for more information on interpreting this value.
