### ISSUE TITLE
CameraImage and worldmap

### ISSUE THREAD

**Issue by Davidwang007** [Unity-Technologies/arfoundation-samples#300]
1. The image i got from the Samples of CameraImage  was rotated 90 degree in clockwise, and i can't get the greyscale image by set the TextureFormat.Alpha8 or TextureFormat.R8, is it a problem ?

2.With the worldmap Sample, i modified it to put some cubes in the detected plane,then save it ,but i can't load the cubes when i load it again. The tips from the screen said it was saved and loaded successfully .

**Comment by tdmowrer** [comment]
> 1. The image i got from the Samples of CameraImage was rotated 90 degree in clockwise

That is expected. It's the raw camera image and is not transformed in any way (except for the optional downsampling and color conversions).

> and i can't get the greyscale image by set the TextureFormat.Alpha8 or TextureFormat.R8, is it a problem ?

That doesn't sound right. Can you post some sample code showing what you're trying to do?

> 2.With the worldmap Sample, i modified it to put some cubes in the detected plane,then save it ,but i can't load the cubes when i load it again. The tips from the screen said it was saved and loaded successfully .

`ARWorldMap` is an ARKit construct. It contains information about the physical environment and detected features. It is not aware of anything in the Unity scene, so the cubes in your example would not be serialized as part of the world map.

**Comment by Davidwang007** [comment]
thanks for your replay,about question 2,i used the code like bellow:
`    unsafe void OnCameraFrameReceived(ARCameraFrameEventArgs eventArgs)
    {
        XRCameraImage image;
        if (!mARCameraManager.TryGetLatestImage(out image))
            return;

        var format = TextureFormat.R8;
        var conversionParams = new XRCameraImageConversionParams(image, format, CameraImageTransformation.None);
        mTotalSize = image.GetConvertedDataSize(conversionParams);
        if (mTexture == null || mTexture.width != image.width || mTexture.height != image.height)
        {
            
            mTexture = new Texture2D(image.width, image.height, format, false);
            mFinalImage = new byte[mTotalSize];
        }        
        var rawTextureData = mTexture.GetRawTextureData<byte>();
        try
        {
            image.Convert(conversionParams, new IntPtr(rawTextureData.GetUnsafePtr()), rawTextureData.Length);
            Sobel(mFinalImage, mTexture.GetRawTextureData(), image.width, image.height);
            mTexture.LoadRawTextureData(mFinalImage);
            mTexture.Apply();
        }
        finally
        {
            image.Dispose();
        }
        
        mRawImage.texture = mTexture;
    }`
and got the resout like this:
![123](https://user-images.githubusercontent.com/55229704/66623233-4659ae80-ec1d-11e9-97b9-b83a4d7d81f3.png)

**Comment by tdmowrer** [comment]
Looks cool! Sorry, did you have another question?

**Comment by Davidwang007** [comment]
Yes,the question here is i can't get the greyscale image by by use the TextureFormat.Alpha8 or TextureFormat.R8. as the information from 
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/cpu-camera-image.html
said:
use TextureFormat.Alpha8 and TextureFormat.R8 i can get the greyscale image.
so,How to get the greyscale image ?

**Comment by tdmowrer** [comment]
It looks like it is working to me. What is the problem?

**Comment by Davidwang007** [comment]
when use TextureFormat.Alpha8  i just get the Alpha channel data of the rawimage,
and TextureFormat.R8 just get the R channel ,not greyscale image expected. 
the picture above showed that when use TextureFormat.R8 the result is red not grey.
the greyscale image which i expected is only has one channel and don't has any color pixel ,just grey.

how can i get it ?

**Comment by Davidwang007** [comment]
just like this one
![QQ截图20181114202126](https://user-images.githubusercontent.com/55229704/66790664-3abefe00-ef23-11e9-8ddb-673674ba8083.jpg)

**Comment by tdmowrer** [comment]
You're extracting the grayscale component of the camera image and storing it somewhere. Unity doesn't have a "grayscale" texture format (i.e., a texture format that always renders in gray), so it must be stored in an R8 or Alpha8 texture image format. However, you are operating on the gray channel of the camera image.

If you need to _render_ it in grayscale, I suggest using a shader which samples a Texture2D in R8 format and generates a color whose rgb values are all equal to that value. However, if you just want to _debug_ that the image is correct, I would leave it as is.

**Comment by Davidwang007** [comment]
OK,i got it,thank you very much!
