### ISSUE TITLE
'Scale' example no longer works in ‘preview.2 - 3.0.0’

### ISSUE THREAD

**Issue by StevenBrammah** [Unity-Technologies/arfoundation-samples#301]
The ‘Scale’ scene no longer works in the examples. It seems to be something that has changed in ‘preview.2 3.0.0’ as this example works in preview.1 3.0.0’. 
The issue seems to occur when a user taps on a trackable plane. This makes both the content and planes seem to disappear. This is called on Update in the ‘MakeAppearOnPlane.cs’ script.

Noticed in ‘preview.2 - 3.0.0’ the Content Placement Offset Transform position has some strange values.

Current Setup:
- Unity 2019.2.4f1

- Xcode 11 beta 7
- iPadOS 13.1 beta

- AR Foundation preview.2 - 3.0.0
- ARKit XR Plugin preview.2 - 3.0.0

**Comment by sergiosolorzano** [comment]
Bump

**Comment by amadis77** [comment]
In 'preview.3 - 3.0.0' the trackable planes and content sometimes remain visible but in a different location.  Here is the behavior I witnessed:

- Plane discovery and tracking works as expected at app start
- Touch on the plane makes the Content object appear at the expected location
- Most Common Behavior - Immediately upon Touch, the Scene shrinks (trackable planes and Content), quickly becoming too small to see (in one of my apps I cast a ray from the center of my screen and it still hits a trackable plane, causing my anchor button to appear).  If plane discovery is still working, new planes are not visible.
- One Time Behavior - Immediately upon Touch, the Scene shrank by ~20% (trackable planes and Content both) and translated along the Z-axis a short distance.  I saw them after looking around with the device.  The Content object no longer appeared on the trackable plane it was expected to be on.
- ScaleController, in this instance, affected both the Content object and the trackable planes independently.  RotationController, in this instance, also affected both the Content object and the trackable planes, but all objects appeared to rotate around the same point (if I had to guess, I would say scene origin, but I can't prove it).

Current Setup:

- Unity 2019.3.0b7
- ARCore XR Plugin preview.3 - 3.0.0
- AR Foundation preview.3 - 3.0.0
- Android 9 (Samsung Galaxy S9+)

I hope this helps in the investigation (using AR Foundation and Scale in my Thesis...so...good luck!)

**Comment by tdmowrer** [comment]
Fixed in 3.0.0-preview.4

**Comment by mubeenfahmed** [comment]
**My Setup:**
Unity 2019.2.11
AR Foundation preview 4 3.1.0

@tdmowrer I am having an issue with scaling, if I either scale up or down and then re-instantiate the object on by tapping on the detected plane. The object doesn't appear there, it is placed out of my camera view. What should I do now, need help Urgently.

**Comment by mubeenfahmed** [comment]
**My Setup:**
Unity 2019.2.11
AR Foundation preview 3.1.0

@tdmowrer I am having an issue with scaling
