### ISSUE TITLE
makecontentappearat makes planes and content drift off

### ISSUE THREAD

**Issue by sergiosolorzano** [Unity-Technologies/arfoundation-samples#303]
FYI I used the function when instantiating (not scaling or rotating etc). I no longer use it but transform.position because otherwise all contents drifts off to another location. On Unity 2019.2.2f1 ARF prev .2 3.0.0 lwrp 6.9.1

**Comment by StevenBrammah** [comment]
This issue also relates to this issue: https://github.com/Unity-Technologies/arfoundation-samples/issues/301 still waiting for response.

**Comment by mdurand42** [comment]
Please try this with URP support and re-open if the issue persists.
