### ISSUE TITLE
Sample Scenes crash EXC_BAD_ACCESS (code=1, address=0x3cbfa49b1ed0)

### ISSUE THREAD

**Issue by tokageD** [Unity-Technologies/arfoundation-samples#304]
I trying ARFoundation 3.0 example scenes. But they doesn’t work. "EXC_BAD_ACCESS (code=1, address=0x3cbfa49b1ed0)" occurred at start up program.

MacOS : 10.15 Beta（19A558d）
Unity : 2019.2.5f1
ARFoundation : preview.2 - 3.0.0
ARSubsystems and some  : preview.2 - 3.0.0
Xcode : 11.0 (11A419c)
Target : iPad Pro   iPadOS 13.1(17A5837a)
Scene :  Check Support  (and some scene don’t work as same)

Attached log is Device log.
[ARFoundationDeviceLog20190916.log](https://github.com/Unity-Technologies/arfoundation-samples/files/3616224/ARFoundationDeviceLog20190916.log)

**Comment by AbrahamManomotion** [comment]
Out of curiosity, which device are you deploying for? I am also facing similar issues and I want to rule out 13.1 being the issue.

**Comment by tokageD** [comment]
I'm deploying for iPad Pro iPadOS 13.1(17A5837a).


I retried from recreating the project folder.
As a result, the problem no longer occurred.

Sorry, there might have been a problem in my project folder ...

**Comment by tokageD** [comment]
I found below.
In the case of using Unity ver.2019.2.4f1, it works with no error.
However, when using Unity ver.2019.2.5f1, some error occurred regarding the shader, and occurred this issue.

**Comment by tdmowrer** [comment]
Hmm, that sounds very odd, and I doubt it is related to a point revision of Unity. Looks like a crash in the Metal shader compiler. You mentioned using Xcode : 11.0 (11A419c), which is the GM seed. You might want to update to the officially released version (11A420a).

**Comment by tdmowrer** [comment]
Closing as I suspect this is related to a pre release. Please reopen if the problem persists.
