### ISSUE TITLE
Crash when disabling ARHumanBodyManager, with Multithreaded rendering

### ISSUE THREAD

**Issue by NumaNumaNuma** [Unity-Technologies/arfoundation-samples#308]
If you have multithreaded rendering ON, disabling the ARHumanBodyManager crashes the app 90% of the time. Using Unity 2019.2.0f1 and ARFoundation 3.0.0 preview 2

Steps to reproduce:

1. Open HumanSegmentationImages sample scene
2. Add a button to toggle the ARHumanBodyManager component on or off
3. Turn on Multithreaded rendering in the player settings
4. Run app on device and press your toggle button multiple times. 
5. The app crashes after ~1-10 times disabling the manager.

Possible workarounds I foud so far: (not great considering how tough segmentation is on battery / performance)
- Disable multi-threaded rendering
- Never disable the ARHumanBodyManager

Thanks

**Comment by NumaNumaNuma** [comment]
Looks like it doesn't happen anymore with the latest packages (preview 3)? 🤞🤞🤞

**Comment by tdmowrer** [comment]
Thanks for reporting. We didn't do anything specific to address this in 3.0.0-preview.3, but preview.2 was built with Xcode 11 beta and preview.3 was built with the non-beta version. I assume you've also updated your device from an iOS 13 beta to the non-beta version, so perhaps it was an issue with the beta. Please let us know if you see this again.

**Comment by NumaNumaNuma** [comment]
That might have been it :) (Haven't updated iOS though, I'm still running the beta) I thought it could have something to do with the ios/unity frame synchronisation changes that happened in preview 3.
Anyway it looks like it's fixed. 👍
