### ISSUE TITLE
Android - ARCore - Slow Image Tracking and Jittering

### ISSUE THREAD

**Issue by lbaptista95** [Unity-Technologies/arfoundation-samples#310]
Hi, I'm developing an app that is gonna be used on both platforms (iOS and Android), so I need to use AR Foundation. When I build my iOS version, everything works fine, the tracking is very fast and precise, but when I run the Android version, the tracking gets very slow, it takes like 10-20 seconds to detect an image (and the camera has to be less than 10cm away). Besides that, when the camera finally detects the image the instantiated prefab becomes unstable and does not follow the image transform correctly. 

I've tested it on all versions of AR Foundation and ARCore XR Plugin and yet the problem persists.

Does anyone know how to solve this? Or will I have to create another project using the ARCore SDK instead of ARFoundation?

**Comment by dnnkeeper** [comment]
I noticed that ARCore rendering lags behind actual movement and rotation of the camera after ARCore version 1.9 when using image tracking. But it detects my image targets pretty fast. Make sure your image targets has enough contrast features, I haven't encountered any noticable difference between ios and android detection speed.

**Comment by lbaptista95** [comment]
I used the targets that came with these samples. Now I'm using ARCore SDK and it works fine, the problem is that I'll have to create 2 separate projects, one using AR Foundation (for iOS) and the other using ARCore (for Android). 

Besides the fact that the tracking is slow, it gets a little unstable too...

**Comment by tdmowrer** [comment]
We haven't noticed this. Image detect is fast and stable. What device(s) are you testing with?

**Comment by lbaptista95** [comment]
Xiaomi Pocophone F1 and Motorola Moto G7 Plus

**Comment by Str0ss** [comment]
Hi, did you succeed with solving the lag problem? I experience this too (OnePlus 6) - the difference can be noticed with bare eye: when I don't configure the session with image DB (or even specify a DB that has no images), there is no lag. When image DB is not empty, the lag is present. Setting DB to null at runtime (after the image was found and anchor created) does not help - the lag is still present.
I didn't perform measurements, but it seems to be ~30-50 ms

**Comment by tdmowrer** [comment]
Device capabilities can vary quite a bit. Also, newer versions of ARCore do tend to improve image tracking. Is this still an issue?

**Comment by lbaptista95** [comment]
No, it isn`t. Updating ARCore solved the problem. Thanks!

Em sex., 10 de jul. de 2020 às 19:55, Tim Mowrer <notifications@github.com>
escreveu:

**Comment by tdmowrer** [comment]
Great, thanks for confirming!

**Comment by BioeJD** [comment]
Using the most current version of ARCore/ARFoundation, I continue to see these issues with image tracking on all our testing devices (a variety of well spec'ed Android devices).

It takes a considerable amount of time to track images (images that score well for expected tracking quality), the camera must be very close to the image to detect it, and tracking quickly becomes unstable as described, even after small movements.

This is in stark contrast to other solutions like Vuforia where tracking is happening virtually instantaneously with the same images from further distance, and remains tracking well even with significant movement.

I really would like to use AR Foundation/AR Core, but I cannot get acceptable image tracking performance, even with the sample content and up-to-date software.

**Comment by DominicdeGraaf** [comment]
I am also noticing very slow image detection on ARCore (when using AR Foundation). It usually takes Android 1 second to call the "added" event when I dynamically add a tracking image. Than the first updated event will take between 5-10 second... Using ARCore 4.x.x (tried them all).

**Comment by GabrielR** [comment]
Same issue in Unity 2021.2.9.  If Unity's ARCore is in the project the Android phone camera runs around 1 frame per second and freezes for five seconds every 7 or 8 seconds.  Unusable.  I tried switching to Vuforia, but it has the same issue if Unity's ARCore plugin is included.  Did anyone find a cause for this?   

Tested on Samsung s21, s20 and S8.  Two of those are top of the line phones.

**Comment by JeromevDEV** [comment]
Does someone has a solution ?
