### ISSUE TITLE
Reflection probes shift to intense blue in bright environments

### ISSUE THREAD

**Issue by NumaNumaNuma** [Unity-Technologies/arfoundation-samples#311]
When the room is really bright, the cubemaps turn blue. I've attached screenshots from the sample scene.

![IMG_8289](https://user-images.githubusercontent.com/18409362/65931342-a5b10500-e44c-11e9-981c-aafc8a13d12a.PNG)
![IMG_8288](https://user-images.githubusercontent.com/18409362/65931343-a6499b80-e44c-11e9-81f5-c4b3eeb30ee2.PNG)

![blue probes](https://user-images.githubusercontent.com/18409362/65931547-78b12200-e44d-11e9-944a-d9b7afa05fa5.gif)

Steps to reproduce:
Load up Environment Probes sample scene in a bright room.

**Comment by tdmowrer** [comment]
Thanks for reporting. This appears to be an issue with ARKit, so there's not much we can do about it in ARFoundation.

I'll close this issue, but let me know if you have additional info on this.
