### ISSUE TITLE
ARSession example to keep session between scenes

### ISSUE THREAD

**Issue by Borisss** [Unity-Technologies/arfoundation-samples#312]
Is there an example how to keep `ARSession `alive and stable between scenes?

Example, UI main menu (no AR) -> scene1 (user setups where the scene is placed, calling `MakeContentAppearAt`), all ok, -> return to menu -> scene2, let's have the same placement of this new content.

I'm struggling to make it work. It deteriorates (no matter if `ARSession` is singleton and never gets disabled) and next time (I have the world pos user chose stored) content is placed completely elsewhere. It works fine if user places level manually each time it is loaded but that is undesired (rayhit is chosen on horizontal place via `ARRaycastManager`).

Using Unity 2019.2.4f and ARFoundation 2.0.2 verified

_Btw it is a nightmare developing without `ARRemote` on iOS, have done it in 4 days for a different app year and a half ago with experimental AR support Unity had back then, struggling for over a week to recreate that with now official ARFoundation :(._

**Comment by Borisss** [comment]
furthermore this line of code in `ARSessionOrigin` is quite dangerous...
```
// Adjust the "point of interest" transform to account
// for the actual position we want the content to appear at.
contentOffsetTransform.position += transform.position - position;
```

when you want to place it differently (like user reconsiders and wants scene elsewhere, calling `MakeContentAppearAt` will offset it again because of `+=`, as there is no reset for `ARSessionOrigin`, or should we reinstantiate the prefab with origin in that case?

**Comment by tdmowrer** [comment]
You can use [DontDestroyOnLoad](https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html) to keep GameObjects alive between scene changes. The [Unity manual](https://docs.unity3d.com/Manual/MultiSceneEditing.html) also suggests:

> It is recommended to avoid using DontDestroyOnLoad to persist manager GameObjects that you want to survive across scene loads. Instead, create a manager scene that has all your managers and use SceneManager.LoadScene(<path>, LoadSceneMode.Additive) and SceneManager.UnloadScene to manage your game progress.

**Comment by Borisss** [comment]
The part with the `DontDestroyOnLoad` is was what I used, didn't work. But documentation suggests that AR session is some global construct living in the background right? So it shouldn't really matter if I connect to it using `ARSession` script on each scene load?

It works perfectly fine if it is initialized in one scene, placed in that scene and played in AR. The persistance between scenes is the only problem (so the next scene shows Unity scene data at the same place), that is why I was asking for some example code...

**Comment by tdmowrer** [comment]
> The part with the `DontDestroyOnLoad` is was what I used, didn't work. But documentation suggests that AR session is some global construct living in the background right? So it shouldn't really matter if I connect to it using `ARSession` script on each scene load?

Its lifetime is still connected to the ARSession MonoBehaviour. Disabling or destroying that MonoBehaviour will pause or destroy the session, respectively.

> It works perfectly fine if it is initialized in one scene, placed in that scene and played in AR. The persistance between scenes is the only problem (so the next scene shows Unity scene data at the same place), that is why I was asking for some example code...

I'll add it to our backlog to create a sample for this.

**Comment by Borisss** [comment]
Thanks, sample would be appreciated.

I've given it another go, setup with `DontDestroyOnLoad` but on subsequent scene using AR I get sometimes black screen (no camera input). And my scene is just attached to the AR camera (static on screen), even the trackables (dots) are static to AR camera... Looks like `TrackedPoseDriver` or `ARInputManager` binding issue.

Maybe you can just post a screenshot of the GO setup for ARSession, ARSessionOrigin and their respective components. What should stay living through scenes, Session only or Origin as well?

**Comment by tdmowrer** [comment]
In ARFoundation 4.0+, the lifecycle of the session (and all other managers) is managed by [XR Management](https://docs.unity3d.com/Packages/com.unity.xr.management@3.2/manual/index.html) and therefore is not destroyed during scene switching. There is a new [LoaderUtility](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.LoaderUtility.html) which lets you interact with the various subsystems that control the session and other subsystems.

**Comment by antont** [comment]
So what is the recommended way with ARSession in multi scene setups now?

The comment above says "the lifecycle of the session (..) is not destroyed during scene switching" but the doc for ARSession at 4.1.7 says "Enabling or disabling the ARSession will start or stop the session, respectively"

So what does this mean exactly? The session is not destroyed, but is stopped, and immediately started again? Is this the recommended way? When switching from one scene with ARSession to another where it also exists. XR Plug-in Management doc doesn't seem to say anything about ARSession.

**Comment by tdmowrer** [comment]
> The comment above says "the lifecycle of the session (..) is not destroyed during scene switching" but the doc for ARSession at 4.1.7 says "Enabling or disabling the ARSession will start or stop the session, respectively"

Those statements are referring to two different concepts: destruction and start/stop (or resume/pause in ARCore & ARKit parlance). When you enable or disable the ARSession, it will resume or pause the session, respectively, while the loader utility is used to completely tear down (destroy) the session, freeing all associated memory.

> The session is not destroyed, but is stopped, and immediately started again?

Depends what you are doing. I assume you are asking about the behavior when you have an ARSession in one scene, unload that scene, and subsequently load a different scene that also contains an ARSession. In that situation, it would pause the session when the first scene is unloaded and resume the same session when the new scene is loaded.

> Is this the recommended way?

To do what?

> XR Plug-in Management doc doesn't seem to say anything about ARSession.

The ARSession is a concept in AR Foundation, which depends on, and uses features from, XR Plug-in Management. XRM doesn't "know" anything about ARSessions.

**Comment by antont** [comment]
> Those statements are referring to two different concepts: destruction and start/stop (or resume/pause in ARCore & ARKit parlance). When you enable or disable the ARSession, it will resume or pause the session, respectively, while the loader utility is used to completely tear down (destroy) the session, freeing all associated memory.

Right-o. I eventually figured so based on the docs too, but due to unfamiliarity about the whole was not completely sure.

> Depends what you are doing. I assume you are asking about the behavior when you have an ARSession in one scene, unload that scene, and subsequently load a different scene that also contains an ARSession. In that situation, it would pause the session when the first scene is unloaded and resume the same session when the new scene is loaded.

Exactly. Sorry for not being explicit about the use case, it is the same as in the first post in this issue though.

That's what we did yesterday and it all has worked well in tests. Am very grateful for your clarifications and elaboration, is easy to trust it now that know what's going on exactly. Thanks!

I find it's quite convenient to not need a loader / AR session scene or so, especially as our case was such that a different company had already made the game with multiple scenes that they load one at a time, and we added AR to it in a later step. This architecture with the underlying XRM and the ARSession object on top seems perfect.
