### ISSUE TITLE
BuildFailedException for AR Foundation

### ISSUE THREAD

**Issue by sergiosolorzano** [Unity-Technologies/arfoundation-samples#313]
Can't build, building error as shown below. 

LibUtil needs amending and then it builds fine. But this needs to be done each time Unity is opened fresh. Tested on Unity 2019.2 and 2019.3

Discussion and proposed solution by JeromeHinds in Unity forum https://forum.unity.com/threads/buildfailedexception-for-ar-foundation-in-2019-2.737366/#post-5026157

BuildFailedException: Could not determine which version of Xcode was selected in the Build Settings. Xcode app was computed as .
UnityEditor.XR.ARKit.LibUtil.SelectPlugin (UnityEditor.PluginImporter libXcode10, UnityEditor.PluginImporter libXcode11) (at Library/PackageCache/com.unity.xr.arkit@3.0.0-preview.2/Editor/LibUtil.cs:19)
UnityEditor.XR.ARKit.ARKitBuildProcessor+Preprocessor.SelectStaticLib () (at Library/PackageCache/com.unity.xr.arkit@3.0.0-preview.2/Editor/ARKitBuildProcessor.cs:93)
UnityEditor.XR.ARKit.ARKitBuildProcessor+Preprocessor.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.arkit@3.0.0-preview.2/Editor/ARKitBuildProcessor.cs:106)
UnityEditor.Build.BuildPipelineInterfaces+<OnBuildPreProcess>c__AnonStorey0.<>m__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:376)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

BuildFailedException: Could not determine which version of Xcode was selected in the Build Settings. Xcode app was computed as .
UnityEditor.XR.ARKit.LibUtil.SelectPlugin (UnityEditor.PluginImporter libXcode10, UnityEditor.PluginImporter libXcode11) (at Library/PackageCache/com.unity.xr.arkit@3.0.0-preview.2/Editor/LibUtil.cs:19)
UnityEditor.XR.ARKit.BuildProcessor.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.arkit-face-tracking@3.0.0-preview.2/Editor/BuildProcessor.cs:15)
UnityEditor.Build.BuildPipelineInterfaces+<OnBuildPreProcess>c__AnonStorey0.<>m__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:376)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by tdmowrer** [comment]
I assume you're building on a machine that does not have Xcode installed, e.g., a PC. This will be fixed in the next release. However, we still have to choose between Xcode 10 & 11, so on non-macOS platforms, it will choose Xcode 11. Does that work for you?

**Comment by sergiosolorzano** [comment]
Thanks you @tdmowrer  In my case I've been building with xcode 10.3 and worked fine, now building with 11.1 and also works fine :)

**Comment by tdmowrer** [comment]
Fixed in 3.0.0-preview.4
