### ISSUE TITLE
Don't work ARFoundation Eyes Tracking on IOS

### ISSUE THREAD

**Issue by DmitriiLiakin** [Unity-Technologies/arfoundation-samples#314]
ARFace.leftEye and ARFace.rightEye do not work properly (doesn't bound to the face (eyes) of a user when using front camera and move the device) when using ARFoundation Eyes Tracking on iOS
Demo scenes: EyeLasers, EyePoses, FixationPoint

Iphone XS
IOS 13
Xcode 11
Unity 2019.2.2f1

https://user-images.githubusercontent.com/18499350/66134211-a25e7a80-e600-11e9-85c5-c09ec346ebd5.PNG
https://user-images.githubusercontent.com/18499350/66134212-a25e7a80-e600-11e9-8754-1f7b31c31004.PNG
https://user-images.githubusercontent.com/18499350/66134213-a25e7a80-e600-11e9-8af6-92ea8eef3012.PNG
https://user-images.githubusercontent.com/18499350/66134214-a2f71100-e600-11e9-9aa8-8b3f117f2231.PNG

**Comment by sveekey** [comment]
Hello! Same bug happens. Any update on this? Thank you!

**Comment by tdmowrer** [comment]
Fixed in 3.0.0-preview.4
