### ISSUE TITLE
Image tracking Instantiated prefab Rotation Issue

### ISSUE THREAD

**Issue by MrRobat0** [Unity-Technologies/arfoundation-samples#315]
There seems to be an issue with the rotation of any instantiated object upon recognizing the marker, even if I try to change the rotation via script I get weird values. In my case, I'm trying to overlay an image in front of the recognized one and every time I build the app the prefab image is horizontal to the tracked image.

This has both happened on ARcore and Arkit, so android pixel 3 and iPhone 8.

I've tried with the latest ar foundation version 3.0 preview 3 as well as 2.2.0 preview 3
in both unity versions 2019.1 and 2019.2
I'm also working on mac.

Thanks
![71340749_907468916302675_7646509523233931264_n](https://user-images.githubusercontent.com/55761696/66172358-6b5d8880-e643-11e9-8f87-9e4590704815.png)

**Comment by tdmowrer** [comment]
Have you built your own app, or are you using the image tracking sample in this repo? The sample does exactly as you describe (overlay the original image on top of the detected one) and works without issue on Pixel and various iOS devices.

**Comment by MrRobat0** [comment]
@tdmowrer I've retested everything again using unity 2019.2.3 and ARfoundation 3.0 and what I've found is that the prefab needs to be a child of an empty parent object with default transform. Otherwise, the rotation of the object gets changed when tracked. The child prefab image always needs to horizontal. If using a plane and material the plane needs to be rotated 180 on the y-axis. 
If using a sprite it needs to be rotated 90 on the x-axis.

Keep in mind always make your prefab a child of an empty Game Object with default transform.

<img width="1664" alt="Screenshot 2019-10-07 at 22 15 08" src="https://user-images.githubusercontent.com/55761696/66351631-dbc31d00-e955-11e9-9a52-e2b1689d3800.png">

using a plane.

<img width="1654" alt="Screenshot 2019-10-07 at 22 58 33" src="https://user-images.githubusercontent.com/55761696/66351715-0614da80-e956-11e9-979a-26b1c450008f.png">

using a sprite.

**Comment by tdmowrer** [comment]
Like all trackables, the ARTrackedImage's transform is set according to the image detected in the real world, so if you need a particular orientation, you would have to nest those objects under your main prefab GameObject. This is what we do in the [ImageInfoPrefab](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/ImageTracking/ImageInfoPrefab.prefab).

**Comment by tdmowrer** [comment]
> @tdmowrer Excuse me, but can I achieve the tracked image prefab to stay at (0,0,0) in unity world when according to that prefab's target image was found?

The purpose of the ARTrackedImageComponent is to provide you with information about the tracked image, including its position and orientation.

If your intention is to instantiate a GameObject at the origin in response to a image being detected, you should subscribe to [`ARTrackedImageManager.trackedImagesChanged`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged) and perform your logic there (you get a list of `added` tracked images).

**Comment by KamikyIT** [comment]
@tdmowrer 
Yes, I've subscribed on changing ARTrackedImageManager.trackedImagesChanged.
In my project on 1st image was found(I'm looking only for one image), I'm calling this code once:

```
var babyGo = GameObject.FindObjectOfType<ARTrackedImage>();
var arOrig = GameObject.FindObjectOfType<ARSessionOrigin>();

arOrig.transform.Translate(-babyGo.transform.position, Space.World);

float babyAngle;
Vector3 babyAxis;
babyGo.transform.rotation.ToAngleAxis(out babyAngle, out babyAxis);

arOrig.transform.RotateAround(Vector3.zero, babyAxis, -babyAngle);
```

With this code It's working, but ARSessionOrigin rewrites coordinates on Update.
As a result I want the image created prefab to become in the Unity space coordinates middle(Vector3.zero) with Quaternion.identity. 

I've also tried 
`arOrig.MakeContentAppearAt(babyGo.transform, Vector3.zero, Quaternion.identity);`
but it didnt work as I want.

Help me, please.

**Comment by tdmowrer** [comment]
If you want your GameObject to be at (0,0,0), then instantiate it at (0,0,0). You don't need to use a prefab, and it doesn't need to be a child of the session origin.

**Comment by Newfu** [comment]
Hi! I have been following this issue for a few weeks now, and I followed the different tips gave by @tdmowrer (thanks!), unfortunately I still have a problem with the rotation of my instantiated prefab on `Image tracking`. 

I have a prefab named `GeneratorHandler` spawned by the ARTrackedImageManager.
This prefab contains another one named `Generator` (this one is just instantiating a grid of GameObjects with each a rotation set to `Quaternion.identity`).

Every time I launch my app and the image is recognized, my grid is generated but always with a wrong, and often different, rotation (example attached).
Both prefabs `GeneratorHandler` and `Generator` have a basic rotation set to `0,0,0`. I even tried to set it by hand like `transform.rotation = trackedImage.transform.rotation` but it's not fixing it...

Am I missing something or is there a problem?

Thanks for you help.

![grid_rotation](https://user-images.githubusercontent.com/8082128/68490207-ddc81680-0248-11ea-864c-371785c5d5c6.png)

**Comment by sergiosolorzano** [comment]
I also found the same issue, ARF 3.1.0 prev.1, it seemed with a larger tracking image it was more stable else it'd rotate

**Comment by MalteJosten** [comment]
@Newfu I have the same problem and I think it has something to do with the World Space orientation / coordinate system. Whenever you start your app, the coordinate system is initialised according to your device's orientation (I believe). If you now instantiate your grid-like object, its rotation depends on the world space's orientation. Every time you start your app while holding your device in another direction, the world space orientation is different, hence your grid's rotation/orientation is different too.
Didn't find a way to fix it though...

**Comment by ZivMahluf** [comment]
> 
> 
> @Newfu I have the same problem and I think it has something to do with the World Space orientation / coordinate system. Whenever you start your app, the coordinate system is initialised according to your device's orientation (I believe). If you now instantiate your grid-like object, its rotation depends on the world space's orientation. Every time you start your app while holding your device in another direction, the world space orientation is different, hence your grid's rotation/orientation is different too.
> Didn't find a way to fix it though...

@MalteJosten Did you find a way to fix it by now? I'm having the exact same issue

**Comment by MalteJosten** [comment]
@ZivMahluf I'm using `MakeContentAppearAt()` to place my object. It moves the environment origin to the marker origin and applies its rotation too. To understand its parameters etc. I would recommend to take a look at the documentation which you'll find [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARSessionOrigin.html).

**Comment by ZivMahluf** [comment]
> 
> 
> @ZivMahluf I'm using `MakeContentAppearAt()` to place my object. It moves the environment origin to the marker position and applies its rotation too. To understand its parameters etc. I would recommend to take a look at the documentation which you'll find [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARSessionOrigin.html).

Works like a charm. Thank you!

**Comment by luca1107** [comment]
> @ZivMahluf I'm using `MakeContentAppearAt()` to place my object. It moves the environment origin to the marker position and applies its rotation too. To understand its parameters etc. I would recommend to take a look at the documentation which you'll find [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARSessionOrigin.html).

Can you tell me more about your solution, having the same problem with wrong world orientation because of different rotation of the phone at the start of the Ar Scene

**Comment by ZivMahluf** [comment]
> 



> > @ZivMahluf I'm using `MakeContentAppearAt()` to place my object. It moves the environment origin to the marker position and applies its rotation too. To understand its parameters etc. I would recommend to take a look at the documentation which you'll find [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARSessionOrigin.html).
> 
> Can you tell me more about your solution, having the same problem with wrong world orientation because of different rotation of the phone at the start of the Ar Scene

Hey @luca1107, I didn't find a perfect solution so I manipulated the physical world a bit for the solution.
I had a QR code in the physical world and I needed to replace it with an image.
After recognizing the QR has been tracked I waited for another 2 seconds (to make sure the camera is actually pointing at the code, and facing it) and then I used `camera.transform.forward` to get the direction the camera is facing + `MakeContentAppearAt` to show the image.
I no longer have access to that code so can't paste it here
