### ISSUE TITLE
Image Tracking with dynamic add reference image at runtime

### ISSUE THREAD

**Issue by Davidwang007** [Unity-Technologies/arfoundation-samples#319]
Unity 2019.3.06b or Unity 2019.3.03b
ARFoundation 3.0.0.preview3 or preview 1
when 
[log.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/3705769/log.txt)
use these code :
------------------------------------
    private void Awake()
    {
        mARTrackedImageManager = gameObject.AddComponent<ARTrackedImageManager>();
        if (mARTrackedImageManager.descriptor.supportsMutableLibrary)
        {
            MutableRuntimeReferenceImageLibrary myRuntimeReferenceImageLibrary =
                mARTrackedImageManager.CreateRuntimeLibrary() as MutableRuntimeReferenceImageLibrary;
            var texture = Resources.Load("Spider") as Texture2D;
            Debug.Log("Texture Name:"+ texture.name);
            Unity.Jobs.JobHandle jobHandle = myRuntimeReferenceImageLibrary.ScheduleAddImageJob(texture, "Spider", 0.2f);
            jobHandle.Complete();

            if (myRuntimeReferenceImageLibrary != null)
            {
               Debug.Log("myRuntimeReferenceImageLibrary: " + myRuntimeReferenceImageLibrary.count);
               Debug.Log("supportedTextureFormatCount: " + myRuntimeReferenceImageLibrary.supportedTextureFormatCount);

                mARTrackedImageManager.referenceLibrary = myRuntimeReferenceImageLibrary;
            }
            mARTrackedImageManager.maxNumberOfMovingImages = 1;
            mARTrackedImageManager.trackedImagePrefab = mTrackedImagePrefab;
            mARTrackedImageManager.enabled = true;
        }
    }
---------------------------
then got a Error in runtime:
Unable to find _burst_generated

what wrong with it ?

**Comment by Davidwang007** [comment]
I got it ,this need to install the Burst package. Thanks

**Comment by bhosaleT** [comment]
@Davidwang007  Did that fix it?

**Comment by tdmowrer** [comment]
ARFoundation does not require burst. The message you see in logcat is not an error and can be ignored.

**Comment by rremigius** [comment]
More important information from the log.txt is this:

```
10-09 13:52:31.528: I/Unity(15099): myRuntimeReferenceImageLibrary: 0 
```

Even if ARFoundation doesn't require burst, it's not loading the reference image.
I have a similar setup (based on the [documentation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/tracked-image-manager.html#adding-new-reference-images-at-runtime)) and also I cannot get the reference image to load. The count stays at 0 and it will not detect the image.

@Davidwang007 Installing the Burst package indeed removes the error from the log, but does not fix the issue of the reference image not being loaded.

@tdmowrer Since it's not because of the Burst package, do you know why the image is not loaded?

**Comment by tdmowrer** [comment]
I do not. Is there any other logcat output? You might try filtering on the tags `native` (for ARCore) and `Unity-ARCore` (for the ARCore XR Plugin package).

**Comment by laurenta35** [comment]
I'm also facing the same issue and I'm very interested to know how to solve this issue.
Here is the logcat capture

[log.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/4388099/log.txt)

**Comment by tdmowrer** [comment]
It looks like you are creating an image before ARCore is initialized:

```
Entering ArSession_createWithFeatures
```

Happens after you've added the image. You can use the [ARSession.stateChanged](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARSession.html#UnityEngine_XR_ARFoundation_ARSession_stateChanged) event to determine when ARCore is ready to use.

**Comment by laurenta35** [comment]
Thanks a lot! This was the reason of my problem. Now I create the dynamic library only when the _ARSession.stateChanged_ event is equal to _ARSessionState.SessionInitializing_ and it works perfectly!

**Comment by Bakalino** [comment]
Are the added images also persistent in the imagelibrary? By that i mean when i restart the app again do i need to add all images again or are they already in the image library?

**Comment by tdmowrer** [comment]
They are not persistent, no.

**Comment by veartDesigns** [comment]
I'm working with Unity 2019.3.13f1 and with ARFoundation 4.0.0 and It's not working properly when I'm changing the reference image library at runtime.
I have a List with 4 XRReferenceImageLibrarys (created previously with the editor) and I'm assigning to the ARTrackedImageManager.referenceLibrary independently. 
The problem here is that the tracking only recognizes the first library image assigned, and even if I change it to other library, it recognizes the first old library images but shows the new library image over. It seems like it's getting the old image index and getting the image from the new library. 
I tried to add ARTrackedImageManager at runtime and assign then the library...but it's the same. 
Any idea? thanks.

**Comment by veartDesigns** [comment]
> I'm working with Unity 2019.3.13f1 and with ARFoundation 4.0.0 and It's not working properly when I'm changing the reference image library at runtime.
> I have a List with 4 XRReferenceImageLibrarys (created previously with the editor) and I'm assigning to the ARTrackedImageManager.referenceLibrary independently.
> The problem here is that the tracking only recognizes the first library image assigned, and even if I change it to other library, it recognizes the first old library images but shows the new library image over. It seems like it's getting the old image index and getting the image from the new library.
> I tried to add ARTrackedImageManager at runtime and assign then the library...but it's the same.
> Any idea? thanks.

Solved. 
I had duplicate the reference image libraries files from the same one..and that was creating a problem. Creating from zero each, works. 
But there is another problem, not related to the reference image libraries, 
is the untracking not working? when something is tracked, the plane appears, but never more disappears.

**Comment by rajshirolkar** [comment]
I'm facing the same issue. The ScheduleAddImageJob() completes but the reference library count remains 0. Reading this I even  checked the ARSession state and the state is "ready" before I add the image.


`
2020-10-17 17:04:56.211 2012-2210/? I/Unity: before loading texture 
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.212 2012-2210/? I/Unity: texture2d populated from resources
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.219 2012-2210/? I/Unity: newtex created with rgba32 format
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.270 2012-2210/? I/Unity: setpixels from previous texture2d
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.271 2012-2210/? I/Unity: image loaded 
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.271 2012-2210/? I/Unity: before Job reference library count : 0
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.272 2012-2210/? I/Unity: arsession state : Ready 
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.289 2012-2210/? E/Unity: Unable to find _burst_generated
2020-10-17 17:04:56.295 2012-2210/? I/Unity: Job Running... 
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.360 2012-2210/? I/chatty: uid=10525 UnityMain identical 4606 lines
2020-10-17 17:04:56.360 2012-2210/? I/Unity: Job Running... 
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.360 2012-2210/? I/Unity: Job Completed reference library count : 0
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-10-17 17:04:56.361 2012-2210/? I/Unity: TextureFormat.RGBA32 supported: True
     
`

**Comment by Unity3D-Hardik** [comment]
Can we switch Multiple MutableRuntimeReferenceImageLibrary  ? I have tried but after switching eventArgs.updated not working.
