### ISSUE TITLE
Teleport In ArFoundation

### ISSUE THREAD

**Issue by KhanhNguyen1995** [Unity-Technologies/arfoundation-samples#320]
Dear UNITY experts! I am currently doing an AR related thesis in architecture, using Example "Scale" in AR Foundation to display objects. How can I move upstairs, after the model appears in the plane (because the architecture model has many floors)? (This function is similar to teleport in VR). I have struggled with it for the past 3 weeks but failed. Looking forward to the advice of the experts. Sincere thanks!

**Comment by tdmowrer** [comment]
The easiest thing to do after placing your model on the plane would be to simply translate the `ARSessionOrigin` up, that is, increase its Y value by the distance between the floors.

**Comment by KhanhNguyen1995** [comment]
Dear @tdmowrer!
Thanks for your prompt feedback. Thanks to your guidance, my friend and I wrote the code to function up the floor. But when this code is put into some ARSessionOrigin, it doesn't work with the MakeAppearOnPlane.cs code. The model appeared but could not reach the upper floor. Can you comment on the code I attached? Thank you very much!
I use Unity 2019.2.07; ArFoundation 2.1.0; Arcore 2.1.
(https://gist.github.com/KhanhNguyen1995/2be9dda0424eb9baa27f1091edd34545)
![CodeUpstair](https://user-images.githubusercontent.com/55489175/66625346-1f4fac80-ec1e-11e9-97b4-5050f292fdfd.JPG)

**Comment by mdurand42** [comment]
You might be able to get some assistance with this question from other Unity users on the forums. https://forum.unity.com/forums/handheld-ar.159/
