### ISSUE TITLE
Does not work with GVR

### ISSUE THREAD

**Issue by amir989** [Unity-Technologies/arfoundation-samples#322]
ARFoundation doesnt work with Google VR on IOS and Android. but if i download ARCore from google, then it works in Android phones. 

tried on Unity 2019.2.x  and 2019.3.x
 galaxy S9 and Iphone XS max

**Comment by tdmowrer** [comment]
Google VR is not supported by ARFoundation, nor are any of the ARCore features for iOS.

**Comment by amir989** [comment]
Thanks for fast answer! before ARKit combined with ARFoundation, we were able to use ARKit and GVR together on IOS for inside out tracking while using GVR. The coming Google pixle 4 screen has 90Hz screen refresh which is perfect for phone VR (there are roomers for next iphone as well). Is there any plan to let us to do position tracking while using GVR in upcoming ARFoundation?!

**Comment by tdmowrer** [comment]
No plans at the moment, no. I'll add a feature request, though.
