### ISSUE TITLE
iOS: black background with fresh install and up to date system and packages

### ISSUE THREAD

**Issue by OlivierHoel** [Unity-Technologies/arfoundation-samples#323]
Hi !
I've just had a fresh setup for everything:
- macOS catalina
- iOS 13.1.2
- XCode 11.1
- Unity 2019.2.8

I've created a new LWRP project with:
- LWRP 6.9.1
- AR Foundation 3.0.0 p3
- AR Kit Plugin 3.0.0 p3

Then created a simple scene with sample models, AR session and AR session origin created using  Create menu. Build, deploy, ... camera feed is not rendered and I get a black background :( (whereas pose tracking seems to work ok). What am I missing ? Do I have to setup a custom renderer for the camera background?
The only other parameters I've changed are in the player settings:
- API => .NET 4.x
- min iOS version: 11.0
- Architecture: ARM64

Also downloaded and tried some AR foundation samples from scratch, same issue...

**Comment by tdmowrer** [comment]
Your package/iOS/Xcode/Unity versions sound okay. Have you seen the [step-by-step instructions](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html)?

**Comment by OlivierHoel** [comment]
Oh...
I naively thought that section is when you already have a custom SRP in your app. Sorry my bad.
It works alright now, thanks!
