### ISSUE TITLE
Can't launch ARCollaborationData iOS

### ISSUE THREAD

**Issue by AytoMaximo** [Unity-Technologies/arfoundation-samples#325]
Hello!
My config:
Unity 2019.2.9f1
Xcode beta 11.0
iPhone XR iOS 13.1.2

When I try to launch the app with ARCollaborationData scene I get tons of errors and my iphone screen colored in magenta color. 

Logs from console (the last error loops for infinity):
2019-10-13 21:09:27.849400+0300 samples[2638:775236] Built from '2019.2/staging' branch, Version '2019.2.9f1 (ebce4d76e6e8)', Build type 'Development', Scripting Backend 'il2cpp'
2019-10-13 21:09:27.864111+0300 samples[2638:775236] -> registered mono modules 0x1029512b0
-> applicationDidFinishLaunching()
PlayerConnection initialized from /private/var/containers/Bundle/Application/A66B147C-4AF7-462D-A89B-97ECFF637890/samples.app/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55000
Multi-casting "[IP] 100.88.57.202 [Port] 55000 [Flags] 3 [Guid] 751530509 [EditorId] 1618597891 [Version] 1048832 [Id] iPhonePlayer(iPhone):56000 [Debug] 1 [PackageName] iPhonePlayer" to [225.0.0.222:54997]...
Waiting for connection from host on [0.0.0.0:55000]...
Remaining time:8s
Remaining time:7s
Remaining time:6s
Remaining time:5s
Remaining time:4s
Remaining time:3s
Remaining time:2s
Remaining time:1s
Remaining time:0s
Timed out. Continuing without host connection.
Started listening to [0.0.0.0:55000]
Starting managed debugger on port 56000
PlayerConnection already initialized - listening to [0.0.0.0:55000]
2019-10-13 21:09:39.128084+0300 samples[2638:775236] Metal GPU Frame Capture Enabled
-> applicationDidBecomeActive()
[XR] Discovering subsystems at path /private/var/containers/Bundle/Application/A66B147C-4AF7-462D-A89B-97ECFF637890/samples.app/Data/UnitySubsystems
[XR] No descriptors matched for examples in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] 1 'inputs' descriptors matched in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json
[XR] No descriptors matched for cameras in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for displays in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for depths in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for meshings in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for planes in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for raycasts in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for referencePoints in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for sessions in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for experience in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[XR] No descriptors matched for gestures in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
Initializing Metal device caps: Apple A12 GPU
Initialize engine version: 2019.2.9f1 (ebce4d76e6e8)
WARNING: Shader Unsupported: 'Unlit/ARKitBackground' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Unlit/ARKitBackground' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/Internal-GUITexture' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-GUITexture' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-GUITexture' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/Internal-GUITextureClip' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-GUITextureClip' - Pass '' has no fragment shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/Internal-GUITextureClip' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/Internal-GUIRoundedRect' - Pass '' has no fragment shader
Failed to find expected binary shader data in 'Standard'.

(Filename: ./Runtime/Shaders/SerializedShader.cpp Line: 595)

Failed to find expected binary shader data in 'Standard'.

(Filename: ./Runtime/Shaders/SerializedShader.cpp Line: 595)

WARNING: Shader Unsupported: 'Standard' - Pass 'FORWARD' has no fragment shader
UnloadTime: 0.242958 ms
InvalidOperationException: The
 
ARKitParticipantSubsystem provider has not been created.
at UnityEngine.XR.ARKit.ARKitParticipantSubsystem+ARKitProvider.Start () [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARSubsystems.XRParticipantSubsystem.OnStart () [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARSubsystems.XRSubsystem`1[TSubsystemDescriptor].Start () [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARFoundation.SubsystemLifecycleManager`2[TSubsystem,TSubsystemDescriptor].OnEnable () [0x00000] in <00000000000000000000000000000000>:0

(Filename: currently not available on il2cpp Line: -1)

[XR] Loading plugin UnityARKit for subsystem ARKit-Input...
[XR] UnityARKit successfully registered Provider for ARKit-Input
InvalidOperationException: The ARKitParticipantSubsystem provider has not been created.
at UnityEngine.XR.ARKit.ARKitParticipantSubsystem+ARKitProvider.GetChanges (UnityEngine.XR.ARSubsystems.XRParticipant defaultParticipant, Unity.Collections.Allocator allocator) [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARSubsystems.XRParticipantSubsystem.GetChanges (Unity.Collections.Allocator allocator) [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARFoundation.ARTrackableManager`4[TSubsystem,TSubsystemDescriptor,TSessionRelativeData,TTrackable].Update () [0x00000] in <00000000000000000000000000000000>:0

(Filename: currently not available on il2cpp Line: -1)

2019-10-13 21:09:40.487344+0300 samples[2638:775236] Compiler failed to build request
Metal: Error creating pipeline state (Skybox/Procedural): output of type half4 is not compatible with a MTLPixelFormatInvalid color attachement.
(null)2019-10-13 21:09:50.254386+0300 samples[2638:775475] XPC connection interrupted
Setting up 1 worker threads for Enlighten.
Thread -> id: 171803000 -> priority: 1
2019-10-13 21:09:50.576999+0300 samples[2638:775236] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-10-13 21:09:50.586385+0300 samples[2638:775236] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-10-13 21:10:00.618887+0300 samples[2638:775236] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-10-13 21:10:00.619051+0300 samples[2638:775236] MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 3 try
Metal: Error creating pipeline state (UI/Default): Compiler encountered an internal error
(null)2019-10-13 21:10:00.634243+0300 samples[2638:775236] [Common] _BSMachError: port 10a03; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-10-13 21:10:00.635820+0300 samples[2638:775236] [Common] _BSMachError: port 10a03; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-10-13 21:10:00.638750+0300 samples[2638:775236] [Common] _BSMachError: port 14d03; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-10-13 21:10:00.640405+0300 samples[2638:775236] Unbalanced calls to begin/end appearance transitions for <SplashScreenController: 0x129da6d40>.
Failed to find expected binary shader data in 'Hidden/Internal-MotionVectors'.

(Filename: ./Runtime/Shaders/SerializedShader.cpp Line: 595)

Failed to find expected binary shader data in 'Hidden/Internal-MotionVectors'.

(Filename: ./Runtime/Shaders/SerializedShader.cpp Line: 595)

WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Setting to default shader.
InvalidOperationException: The ARKitParticipantSubsystem provider has not been created.
at UnityEngine.XR.ARKit.ARKitParticipantSubsystem+ARKitProvider.GetChanges (UnityEngine.XR.ARSubsystems.XRParticipant defaultParticipant, Unity.Collections.Allocator allocator) [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARSubsystems.XRParticipantSubsystem.GetChanges (Unity.Collections.Allocator allocator) [0x00000] in <00000000000000000000000000000000>:0
at
 
UnityEngine.XR.ARFoundation.ARTrackableManager`4[TSubsystem,TSubsystemDescriptor,TSessionRelativeData,TTrackable].Update () [0x00000] in <00000000000000000000000000000000>:0

(Filename: currently not available on il2cpp Line: -1)

InvalidOperationException: The ARKitParticipantSubsystem provider has not been created.
at UnityEngine.XR.ARKit.ARKitParticipantSubsystem+ARKitProvider.GetChanges (UnityEngine.XR.ARSubsystems.XRParticipant defaultParticipant, Unity.Collections.Allocator allocator) [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARSubsystems.XRParticipantSubsystem.GetChanges (Unity.Collections.Allocator allocator) [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARFoundation.ARTrackableManager`4[TSubsystem,TSubsystemDescriptor,TSessionRelativeData,TTrackable].Update () [0x00000] in <00000000000000000000000000000000>:0

**Comment by tdmowrer** [comment]
We aren't aware of any issues with this sample. However, you mentioned using the Xcode 11 beta. Could you try updating to a released (non-beta) version of Xcode 11?

**Comment by AytoMaximo** [comment]
> We aren't aware of any issues with this sample. However, you mentioned using the Xcode 11 beta. Could you try updating to a released (non-beta) version of Xcode 11?

I’ve managed to solve this issue with Unity 2019.2.2 version (the same of yours). Also, I found the same issue on Unity forum about .7-9 versions (shader compilation errors while Unity project build). I had these errors in Editor too, but suddenly it’s gone, but Xcode build was still “corrupted”. 
The link: https://forum.unity.com/threads/unknown-shader-compiler-error-using-unity-2019-2-8f1-when-building-ios.758339/

Xcode beta 11.0 and 11.2 work fine :)

**Comment by ovkhan** [comment]
Been searching since yesterday, and i have exactly the same problem (but with Unity 2019.2.7f2, XCode 11.1 and IOS 13.1.2.
Like you, when i import project, and build it, i have lots of error the first time (related to shader, same as screenshot on link you posted), second time i have like 2-3 errors, and third time i can build the app, but got a pink screen when testing it on my iphone.

**Comment by AytoMaximo** [comment]
> Like you, when i import project, and build it, i have lots of error the first time (related to shader, same as screenshot on link you posted), second time i have like 2-3 errors, and third time i can build the app, but got a pink screen when testing it on my iphone.

Exactly the same!

**Comment by tdmowrer** [comment]
I'm currently using Unity 2019.2.7f2 and Xcode 11.1 (11A1027). I've tried two devices, one running iOS 13.1 and the other running iOS 13.2 beta. I haven't seen the issues described here.

Out of interest, what version of macOS are folks using?

**Comment by AytoMaximo** [comment]
> Out of interest, what version of macOS are folks using?

As it’s mentioned in forum thread above - it’s Catalina fault :(

**Comment by josefgrunig** [comment]
Same issue here with macOS Catalina 10.15, Xcode 11.1, Unity 2019.2.6f1
As mentioned above a workaround is to downgrade to Unity 2019.2.2f1

**Comment by tdmowrer** [comment]
Here is the public issue tracker for this issue: https://issuetracker.unity3d.com/issues/ios

Closing this issue as it is a general problem with Unity on macOS Catalina and not AR specific.

**Comment by CorpusCallosum** [comment]
Hi, I'm still having this issue today on Unity v2020.1 when trying to build to Android. 


sent Today at 5:51 PM
BuildFailedException: Cannot find shader 'Unlit/ARKitBackground'
UnityEditor.XR.ARSubsystems.BuildHelper.FindShaderOrFailBuild (System.String shaderName) (at Library/PackageCache/com.unity.xr.arsubsystems@4.1.1/Editor/BuildHelper.cs:83)
UnityEditor.XR.ARSubsystems.BuildHelper.RemoveShaderFromProject (System.String shaderName) (at Library/PackageCache/com.unity.xr.arsubsystems@4.1.1/Editor/BuildHelper.cs:56)
UnityEditor.XR.ARKit.NoniOSBuildProcessor.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.arkit@4.1.1/Editor/NoniOSBuildProcessor.cs:18)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass15_0.<OnBuildPreProcess>b__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:411)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:391)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

**Comment by tdmowrer** [comment]
This issue was about an ARKit-specific feature (collaboration) which is considered closed. Your question is about an Android build issue. Could you please create a new issue for this?
