### ISSUE TITLE
Can't launch SimpleAR sample on iOS

### ISSUE THREAD

**Issue by nickmeinhold** [Unity-Technologies/arfoundation-samples#327]
Hello, thanks for taking a look! 

The app either crashes on launch, or doesn't crash but the screen just stays black.

Unity 2019.2.9f1
Xcode 11.1
iPhone6sPlus iOS 13.1.2

console: 
https://pastebin.com/GMhZMXjN

stacktrace:  
https://pastebin.com/GpvfLX3s

**Comment by ovkhan** [comment]
Hello,

Same problem, but with iPhone X and Unity 2019.2.7f2.

**Comment by tdmowrer** [comment]
Works for me with an iPhone X and iPad Pro using Unity 2019.2.f1, Xcode 11.1, and iOS 13.1 and 13.2 beta.

What version of macOS are you using?

**Comment by nickmeinhold** [comment]
I'm on Catalina 10.15. Do you think that's the problem?

**Comment by tdmowrer** [comment]
> I'm on Catalina 10.15. Do you think that's the problem?

According to [this forum post](https://forum.unity.com/threads/unknown-shader-compiler-error-using-unity-2019-2-8f1-when-building-ios.758339/), it seems to be an issue with Unity on macOS Catalina in general, not ARFoundation specifically.

**Comment by nickmeinhold** [comment]
Thanks so much!  That was the problem - as they said in the forum you linked to, I downloaded the beta (2019.3.0b7) and it works!

**Comment by tdmowrer** [comment]
Here is the public issue tracker for this issue: https://issuetracker.unity3d.com/issues/ios

Closing this issue as it is a general problem with Unity on macOS Catalina and not AR specific.
