### ISSUE TITLE
Tracked Image to Prefab transformations ratio

### ISSUE THREAD

**Issue by thePostFuturist** [Unity-Technologies/arfoundation-samples#328]
Hello,

How do I transform the prefab assigned to a tracked image in the Editor?

P.e. I have a reference image IRL that's 0.5m. I'd like to position a model on a correct way. How would I go around doing this? 

Thanks for reading.

**Comment by tdmowrer** [comment]
This sounds like what the [image tracking sample](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/ImageTracking/ImageTracking.unity) does.

That sample also [changes the scale of the prefab](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/ImageTracking/TrackedImageInfoManager.cs#L85) to match the extents of the detected image. Is that what you're asking?

**Comment by thePostFuturist** [comment]
Very much appreciate the response, but is there a way I can do this
visually? I need to match the exact placement and rotation.

For example in Vuforia's image targets you can place a GO directly on an
image and transform it.

Thanks for your help.

**Comment by thePostFuturist** [comment]
I wrote my own tool to do this on the device ( simple transforms and print values ), but doing this visually is a missing core feature.

**Comment by Avatarchik** [comment]
> I wrote my own tool to do this on the device ( simple transforms and print values ), but doing this visually is a missing core feature.
Hi! Can you share your best practices? I would also like a scaling mechanism like in Vuforia
