### ISSUE TITLE
Can't build for Android - Missing UnityARCore\classes.jar file

### ISSUE THREAD

**Issue by MohammedAlsayedOmar** [Unity-Technologies/arfoundation-samples#33]
I am using Unity 2018.2.3f1
Updated my Android SDK (SDK Manager) to the latest version
Cloned the repo and Opened the project from Unity Hub
Build Settings -> Build
The first image is some warning I get when I opened. I am not sure how can I help the editor and do it manually. (Not sure if it's related so I mentioned it)

![image](https://user-images.githubusercontent.com/26679355/44076300-f8a3c5ec-9f9f-11e8-8848-d4e01ffce375.png)

In the second image, is the actual build error that appears. I am not sure where to download this missing file and where will be the destination to put the file in. 
![image](https://user-images.githubusercontent.com/26679355/44076401-650df16c-9fa0-11e8-9a26-1fd86dc23ea2.png)

If you need any more details, let me know.
Thanks

**Comment by tdmowrer** [comment]
The ARCore XR Plugin requires the Gradle build system. You'll get an error message like this one otherwise.

**Comment by MohammedAlsayedOmar** [comment]
Thanks for your time. It worked!

**Comment by tdmowrer** [comment]
Great! This will fail more gracefully in the next version with an error message telling indicating that you need to use Gradle.

**Comment by flankechen** [comment]
I have the same issue but changing to gradle build takes forever, and not responding for few hours

**Comment by tdmowrer** [comment]
@flankechen That sounds like an issue with Unity's Gradle build system. Could you please [submit a bug](https://unity3d.com/unity/qa/bug-reporting)?

**Comment by flankechen** [comment]
@tdmowrer Sorry, it's from bad network, maybe in China, grade try to get jars from jcenter and read timeout... I am trying to switch the net. Thanks for your reply.
