### ISSUE TITLE
Object Tracking missing scripts ?

### ISSUE THREAD

**Issue by ghus86** [Unity-Technologies/arfoundation-samples#330]
Hi Tim - @tdmowrer 

I was trying the ar foundation samples in the version 2.1
but I think the scripts are missing
like ARObjectImporter and the other that controlls the object detection
can you help please 
thanks in advance

**Comment by tdmowrer** [comment]
2.1 is "verified", which means it cannot use any experimental Unity APIs. The scriptable asset importer is still marked as "experimental", so the object tracking had to be removed from the verified package. However, it is still available in the 2.2 and 3.0 _preview_ packages.

**Comment by ghus86** [comment]
oh understood thanks
