### ISSUE TITLE
IOS 13 Update Compability

### ISSUE THREAD

**Issue by ufktvfk** [Unity-Technologies/arfoundation-samples#331]
Hi, 
I just wanted to ask if AR Foundation version 3.0 does not have any compatibility issues with IOS 13 or should we wait for any update for IOS 13 compatibility?
Sorry, I am just asking since I am an online instructor and may inform my students about it. 
Thank you

**Comment by tdmowrer** [comment]
There are no known compatibility issues with iOS 13. Note, however, that your students will need Xcode 11 in order to enable the new ARKit 3 features available in iOS 13.
