### ISSUE TITLE
URP - Black screen after plane detected

### ISSUE THREAD

**Issue by FDDdan** [Unity-Technologies/arfoundation-samples#332]
I'm testing ARFoundation 3 with URP and the camera feed is fine until a plane is detected, after that the camera feed can be seen only through the mesh of the plane and where point cloud particles are appearing, everything else is black. I have added ARBackgroundRendererFeature to the ForwardRenderer of the URP pipeline asset and tried different settings, but I can't find a fix. The screenshot attached is made using the FeatheredPlanes scene, but it is the same with SimpeAR scene or any other scene that is using planes.

Unity 2019.3.0b6
ARFoundation 3.0.0 preview.3
Universal RP 7.1.2
Android 9

![Screenshot_20191017-135334_URPMatLib](https://user-images.githubusercontent.com/26852328/67002975-a9e45000-f0e5-11e9-9fd7-af0ae0dfa38f.jpg)

**Comment by tdmowrer** [comment]
Very strange. What device(s) have you seen this on?

**Comment by FDDdan** [comment]
> Very strange. What device(s) have you seen this on?

I'm using a Samsung Galaxy Note 8 (EU version) and Android 9.

**Comment by tdmowrer** [comment]
We aren't aware of any issues, so we'll have to investigate this. Thanks for reporting.

**Comment by TsukatMPtitsyn** [comment]
Got the same problem Unity 2019.2.10f1, LWRP 6.9.2, AR Foundation 3.0.0 preview 4
The problem happens only on Samsung devices. Samsung Galaxy S8+, Samsung S10+

**Comment by ar4ds** [comment]
Mark, same problem, i've used official LWRP material (Packages>ARKit XR Plugin>Asset>Shaders>ARKitLWRPBackground.shader)Shader in "ARCameraBackground" Component, but background still black, should i add some texture to this material manually?
-----------------------
iPhoneMax
-----------------------
Unity 2019.2.6f1
AR Foundation 3.0.1
ARKit Face Tracking 3.0.1
Lightweight RP 6.9.2

**Comment by tdmowrer** [comment]
There was a similar issue fixed in a later version of ARFoundation. Does it still reproduce in the 3.1.x verified packages?
