### ISSUE TITLE
HumanBodyTracking3D using front camera, is it possible?

### ISSUE THREAD

**Issue by mohammedghabyen** [Unity-Technologies/arfoundation-samples#333]
I wonder is there a way to use front camera for human body tracking 3D?

**Comment by tdmowrer** [comment]
None of the human body tracking (2D, 3D, or occlusion) is currently supported with the front camera. As Apple is currently the only platform offering those features, support depends on Apple. If they support it in the future, then we will update ARFoundation to do so as well.

**Comment by mohammedghabyen** [comment]
Thank you, Have another question, I've tested human body tracking on iPhone XR and results was great, and I've tested it on iPhone 11, the results is not accurate and not stable, I think it because iPhone 11 have two cameras in the back, and it activate the close camera in arkit rear camera, Is there a way to switch cameras and use the other rear camera in iPhone 11?

**Comment by tdmowrer** [comment]
It is not possible to switch cameras, no. However, the iPhone 11 shouldn't be worse, so we'll investigate that.

**Comment by mohammedghabyen** [comment]
Hope you are doing well, Can I ask you about how to change character in the runtime, with arkit 3 humanbodytracking3d, I've tried to enable and disable humanbodytracker, but it didn't work, then I've tried to destroy bonecontroller game object, I remove the current showed character gameobject from the scene, but do not show the new character.
I have array of characters prefabs in the humanbodytracker script attached to it, when I change character, I call this script:
CurrentSkeletonPrefab = CharactersGO[CharNO];
when CharactersGO have array of characters prefabs with bone controller attached and ready to show same as the robot prefab,
but it dose not show the new chooses character, could you help me please, Thank you.

**Comment by tdmowrer** [comment]
> Thank you, Have another question, I've tested human body tracking on iPhone XR and results was great, and I've tested it on iPhone 11, the results is not accurate and not stable, I think it because iPhone 11 have two cameras in the back, and it activate the close camera in arkit rear camera, Is there a way to switch cameras and use the other rear camera in iPhone 11?

I tested this recently and don't see any issues with an iPhone 11. Is this still an issue? If so, can you provide more details or record a video showing the inaccurate/unstable results?

**Comment by mohammedghabyen** [comment]
Yes, I think the problem is with testing area, their was a lot of obstacles in front of the camera like table or chairs, now I get the idea of how using AR camera to get best results, Thank you.

**Comment by AHRealift** [comment]
Any updates?

**Comment by MarcoLavoro** [comment]
> . However, the iPhone 11 shouldn't be worse, so we'll investigate that.

there is any update in this?

**Comment by MarcoLavoro** [comment]
> None of the human body tracking (2D, 3D, or occlusion) is currently supported with the front camera. As Apple is currently the only platform offering those features, support depends on Apple. If they support it in the future, then we will update ARFoundation to do so as well.

There is any news about front camera human segmentation on IOS?

**Comment by AbdulWahabTanveer** [comment]
Any Updates?
