### ISSUE TITLE
Upadte the TrackedObjectPrefab every frame with the position of the ObjectTracked?

### ISSUE THREAD

**Issue by bharath09vadde** [Unity-Technologies/arfoundation-samples#334]
Hello,
I have tested the Object detection using AR Foundation, But I wanted to update the position of the instantiated prefab, every frame to match with the position and rotation of the tracking object. How can I do it? Can somebody please help me with that.
Thanks

**Comment by tdmowrer** [comment]
The ARTrackedObjectManager does this for you already. Note that ARKit does not track moving objects so if you move the physical object it may take some time before the instantiated prefab updates to match.

**Comment by bharath09vadde** [comment]
Thanks for the reply
