### ISSUE TITLE
Are environment probes Android compatible?

### ISSUE THREAD

**Issue by lb-thomas** [Unity-Technologies/arfoundation-samples#335]
Hello,
I am able to run the environment probes sample on an iPhone 10. However, I have tried it on a Samsung s10e and a Samsung s8 and there are no reflections at all (I don't think any reflection probes are being generated). 

Are environment probes supported on Android? Are there any limitations or required settings?

**Comment by DavidMohrhardt** [comment]
ARCore does not have an implementation of the environment probes yet.  We are planning to put it in the next preview release.  There is no specific timeline set for the release but the implementation is completed.

**Comment by lb-thomas** [comment]
Thanks for the info.
