### ISSUE TITLE
Occlusion feature on ARKit 3

### ISSUE THREAD

**Issue by hanquel** [Unity-Technologies/arfoundation-samples#336]
Occlusion feature updated in ARKit 3.0 Is there a plan to make it as AR Foundation Sample?

**Comment by tdmowrer** [comment]
From the [README](https://github.com/Unity-Technologies/arfoundation-samples#humansegmentationimages) (updated yesterday):

> This sample demonstrates "people occlusion", which can produce stencil and depth textures for detected persons. This sample is very primitive and simply displays the raw texture on the screen. We are currently working on a better sample.
>
> This sample requires a device with an A12 bionic chip running iOS 13.

**Comment by tdmowrer** [comment]
There is also now an [`AROcclusionManager`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html?q=AROcclusionManager), which is used in the SimpleAR scene.
