### ISSUE TITLE
[Android] AREnvironmentProbeManager breaks LightEstimation

### ISSUE THREAD

**Issue by dnnkeeper** [Unity-Technologies/arfoundation-samples#338]
First, thank you for adding a long-awaited AREnvironmentProbeSybsystem for ARCore in 3.0.0-preview.4! Unfortunately, it breaks LightEstimation somehow and ARCameraFrameEventArgs.lightEstimation.averageBrightness and lightEstimation.colorCorrection starts returning 0 values if AREnvironmentProbeManager is present on the scene.

**Comment by DavidMohrhardt** [comment]
ARCore provides the environment probe through a separate mode for the light estimation.  Using the environment probe subsystem will enforce that mode which unfortunately will turn off the default.  I checked and our documentation is woefully lacking in this regard so we will move to rectify that.

**Comment by tdmowrer** [comment]
Just to clarify: this is the expected behavior and a limitation of ARCore (you can either have environment probes or ambient light estimation, but not both).
