### ISSUE TITLE
Include ARCameraLighting?

### ISSUE THREAD

**Issue by christougher** [Unity-Technologies/arfoundation-samples#34]
Hi, I was wondering if there were plans to adapt the ARCameraLighting project at https://github.com/johnsietsma/arcameralighting to work with AR Foundation?  I've tried and failed to adapt it myself...

**Comment by christougher** [comment]
bump!

**Comment by jjfranzen** [comment]
Re-bump as this needs to happen at some point. UE4 is implementing it...

**Comment by mdurand42** [comment]
HDR light estimation has been supported in AR Foundation for some time now on ARKit and ARCore.
