### ISSUE TITLE
Android app , no background, no autorisation asked

### ISSUE THREAD

**Issue by DudleySmith** [Unity-Technologies/arfoundation-samples#342]
Hi,
when I start the examples my tablet never ask for camera use permission and no camera preview in background.
I have also a purple on splash screen instead of the Unity logo.

Can you help ?

**Comment by tdmowrer** [comment]
The purple color sounds like the missing shader color. Is this still happening? If so, please provide details on the device, OS, Unity, ARFoundation & ARCore plugin versions.
