### ISSUE TITLE
ARFace's GetUndisposable throws error on UnityEditor

### ISSUE THREAD

**Issue by asus4** [Unity-Technologies/arfoundation-samples#343]
Hi, I am making [an ARFoundation remote simulation tool](https://github.com/asus4/ARKitStreamer). Making a subclass of XRFaceSubsystem that works on UnityEditor. 

`ARFace.GetUndisposable` throws on only UnityEditor, since NativeArray.cs is checked read/write access on Editor. it works if remove `GetUndisposable` and simply return the native array. any workaround?

[NativeArray.cs source code](https://github.com/Unity-Technologies/UnityCsReference/blob/f78f4093c8a2b45949a847cdc704cf209dcf2f36/Runtime/Export/NativeArray/NativeArray.cs#L132)

```
// ARFace.cs
 public unsafe NativeArray<Vector3> vertices
 {
    get
    {
         // throws error on Editor
         return GetUndisposable(m_FaceMesh.vertices);
         // It works
         return m_FaceMesh.vertices;
     }
}
```

__Error Message__
```
NullReferenceException: Object reference not set to an instance of an object
Unity.Collections.NativeArray`1[T].CheckElementReadAccess (System.Int32 index) (at /Users/builduser/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:117)
Unity.Collections.NativeArray`1[T].get_Item (System.Int32 index) (at /Users/builduser/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:139)
Unity.Collections.NativeArray`1+Enumerator[T].get_Current () <0x14a2783c0 + 0x0007a> in <85963591c1a04aad836445db604e7807>:0
UnityEngine.XR.ARFoundation.ARFaceMeshVisualizer.TryCopyToList[T] (Unity.Collections.NativeArray`1[T] array, System.Collections.Generic.List`1[T] list) (at Library/PackageCache/com.unity.xr.arfoundation@3.0.0-preview.4/Runtime/AR/ARFaceMeshVisualizer.cs:46)
UnityEngine.XR.ARFoundation.ARFaceMeshVisualizer.SetMeshTopology () (at Library/PackageCache/com.unity.xr.arfoundation@3.0.0-preview.4/Runtime/AR/ARFaceMeshVisualizer.cs:61)
UnityEngine.XR.ARFoundation.ARFaceMeshVisualizer.SetVisible (System.Boolean visible) (at Library/PackageCache/com.unity.xr.arfoundation@3.0.0-preview.4/Runtime/AR/ARFaceMeshVisualizer.cs:34)
UnityEngine.XR.ARFoundation.ARFaceMeshVisualizer.UpdateVisibility () (at Library/PackageCache/com.unity.xr.arfoundation@3.0.0-preview.4/Runtime/AR/ARFaceMeshVisualizer.cs:103)
UnityEngine.XR.ARFoundation.ARFaceMeshVisualizer.OnUpdated (UnityEngine.XR.ARFoundation.ARFaceUpdatedEventArgs eventArgs) (at Library/PackageCache/com.unity.xr.arfoundation@3.0.0-preview.4/Runtime/AR/ARFaceMeshVisualizer.cs:108)
UnityEngine.XR.ARFoundation.ARFace.Update () (at Library/PackageCache/com.unity.xr.arfoundation@3.0.0-preview.4/Runtime/AR/ARFace.cs:123)
```

__Environment__
- macOS
- UnityEtior 2019.2.8f1
- Packages
    - "com.unity.xr.arcore": "3.0.0-preview.4",
    - "com.unity.xr.arfoundation": "3.0.0-preview.4",
    - "com.unity.xr.arkit": "3.0.0-preview.4",
    - "com.unity.xr.arkit-face-tracking": "3.0.0-preview.4",

**Comment by tdmowrer** [comment]
Thanks for reporting. This does not happen in current `master`, and, looking at the code for `ARFace.cs`, it looks like everything is guarded correctly. It may have been an issue in a 3.0 preview, but it looks like it was fixed. Please reopen if you are still seeing this.

**Comment by Lchikar** [comment]
Hello,

I have dealt with the exact same issue lately while working on an ARFoundation simulation tool as well. I managed to solve it temporarily with what @asus4 shared in [his thread](https://github.com/asus4/ARKitStreamer/issues/2#issuecomment-552880905).

Are there any updates about this issue today ?

Environment :
Unity Editor 2019.4.24f1
ARFoundation 4.1.7
ARKit 4.1.7
ARCore 4.1.7
