### ISSUE TITLE
Arfoundation iOS 13.1.3 compatible?

### ISSUE THREAD

**Issue by gabexr** [Unity-Technologies/arfoundation-samples#344]
Hello,
I've been trying to have ARKit 3 work with iOS13, but when I launch the app there's nothing being shown. I did add a plane manager and point cloud manager on the scene and those are not visible, at all, I am not sure if there's any tracking going on.
I am using Unity 2019.2.1f1 and Xcode 11.
I'd like to know what are preview or stable arfoundation/ARKit/etc... versions that work with BOTH iPadOS 13 and iOS13.

Thank You.

**Comment by DiveshNaidoo** [comment]
I’m also having issues on iOS 13.2 initially I thought that the tracking was not working at all however if you move around for a while, tracking information through debug visualizers will appear and track momentarily. The tracking then drifts quite badly and will not stabilize for more than a few seconds.

**Comment by mdurand42** [comment]
Are you still seeing this issue with later versions of iOS 13? Also, please test with the verified packages that ship with the latest Unity 2019.3.
