### ISSUE TITLE
On A12 and up devices, ARHumanBodyManager and ARParticipantManager conflicts with each other.

### ISSUE THREAD

**Issue by JustinFincher** [Unity-Technologies/arfoundation-samples#345]
Hi, I have some issues when using `ARHumanBodyManager` and `ARParticipantManager` at the same time, specifically, when I have both managers attached to the AR Session Origin game object, the plugin cannot find the person in the camera view, but if I remove the `ARParticipantManager` component from the game object, export the project and run, the skeleton would display again. I wonder if these two sub-systems just cannot work together in the current version of ARKit, or is this just a bug in implementation? Thanks!

Steps to reproduce:
Clone this repo
Open ARCollaborationDataExample scene
Add ARHumanBodyManager to AR Session Origin game object
Enable 3D pose and scale tracking in ARHumanBodyManager
Run it on iOS devices

Environment:
Unity 2019.3.0b8
iOS 13.1 / 13.2
Xcode 11.1 / 11.2 beta 2
iPad Pro 2018 11 inch

package.json
```
    "com.unity.xr.arfoundation": "3.0.0-preview.4",
    "com.unity.xr.arkit": "3.0.0-preview.4",
    "com.unity.xr.arsubsystems": "3.0.0-preview.4",
    "com.unity.xr.legacyinputhelpers": "2.0.6",
    "com.unity.xr.management": "3.0.3",
```

**Comment by JustinFincher** [comment]
As Motion Tracking in ARKit 3 requires A12 chips and up, when I am running the same demo on an iPad Pro 2018 (A12X) and an iPhone X (A11), only the iPad Pro would enable Motion Tracking, and that is where the issue gets weird: iPhone X doesn't work with Motion Tracking, and it always has collaboration data and sends it no matter if ARHumanBodyManager is present or not, but for the iPad Pro, ARParticipantManager only works without ARHumanBodyManager. With the ARHumanBodyManager, "Has Collaboration Data" UI Indicator is always off, and I get this log entry spamming in the Xcode console:
```
2019-10-30 22:31:03.192763+0800 samples[1380:348983] [Technique] ARWorldTrackingTechnique(0x12f00f640) collaboration data cannot be pushed because the feature is disabled.
```
🤔But accessing ARParticipantManager.subsystem.running results true, could this mean that if ARHumanBodyManager kicks in, the ARParticipantManager would be disabled in the background?

**Comment by JustinFincher** [comment]
Well it seems to due to the fact that an ARSession could only run either an ARBodyTrackingConfiguration (HumanBodyManager) or an ARWorldTrackingConfiguration(ParticipantManager) at one time: https://developer.apple.com/documentation/arkit/arconfiguration?language=objc

**Comment by tdmowrer** [comment]
This is a bit confusing. Not all features are supported simultaneously, but some features provided by the `ARHumanBodyManager` do use an `ARWorldTrackingConfiguration` and can therefore be used in a collaborative session.

> ARBodyTrackingConfiguration (HumanBodyManager)

The `ARHumanBodyManager` only uses the `ARBodyTrackingConfiguration` when 3D body tracking is enabled.

We are working on making these choices less opaque in the future, so it should be possible to know what combination of features will work together.

**Comment by JustinFincher** [comment]
OK now I get it, I was going to use 3D body tracking and participation functions at the same time. So it did involve `ARBodyTrackingConfiguration` and `ARWorldTrackingConfiguration`. I guess the current workaround would be using a CoreML model to make 3D pose estimations and remove the ARHumanBodyManager from the scene. Thanks!
