### ISSUE TITLE
Can't pass cvPixelBufferPtr to CoreML

### ISSUE THREAD

**Issue by fsal-code** [Unity-Technologies/arfoundation-samples#347]
Hi,

I'm using XRCameraImage to pass a pointer to the cvPixelBufferPtr to CoreML, but I always get BAD_EXCPETION error in objective-c. Using videoParams.cvPixelBufferPtr from the old ARKit plug in works just fine. So I'm wondering what has changed.

I'm using the latest ARFoundation preview.

**Comment by tdmowrer** [comment]
`XRCameraImage` is our abstraction for `CVPixelBuffer`, though we don't surface the pointer to the `CVPixelBuffer` itself; you _can_, however, get pointers to the raw image planes from the `XRCameraImage`, the equivalent of [`CVPixelBufferGetBaseAddressOfPlane`](https://developer.apple.com/documentation/corevideo/1456821-cvpixelbuffergetbaseaddressofpla?language=objc). I'm not sure if that's "good enough" for CoreML.

If you do need the `CVPixelBuffer` itself, you can get a pointer to the ARFrame and [get it from that](https://developer.apple.com/documentation/arkit/arframe/2867984-capturedimage?language=objc).

To get a pointer to ARKit's ARFrame in ARFoundation, you can do something like:
```csharp
cameraManager.subsystem.TryGetLatestFrame(params, out XRCameraFrame cameraFrame);
```

And then `cameraFrame` has a [`nativePtr`](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.1/api/UnityEngine.XR.ARSubsystems.XRCameraFrame.html#UnityEngine_XR_ARSubsystems_XRCameraFrame_nativePtr) which will point to a struct that looks like the one [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/manual/extensions.html):

```c
struct native_arframe {
    int version;
    void* arframe_from_arkit;
};
```
