### ISSUE TITLE
Black Screen - cameraManager.TryGetLatestImage(out __image)

### ISSUE THREAD

**Issue by brklipel** [Unity-Technologies/arfoundation-samples#348]
Hi, i have had a problem at black screen when that line is activated:
if (!cameraManager.TryGetLatestImage(out __image))

in the TestCameraImage.cs.

But, if it isn't atcivated the camera runs normally.

I'm running the project on Unity 2019.2.9f.
My phone is a Pocophone F1 and there aren't errors in Logcat

**Comment by RuiBEAT** [comment]
I have experienced the same behaviour on some devices, including Pocophone F1. The black screen gets fixed when rotating the device screen.

More details here: https://forum.unity.com/threads/arfoundation-black-screen-when-trying-to-get-cpu-camera.764345/

**Comment by tdmowrer** [comment]
This sounds like an issue which only affected certain devices and was a while back. Which version of ARFoundation are you using (and does it still happen)?

**Comment by RuiBEAT** [comment]
The issue was fixed with the ARFoundation 3.0 release. :)
Thank you,

**Comment by tdmowrer** [comment]
Great, thanks for confirming!
