### ISSUE TITLE
Scripts > Multipeer is Not needed, but iOS App is not compiled without it

### ISSUE THREAD

**Issue by andrewio** [Unity-Technologies/arfoundation-samples#350]
I don't use ARCollaborationData in my project, but it's needed in fact. Please, fix it.

**Comment by tdmowrer** [comment]
Sorry, I don't understand the question.

The collaborative session feature in ARFoundation does not require Multipeer (you can choose any networking technology you like).

The _sample_ demonstrating collaborative sessions does use [Multipeer Connectivity](https://developer.apple.com/documentation/multipeerconnectivity) to communicate between devices. The files in Scripts/Multipeer is a C# wrapper around this API.

**Comment by andrewio** [comment]
> Sorry, I don't understand the question.
> 
> The collaborative session feature in ARFoundation does not require Multipeer (you can choose any networking technology you like).
> 
> The [_sample_](https://github.com/Unity-Technologies/arfoundation-samples/tree/master/Assets/Scenes/ARCollaborationData) demonstrating collaborative sessions does use [Multipeer Connectivity](https://developer.apple.com/documentation/multipeerconnectivity) to communicate between devices. The files in Scripts/Multipeer is a C# wrapper around this API.

Got it. I previously builded AR Foundation Samples  with all scenes in build. And it's OK, but scene I have only one scene without using ARCollaborationData. Then I Build with Replacing, but I've got errors, because Xcode System Folder > DerivedData must be cleaned manually to clean old dependencies.

After cleaning this folder all is OK.
