### ISSUE TITLE
Sony Xperia XZ Premium: Black Camera Screen at the ARCoreFaceRegions Scene

### ISSUE THREAD

**Issue by Russel1** [Unity-Technologies/arfoundation-samples#352]
When I start the ARCoreFaceRegions scene on the Sony Xperia XZ Premium, the permission is requested but afterwards the camera screen remains black. But on my Google Pixel 2 it works fine.

Sony Xperia XZ Premium
Model:G8141
Android: 9

Can anyone confirm the problem?

**Comment by Russel1** [comment]
Can anyone confirm the problem?

**Comment by mdurand42** [comment]
Does this issue still reproduce with newer versions of Play Services for AR? Does world tracking work for you with this device or is face tracking the only issue?
