### ISSUE TITLE
XRSubsystem<TSubsystemDescriptor>.OnDestroy(): no suitable method found to override

### ISSUE THREAD

**Issue by YVanhoutte** [Unity-Technologies/arfoundation-samples#356]
I just downloaded the project and opened it in Unity 2019.3.0a8 and am immediately hit with the following errors:
Library\PackageCache\com.unity.xr.arsubsystems@3.0.0-preview.4\Runtime\XRSubsytstem.cs(50,40): error CS0115: 'XRSubsystem<TSubsystemDescriptor>.OnDestroy()': no suitable method found to override

Library\PackageCache\com.unity.xr.management@3.0.2-preview.2\Editor\XRGeneralBuildProcessor.cs(109,33): error CS0234: The type or namespace name 'BootOptions' does not exist in the namespace 'UnityEditor.XR' (are you missing an assembly reference?)

How to fix these?

**Comment by wakatanka** [comment]
bumb, same on 2019.3.0b4

**Comment by sergiosolorzano** [comment]
Same on 2019.3.0b1, anyone found a solution? cheers

**Comment by midopooler** [comment]
still no solutions?

**Comment by cmwolke-gamedesign** [comment]
Same 2019.2.10f1

**Comment by tdmowrer** [comment]
This should only have been an issue during a brief window while 2019.3 was in development, and should not affect 2019.2. However, 2019.2 is no longer supported now that 2019.3 is out. Can you upgrade to that version of Unity?

**Comment by Augmentaio** [comment]
Same on 2019.2.9f1

**Comment by tdmowrer** [comment]
2019.2 is not supported. Have you tried 2019.3?
