### ISSUE TITLE
Skybox Material missing in iOS build

### ISSUE THREAD

**Issue by WangChaolun** [Unity-Technologies/arfoundation-samples#358]
Test in Unity2019.2.10f1, Unity2019.2.11f1, Unity2019.3.0b10. Xcode version 11.2 beta2, arfoundation 3.0 preview-4
Skybox shader used Skybox/Cubemap
seem like Skybox Material missing in build!(bc if i set skybox material == null in Editor, the effect is same in build)
all the light effct and reflection effect incorrect
any idea?
thanks

**Comment by mdurand42** [comment]
We have not had reports of this and in AR we do not make use of skybox materials.
