### ISSUE TITLE
Get detected plane's normal always pointing to camera's side.

### ISSUE THREAD

**Issue by srcnalt** [Unity-Technologies/arfoundation-samples#36]
There is an issue I face mostly when I work on vertical surfaces. AR tool detects a couple of planes on the same surface and one of these planes have it's normal inverted. Like normal of that plane is looking the other way where camera is. So the spawned object looks upside down.

**Edit:** Issue occurs on horizontal surfaces too.

**Comment by bitfabrikken** [comment]
Anecdotal, but I've only had this happen in low lighting situations.

**Comment by tdmowrer** [comment]
On ARCore or ARKit (or both)?

That sounds like something happening at the device level, and if it only happens in low light, it might just be the device struggling to get good tracking data.

**Comment by bitfabrikken** [comment]
My money's on ARCore, that's where it's happened to me (in low light).

**Comment by srcnalt** [comment]
Environment was not dark at all. When I over-scan a surface it was creating couple of layers on top of each other. However yesterday's ARCore update seems to clean this problem out. Same surface same light conditions did not create the same problem.

**Comment by tdmowrer** [comment]
> ...yesterday's ARCore update...

Hang on, do you mean [GoogleARCore](https://github.com/google-ar/arcore-unity-sdk)? That's different from the ARCore XR Plugin package provided by Unity for which this repo contains samples.
