### ISSUE TITLE
Crash! Integrated into native Android app,enter AR again crashed.

### ISSUE THREAD

**Issue by LiuquanReal** [Unity-Technologies/arfoundation-samples#360]
When AR is integrated into Android native app, when I use Application.Quit() exit Unity and entered again crashed.
![image](https://user-images.githubusercontent.com/18605994/68846236-b91be500-0707-11ea-9856-b1a3e2707bf9.png)

**Comment by tdmowrer** [comment]
We haven't seen this reported elsewhere when using Unity as a Library, but I do recall there being an issue generally with Application.Quit on Android. Have you tried this on a more recent version of Unity?
