### ISSUE TITLE
Memory leak in iOS , ARFoundation 3  preview 5

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#361]
When I load a blank scene, the memory is 160 M+, and after the ARFoundation session is created, the memory is 500 M+, and then all ARFoundation sessions are destroyed, and the memory is reduced to 300 M+.

Detial:

- iOS 13.2.2
- iPhone 11
- Unity 2019.3 B11
- URP/LWRP-7.1.5
- Xcode 11.2.1

<img width="476" alt="截屏2019-11-16下午11 28 01" src="https://user-images.githubusercontent.com/11573490/68995684-5a9f6400-08cb-11ea-8e1a-08c4594427ce.png">

<img width="476" alt="截屏2019-11-16下午11 29 06" src="https://user-images.githubusercontent.com/11573490/68995668-3774b480-08cb-11ea-89db-616f549da5db.png">

<img width="476" alt="截屏2019-11-16下午11 29 37" src="https://user-images.githubusercontent.com/11573490/68995677-4d827500-08cb-11ea-8353-d57984bf4c31.png">

**Comment by kobechen413** [comment]
I has same problem, can you think solution the issue ?

**Comment by weacw** [comment]
> I has same problem, can you think solution the issue ?

尝试 ` ARSession.Reset() ` 会对内存有比较大的减少 ，但还是没解决根本性泄露问题。

**Comment by tdmowrer** [comment]
Some memory leaks were fixed during the preview cycle. Is this reproducible on the verified version of ARFoundation 3? (Latest is 3.1.3)
