### ISSUE TITLE
LWRP+ARFoundation Doesn't work 2019.1

### ISSUE THREAD

**Issue by apiotuch** [Unity-Technologies/arfoundation-samples#362]
Is LWRP going to be supported for ARFoundation going forward? Or is there a combination of packages (versions) that currently works for android + iOS devices? I am currently using 2019.1.10f1 and that seems to be the most stable with the 2019 versions I've tried so far. One major issue I've seen with the sample project is dependencies on Experimental libraries, Unity has since moved those into UnityEngine.Rendering and .LWRP. However the sample has files that no longer implement the correct methods for custom scripts when inheriting the classes from the moved libraries. I am about to dig deep but was hoping that ARFoundation + LWRP will finally have stable support instead of me fixing these issues. without the sample, ARFoundation renders the scene without the cam (black screen). When I select the AR Camera GameObject, the only thing that seems to be missing is the ability to create and reference AR Background Rendering Asset on the AR Background Camera component. I tested an android build with just 3D pipeline and it works. LWRP only 3D objects work, not camera.

**Comment by mdurand42** [comment]
Support for LWRP has been discontinued in favor of URP. Please see the instructions here for converting your AR Foundation project to use URP.
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/manual/index.html
