### ISSUE TITLE
Can we get a face mesh in ARFace with the eyes and mouth meshed up?

### ISSUE THREAD

**Issue by digitalmonkey** [Unity-Technologies/arfoundation-samples#363]
Hi, I would like to work with a version of the tracked face mesh in FaceTracking that does not have holes for the eyes and mouth. Instead, I would like them sealed up or meshed over. I know the face from SceneKit for ARKit3 provides the option of filling in the mesh holes. Can we have an option to provide that version of the mesh as well. It makes it easier to texture over the face mesh with a video or photo.

**Comment by tdmowrer** [comment]
SceneKit seems to have more information available to it than ARKit makes available to us, so we have no way of knowing which parts of the mesh represent the eyes and mouth. I've added it to our backlog, but currently, there is no way we can offer this functionality.

**Comment by MubeenNawabChandna** [comment]
A faceMesh example don't show user eyes mouth, nose hole in ARcore۔
Please resolve this example
