### ISSUE TITLE
Using back camera for AR while simultaneously capturing input with the front camera

### ISSUE THREAD

**Issue by cfry2** [Unity-Technologies/arfoundation-samples#366]
Hi there,

I'm wondering if something like this is possible with ARFoundation. 
From what I've read it's possible to record with front and back cameras simultaneously with the latest iPhones (XS+). I've also read that a limit set of Android devices support simultaneous use of front and back cameras.

However, I haven't been able to get anything to work. Using the AR Session camera immediately disables a WebCamTexture that is playing from my front cam device (tested on pixel 3)

My specific use case is to manipulate AR imagery depending on the user's emotional response. The front camera just needs to snapshot this information so that I can send it to be processed by AWS' Rekognition API.

Is what I'm trying to achieve simply not possible with a single device?

**Comment by mdurand42** [comment]
AR Foundation 4.0.0 allows for this configuration much more easily than AR Foundation 3.0.0 did. Please see this migration guide for more details.
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/migration-guide-3.html

**Comment by BJWOODS** [comment]
> AR Foundation 4.0.0 allows for this configuration much more easily than AR Foundation 3.0.0 did. Please see this migration guide for more details. https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/migration-guide-3.html

This documentation you're referencing is not explicit; could you point out exactly what components or class attributes we'd use to enable streaming of the front & rear camera at the same time? I am trying to do this now.
