### ISSUE TITLE
how change character at the runtime for bodytracking3D?

### ISSUE THREAD

**Issue by MohammedGh92** [Unity-Technologies/arfoundation-samples#367]
Hi,
I've 10 characters prefabs in an array and bone controller attached to each one same as robot, and the tracking is working good, but dont know how to change between characters while tracking is on and the scene is playing, I've managed to do that by reloading the whole scene and setting the desired character from the beginning from the array of 3D prefabs of characters, each time I want to switch character to another one at the runtime, I reload the whole scene which is not efficient way to do it, any ideas how to make it?
thank you

**Comment by mdurand42** [comment]
The  best advice we can give is to refer to this documentation page.
https://docs.unity3d.com/Manual/Retargeting.html

We plan to provide a sample to demonstrate this in the future.
