### ISSUE TITLE
Plane tracking not working on my iPhone 6s with iOS 11.2

### ISSUE THREAD

**Issue by bharath09vadde** [Unity-Technologies/arfoundation-samples#368]
Hello,
I have created an application using AR Foundation 2.1.4, ARKit 2.1.2 and deployed it to iPhone 6s that is running on iOS 11.2.6 using Xcode 11.3. When I open the AR scene, it does not detect the ground which is working fine on other iOS devices that are running on iOS 12 or later. Is there a possibility of overcoming this issue by downgrading AR Foundation or Xcode or ARKit?

Thanks in advance.

**Comment by mdurand42** [comment]
We have not been able to duplicate this issue.
