### ISSUE TITLE
MakeContentAppearAt bug in the editor

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#371]
Is MakeContentAppearAt supposed to work in the editor? The content placement offset doubles when calling it a second time for the same transform with the same position.

Same exact code works fine on devices

**Comment by rogueyoshi** [comment]
How could it work in editor without getting pose info from the phone?

**Comment by tdmowrer** [comment]
ARFoundation generally does not support in-Editor workflows. However, we are working on a remoting package which will provide communication between a device running ARFoundation and the Editor, which should improve iteration time.
