### ISSUE TITLE
URP No Cascade for shadows causing black camera (2019.3.0b12 & 3.1.0 p1)

### ISSUE THREAD

**Issue by TeorikDeli** [Unity-Technologies/arfoundation-samples#372]
Hi!

Changing URP's shadows setting "Cascade" to "No cascade" creates an error for Unlit/ARKitURPBackground shader and gives black camera background. But, I think the reflection probes works normally, because I can see their textures.

The error:

"Metal: Error creating pipeline state (Unlit/ARKitURPBackground): depthAttachmentPixelFormat is not valid and shader writes to depth"

I am suspecting "ForceNoShadowCasting" = "True" tag in the shader, but idk. I will try to change this shader and if anything fixes the problem, I will post to here.

Device: iPhone 8 iOS 13.2.3
Xcode: 11.2.1 (GM)
Unity: 2019.3.0b12
AR Foundation (and ARKit, ARCore): preview.1 - 3.1.0

**Comment by TeorikDeli** [comment]
I fixed the issue with removing the depth of fragment_output. It is not an ideal solution if the Human Segmentation is active.

**Comment by Saicopate** [comment]
I have the same "Error creating pipeline state" error and blank screen with newest Unity + ARF revisions. Switching shadow cascades does not help.

**Comment by DavidMohrhardt** [comment]
Hello, sorry this has taken so long to get to.  I have attempted to recreate the issue with the latest packages as well as the non-preview release of 3.1 and I have not been able to reproduce the issue.  If this is still an issue please let us know by making a [bug report](https://unity3d.com/unity/qa/bug-reporting) and responding with a case number so we can find it faster.

**Comment by christougher** [comment]
Hi, I was getting the same problem with using the older ArCameraLighting Git, the fix for me was to change my target rendertexture depth buffer setting from "no depth buffer" to one of the other settings. Hope this helps
