### ISSUE TITLE
Black screen after enabling post processing (2019.3.0f1, 3.1.0 preview 1, URP)

### ISSUE THREAD

**Issue by DiveshNaidoo** [Unity-Technologies/arfoundation-samples#374]
After enabling post processing I get a black screen. Did not have this issue on previous ARkit/ARFoundation releases.

**Comment by TeorikDeli** [comment]
Hi! I am also using post processing in my project (same Unity & ARF versions), but I don't have the same problem. I have the black screen issue when I set shadow cascading to "No Cascade" in my URP settings. By the way, I am only using FXAA and Bloom in post processing.

**Comment by b29b** [comment]
i changed "no cascade" but still get a black screen, can you share your configs?
or better a working sample project...

**Comment by DiveshNaidoo** [comment]
There is an update in this thread concerning the issue https://forum.unity.com/threads/configuring-ar-foundation-3-0-0-preview-to-work-with-lwrp-or-urp.736583/page-2#post-5292990

**Comment by tdmowrer** [comment]
This was fixed in [3.1.0-preview.3](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/changelog/CHANGELOG.html#fixes). Let me know if this is still an issue for you.
