### ISSUE TITLE
Scale (example scene not working)

### ISSUE THREAD

**Issue by MrDChristop** [Unity-Technologies/arfoundation-samples#375]
Hi 
i am using unity 2019,2,6f1 and ARFoundation 3.0.0 (preview 2) on an iPad Air 3

the Scale example isn't working at all. IT scans the floor but then as soon as you tap on it everything vanishes.
As you scan the floor the 3D model that is scaled appears often automatically then if you rotate or scale it using the sliders again everything disappears.
I have a video attached here
https://www.dropbox.com/s/aqxm06ptrcysbng/2019-12-03%2015.59.06.mp4?dl=0

**Comment by tdmowrer** [comment]
I believe this was temporarily broken in one of the 3.0 preview releases. Have you tried the verified (non-preview) 3.0 release?
