### ISSUE TITLE
Problem with "stuck" ar elements and very slow plane detection

### ISSUE THREAD

**Issue by franMx** [Unity-Technologies/arfoundation-samples#376]
Hi, I have  a problem with arfoundation. Plane detection is extremely slow (sometimes it doesn't work at all) and AR elements "stuck" with camera.

Using Unity's ar foundation  I have this problem on Galaxy s10 (android 9.0). 
**Unity version: 2019.2.15f1** on OSX
**ar samples: branch 2.1**
**platform: Android**

Same apk works smoothly in other devices:
LG G6, Galaxy s7 and even Xiaomi mi5 (unsupported).

Video: [https://youtu.be/BBNp0wn7ftY]()

**Comment by tdmowrer** [comment]
> Plane detection is extremely slow

That can vary by device (different hardware, different results), and your environment seems to lack detail which can help with tracking and plane detection (e.g., a smooth, homogeneous surface like the smooth concrete floor). Do you have similar results with [Google's plugin](https://github.com/google-ar/arcore-unity-sdk)?

> and AR elements "stuck" with camera.

I'm not sure what you mean; I don't see that in the video. Can you elaborate?

**Comment by franMx** [comment]
Hi Tim, about 1:29 of the video posted is what meant with stuck (https://youtu.be/BBNp0wn7ftY?t=89) If the device was able to detect position, it lost track and 3d elements got "stuck" in the screen. Tests were done inside a building, at street and in the backyard shown in the video. In none of those it was working fine. Daytime and evening were tested, natural and artificial light.

What worries me is that same app was deployed  in 3 different samsung s10 , maybe the 3 of them were malfunctioning (kind of weird, but let's assume it was the case). Exact same app was tested on low end devices as well as iphones, on those devices it worked from ok to really well.  

I haven't tested with google's plugin, will have a look at it. Is there any specific version that you would recommend?

**Comment by tdmowrer** [comment]
Okay, I see what you mean by "stuck". Are there any exceptions thrown (or other errors)? It looks like it happens right as you move out of the "portal" you've created, and I imagine you might have code that only executes when that happens -- could there be a problem there?

> ...google's plugin...Is there any specific version that you would recommend?

Just build the Unity project from the `master` branch of their [GitHub repo](https://github.com/google-ar/arcore-unity-sdk). Their "HelloAR" sample scene performs plane detection, so you can run that without modification to see whether you get different plane detection results.

**Comment by franMx** [comment]
Hi Tim, it was happening with included samples too, not only that scene.

I will compile google's helloAR  and check out for errors, any specific logcat keyword to check for? Otherwise can paste all of it, but probably will be huge.

**Comment by tdmowrer** [comment]
> I will compile google's helloAR and check out for errors, any specific logcat keyword to check for? Otherwise can paste all of it, but probably will be huge.

Sorry, those are two separate things.
* To debug the "stuck" issue, run your app and look for exceptions or other errors around the time objects get "stuck". You can filter logcat for messages from `Unity` and `native` (this will be messages from ARCore).
* To debug the "plane detection takes a while on s10" issue, just run Google's HelloAR sample and see if there are any differences. This will help determine if the issue is just a difference between devices, or a real problem in ARFoundation.

**Comment by ChazM** [comment]
I know this looks closed, but it is 2021 and I have found with the same issue objects stuck in a corner, before everything was working fine, I did make a rebuild and then all went to hell.
The device is a Huawei Y9 2020

**Comment by raghavmittal101** [comment]
I too am facing same issue. I have a Redmi Note 8 Pro. The build works great for the first time after installation. Reopening the installed app next time is not working.
