### ISSUE TITLE
AR Face iOS front Camera Issue

### ISSUE THREAD

**Issue by lijualivenow** [Unity-Technologies/arfoundation-samples#377]
I am using iPhone 8 with ios 13. I made with face mesh sample scene. It's working on Android. In iOS instead of the front camera, it is showing the rear camera, even no face are detecting. Tried in different unity version 2018.4.x and 2019.2.x. The issue is still there.

**Comment by rvegele** [comment]
Hi, perhaps I'm wrong on this, but face-tracking requires a newer apple device, 

Specifically:

> An iOS device with front-facing TrueDepth camera:
iPhone X, iPhone XS, iPhone XS Max, or iPhone XR.
iPad Pro (11-inch) or iPad Pro (12.9-inch, 3rd generation).

from [faces](https://developer.apple.com/documentation/arkit/tracking_and_visualizing_)

**Comment by lijualivenow** [comment]
> 
> 
> Hi, perhaps I'm wrong on this, but face-tracking requires a newer apple device,
> 
> Specifically:
> 
> > An iOS device with front-facing TrueDepth camera:
> > iPhone X, iPhone XS, iPhone XS Max, or iPhone XR.
> > iPad Pro (11-inch) or iPad Pro (12.9-inch, 3rd generation).
> 
> from [faces](https://developer.apple.com/documentation/arkit/tracking_and_visualizing_)

You mean https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/DeviceCompatibilityMatrix/DeviceCompatibilityMatrix.html

**Comment by lijualivenow** [comment]
Okay, I got it, iPhone X or higher is required for face tracking. https://developer.apple.com/documentation/arkit/tracking_and_visualizing_faces.

Thank you @rvegele
