### ISSUE TITLE
Not getting correct dimensions of image target added at runtime

### ISSUE THREAD

**Issue by lb-thomas** [Unity-Technologies/arfoundation-samples#379]
It appears I'm not getting the correct dimensions of an image target added at runtime.

See screenshot below:
The target on the left was added to the ReferenceImageLibrary prior to building. It displays the expected reference size and the green box (which is resized according to the size of `ARTrackedImage.size`) fits the dimensions of the actual target.

The target on the right was added at runtime to the same ReferenceImageLibrary using
`MutableRuntimeReferenceImageLibraryExtensions.ScheduleAddImageJob`. It appears the width and height of the image target are both the same as the input for the `widthInMeters` argument of `ScheduleAddImageJob`. But this target is not a square.

![IMG_0145](https://user-images.githubusercontent.com/22300782/71107812-d83ae600-218f-11ea-87bb-a035cc49da10.JPG)

Any advice here?

Using:
AR Foundation 3.0.1
Unity 2019.3.0f1
XCode 11.2.1
iPhone X 12.3.1

**Comment by tdmowrer** [comment]
By default, texture dimensions are rounded to the nearest power of 2, which looks like what is happening here. You can change the Texture2D's import settings, or get the image some other way (e.g., raw pixel data).
