### ISSUE TITLE
Black Screen on Samsung Galaxy S7

### ISSUE THREAD

**Issue by rubit0** [Unity-Technologies/arfoundation-samples#380]
We are experiencing an blocking issue on the Samsung Galaxy S7 where there is no Camera Feed and no active AR feature detection happening. Also when switching scene away, so that the AR Subsystem gets disabled, then the entire App will crash. There are no Exceptions logged from Unity but with logcat I was disabled to catch this:

Note: I have replaced the app name with 'XXX'
> 12-18 21:24:51.723 24816 24832 E mono-rt : =================================================================
> 12-18 21:24:51.723 24816 24832 E mono-rt : Got a SIGSEGV while executing native code. This usually indicates
> 12-18 21:24:51.723 24816 24832 E mono-rt : a fatal error in the mono runtime or one of the native libraries
> 12-18 21:24:51.723 24816 24832 E mono-rt : used by your application.
> 12-18 21:24:51.723 24816 24832 E mono-rt : =================================================================
> 12-18 21:24:51.723 24816 24832 E mono-rt :
> 12-18 21:24:51.751 24816 24832 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 12-18 21:24:51.752 24816 24832 E CRASH   : Version '2019.3.0f3 (6c9e2bfd6f81)', Build type 'Development', Scripting Backend 'mono', CPU 'armeabi-v7a'
> 12-18 21:24:51.752 24816 24832 E CRASH   : Build fingerprint: 'samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU2DRC1:user/release-keys'
> 12-18 21:24:51.752 24816 24832 E CRASH   : Revision: '8'
> 12-18 21:24:51.752 24816 24832 E CRASH   : ABI: 'arm'
> 12-18 21:24:51.752 24816 24832 E CRASH   : Timestamp: 2019-12-18 21:24:51+0100
> 12-18 21:24:51.752 24816 24832 E CRASH   : pid: 24816, tid: 24832, name: UnityMain  >>> XXX.XXX.XXX <<<
> 12-18 21:24:51.752 24816 24832 E CRASH   : uid: 10199
> 12-18 21:24:51.752 24816 24832 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
> 12-18 21:24:51.752 24816 24832 E CRASH   : Cause: null pointer dereference
> 12-18 21:24:51.752 24816 24832 E CRASH   :     r0  00000000  r1  00000000  r2  0001d080  r3  00000003
> 12-18 21:24:51.752 24816 24832 E CRASH   :     r4  00000000  r5  c99cc6b8  r6  00000000  r7  e7e23e70
> 12-18 21:24:51.752 24816 24832 E CRASH   :     r8  00000000  r9  e7fee7e8  r10 00000002  r11 e7fee2e8
> 12-18 21:24:51.752 24816 24832 E CRASH   :     ip  adaa5234  sp  e7fee1a0  lr  ada88678  pc  00000000
> 12-18 21:24:51.778 24816 24832 E CRASH   :
> 12-18 21:24:51.778 24816 24832 E CRASH   : managed backtrace:
> 12-18 21:24:51.778 24816 24832 E CRASH   :       #00 (wrapper managed-to-native) UnityEngine.XR.ARCore.ARCoreXRDepthSubsystem/Provider/NativeApi:UnityARCore_depth_Stop ()
> 12-18 21:24:51.778 24816 24832 E CRASH   :       #01 UnityEngine.XR.ARCore.ARCoreXRDepthSubsystem/Provider:Stop () <D:\Projects\XXX\Library\PackageCache\com.unity.xr.arcore@2.1.2\Runtime\Depth\ARCoreXRDepthSubsystem.cs:215>
> 
> 12-18 21:24:51.778 24816 24832 E CRASH   :       #02 UnityEngine.XR.ARSubsystems.XRDepthSubsystem:Stop () <D:\Projects\XXX\Library\PackageCache\com.unity.xr.arsubsystems@2.1.1\Runtime\DepthSubsystem\XRDepthSubsystem.cs:67> 12-18 21:24:51.778 24816 24832 E CRASH   :       #03 UnityEngine.XR.ARFoundation.SubsystemLifecycleManager`2<TSubsystem_REF, TSubsystemDescriptor_REF>:OnDisable () <D:\Projects\XXX\Library\PackageCache\com.unity.xr.arfoundation@2.1.4\Runtime\AR\SubsystemLifecycleManager.cs:89>
> 12-18 21:24:51.779 24816 24832 E CRASH   :       #04 UnityEngine.XR.ARFoundation.ARPointCloudManager:OnDisable () <D:\Projects\XXX\Library\PackageCache\com.unity.xr.arfoundation@2.1.4\Runtime\AR\ARPointCloudManager.cs:55>
> 12-18 21:24:51.779 24816 24832 E CRASH   :       #05 (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
> 12-18 21:24:51.888  4492  4492 D io_stats: !@   8,0 r 73271 5406928 w 20732 1080344 d 3310 841664 f 18368 18360 iot 68540 63940 th 416268 0 0 pt 0 inp 0 0 2226.908
> 12-18 21:24:52.211  3687  3938 D WifiStateMachine: Current network is: "RubensWifi" , ID is: 2
> 12-18 21:24:52.334 24816 24832 E CRASH   : Tombstone written to: /storage/emulated/0/Android/data/XX.XX.XXX/files/tombstone_00
> 12-18 21:24:52.334 24816 24832 E CRASH   : chained_signal_handler 575 got 11
> 12-18 21:24:52.334 24816 24832 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 24832 (UnityMain)
> 12-18 21:24:52.335  3096  3096 W         : debuggerd: handling request: pid=24816 uid=10199 gid=10199 tid=24832
> 12-18 21:24:52.408 25480 25480 I FIPS_bssl: FIPS (v1.1) approved mode (1) | 25480 | pidof
> 12-18 21:24:52.465 25472 25472 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 12-18 21:24:52.465 25472 25472 F DEBUG   : Build fingerprint: 'samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU2DRC1:user/release-keys'
> 12-18 21:24:52.465 25472 25472 F DEBUG   : Revision: '8'
> 12-18 21:24:52.465 25472 25472 F DEBUG   : ABI: 'arm'
> 12-18 21:24:52.466 25472 25472 F DEBUG   : pid: 24816, tid: 24832, name: UnityMain  >>> XX.XX.XXX <<<
> 12-18 21:24:52.466 25472 25472 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
> 12-18 21:24:52.466 25472 25472 F DEBUG   :     r0 00000000  r1 00000000  r2 0001d080  r3 00000003
> 12-18 21:24:52.466 25472 25472 F DEBUG   :     r4 00000000  r5 c99cc6b8  r6 00000000  r7 e7e23e70
> 12-18 21:24:52.466 25472 25472 F DEBUG   :     r8 00000000  r9 e7fee7e8  sl 00000002  fp e7fee2e8
> 12-18 21:24:52.466 25472 25472 F DEBUG   :     ip adaa5234  sp e7fee1a0  lr ada88678  pc 00000000  cpsr 600b0010
> 12-18 21:24:52.467 25472 25472 F DEBUG   :
> 12-18 21:24:52.467 25472 25472 F DEBUG   : backtrace:
> 12-18 21:24:52.467 25472 25472 F DEBUG   :     #00 pc 00000000  <unknown>
> 12-18 21:24:52.467 25472 25472 F DEBUG   :     #01 pc 0001b674  /data/app/XX.XX.XXX-1/lib/arm/libUnityARCore.so (UnityARCore_depth_Stop+52)
> 12-18 21:24:52.468 25472 25472 F DEBUG   :     #02 pc 000092a0  <anonymous:ad85c000>

To make sure that the issue does not come from the app we also did a test build with this test project and we are getting the same issue.

Tested Environments: 
Unity 2019.1, 2019.3, 2020.1.
Different AR Foundation Versions including stable and pre-release versions.
The device is a Galaxy 7 with Android 7.0 and latest ARCore support library installed from app store.

AR Core: Release 04.12.2019 Version 1.14.191118086

The issue also happens with Galaxy 7 Edge.

**Comment by franMx** [comment]
I had lots of issues (never was able to work with) S10. Were you able to find a solution?

**Comment by jiungerich** [comment]
I can get the galaxy 7 to work if I use AR tracked image manager component but not if I spawn the image manager in script. I also if I create a runtime image library in script this seems to cause a black screen.

**Comment by mdurand42** [comment]
@rubit0 You might try this with version 4.0.0-preview.3 of AR Foundation and the ARCore package . We have addressed some issues when switching scenes.

**Comment by tdmowrer** [comment]
Is this still an issue?
