### ISSUE TITLE
Most stable arfoundation, arcore and arkit versions

### ISSUE THREAD

**Issue by marioslokas** [Unity-Technologies/arfoundation-samples#381]
Hello all,

Can anyone point out the most stable version combinations for all 3 packages? Or is it written somewhere in the docs?
I have been upgrading to all preview versions for a while now trying to locate something that isn't problematic for an urgent release of my app.

EDIT: Forgot to mention I require horizontal plane detection and tracked images for Android and iOS

**Comment by tdmowrer** [comment]
The latest verified (i.e. stable) release is 3.0 (for all 5 packages), compatible with 2019.2+.
