### ISSUE TITLE
TypeLoadException on latest ARFoundation package

### ISSUE THREAD

**Issue by marioslokas** [Unity-Technologies/arfoundation-samples#382]
The latest combination of ARFoundation, ARCore and ARKit packages causes the following error when starting up an AR scene:
`TypeLoadException: Could not resolve type with token 01000034 (from typeref, class/assembly UnityEngine.XR.ARFoundation.ARReferencePointManager, Unity.XR.ARFoundation, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Rethrow as TypeInitializationException: The type initializer for 'UnityEditor.XR.ARFoundation.ARSceneValidator' threw an exception.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnProcessScene (UnityEngine.SceneManagement.Scene scene, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:163)
UnityEditor.Build.BuildPipelineInterfaces+<OnSceneProcess>c__AnonStorey1.<>m__1 (UnityEditor.Build.IProcessSceneWithReport spp) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:387)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEditor.Build.BuildPipelineInterfaces:OnSceneProcess(Scene, BuildReport)`

The error was observed with the following packages:
ARFoundation 3.0.1
ARCore 3.0.1
ARKit 3.0.1
AR Subsystems 3.0.0
Unity 2019.2.5f1

**Comment by Goncharuk-Nikita** [comment]
Up, same issue.

**Comment by Goncharuk-Nikita** [comment]
![image](https://user-images.githubusercontent.com/30652592/72817864-c787ff00-3c6a-11ea-977f-d78e497a2189.png)
This is after upgrading to 3.0.1. You need to check all of your code with old references.

**Comment by Goncharuk-Nikita** [comment]
Need to Remove ARPointManager script from your ARSessionOrigin game object and replace it to ARAnchorManager. Also, replace ARReferencePoint to ARAnchor in your old ReferencePoint prefab.

**Comment by Goncharuk-Nikita** [comment]
After that, I also had an exception when trying to build, but I reinstalled the ARFoundation package and it worked
