### ISSUE TITLE
ARKIT does not work when building a project from unity.

### ISSUE THREAD

**Issue by wskabir123** [Unity-Technologies/arfoundation-samples#383]
I get a pink screen after building a project in Unity with AR foundation. But it works when I make a new project in Xcode and build it from there. Is anyone else experiencing the same problem? I have googled a bit and there it says the Ar Foundation requires a camera with depth which could work with AR but if it’s the case then why does it work when I use Xcode and the project has no link to UnityEngine whatsoever.

**Comment by tdmowrer** [comment]
A pink screen sounds like a missing shader. Does this happen when building the sample project in this repo, or in your own project?

**Comment by wskabir123** [comment]
Hello,

Thanks for the reply, I solved the problem by changing the gamma to linear.
It was hard to know what is being the problem.

But now it is solved, appreciate your time.


Best
Waris

**Comment by tdmowrer** [comment]
3.0 supports both gamma and linear color spaces (see [changelog](https://docs.unity3d.com/Packages/com.unity.xr.arkit@3.0/changelog/CHANGELOG.html#300-preview3---2019-09-26)). What version are you using?

**Comment by wskabir123** [comment]
Yes i have googled the issue and found ways to troubleshoot it.

It was ARKIT 3.0, but now everything works perfectly fine.


Best
Waris

**Comment by tdmowrer** [comment]
I'm glad you have a solution, but

> It was ARKIT 3.0

You're saying gamma color space does _not_ work in 3.0?

**Comment by wskabir123** [comment]
Yes I had problem using it and when I googled it, loads of people had the
same problem. But that’s for unity 2018.3 plus in my class I only had this
problem no one else. Maybe it was because of my operating system MAC. But
now i have tested it in gamma and linear and both works perfect. However I
wanted to ask if there is any opportunity for internship in unity office? I
live in Stockholm and I have talked to the Stockholm staff they had no
seats available I have even talked to Jessica Huges because if it but had
no luck then. Could I kindly ask you if you could recommend me anyone who
can I contact with and do my student internship in unity’s environment. I
have studied Virtual and augmented reality and have only worked UNITY, C#,
Xcode, swiftUi, Maya3D for more I will attach my CV and website link where
all my work samples are available.

https://wskabir.wixsite.com/wariskabir


Best
Waris Kabir

**Comment by tdmowrer** [comment]
Closing as this is no longer an issue.

Regarding internships, that's off-topic for this issues page, but I'll follow up with you separately via email.

**Comment by wskabir123** [comment]
Thank you for your email, I will be looking forward.


Best wishes,
Waris
