### ISSUE TITLE
PlaneClassification sample on Google Pixel 3 always classifies each frame as 'None'

### ISSUE THREAD

**Issue by dremond71** [Unity-Technologies/arfoundation-samples#384]
Apparently some devices can classify an image as door or floor or chair etc
according to 

https://github.com/Unity-Technologies/arfoundation-samples#planeclassification

But running this sample on my phone, the planes only get labelled as 'None'

**Comment by Berenice2018** [comment]
I experience the same on a Samsung Galaxy S10. All planes are labelled as "None", running the sample scene of this repo. I would be interested in knowing a bit more about how the classification works under the hood. I assume that the classification is done with Deep Learning/ a neural network. 

1. Does the user need a stable internet connection or is the model inference performed locally on the device? 
2. Is there any list of devices that support PlaneClassification?

**Comment by tdmowrer** [comment]
I believe plane classification currently only works on ARKit. You can query for support by interrogating the [subsystem descriptor](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.1/api/UnityEngine.XR.ARSubsystems.XRPlaneSubsystemDescriptor.html#UnityEngine_XR_ARSubsystems_XRPlaneSubsystemDescriptor_supportsClassification).

**Comment by Berenice2018** [comment]
Thanks! To everyone who will read this thread: "Plane classification is available on iOS devices with A12 or later GPU." Source: https://developer.apple.com/documentation/arkit/arplaneanchor/2990938-isclassificationsupported
