### ISSUE TITLE
Object Tracking not working.

### ISSUE THREAD

**Issue by XR-Venom** [Unity-Technologies/arfoundation-samples#386]
I am able to build and run my app on iphone 7 but it does not track object and tried sample objects also.

AR Foundation 3.1.0 preview 1
ARKit XR plugin 3.1.0 preview 1
AR Subsystems 3.1.0 preview 1
Xcode 11.3
Unity 2019.2.2f1

**Comment by tdmowrer** [comment]
There are no known issues with this feature, but it can be quite sensitive to the lighting conditions of the reference object. Have you tried [scanning](https://developer.apple.com/documentation/arkit/scanning_and_detecting_3d_objects) your own objects?
