### ISSUE TITLE
Human Segmentation Point Cloud

### ISSUE THREAD

**Issue by aqaddoumi** [Unity-Technologies/arfoundation-samples#387]
I've trying to create two RenderTextures one for PositionMap and one for ColorMap to use in VFX Graph from ARKit's:
- Human Depth Image
- Human Stencil Image
- Camera Background Image

More or less implementing what @keijiro did here but for ARKit:
https://github.com/keijiro/Rsvfx
https://github.com/keijiro/Dkvfx

Ideally, I would end up with:
- PositionMap RenderTexture that maps all the human stencil pixels to the screen/camera with x, y, depth and can work on different orientations and aspect ratios.
- ColorMap RenderTexture that maps all human stencil pixels from the camera background.

It has a lot of moving parts that I'm not very familiar with and I'm not sure what's the right approach would be.
Any ideas or steps that I should take would be appreciated!

**Comment by smxthereisonlyone** [comment]
Any update on this?

**Comment by aqaddoumi** [comment]
I found this article, however, it's only in Japanese.
https://qiita.com/yohanashima/items/dd3f1ea20fc783bbcd8c

I eventually achieved in a similar way but with a regular shader instead of a compute before I found the article, I haven't tried the approach in the article but I've looked at it and it looks very similar and I think his way is more efficient, so I would give that tutorial a go with google translate :)

**Comment by s-r-jones** [comment]
@aqaddoumi would you care to expand on your technique? Im trying to achieve a similar look and find myself going to down the compute shader rabbit hole.
