### ISSUE TITLE
Detection not working on OnePlus 6

### ISSUE THREAD

**Issue by bitfabrikken** [Unity-Technologies/arfoundation-samples#39]
I've got an app in production that seems to work just fine on most Android devices.

But I've had a report from a friend, that plane detection doesn't work on his OnePlus 6.
The marker particles never show up, it's just like a regular camera view. Had him try many different locations, good lighting, surfaces that should show marker particles. Nothing.

Have tried all other troubleshooting I could think of, including uninstalling, checking if camera works in other apps, etc. It does work in the Ikea Place app*. Also had him manually reinstall and update to latest version of ARCore with no luck.

*Update: The Ikea Place app does allow him to place something, but it does not follow with the camera. It's placed where he pointed his camera at first. So it would seem like there's some issues there too.

The app in question can be installed from [App Store](https://itunes.apple.com/ro/app/vita-copenhagen/id989131984?mt=8) or [Google Play](https://play.google.com/store/apps/details?id=dk.vita.app), in case you want to reproduce/see it.

**Build info:**
Unity: Unity 2018.2.3f1, Lightweight Render Pipeline, AR Foundation, ShaderGraph
iOS: macOS High Sierra 10.13.6, Mac mini Late 2014, Xcode 9.4.1 (9F2000)
Android: Windows 10.0.17134, min API level 24, target API 27, .NET 3.5 eq. runtime, Mono and .NET 2.0 subset, ARMv7
Other: Applied fix to get LWRP working with the camera (black camera view without it): (https://nolanscobie.com/2018/07/unity-mobile-ar-with-lwrp/

manifest.json:
```
{
  "dependencies": {
    "com.unity.package-manager-ui": "1.9.11",
    "com.unity.render-pipelines.core": "3.0.0-preview",
    "com.unity.render-pipelines.lightweight": "3.0.0-preview",
    "com.unity.shadergraph": "3.0.0-preview",
    "com.unity.textmeshpro": "1.2.4",
    "com.unity.xr.arcore": "1.0.0-preview.18",
    "com.unity.xr.arfoundation": "1.0.0-preview.17",
    "com.unity.xr.arkit": "1.0.0-preview.14",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
} 
```

**Comment by SafwanCheng** [comment]
Luckily, we're all using one plus six, and I've only tested one.The problem is as you described, and now I have it.I hope it can be solved earlier. I'm sure it can be used a month ago.It seems that some updates have been made recently.I'm just guessing. I'd like to talk to you about this.

**Comment by SumithHrtz** [comment]
Hey it's 2k19 and I am still facing this issues. Searched internet a lot and found this thread. I even made a video about it  still no help.
Link👉https://youtu.be/2JnXDThnj6s

Please help and tell me how to solve this issue bro

**Comment by kiaxseventh** [comment]
> Hey it's 2k19 and I am still facing this issues. Searched internet a lot and found this thread. I even made a video about it still no help.
> Link👉https://youtu.be/2JnXDThnj6s
> 
> Please help and tell me how to solve this issue bro

can you send me one email ?
kiarash.alinejad@gmail.com

**Comment by SafwanCheng** [comment]
Sorry, I only saw this email now. I encountered the same problem as you. It
was just that I tried ARFodt in a room where I didn’t turn on the lights at
night. This is not true. You should try the light in the open air. Good
site testing, not in the bedroom full of obstacles. To rule out the error,
you should first try ARCore's sample scenario to see if it works, and if
you can, ARFodt will not be too bad.

SumithHrtz <notifications@github.com> 于 2019年1月7日周一 20:23写道：

**Comment by tdmowrer** [comment]
This is an old thread -- is this still an issue?

**Comment by Suzee1993** [comment]
Hi All!

Sadly enough I am, still, facing this same issue. Has anyone been able to solve this yet? 

Thank you!

**Comment by SumithHrtz** [comment]
So mine was fixed last year . I had faced the same issue and I have commted for help. So here is the fix.

The problem is with the main mother board of the phone. The issue is with accelerometer and gyrosensor that mess up to cause this issue. So I went to OnePlus customer service during my warranty period and showed them this issue. They where unable to troubleshoot the problem hence the changed my board. Vola my problem was solved. The problem is a manufacturer defect I guess. I reacwd on time before my warranty was gonna ende and got the whole fix cost aka motherboard replacement for free.

**Comment by Suzee1993** [comment]
@SumithHrtz Thank you so much for your reply! You've spared me days of searching for a, non existing, solution! The warranty period for my phone has long since passed so I'll try to get my hand on a new, and better, one then :). 

Thanks again!
