### ISSUE TITLE
No TrackedPoseDriver script in 3.0.1

### ISSUE THREAD

**Issue by mistergreen** [Unity-Technologies/arfoundation-samples#392]
There is no Tracked Pose Driver in the 3.0.1 update to attach to the camera as instructed on
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/index.html

There is ARPoseDriver but doesn't have the same options as TrackedPoseDriver.

**Comment by mistergreen** [comment]
ARPoseDriver seems to replace TrackedPoseDriver.

**Comment by DavidMohrhardt** [comment]
The `TrackedPoseDriver` is a component that is exists in our `LegacyInputHelpers` package which was made an optional dependency and replaced with the `ARPoseDriver` component.  You are able to use either or to accomplish the same thing but the `TrackedPoseDriver` is a general solution for AR and VR whereas the `ARPoseDriver` is explicitly for AR.

Thanks for catching the missing documentation, we will be sure to update that!

**Comment by AdiPathak97** [comment]
Please update the documentation ASAP, my project with AR plane detection suddenly broke and I couldn't figure out the reason. Luckily came across this thread to realize that TrackedPoseDriver script on my ARCamera was nowhere to be found.

**Comment by digitalmkt** [comment]
I Just added the missing folder TrackedPoseDriver to the project and everything is working fine now.
