### ISSUE TITLE
How to spawn different prefabs for different images in ARFoudnation Image Tracking.

### ISSUE THREAD

**Issue by shubhamguptak** [Unity-Technologies/arfoundation-samples#393]
Hello Sir,
I've been trying to spawn different prefabs for differents images in ARFoundation but unable to do. Could you please tell me how should i do that.

**Comment by TheIntellify-Hardik** [comment]
hello every one , i am able to Instantiate predefine prefab on different image target that set on script , 

but my issue is i need  to instantiate object from server and set position and perfect scale on image target. 


My issue is : 
Prefab scale : (1f,1f,1f)

tracked image scale is different on base of Ratio , so my prefab is not look perfect on Image target.


is there any solution ?

**Comment by tdmowrer** [comment]
> I've been trying to spawn different prefabs for differents images in ARFoundation but unable to do. Could you please tell me how should i do that.

Each reference image has a unique GUID and you can provide each one with a string name. You could spawn different prefabs based on the either of these (the string name might be easier).

**Comment by tdmowrer** [comment]
@TheIntellify-Hardik 

> My issue is :
> Prefab scale : (1f,1f,1f)
> tracked image scale is different on base of Ratio , so my prefab is not look perfect on Image target.

Sorry, I don't understand your question. Could you provide screen shots or example code of what you're trying to do?
