### ISSUE TITLE
How to re-scan the image marker again without resetting the arsession.

### ISSUE THREAD

**Issue by shubhamguptak** [Unity-Technologies/arfoundation-samples#394]
Hello Sir, 
I am trying to re-scan the image marker again without losing the ground plane detection or resetting the ar session can you please tell me how to do this.
Regards 
Shubham

**Comment by tdmowrer** [comment]
Sorry, I'm not sure what you mean by "re-scan" the image marker. Once an image is detected, it should be updated regularly as long as it is visible. Could you describe your use case a bit more?
