### ISSUE TITLE
HumanBody 3D tracking

### ISSUE THREAD

**Issue by DKWIPL** [Unity-Technologies/arfoundation-samples#396]
I want to Instantiate the 3D model of a human after the user detected. But after that, I don't want my 3D model to move with the user, I want my model to stay there only where the user was detected.

Can some can tell me how can I achieve that?

**Comment by DKWIPL** [comment]
Very first thing, why no one is replying to this forum?
It's almost 28 Days now, but no reply.

I solved this.

Now i have to change the model at the runtime. Like for example I have 2 human 3D models. I want to switch bwtween them at run time. How to do that?

If possible please reply on this asap.

**Comment by tdmowrer** [comment]
> I want to Instantiate the 3D model of a human after the user detected. But after that, I don't want my 3D model to move with the user, I want my model to stay there only where the user was detected.

Subscribe to the human body manager's `humanBodiesChanged` event. When a new body is added, [create an anchor](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARAnchorManager.html#UnityEngine_XR_ARFoundation_ARAnchorManager_AddAnchor_Pose_) at that position and then add your model as a child of the anchor.

> Now i have to change the model at the runtime. Like for example I have 2 human 3D models. I want to switch bwtween them at run time. How to do that?

The same way you normally switch between any models in Unity: enable one and disable the other. If that does not work, please provide more details on what you are trying to achieve.

**Comment by DKWIPL** [comment]
Hi, @tdmowrer thanks fo the reply.

Now I want to add the multiple human models and want to give them to move as the user does.
But in this, I want to display only one human model at a time and want to change them in realtime. 

Like for example, If one Human 3D model is making the movement as the user does and I want that model to change at run time with another model.

Is this possible to do? If Yes, then how?

Because I tried to enable and disable the models but they are not moving with the user movements. But if I am applying only one model then they are working fine.

**Comment by mdurand42** [comment]
@DKWIPL Your question is probably better asked on the Unity Forums where other users can share solutions for how to make their experiences richer. The API we expose for 3D human tracking is something we plan to improve over time but appears to be working as expected. Closing.
