### ISSUE TITLE
ARKit Remote? 

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#397]
Whatever happened to ARKit remote?

**Comment by chris-o3h** [comment]
Yes. Curious...

**Comment by tdmowrer** [comment]
See https://forum.unity.com/threads/ar-remoting-simulation.720575/

**Comment by chris-o3h** [comment]
Thanks for sharing @tdmowrer

**Comment by tobeglad** [comment]
Check out this plugin:
https://stampedegames.net/ar-foundation-remote.html
