### ISSUE TITLE
Plane detection not working with HoloLens 1

### ISSUE THREAD

**Issue by JendrikDerWeise** [Unity-Technologies/arfoundation-samples#398]
Hi,
I build the sample from the git repo on Android and everything seems fine. When I build for HoloLens 1, the plane detection is not working, not even the UI iis showing up.

Is there anything to activate, when building for HL to get the plane detection to work?
The app is not asking for getting camera permissions - maybe thats the problem? 

Unity 2019.3.0f5
ARFoundation 2.1.4
ARCore XR Plugin 2.1.2
Windows XR Plugin 2.0.3

I tried also ARFoundation 3 with suitable plugins. But then the app doesn´t start on HL.

I appreciate your help :)
Jendrik

**Comment by DavidMohrhardt** [comment]
ARFoundation does not support planes on Hololens 1.  The feature set for Hololens 1 is limited to Meshing, Input, and Anchors.
