### ISSUE TITLE
Linear Color Space for Camera Background

### ISSUE THREAD

**Issue by blanxdev** [Unity-Technologies/arfoundation-samples#4]
I just started using the foundation framework to see how it works out.

During testing I wondered how to use a proper linear camera background shader instead of the default one. Seems like the background image is to bright when setting the player settings to linear.

I tried to plug the arkit camera shader into a material and use this as override, but this gives me black background.

Is there a sample shader available that will work?

**Comment by Leiong** [comment]
I was having a similar issue to this .

**Comment by tdmowrer** [comment]
Linear color space is now supported in 3.0.0-preview.3
