### ISSUE TITLE
Vertical Planes UVs are stretched

### ISSUE THREAD

**Issue by MohammedAlsayedOmar** [Unity-Technologies/arfoundation-samples#40]
The horizontal planes are fine but the vertical ones seem to have some issues with the UVs

![ar foundation samples](https://user-images.githubusercontent.com/26679355/44535267-e55dd700-a6f9-11e8-980d-8c46514ce7e2.jpg)

I used the "FeatheredPlaneScene" scene and changed the shader of the ARPlane's material to the one in this [tutorial](https://haptic.al/arcore-101-fa6f93d4c00).

If there is a quick fix on my side please let me know.

Thank you

**Comment by MohammedAlsayedOmar** [comment]
Forgot to add these details
Unity version 2018.2.3f1
AR Foundation 1.0.0-preview.17
ARCore XR Plugin 1.0.0-preview.18
ARKit XR Plugin 1.0.0-preview.14

**Comment by tdmowrer** [comment]
The feathered plane scene was just updated; you might want to try pulling latest. The feathered plane is also just an example -- does this happen with the default plane available from the GameObject menu in ARFoundation?

**Comment by MohammedAlsayedOmar** [comment]
After pulling the latest changes, the default plane is working fine but the feathered plane still have the same UVs problem. Reverting back to the original shader and everything is working fine!

Default Plane

![Default Plane](https://user-images.githubusercontent.com/26679355/44549346-19002780-a721-11e8-9524-2451de307743.jpg)

Feathered Plane (with the shader from the tutorial mentioned above)
![Feathered plane with tutorial shader](https://user-images.githubusercontent.com/26679355/44549713-3bdf0b80-a722-11e8-80d5-67b08d56df6f.jpg)

Feathered Plane (with the feathered plane shader)
![Feathered plane with it's shader](https://user-images.githubusercontent.com/26679355/44550461-a8f3a080-a724-11e8-9ac8-9ce0468035e5.jpg)

Thanks a lot!
