### ISSUE TITLE
ARSubsystemManager.cameraSubsystem in ARFoundation 3.0.0

### ISSUE THREAD

**Issue by WajanaPiromnok** [Unity-Technologies/arfoundation-samples#400]
I am updating an AR Foundation Unity application from AR Foundation 1.0 to AR Foundation 3.0

I found this problem from these line : 

var cameraSubsystem = ARSubsystemManager.cameraSubsystem;

what would it migration from ARSubsystemManager.cameraSubsystem in AR Foundation 1.0 to 3.0.0

Thanks

**Comment by tdmowrer** [comment]
Looks like maybe you found the answer already. For future readers, [the documentation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/index.html) includes a couple of migration guides.

The `ARSubsystemManager` was removed and subsystems can be access from their managers, the `ARCameraManager` component in this particular case.
