### ISSUE TITLE
Orange cubes appear during plane finding

### ISSUE THREAD

**Issue by thePostFuturist** [Unity-Technologies/arfoundation-samples#401]
Updated to iOS 13.3.1, now during plane finding, from what I assume to be a space segmentation phase, I'm getting orange boxes appear along with the planes. 

The tracking also appears to be worse. I can't downgrade iOS, and I'm at ARKit, ARFoundation, and ARSubsystems 3.1.0 preview 4.

**Comment by tdmowrer** [comment]
> now during plane finding, from what I assume to be a space segmentation phase, I'm getting orange boxes appear along with the planes.

The SimpleAR scene uses people occlusion, and the coarseness of the result might manifest itself this way if, for example, you put your hand (or other body part) near the detected plane. Hard to diagnose without more information -- could you post a screen shot?

> The tracking also appears to be worse.

Is the only change you made to upgrade to iOS 13.3.1? From what version did you upgrade?

**Comment by thePostFuturist** [comment]
13.3.0. 

The culprit were the realtime environment probes. I no longer have the orange cubes, and the tracking seems to have improved.  I'll mark this as at least the core as functional.
