### ISSUE TITLE
Post Processing v2 stack used on ARCamera impedes tracking

### ISSUE THREAD

**Issue by thePostFuturist** [Unity-Technologies/arfoundation-samples#405]
Even though none of this is in the samples, I'm going to file this here. PPv2 attached to a camera, even if a volume is not present greatly impedes tracking.

**Comment by tdmowrer** [comment]
What exactly do you mean by "impedes tracking"?

**Comment by vburovIntuitive** [comment]
Makes tracking worse. For example, the planes start to swim upon detection.

Tangentially, I have an update for a partial work-around. I attached a child camera to the ARCamera, attached the PPv2 to the child, and matched the FoV of the ARCamera in runtime.

**Comment by tdmowrer** [comment]
That sounds like the projection matrix is wrong. The ARCameraManager sets this each frame, but it sounds like the PPv2 may also be affecting it. Could you [submit a bug](https://unity3d.com/unity/qa/bug-reporting) with a project that reproduces the issue and post the bug tracking number here?

**Comment by thePostFuturist** [comment]
Haven't submitted the bug project yet, but I have tried this suggestion (you are in this thread):

https://forum.unity.com/threads/arfoundation-post-processing-stack-tracking-drift.593872/#post-5030378

The drift remains, only now the video background now fails to refresh every now and then.

**Comment by tdmowrer** [comment]
> now the video background now fails to refresh every now and then.

Can you be more specific? Does the pass through video pause or jitter? Is this still an issue? If so, please log a bug and post the case ID here.

**Comment by thePostFuturist** [comment]
On ARF4.1, I can now use PPv2 on the same camera, no issues.
