### ISSUE TITLE
how to switch on the flash light during AR session ?

### ISSUE THREAD

**Issue by shubhamguptak** [Unity-Technologies/arfoundation-samples#406]
Hi,

I am trying to switch on the flash light of the camera during the AR session.
Nevertheless, I was trying to switch it in anyway using Camera2 with the following code:
Tested on Xiaomi POCO F1 
   public void ToggleAndroidFlashlight()
    {

        if (camera == null)
        {
            AndroidJavaClass cameraClass = new AndroidJavaClass("android.hardware.Camera");
            camera = cameraClass.CallStatic<AndroidJavaObject>("open", 0);
            if (camera != null)
            {
                cameraParameters = camera.Call<AndroidJavaObject>("getParameters");
                cameraParameters.Call("setFlashMode", "torch");
                camera.Call("setParameters", cameraParameters);
            }
        }
        else
        {
            cameraParameters = camera.Call<AndroidJavaObject>("getParameters");
            string flashmode = cameraParameters.Call<string>("getFlashMode");
            if (flashmode != "torch")
                cameraParameters.Call("setFlashMode", "torch");
            else
                cameraParameters.Call("setFlashMode", "off");

            camera.Call("setParameters", cameraParameters);
        }
    }

    void ReleaseAndroidJavaObjects()
    {
        if (camera != null)
        {
            camera.Call("release");
            camera = null;
        }
    }
        }

**Comment by tdmowrer** [comment]
What happens when you run this script? I imagine the call to ```camera = cameraClass.CallStatic<AndroidJavaObject>("open", 0);``` will fail as ARCore has exclusive access to the camera during an ArSession.

**Comment by kyzylmonteiro** [comment]
@augmentedxreality was this issue solved? 
@tdmowrer is there a way around it?

**Comment by mdurand42** [comment]
According to Google it is not possible to enable the flashlight while running ARCore.
https://github.com/google-ar/arcore-android-sdk/issues/356

**Comment by yosun** [comment]
What about for iOS?

**Comment by yosun** [comment]
https://github.com/glazunov/MyAwesomeFlashlight/tree/main also android has allowed flashlight access as of 2021 at least

**Comment by ZFHung** [comment]
any update on this?
