### ISSUE TITLE
how to set camera config?

### ISSUE THREAD

**Issue by franMx** [Unity-Technologies/arfoundation-samples#409]
Hi, my device doesn't support some of the modes in samples / CameraImage. (Modes 0-2 are not working, 3-5 are). I made a hard-coded index in script that sets camera to a working known mode, but would like to make it dynamic.

What is the best way to set camera to a working configuration?

**Comment by DavidMohrhardt** [comment]
The supported camera configurations can be queried via [GetConfigurations(Allocator)](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARCameraManager.html).

**Comment by franMx** [comment]
Hi David, thanks, I'm able to retrieve supported configurations, however for some reason it wasn't really working on phone.

My main concern is I haven't been able to get AR on samsung s10 phone, so thought this might have been the problem - unfortunately haven't had luck on getting it to work properly.

**Comment by DavidMohrhardt** [comment]
Would you be able to post your package manifest?

**Comment by franMx** [comment]
sure, this is it:

`{
  "dependencies": {
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.ext.nunit": "1.0.0",
    "com.unity.ide.rider": "1.1.0",
    "com.unity.ide.vscode": "1.1.3",
    "com.unity.package-manager-ui": "2.2.0",
    "com.unity.test-framework": "1.0.13",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.1.0",
    "com.unity.ugui": "1.0.0",
    "com.unity.xr.arcore": "3.1.0-preview.1",
    "com.unity.xr.arfoundation": "3.1.0-preview.1",
    "com.unity.xr.arsubsystems": "3.1.0-preview.2",
    "com.unity.xr.legacyinputhelpers": "2.0.6",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}`

**Comment by tdmowrer** [comment]
> My main concern is I haven't been able to get AR on samsung s10 phone

There was an issue specific to a few devices, the s10 among them, that was fixed in [3.0.0-preview.6](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/changelog/CHANGELOG.html#fixes-1). ARFoundation 3 is now verified, so please use version 3.1.3 or update to 4.0 and see if that fixes the issue.

**Comment by franMx** [comment]
Hi, I tried using version 4, still doesn't work.

**Comment by tdmowrer** [comment]
Let's recap what "doesn't work" exactly.

> my device doesn't support some of the modes in samples / CameraImage. (Modes 0-2 are not working, 3-5 are)

What modes (resolution, frame rate) do not work? What does "not work" mean exactly? (Black screen?)

> I haven't been able to get AR on samsung s10 phone

Nothing works at all on the s10? What happens when you try to run the SimpleAR sample from this repo? Can you provide the logcat output here?

**Comment by mdurand42** [comment]
Closing due to lack of response.
