### ISSUE TITLE
Crash on LG G6

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#41]
Hi, I've been experiencing strange crashes on an LG G6. It'll sometimes work and then other times it just crashes before or sometimes just after starting the camera feed, logs attached.

[arprestolog.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/2342757/arprestolog.txt)
[fulllog.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/2342758/fulllog.txt)

**Comment by tdmowrer** [comment]
Thanks for the report and the logs. Could you submit a full [bug report](https://unity3d.com/unity/qa/bug-reporting) too?

**Comment by nilsk123** [comment]
The project is in production and I'm afraid I can't share it. For what its worth I think the example project should be enough to reproduce the issue, I see the same behaviour on other ARCore apps (Ikea).


I will try to find some time to create a small reproduction project in the next couple of days.

**Comment by tdmowrer** [comment]
That'd be great. Is it specific to the LG G6?

**Comment by nilsk123** [comment]
Yes, it is specific to the LG G6.

**Comment by Ursanon** [comment]
@nilsk123 
Do you still have this problem?
After last ARCore update (1.7 i think..) this issue is no more.
