### ISSUE TITLE
Raycast doesn't hit TrackableType.Face

### ISSUE THREAD

**Issue by aidanwolf** [Unity-Technologies/arfoundation-samples#413]
1) Using FaceMeshPrefab.prefab with MeshCollider component added
2) ARRaycastManager.Raycast(ray, s_Hits, TrackableType.Face) returns no hits

**Comment by tdmowrer** [comment]
Neither ARCore nor ARKit SDKs support raycasting against faces. If you put a mesh collider on the ARFace prefab, you can use the [Physics.Raycast](https://docs.unity3d.com/ScriptReference/Physics.Raycast.html) API.
