### ISSUE TITLE
ScreenPointToRay is laggy on AR Session camera

### ISSUE THREAD

**Issue by thePostFuturist** [Unity-Technologies/arfoundation-samples#417]
Hello,

I'm using the `ScreenPointToRay` function to cast a ray from a position on screen to a 3D object, and then using `LineRenderer` to draw a line between those two objects.

In the AR Session camera, when I move the phone, the `LineRenderer` drawing doesn't update fast enough and lags. In my case, I have a `RectTransform` with an Image, to the center pivot of which the `LineRenderer` receives its first point ( the second is the 3D object ). The Line Position 0 is behind the Image, but due to the lag, the origin appears outside the Image.

Furthermore, applying this same technique in regular 3D Space, or Vuforia Model Tracking does not lag.

I'm setting positions via `SetPositions`, and tried running this in `Update` and `LateUpdate` with no resolve.

**Comment by tdmowrer** [comment]
The camera's transform is updated just before rendering, so if you are using `Camera.ScreenPointToRay` in an `Update` method, you will be a frame off. Subscribe to the [onBeforeRender](https://docs.unity3d.com/ScriptReference/Application-onBeforeRender.html) callback and perform your logic there. The camera's transform will have been updated for the current frame.

**Comment by thePostFuturist** [comment]
10/10 solution, thanks much
