### ISSUE TITLE
HoloLens Issues with Unity 2019.3, AR Foundation 3.0.1, AR Subsystems 3.0.0

### ISSUE THREAD

**Issue by julianparismorgan** [Unity-Technologies/arfoundation-samples#419]
**[Update 3/25]** After more research, the issue I was running into was that in order to use iOS / Android / HoloLens through AR Foundation 3 on Unity 2019.3, we need a package that works on Unity 2019.3 with the following packages:

AR Foundation : 3.0.1
AR Subsystems : 3.0.0
Windows XR Plugin : TBD

====
**[Original post - it is slightly confusing, I recommend you read my follow-ups below for more clarity, or look at the image I attached]**
Hi there - I'm testing out ARFoundation + Windows XR on HoloLens 1 (without MRTK) and am having an issue where I can't see any content. Instead, I just see black with a white cursor. 

I have created a simple test scene based off of the SimpleAR scene in this repo. When I use ARFoundation 3.1.0-preview.4 and WindowsMR 3.0.1-preview3, I don't see any content. My test [project is here in the `arfoundation-3-testing` branch](https://github.com/julianparismorgan/ARFoundation_HoloLens/tree/arfoundation-3-testing). And this is part of the manifest:
```
"com.unity.xr.arfoundation": "3.1.0-preview.4",
"com.unity.xr.management": "3.1.0-preview.2",
"com.unity.xr.windowsmr": "3.0.1-preview.3",
"com.unity.xr.legacyinputhelpers": "2.0.6",
```

But, based on the comment [here](https://forum.unity.com/threads/ar-foundation-on-hololens-without-mrtk.725201/#post-5422326), when I downgrade to ARFoundation 2.1.4 and WindowsMR 2.0.3, I am able to see my cubes (I haven't tested other functionality, but I can see them). You can see this in [`master` of the repo](https://github.com/julianparismorgan/ARFoundation_HoloLens/tree/arfoundation-3-testing). And here is part of the manifest:
```
"com.unity.xr.arfoundation": "2.1.4",
"com.unity.xr.arsubsystems": "2.1.1",
"com.unity.xr.management": "3.0.5",
"com.unity.xr.windowsmr": "2.0.3",
```

This is what my project looks like:

![image](https://user-images.githubusercontent.com/1396242/75397381-83ac9900-58ab-11ea-9de1-b37e22987f62.png)

Let me know if I should move this to the Unity forums instead, thanks!

Update: Just to call it out - my goal is to move our project to 2019.3.1f1 and ARFoundation 3.0.1.

**Comment by julianparismorgan** [comment]
I've also tested with the following, and am still just seeing a black screen with a white cursor.

```
"com.unity.xr.arfoundation": "3.0.1",
"com.unity.xr.legacyinputhelpers": "2.0.6",
"com.unity.xr.management": "3.0.6",
"com.unity.xr.windowsmr": "3.0.1-preview.3",
```

Here's a [branch with this set up.](https://github.com/julianparismorgan/ARFoundation_HoloLens/tree/arfoundation-3.0.1-testing)

**Comment by mdurand42** [comment]
Thanks for reporting this. I will check it out ASAP.

**Comment by julianparismorgan** [comment]
Thanks @mdurand42. So I looked more into the Windows XR 3.0.1-preview3 package, and I believe it wasn't working because it's for Unity 2020.1. I see that in it's package.json (I was able to use it because I added it to my project by modifying the manifest.json). This is the package.json:

```
  "name": "com.unity.xr.windowsmr",
  "displayName": "Windows XR Plugin",
  "version": "3.0.1-preview.3",
  **"unity": "2020.1",**
  "unityVersion": "0a15",
```

Based on that, I tried testing with ARFoundation 3.0.1, AR Subsystems 3.0.0, and  Windows XR 2.0.3. When I do this, I get errors because of the rename from XRReferencePoint to XRAnchor ([AR Subsystems changelog](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.1/changelog/CHANGELOG.html)) ([AR Foundation changlog](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/changelog/CHANGELOG.html)), along with many other errors (I think because of the subsystems interface changing?):

![image](https://user-images.githubusercontent.com/1396242/75595840-d4a2c580-5a42-11ea-88b4-d19b1b1b2e7d.png)

```
"com.unity.xr.arfoundation": "3.0.1",
"com.unity.xr.arsubsystems": "3.0.0",
"com.unity.xr.management": "3.0.5",
"com.unity.xr.windowsmr": "2.0.3",
```

I also tried using Windowx XR to 2.0.4-preview.3, which is the most recent Windows XR package that supports 2019.3.1f1, but it also has errors (similar to those above).

**Comment by julianparismorgan** [comment]
Hey @mdurand42. any update? I wrote out a diagram of how I understand things, and it seems like the solution that we need is a Windows XR package that supports ARSubsystems 3.0.0 and Unity 2019.3.

![issue](https://user-images.githubusercontent.com/1396242/76467476-ee2f0000-63a6-11ea-8320-6b5345c34cd1.png)

**Comment by mdurand42** [comment]
> Hey @mdurand42. any update? I wrote out a diagram of how I understand things, and it seems like the solution that we need is a Windows XR package that supports ARSubsystems 3.0.0 and Unity 2019.3.
> 
> ![issue](https://user-images.githubusercontent.com/1396242/76467476-ee2f0000-63a6-11ea-8320-6b5345c34cd1.png)

Hi Julian-

You are indeed correct that the Windows XR plugin 3.0.0 requires Unity 2020.1. That is not something we will be able to change, unfortunately.

I was able to confirm that HoloLens support works on Unity 2020.1 with the following verified packages:
    AR Foundation : 3.0.1
    AR Subsystems : 3.0.0
    Windows XR Plugin : 3.0.0

Also confirmed with these packages:
    AR Foundation : 3.1.0-preview.8
    AR Subsystems : 3.1.0-preview.8
    Windows XR Plugin : 3.0.1-preview.3

**Comment by julianparismorgan** [comment]
Thanks @mdurand42 for looking into this! Yes, Unity 2019.3 works with these packages:

AR Foundation : 2.1.4
AR Subsystems : 2.1.1
Windows XR Plugin : 2.0.3

But we are moving to ARFoundation 3.0.1, which requires AR Subsystems 3.0.0. But the Windows XR Plugin doesn't support Unity 2019.3 and AR Subsystems 3.0.0, so we **can't use AR Foundation 3.0.0 and Windows XR Plugin together on Unity 2019.3**. 

The high-level ask here is to keep the Windows XR Plugin dependencies in line with AR Foundation dependencies so that they can be used together.

**Comment by tdmowrer** [comment]
Each release of Unity includes a set of _verified_ packages. When a package is verified for a version of Unity, it refers to a set of packages that are known to work together for that version of Unity.

ARFoundation 2.1 is verified for Unity 2019.3
ARFoundation 3.0 is verified for Unity 2020.1

ARFoundation 3.0 also _happens_ to be compatible with 2019.3, which I believe is the source of confusion in this thread.

> AR Foundation : 3.0.1
> AR Subsystems : 3.0.0
> Windows XR Plugin : TBD
> The high-level ask here is to keep the Windows XR Plugin dependencies in line with AR Foundation dependencies so that they can be used together.

They are in line. There is a set of packages that work together in 2019.3 (ARFoundation 2.1 + Windows XR Plugin 2.0) and a set that works together in 2020.1 (ARFoundation 3.0 + Windows XR Plugin 3.0). Some packages can work with multiple Unity versions, but of course, not all packages will work across all versions of Unity.
