### ISSUE TITLE
Black Screen and no camera permission

### ISSUE THREAD

**Issue by ikaro88** [Unity-Technologies/arfoundation-samples#42]
Hi i tried arfoundation 1 month ago and it worked just 1 time.
But since than i try different time with different version of unity, but the app do not ask me the camera permission and i not show me the camera background
no error on debug...

i tried to allow permission in app setting but nothing change, any idea why it appen?﻿

**Comment by tdmowrer** [comment]
If your bundle identifier is the same, then you won't get prompted for camera permission after granting it the first time.

Things to try:

-  If on Android, could you check the logcat output
```
adb logcat Unity:* Unity-ARCore:* ArPresto:* *:S
```
- Try `Debug.LogFormat`ing the `ARSubsystemManager.systemState` (this would tell you if, for example, the device is unsupported).

What device are you using?

**Comment by ikaro88** [comment]
I am using a Galaxy A6, and arcore works fine.

i not understend wy but with unity 2018.1.1. now seems work

**Comment by tdmowrer** [comment]
This is difficult to diagnose without any other information. Is there any logcat output (using the command I mentioned in my previous post)?

It would also be helpful to [submit a bug](https://unity3d.com/unity/qa/bug-reporting) with a project that reproduces the issue.

**Comment by ikaro88** [comment]
@tdmowrer the project is exactly the arfoundation-samples, i just download it and opened with different version of unity, switced platform and build it on my phones

**Comment by craftercis** [comment]
> @tdmowrer the project is exactly the arfoundation-samples, i just download it and opened with different version of unity, switced platform and build it on my phones

Do you have found the problem? I have now the same after building my app there is no camera permission pop-up and the screen is black

**Comment by mashai** [comment]
Same issue, here's what I get when running the logcat command

09-18 13:04:46.872 10025 10046 I ArPresto: ArPresto_initialize
09-18 13:04:47.016 10025 10046 I ArPresto: ArPresto_setCameraTextureName
09-18 13:04:49.813 10025 10046 I ArPresto: ArPresto_setEnabled
09-18 13:04:49.822 10025 10046 I ArPresto: ArPresto::Got install result.
09-18 13:04:49.851 10025 10046 I ArPresto: ArPresto::Got permission result.
09-18 13:04:51.220 10025 10046 I ArPresto: ArPresto::Session created.
09-18 13:04:51.245 10025 10046 E ArPresto: ArPresto::SetConfiguration failed to deserialize Augmented Image database with status -19.

**Comment by tdmowrer** [comment]
That output suggests things are generally working. My guess is the phone may think it is unsupported.

Did you try Try `Debug.LogFormat`ing the `ARSubsystemManager.systemState`?

**Comment by sridevipavithra** [comment]
Hi! How do I handle Camera Permission declined in ARFoundation? I see the error being logged in Xcode and it seems to be in API level. But again, the session state seems to be in Initialising. Is there anyway to handle those errors inside ARFoundation itself?

**Comment by tdmowrer** [comment]
> Hi! How do I handle Camera Permission declined in ARFoundation? I see the error being logged in Xcode and it seems to be in API level. But again, the session state seems to be in Initialising. Is there anyway to handle those errors inside ARFoundation itself?

You can check whether camera permission was granted with this API: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_permissionGranted
