### ISSUE TITLE
can not build to android with unity 2019.3.3f1

### ISSUE THREAD

**Issue by setiahadi83** [Unity-Technologies/arfoundation-samples#420]
my package :
ARFoundation 3.0.1
ARCore XR Plugin 3.0.1

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x00275] in <9a184ab867bb42c296d20ace04f48df3>:0 

any idea to fix this??

**Comment by tdmowrer** [comment]
What are the errors?

**Comment by tdmowrer** [comment]
I've just built this repo for Android with Unity 2019.3.4f1 (released today) without issue. Let me know if you are still having issues, and please paste the 2 errors reported by the build process.
