### ISSUE TITLE
ARPlane detection 

### ISSUE THREAD

**Issue by ArCoreDxb** [Unity-Technologies/arfoundation-samples#422]
Hi,

I have just downloaded the new release of the samples.

Tried the ARplan detection , classifying them and changing colors based on what type of plane has been detected.

Using unity 2019.3.0f6 , deployed on Galaxy s10+

all I get is none text shown regardless of what even plane is being detected.

I still don't understand what is the following used for

namespace UnityEngine.XR.ARSubsystems
{
    public enum PlaneClassification
    {
        None = 0,
        Wall = 1,
        Floor = 2,
        Ceiling = 3,
        Table = 4,
        Seat = 5,
        Door = 6,
        Window = 7
    }
}

Really need help on this one to understand what is going on and why i'm getting one only.

**Comment by tdmowrer** [comment]
Classification is only supported on iOS 13 and later. ArCore (Android) does not yet support this feature.
