### ISSUE TITLE
IOS Build does not show 3d models

### ISSUE THREAD

**Issue by chethansai** [Unity-Technologies/arfoundation-samples#423]
I have a working project in android build.When I have changed build to ios and opened through xcode and install .the 3d object arent deployed.

**Comment by tdmowrer** [comment]
Sorry, that is too vague to troubleshoot, but it doesn't sound like an AR issue per se. What exactly do you mean by "the 3d object arent deployed"? Code and/or a screen recording would be helpful. If you think this is a bug, please [report an issue](https://unity3d.com/unity/qa/bug-reporting) with a minimal project that reproduces the issue.
