### ISSUE TITLE
Anchor's position does not sync during collaboration session

### ISSUE THREAD

**Issue by AytoMaximo** [Unity-Technologies/arfoundation-samples#424]
Hello! I'm not sure if it's an issue or just my misunderstanding.  

I can't find any difference between AnchorManager and ARParticipantManager implementations, however when I'm moving my second device its position is updating everywhere, but changing an anchor's position influences only one device (where I'm calling this object's repositioning).

So, is there a way to update anchor's transform in collaborative session? 

Thank you!

**Comment by tdmowrer** [comment]
> I can't find any difference between AnchorManager and ARParticipantManager implementations,

The difference is in the subsystem whose lifetime they control. Different functionality is enabled at the native level.

> but changing an anchor's position influences only one device (where I'm calling this object's repositioning).

You cannot change an anchor's position. We can't stop you from changing the transform of the `GameObject` which represents it, but that won't have any effect, so the behavior you are seeing is expected.

What are you trying to accomplish by changing the anchor's position?

**Comment by AytoMaximo** [comment]
> What are you trying to accomplish by changing the anchor's position?

Thank you for your explanations! 
I want to create a moving object for all the participants of collaborative session. I understand that I can't sync such things like Animation clips and other Unity stuff, however I see the ARParticipant anchor moving with the player and want the same thing to my own custom anchors. 
I guess this way should have a higher performance and easier implementation than using back-end.

**Comment by necron4a** [comment]
Hi, i think this task able to deside by Reality Kit. It the part of ARKit. It can sync transform, physics... @tdmowrer do you planning to add this functional to AR Foundation?

**Comment by tdmowrer** [comment]
> a host player put a ball (anchor) in the center of the room, other players see this ball at the same point after callibration and then all of them can start to kick it. If one player added force to the ball and changed its position, everyone will see the new ball's positioning and react it.

You can use the anchor to find a spot that both devices can agree upon, and then send positions relative to that. So, in this example, you would create an anchor, wait for the other device to find the same anchor, then spawn a ball at the anchor (but separate from it). Each frame, one device can send the other the ball's position _relative to the anchor_, and the other device can update the ball's position accordingly.

> this task able to deside by Reality Kit. I guess it the part of ARKit. It can sync transform, physics... @tdmowrer do you planning to add this functional to AR Foundation?

It's not part of the ARKit API -- that is something Reality Kit is doing on top of ARKit. We have no plans to provide similar functionality, but I will make a feature request for this.

**Comment by Nishat11** [comment]
Hi @tdmowrer , i am using AR Foundation 5 with ARKit 5. I am looking for a multiuser functionality using ARFoundation and AR collaboration.  Is there any way I can sync game-object's (Spawn/placed game-object in an AR environment) transform to all my connected app instances? If not then, is there any plan or other solution available to make a multiuser/ trackable game object in an AR environment?

**Comment by tdmowrer** [comment]
I no longer work at Unity, and my comment above from March 10, 2020 is still relevant as far as I know. Basically, a collaborative session can help you find a shared reference point, but networking and state synchronizing is beyond the scope of AR Foundation. You could look into [Unity's Multiplayer Networking](https://docs-multiplayer.unity3d.com/).

You might also want to create a new GitHub issue (closed issues are less likely to get attention) and ask for a sample that shows how to do this.
