### ISSUE TITLE
How to add images to a Mutable Runtime Reference Library. with ARTrackedImageManager.

### ISSUE THREAD

**Issue by bhosaleT** [Unity-Technologies/arfoundation-samples#426]
Hey guys I am trying to create a reference image library at runtime. 
I have a static Dictionary which is storing the a bunch of image textures from a different scene of the game.  I have a seperate AR Scene and when I go this AR Scene , I am adding a ARTrackedImageManager component and then I want to add all the images from the aforementioned Dictionary to the referenceImageLibrary. 
I have some questions regarding this.
1. When do I actually set the ARTrackedImageManager.referenceLibrary ? before adding the images or after adding the images.
2. Where can I find some examples of adding images to the reference library?
3. When using "ScheduleAddImageJob" do I need to wait for this job to end?

I am adding a snippet of the code I have written so far. when I try to logout the count of images in the mutable library it logs 0.

`trackedImageManager = gameObject.AddComponent<ARTrackedImageManager>();

        RuntimeReferenceImageLibrary runtimeLibrary = trackedImageManager.CreateRuntimeLibrary();

        MutableRuntimeReferenceImageLibrary mutableLibrary = runtimeLibrary as MutableRuntimeReferenceImageLibrary;

        // Static dictionary of images taken by the user from the rest of the game.
        foreach (Texture2D texture in CreateTrackingImages.trackingImagesList)
        {

            // if that texture exists.
            if (texture)
            {
               var addImageJob =  mutableLibrary.ScheduleAddImageJob(texture, texture.name, 0.1f);

                while (!addImageJob.IsCompleted) {
                    Debug.Log("Adding images");
                }

                addImageJob.Complete();
            }
        }

        if (mutableLibrary != null) {
            Debug.Log("Mutable library with images was created " + mutableLibrary.count);
            trackedImageManager.referenceLibrary = mutableLibrary;
        }
        

        trackedImageManager.enabled = true;

        trackedImageManager.trackedImagesChanged += OnTrackedImagesChanged;`

**Comment by tdmowrer** [comment]
Saw that you closed this issue, but future readers might benefit from these answers:

> 1. When do I actually set the ARTrackedImageManager.referenceLibrary ? before adding the images or after adding the images.

It should not matter. You can even set the `referenceLibrary` after adding but before the job completes.

> 2. Where can I find some examples of adding images to the reference library?

There is some example code in the [documentation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/tracked-image-manager.html#adding-new-reference-images-at-runtime).

> 3. When using "ScheduleAddImageJob" do I need to wait for this job to end?

Nope, you don't need to do anything (the `addImageJob.Complete();` in the code you posted is unnecessary and probably undesirable). JobHandles have an [IsCompleted](https://docs.unity3d.com/ScriptReference/Unity.Jobs.JobHandle.IsCompleted.html) property, which can be useful if you want to know when the image is added to the library, but you don't need to do anything with it.

**Comment by danielng21** [comment]
I had tried using this codes and the one mentioned in documentation, with and without .Complete();, IsComplete return true, yet the mutableLibrary.count always return 0. Hope somebody found this post and could give me a direction on how to solve this problem or what may cause this problem. (tested on android device)

**Comment by tdmowrer** [comment]
I believe this can happen if ARCore does not accept your image, e.g., because it does not contain enough features to perform image tracking.

**Comment by danielng21** [comment]
@tdmowrer You are right! Just not a good set of images for tracking to begin with. Change another set, with only 1-2 images out of 6 failed to add occasionally.

**Comment by kdpkke** [comment]
> I had tried using this codes and the one mentioned in documentation, with and without .Complete();, IsComplete return true, yet the mutableLibrary.count always return 0. Hope somebody found this post and could give me a direction on how to solve this problem or what may cause this problem. (tested on android device)

I'm having this exact same problem, and I'm using QR Codes as images. 
Using ARFoundation 4.2.0 preview and Unity 2020.2.2.f1
What could be the problem?

**Comment by KirillKuzyk** [comment]
> > I had tried using this codes and the one mentioned in documentation, with and without .Complete();, IsComplete return true, yet the mutableLibrary.count always return 0. Hope somebody found this post and could give me a direction on how to solve this problem or what may cause this problem. (tested on android device)
> 
> I'm having this exact same problem, and I'm using QR Codes as images.
> Using ARFoundation 4.2.0 preview and Unity 2020.2.2.f1
> What could be the problem?

Please check the [AddReferenceImageJobState.status](https://docs.unity.cn/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.AddReferenceImageJobState.html#UnityEngine_XR_ARSubsystems_AddReferenceImageJobState_status) after AddReferenceImageJobState is finished (only available in AR Foudatuon >= 4.1). If the status is ErrorInvalidImage, it means your image is not suitable for Image Tracking.

**Comment by kdpkke** [comment]
> > > I had tried using this codes and the one mentioned in documentation, with and without .Complete();, IsComplete return true, yet the mutableLibrary.count always return 0. Hope somebody found this post and could give me a direction on how to solve this problem or what may cause this problem. (tested on android device)
> > 
> > 
> > I'm having this exact same problem, and I'm using QR Codes as images.
> > Using ARFoundation 4.2.0 preview and Unity 2020.2.2.f1
> > What could be the problem?
> 
> Please check the [AddReferenceImageJobState.status](https://docs.unity.cn/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.AddReferenceImageJobState.html#UnityEngine_XR_ARSubsystems_AddReferenceImageJobState_status) after AddReferenceImageJobState is finished (only available in AR Foudatuon >= 4.1). If the status is ErrorInvalidImage, it means your image is not suitable for Image Tracking.

Thank you for your input. the status returns "ErrorUnknown". The documentation doesn't help too much in this regard...

**Comment by yynakar** [comment]
Hello everyone
I'm having trouble with MutableRuntimeReferenceImageLibrary. I'm using this coroutine
` private IEnumerator AddAllImagesToMutableReferenceImageLibraryAR(MutableRuntimeReferenceImageLibrary mutableLibrary)
    {
        if (m_TrackedImageManager.descriptor.supportsMutableLibrary)
        {
            Texture2D textureImg = Resources.Load("qr1") as Texture2D;
            JobHandle job;
            if (textureImg.isReadable)
            {
                string name = "qrcode1";
                job = mutableLibrary.ScheduleAddImageJob(textureImg, name, 0.1f);
                yield return new WaitUntil(() => job.IsCompleted);
            }
        textureImg = Resources.Load("Vaseline-Logo") as Texture2D;
            if (textureImg.isReadable)
            {
                name = "qrcode2";
                job = mutableLibrary.ScheduleAddImageJob(textureImg, name, 0.1f);
                yield return new WaitUntil(() => job.IsCompleted);
            }

            m_TrackedImageManager.enabled = true;
            m_TrackedImageManager.referenceLibrary = mutableLibrary;
            m_TrackedImageManager.trackedImagesChanged += OnTrackedImagesChanged;
            
        }
    }`

and then I try to scan the added images with this 
` private void UpdateTrackedImages(IEnumerable<ARTrackedImage> trackedImages)
    {
        var trackedImage =
            trackedImages.FirstOrDefault(x => x.referenceImage.name == "qrcode1");
        var trackedImage2 =
            trackedImages.FirstOrDefault(x => x.referenceImage.name == "qrcode2");


        if (trackedImage)
        {
            CorrectMsg.SetActive(true);
            WrongMsg.SetActive(false);

        }
        if (trackedImage2)
        {
            WrongMsg.SetActive(true);
            CorrectMsg.SetActive(false);
        }

    }
`

When I had a non-rutime library I had no trouble with it scanning the images. No, I'm not even sure if the images are added, cause the count comes as 0.

Does anyone have any suggestions?

thank you in advance

**Comment by shb3014** [comment]
> > > > I had tried using this codes and the one mentioned in documentation, with and without .Complete();, IsComplete return true, yet the mutableLibrary.count always return 0. Hope somebody found this post and could give me a direction on how to solve this problem or what may cause this problem. (tested on android device)
> > > 
> > > 
> > > I'm having this exact same problem, and I'm using QR Codes as images.
> > > Using ARFoundation 4.2.0 preview and Unity 2020.2.2.f1
> > > What could be the problem?
> > 
> > 
> > Please check the [AddReferenceImageJobState.status](https://docs.unity.cn/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.AddReferenceImageJobState.html#UnityEngine_XR_ARSubsystems_AddReferenceImageJobState_status) after AddReferenceImageJobState is finished (only available in AR Foudatuon >= 4.1). If the status is ErrorInvalidImage, it means your image is not suitable for Image Tracking.
> 
> Thank you for your input. The status for the first image returns "ErrorUnknown", for the second one is "None". The same goes if I switch the code of the two images. The documentation doesn't help too much in this regard...
> 
> `
> 
> ```
> private void Awake()
> {
>     libraryAR = arManager.CreateRuntimeLibrary();
>     if (libraryAR is MutableRuntimeReferenceImageLibrary mutableLibrary)
>     {
>         mutableLibrary = arManager.CreateRuntimeLibrary() as MutableRuntimeReferenceImageLibrary;
> 
>         StartCoroutine(AddAllImagesToMutableReferenceImageLibraryAR(mutableLibrary));
>     }
> }
> 
> private IEnumerator AddAllImagesToMutableReferenceImageLibraryAR(MutableRuntimeReferenceImageLibrary mutableLibrary)
> {   
>     Texture2D textureImg = Resources.Load("totemReal") as Texture2D; 
>     Debug.LogError("texture: " + textureImg);
>     AddReferenceImageJobState job;
>     if (textureImg.isReadable)
>     {
>         string name = "qrcode1";
>         job = mutableLibrary.ScheduleAddImageWithValidationJob(textureImg, name, 200f);
>         yield return new WaitUntil(() => job.jobHandle.IsCompleted);
>     }
> 
>     textureImg = Resources.Load("qrCodeTest") as Texture2D;
>     if(textureImg.isReadable)
>     {
>         name = "qrcode2";
>         job = mutableLibrary.ScheduleAddImageWithValidationJob(textureImg, name, 200f);
>         yield return new WaitUntil(() => job.jobHandle.IsCompleted);
>     }
>     Debug.LogError("mutableLibrary.count = " + mutableLibrary.count);
> 
>     arManager.referenceLibrary = mutableLibrary;
> } `
> ```
> 
> EDIT: I solved this changing the third parameter of ScheduleAddImageWithValidationJob to 1f and moving the code from the Awake method to the Start method and putting it inside a coroutine that has a yield return null at the beginning

Same issue here. Solved thanks to your solution. The key is to put a yield return null at the begining. I think the reason is that ScheduleAddImageWithValidationJob should only be called after the first frame when awake and possibly some other initilization is completed.
