### ISSUE TITLE
Anchor Manager Error

### ISSUE THREAD

**Issue by Spiraseven** [Unity-Technologies/arfoundation-samples#427]
I am getting the below error when trying to add an anchor to the anchor manager. I am using 3.0.1 and ARCore.

InvalidOperationException: Anchor manager has no subsystem. Enable the manager first.
UnityEngine.XR.ARFoundation.ARAnchorManager.AddAnchor (UnityEngine.Pose pose) (at Library/PackageCache/com.unity.xr.arfoundation@3.0.1/Runtime/AR/ARAnchorManager.cs:66)
ImageTrackingAnchor.Update () (at Assets/Scripts/ImageTrackingAnchor.cs:30)

The ARAnchorManager is attached and enabled on the ARSessionOrigin

**Comment by tdmowrer** [comment]
Not having a subsystem can also mean your device is not supported. What device are you getting this on, and are there any other errors or warnings in logcat?

**Comment by Spiraseven** [comment]
Ah i see, I was not getting any anchors to appear on android and so just ran the application in the Unity Editor on Windows to see if anything came up and saw this error. It is possible this error only shows up on Windows when running in Unity. This means I am having a separate error on Android with anchors if this is the case.

**Comment by tdmowrer** [comment]
This is the expected behavior when running in the Editor, as there is no subsystem available. (A subsystem is the platform implementation.)
