### ISSUE TITLE
ARCore build fails using Gradle 3.6.1

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#429]
Hello,

We are working on integrating unity as a library in an existing native Android application.

The native application uses the following Gradle dependencies:

> +        classpath 'com.android.tools.build:gradle:3.6.1'
> +        distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

The gradle build fails and throws these errors:

[log.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/4339069/log.txt)

Steps to reproduce:

 - Create new unity project
 - Import arfoundation and arcore packages
 - Set player settings to IL2CPP
 - Export to gradle settings
 - Open project in android studio
 - Update Gradle version
 - Attempt to build

A zip containing the Unity project from which the exports were made:

https://s3-eu-west-1.amazonaws.com/byardev.mysmilez.nl/samples/UnityTestProject.zip

A zip containing one working and one failing gradle export:

https://s3-eu-west-1.amazonaws.com/byardev.mysmilez.nl/samples/GradleProjects.zip

**Comment by tgobbens** [comment]
Same issue over here

**Comment by tdmowrer** [comment]
We are investigating the proper fix for this. In the meantime, there is a [workaround](https://github.com/Unity-Technologies/uaal-example/issues/16).

**Comment by nilsk123** [comment]
> We are investigating the proper fix for this. In the meantime, there is a [workaround](https://github.com/Unity-Technologies/uaal-example/issues/16).

The workaround is to downgrade the Gradle dependency? That's not really feasible, the native project has tons of other dependencies.

**Comment by NetDevoGames** [comment]
I was having the same issue and found another workaround which I mentioned [here](https://github.com/Unity-Technologies/uaal-example/issues/16#issuecomment-628738686)

**Comment by mdurand42** [comment]
A proper fix will be released soon for 2020.2 verified packages and backports for 2020.1 and 2019.3 verified packages are also in flight. I will update this issue when the packages containing the fix are published.

**Comment by mdurand42** [comment]
The 4.0 ARCore package has been published and includes support for Gradle 3.6.1.
