### ISSUE TITLE
Crash when starting ARCore on Samsung S8 related to permissions

### ISSUE THREAD

**Issue by GeddesJ** [Unity-Technologies/arfoundation-samples#43]
Hello,
I'm having an issue with getting ARFoundation to work on Android (a Samsung S8) in that it crashes when it tries to ask for camera permissions. (It's not entirely clear to me why it needs to ask for camera permissions, since according to the Unity manual permissions are supposed to be set at install). Part of the design of my app requires being able to toggle AR on and off within the same scene, and I have noticed that ARFoundation can be a bit finicky when used this way. However I have no issues building and running on IOS. 

Below is the relevant section of the log:
```
09-07 16:12:53.431: E/mono(16776): Unhandled Exception:

09-07 16:12:53.431: E/mono(16776): UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.AndroidJNISafe.CheckException () [0x00091] in <923839a08fb841a3aae5c73693b946f8>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00011] in <923839a08fb841a3aae5c73693b946f8>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x002d6] in <923839a08fb841a3aae5c73693b946f8>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.AndroidJavaObject.CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00001] in <923839a08fb841a3aae5c73693b946f8>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x0001d] in <923839a08fb841a3aae5c73693b946f8>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00020] in <923839a08fb841a3aae5c73693b946f8>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x00007] in <923839a08fb841a3aae5c73693b946f8>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.XR.ARCore.ARCorePermissionManager.get_permissionsService () [0x00014] in <57129082ff43417e8b08c23e3f1db4f7>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.XR.ARCore.ARCorePermissionManager.IsPermissionGranted (System.String permissionName) [0x0000c] in <57129082ff43417e8b08c23e3f1db4f7>:0 

09-07 16:12:53.431: E/mono(16776):   at UnityEngine.XR.ARCore.ARCorePermissionManager.RequestPermission (System.String permissionName, System.Action2[T1,T2] callback) [0x00011] in <57129082ff43417e8b08c23e3f1db4f7>:0 
```
This behaviour is displayed if I build with mono and IL2CPP. I have a suspicion it could have something to do with my player settings because deploying the samples project displays the permissions and works correctly. The only difference I can see between the player settings in the sample project is that it is set to use .Net 3.x (Which won't work for my purposes, and I can't see how this would be the problem). And the text under Scripting Define Symbols is "UNITY_POST_PROCESSING_STACK_V2" - which I have no idea what this means.

Attached are the player settings for my project. Also attached is the full log from the session, but I couldn't really find anything else of note.

![projectsettings1](https://user-images.githubusercontent.com/24245184/45204588-0f4ef600-b2c3-11e8-9e6f-f84a7320e8a0.PNG)

![projectsettings2](https://user-images.githubusercontent.com/24245184/45204695-605eea00-b2c3-11e8-8698-2c449b48ac1f.PNG)

[ProjectSettings.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/2359995/ProjectSettings.txt)

[samsungfulllog.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/2359961/samsungfulllog.txt)

**Comment by tdmowrer** [comment]
Is this still an issue?
