### ISSUE TITLE
Image Tracking 

### ISSUE THREAD

**Issue by Bentoon** [Unity-Technologies/arfoundation-samples#430]
Hi All, I have image tracking working fine, 

But I'm trying to have multiple images each trigger their own objects 
...and w the AR foundations you can only assign One object to be triggered by the AR Tracked image Manager (and you can only have one instance of this script on each camera)...

I have done a few Google searches to no avail ... unless I hack in to the code but it still has limited functionality 

Thanks !
~be

**Comment by DavidMohrhardt** [comment]
One way to accomplish what you want to is to have a "Content Factory" that hooks into the [ARTrackedImageManager.OnTrackablesChanged](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_OnTrackablesChanged_System_Collections_Generic_List_UnityEngine_XR_ARFoundation_ARTrackedImage__System_Collections_Generic_List_UnityEngine_XR_ARFoundation_ARTrackedImage__System_Collections_Generic_List_UnityEngine_XR_ARFoundation_ARTrackedImage__) callback to instantiate the content you want for each image.

**Comment by Bentoon** [comment]
thank you @DavidMohrhardt  for a swift reply !

**Comment by tdmowrer** [comment]
From an `ARTrackedImage`, you can get its [referenceImage](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARTrackedImage.html#UnityEngine_XR_ARFoundation_ARTrackedImage_referenceImage), which contains a [string](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.0/api/UnityEngine.XR.ARSubsystems.XRReferenceImage.html?q=xrreferenceimage#UnityEngine_XR_ARSubsystems_XRReferenceImage_name) name that you assigned it in the Editor, as well as an automatically generated [Guid](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.0/api/UnityEngine.XR.ARSubsystems.XRReferenceImage.html?q=xrreferenceimage#UnityEngine_XR_ARSubsystems_XRReferenceImage_guid).

You can use either of these to identify the image that was detected.
