### ISSUE TITLE
人物遮挡（AROcclusionManager）

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#433]
I try to update the verson of ARfundation3.0，but i can't find the （AROcclusionManager）in this package

**Comment by tdmowrer** [comment]
From what version did you "upgrade"? The occlusion manager was not added until [3.1.0-preview.1](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/changelog/CHANGELOG.html#new).

**Comment by Arytes** [comment]
> 您从哪个版本“升级”？直到[3.1.0-preview.1](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/changelog/CHANGELOG.html#new)才添加遮挡管理器。

![WechatIMG1](https://user-images.githubusercontent.com/47556504/77526072-fa49b000-6ec4-11ea-8696-fafd74b90a1e.jpeg)
i use unity 2019.3.2

**Comment by Arytes** [comment]
and i see the Editor of Unity2019.3.2，just can update the verson 3.0.1

**Comment by tdmowrer** [comment]
Sorry, I'm not sure what you are asking.

If you want to use the `AROcclusionManager`, you need to use at least 3.1.0-preview.1 (the latest is 3.1.0-preview.8).
