### ISSUE TITLE
Black Screen - No camerafeed on Android 7.0 - Working on Android 8.0

### ISSUE THREAD

**Issue by nicolasfischoeder** [Unity-Technologies/arfoundation-samples#434]
Dear support, dearest developers,

I have encountered a bug which leads to the ARCamera not working and thus responding with a black camera background. This occured when using an Android device of version 7.0. I tried several things like switching between Unity-versions and different versions of ARFoundation and ARCore XR Plulgin in the package manager. Nothing helped. However updating my phone (Samsung Galaxy S7) to Android 8.0 resolved the issue. During googling for a solution I encountered some people who faced the same issue and came up with the same solution. Appearantly I am not the only one facing this. Since Android 7.0 is regarded as a minimum for ARCore, but yields these issues with ARFoundation, a fix would be more than welcome :); AS 7.0 is still wide spread.

Here is my setup:
Android 7.0 (working with 8.0)
Unity version 2019.3.3f
ARCore XR Plugin 2.1.2 and 3.0.1
ARFoundation 2.1.4 and 3.0.1

**Comment by tdmowrer** [comment]
Could you send me the device fingerprint for your S7? You can get it using `adb`:
```
adb shell getprop ro.build.fingerprint
```

**Comment by hesselmonk** [comment]
I have the exact same issue, but using another unity project with ARFoundation 4.0.0 and URP works just fine. Tested the AR samples project with 3.0.1 and 4.0.0

the device fingerprint:
`samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQL5:user/release-keys`

**Comment by tdmowrer** [comment]
> I have the exact same issue, but using another unity project with ARFoundation 4.0.0 and URP works just fine. Tested the AR samples project with 3.0.1 and 4.0.0
> 
> the device fingerprint:
> `samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQL5:user/release-keys`
> 
> edit: I can confirm that, when switching the examples project to the URP, the camera will work (if you don't forget to enable the ARCamera render feature)

To confirm, by "exact same issue", you mean it works with Android 8, but not Android 7?

**Comment by hesselmonk** [comment]
Sorry, with the exact same I meant that the camera feed stays black on Android 7.0 (I can't update my testing device now to verify that 8.0 it would've worked).

**Comment by tdmowrer** [comment]
Thanks for the info. It's unlikely this is specific to ARFoundation and is probably an issue with ARCore. To confirm, you can try to reproduce the issue using [Google's ARCore SDK for Unity](https://github.com/google-ar/arcore-unity-sdk).

**Comment by tdmowrer** [comment]
Closing as not actionable by Unity.
