### ISSUE TITLE
ARKit 3.5 Scene Reconstruction

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/arfoundation-samples#435]
I understand that ARKit 3.5 has only been available for a few days, that Unity is always on top of these updates and rolls them out as soon as possible, and that there are more urgent things going on in the world right now, and time and resources are limited.

But I thought I would ask if there is an ETA on when the new Scene Reconstruction features will be added to AR Foundation?
https://developer.apple.com/documentation/arkit/arconfiguration/scenereconstruction

**Comment by sam598** [comment]
If the backlog is getting full, this would be another great reason to open source the ARKit library for AR Foundation.
https://github.com/Unity-Technologies/arfoundation-samples/issues/190

**Comment by tdmowrer** [comment]
Please see https://forum.unity.com/threads/arkit-3-5.855262/

**Comment by sam598** [comment]
Thanks for the update @tdmowrer 

@mdurand42 I believe this issue is still open since the update has not been released. Thanks.

**Comment by mdurand42** [comment]
Please follow the progress on this feature via the forum link that @tdmowrer linked previously.

**Comment by sam598** [comment]
Hi @mdurand42 I have been checking that link but it has not been updated since the 27th of last month. Is there a further update?

**Comment by sam598** [comment]
Any update on this or open sourcing the ARKit portion of the API? There are still some missing features that I would like to add for my own projects, but can't as the native session is locked down.

**Comment by mdurand42** [comment]
> Any update on this or open sourcing the ARKit portion of the API? There are still some missing niche features that I would like to add, but can't as the native session is locked down.

Hi Sam-

We are actively working on meshing and hope to have that feature in the community's hands soon. 

Regarding the locked down concern: Are you aware that you can access the native session pointer and call ARKit methods? https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@2.1/api/UnityEngine.XR.ARSubsystems.XRSessionSubsystem.html
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/extensions.html?_ga=2.142866741.1433101387.1586818146-2015064373.1516139569


-Best,
 Mike

**Comment by doukasd** [comment]
> Please follow the progress on this feature via the forum link that @tdmowrer linked previously.

There is not much to follow, it's just an announcement that has not been updated in over a month.
