### ISSUE TITLE
3.1 Samples: In "Simple AR" scene, cubes are not placed when tapping

### ISSUE THREAD

**Issue by fedeali90** [Unity-Technologies/arfoundation-samples#436]
Using latest version of AR Foundation Samples 3.1 branch, in Unity 2019.3.5f1, using Universal Render Pipeline.
After building and installing the "Simple AR" scene on my iPad Pro 2nd gen with latest iOS 13, the AR Camera Background works, and I can also see yellow dots representing detected Cloud Points. But is seems it cannot detect any planar surface, because I can spawn cubes when tapping on the image of the floor or tables.

**Comment by tdmowrer** [comment]
Have you [upgraded your shaders](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.0/manual/upgrading-your-shaders.html) for Universal RP?

**Comment by tdmowrer** [comment]
I'll close this issue for now, but feel free to reopen it if upgrading your shaders didn't solve the problem.
