### ISSUE TITLE
Broken samples

### ISSUE THREAD

**Issue by marwie** [Unity-Technologies/arfoundation-samples#437]
Missing Camera Manager on UIManager.cs in SampleUXScene
![image](https://user-images.githubusercontent.com/5083203/78019343-d1f00480-734f-11ea-9975-5ec38c5bf5c8.png)

PlaceMultipleObjectsOnPlane.cs ONLY supports touch (therefor only works if I install DeviceSimulator and use that package instead, this is inconsistent for other samples tho and nowhere mentioned). This is also SampleUXScene
![image](https://user-images.githubusercontent.com/5083203/78019368-e502d480-734f-11ea-97fa-0c5e13b6a789.png)

**Comment by tdmowrer** [comment]
Thanks for reporting! I've fixed the missing camera manager.

> PlaceMultipleObjectsOnPlane.cs ONLY supports touch

That's true, but most of the samples only do something interesting on device. Is this different from other samples?

**Comment by soraryu** [comment]
@tdmowrer please don't assume that just because Unity is not providing an official way to use that in Editor people are not trying :) And in my experience yes, for other samples it works.

**Comment by marwie** [comment]
@tdmowrer thanks for the reply. It's just that samples are very inconsistent (some scenes support touch, some dont, some have only touch...)

There is another issue in SampleUXScene 
![image](https://user-images.githubusercontent.com/5083203/78182930-5d0fee00-7467-11ea-9930-d66e195324d0.png)

**Comment by tdmowrer** [comment]
> some scenes ... have only touch

I'm not really sure what you mean. For example, the `PlaceMultipleObjectsOnPlane` script looks like this:

```csharp
if (Input.touchCount > 0)
{
    Touch touch = Input.GetTouch(0);

    if (touch.phase == TouchPhase.Began)
    {
        if (m_RaycastManager.Raycast(touch.position, s_Hits, TrackableType.PlaneWithinPolygon))
        {
```csharp

Even if you replaced touch with mouse input, you would not get a raycast from the raycast manager unless the underlying subsystem detected an AR plane, which only happens on device, no?

> some scenes support touch, some dont

Which scenes do _not_ support touch?

> There is another issue in SampleUXScene

What is the issue? Some scripts are reused between different scenes. Not all properties are used by all scenes.

**Comment by marwie** [comment]
The issue is a nullreference exception because of the missing reference.

**Comment by tdmowrer** [comment]
> The issue is a nullreference exception because of the missing reference.

Can you post the exception message? I just ran it on Android and do not get an exception.

**Comment by marwie** [comment]
Yes of course. The exception happens in the editor tho.

```UnassignedReferenceException: The variable m_Arrow of LightEstimation has not been assigned.
You probably need to assign the m_Arrow variable of the LightEstimation script in the inspector.
LightEstimation.OnEnable () (at Assets/Scripts/LightEstimation.cs:94)
```

**Comment by tdmowrer** [comment]
Interesting. It's not a `NullReferenceException`. In fact, there is a null check for `arrow` already:
```csharp
arrow?.gameObject.SetActive(false);
```

But it looks like there is special Editor-only logic that sees this as an unchecked reference (even though it isn't). That's new to me, but easy to fix in the script.

**Comment by marwie** [comment]
oh yeah, right. Haven't seen that message before as well. Interesting

**Comment by soraryu** [comment]
@tdmowrer I think this is a case of Unity null overload doing weird things. 
You shouldn't use arrow?, use if(arrow) instead. That's a Unity speciality ;)
https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/

**Comment by tdmowrer** [comment]
Yep, I ultimately arrived at that same blog post. TIL.
