### ISSUE TITLE
No reflection from enviroment and it is black 

### ISSUE THREAD

**Issue by kingkimohero69** [Unity-Technologies/arfoundation-samples#438]
Hi everyone,
   I am using Arfoundation 3.0.1 with Universal render pipeline and get a black reflection when using metallic in material whenever i increases metallic near 1, using android mi 9T to be specified,
Real environment probe does not work in android i think so i tried to disable it and used probe near my object and used baked lightmapping but it is still black.
I do not know what makes it like that.

**Comment by DavidMohrhardt** [comment]
Can you please post your Unity version, URP package version, and did you update your shaders https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html

**Comment by kingkimohero69** [comment]
yeah i did all that, unity :2019.3.0f3 
URP:7.1.6

**Comment by kingkimohero69** [comment]
Solved,Thank you

**Comment by tdmowrer** [comment]
What was the solution?

**Comment by mr-austinmiller** [comment]
@kingkimohero69 what was your solution to this issue?

**Comment by Mashimaro7** [comment]
Dude, it's so rude to just be like "Solved, thanks" and not tell anyone what the solution was lol
