### ISSUE TITLE
ARTrackedImagesChangedEventArgs doesn't properly work. ARCORE

### ISSUE THREAD

**Issue by AdrianGodlewski** [Unity-Technologies/arfoundation-samples#439]
I'm having an issue with **ARTrackedImagesChangedEventArgs arg** not properly working. I want to accomplish the same effect as this guy did in his tutorial:
https://www.youtube.com/watch?v=cWEhMlN_bSk&list=PLQMQNmwN3FvzLN-8moCKmZb00gr7sdcrZ&index=8    --> minute 22:00 exactly for the effect (for every tracked image he displayed the image's name)

I'm using ARcore, this guy had been using ARkit.

The problem is with that eventArgs.removed never gets called. I have read Your issues repo and I have found some answers, for example:
- https://github.com/Unity-Technologies/arfoundation-samples/issues/365
- https://github.com/Unity-Technologies/arfoundation-samples/issues/261

As **mdurand42** replied: 

> Update: We confirmed with Google today that the ARCore API assumes that augmented images are static in the environment so once they are recognized successfully they will always appear in the list of anchors until the session is reset. This means that AR Foundation will never report that a tracked images is removed on ARCore-enabled devices nor will a tracked image's tracking state be reported as None.

So the question is how can i solve this? I want my app to recognize specific image, for example "cat image" and then tell the user "HEY THIS IS CAT IMAGE THAT YOU WERE LOOKING FOR". And yeah, that works, but after the image is out of sight it still keeps saying "HEY THIS IS CAT IMAGE THAT YOU WERE LOOKING FOR". It looks like eventArgs.added works, but eventArgs.removed doesn't. It just remembers that image as a static field -> I want it dynamic, so when the image is out of sight it should lose track of it. 
If I'm tracking two images, I can't display the first image's name after i recognize the second one, cause it is already in stage "added". I assume that I just have to remove it.

Here is my code:
https://pastebin.com/5aqvMTup

I understand that there were already few issues around this, but I still don't understand how to get around this problem. **Clossing a session and then opening it?**
Any help would be highly appreciated.

**Comment by tdmowrer** [comment]
As @mdurand42 says, ARCore does not remove images. However, an [ARTrackedImage](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARTrackedImage.html)'s [tracking state](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARTrackable-2.html#UnityEngine_XR_ARFoundation_ARTrackable_2_trackingState) will change to [TrackingState.Limited](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.0/api/UnityEngine.XR.ARSubsystems.TrackingState.html) when the image is not actively being tracked (for example, if it is no longer in visible to ARCore). You should be able to use the tracking state to drive the logic you want.

**Comment by AdrianGodlewski** [comment]
**Firstly, I'm very thankful for Your answer!**
I tried to apply Your advice to my code, but it doesn't seem to work. It seems like TrackingState is **None** for the whole time.
I added few lines to my code (I know it looks terrible):
https://pastebin.com/bXdczHTz
In lines 20, 36,55 and 67 You can see the changes. 

When I have used an "if" statement with TrackingState.None it seemed like it was "none" for the entire app runtime. 
Do I have to add any extras in my Unity inspector or am I just doing something wrong? How do I use this?
I'm sorry if I'm asking silly questions, I'm kinda new to Unity and c# stuff.

Greetings

**Comment by tdmowrer** [comment]
The image tracking sample in this repo [hides images whose trackingState is `TrackingState.None`](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/ImageTracking/TrackedImageInfoManager.cs#L80-L94). Does that sample work for you?

**Comment by AdrianGodlewski** [comment]
Thank You for Your response again.
This sample worked for me, thanks alot! If I could, let me ask 2 last questions:
**1)** `var canvas = trackedImage.GetComponentInChildren<Canvas>(); `--> I don't understand this line of code. If i get it right, `trackedImage` object is one of the images we track (for example Rafflesia in the sample You have sent me) and "Tracked Image Prefab" is a child, right? If i'm correct, then how is the "Tracked Image Prefab" in Unity Inspector made as a child of trackedImage? (Screen below)
![image](https://user-images.githubusercontent.com/43793163/78364358-9a868f80-75bd-11ea-9a53-829b90d8870c.png)
In this example "ImageInfoPrefab" is a child of any trackedImages? Sorry, i'm abit confused.

**2)** Is there any way to check app runtime in Unity? For instance: when you see the tracked image, You could Debug it in the Unity console. I always Build and Run it on my phone, which is connected via USB.

Greetings!

**Comment by tdmowrer** [comment]
> **1)** `var canvas = trackedImage.GetComponentInChildren<Canvas>(); `--> I don't understand this line of code. If i get it right, `trackedImage` object is one of the images we track (for example Rafflesia in the sample

There is documentation [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/tracked-image-manager.html) and [here](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.0/manual/image-tracking.html). To summarize:

There are `XRReferenceImage`s (the images to search for) and `ARTrackedImage`s (the images that are actually detected in the physical environment).

The `XRReferenceImageLibrary` is a collection of reference images to look for. You set this up in the Editor.

The `TrackedImagePrefab` is the prefab that gets instantiated any time on of the images in the reference library is detected. These only exist at runtime. The "Tracked Image Prefab" is whatever you want it to be, but it will at least have an `ARTrackedImage` component on it (if it doesn't already, ARFoundation adds one after instantiation).

In the example scene, the prefab has a `Canvas` component on it:
![Screen Shot 2020-04-03 at 9 17 34 AM](https://user-images.githubusercontent.com/4934281/78382807-42836500-758c-11ea-8b31-5fc605ae5e9e.png)

This is so that we can overlay some text on top of the image. That line of code in the sample is just setting up the canvas and its child `Text` component.

> **2)** Is there any way to check app runtime in Unity?

Do you mean run the sample in the Editor? Not currently, but we are working on a remoting feature that will allow you to stream data from the device into the Editor.

**Comment by AdrianGodlewski** [comment]
Hey, thanks again for the answer! Great explanations!

>  The "Tracked Image Prefab" is whatever you want it to be, but it will at least have an ARTrackedImage component on it (if it doesn't already, ARFoundation adds one after instantiation).

So any time, we detect an image in the physical environment, Unity puts this image (the ARTrackedImage) as the parent of Tracked Image Prefab, hope i got it right. Please correct me if I'm wrong.

> Do you mean run the sample in the Editor? Not currently, but we are working on a remoting feature that will allow you to stream data from the device into the Editor.

That is exactly what i meant. 

You're such a great guy. You helped me alot! 
Greetings

**Comment by tdmowrer** [comment]
> So any time, we detect an image in the physical environment, Unity puts this image (the ARTrackedImage) as the parent of Tracked Image Prefab, hope i got it right. Please correct me if I'm wrong.

No, it instantiates your prefab, checks whether it has an `ARTrackedImage` on it, and adds one if necessary. If the prefab is `null`, then it creates an empty `GameObject` with an `ARTrackedImage` component.

All trackables are parented to a special `Trackables` GameObject in the ARSessionOrigin hierarchy. This GameObject is created at runtime and can be accessed via script. Documentation [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARSessionOrigin.html).

**Comment by AdrianGodlewski** [comment]
Thank You again for Your answer. Please, don't hate me for dumb questions :(

`var canvas = trackedImage.GetComponentInChildren<Canvas>();` 

As Unity documentation states GetComponentInChildren:
> Returns the component of Type type in the GameObject or any of its children using depth first search.

So the trackedImage must be a parent of our canvas. Means that ARTrackedImage is instantiated here: 
![image](https://user-images.githubusercontent.com/43793163/78458925-6e4e3a00-76b5-11ea-962b-a30336480369.png)
**For this instance "between" ImageInfoPrefab and PlaneParent.** 
So everytime we detect our tracked image, then prefab with ARTrackedImage gets instantiated with the hierarchy that i have given You above? Am I right?

Greetings!

**Comment by tdmowrer** [comment]
> So the trackedImage must be a parent of our canvas.

Correct.

> Means that ARTrackedImage is instantiated here...For this instance "between" ImageInfoPrefab and PlaneParent.

No. That hierarchy is a hierarchy of `GameObject`s. The `ARTrackedImage` is a type of `MonoBehaviour` which exists _on_ a `GameObject`. The ARTrackedImageManager will first instantiate the prefab, then add an `ARTrackedImage` _component_ to the `GameObject` if it does not already have one. In this case, it will be added to the `GameObject` called `ImageInfoPrefab`.

**Comment by AdrianGodlewski** [comment]
Thank You for Your patience and answers.  Guess I'll have to read up more about MonoBehaviours.  I got everything working and I understand it.

Do You have any code samples to instantiate different 3D models for different images? For example: instantiate a cube when trackedimage ==[name] , else instantiate sphere, etc.

![image](https://user-images.githubusercontent.com/43793163/78642466-12e99b00-78b3-11ea-9ff1-31e3f3a53bce.png)

![image](https://user-images.githubusercontent.com/43793163/78642106-79ba8480-78b2-11ea-94b8-49ae8e17d44f.png)



As You can see above, I deleted the "Tracked Image Prefab" and made up my gameobjects array. I also try to instantiate them.

I'm trying to code that like this, but this doesn't work as expected. I have been searching of the optimal solution on Unity forum/issues etc. There are several answers, but nothing seems to work well for me.

Could you please help me? 

Greetings!

**Comment by AdrianGodlewski** [comment]
Small update:
Guess I have got it working. 
Steps which I did:

**1)** Created a prefab with empty gameobject and called it "Parent". Added 3 different 3D objects (those objects that i want to spawn) to "parent". All set to "inactive".
![image](https://user-images.githubusercontent.com/43793163/78681052-89ef5580-78ec-11ea-9526-f5c12b6aeacc.png)


**2)** Added this prefab to "Tracked Image Prefab" in the Inspector.
![image](https://user-images.githubusercontent.com/43793163/78681196-b3a87c80-78ec-11ea-9708-583786d36fe4.png)


**3)** And here is my piece of code: (osehero, Rafflesia and Logo are my image names in the ReferenceImageLibrary)
![image](https://user-images.githubusercontent.com/43793163/78682725-a68c8d00-78ee-11ea-922e-2399f19a4450.png)

______________________________________________________________________

**Is this a correct approach to multiple objects spawning? Or is this inefficient?**
     

Greetings!

**Comment by tdmowrer** [comment]
That will work, though my suggestion would be to instantiate completely different prefabs based on the reference image name rather than putting them all into a single prefab. If you want them to move with the tracked image, then just make them children of the `ARTrackedImage`'s `Transform`. There's a variant of [`Instantiate`](https://docs.unity3d.com/ScriptReference/Object.Instantiate.html) that supports parenting.

**Comment by AdrianGodlewski** [comment]
Sorry Tim. I'm quite confused with instantiating. Can't make it properly work. Here's my piece of code:

![image](https://user-images.githubusercontent.com/43793163/78818175-8df6a280-79d4-11ea-8b69-5a0d3a387cc4.png)

And here is my inspector window:

![image](https://user-images.githubusercontent.com/43793163/78818261-af578e80-79d4-11ea-8b72-57a41dcbbc46.png)

I also tried following this guy:
https://www.youtube.com/watch?v=iM0ghkvsRos&list=PLQMQNmwN3FvzCWfvCvq2AYh1CFnTlv2Es&index=21

and I also tried this:
https://forum.unity.com/threads/ar-foundation-multiple-tracked-image-managers.697625/

Nothing seem to work for me.

If i get it correct **eventsArgs.updated** is for tracking an image while moving this image. 

Is there any chance that You could give me a sample code for a correct instantiating? I probably keep making silly mistakes.

Greetings and thanks again for your replies and patience!

**Comment by tdmowrer** [comment]
Your code looks fine. What about it does not work correctly?

**Comment by AdrianGodlewski** [comment]
It unfortunetely doesn't instantiate any objects :(. I'm not using the **Tracked Image Prefab**, I'm just using my own array of objects to instantiate. Is there any possibility that You could send me a sample scene with objects instantiating without using the **Tracked Image Prefab**, but just doing that the way that I'm trying to do?
Thank You for your reply.

Greetings!

**Comment by tdmowrer** [comment]
This [example](https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/ImageTracking/Scripts/ImageTrackingObjectManager.cs) instantiates different prefabs when different reference prefabs are detected.

**Comment by AdrianGodlewski** [comment]
Hey, thank You for the response!

For the past few days I've been working on my script, which is deriving logic from Your example. I guess, I got it working. 

```
 void OnEnable()
    {
        m_ImageManager.trackedImagesChanged += OnTrackedImagesChanged;
    }

    void OnDisable()
    {
        m_ImageManager.trackedImagesChanged -= OnTrackedImagesChanged;
    }

    void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
    {
        foreach (ARTrackedImage trackedImage in eventArgs.added)
        {
            switch (trackedImage.referenceImage.name) {

                case "osehero":
                m_SpawnedOnePrefab = Instantiate(gameObjects[0], trackedImage.transform.position, trackedImage.transform.rotation);
                    m_SpawnedOnePrefab.SetActive(true);
                    break;

                case "Rafflesia":
                m_SpawnedTwoPrefab = Instantiate(gameObjects[1], trackedImage.transform.position, trackedImage.transform.rotation);
                     m_SpawnedTwoPrefab.SetActive(true);
                    break;            
            }
        }


        foreach (ARTrackedImage trackedImage in eventArgs.updated)
        {
            // image is tracking or tracking with limited state, show visuals and update it's position and rotation
            if (trackedImage.trackingState == TrackingState.Tracking)
            {
                switch (trackedImage.referenceImage.name) {
                    case "osehero":
                        m_SpawnedOnePrefab.SetActive(true);
                        m_SpawnedOnePrefab.transform.SetPositionAndRotation(trackedImage.transform.position, trackedImage.transform.rotation);
                        break;

                    case "Rafflesia":
                        m_SpawnedTwoPrefab.SetActive(true);
                        m_SpawnedTwoPrefab.transform.SetPositionAndRotation(trackedImage.transform.position, trackedImage.transform.rotation);
                        break;
                }
            }
            // image is no longer tracking, disable visuals TrackingState.Limited TrackingState.None
            else
            {

                switch (trackedImage.referenceImage.name)
                {
                    case "osehero":
                        m_SpawnedOnePrefab.SetActive(false);
                        break;

                    case "Rafflesia":
                        m_SpawnedTwoPrefab.SetActive(false);
                        break;
                }
            }

        }

/*        foreach (ARTrackedImage image in obj.removed)
        {
            if (image.referenceImage.name == "osehero")
            {
                Destroy(m_SpawnedOnePrefab);
            }
            else if (image.referenceImage.name == "Rafflesia")
            {
                Destroy(m_SpawnedTwoPrefab);
            }
        } */
    }
```
It is working fine. May I ask You if it is the most efficient way of tracking images? As we both know eventArgs.removed doesn't work in ARCore. I'm wondering if I should destroy spawnedPrefabs if **trackedImage.trackingState == TrackingState.None**. 

I'm also not sure about **eventArgs.added** function. For example: if we are in the frame, that we start tracking image then **eventArgs.added** is called. If we are moving the tracked image around, then **eventArgs.updated** is called each frame. But if we destroy the instantiated spawned prefab and then we are trying to track the same image again, then **eventArgs.added** isn't called, cause it was called on this image once, right? 

Thank You, have a nice weekend!

**Comment by tdmowrer** [comment]
> I'm wondering if I should destroy spawnedPrefabs if trackedImage.trackingState == TrackingState.None.

Depends on your application. For example, you might instantiate a player character by scanning a picture of the character (e.g., from a set of playing card-sized image markers that come with your game). In that case, you might just be using image tracking to kick off the game and don't care what happens to the tracking state afterwards.

> I'm also not sure about eventArgs.added function. For example: if we are in the frame, that we start tracking image then eventArgs.added is called. If we are moving the tracked image around, then eventArgs.updated is called each frame. But if we destroy the instantiated spawned prefab and then we are trying to track the same image again, then eventArgs.added isn't called

An image is only considered added when it is first detected by the underlying AR framework. It won't be considered added again if you destroy the object that you instantiated as a result.

**Comment by AdrianGodlewski** [comment]
Thank You for Your resopnse!

> Depends on your application. For example, you might instantiate a player character by scanning a picture of the character (e.g., from a set of playing card-sized image markers that come with your game). In that case, you might just be using image tracking to kick off the game and don't care what happens to the tracking state afterwards.

I'm currently working on a field game with the GPS module. The player will be given tips and riddles to solve for each tracked image (the instantiated prefab is gonna be a kind of a riddle), so that the riddle could direct him to another tracking image with another coordinates and so on. For example: first image instantiates only within 21.03 LAT/45.00 LON, second image instantiates within 21.4 LAT/45.20 LON ... etc.
I'm using the gps coordinates to drive the logic of instantiating prefabs.

Have a nice day.

**Comment by AdrianGodlewski** [comment]
Hello again. 
I encountered another problem, if there is any chance You could help me, I would be grateful. 

Here's a piece of my old code where I have been using only 1 prefab in the Tracked Image Prefab, without instantiating different prefabs based on the reference image name:
![kodOld](https://user-images.githubusercontent.com/43793163/81574654-64031800-93a6-11ea-8105-5f7dbd220a70.PNG)

And as a result I'm getting a pretty nice image instantiated on the tracked image. I kinda followed Your sample there -->[SAMPLE](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/ImageTracking/TrackedImageInfoManager.cs#L80-L94)

Here is a screenshot from my phone: 
![niceImage](https://user-images.githubusercontent.com/43793163/81575834-c6a8e380-93a7-11ea-9ef6-5a14fb140137.PNG)
As You can see, it smoothly instantiated an image on the tracked image (on "Rafflesia" pic).

_____________________________________________________________________________________

Now, when I'm instantiating different prefabs for each objects and I'm trying to instantiate an image, here's what happens: 
![badimage](https://user-images.githubusercontent.com/43793163/81578052-9747a600-93aa-11ea-8e9a-9183000341a3.PNG)
The screenshot doesn't show it well enough, but my point is that the image is rotated. I can't access "trackedimage.size" too. Here is my piece of code:
![kodnewcz1](https://user-images.githubusercontent.com/43793163/81578438-1937cf00-93ab-11ea-8a86-26ec18a6d458.PNG)

I tried to set prefab and image size manually: 
![reflibrary](https://user-images.githubusercontent.com/43793163/81578753-85b2ce00-93ab-11ea-99de-b3978a10acea.PNG)
![quadfilm](https://user-images.githubusercontent.com/43793163/81578757-88152800-93ab-11ea-858f-bab04915fbab.PNG)

It still seems that it doesn't work well. It keeps rotating and shaking. If i'm trying to instantiate 3D objects it is working fine.

Thank You in advance!

**Comment by AdrianGodlewski** [comment]
Hello again!

I guess, I got it working. This is what I did:  `arObjects["QuadParentFilm"].transform.SetPositionAndRotation(trackedImage.transform.position, trackedImage.transform.rotation*Quaternion.Euler(90,0, 0));`

I'm still not certainly sure about few things:

1) **Why do we need to rotate instantiated 2D planes with 90 degrees on the X axis?**


2) **If we aren't using the Tracked Image Prefab, but we are instantiating objects in code, where is the ARtrackedImage component located?** 

![image](https://user-images.githubusercontent.com/43793163/81940977-7ecccb00-95f8-11ea-98ef-93ede2ae6e62.png)
Assuming from the documentation and what Tim has said before --> If _Tracked Image Prefab_ is null then ARTrackedImage component will be on instantiated empty game object. 


3) **Why do I have to set scale of instantiated prefab manually, when I'm instantiating objects instead of using _Tracked Image Prefab_? I mean that this line of code doesn't work:** `trackedImage.transform.localScale = new Vector3(trackedImage.size.x, 1f, trackedImage.size.y);`



4) **I'm not sure about the difference in hierarchies for two different approaches. Could You please explain me that?**

This is a hierarchy of the first version of my scene. In this scene I have used "Tracked Image Prefab" and I have been using SetActive for given element in the prefab. I pasted my sample code under this guy's post --> [SAMPLE](https://github.com/Unity-Technologies/arfoundation-samples/issues/445)
![image](https://user-images.githubusercontent.com/43793163/81944169-a9208780-95fc-11ea-8440-dda92d399639.png)


In the second version of my scene, where I am instantiating objects in code, instead of using "Tracked Image Prefab" the hierarchy looks like this:
![image](https://user-images.githubusercontent.com/43793163/81944300-da995300-95fc-11ea-9fc3-c358d68ffb6b.png)
After starting scene it immediately instantiates all of the prefabs (Cube, QuadParentFilm and ToyPlane)

____________________________
I'm sorry for overwhelming You with my questions. I keep reading documentation, forums etc. and I just can't figure it out. Any help would be kindly appreciated.

**Comment by mdurand42** [comment]
@AdrianGodlewski your questions are suitable to post on the Unity Forums. This issues list is specific to AR Foundation and its samples. Best of luck!
