### ISSUE TITLE
Hi, why use internal to report this error when packaging APK. Use gradle to package normally.

### ISSUE THREAD

**Issue by TammyMin** [Unity-Technologies/arfoundation-samples#44]
![image](https://user-images.githubusercontent.com/1487781/45608804-7c167d00-ba87-11e8-8d3e-547a1541db64.png)

**Comment by craftercis** [comment]
Click "Try Again" and buld your app again. I hope this fix your problem

**Comment by tdmowrer** [comment]
You must use the Gradle build system with ARCore. We've added a check for this to present you with a descriptive error message in the future.

**Comment by TammyMin** [comment]
> You must use the Gradle build system with ARCore. We've added a check for this to present you with a descriptive error message in the future.

OK,Thank You.
When can I scan the card?

**Comment by TammyMin** [comment]
> Click "Try Again" and build your app again. I hope this fix your problem

No effect
