### ISSUE TITLE
Requesting Facing Direction: User support on iOS

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#441]
Hello,

As of the latest preview packages it should be possible to request the camera feed from the front cam, but I can only get it to work on Android.

On iOS (iPhone SE and iPhone X) it always shows the back image. I have set the facing direction to user in the inspector and to test also request it every frame from script, but to no avail.

Is it supported on iOS? Or only when facetracking.

**Comment by tdmowrer** [comment]
The configuration that you get is the one that matches the most requested features. So, for example, if you request the user facing camera, but also request features that require the world facing camera, the [configuration chooser](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.0/api/UnityEngine.XR.ARSubsystems.ConfigurationChooser.html) will likely favor the world facing camera.

In development builds, there is debug output that will tell you which features were requested and which ones could not be satisfied. It also lists all available configuration types and their supported features on startup. Not all iOS devices support a user facing camera configuration (the iPhone X does, though).

**Comment by nilsk123** [comment]
Thanks!

Am I right in thinking front cam is supported only on devices with a 'true-depth' camera, because they support face tracking? (found this https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration?language=objc)

Or is there more to it. Also, on android, is there a similar compatability 'problem'?

**Comment by tdmowrer** [comment]
That's correct. Also, note that the face tracking functionality is not provided by the ARKit XR Plugin; you must also have the ARKit Face Tracking package installed or the user-facing camera will not be available. [The readme](https://github.com/Unity-Technologies/arfoundation-samples#why-is-arkit-face-tracking-a-separate-package) explains why.
