### ISSUE TITLE
ARFoundation Supports less no. of devices only 246 out of 14000+ devices as per google playstore. Any way to support more devices?

### ISSUE THREAD

**Issue by miscrealitystudios** [Unity-Technologies/arfoundation-samples#443]
Hi,
So I have launched my app in play store [ https://play.google.com/store/apps/details?id=com.cygnops.cygnopsapp ] but the app is supported only in 246 devices out of 14000+ mobile devices which means my app will be available to very less no. of people. Is there any way I can let my app reach to more users. Like Pokemon Go which has AR Services and has a lot of supported devices and users

**Comment by tdmowrer** [comment]
ARFoundation uses ARCore on Android, so you are limited to the [devices supported by ARCore](https://developers.google.com/ar/discover/supported-devices).

Pokemon Go used a different solution.
