### ISSUE TITLE
Image Tracking multiple prefabs 

### ISSUE THREAD

**Issue by Istanolion** [Unity-Technologies/arfoundation-samples#445]
hi
I have been trying to reproduce what's in this video using android
https://youtu.be/iM0ghkvsRos

So far i can instantiate all the prefabs i want, however, when an image is recognaized it will set inmediatly its TranckingState to none, normaly it changes the next frame to tracking so no big problem. But sometimes the TrackingState remains in none, until i move aroud my phone (quite a lot) looking at the image again and then changes its TrackingStatus to either limited or tracking.

I'm using ARFoundation2.1.4 in unity 2019.3.6f1

My code is this one:

[RequireComponent(typeof(ARTrackedImageManager))]
public class Instanciador : MonoBehaviour
{
    [SerializeField]
    private Text textField;
    [SerializeField]
    private GameObject[] arObjectsToPlace;
    [SerializeField]
    private Dictionary<string,GameObject> arObjects= new Dictionary<string, GameObject>();
    private ARTrackedImageManager m_TrackedImageManager;
    // Start is called before the first frame update
    void Awake()
    {
      m_TrackedImageManager=GetComponent<ARTrackedImageManager>();
    }

    void OnEnable() {
        m_TrackedImageManager.trackedImagesChanged+=OnTrackedImagesChanged;
    }
    void OnDisable() {
        m_TrackedImageManager.trackedImagesChanged-=OnTrackedImagesChanged;
    }

    void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs){
      foreach(ARTrackedImage trackedImage in eventArgs.added){
        InstantiateARImage(trackedImage);
      }
      foreach(ARTrackedImage trackedImage in eventArgs.updated){
        if(trackedImage.trackingState==TrackingState.Limited){
          TurnOffARObject(trackedImage);
        }
       else{
        if(!arObjects[trackedImage.referenceImage.name].activeSelf){
          arObjects[trackedImage.referenceImage.name].SetActive(true);
        }
        UpdateARImage(trackedImage);
       }
      }
    }
    void TurnOffARObject(ARTrackedImage ARTI){       
      arObjects[ARTI.referenceImage.name].SetActive(false);      
    }
    void InstantiateARImage(ARTrackedImage trackedImage){
      foreach(GameObject obj in arObjectsToPlace){
        if(obj.name==trackedImage.referenceImage.name){
          GameObject newObj=Instantiate(obj,trackedImage.transform.position,trackedImage.transform.rotation);
          newObj.name=trackedImage.referenceImage.name;
          newObj.transform.localScale=new Vector3(0.1f,0.1f,0.1f);
          arObjects.Add(obj.name,newObj);
        }
      }
    }
    void UpdateARImage(ARTrackedImage trackedImage){
      AssignGameObject(trackedImage.referenceImage.name,trackedImage.transform.position,trackedImage.transform.rotation);
    }
    void AssignGameObject(string name,Vector3 newPosition,Quaternion newRot){
      if(arObjectsToPlace!=null){
        GameObject goARObject=arObjects[name];
        goARObject.transform.position=newPosition;
        goARObject.transform.rotation=newRot;
      }
    }
}

**Comment by AdrianGodlewski** [comment]
Guess I have got it working. **Is my approach to multiple prefab spawning correct or is it inefficient?**
https://github.com/Unity-Technologies/arfoundation-samples/issues/439  <- You can follow it here. Sorry for duplicating my comment. If You want I can delete my comment here, on in another post.
Steps which I did:

**1)** Created a prefab with empty gameobject and called it "Parent". Added 3 different 3D objects (those objects that i want to spawn) to "parent". All set to "inactive".
![image](https://user-images.githubusercontent.com/43793163/78681052-89ef5580-78ec-11ea-9526-f5c12b6aeacc.png)


**2)** Added this prefab to "Tracked Image Prefab" in the Inspector.
![image](https://user-images.githubusercontent.com/43793163/78681196-b3a87c80-78ec-11ea-9708-583786d36fe4.png)


**3)** And here is my piece of code: (osehero, Rafflesia and Logo are my image names in the ReferenceImageLibrary)
![image](https://user-images.githubusercontent.com/43793163/78682725-a68c8d00-78ee-11ea-922e-2399f19a4450.png)

______________________________________________________________________

**Is this a correct approach to multiple objects spawning? Or is this inefficient?**
     

Greetings!

**Comment by mdurand42** [comment]
> Guess I have got it working. **Is my approach to multiple prefab spawning correct or is it inefficient?**
> #439 <- You can follow it here. Sorry for duplicating my comment. If You want I can delete my comment here, on in another post.
> Steps which I did:
> 
> **1)** Created a prefab with empty gameobject and called it "Parent". Added 3 different 3D objects (those objects that i want to spawn) to "parent". All set to "inactive".
> ![image](https://user-images.githubusercontent.com/43793163/78681052-89ef5580-78ec-11ea-9526-f5c12b6aeacc.png)
> 
> **2)** Added this prefab to "Tracked Image Prefab" in the Inspector.
> ![image](https://user-images.githubusercontent.com/43793163/78681196-b3a87c80-78ec-11ea-9708-583786d36fe4.png)
> 
> **3)** And here is my piece of code: (osehero, Rafflesia and Logo are my image names in the ReferenceImageLibrary)
> ![image](https://user-images.githubusercontent.com/43793163/78682725-a68c8d00-78ee-11ea-922e-2399f19a4450.png)
> 
> **Is this a correct approach to multiple objects spawning? Or is this inefficient?**
> 
> Greetings!

Yes, this looks reasonable. It's roughly equivalent to the approach in our sample:
https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/ImageTracking/TrackedImageInfoManager.cs

**Comment by bduinatCIMMI** [comment]
Hi, 
Do you include this piece of code in ARTrackedImageManager, or do you create a separate script ?

**Comment by AdrianGodlewski** [comment]
Hello,
I have created separate script for this.

**Comment by benbyford** [comment]
seem to be following along with LOTS of tutorials and forum posts but cant get my prfabs to track the images properly. They seem to track the image fine but the position is all over the place, if i rotate the physical image the prefab rotates but if i move the phone left or right then it follows the phone not the image in place (e.g. it flys off)
