### ISSUE TITLE
Image Tracking by dynamically added images  

### ISSUE THREAD

**Issue by woelfle2004** [Unity-Technologies/arfoundation-samples#449]
I desperately try to create a runtime library via CreateRuntimeLibrary.
If I create the ReferenceImageLibrary in Unity Editor everything works.
But I want to store each tracked image in a SQL Database and therefore I want to amend an existing ImageLibrary or to create an empty one.
Is there an example how it works ?

This expression tells me always that the ReferenceImageLibrary cannot be amended
```
if (m_TrackedImageManager.referenceLibrary is MutableRuntimeReferenceImageLibrary mutableLibrary)
        {
            Debug.Log("ImageRecognition");
        }
```

I am using Unity 2020 and ARFoundation 4 on a Android machine.

**Comment by smaerdlatigid** [comment]
Read the docs...I've searched the web and couldn't find any good examples, here's a start:

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.MutableRuntimeReferenceImageLibraryExtensions.html

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html

https://github.com/Unity-Technologies/arfoundation-samples/issues/450

**Comment by tdmowrer** [comment]
We'll add a sample showing this. In the meantime, https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html is a good place to start for example snippets. Looks like that's what @woelfle2004 was using; were there any errors or other output in adb?

**Comment by woelfle2004** [comment]
I really appreciate your reply Tim,
actually I am sorry to say that I am not able to reproduce my source code anymore.
But as far as I know I got an error message from the ARCore.

**Comment by tdmowrer** [comment]
If you can reproduce it, please re-open this issue and post any logs or other errors.
