### ISSUE TITLE
Black screen after building to Android

### ISSUE THREAD

**Issue by craftercis** [Unity-Technologies/arfoundation-samples#45]
**Hello,**

The first time I downloaded this project and build I still had no problems with my camera. But now I have removed that project because after a build a camera no longer appeared. That is why I have now downloaded this project again, but again, after the build, he gives no more pop-up to accept the camera permission. If I want to do this mentally in the settings and I restart the app it still does not work. How do I solve this?

**Comment by tdmowrer** [comment]
Anything interesting in the logcat output? ```adb logcat Unity:* Unity-ARCore:* ArPresto:* *:S```
Are you in China by any chance? The "is this device supported" check works a bit differently there, due to lack of the Play Store.

**Comment by craftercis** [comment]
> Anything interesting in the logcat output? `adb logcat Unity:* Unity-ARCore:* ArPresto:* *:S`
> Are you in China by any chance? The "is this device supported" check works a bit differently there, due to lack of the Play Store.

I hope this is a good logcat but this is the first time i did this. I live in the netherlands

`--------- beginning of system
--------- beginning of crash
--------- beginning of main
09-19 09:25:50.751  6595 31478 I Unity   : SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 8, Memory = 3622mb
09-19 09:25:50.751  6595 31478 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 240), 4 little (mask: 15)
09-19 09:25:50.752  6595 31478 I Unity   : ApplicationInfo com.unity.arfoundation.samples version 0.1 build bdd698d6-e0ea-465e-9d4c-8963434c21f9
09-19 09:25:50.752  6595 31478 I Unity   : Built from '2018.1/release' branch, Version '2018.1.9f2 (a6cc294b73ee)', Build type 'Release', Scripting Backend 'mono'
09-19 09:25:50.849  6595 31478 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_EXT_mul
09-19 09:25:50.849  6595 31478 D Unity   : tisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance
09-19 09:25:50.849  6595 31478 D Unity   :  GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation
09-19 09:25:53.148  6595 31478 E Unity   : Unable to find UnityARCore
09-19 09:25:53.247  6595 31478 E Unity   : DllNotFoundException: UnityARCore
09-19 09:25:53.247  6595 31478 E Unity   :   at (wrapper managed-to-native) UnityEngine.XR.ARCore.Api:UnityARCore_setCameraPermissionProvider (UnityEngine.XR.ARCore.Api/CameraPermissionRequestProvider)
09-19 09:25:53.247  6595 31478 E Unity   :   at UnityEngine.XR.ARCore.ARCoreCameraExtension.Register () [0x00000] in <filename unknown>:0
09-19 09:25:53.247  6595 31478 E Unity   :
09-19 09:25:53.247  6595 31478 E Unity   : (Filename:  Line: -1)
09-19 09:25:53.247  6595 31478 E Unity   :
09-19 09:25:53.272  6595 31478 E Unity   : NullReferenceException: Object reference not set to an instance of an object
09-19 09:25:53.272  6595 31478 E Unity   :   at UnityEngine.Experimental.SubsystemDescriptor`1[TSubsystem].Create () [0x00000] in <filename unknown>:0
09-19 09:25:53.272  6595 31478 E Unity   :   at UnityEngine.XR.ARFoundation.ARSubsystemUtil.CreateSubsystem[XRSessionSubsystemDescriptor,XRSessionSubsystem] (System.Collections.Generic.List`1 descriptors, System.String id) [0x00000] in <filename unknown>:0
09-19 09:25:53.272  6595 31478 E Unity   :   at UnityEngine.XR.ARFoundation.ARSubsystemUtil.CreateSessionSubsystem (System.String id) [0x00000] in <filename unknown>:0
09-19 09:25:53.272  6595 31478 E Unity   :   at UnityEngine.XR.ARFoundation.ARSubsystemManager.CreateSubsystems () [0x00000] in <filename unknown>:0
09-19 09:25:53.272  6595 31478 E Unity   :   at UnityEngine.XR.ARFoundation.ARSession.OnEnable () [0x00000] in <filename unknown>:0
09-19 09:25:53.272  6595 31478 E Unity   :
09-19 09:25:53.272  6595 31478 E Unity   : (Filename:  Line: -1)
09-19 09:25:53.272  6595 31478 E Unity   :`

**Comment by tdmowrer** [comment]
@craftercis The output is useful. Here is the problem:
```Unable to find UnityARCore```

You said updating your package fixed it -- what version did you update from and to?
What combination of backend and scripting runtime did you use? Any other changes to this repo?

**Comment by craftercis** [comment]
> @craftercis The output is useful. Here is the problem:
> `Unable to find UnityARCore`
> 
> You said updating your package fixed it -- what version did you update from and to?
> What combination of backend and scripting runtime did you use? Any other changes to this repo?

I update from ARCore XR Plugin preview 18 to 19. 

I have not changed anything else about the project. I just build the sample scene and now it works

**Comment by mklitsner** [comment]
Im having the same problem with the google arcore cloud anchors example, as well as the hello Ar example. updating Arcore XR plugin didn't do anything for me as it actually clashes with the Arcore plugin that I have from google's repository. I noticed there might be an issue with the splash screen per this logcat chunk on the initialization of the build:

```
02-14 13:19:01.026 11247 11263 D         : PlayerBase::PlayerBase()
02-14 13:19:01.027 11247 11263 D         : TrackPlayerBase::TrackPlayerBase()
02-14 13:19:01.027 11247 11263 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
02-14 13:19:01.027 11247 11263 W AudioTrack: notificationFrames=-42 clamped to the range -1 to -8
02-14 13:19:01.027   858  1176 D AudioFlinger: Client defaulted notificationFrames to 96 for frameCount 768
02-14 13:19:01.027 11247 11263 I AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 768
02-14 13:19:01.030   817   817 W AshmemAllocator: ashmem_create_region(7680) returning hidl_memory(0x7bcf62c100, 7680)
02-14 13:19:01.031   817   817 W AshmemAllocator: ashmem_create_region(7680) returning hidl_memory(0x7bcf62c100, 7680)
02-14 13:19:01.034   821  5136 D audio_route: Apply path: speaker
02-14 13:19:01.034   821  5136 D audio_hw_primary: enable_snd_device: snd_device(102: vi-feedback)
02-14 13:19:01.034   821  5136 D audio_route: Apply path: vi-feedback
02-14 13:19:01.034   821  5136 E audio_hw_utils: audio_extn_utils_send_app_type_cfg: Failed to derive app_type for uc type : 0x1
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 512, path = 1, app id = 0x11132, sample rate = 48000
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_asm_topology
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_adm_topology
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_audtable
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_audvoltable
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
02-14 13:19:01.034   821  5136 D         : Failed to fetch the lookup information of the device 00000200
02-14 13:19:01.034   821  5136 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_audstrmtable
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 16
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_afe_topology
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 512, Topology Id 10001ccc
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_afe_cal
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 512 path = 1
02-14 13:19:01.034   821  5136 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
02-14 13:19:01.034   838   838 D android.hardware.power@1.3-service.crosshatch-libperfmgr: AUDIO STREAMING ON
02-14 13:19:01.034   821  5136 D audio_hw_primary: enable_audio_route: usecase(24) apply and update mixer path: spkr-vi-record vi-feedback
02-14 13:19:01.034   821  5136 D audio_route: Apply path: spkr-vi-record vi-feedback
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 513, path = 0, app id = 0x11130, sample rate = 48000
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_asm_topology
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_adm_topology
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_audtable
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_audvoltable
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
02-14 13:19:01.068   821  5136 D         : Failed to fetch the lookup information of the device 00000201
02-14 13:19:01.068   821  5136 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_audstrmtable
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 456
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_afe_topology
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 513, Topology Id 10000ccc
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> send_afe_cal
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
02-14 13:19:01.068   821  5136 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
02-14 13:19:01.069   821  5136 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
02-14 13:19:01.069   821  5136 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 513 path = 0
02-14 13:19:01.069   821  5136 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
02-14 13:19:01.069   821  5136 D audio_hw_primary: enable_audio_route: usecase(5) apply and update mixer path: audio-ull-playback speaker
02-14 13:19:01.069   821  5136 D audio_route: Apply path: audio-ull-playback speaker
02-14 13:19:01.073   626  2207 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.google.ar.core.examples.unity.cloudanchors#0
02-14 13:19:01.073   626  2207 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.google.ar.core.examples.unity.cloudanchors#0
02-14 13:19:01.118   821  5136 D audio_hw_primary: out_write: retry previous failed cal level set
02-14 13:19:01.118   821  5136 W qc_adm  : margin check: adm_request_focus_v2(p) failed diff -192
02-14 13:19:01.118   821  5136 W qc_adm  : margin check: adm_abandon_focus(p) failed diff -192
02-14 13:19:01.118   838   838 D android.hardware.power@1.3-service.crosshatch-libperfmgr: AUDIO STREAMING OFF
02-14 13:19:01.119   838   838 D android.hardware.power@1.3-service.crosshatch-libperfmgr: AUDIO LOW LATENCY ON
02-14 13:19:01.124   821  5136 D qc_adm  : ns 1748698 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.128   821  5136 D qc_adm  : ns 1844322 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.129   821  5136 D qc_adm  : ns 2619739 > expected_ns 2000000 (skipped 0)
02-14 13:19:01.134   821  5136 D qc_adm  : ns 1833541 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.138   821  5136 D qc_adm  : ns 1713280 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.142   821  5136 D qc_adm  : ns 1717186 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.146   821  5136 D qc_adm  : ns 1810935 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.147   821  5136 D qc_adm  : ns 2578383 > expected_ns 2000000 (skipped 0)
02-14 13:19:01.152   821  5136 D qc_adm  : ns 1727914 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.156   821  5136 D qc_adm  : ns 1614632 > expected_ns 1000000 (skipped 0)
02-14 13:19:01.320  1870  1870 I WallpaperService: engine paused
02-14 13:19:01.331   845  2005 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
02-14 13:19:00.979 11247 11263 I chatty  : uid=10170(com.google.ar.core.examples.unity.cloudanchors) UnityMain identical 14 lines
02-14 13:19:00.979 11247 11263 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
02-14 13:19:01.352  1262  4269 I ActivityManager: Killing 18368:com.google.android.apps.turbo/u0a24 (adj 906): empty #17
02-14 13:19:01.353  1262  1280 W libprocessgroup: kill(-18368, 9) failed: No such process
02-14 13:19:01.372  2907 11223 I PBSessionCacheImpl: Deleted sessionId[1802208186222] from persistence.
02-14 13:19:01.373   839  1626 I sensors-hal: batch_physical_sensor:192, android.sensor.accelerometer/16, period=200000000, max_latency=0
02-14 13:19:01.373   839  1626 I sensors-hal: batch_physical_sensor:201, android.sensor.accelerometer/16, period=200000000, max_latency=0 request completed
```

**Comment by redagrandrei** [comment]
In my case big resolution textures made ARCore go to black screen. Just go in texture settings turn on texture compression and put th resolution to 512 or something

**Comment by woelfle2004** [comment]
Hi Tim and all other coders,
I am still struggling with my project in terms of a black screen and even crashes of the Android Version of my project. The first time I run the APK file on my S9+ everything works great. I close the app by Application.Quit(). If I then start the app again I get the black screen or the app crashes. I tried to debug the app on the phone and and found out that the state of ARSubsystemManager is "CheckAvailability" before it chrashes. If I clean the phone's Memory by "Force Stop the app" then the App works again perfect. I got the newest Unity 2019 version and the newest ARfoundation and ARCore package as well. I really appreciate if you could help me with this issue.
- Rainer

**Comment by woelfle2004** [comment]
I found now a Workaround for my Problem with the crashing app if I started my Unity app the second time. The AR Camera seems not to be destroyed properly by the call Application.Quit(). But what works for me was this additional function which kills the process out of the Android Memory. Et voila I can start the app as often I want:
public void onDestroy()
    {
        AndroidJavaClass process = new AndroidJavaClass("android.os.Process");
        int pid = process.CallStatic<int>("myPid");
        process.CallStatic("killProcess", pid);
    }

- Rainer

**Comment by tdmowrer** [comment]
> I found now a Workaround for my Problem with the crashing app if I started my Unity app the second time. The AR Camera seems not to be destroyed properly by the call Application.Quit(). But what works for me was this additional function which kills the process out of the Android Memory. Et voila I can start the app as often I want:
> public void onDestroy()
> {
> AndroidJavaClass process = new AndroidJavaClass("android.os.Process");
> int pid = process.CallStatic("myPid");
> process.CallStatic("killProcess", pid);
> }
> 
> * Rainer

I seem to remember there being an issue in Unity where Application.Quit didn't always call OnDestroy on the MonoBehaviours in the scene, which would have left ARCore running in the background. Just tested this in 2019.2.7f2 and Application.Quit() does destroy the session properly. I'll close this issue but please reopen it if this continues to be a problem.
