### ISSUE TITLE
 AR Fondation Image Tracking + Plane Detection

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#451]
Hi,

I am trying to make it so that in my app after the user detects a plane, he can scan an image and I want the object associated with that image to appear on the detected plane, is that possible, with both trackings enabled in the same project?

I can provide samples of code if needed and would kindly be appreciated!

**Comment by mdurand42** [comment]
Hi-

Image tracking and plane tracking are not directly related to one another and can be used together just fine. Could you explain your use case in more detail please?

-Mike

**Comment by Sterling-Malory-Archer** [comment]
My use case would be:

- The user scans an image
- The user scans for an ARPlane
- The object associated with the image appears on the ARPlane

I have multiple images and multiple objects associated with them.

Down below is my script

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.XR.ARSubsystems;
using UnityEngine.XR.ARFoundation;

[RequireComponent(typeof(ARTrackedImageManager))]
public class MultiTrackedImageManager : MonoBehaviour
{

    public static MultiTrackedImageManager Instance { get { return instance; } }
    private static MultiTrackedImageManager instance;

    private ARTrackedImageManager m_TrackedImageManager;
    private GameObject curobject;
    private string PREFABFOLDER = "Prefabs/";
    private ARSessionOrigin aRSessionOrigin;

    #region PlaneDetectionNecessities
    [SerializeField]
    private ARPlaneManager aRPlaneManager;

    private ARPlane aRPlane;
    #endregion

    public List<MultiTrackedImage> Images = new List<MultiTrackedImage>();

    private void Awake()
    {
        if (instance != null) { Destroy(instance); }
        instance = this;
        m_TrackedImageManager = GetComponent<ARTrackedImageManager>();
        aRSessionOrigin = GetComponent<ARSessionOrigin>();
        curobject = null;
        aRPlaneManager = GetComponent<ARPlaneManager>();
    }

    private void PlanesChanged(ARPlanesChangedEventArgs args)
    {
        aRPlane = args.added[0];
    }

    void OnEnable()
    {
        m_TrackedImageManager.trackedImagesChanged += OnTrackedImagesChanged;
        aRPlaneManager.planesChanged += PlanesChanged;
    }
    void OnDisable()
    {
        m_TrackedImageManager.trackedImagesChanged -= OnTrackedImagesChanged;
    }

    void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
    {

        foreach (var trackedImage in eventArgs.updated)
        {
            OnImageUpdated(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
        }

        foreach (var trackedImage in eventArgs.added)
        {
            OnImageAdded(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
        }
    }

    public void OnImageUpdated(string textureName, string name, ARTrackedImage m_ARTrackedImage)
    {

        for (int i = 0; i < Images.Count; i++)
        {
            //if we have a match for the object and we have regained tracking and the current object is not the one for the trigger we just found
            if (m_ARTrackedImage.trackingState == TrackingState.Tracking)
            {

                //this checks to make sure we are tracking the right image target
                if (!string.Equals(Images[i].target.name, textureName)) { continue; }

                //this checks to see if our current object is equal to the name of the image target so we don't delete and duplicate
                if (string.Equals(curobject.name, Images[i].target.name)) { continue; }

                //for some reason we are getting updates from non visible targets
                if (curobject != null) { Destroy(curobject); }

                GameObject go = GameObject.Find(name);
                
                GameObject prefab = Resources.Load($"{PREFABFOLDER}{Images[i].path}") as GameObject;

                GameObject target = Instantiate(prefab, arPlane.transform.position, Quaternion.identity);

                curobject = target;
                curobject.name = Images[i].target.name;

                Images[i].go = go;
                target.transform.Rotate(Vector3.up, 180);
                target.transform.SetParent(go.transform);
                target.transform.localPosition = Vector3.zero;
            }
        }
    }

    public void OnImageAdded(string textureName, string name, ARTrackedImage m_ARTrackedImage)
    {

        //PrefabManager.s.ClearPrefabs();
        for (int i = 0; i < Images.Count; i++)
        {
            if (string.Equals(Images[i].target.name, textureName) && Images[i].go == null)
            {
                //Destroy the existing AR Animation
                if (curobject != null) { Destroy(curobject); }

                GameObject go = GameObject.Find(name);
                
                GameObject prefab = Resources.Load($"{PREFABFOLDER}{Images[i].path}") as GameObject;

                //Instantiate the prefab with the position of arPlane
                GameObject target = Instantiate(prefab, arPlane.transform.position, Quaternion.identity);

                curobject = target;
                curobject.name = Images[i].target.name;

                Images[i].go = go;
                target.transform.Rotate(Vector3.up, 180);
                target.transform.SetParent(go.transform);
                target.transform.localPosition = Vector3.zero;
            }
        }
    }
}

`

**Comment by mdurand42** [comment]
> My use case would be:
> 
> * The user scans an image
> * The user scans for an ARPlane
> * The object associated with the image appears on the ARPlane
> 
> I have multiple images and multiple objects associated with them.
> 
> Down below is my custom script for tracking which image gets tracked and also if the plane is detected
> 
> `
> using System.Collections;
> using System.Collections.Generic;
> using UnityEngine;
> using UnityEngine.UI;
> using UnityEngine.XR.ARSubsystems;
> using UnityEngine.XR.ARFoundation;
> 
> [RequireComponent(typeof(ARTrackedImageManager))]
> public class MultiTrackedImageManager : MonoBehaviour
> {
> 
> ```
> public static MultiTrackedImageManager Instance { get { return instance; } }
> private static MultiTrackedImageManager instance;
> 
> private ARTrackedImageManager m_TrackedImageManager;
> private GameObject curobject;
> private string PREFABFOLDER = "Prefabs/";
> private ARSessionOrigin aRSessionOrigin;
> 
> #region PlaneDetectionNecessities
> [SerializeField]
> private ARPlaneManager aRPlaneManager;
> 
> private ARPlane aRPlane;
> #endregion
> 
> public List<MultiTrackedImage> Images = new List<MultiTrackedImage>();
> 
> private void Awake()
> {
>     if (instance != null) { Destroy(instance); }
>     instance = this;
>     m_TrackedImageManager = GetComponent<ARTrackedImageManager>();
>     aRSessionOrigin = GetComponent<ARSessionOrigin>();
>     curobject = null;
>     aRPlaneManager = GetComponent<ARPlaneManager>();
> }
> 
> private void PlanesChanged(ARPlanesChangedEventArgs args)
> {
>     if (args.added != null)
>     {
>        aRPlane = args.added[0];
>     }
> }
> 
> void OnEnable()
> {
>     m_TrackedImageManager.trackedImagesChanged += OnTrackedImagesChanged;
>     aRPlaneManager.planesChanged += PlanesChanged;
> }
> void OnDisable()
> {
>     m_TrackedImageManager.trackedImagesChanged -= OnTrackedImagesChanged;
> }
> 
> void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
> {
> 
>     foreach (var trackedImage in eventArgs.updated)
>     {
>         OnImageUpdated(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
>     }
> 
>     foreach (var trackedImage in eventArgs.added)
>     {
>         OnImageAdded(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
>     }
> }
> 
> public void OnImageUpdated(string textureName, string name, ARTrackedImage m_ARTrackedImage)
> {
> 
>     for (int i = 0; i < Images.Count; i++)
>     {
>         //if we have a match for the object and we have regained tracking and the current object is not the one for the trigger we just found
>         if (m_ARTrackedImage.trackingState == TrackingState.Tracking)
>         {
> 
>             //this checks to make sure we are tracking the right image target
>             if (!string.Equals(Images[i].target.name, textureName)) { continue; }
> 
>             //this checks to see if our current object is equal to the name of the image target so we don't delete and duplicate
>             if (string.Equals(curobject.name, Images[i].target.name)) { continue; }
> 
>             //for some reason we are getting updates from non visible targets
>             if (curobject != null) { Destroy(curobject); }
> 
>             GameObject go = GameObject.Find(name);
>             
>             GameObject prefab = Resources.Load($"{PREFABFOLDER}{Images[i].path}") as GameObject;
> 
>             GameObject target = Instantiate(prefab, arPlane.transform.position, Quaternion.identity);
> 
>             curobject = target;
>             curobject.name = Images[i].target.name;
> 
>             Images[i].go = go;
>             target.transform.Rotate(Vector3.up, 180);
>             target.transform.SetParent(go.transform);
>             target.transform.localPosition = Vector3.zero;
>         }
>     }
> }
> 
> public void OnImageAdded(string textureName, string name, ARTrackedImage m_ARTrackedImage)
> {
> 
>     //PrefabManager.s.ClearPrefabs();
>     for (int i = 0; i < Images.Count; i++)
>     {
>         if (string.Equals(Images[i].target.name, textureName) && Images[i].go == null)
>         {
>             //Destroy the existing AR Animation
>             if (curobject != null) { Destroy(curobject); }
> 
>             GameObject go = GameObject.Find(name);
>             
>             GameObject prefab = Resources.Load($"{PREFABFOLDER}{Images[i].path}") as GameObject;
> 
>             //Instantiate the prefab with the position of arPlane
>             GameObject target = Instantiate(prefab, arPlane.transform.position, Quaternion.identity);
> 
>             curobject = target;
>             curobject.name = Images[i].target.name;
> 
>             Images[i].go = go;
>             target.transform.Rotate(Vector3.up, 180);
>             target.transform.SetParent(go.transform);
>             target.transform.localPosition = Vector3.zero;
>         }
>     }
> }
> ```
> 
> }
> 
> `

Your code seems reasonable (although we haven't actually run it). Is this not working for you?

**Comment by Sterling-Malory-Archer** [comment]
Hi,

It is working but for some strange reason, it places the prefab in mid-air instead of placing it on the detected plane, and my prefabs all have a position of 0, 0.5, 0. in order to appear above the plane.

**Comment by mdurand42** [comment]
> Hi,
> 
> It is working but for some strange reason, it places the prefab in mid-air instead of placing it on the detected plane, and my prefabs all have a position of 0, 0.5, 0. in order to appear above the plane.

The best results for keeping your content realistically attached to a plane would be to modify your code in the following manner:

```            
public void OnImageAdded(string textureName, string name, ARTrackedImage m_ARTrackedImage)
{
            ...
            //Instantiate the prefab with the position of arPlane
            var anchorManager = GetComponent<ARAnchorManager>();
            anchorManager.anchorPrefab = prefab;

            var anchor = m_AnchorManager.AttachAnchor(arPlane, arPlane.center);
            GameObject target = anchor.gameObject;
            ...
}
```
Adding an anchor on your plane provides a cue to the underlying SDK that your application cares about accurate tracking of this region in space. As the SDK gets a better estimate for the plane it will update your ARAnchor which is driving the transform of your instantiated prefab.

**Comment by Sterling-Malory-Archer** [comment]
Except I am using AR Foundation 2.1.4 and there is no ARAnchorManager script available, my ARKit and ARCore packages are 2.1.2.

Which version contains the AnchorManager?

**Comment by Sterling-Malory-Archer** [comment]
I am getting an error with arPlane.center

Cannot convert Vector3 to Pose

**Comment by DavidMohrhardt** [comment]
https://docs.unity3d.com/ScriptReference/Pose.html

A pose is both a position (Vector3) and a rotation (Quaternion).

As for the image detection failing, can you provide us with the device you are testing on, the Unity version you are using for your project and the active ARManagers in your project???

**Comment by Sterling-Malory-Archer** [comment]
Hi David,

I fixed it by just re-adding the XR Image Library. Currently, I have 3 ARManagers:
- Tracked Image Manager
- AR Plane Manager
- AR Anchor Manager

As for the Pose, the code Mike provided worked perfectly, however it is still spawning the prefab above the plane, is it due to me having 

`
                var anchorManager = GetComponent<ARAnchorManager>();
                anchorManager.anchorPrefab = prefab;

                var anchor = anchorManager.AttachAnchor(aRPlane, Pose.identity);
                GameObject target = anchor.gameObject;
`

instead of var anchor = anchorManager.AttachAnchor(aRPlane, aRPlane.center);?

How would I go for referencing the arPlane.center with a Pose instead of Vector3?

**Comment by mdurand42** [comment]
Try:

```var anchor = anchorManager.AttachAnchor(aRPlane, new Pose(arPlane.center, Quaternion.identity);```

Or it may be a better experience to set the orientation of your content to face the camera when building your pose. There plane classification sample includes an example of how to do that.
https://github.com/Unity-Technologies/arfoundation-samples/tree/master/Assets/Scenes/Plane%20Detection

**Comment by Sterling-Malory-Archer** [comment]
Thank you, Mike,

I made a new Pose so now it should do it!

I will definitely check it out and see how to implement that, because that is exactly what I wanted!

Thank you again for your time and help!
