### ISSUE TITLE
Keep running ARSession + Many AR Object, the FPS is going downhill

### ISSUE THREAD

**Issue by kidapu** [Unity-Technologies/arfoundation-samples#452]
I rotated 6000 cubes in `SimpleAR` Scene, after 3-10 min the fps drops down from 60fps to 30fps.

I've wote `Application.targetFrameRate = 60;`. I want to know the way to keep it at 60fps. 

My tested enviroment is below.
- iPhone8(iOS13.4), iPhone11 Pro(iOS13.3)
- Unity 2019.3.7f1
- "com.unity.xr.arfoundation": "3.0.1",
- "com.unity.xr.arkit": "3.0.1",

Here's what else I've observed.

### 1) The bottleneck of Unity Profiler is different in each iPhones

The bottleneck was the rendering of the CUBE to the camera in iPhone8.
The bottleneck was `ARSession.Update()` in iPhone11 Pro.

<img width="873" alt="screen_shot_2020-04-13_at_23_35_14" src="https://user-images.githubusercontent.com/720154/79182703-6ecf9900-7e4a-11ea-8b56-77d847c65250.png">

After the FPS went down, ARSession.Reset() didn't raise the FPS

Over time, there was no particular change in `Memory` or `Rendering`.
Only `CPU Usage` has been changed.

### 2) Rotated 6000 cubes without ARKit
This experiment could able to keep 60fps for over 10 minutes.

I'm guessing that there is a causal relationship between keeping ARSession running and FPS going down.
However, I don't know the immediate cause and solution.

**Comment by mdurand42** [comment]
> I rotated 6000 cubes in `SimpleAR` Scene, after 3-10 min the fps drops down from 60fps to 30fps.
> 
> I've wote `Application.targetFrameRate = 60;`. I want to know the way to keep it at 60fps.
> 
> My tested enviroment is below.
> 
> * iPhone8(iOS13.4), iPhone11 Pro(iOS13.3)
> * Unity 2019.3.7f1
> * "com.unity.xr.arfoundation": "3.0.1",
> * "com.unity.xr.arkit": "3.0.1",
> 
> Here's what else I've observed.
> 
> ### 1) The bottleneck of Unity Profiler is different in each iPhones
> The bottleneck was the rendering of the CUBE to the camera in iPhone8.
> The bottleneck was `ARSession.Update()` in iPhone11 Pro.
> 
> <img alt="screen_shot_2020-04-13_at_23_35_14" width="873" src="https://user-images.githubusercontent.com/720154/79182703-6ecf9900-7e4a-11ea-8b56-77d847c65250.png">
> 
> After the FPS went down, ARSession.Reset() didn't raise the FPS
> 
> Over time, there was no particular change in `Memory` or `Rendering`.
> Only `CPU Usage` has been changed.
> 
> ### 2) Rotated 6000 cubes without ARKit
> This experiment could able to keep 60fps for over 10 minutes.
> 
> I'm guessing that there is a causal relationship between keeping ARSession running and FPS going down.
> However, I don't know the immediate cause and solution.

Hi. What you are running into is thermal throttling that ARKit enables to preserve battery life and protect the device. We are accounting for this as of v3.0.3 of the ARKit XR Plugin package. See release notes:

`The "match frame rate" option did not account for thermal throttling, which can put ARKit into a 30 frames per second update mode while Unity would keep trying to update at 60 frames per second. This could lead to visual artifacts like judder. The calculated frame rate now takes the thermal state into account and will do a better job matching ARKit's update rate.
`
You have the option to keep Unity running at 60Hz but we do not recommend it as it causes judder when ARKit throttles to 30Hz.

**Comment by kidapu** [comment]
@mdurand42 
Thanks you for your quick answer m(_ _)m

The `thermal throttling ` is really make sense for my question.
I was wondering why the FPS would drop .

I also tried the code below to see if I could keep 60fps, even though it was not recommended.

```
Application.targetFrameRate = 60;
ArSession.matchFrameRate = true;
```
After about 10 minutes, the FPS dropped from 60 to 30. And the iPhone 11 Pro was hot. I didn't think it was possible to force 60fps keep from the code.

**Comment by mdurand42** [comment]
> @mdurand42 
> Thanks you for your quick answer m(_ _)m
> 
> The `thermal throttling ` is really make sense for my question.
> I was wondering why the FPS would drop .
> 
> I also tried the code below to see if I could keep 60fps, even though it was not recommended.
> 
> ```
> Application.targetFrameRate = 60;
> ArSession.matchFrameRate = true;
> ```
> After about 10 minutes, the FPS dropped from 60 to 30. And the iPhone 11 Pro was hot. I didn't think it was possible to force 60fps keep from the code.
> 
> 

If you want to force 60 fps you need

```ArSession.matchFrameRate = false;```

**Comment by kidapu** [comment]
@mdurand42 
Thanks! It works on my enviroment!
I don't think I'll actually use this cord because the iPhone gets so hot.
But I'm glad to see a solution.
