### ISSUE TITLE
screen effect

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#453]
How can i do that make the screen effect right use arfundation？
i get a problem ，i make a screen effect right in Unity_edit,but when i
build in ios device is wrong just like two shadow in my screen.
I try to get the camera orthographic,fieldOfView to show same screen,but it doesn't work in ios devive

grateful！！！！！！

**Comment by mdurand42** [comment]
> How can i do that make the screen effect right use arfundation？
> i get a problem ，i make a screen effect right in Unity_edit,but when i
> build in ios device is wrong just like two shadow in my screen.
> I try to get the camera orthographic,fieldOfView to show same screen,but it doesn't work in ios devive
> 
> grateful！！！！！！

The camera matrices are driven by the AR platforms themselves so it is highly likely that the effects you see in the Editor will present differently on device.
