### ISSUE TITLE
Image Tracking and URP

### ISSUE THREAD

**Issue by marwie** [Unity-Technologies/arfoundation-samples#454]
Hello, running the ar foundation image tracking sample scene using URP (7.3.1) I get the following error 

```Property (_BaseColor) already exists. Use SetTexture instead.
UnityEngine.Material:set_mainTexture(Texture)
TrackedImageInfoManager:UpdateInfo(ARTrackedImage) (at Assets/Thirdparty/Unity/ARFoundationSamples/Scenes/ImageTracking/TrackedImageInfoManager.cs:87)
TrackedImageInfoManager:OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs) (at Assets/Thirdparty/Unity/ARFoundationSamples/Scenes/ImageTracking/TrackedImageInfoManager.cs:102)
UnityEngine.XR.ARFoundation.ARTrackableManager`4:Update()
```

**Comment by mdurand42** [comment]
Hi-

Could you please include the part of the log that describes the error? Also, could you describe the behavior you are aside from log messages?

-Mike

**Comment by marwie** [comment]
Hello Mike, sorry what a stupid mistake :)

the whole error message looks like this:
```Property (_BaseColor) already exists. Use SetTexture instead.
UnityEngine.Material:set_mainTexture(Texture)
TrackedImageInfoManager:UpdateInfo(ARTrackedImage) (at Assets/Thirdparty/Unity/ARFoundationSamples/Scenes/ImageTracking/TrackedImageInfoManager.cs:88)
TrackedImageInfoManager:OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs) (at Assets/Thirdparty/Unity/ARFoundationSamples/Scenes/ImageTracking/TrackedImageInfoManager.cs:103)
UnityEngine.XR.ARFoundation.ARTrackableManager`4:Update()```

**Comment by mdurand42** [comment]
Are you making sure to check the box in your ReferenceImageLibrary to make the texture available at runtime?

Also, have you converted to project to work with URP using the following instructions?
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@9.0/manual/upgrading-your-shaders.html

Also, can you describe any changes you've made to the ImageTracking example?

-Mike

**Comment by marwie** [comment]
I just tried to reproduce the issue in a fresh project (downloaded the sample, added urp, changed material to URP/Lit) but didnt get the error anymore so closing it. Sorry for the troubel!
