### ISSUE TITLE
ARFoundation 4.0 support ARKit3.5 (for LiDAR sensor)?

### ISSUE THREAD

**Issue by clifflinmao** [Unity-Technologies/arfoundation-samples#455]
I would like to ask if ARFoundation 4 already have the support of ARKit3.5, which take advantage. of the latest LiDAR sensor from iPad pro 2020. From the document I didn't find any information. Please confirm, Thanks.

**Comment by clifflinmao** [comment]
I have tested it. I think so. The plain detection sample is insanely faster than the one without LiDAR.

**Comment by sam598** [comment]
Plane detection, body occlusion and skeletal tracking are all greatly improved with the lidar sensor without having to update the SDK. The SDK needs to be updated to include newer features like scene reconstruction, but Unity is planning to release that update soon.

https://github.com/Unity-Technologies/arfoundation-samples/issues/435
