### ISSUE TITLE
AR Foundation Image Tracking plus Plane Detection incoherence

### ISSUE THREAD

**Issue by jairovskaya** [Unity-Technologies/arfoundation-samples#456]
Hi. Thanks for the efforts putting together ARFoundation for Unity. I'm putting image detection and image tracking in order to have paper cards on a table interacting with digital objects. But looks like image tracking has a different origin point when is called within the plane detection. Can someone help me explaining what is happening here and also how can I reconcile both origin points? I'd appreciate any help.

![plane-detection-vs-image-tracking](https://user-images.githubusercontent.com/50005193/79673613-28eb3b80-8190-11ea-91d0-764b72e47b0f.gif)

**Comment by mdurand42** [comment]
Hi-

Could you please explain the problem in a bit more detail? Image detection and plane detection are  independent from one another. Specifically, we would like to know what you mean by this:

> image tracking has a different origin point when is called within the plane detection

And the GIF you attached doesn't seem to include any detected planes.

-Mike

**Comment by jairovskaya** [comment]
Hi Mike.
Thanks for the prompt response.
Here I'm adding a frame from the video where shows more visually the issue.
Is it because the plane detection is "estimating" the surface? versus the
image tracking which is actually the real physical reference?
I appreciate the job you guys are doing with Unity and AR foundation, hope
this helps to create features that allow to create more products.

[image: image.png]

Jairo Fula

**Comment by mdurand42** [comment]
Hi-

Please make sure that your anchor is being attached to a plane and not a feature point. You would want to adjust the paramaters of this call: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.2/api/UnityEngine.XR.ARFoundation.ARRaycastManager.html#UnityEngine_XR_ARFoundation_ARRaycastManager_Raycast_Ray_System_Collections_Generic_List_UnityEngine_XR_ARFoundation_ARRaycastHit__TrackableType_

Feel free to post your code if this doesn't clear things up.

-Mike
