### ISSUE TITLE
ARKit infinite import loop going from 2.19 straight to 4

### ISSUE THREAD

**Issue by muppster** [Unity-Technologies/arfoundation-samples#457]
Upgrading ARKit 2.19 (verified) straight to preview 4 causes recursion during import in Unity 2019.3.0f6, on reloading the project console reports:

"An infinite import loop has been detected. The following Assets were imported multiple times, but no changes to them have been detected. Please check if any custom code is trying to import them:
Packages/com.unity.xr.arkit/Runtime/ARKitReferencePointSubsystem.cs - (Force Reimport)"

Upgrading ARKit 2.19 to 3.0.1 then to 4 works fine.

**Comment by mdurand42** [comment]
Thank you  for reporting this. I will try to duplicate this and will investigate a fix.

**Comment by tdmowrer** [comment]
This has been fixed in [4.1.0-preview.6](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/changelog/CHANGELOG.html#fixes) and will be backported to 4.0 as well.
