### ISSUE TITLE
The AROcclusionManager property humanStencilTexture returns an empty byte array

### ISSUE THREAD

**Issue by nicholasmaurer** [Unity-Technologies/arfoundation-samples#458]
The AROcclusionManager property humanStencilTexture returns an empty byte array when I call GetRawTextureData on the humanStencilTexture object.

**Comment by tdmowrer** [comment]
The stencil texture only exists on the GPU (it's an "external" texture). You must first read the data back to the CPU in order to be able to read the raw texture data. See [AsyncGPUReadback](https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadback.html).
