### ISSUE TITLE
Loading a GameObject from AssetBundle crashes the app on a new Image detected

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#459]
I have an AR App in which I have multiple tracked images and a specific GameObject in the AssetBundle associated with them.

When I start my app and I detect an Image, it works as intended, however, when I go on to detect another Image, the app crashes.

Here's my code:

`[RequireComponent(typeof(ARTrackedImageManager))]
public class MultiTrackedImageManager : MonoBehaviour
{
 
    public static MultiTrackedImageManager Instance { get { return instance; } }
    private static MultiTrackedImageManager instance;
 
    private ARTrackedImageManager m_TrackedImageManager;
    private string currentGO;
    private string lastGO;
    private string currentPrfb;
    private string lastPrfb;
    private GameObject curobject;
    private string PREFABFOLDER = "Prefabs/";
 
    AssetBundle myLoadedAssetBundle;
    private string imageName;
    private GameObject prefabToLoad;
 
    private GameObject prefab;
    public List<MultiTrackedImage> Images = new List<MultiTrackedImage>();
 
    private void Awake()
    {
        if (instance != null) { Destroy(instance); }
        instance = this;
        m_TrackedImageManager = GetComponent<ARTrackedImageManager>();
        curobject = null;
        LoadAssetFromBundle();
    }
 
    void OnEnable()
    {
        m_TrackedImageManager.trackedImagesChanged += OnTrackedImagesChanged;
    }
 
    void OnDisable()
    {
        m_TrackedImageManager.trackedImagesChanged -= OnTrackedImagesChanged;
    }
 
    void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
    {
 
        foreach (var trackedImage in eventArgs.updated)
        {
            OnImageUpdated(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
        }
 
        foreach (var trackedImage in eventArgs.added)
        {
            OnImageAdded(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
        }
    }
 
    public void OnImageUpdated(string textureName, string name, ARTrackedImage m_ARTrackedImage)
    {
 
        for (int i = 0; i < Images.Count; i++)
        {
            //if we have a match for the object and we have regained tracking and the current object is not the one for the trigger we just found
            if (m_ARTrackedImage.trackingState == TrackingState.Tracking)
            {
 
                //this checks to make sure we are tracking the right image target
                if (!string.Equals(Images[i].target.name, textureName)) { continue; }
 
                //this checks to see if our current object is equal to the name of the image target so we don't delete and duplicate
                if (string.Equals(curobject.name, Images[i].target.name)) { continue; }
 
                //for some reason we are getting updates from non visible targets
                if (curobject != null) { Destroy(curobject); }
 
                GameObject go = GameObject.Find(name);

                imageName = Images[i].path;
                //InstantiateObjectFromBundle(imageName);
                if (prefab != null) { Destroy(prefab);  }
                prefab = myLoadedAssetBundle.LoadAsset<GameObject>(imageName);
                Resources.UnloadUnusedAssets();
 
                //Instantiate the prefab with the position of go
                GameObject target = Instantiate(prefab, go.transform.position, Quaternion.identity);
 
                curobject = target;
                curobject.name = Images[i].target.name;
 
                TextManager.s.txtContent1 = Images[i].txt1 == "" ? "  " : Images[i].txt1;
                TextManager.s.txtContent2 = Images[i].txt2 == "" ? "  " : Images[i].txt2;
                TextManager.s.ResetText();
 
                Images[i].go = go;
                target.transform.rotation = go.transform.rotation;
                target.transform.SetParent(go.transform);
                target.transform.localPosition = Vector3.zero;
            }
        }
    }
 
    public void OnImageAdded(string textureName, string name, ARTrackedImage m_ARTrackedImage)
    {
 
        //PrefabManager.s.ClearPrefabs();
        for (int i = 0; i < Images.Count; i++)
        {
            if (string.Equals(Images[i].target.name, textureName) && Images[i].go == null)
            {
                //Destroy the existing AR Animation
                if (curobject != null) { Destroy(curobject); }
 
                GameObject go = GameObject.Find(name);

                imageName = Images[i].path;

                if (prefab != null) { Destroy(prefab); }
                prefab = myLoadedAssetBundle.LoadAsset<GameObject>(imageName);
                Resources.UnloadUnusedAssets();
 
                //Instantiate the prefab with the position of go
                GameObject target = Instantiate(prefab, go.transform.position, Quaternion.identity);
 
                curobject = target;
                curobject.name = Images[i].target.name;
 
                TextManager.s.txtContent1 = Images[i].txt1 == "" ? "  " : Images[i].txt1;
                TextManager.s.txtContent2 = Images[i].txt2 == "" ? "  " : Images[i].txt2;
                TextManager.s.ResetText();
 
                Images[i].go = go;
                target.transform.rotation = go.transform.rotation;
                target.transform.SetParent(go.transform);
                target.transform.localPosition = Vector3.zero;
            }
        }
    }
 
    void LoadAssetFromBundle()
    {
        StartCoroutine(DownloadAssetBundle());
    }
 
    IEnumerator DownloadAssetBundle()
    {
        var uwr = UnityWebRequestAssetBundle.GetAssetBundle("https://brain.rs/rkd/prefabbundletest");
        yield return uwr.SendWebRequest();
 
        if (uwr.isNetworkError || uwr.isHttpError)
        {
            Debug.Log(uwr.error);
        }
        else
        {
            // Get an asset from the bundle and instantiate it.
            myLoadedAssetBundle = DownloadHandlerAssetBundle.GetContent(uwr);
            if (myLoadedAssetBundle == null)
            {
                Debug.Log("Failed to load AssetBundle!");
            }
        }
    }
}`

**Comment by mdurand42** [comment]
Can you please attach the log output that contains crash information?

**Comment by Sterling-Malory-Archer** [comment]
> Can you please attach the log output that contains crash information?

Hi Mike, unfortunately, a few days ago the phone I used for testing which was ARCore compatible broke, and my current one doesn't support it. 

So I cannot attach the log output because I cannot perform an image detection.

**Comment by mdurand42** [comment]
> > Can you please attach the log output that contains crash information?
> 
> Hi Mike, here is a log output file
> 
> [log.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/4546644/log.txt)

Those error messages would lead me to believe that it wouldn't even work the first time. Could you try rebuilding your project using Mono instead of IL2CPP? That would get you past the code stripping issue.
