### ISSUE TITLE
Linear color space shader

### ISSUE THREAD

**Issue by Leiong** [Unity-Technologies/arfoundation-samples#46]
Hi,Unity
The ARKit plugin has two shaders for gamma color space and linear color space. Arfoundation is only available for gamma color space shaders. Unfortunately, my project uses linear space. How can I solve this problem?
![36cbf8d48a421e774969f7e2f7b7d59b](https://user-images.githubusercontent.com/41097890/45695427-f6342800-bb93-11e8-90fd-369782379fd3.png)
![ee1133238da5e26e7b61c14c75cf785a](https://user-images.githubusercontent.com/41097890/45695434-f92f1880-bb93-11e8-9daf-927dcb2a5bc6.png)

**Comment by tdmowrer** [comment]
You can override the ARCameraBackground with a [custom material](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARCameraBackground.html#UnityEngine_XR_ARFoundation_ARCameraBackground_customMaterial). The linear color space shader from the `UnityARKit` plugin should work.

**Comment by Leiong** [comment]
Hi，@tdmowrer 
The linear color space shader from the UnityARKit plugin should work, but the color of the lens rendering is wrong, which will lead to overexposure. The linear Shader using the ARKIT plugin can fix this problem, I tried to override the ARCameraBackground with a custom material. It seems to have no effect.

**Comment by Leiong** [comment]
Hi, @tdmowrer 
I've sent you an email with a replication;I hope you can help me, thank you.

**Comment by Leiong** [comment]
@tdmowrer that resolves it!Thank you!

**Comment by tdmowrer** [comment]
3.0.0-preview.3 now supports both linear and gamma color spaces.
