### ISSUE TITLE
Resolution and changing framerate

### ISSUE THREAD

**Issue by amir989** [Unity-Technologies/arfoundation-samples#460]
Unity Version 2019.3.0f3
ARFoundation 3.1 & 4
Iphone Xs

Hi guys,
I have 2 questions and 1 bug report.

1- When Im using front camera, the maximum resolution I can get is 1440x1080 60fps. However, other selfie apps are getting 1908x3392. I'm making a selfie app, and camera resolution is important for me.
I was wondering if this is a limitation by Unity or ARKit? and is there any way to access to a higher res?

2- Application.TargetFramerate doesnt effect immediately! it usually takes 10-15 sec to change framerate from 60 to 30 or the other way when using ARfoundation.(Match FrameRate is checked) 
My question is what makes the 10-15 sec delay? 

Bug report is for ARFoundation 4. [CameraConfigController](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scripts/CameraConfigController.cs)'s dropdown shows weird information which you can see it [here](https://ibb.co/Ns7zf4n). 

Cheers

**Comment by mdurand42** [comment]
1) The resolution is constrained by ARKit and cannot be changed

2) The delay you are seeing is likely the amount of time it takes for ARKit to throttle the framerate lower to avoid overheating. We suggest not attempting to set the frame rate if you have Match Framerate checked. (and we recommend leaving it checked)

**Comment by amir989** [comment]
Thank you so much for the answer. you guys are great. you can close the ticket!

Just one note on side, where would be best place to put a comment for Apple, to see if they can revise the resolution?

**Comment by tdmowrer** [comment]
> where would be best place to put a comment for Apple, to see if they can revise the resolution?

You can send Apple feedback using https://feedbackassistant.apple.com/
