### ISSUE TITLE
ARCore Setting Up Separate Prefab for Different Image Targets

### ISSUE THREAD

**Issue by lasersharkkiller** [Unity-Technologies/arfoundation-samples#462]
I am trying to create an AR app that places different prefabs for the different images contained in my ReferenceImageLibrary. The only solution I seem to have come across is in the link below, but I don't see where the script in reference is. Is there a good example showing creating different prefabs for different image targets? The end goal is my son and I have been dabbling with the Unity tutorials and he wants to set up trading cards that have little augmented characters that pop up. I'm not a developer by trade though I do work in IT so I'm a bit rusty in coding but it's not foreign to me. 
First post in reference: https://github.com/Unity-Technologies/arfoundation-samples/issues/157
Unity post sort of possibly having a solution but seems more for ARKit (iOS), possibly resolved in a later update: https://forum.unity.com/threads/arfoundation-2-image-tracking-with-many-ref-images-and-many-objects.680518/#post-4668326

However, I dont see the script in reference? Is there a good how to?

**Comment by tdmowrer** [comment]
Each reference image has a string name that you assign it, as well as a GUID that is assigned automatically. GUIDs are better for performance, but strings may be easier to work with if you are just prototyping.

Like all [trackable managers](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/trackable-managers.html), the [`ARTrackedImageManager`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/tracked-image-manager.html) has an [event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html?q=artrackedimage#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged) you can subscribe to that tells you when an image is first detected and subsequently updated.

You can use this event to instantiate your content. For example:
```csharp
void Start()
{
    GetComponent<ARTrackedImageManager>().trackedImagesChanged += OnTrackedImagesChanged;
}

void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
{
    foreach (var trackedImage in eventArgs.added)
    {
        switch (trackedImage.referenceImage.name)
        {
            case "MyFirstImage":
                Instantiate(prefabForMyFirstImage, trackedImage.transform);
                break;
            case "MySecondImage":
                Instantiate(prefabForMySecondImage, trackedImage.transform);
                break;
            // ... etc
        }
    }
}
```

This will instantiate your prefabs as children of the `ARTrackedImage`. That means whenever the tracked image is updated, your content will move with it. If that is not desired, you can instantiate it where ever you like.

**Comment by lasersharkkiller** [comment]
For placement of the script, does it mean that I would replace the AR Tracked Image Manager Script (a component under AR Session Origin) with the script above? Also, if you want to be able to track multiple objects at the same time, do you just remove the break statements or is it more complicated?

**Comment by tdmowrer** [comment]
No, don't replace the tracked image manager. The snippet I posted is meant to be part of a new MonoBehaviour that you author. Note that it requires the existence of the ARTrackedImageManager on the same GameObject.

> Also, if you want to be able to track multiple objects at the same time, do you just remove the break statements or is it more complicated?

The snippet handles multiple objects the way it is.

**Comment by lasersharkkiller** [comment]
I'm sorry I'm having a little trouble following.. by new MonoBehavior, is that a new C# script which becomes an additional component in AR Session Origin? I tried doing doing that but seem to be having some trouble.

**Comment by tdmowrer** [comment]
>by new MonoBehavior, is that a new C# script which becomes an additional component in AR Session Origin?

Yes. In the Project window, Right click > Create > C# Script. This creates a new C# file with an empty implementation of a `MonoBehaviour`.

>  I tried doing doing that but seem to be having some trouble.

What was the issue?

**Comment by lasersharkkiller** [comment]
I created the script, replaced the Start() and Update() functions with the script above, and replace "MyFirstImage/MySecondImage" with the image names, and prefabs with the prefab image names. I then add this script as a component to the AR Session Origin. I then get an error at the bottom saying the type or anmespace name 'ARTrackedImagesChangedEventArgs' could not be found (are you missing a using directive or an assembly reference?)

**Comment by lasersharkkiller** [comment]
*I also set TrackedImagePrefab to None as I assume this would have conflicting logic under the AR Tracked Image Manager script.

**Comment by tdmowrer** [comment]
> I then get an error at the bottom saying the type or anmespace name 'ARTrackedImagesChangedEventArgs' could not be found (are you missing a using directive or an assembly reference?)

ARFoundation is in the `Unity.XR.ARFoundation` namespace.

> *I also set TrackedImagePrefab to None as I assume this would have conflicting logic under the AR Tracked Image Manager script.

This is probably what you want in this case. The prefab field on the tracked image manager is optional, and I generally wouldn't recommend using it to instantiate your content -- you may not want your content to update with the image, or you may want to put it somewhere else completely, or you may want to simply trigger additional behavior based on the detected image.

**Comment by lasersharkkiller** [comment]
I compared it to the ARTrackedImageManager script and I think that means I needed to add "using UnityEngine.XR.ARFoundation;" at the top, but then I get 'prefab1' does not exist in the current context?

**Comment by tdmowrer** [comment]
How have you defined `prefab1`?

**Comment by lasersharkkiller** [comment]
By define I set the name on the prefab itself, is there something else I need to do?

**Comment by tdmowrer** [comment]
From

> I get 'prefab1' does not exist in the current context

It sounds as though you've written `prefab1` as a variable in your script. However, from

> By define I set the name on the prefab itself

It sounds like you have simply named the prefab `prefab1` in the Editor. Could you post the code for your script?

**Comment by lasersharkkiller** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.ARFoundation;

public class ARTrackedMultiple : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        GetComponent<ARTrackedImageManager>().trackedImagesChanged += OnTrackedImagesChanged;
    }

    void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
    {
        foreach (var trackedImage in eventArgs.added)
        {
            switch (trackedImage.referenceImage.name)
            {
                case "target1":
                    Instantiate(prefab1, trackedImage.transform);
                    break;
                case "target2":
                    Instantiate(prefab2, trackedImage.transform);
                    break;
                    // ... etc
            }
        }
    }
}

**Comment by tdmowrer** [comment]
You have not defined the variables `prefab1` or `prefab2` in your code, so the compiler error ```prefab1 does not exist in the current context``` is accurate. If you add them as public member fields to your class, they will become editable fields in the Unity inspector and you can assign whatever prefab you like:

```csharp
public class ARTrackedMultiple : MonoBehaviour
{
    public GameObject prefab1;
    public GameObject prefab2;

    // Start is called before the first frame update
    void Start()
    {
        GetComponent().trackedImagesChanged += OnTrackedImagesChanged;
    }
...
```

If this is new territory for you, I recommend going through some basic C#-in-Unity tutorials. There is a ton of learning material on Unity's website, e.g. https://unity3d.com/learning-c-sharp-in-unity-for-beginners, as well as YouTube.

**Comment by lasersharkkiller** [comment]
I added the variable declarations and I am able to compile but it doesnt recognize the images?

**Comment by lasersharkkiller** [comment]
Woops, didnt see that in the component there was now an option to assign the prefabs, I thought by using the prefab name it assigned it. Working now, thank you!!

**Comment by tdmowrer** [comment]
Great! I'll close this issue for now. Feel free to ask more questions as they come up. Note for general programming-in-Unity questions, you might also try https://forum.unity.com/forums/scripting.12/
