### ISSUE TITLE
3.1 Branch — LightEstimation incompatible with ARF 3.1.3

### ISSUE THREAD

**Issue by JasonRTBond** [Unity-Technologies/arfoundation-samples#463]
I tried pulling only LightEstimation.cs from the 3.1 branch and found it is not compatible with ARF 3.1.3. Rather, it seems to be the sample for ARF 4.0?

The one in the 3.0 branch seems to work fine.

**Comment by tdmowrer** [comment]
Can you explain what doesn't work properly?

**Comment by JasonRTBond** [comment]
Of course. Pardon the lack of details!

Here's the exact file I'm pulling: https://raw.githubusercontent.com/Unity-Technologies/arfoundation-samples/3.1/Assets/Scripts/LightEstimation.cs

Below I've attached the current Package Manager view of which version of ARF I have in the project, and a console log showing a variety of compile errors.

<img width="291" alt="Screen Shot 2020-04-27 at 17 32 25" src="https://user-images.githubusercontent.com/2727461/80423027-35b51100-88ad-11ea-8b2b-492f9e905140.png">
<img width="1239" alt="Screen Shot 2020-04-27 at 17 32 10" src="https://user-images.githubusercontent.com/2727461/80423033-364da780-88ad-11ea-95b8-44b001c824bd.png">

**Comment by JasonRTBond** [comment]
This file, on the other hand, works fine with ARF 3.1.3: https://raw.githubusercontent.com/Unity-Technologies/arfoundation-samples/3.0/Assets/Scripts/LightEstimation.cs

**Comment by DavidMohrhardt** [comment]
Branch updated.
