### ISSUE TITLE
Black Screen - NormalMeshing scene

### ISSUE THREAD

**Issue by danlee-lils** [Unity-Technologies/arfoundation-samples#468]
I am seeing a black screen on all three scenes in Meshing example. Any thoughts?

Device: iPad Pro (2020) with latest iOS
ARfoundation and ARKit plugin 4.0.0 preview 3
Unity 2020.1.0b8

Thanks!

**Comment by tdmowrer** [comment]
The meshing samples work for us in 2020.1.

1. Do any other samples have this problem?
1. Have you made any modifications to the samples?
1. Could you provide the console log from Xcode?

**Comment by danlee-lils** [comment]
I

**Comment by tdmowrer** [comment]
No problem! Glad it was something simple :)
