### ISSUE TITLE
Detecting if ARTrackedImage is off the screen?

### ISSUE THREAD

**Issue by YoungRichi** [Unity-Technologies/arfoundation-samples#469]
Hello,

Can AR foundation check when an AR tracked image is off the screen?

From my understanding, the reference image is like a trigger. It gets triggered when AR camera recognizes an image target. 

For example, I have an "ImageTrackingManager" script.
It spawns a prefab when it "sees" a reference image from the library. 
Is it possible to check when a reference image is no longer in the camera?

I want to remove the prefab from world when the image target disappears.
In order to do that, I'd have to somehow "unsee"  a reference image? Maybe binding an event to "trackedImageChanged"?

Is that possible? Could that be a feature for future updates?

All suggestions are welcomed. Thank you.

**Comment by tdmowrer** [comment]
No, but the tracking state is somewhat correlated with visibility. See https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html#determining-when-an-image-is-visible for an explanation.

**Comment by YoungRichi** [comment]
Thank you for answering!

Do the tracking state changes to  ```TrackingState.Limited``` when an object is blocking a tracked image? Lets say if i cover the tracked image with my palm. 

Theoretically, I can then turn off the Prefab with ```setActive(false)``` if the tracked image is not visible. Is that correct?

**Comment by tdmowrer** [comment]
> Do the tracking state changes to TrackingState.Limited when an object is blocking a tracked image? Lets say if i cover the tracked image with my palm.

I don't have anything to add to the docs I already linked, but I'll repeat them here. Please let me know they are not clear on this point:
> There is no API to determine the visibility of an image. Generally, if the tracking state is Tracked, it will likely change to Limited when the image is not visible. 

> Theoretically, I can then turn off the Prefab with setActive(false) if the tracked image is not visible. Is that correct?

Yep.

**Comment by YoungRichi** [comment]
Thank you Tim!
