### ISSUE TITLE
AR Tracked Object Manager is not present in AR Foundation 3.1.3

### ISSUE THREAD

**Issue by menfra** [Unity-Technologies/arfoundation-samples#471]
Hi @tdmowrer, did AR Foundation remove the **AR Tracked Object Manager** support from AR Foundation? I cannot find it after updating to AR foundation 3.1.3

The AR Tracked Object Manager is absent.
![trackedManager](https://user-images.githubusercontent.com/33913399/81740460-49f83100-949d-11ea-83bb-bb1debb67f6a.png)

The Reference Object Library is absent.
![refLib](https://user-images.githubusercontent.com/33913399/81740679-a3606000-949d-11ea-857b-2c6849b483e4.png)

**Comment by tdmowrer** [comment]
This feature uses an experimental UnityEngine API ([ScriptedImporter](https://docs.unity3d.com/ScriptReference/Experimental.AssetImporters.ScriptedImporter.html)). Verified packages cannot use experimental APIs, so it is only available in the preview packages. It is present, for example, in 3.1.0-preview.8 (latest 3.1 preview) and 4.0.0-preview.3 (latest 4.0 preview).

**Comment by menfra** [comment]
Thanks a lot
