### ISSUE TITLE
3.1 branch isn't using 3.1.3

### ISSUE THREAD

**Issue by maximeLong** [Unity-Technologies/arfoundation-samples#473]
When you download the 3.1 branch (which I assume is the current stable version of this sample library, as 4.0 is still in preview), it is based on 3.1.0 preview-8, instead of 3.1.3. I'm guessing this has various side-effects for people that attempting to port features from the sample library into their own project, for instance I just ran into an issue where LightEstimation.cs from the sample library no longer uses the correct values in 3.1.3. 

Is there a reason that the 3.1 branch isn't based around 3.1.3? It's already somewhat confusing navigating the changes that ARFoundations makes across versions, and having the sample library use an outdated version only adds another layer of confusion to the mix.

**Comment by tdmowrer** [comment]
Dup of #463

**Comment by maximeLong** [comment]
@tdmowrer I'm asking for insight on why the 3.1 branch of this library isn't using 3.1.3. I was using LightEstimation.cs as an example of potential issues that could arise due to these version differences, not trying to make this thread about that issue in particular.

**Comment by tdmowrer** [comment]
Right, and I know it's not light estimation-specific. The action item for us is to update the 3.1 branch to the verified version of the packages.

**Comment by maximeLong** [comment]
Great, thank you. I didn't understand that from your comment.

**Comment by maximeLong** [comment]
I think it makes sense from a community standpoint to keep this issue open until 3.1 branch is updated to 3.1.3, in case other people that run into problems can cross reference that this isn't the cause for them. The other thread does not make it clear that the 3.1 branch is behind the verified version.
