### ISSUE TITLE
"ARCore Supported" (Player Settings > XR Settings) refers to the built-in ARCore support in Unity and conflicts with the "ARCore XR Plugin" package.

### ISSUE THREAD

**Issue by hamza-alsawy** [Unity-Technologies/arfoundation-samples#474]
i made a small GPS AR application .. no error appears when i Run the application but with a black screen from the AR camera. However, when i build the application errors show up for the AR Core Plugin. 

BuildFailedException: "ARCore Supported" (Player Settings > XR Settings) refers to the built-in ARCore support in Unity and conflicts with the "ARCore XR Plugin" package.
UnityEditor.XR.ARCore.ARCorePreprocessBuild.EnsureARCoreSupportedIsNotChecked () (at Library/PackageCache/com.unity.xr.arcore@2.1.8/Editor/ARCoreBuildProcessor.cs:59)
UnityEditor.XR.ARCore.ARCorePreprocessBuild.OnPreprocessBuild

![bild error](https://user-images.githubusercontent.com/52302831/81932692-bcdce580-961e-11ea-9377-89f16a34db75.PNG) 
![ARcore](https://user-images.githubusercontent.com/52302831/81932649-ae8ec980-961e-11ea-98ec-2440489dac2f.PNG)
![optional](https://user-images.githubusercontent.com/52302831/81932651-afbff680-961e-11ea-8cb8-6477440b474e.PNG)
![XR](https://user-images.githubusercontent.com/52302831/81932653-b0588d00-961e-11ea-87ef-b028bd0490d0.PNG)

**Comment by tdmowrer** [comment]
The error is telling you to uncheck the "ARCore supported" checkbox as it is not compatible with the ARCore package.

**Comment by hamza-alsawy** [comment]
> The error is telling you to uncheck the "ARCore supported" checkbox as it is not compatible with the ARCore package.

i uninstalled them and reinstall the ARCore but still all the same. how can i make it compatible ... can i change in the configuration code to match the ARCore package.

**Comment by mdurand42** [comment]
> > The error is telling you to uncheck the "ARCore supported" checkbox as it is not compatible with the ARCore package.
> 
> i uninstalled them and reinstall the ARCore but still all the same. how can i make it compatible ... can i change in the configuration code to match the ARCore package.

If you are not using the AR Foundation API you should just remove the ARCore XR Plugin from your project along with the AR Foundation package.

If you are using AR Foundation APIs then keep the packages as they are and remove Google's ARCore SDK from your project.

Google's ARCore SDK is not compatible with Unity's package-based approach. You will need to choose one of these two APIs and exclude the other.

**Comment by imanirajdoost** [comment]
> > > The error is telling you to uncheck the "ARCore supported" checkbox as it is not compatible with the ARCore package.
> > 
> > 
> > i uninstalled them and reinstall the ARCore but still all the same. how can i make it compatible ... can i change in the configuration code to match the ARCore package.
> 
> If you are not using the AR Foundation API you should just remove the ARCore XR Plugin from your project along with the AR Foundation package.
> 
> If you are using AR Foundation APIs then keep the packages as they are and remove Google's ARCore SDK from your project.
> 
> Google's ARCore SDK is not compatible with Unity's package-based approach. You will need to choose one of these two APIs and exclude the other.

That solved my problem, just make sure to remove the Google ARCore Plugin using the Unity Package Manager.

**Comment by douuleii** [comment]
i have the same problem,when i Run the application but with a black screen from the AR camera.Did you finally solve the black screen problem?
