### ISSUE TITLE
ImageTracking is not working on iOS 13.4.1

### ISSUE THREAD

**Issue by AhmedBnAmor** [Unity-Technologies/arfoundation-samples#475]
I'm trying to use ImageTracking sample provided in this repo. No modifications in the code, just clone and build.

It works perfectly fine on Android devices, however on iOS nothing is shown and it dosen't seem to recognize the ReferenceImage. What can possibliy be the cause of this behavior ?

I'm using iPhone 8 on iOS 13.4.1
Unity 2019.3.11f1

**Comment by tdmowrer** [comment]
None of the branches in this repo use 3.1.3; if you haven't made any modifications, how are you using a different package version?

**Comment by AhmedBnAmor** [comment]
I was unclear in my OP, what I meant is: I tried first with Unity 2019.3.11f1 and ARKit XR Plugin 3.1.3 but my code didn't work, so I tried using the sample project (I'm not sure which version it is using)

**Comment by mdurand42** [comment]
We will verify that the sample is working with older iOS devices.

**Comment by tdmowrer** [comment]
I just tried the [`ImageTracking`](https://github.com/Unity-Technologies/arfoundation-samples/tree/master/Assets/Scenes/ImageTracking) sample on the `master` branch of this repo, and it worked on an iPhone 6+ and iPhone 11. I tested a few iOS versions, including 13.4.1. 

Can you explain the behavior you're seeing in more detail? Do other features work (e.g., pass through video, world tracking)? Are there any errors or other relevant information in the Xcode console?

**Comment by AhmedBnAmor** [comment]
SimpleAR is working fine on the iphone.
I tried using examples directly from Apple (ARKit, without ARFoundation) to make sure that the issue is not from my device and these exmaples worked fine.

Steps I followed in my tests:
- clone the project directly from this repo (master branch)
- export project to Xcode and build (and build directly to Andoid)
- when running on the device, I point to the target Image (on my scrren, not printed)

Results:
- iphone shows nothing, no errors in the console
- android devices show Image Info (as intended with the example)

**Comment by tdmowrer** [comment]
What about the Xcode log? Could you post that?

**Comment by AhmedBnAmor** [comment]
I cannot post Xcode log currently because we are testing remotely (someone makes the build, upload to the store, and someone else downloads on his iphone to test) due to current lockdown status.

I will keep this issue updated once i can get Xcode logs

**Comment by mdurand42** [comment]
@AhmedBnAmor can you make sure that the physical size of the image you are trying to detect matches the size configured for that image? ARKit requires this whereas ARCore doesn't and it could account for the behavior you are seeing. Here is relevant documentation:
