### ISSUE TITLE
AR Foundation 4.0.0 - preview.3 rejected from App Store

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/arfoundation-samples#477]
Rejection message from Apple:

```
During review, we found that your app includes TrueDepth APIs. However, we were not able to locate any features in your app that use TrueDepth APIs.

Next Steps

If your app does not include any features that use TrueDepth APIs, please remove them from your app.

If your app uses the Unity ARKit plugin, it would be appropriate to update to the latest version, which includes a setting that allows you to exclude TrueDepth APIs.
```

Info about the app:

- AR Foundation, AR Subsystems, ARCore XR Plugin, and ARKit XR Plugin are all set to "preview.3 - 4.0.0"
- ARKit Face Tracking package is not installed
- ARKit Setting are set to required. There is no option to enable/disable face tracking.
- The app was previously getting approved with AR Foundation 3.0

**Comment by tdmowrer** [comment]
Looking into it.

**Comment by tdmowrer** [comment]
I have audited our codebase and there is no reference to face tracking APIs (this is what triggers the "TrueDepth API" error you received). Additionally, I submitted a test app to the app store and it passed this portion of the review.

Could you [file a bug](https://unity3d.com/unity/qa/bug-reporting) and attach your project? Post the bug id here when you do.

**Comment by sam598** [comment]
Brief update. I'm waiting on App Store to approve a new "clean" build to see if that fixes, but the approval times are (understandably) slower than usual. If it fails again I will file the bug with the attached project if I can get approval from client.

**Comment by doukasd** [comment]
Our app built on Unity 2019.3.5 and AR Foundation/ARKit XR plugin 4.0 preview 3 was just rejected today.

We are not using front facing camera APIs nor have we installed the ARKit Face Tracking plugin.

Any idea what the issue could be?

**Comment by tdmowrer** [comment]
@doukasd As I said, we are not using face tracking APIs, and our test app passes validation. Please [submit a bug](https://unity3d.com/unity/qa/bug-reporting) with your app so we can investigate further.

**Comment by doukasd** [comment]
Hi @tdmowrer thanks for the quick response. Can you point me to the test app that passes validation to make sure we are doing everything the same way?

Is it the project of this very [repo](https://github.com/Unity-Technologies/arfoundation-samples), with all scenes included that passes Apple review?

**Comment by doukasd** [comment]
Hmm, reading [the information on this repo](https://github.com/Unity-Technologies/arfoundation-samples#lightestimation) again it seems that Light Estimation could be the offending feature here?

```This sample also attempts to read HDR lighting information. On iOS, this is only available when face tracking is enabled and requires a device with a TrueDepth camera (such as an iPhone X, XS or 11). When available, a virtual arrow appears in front of the camera which indicates the estimated main light direction. The virtual light direction is also updated, so that virtual content appears to be lit from the direction of the real light source.```

We had actually enabled `Main Light Direction` and `Main Light Intensity` in the build that was rejected. We will remove those and try another build.

Would these features of Light Estimation work without having the `ARKit Face Tracking` package included though?

Thank you.

**Comment by DavidMohrhardt** [comment]
@doukasd No those features should not work in the scenario where ARKit Face Tracking is not present or enabled (they are only enabled in the ARKitFaceTracking package even if they are requested).  If your application had those settings enabled and they worked in your application then your application is using face tracking in some form, can you make sure that your library folder doesn't have any left over artifacts of face tracking?

**Comment by mdurand42** [comment]
@doukasd Also, please confirm that the Xcode project generated by Unity **does not** somehow have the Facetracking library in it:

<img width="342" alt="Screen Shot 2020-06-05 at 12 00 12 PM" src="https://user-images.githubusercontent.com/8888270/83913612-87f71680-a724-11ea-855d-717046497288.png">

**Comment by doukasd** [comment]
(At first sight, it seems that the app got approved after just completely disabling Light Estimation on the AR Camera. I am waiting for some final approval from Apple before reporting back.)

**Comment by mdurand42** [comment]
> (At first sight, it seems that the app got approved after just completely disabling Light Estimation on the AR Camera. I am waiting for some final approval from Apple before reporting back.)

That doesn't make a lot of sense if that turns out to be the case. We created a separate static library for the Face Tracking functionality specifically to segregate the API calls that the App Store cert process flags.

Did you verify that your Xcode project does not contain the _libUnityARKitFaceTracking.a_?

**Comment by doukasd** [comment]
Unfortunately, it's true, the app was now approved by Apple, without us making any other change to libraries included apart from disabling light estimation completely.

I have not had the time to check which libraries are included in a version with the feature enabled or disabled, but once I get the chance I will do that and report back.

**Comment by sam598** [comment]
My app never used light estimation, and it was still rejected for using TrueDepth APIs.

After doing a completely clean build of the XCode project the app was approved for public release. Nothing was changed in the Unity project. The app was never built with the face tracking package.

I am going to close this issue for now. Hopefully this was a fluke or something odd happening on Apple's end.

**Comment by sergiosolorzano** [comment]
Hey all,

Just had my app rejected by Apple for this same reason.

I'm on Unity 2019.4.1 ARF 4.0.2 ARKit XR plugin 4.0.1 and package manager also shows ARKit Face Tracking 4.0.1

Following @mdurand42 's recommendation I've also checked the Xcode project generated by Unity and indeed it does include a Facetracking library in it in iOS folder same as shown by @mdurand42 libUnityARKitFaceTracking.a

Should I remove the ARKit Face tracking package or does this break ARF?

Or should I just a raw right-click delete the ARKitFaceTracking library libUnityARKitFaceTracking.a from XCode project?

Thank you for your help

**Comment by DavidMohrhardt** [comment]
@sergiosolorzano as long as you are not using face tracking in your AR scenes then you can remove the arkit face tracking package with no problems.

**Comment by sergiosolorzano** [comment]
Thanks a bunch @DavidMohrhardt , in case someone wanted to follow up on this , response at https://github.com/Unity-Technologies/arfoundation-samples/issues/623

cheers!

**Comment by ariensaenger** [comment]
Hello quick question, I try to remove AR Kit Facetracking Plugin in the Package Manager because of a App Review Rejection, but it always reinstall itself automatically in Unity.

Is there any solution for this?
