### ISSUE TITLE
[QUESTION] Why the Anchors sample have a Plane Manager & a Point Cloud Manager?

### ISSUE THREAD

**Issue by Thomas-6freedom** [Unity-Technologies/arfoundation-samples#478]
Why the Anchors sample have a Plane Manager & a Point Cloud Manager?

Does adding theses Manager improve the tracking ?
If yes, why theses Managers are not in every samples ?
If no, why are they here ?

Thank you.

**Comment by tdmowrer** [comment]
Because the sample creates an anchor in response to a raycast, so it visualizes things you can raycast against, like planes and feature points (though I think that particular sample only raycasts against feature points).
