### ISSUE TITLE
Set local fbx file to Image tracked manager at runtime [Question]

### ISSUE THREAD

**Issue by ozankonur** [Unity-Technologies/arfoundation-samples#479]
Is there any way to set local fbx animation file to Image tracked manager at runtime ? I am trying to implement fbx files from server to local storage then display on AR session dynamically. Any suggestion ?

**Comment by mdurand42** [comment]
This isn't really an AR-related question so I would suggest asking on this forum:

https://forum.unity.com/forums/addressables.156/
