### ISSUE TITLE
how can i change camera in runtime?

### ISSUE THREAD

**Issue by KiDeokKim** [Unity-Technologies/arfoundation-samples#481]
hi, i'm trying to change camera in runtime for android device.
i want start scene back camera and if i click button, camera is restart and set front camera in runtime.
how can i change camera? i read this thread
[https://forum.unity.com/threads/arfoundation-switching-between-front-and-rear-camera.621793/](url)
so i tried find selection camera device(front and back), but i can't find settings.
i'm using unity version is 2019.3.8f1 and package is preview version - 4.0

**Comment by tdmowrer** [comment]
That thread is outdated; you can now request the front or rear camera explicitly. More information [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/migration-guide-3.html), and [here is some sample code](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/FaceTracking/ToggleCameraFacingDirection.cs) that shows how to do it.

**Comment by KiDeokKim** [comment]
ah, thanks to comment.
I found sample scene 'WorldCameraWithUserFacingFaceTracking'
