### ISSUE TITLE
Accessing Tracked Image Quality Score at runtime

### ISSUE THREAD

**Issue by jiungerich** [Unity-Technologies/arfoundation-samples#482]
I know ARCore has an image tool that gives a quality score for a tracked image and it is supposedly in their AR SDK for unity although I have had some trouble locating this or documentation on it other than a web page at the ARCore's site (https://developers.google.com/ar/develop/java/augmented-images/arcoreimg)  ARKit also mentions that it gives image quality feedback.  Is there a way to access these quality measurement tools at runtime?

It would be helpful to run as check before trying to add these to mutable runtimes reference library.  It would also just be helpful as a debug tool to know why images are not being picked up as easily.  I have noted images that get quickly detected in a regular reference library sometimes just do not get seen after being add to a runtime library even though it say they were added successfully.

**Comment by mdurand42** [comment]
Not all of the providers support the notion of a quality score and the ARKit assessment of image quality is only available from within Xcode. We will add this to our backlog of features and discuss with our partners how we can improve users' understanding of image quality at design time.
