### ISSUE TITLE
AR Object Drifting/Flying Away Issue

### ISSUE THREAD

**Issue by AQ1991** [Unity-Technologies/arfoundation-samples#483]
Hello,
I am new to AR development so sorry for this noob question, I am spawning an AR object in front of camera which is spawns fine, but when ever there is an abrupt fast movement of device in any direction the object starts drifting in random directions. Can anyone help me in this issue i have searched for quite sometime now i was unable to find the fix.

**For Object Spawning**

`prefabInstance = Instantiate(placeObject);
        GetComponent<ARSessionOrigin>().MakeContentAppearAt(prefabInstance.transform, new Vector3(0, -0.76f, 3.35f), Quaternion.identity);`

I want the abrupt movement because i need shake to shatter the object in pieces. After the object is in pieces i relocate them in a different areas.

**Relocation Code** 
`int temp = UnityEngine.Random.Range(0, ReferenceSpawnPoint.Length);
gObject.transform.position = new Vector3(ReferenceSpawnPoint[temp].position.x, ReferenceSpawnPoint[temp].position.y, ReferenceSpawnPoint[temp].position.z);
float y = UnityEngine.Random.Range(0, 360);
float z = UnityEngine.Random.Range(-10, 10);
gObject.transform.rotation = Quaternion.Euler(0, y, 0);`

Your help will be greatly appreciated.
Regards,
Abdul Qadir

**Comment by mdurand42** [comment]
None of the AR platforms we support can tolerate rapid shaking of the device as that would interfere with their computer vision and sensor algorithms. Sorry.

**Comment by AQ1991** [comment]
Thank you for your reply but some time this happens randomly. Post shaking of the mobile

**Comment by AQ1991** [comment]
Was able to fix the issue @mdurand42 if you violently shake the device the object is pinned to the screen but as soon as the mobile stabilizes it goes back again to its original position.
Here the is fix:

- First of all created a parent object and placed all my object that i am spawning in the parent.
- Added an Anchor point component to the parent
and updated my spawning code.

```
private void Update()
    {
        if (!hasSpanwed)
        {
            Ray ray = GetComponent<ARSessionOrigin>().camera.ViewportPointToRay(new Vector3(0.5F, 0.5F, GetComponent<ARSessionOrigin>().camera.farClipPlane));
            var hits = new List<ARRaycastHit>();
            if (GetComponent<ARRaycastManager>().Raycast(ray, hits, TrackableType.PlaneWithinPolygon))
            {
                hasSpanwed = !hasSpanwed;
                var hitPose = hits[0].pose;
                prefabInstance = Instantiate(placeObject, new Vector3(hitPose.position.x, hitPose.position.y, hitPose.position.z + 5), hitPose.rotation);
            }
        }
    }
```

**Comment by NGUYENTRUONGKHANH** [comment]
Hi @AQ1991 !
I also had the same problem as you! I have read your treatment but I don't understand it yet. Where will your "Spawning code" be attached?. Can you explain more clearly? 
Thank you very much!
