### ISSUE TITLE
Get Texture Coords From ARMeshManager?

### ISSUE THREAD

**Issue by yanivx4x** [Unity-Technologies/arfoundation-samples#485]
Hello,
I am using the ARMeshManager with ARFoundation 4.0.0  and marking the Texture Coordinates as true on the component (which of course means I want them to be generated).
After receiving all the new/updated mesh filters through the meshesChanged event I do not have anything in the uv property of the mesh or in the vertex attributes.

Am I missing something?
Thanks in advance!

**Comment by tdmowrer** [comment]
The ARMeshManager is platform agnostic, so it includes all the options you can ask for, but not all platforms support all features. ARKit (I assume you are testing on ARKit) does not supply texture coordinates for its meshes. See [ARMeshGeometry](https://developer.apple.com/documentation/arkit/armeshgeometry).

**Comment by yosun** [comment]
Just apply planar UV and project from video. I am surprised texturing has not been included as a sample since it is probably one of the most requested features for meshing.

**Comment by chaoslife** [comment]
will texturing for meshing be supported future?

**Comment by tdmowrer** [comment]
If Apple's ARKit supports it, then Unity will support it in our ARKit XR Plugin package. You can request this feature using Apple's [feedback assistant](https://feedbackassistant.apple.com/).

**Comment by MarcoLavoro** [comment]
> Just apply planar UV and project from video. I am surprised texturing has not been included as a sample since it is probably one of the most requested features for meshing.

There is an example to how to do it?

**Comment by MarcoLavoro** [comment]
> The ARMeshManager is platform agnostic, so it includes all the options you can ask for, but not all platforms support all features. ARKit (I assume you are testing on ARKit) does not supply texture coordinates for its meshes. See [ARMeshGeometry](https://developer.apple.com/documentation/arkit/armeshgeometry).

what devices supports ARMeshManager texture?

**Comment by tdmowrer** [comment]
I don't think any do at the moment.
