### ISSUE TITLE
No active UnityEngine.XR.ARSubsystems.XRParticipantSubsystem is available

### ISSUE THREAD

**Issue by AytoMaximo** [Unity-Technologies/arfoundation-samples#486]
Hello! 

I have an issue with AR CollaborationSession example. It worked fine on previous versions of ARFoundation/Unity, but now I can't get the ARParticipants' transforms (no prefab appears presenting the AR participant position). 

The error message on the startup is:  

> No active UnityEngine.XR.ARSubsystems.XRParticipantSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.

I don't know what kind of a setting I need to look for. 

Also I'm having spam of this message: 

> [Technique] Error getting pose for participant anchor: CMMapNotAvailable

...and also having something like this:

> 2020-05-26 01:14:52.053698+0300 samples[9137:2247306] [GCKSession] Not in connected state, so giving up for participant [64A3896D] on channel [0].
> 2020-05-26 01:14:52.063293+0300 samples[9137:2247306] [GCKSession] Not in connected state, so giving up for participant [64A3896D] on channel [1].
> 2020-05-26 01:14:52.071056+0300 samples[9137:2247306] [GCKSession] Not in connected state, so giving up for participant [64A3896D] on channel [2].
> 2020-05-26 01:14:52.077876+0300 samples[9137:2247306] [GCKSession] Not in connected state, so giving up for participant [64A3896D] on channel [3].
> 2020-05-26 01:14:52.084187+0300 samples[9137:2247306] [GCKSession] Not in connected state, so giving up for participant [64A3896D] on channel [5].
> 2020-05-26 01:14:52.089913+0300 samples[9137:2247306] [GCKSession] Not in connected state, so giving up for participant [64A3896D] on channel [6].

However, the AR anchor works still fine. 

Unity 2019.3.14f1, AR Foundation/ARKit 4.0 preview 3.

**Comment by tdmowrer** [comment]
As of 4.0.0-preview.3, ARFoundation now requires XR Management. See https://github.com/Unity-Technologies/arfoundation-samples/issues/484#issuecomment-632312749

**Comment by AytoMaximo** [comment]
> As of 4.0.0-preview.3, ARFoundation now requires XR Management. See [#484 (comment)](https://github.com/Unity-Technologies/arfoundation-samples/issues/484#issuecomment-632312749)

I know about this, I have ARKit plugin activated, my AR is working. But I have an issue with XRParticipantSubsystem

**Comment by tdmowrer** [comment]
Looks like the [`ARKitLoader`](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.0/api/UnityEngine.XR.ARKit.ARKitLoader.html) is indeed missing the `XRParticipantSubsystem`, so it never gets initialized. The fix will be in the next release. In the meantime, if you want to patch it locally, you can just add it to `ARKitLoader.cs`. You need a line like

```csharp
CreateSubsystem<XRParticipantSubsystemDescriptor, XRParticipantSubsystem>(s_ParticipantSubsystemDescriptors, "ARKit-Participant");
```

in `Initialize`.

**Comment by AytoMaximo** [comment]
> Looks like the [`ARKitLoader`](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.0/api/UnityEngine.XR.ARKit.ARKitLoader.html) is indeed missing the `XRParticipantSubsystem`, so it never gets initialized. The fix will be in the next release. In the meantime, if you want to patch it locally, you can just add it to `ARKitLoader.cs`. You need a line like
> 
> ```cs
> CreateSubsystem<XRParticipantSubsystemDescriptor, XRParticipantSubsystem>(s_ParticipantSubsystemDescriptors, "ARKit-Participant");
> ```
> 
> in `Initialize`.

Thx, it's OK now!

**Comment by Daniellb12** [comment]
Hey Tom,

I'm currently running into these errors below which are preventing me from running scenes with my webcam. I've tried your hot fix above and it didn't work. Any help would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/72151123/107430097-bd91a200-6af2-11eb-9b4f-14e9e1c7e29c.png)

**Comment by AdrianDot** [comment]
> Hey Tom,
> 
> I'm currently running into these errors below which are preventing me from running scenes with my webcam. I've tried your hot fix above and it didn't work. Any help would be greatly appreciated.
> 
> ![image](https://user-images.githubusercontent.com/72151123/107430097-bd91a200-6af2-11eb-9b4f-14e9e1c7e29c.png)

I have the same four error-messages in my project and it works fine. Maybe the webcam isn't working for another reason? :)

**Comment by Daniellb12** [comment]
> > Hey Tom,
> > I'm currently running into these errors below which are preventing me from running scenes with my webcam. I've tried your hot fix above and it didn't work. Any help would be greatly appreciated.
> > ![image](https://user-images.githubusercontent.com/72151123/107430097-bd91a200-6af2-11eb-9b4f-14e9e1c7e29c.png)
> 
> I have the same four error-messages in my project and it works fine. Maybe the webcam isn't working for another reason? :)

What's your current Unity version? I've had 16 people try from unity version 2019.4.13f1, unity version 2020.110f1, 2020.21f1, across mac, windows and , Ubuntu. 

Any help would be greatly appreciated. It works fine when pushed to device, just isn't able to access webcam for all 16 of those users.

**Comment by AdrianDot** [comment]
ARFoundation is only meant to be build on smartphones with either ARCore or ARKit. It's not working for pc webcams. Try Vuforia for your purpose :)

See: [https://stackoverflow.com/questions/61633914/how-to-use-pc-webcam-for-ar-foundation-in-unity]

**Comment by Daniellb12** [comment]
Interesting, because in early 2020 it was able to access my webcam without issue. Good to know, thanks Adrian.

**Comment by tdmowrer** [comment]
Unity has never provided webcam support for AR Foundation, but it is possible for someone outside of Unity to implement support. Perhaps you had another plugin in your project that implemented webcam support for AR Foundation?

**Comment by Daniellb12** [comment]
Maybe, haha I'll have to access my old archived files to see if I have the old project file. Thanks for clearing up the confusion. That said, is there anyway to clear those warnings? Also, sorry for calling you Tom, for some reason I read Tom instead of Tim. My apologies.

**Comment by tdmowrer** [comment]
There's a button to clear messages in the console, but there is no way to suppress the message if that is what you mean.

**Comment by Daniellb12** [comment]
Yeah I meant suppressing the warning's or if there might be a hot fix to just get rid of them besides clearing my console since that singular line of code above didn't work. Besides that you two have answered my questions. Thanks guys.

**Comment by tdmowrer** [comment]
To clarify: the warnings are telling you that AR isn't going to work because the current platform is not supported by any of the packages you currently have installed. It does not impact any other functionality, so other than unwanted log messages, there is nothing to "fix". Are you suggesting a change to this behavior?

**Comment by Paul995** [comment]
Hi all, I am having the same issue as the ones previously written. I tried the hotfix but it didn't work for me, I am still having a black screen on my phone while I try to build the AR application.
I have the following warnings:

![immagine_2021-08-25_150657](https://user-images.githubusercontent.com/37587240/130795936-7cd927b5-4005-4cd6-9a60-d1fdde052d3c.png)

**Comment by nory233** [comment]
I have the same warnings any help please?

**Comment by gteodoro1** [comment]
Did anyone manage to fix it? when i run the application it immediatly closes when i grant acces to camera, i don't know if those warnings are the reason.

**Comment by tdmowrer** [comment]
> Did anyone manage to fix it? when i run the application it immediatly closes when i grant acces to camera, i don't know if those warnings are the reason.

That's probably unrelated. App closing unexpectedly could be a crash. Have you checked logcat?

**Comment by gteodoro1** [comment]
I am using samsung dex, and i can't find any option to check the logcat, i tried some applications on the phone but they don't show the needed information, any recommendation would help.

**Comment by tdmowrer** [comment]
> Managed to fix it with the following :Build Settings > Player Settings
> Scripting set to IL2CPP
> Target Architecture check ARM64

ARCore does not officially support 32 bit on 64 bit devices, and a crash is expected in this case. From https://developers.google.com/ar/64bit:

> 32-bit-only ARCore-enabled apps that aren't updated will fail to create an ARCore session and might crash when attempting to start an augmented reality (AR) session on affected 64-bit devices.
