### ISSUE TITLE
ARSubsystemManager.systemStateChanged never reaches ARSystemState.SessionTracking on iOS

### ISSUE THREAD

**Issue by mj-rh** [Unity-Technologies/arfoundation-samples#49]
After the ARSession is deactivated and reactivated (ARSession.enabled), the status ARSystemState.SessionTracking is never reached on iOS.

reproduction:

- Open the SampleScene from ARFoundation
- Add a event on ARSubsystemManager.systemStateChanged which logs the state on Call
- Add two buttons to the scene
- one button to disable ARSession
- another button to enable the ARSession
- build the app for ios (with 2018.1.9f1)
- At first run the state changes from Ready to SessionInitializing to SessionTracking. After switch it only changes from Ready to SessionInitializing. But it is still functional and scans the environment and change and add planes. Only the PointCloud isnt visible.

On Android all is working fine.

**Comment by tdmowrer** [comment]
Closing this as the API mentioned is obsolete.
