### ISSUE TITLE
Camera Permission Request => Deny & Don't Ask Again => Black Screen on Android 10 & AR Foundation 3.1.3

### ISSUE THREAD

**Issue by andrewio** [Unity-Technologies/arfoundation-samples#491]
1. I have continuous permission request on every app start if I tap "Deny" in Dialog Windows with appropriate black screen on camera texture.

2. If I once tap "Deny & Don't Ask Again" then I have no Permission request further with continues black screen on camera texture on every app start.

I've found "permissionGranted" property of ARCameraManager here: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/api/UnityEngine.XR.ARFoundation.ARCameraManager.html

And guidelines are described here clearly for both: iOS & Android: https://github.com/yasirkula/UnityNativeCamera

But I want to hear your recommendation on How do I operate with these situations?
Any guidelines from AR Foundation team:

- On What stage of scene init I need to ask  "permissionGranted" property for both OS?
- Is there any events from AR Foundation that are dispatched when "Deny & Don't Ask Again" or "Deny" taps?
- Need I use https://github.com/yasirkula/UnityNativeCamera to be more flexible, say in separate scene before main scene with AR Foundation?
- and so on. 

Thank you.

**Comment by mdurand42** [comment]
We suggest presenting some sort of informational screen informing the user that the app is not useful without the camera permission being granted. You could then choose to terminate the app or whatever makes sense for your experience.

You should refer to this API for information on re-requesting and querying permissions:
https://docs.unity3d.com/Manual/android-RequestingPermissions.html

Just for your information: the "Don't Ask Again" feature is an Android feature and is not anything that Unity can control or be made aware of. Any subsequent requests for the permission will be denied without user prompting.
