### ISSUE TITLE
Image tracking fine on android but not iOS. 

### ISSUE THREAD

**Issue by kingbaggot** [Unity-Technologies/arfoundation-samples#492]
I cant get anything out of iOS with the AR tracked image manager - although it works fine with android. 

Have added my ar session & ar session origin, then attached the ar tracked image manager and linked it to my XRReferenceimagelibrary with some images (at the correct size of their printed out versions) .

This builds fine without errors on iOS & android. But ios version doesn't drop my tracked image prefab.( I'll add that plane detection works fine for me on ios )

I've tried this with 
AR foundation 2.1.8 , ARKit 2.1.9, ARCore 2.1.8, & AR subsystems & AR facetracking 
also
AR foundation 3.0 & the 3.0 versions of ARKit & ARCore 
also 
AR Foundation 3.1.0 preview 8 and the 3.1.0 prev. 8 versions of ARKit & ARCore.
  
Working with Unity 2019.3.10f - with ios 13.3.1 on  iphone7 and 13.4. on iphoneX 

Unity ios settings attached - this might be where I'm going wrong. Any help/pointers much appreciated - have blown all day on this :)

![iosUnitySettings](https://user-images.githubusercontent.com/4214940/83457798-4f6fe800-a459-11ea-8025-011b135c039e.jpg)

**Comment by kingbaggot** [comment]
looking into it - this may well be to do with building the xcode project on a pc, and then compiling that project on a mac (which is my usual pipeline)

Somewhere in this process the Image Tracking fails (although the plane detection/point clouds are fine) - possibly this will be to do with the image reference library ?

**Comment by mdurand42** [comment]
We do support that workflow but it's possible we have a regression. Could you please submit a bug for it from the Unity Editor? https://unity3d.com/unity/qa/bug-reporting

**Comment by DavidMohrhardt** [comment]
Closing in favor of the more universal https://github.com/Unity-Technologies/arfoundation-samples/issues/145
