### ISSUE TITLE
Execute LibUtil.SelectPlugin when editor loads instead of pre build to simplify generating assetbundles

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#493]
The ARKit plugin selects the right lib for your XCode in a pre build step. This is inconvenient because when building assetbundles before generating an xcode project (and therefore executing the LibUtil.SelectPlugin function) Unity complains about plugin duplication.

We have worked around this by executing the logic in SelectPlugin ourselves before generating bundles.

Ideally the SelectPlugin logic would be executed at an earier moment (when initialising the editor?) so we don't have to work around this issue. An alternative might be to no longer mark LibUtil as internal so we can call the static function ourselves at some point in our workflow without having to 'duplicate' it's functionality.

**Comment by tdmowrer** [comment]
> Ideally the SelectPlugin logic would be executed at an earier moment (when initialising the editor?)

It uses the version of Xcode selected in the Build Settings menu, so we don't know what version of Xcode is selected until you request to build.

ARFoundation 4.0 will soon drop support for Xcode 10, so this problem should go away when that happens.
