### ISSUE TITLE
Rotate Object towards Camera that are placed at the center of ARPlane

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#494]
I have a script in which an object is placed on a detected arPlane in the center of it, using AnchorManager.

I am trying to have the instantiated object be turned towards the camera, I currently have this code:

```cs
 public void OnImageAdded(string textureName, string name, ARTrackedImage m_ARTrackedImage)
    {

        //PrefabManager.s.ClearPrefabs();
        for (int i = 0; i < Images.Count; i++)
        {
            if (string.Equals(Images[i].target.name, textureName) && Images[i].go == null)
            {
                //Destroy the existing AR Animation
                if (curobject != null) { Destroy(curobject); }

                GameObject go = GameObject.Find(name);


                // Find the prefab game object by loading it from the PREFABFolder with the name matching the .path from Images[i]
                GameObject prefab = Resources.Load($"{PREFABFOLDER}{Images[i].path}") as GameObject;

                var anchorManager = GetComponent<ARAnchorManager>();
                anchorManager.anchorPrefab = prefab;

                Pose arPlanePose = new Pose(aRPlane.center, Quaternion.identity);

                var anchor = anchorManager.AttachAnchor(aRPlane, arPlanePose);
                GameObject target = anchor.gameObject;
                target.transform.LookAt(Camera.main.transform);

                curobject = target;
                curobject.name = Images[i].target.name;
            }
        }
    }
```

But when I call .LookAt(Camera.main.transform) it doesn't rotate it.

**Comment by mdurand42** [comment]
@Sterling-Malory-Archer For this scenario you should not place your content prefab in the Anchor Prefab field. You should instead instantiate your content prefab and make the Anchor gameobject your content's parent. Then call `transform.LookAt(Camera.main.transform);` on the content gameobject. Does that make sense?

**Comment by Sterling-Malory-Archer** [comment]
> @Sterling-Malory-Archer For this scenario you should not place your content prefab in the Anchor Prefab field. You should instead instantiate your content prefab and make the Anchor gameobject your content's parent. Then call `transform.LookAt(Camera.main.transform);` on the content gameobject. Does that make sense?

Hi Mike,

Would you please help me with an issue I am experiencing: When a user detects more than one AR Plane, the gameobject that I instantiate on the ARPlane, the gameobject sometimes starts to bounce between the 2, I can provide a link to the video if needed.

Also for the scenario that I wrote originally, would you be able to help me with the code?

Thank you in advance,

Strahinja

**Comment by drekin11** [comment]
Regarding the LookAt code, for the gameobject being instantiated, if it has a script on it, add the line:
transform.LookAt(Camera.main.transform); in the Update function, or just create a new script and add the line to the Update function.
Also, I think the camera has to have the tag 'main'/'MainCamera'.

**Comment by Sterling-Malory-Archer** [comment]
> Regarding the LookAt code, for the gameobject being instantiated, if it has a script on it, add the line:
> transform.LookAt(Camera.main.transform); in the Update function, or just create a new script and add the line to the Update function.
> Also, I think the camera has to have the tag 'main'/'MainCamera'.

The problem that I have is that I want the object to turn towards the camera once when it's instantiated, and when I try to achieve that, the animal gameObject that I spawn doesn't stay on the ground plane, but rather appears tilted towards the camera position .

**Comment by mdurand42** [comment]
> > @Sterling-Malory-Archer For this scenario you should not place your content prefab in the Anchor Prefab field. You should instead instantiate your content prefab and make the Anchor gameobject your content's parent. Then call `transform.LookAt(Camera.main.transform);` on the content gameobject. Does that make sense?
> 
> Hi Mike,
> 
> Would you please help me with an issue I am experiencing: When a user detects more than one AR Plane, the gameobject that I instantiate on the ARPlane sometimes starts to bounce between the 2 planes, I can provide a link to the video if needed.
> 
> Also for the scenario that I wrote originally, would you be able to help me with the code?
> 
> Thank you in advance,
> 
> Strahinja

@Sterling-Malory-Archer the purpose of the issues in this repo is to help users who are having issues with either the AR Foundation samples or issues with AR Foundation itself. Your question is more about general Unity knowledge so it more appropriate that you ask for assistance on the forums. 

But I'm glad the AR aspects of your experience are working well. I'm sure you will be able to solve your `LookAt()` issue with help from other Unity users.
