### ISSUE TITLE
i need turn off Light estimation.

### ISSUE THREAD

**Issue by KiDeokKim** [Unity-Technologies/arfoundation-samples#496]
hi, i need some help in AR Foundation.
i tried to set none in script ,'AR Camera Manager', but my object is so darkness.
my object's set false 'cast shadow' and add value intensity in Directional Light, shadow is still exist.
how do i turn off Light Estimation?

my Unity Editor version : 2019.3.8f1
AR Foundation version : 4.0(Preview version)
and build is android.

**Comment by RyanJVR** [comment]
Hi I haven't tried AR Foundation 4 yet, still on 3.1 but what I do I is access the 'AR Camera Manager' then set
`m_LightEstimationMode = LightEstimationMode.Disabled;` 
to Disabled and
`m_LightEstimationMode = LightEstimationMode.AmbientIntensity;` 
to enable again. Not sure if this is what you are looking for and for all I know I could be doing it wrong:P

**Comment by KiDeokKim** [comment]
@RyanJVR  Thanks commented.
sometimes LightEstimationMode is uncorrect work...(I think.. maybe)
before apply your opinion, i solve this phenomenon by added more directional light.
it does work, but i don't know i think that LightEstimaionMode doesn't work phenomenon is my fault..
