### ISSUE TITLE
Reference Image Library Generator

### ISSUE THREAD

**Issue by jean-barre** [Unity-Technologies/arfoundation-samples#497]
**Issue met**
I have to create an Image Library of several images. It is painful to add it one by one.

**Desired solution**
An out-of-the-box runnable like [arcoreimg.exe](https://developers.google.com/ar/develop/c/augmented-images/arcoreimg#windows) able to build a library from a directory path. It could be a Unity project to run in the editor, taking an AR Core image database (imgdb) as an argument and generating the corresponding XRReferenceImageLibrary.

**Alternatives**
I am trying to generate the library at runtime using the [MutableRuntimeReferenceImageLibraryExtensions](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.MutableRuntimeReferenceImageLibraryExtensions.html) static class. But it would imply an overhead at application launch while the images to load is pre-defined.

**Comment by tdmowrer** [comment]
Not a bad idea to drag and drop a directory or multi-select and drag images into a library. Note, however, that you would still need to fill out the metadata for each one (e.g., image size and name).
