### ISSUE TITLE
Non-Camera as Input for Segmentation / Body Tracking

### ISSUE THREAD

**Issue by smxthereisonlyone** [Unity-Technologies/arfoundation-samples#499]
Is it possible to capture a frame of camera (stil), save human segmentation mask and then take original frame as input for human body tracking?

The reason being that afaik at the moment human segmentation and body tracking cannot be combined at the same time.

Regards

**Comment by todds-unity** [comment]
No.  ARKit has restrictions on which features can and cannot be used together.
