### ISSUE TITLE
ARFoundation Body tracking feature - Character/Outfit rigging issue

### ISSUE THREAD

**Issue by Hypnotistas** [Unity-Technologies/arfoundation-samples#501]
How do I rig properly a character/an outfits to use body tracking feature?

From what I have tested - the body tracking feature of ARKit is pretty much unusable when it comes to using your own character/outfit. The initial rig of a model provided within ARFoundation is a rig where you can't find or buy anywhere else. I mean, ARFoundation uses a rig like nobody else is rigging the characters/outfits... I would appreciate any tutorial/guidance/tips on how the characters/outfits should be rigged to use this feature.

**Comment by fight4dream** [comment]
a chip in here. 
i notice their rig have a lot of bones
if you want to have a quick dirty solution, use ik on your own rig following their rig
i think most bones your rig having will have a close enough bone on theirs

**Comment by Hypnotistas** [comment]
> a chip in here.
> i notice their rig have a lot of bones
> if you want to have a quick dirty solution, use ik on your own rig following their rig
> i think most bones your rig having will have a close enough bone on theirs

Could you be more specific on "use ik on your own rig"?

**Comment by fight4dream** [comment]
use IK solutions such as FinalIK

**Comment by Hypnotistas** [comment]
Have you tried it or that's a suggestion(s) that you haven't tested on your own?
Important to note:
1) Switching to a different hierarchy of the bones alone won't help here, orientation of the bones are different.

2) As for FinalIK. I have asked FinalIK creators about this situation 5 months ago. What we talked:

**Me:**
I was wondering whether Final IK plugin is the right one to solve the issues that I am stumbled upon. 

Recently ARKit 3 propose a body tracking feature and they provided one ControlledRobot model which seems to work really good. However, the rig of their models is really different from the rigs available on most of the models available in Unity Asset Store, for instance, the well known unity chan model. it seems that x rotation is mixed up with y rotation. I was wondering whether the avatar/rig can be somehow easily changed with your plugin, so it would be the right one? 

The "ControlledRobot" that can be found is located in this arfoundation sdk: https://github.com/Unity-Technologies/arfoundation-samples I assume you know the unity chan model as an example

**They:**
No, Final IK can not change the bone orientations of avatars. I haven't tried ARKit myself yet, so can't really give you any good advice on the matter, sorry.

It seems that you know better that with FinalIK will solve this issue, but the plugin creators themselves don't? :)

**Comment by Hypnotistas** [comment]
Funny to note. Probably 99% of all rigs are made not in the way ARKit uses it. Though I haven't found a single other one working with it, so I left 1% just in case. I mean, cmon...

**Comment by fight4dream** [comment]
just make child transforms as the 'orientation correct target' under the arkit rig.
plugin creators don't necessarily know all use cases so they're fine to just say don't know
we've mainly worked with vr and final ik and deal with different rigs/target model orientations, i see no problem to have different orientations.

**Comment by fight4dream** [comment]
i also find the robo rig very hard to use
it is strangely it is not an fbx/obj, it is just a prefab asset
and even without the unity humanoid avatar (not mecanim)

**Comment by Hypnotistas** [comment]
> just make child transforms as the 'orientation correct target' under the arkit rig.
> plugin creators don't necessarily know all use cases so they're fine to just say don't know
> we've mainly worked with vr and final ik and deal with different rigs/target model orientations, i see no problem to have different orientations.

I will try again, though, if FinalIK does that automatically, I will get this asset at once.

**Comment by thornebrandt** [comment]
> i also find the robo rig very hard to use it is strangely it is not an fbx/obj, it is just a prefab asset and even without the unity humanoid avatar (not mecanim)

I am also running into this issue.  I usually solve tracking issues like this by bringing the demo skeleton into a 3d program like blender and matching up the skeletons to a new model. I'm unable to do this because it's a strange un-referenced prefab.  I tried a unity fbx exporter and it's still behaving strangely.    
 
<img width="400" alt="rotation" src="https://user-images.githubusercontent.com/1588366/143673294-7d3075d8-d16d-451f-947f-d947ca1805c0.png">
 
Has anyone found a solution for this?
