### ISSUE TITLE
Environment probes for front-facing camera

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#503]
How do I use the ARFoundation environment probes for the front-facing camera?

**Comment by tdmowrer** [comment]
Environment probes are not available in the user-facing (front-facing) camera mode. In ARFoundation 4, you can query which features are available at the same time. See https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/migration-guide-3.html#configuration-chooser
