### ISSUE TITLE
[Bug] ARFoundation Environment Probes do not work for front facing camera

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#504]
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**

**To Reproduce**
1. Go to any Face sample scene such as FacePose
2. Click on Add Environment Probe Manager to the AR Session game object and the corresponding EnvironmentProbePrefab
3. Add a sphere with the ReflectiveMaterial 
4. Build to your iPhone X or XS or ARKit front facing device to find the environment probes do not work.

**Expected behavior**
Environment probes should work so that the spheres appear to be reflective 

**Actual behavior**
Spheres do not reflect the environment. Just the skybox.

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 13.4.1
 - Unity version 2019.3.0f1 
 - ARFoundation version 2.1.2

**Comment by tdmowrer** [comment]
The expected behavior is not supported. See explanation at https://github.com/Unity-Technologies/arfoundation-samples/issues/503
