### ISSUE TITLE
[Bug] XRCameraImage error with AR Foundation 4.0.2

### ISSUE THREAD

**Issue by StefanoCecere** [Unity-Technologies/arfoundation-samples#510]
there are blocking errors updating AR Foundation to latest stable 4.0.2
(XRCameraImage doesn't exist anymore but there is a new XRCpuImage )

since master branch should work with Foundation 4.x, i created a patch to fix it:

https://github.com/Unity-Technologies/arfoundation-samples/pull/509

**Comment by Pixel-Labs** [comment]
Can here with same error. Patch fixed it for me. Thank you @StefanoCecere :)

**Comment by tdmowrer** [comment]
The current `master` branch works with the latest _preview_ packages; the 4.0 _verified_ packages were just published today, and we'll update this samples repo with a corresponding branch shortly.

**Comment by tdmowrer** [comment]
This repo has been updated. Please see https://github.com/Unity-Technologies/arfoundation-samples/tree/4.0
