### ISSUE TITLE
MeshClassification How to get the classifiedMesh with RayCast?

### ISSUE THREAD

**Issue by megatran** [Unity-Technologies/arfoundation-samples#511]
Hello!

I'm testing out the MeshClassification scene in the arfoundation-samples which uses the mesh classification functionality ([Assets/Scenes/Meshing/Scripts/MeshClassificationFracking.cs](https://github.com/Unity-Technologies/arfoundation-samples/blob/8914be76fe1b5a866d116d94670ff0cafae6b5c5/Assets/Scenes/Meshing/Scripts/MeshClassificationFracking.cs)) to generate colored overlays on top of the real world. Each color represents a unique surface typed detected by ARKit.

**High Level Goal:** I wanted to add a Raycast functionality so that whenever the user clicks on the screen, a text object displays what the surface is. For example, the [MeshClassificationFracking.cs](https://github.com/Unity-Technologies/arfoundation-samples/blob/8914be76fe1b5a866d116d94670ff0cafae6b5c5/Assets/Scenes/Meshing/Scripts/MeshClassificationFracking.cs) script creates a Yellow mesh prefab for the Wall classification.

**What I tried**
So far I tried making the `NonrenderedMeshPrefab` ([instantiated prefab for each generated mesh](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARMeshManager.html).) to have the **LayerMask 11** and was able to use `Physics.Raycast(Camera.main.ScreenPointToRay(touch.position), out hitMeshObj, Mathf.Infinity, 1 << 11)) ` to retrieve the rendered Meshes in real time. 
I could also extract the TrackableID from the hit Mesh's name. However, **I couldn't figure out how to retrieve the name or the `ARMeshClassification` of the **hit mesh face** because one mesh can contain multiple classified faces.** 

Additionally, I thought of using [RaycastHit.triangleIndex](https://docs.unity3d.com/ScriptReference/RaycastHit-triangleIndex.html) to get the material or color for the hit triangle using the suggestion [here]( https://answers.unity.com/questions/291853/raycasthit-triangleindex-and-submeshes-which-subme.html) so that if _color == Yellow, the triangle must be a Wall_. 

Another thought: I noticed `readonly Dictionary<TrackableId, MeshFilter[]> m_MeshFrackingMap` [here](https://github.com/Unity-Technologies/arfoundation-samples/blob/8914be76fe1b5a866d116d94670ff0cafae6b5c5/Assets/Scenes/Meshing/Scripts/MeshClassificationFracking.cs) contains the mapping from tracking ID to instantiated mesh filters. My raycast hit could get the TrackableID MeshId and access the associated MeshFilter array value with that Id. But I'm not sure how to get the particular mesh filter at the hit point.

**Am I overcomplicating the process? Could anyone suggest how you would go about doing this?**

**Comment by megatran** [comment]
I kinda found a hacky way to do it. I first extract the TrackableId from the hit mesh's name. Then, I use `meshSubsystem.GetFaceClassifications(hitTrackableId, Allocator.Persistent);` to get an array of face classifications. Then I access that array with RaycastHit.triangleIndex to get the classification label of that hit triangle. _My assumption is that the triangle index of the raycast matches the triangle index produced by  `meshSubsystem.GetFaceClassifications()`_. It seems to work If anyone has other suggestion, I would love to hear!

`
                        GameObject classificationText = Instantiate(classificationLabelObject, hitMeshObj.point, textRotation);

                        String displayText = "Unable to classify mesh face";
                        if (hitMeshObj.triangleIndex < faceClassifications.Length)
                        {
                            // check if value is defined in enum
                            string classificationValue = faceClassifications[hitMeshObj.triangleIndex].ToString();
                            if ((classificationValue[0] < '0' || classificationValue[0] > '9') && classificationValue[0] != '-')
                            {
                                displayText = string.Format("Mesh Face: {0}", faceClassifications[hitMeshObj.triangleIndex].ToString());
                            }
                        }
                        classificationText.GetComponentInChildren<TextMesh>().text = displayText;
`

<img width="700" alt="Screen Shot 2020-06-16 at 3 01 12 PM" src="https://user-images.githubusercontent.com/10265967/84832711-a1307a80-afe2-11ea-9b39-5220e3373f5a.png">

**Comment by amir989** [comment]
Could you please share the wireframe shader?

**Comment by tdmowrer** [comment]
> I kinda found a hacky way to do it.

This looks like the correct way to me :)
