### ISSUE TITLE
is HumanBodyTracking3D working either on iphone X or iPad Pro (11) 

### ISSUE THREAD

**Issue by shalumhmd** [Unity-Technologies/arfoundation-samples#518]
am trying to build the HumanBodyTracking3D sample in iPhone X. but it not working. 
Can I build the sample on iPhone X and iPad Pro (11).

One more doubt. is it works on both A12 bionic chip and A13 Bionic chip?

**Comment by tdmowrer** [comment]
Body tracking requires an A12 bionic (or later) chip, and the iPhone X uses an A11. See https://en.wikipedia.org/wiki/Apple_A12#Products_that_include_the_Apple_A12_Bionic for a list of A12 devices.

https://github.com/Unity-Technologies/arfoundation-samples#humanbodytracking2d mentions which samples require the A12 chip.
