### ISSUE TITLE
hand checking

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#519]
How do I make hand checking with arfundation？？？

**Comment by tdmowrer** [comment]
I assume you are referring to the hand tracking available in the [Vision Framework](https://developer.apple.com/documentation/vision/detecting_hand_poses_with_vision) that was just announced at WWDC. ARFoundation support for iOS is based on the ARKit framework, and Vision is a different technology. ARFoundation does not support Vision at this time.

**Comment by Arytes** [comment]
thanks
- 

-
