### ISSUE TITLE
throws error when not being able to overwrite aar libs

### ISSUE THREAD

**Issue by UgurIster** [Unity-Technologies/arfoundation-samples#52]
when one deploys an Android Project to where one already deployed the Android Project before it throws a bunch of errors for AAR lib files it can't replace (because they are already there).

Like 

Trying to add file ...unityandroidpermissions.aar to the list of ouptut files in the build report, but a file at that path has already been added.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

it shouldn't show errors for these since it is to be expected the files are already there on re deploy

**Comment by UgurIster** [comment]
though as i just updated the arcore xr plugin package in unity then it becomes clear it is a bug situation when it can't replace the aar files in the androidproject on redeploy since then one has the older aar libs in there which had some previous package version bugs.

**Comment by tdmowrer** [comment]
I don't remember the exact release, but the `arcore_client.aar` was made overridable about 4 months ago.
