### ISSUE TITLE
[Bug] NullReferenceException in CheckAvailableFeatures in Editor

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/arfoundation-samples#522]
**Describe the bug**
Pressing play results in NullReference in the new menu stuff.

**To Reproduce**
Press play in Editor.

**Expected behavior**
All menu items get disabled since no features are available.

**Actual behavior**
NullReference exception.

**Smartphone (please complete the following information):**
Unity Editor, any version.

Note: PR #516 would fix this, merging that would have taken less time than writing an explanation for why not to merge it. Thank you.

**Comment by tdmowrer** [comment]
Thanks again for reporting. This has been fixed on the `latest-preview` and `4.0` branches.
