### ISSUE TITLE
[Bug] Tooltip in new menu is not readable, is behind rest of UI

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/arfoundation-samples#523]
**Describe the bug**
Tooltip in new menu is not readable, is behind rest of UI.

**To Reproduce**
Press play.
Click on any menu item.

**Expected behavior**
Tooltip is readable.

**Actual behavior**
Tooltip is behind UI.

**Smartphone (please complete the following information):**
Unity Editor, also any smartphone.

Note: PR #513 would fix this, but instead of merging in a simple fix of transform orders in the scene you decided to close it.

**Comment by tdmowrer** [comment]
Thanks again for reporting. This has been fixed on the `latest-preview` and `4.0` branches.
