### ISSUE TITLE
is that Google Persistent AR (Cloud Anchor) released in ARFoundation?

### ISSUE THREAD

**Issue by samsgates** [Unity-Technologies/arfoundation-samples#524]
Google announced Persistent AR feature going to release on ARCore next release. they released Depth API but there is no announcement about Persistent AR. is that released in ARFoundation 4.1 ?

**Comment by mdurand42** [comment]
Google Cloud anchors are not incorporated into AR Foundation and Persistent Cloud Anchors have not yet been released by Google.
