### ISSUE TITLE
Keep getting The type or namespace name '****' could not be found error [Bug]

### ISSUE THREAD

**Issue by y4jun** [Unity-Technologies/arfoundation-samples#526]
Hi,

I am new to Unity and AR foundation and your help would be really helpful for me.

After downloading this package, I simply dragged the folder and imported it to my unity project.

But it keeps giving me errors 

<img width="695" alt="2" src="https://user-images.githubusercontent.com/56052737/85941695-44787c80-b95f-11ea-9297-fba4a837c4a3.png">
<img width="1128" alt="1" src="https://user-images.githubusercontent.com/56052737/85941699-480c0380-b95f-11ea-87fc-b7c73e6c450d.png">

I found out that I have to put asset files into asset folder and so on but where should I put the projectsettings to? 

Thanks for your help in advance!

**Comment by tdmowrer** [comment]
> After downloading this package, I simply dragged the folder and imported it to my unity project.

If you mean the contents of this repo, then that will not work. This repo is an entire Unity project, and you cannot merge it into an existing project in this way.

**To add ARFoundation to an existing project**
ARFoundation is a package and can be added to any project from the package manager (Window > Package Manager). You will also need one or more platform support packages for ARFoundation, depending on which platform(s) you'd like to support, i.e., ARCore XR Plugin, ARKit XR Plugin, Magic Leap, and/or Windows XR Plugin.

**To run the samples in this repo**
Simply clone the repo or download+extract the zip, and open it in Unity. Then, switch to either Android or iOS (File > Build Settings...) and click "Build And Run". If you are new to Unity and ARFoundation, I recommend starting with this approach to get familiar with the tech.
