### ISSUE TITLE
How to get texture from AR camera.

### ISSUE THREAD

**Issue by meihkkkkkkk** [Unity-Technologies/arfoundation-samples#527]
Hi,
I'm trying to make an Android app to continuously get texture from AR Camera. The code is something like this:
`
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;
using System;
namespace UnityEngine.XR.ARFoundation.Samples
{
    [RequireComponent(typeof(ARAnchorManager))]
    [RequireComponent(typeof(ARRaycastManager))]  
    public class AnchorCreator : MonoBehaviour
    {
        void Awake()
        {       
            m_RaycastManager = GetComponent<ARRaycastManager>();
            m_AnchorManager = GetComponent<ARAnchorManager>();
            m_Anchors = new List<ARAnchor>();
            m_CameraBackground = GetComponent<ARCameraBackground>();
        }

        void Update()
        {
            getTexture();
        }

        ARRaycastManager m_RaycastManager;
        ARAnchorManager m_AnchorManager;
        ARCameraBackground m_CameraBackground;

        public GameObject thing;
        public Text checktext;
        public RenderTexture renderTexture;
        public Texture2D tex;
        private void getTexture()
        {
            //Copy the camera background to a RenderTexture
            Graphics.Blit(null, renderTexture, m_CameraBackground.material);

            // Copy the RenderTexture from GPU to CPU
            var activeRenderTexture = RenderTexture.active;
            RenderTexture.active = renderTexture;
            
            tex = new Texture2D(renderTexture.width, renderTexture.height, TextureFormat.RGB24, true);
            tex.ReadPixels(new Rect(0, 0, renderTexture.width, renderTexture.height), 0, 0);
            tex.Apply();
            
            RenderTexture.active = activeRenderTexture;

            //This line is to display texture to a small image on screen
            thing.GetComponent<Image>().sprite = Sprite.Create(tex, new Rect(540, 960, 1000, 600), new Vector2(0.5f, 0.5f));
        }
    }
}
`
The code is modified from Anchor sample, so maybe some line are not nessessary.
The problem is, when I run the app, it is supposed to be a full screen camera, with a small window (the Image in last code line) reflecting the camera. But that small window just shows notthing.
Can you tell me if I miss something in my code? Thank you

**Comment by tdmowrer** [comment]
> The code is modified from Anchor sample

Can you link me to that?

`ReadPixels` is pretty slow. I suggest using the `XRCpuImage` API instead. We have a [sample](https://github.com/Unity-Technologies/arfoundation-samples#cpuimages) for that.

**Comment by meihkkkkkkk** [comment]
Hi @tdmowrer , 
Firstly, thank you for replying so quickly. 
1) > Can you link me to that?
Well, it's the Anchor scene in the arfoundation-samples, posted by you. But my problem is not related to that.
2) I will learn about using XRCpuImage, but now I think speed is not what I'm concern about.
3) Let me specify my idea:
![49365d99ab6656380f77](https://user-images.githubusercontent.com/59635254/86037214-36168780-ba69-11ea-9ca2-52cbfa63ca9e.jpg)
Here's the screenshot of how the app work. The white box is attached to "GameObject Thing" in my code and it is supposed to show one part of the camera, but it shows notthing :(
Do you have any sample related to my project?
4) Also, what I want to do is to get texture (like screenshots) continuously from AR camera, then use BarcodeReader.Decode to scan each texture to find qr code. Is that the right way?
It's quite long but hope you can take a look and instruct me. Thank you so much

**Comment by tdmowrer** [comment]
> Do you have any sample related to my project?

The CPU Images sample does something very similar.

> what I want to do is to get texture (like screenshots) continuously from AR camera, then use BarcodeReader.Decode

See https://github.com/Unity-Technologies/arfoundation-samples/issues/489

**Comment by meihkkkkkkk** [comment]
Hi @tdmowrer ,
Thank you for replying. I have checked thread #489, the problem is, I cannot find some struct like:

- XRCameraImage, XRCameraImageConversionParams (I have add UnityEngine.XR.ARSubsystems, so these struct should be available, right?)

- CameraImageTransformation (I think it's in library named: UnityEngine.XR.ARExtensions, but I cannot find that library)
Also, I have already download your repo, but can you show me where to find the sample which uses XRCameraImage?

**Comment by tdmowrer** [comment]
> XRCameraImage, XRCameraImageConversionParams (I have add UnityEngine.XR.ARSubsystems, so these struct should be available, right?)

In 4.0, these were changed to `XRCpuImage` and `XRCpuImage.ConversionParams`.

> CameraImageTransformation (I think it's in library named: UnityEngine.XR.ARExtensions, but I cannot find that library)

No -- ARExtensions was deprecated some time ago. See `XRCpuImage.Transformation`.

> Also, I have already download your repo, but can you show me where to find the sample which uses XRCameraImage?

This [description](https://github.com/Unity-Technologies/arfoundation-samples#cpuimages) has links to the relevant scripts. The scene is simply called `CpuImages`.

**Comment by meihkkkkkkk** [comment]
> > XRCameraImage, XRCameraImageConversionParams (I have add UnityEngine.XR.ARSubsystems, so these struct should be available, right?)
> 
> In 4.0, these were changed to `XRCpuImage` and `XRCpuImage.ConversionParams`.
> 
> > CameraImageTransformation (I think it's in library named: UnityEngine.XR.ARExtensions, but I cannot find that library)
> 
> No -- ARExtensions was deprecated some time ago. See `XRCpuImage.Transformation`.
> 
> > Also, I have already download your repo, but can you show me where to find the sample which uses XRCameraImage?
> 
> This [description](https://github.com/Unity-Technologies/arfoundation-samples#cpuimages) has links to the relevant scripts. The scene is simply called `CpuImages`.

Hi @tdmowrer , I missed the CpuImages. Now it solves all my questions. Thank you so much for helping me all the time. Hope to learn more from you in the future
