### ISSUE TITLE
[Bug][App Store rejected] Apple thinks we are using the TrueDepth API's

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#528]
Duplicate of this closed issue:

https://github.com/Unity-Technologies/arfoundation-samples/issues/477

Cannot reopen so submitting a new issue. App review failed due to supposed use of true depth API's, ARKit FaceTracking not included nor is the library in the xcode project. Customer code so can't share project I'm afraid. I'll submit a bug if it helps you but it would basically be a duplicate of the samples repo with a basic scene.

Unity 2019.4.1f1
ARFoundation 4.0.1
com.unity.xr.arkit 4.0.1

For what its worth, I use this link.xml

`<assembly fullname="Unity.XR.ARFoundation" preserve="all" ignoreIfMissing="0"/>
<assembly fullname="Unity.XR.ARExtensions" preserve="all" ignoreIfMissing="1"/>
<assembly fullname="Unity.XR.ARCore" ignoreIfMissing="0" preserve="all"/>
<assembly fullname="Unity.XR.ARKit" ignoreIfMissing="0" preserve="all"/>`

**Comment by tdmowrer** [comment]
Could you take a look at the libs that are included in the generated Xcode project? It's under "Build Phase" > "Link Binary With Libraries" as in this screen shot:
![Screen Shot 2020-06-29 at 10 47 02 AM](https://user-images.githubusercontent.com/4934281/86038512-e6e33f00-b9f5-11ea-95c3-1bc7f9d58138.png)

Also, the `link.xml` is no longer required.

**Comment by nilsk123** [comment]
Screenshot below. We use the link.xml because we only reference AR components from assetbundle scenes.

<img width="863" alt="Schermafbeelding 2020-06-29 om 19 51 30" src="https://user-images.githubusercontent.com/8883990/86038917-f9836580-ba41-11ea-9719-f4f76c9a146c.png">

**Comment by tdmowrer** [comment]
Can you [log a bug](https://unity3d.com/unity/qa/bug-reporting) with your project attached and post the issue id here so I can find it? We have double checked there are no TrueDepth APIs in `libUnityARKit`, and we have submitted a test app that passed app store validation, so there is something else going on here.

**Comment by nilsk123** [comment]
Case 1259518. Project won't compile without access to our internal scoped registry (this is also where most of our AR stuff 'lives'). If you want to delve into it that deep let me know and I'll give you access to it.

**Comment by tdmowrer** [comment]
Thank you. Yes, I'd like to compile it and inspect the built binary.

**Comment by nilsk123** [comment]
> Thank you. Yes, I'd like to compile it and inspect the built binary.

Email sent

**Comment by tdmowrer** [comment]
So we've been looking at this and can't find any references to face tracking. In the other two reports, it seems like simply resubmitting a clean build might be enough https://github.com/Unity-Technologies/arfoundation-samples/issues/477#issuecomment-647841076:
> After doing a completely clean build of the XCode project the app was approved for public release. Nothing was changed in the Unity project. The app was never built with the face tracking package.

I don't feel like we've gotten to the bottom of this yet, but could you try that?

**Comment by nilsk123** [comment]
> So we've been looking at this and can't find any references to face tracking. In the other two reports, it seems like simply resubmitting a clean build might be enough [#477 (comment)](https://github.com/Unity-Technologies/arfoundation-samples/issues/477#issuecomment-647841076):
> 
> > After doing a completely clean build of the XCode project the app was approved for public release. Nothing was changed in the Unity project. The app was never built with the face tracking package.
> 
> I don't feel like we've gotten to the bottom of this yet, but could you try that?

Thanks for looking into it. We've submitted an appeal (without uploading a new binary) referencing this issue and the app is now in review again. Will keep you posted.

**Comment by nilsk123** [comment]
@tdmowrer the app was approved without having to submit a new binary. I did not get a message back from the review team so I don't know what caused the hickup in the first place, seems pretty random.

**Comment by tdmowrer** [comment]
That is concerning, but I'm glad your app was approved! We'll continue to monitor this situation as it seems to affect many apps using ARFoundation.
