### ISSUE TITLE
ARKitCoachingOverlay display non-English text guide for other language device

### ISSUE THREAD

**Issue by Goya-** [Unity-Technologies/arfoundation-samples#529]
Demo scene
![DCIM(1)](https://user-images.githubusercontent.com/7187511/86109814-5e4cc780-baf7-11ea-8d29-5ed76bd8e1b5.jpg)

Measure app
![DCIM(2)](https://user-images.githubusercontent.com/7187511/86109822-5f7df480-baf7-11ea-8bb3-0db31504ba3b.jpg)

**Comment by tdmowrer** [comment]
Hi - this appears to be a bug in ARKit. It would be helpful if you could provide feedback to Apple on this using their [feedback assistant](https://feedbackassistant.apple.com/).

**Comment by tdmowrer** [comment]
One way to work around this is to add additional "Localizations" within Xcode:

<img width="692" alt="Screen Shot 2020-07-14 at 10 07 30 AM" src="https://user-images.githubusercontent.com/4934281/87455189-e6cc6d00-c5b9-11ea-98f1-330f71dbd1d5.png">
