### ISSUE TITLE
Add multiple anchor prefabs

### ISSUE THREAD

**Issue by meihkkkkkkk** [Unity-Technologies/arfoundation-samples#530]
I'm trying to make an AR app, which can scan qr code and spawn an object (prefabs), which stay at the position of the qr code (using Anchor). The qr scanner worked, thanks to mr @tdmowrer help in #527 .
Now I have another problem, here's what I want the app do: if the qr code return text "123", prefab1(which is a cube) spawn, while the text is "456", prefab2 (which is a sphere) spawn.
In the sample scene named Anchor, I see that the prefab was attached to AR Session Origin/ AR Anchor Manager (script)/ Anchor Prefab. But it can only be 1 prefab there. 
Can you instruct me how to change it?
Thank you

**Comment by tdmowrer** [comment]
Create an anchor using [`ARAnchorManager.AddAnchor`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARAnchorManager.html#UnityEngine_XR_ARFoundation_ARAnchorManager_AddAnchor_Pose_) (the prefab field can be null), and then parent your content to the new anchor.

The [Instantiate](https://docs.unity3d.com/ScriptReference/Object.Instantiate.html) method accepts a parent transform as an argument; use the anchor's transform, e.g.,

```csharp
var anchor = anchorMananger.AddAnchor(<pose>);
Instantiate(myPrefab, anchor.transform);
```

**Comment by meihkkkkkkk** [comment]
Wow, that works perfectly. But I have another questions, please tell me if your suggestion above can work with them.
Firstly, the initial code is something like this:
`
var anchor = m_AnchorManager.AddAnchor(hitPose);
m_Anchors.Add(anchor);
`
The anchor appear will be the prefab attached to AR Anchor Manager (script).

Now I change the code to this (to simplify it to understand, I changed the sample from read QR code to just touch screen, then 2 prefab apprear alternatively)
`
var anchor = m_AnchorManager.AddAnchor(hitPose);
if ((m_Anchors.Count)%2==1)
                {
                    Instantiate(mypref1, anchor.transform);
                }
                else
                {
                    Instantiate(mypref2, anchor.transform);
                }
m_Anchors.Add(anchor);
`
Now the prefab attached to AR Anchor Manager is null. So m_Anchors (a list of ARAnchor) now is a list of null object. Is that what you mean?

Secondly, I'm new in using Unity, so I'm not sure about this. I want to create a button on-screen. Then, for example, I have already spawn 5 prefabs (cube, sphere, cube, sphere, cube), and if I press the button, the 2nd prefab (a sphere) change it color/size/.... So if I use the 1st code, I can use m_Anchors[1] to access to that prefab, right? (actually I haven't known how to change color this way yet, please tell me if possible). While I'm using 2nd code, m_Anchors[1] is now just a null object, it's only here to count number of prefabs, so how can I access to the sphere?

**Comment by mdurand42** [comment]
@meihkkkkkkk It's great that @tdmowrer was able to help you with your question about AR Foundation. The Unity forums are a great place for new users to ask some of your follow-up questions. https://forum.unity.com/
