### ISSUE TITLE
[Bug] ARCore plugin provider needs API 24 even if it's optional

### ISSUE THREAD

**Issue by AytoMaximo** [Unity-Technologies/arfoundation-samples#532]
**Unity bug report case number**
Case 1260222

**Describe the bug**
Hi! I'm not sure if it's a bug or my misunderstanding. 

I want an app that can use ARFoundation optionally, only if it's available on device. 
Project settings -> XR -> ARCore BuildSettings set as "Optional" in my project. 

Also I've checked ARCore plugin provider in XR Plug-in Management setting page, 'cas we need it for using ARCore feature on top devices. 

The problem is that I can't make a build because of manifest merging failure: it forces me to use API 24 (Nougat 7.0) because of ARCore plugin provider. But I don't want to make my app target 7.0, ARCore is optional feature. 

So, what I'm doing wrong here? Thank you!

Unity 2019.4.2 LTS
ARFoundation 4.0.2
ARCore XR Plugin 4.0.3
XR Plugin Management 3.2.12

[UPD] Using XR PM 3.2.10 now because of this [case](https://forum.unity.com/threads/i-get-a-querying-package-manager-for-currently-installed-packages-pop-window-forever.918446/)

**Comment by AytoMaximo** [comment]
This is the message of an error and editor log file. 
[Editor.log](https://github.com/Unity-Technologies/arfoundation-samples/files/4863681/Editor.log)


![image](https://user-images.githubusercontent.com/14392087/86349637-25812f80-bc6a-11ea-9d89-d944c24c2837.png)

**Comment by tdmowrer** [comment]
Thanks for reporting. It's a bug; will get it fixed asap.

**Comment by tdmowrer** [comment]
This has been fixed in ARCore XR Plugin package 4.0.4 https://docs.unity3d.com/Packages/com.unity.xr.arcore@4.0/changelog/CHANGELOG.html as well as the latest preview package.
