### ISSUE TITLE
Does this AR sample work in LG V30?

### ISSUE THREAD

**Issue by meihkkkkkkk** [Unity-Technologies/arfoundation-samples#533]
Hi, I'm trying to make an AR Android app, based on this sample project. The problem is, my current phone isn't compatible with Google Play Service for AR, so I intend to buy a LG V30 to test the app. 
In ARCore support list, the LG V30 is available with a note that "ARCore uses the wide angle fixed focus rear facing camera for AR tracking", what does that mean? 
And if I download this project, build it to an Android apk file, and install in LG V30, will it work normally? 
My project (and this sample project, of course) worked on Samsung Galaxy Note 8, but I don't know how it work on the V30. 

P/S: I have not bought the LG V30 yet, and I'm asking to consider if I should do it or not. 
Also, please tell me if this is not the right place to ask about device. Thank you a lot.

**Comment by tdmowrer** [comment]
Some devices don't support auto focus, or only support it in certain modes. My guess is this one only supports fixed focus.

> Also, please tell me if this is not the right place to ask about device.

https://github.com/google-ar/arcore-android-sdk/issues might be a better place to ask.

**Comment by meihkkkkkkk** [comment]
Hi @tdmowrer , 
Thank you for the answer. 
So if I use the phone to test my app, the performance will be worse and just affect my experience, right? Or do I need to change the code/program for my app to match the only fixed focus?

**Comment by tdmowrer** [comment]
I don't know about performance. Seems like it has a beefy Snapdragon 835. You don't need to change your code. If you request autofocus and the phone doesn't support it, then you just get fixed focus.
