### ISSUE TITLE
Unity's Shadow does not appear/work in Android after adding AROcclusionManager script

### ISSUE THREAD

**Issue by bharatgidwani** [Unity-Technologies/arfoundation-samples#534]
Unity's shadow is getting disappear on android devices if  AROcclusionManager is attached on the ARCamera.

**Comment by tdmowrer** [comment]
Shadows will also be occluded. You should still see objects that cast shadows on other virtual objects as long as nothing is occluded by the environment.

This is something we plan to improve in the future.

**Comment by bharatgidwani** [comment]
> Shadows will also be occluded. You should still see shadows cast between virtual objects as long as nothing is occluded by the environment.
> 
> This is something we plan to improve in the future.

Shadows are not visible at all even if nothing is occluded by the environment.

**Comment by mdurand42** [comment]
@bharatgidwani Please file an issue tracker issue and provide your test project.

**Comment by tdmowrer** [comment]
I added a couple of cubes to the SimpleAR scene, enabled environment depth and ran the sample on a Pixel 3a XL. Shadows rendered as expected and environmental occlusion worked.

When you file an [issue tracker](https://unity3d.com/unity/qa/bug-reporting), please post the case number here so we can find it faster.
