### ISSUE TITLE
How to add reference object at runtime to ARTrackedObjectManager

### ISSUE THREAD

**Issue by thibautvdu** [Unity-Technologies/arfoundation-samples#535]
Dear Team,

Currently, ARFoundation doesn't allow to add a reference object at runtime to a library, only to set an existing object reference library to the ARTrackedObjectManager.

I need to dynamically load .arobject at runtime. Knowing that it's possible to do in ARKit, I tried to create an extension in objective c. The issue is that everytime I modify the configuration to add my reference objects in native code, Unity triggers `UnityARKit: Updating ARSession configuration` and seems to erase the changes.

I tried with an empty reference library in Unity and with a library containing only one object without luck.
Here is my native code (quite straightforward)

```
extern "C"{
    bool ARKitBridge_addTrackedObject(const char* url, const char* name, const NativeARSessionPointer *s) {
        NSString *nsUrlStr= [NSString stringWithCString:url encoding:NSUTF8StringEncoding];
        NSString *nsNameStr= [NSString stringWithCString:name encoding:NSUTF8StringEncoding];

        NSURL *nsUrl = [NSURL URLWithString:nsUrlStr];

        NSError* error = nil;
        ARReferenceObject* newObject = [ARReferenceObject alloc];
        newObject = [newObject initWithArchiveURL:nsUrl error:&error];

        if(newObject == nil) {
            return false;
        }

        newObject.name = nsNameStr;

        ARWorldTrackingConfiguration* config = ((ARWorldTrackingConfiguration*)s->session.configuration);
        NSMutableSet<ARReferenceObject*>* detectionObjects = config.detectionObjects.mutableCopy;
        if(detectionObjects == nil)
            detectionObjects = [NSMutableSet<ARReferenceObject*> new];
        [detectionObjects addObject:newObject];
        config.detectionObjects = detectionObjects;

        [s->session runWithConfiguration:config];

        return true;
    }
}
```

Any idea of how to do that ?

Many thanks

**Comment by tdmowrer** [comment]
There is currently no way to do this as we compare the current configuration against the one we think the session should have each frame. I've added a feature request to add this functionality.

**Comment by thibautvdu** [comment]
@tdmowrer Many thanks for your reply.

Generally speaking (not only for the object libary issue) I think it'd make sense to let the user manipulate the session on the native side, especially considering that ARFoundation documents the way to create native extensions. Maybe something like an unsafe mode that doesn't enforce the configuration.

**Comment by tdmowrer** [comment]
I know what you mean. We'll have to consider this carefully -- it would basically be a "disable everything, full manual" mode where nothing would work as expected (i.e., enabling/disabling managers would have no effect).

**Comment by IsaacBerman** [comment]
@tdmowrer Any update on this feature?

**Comment by tdmowrer** [comment]
No update, no. The stale bot isn't supposed to close feature requests, so I'll reopen this issue.

**Comment by YordDev** [comment]
Do you have some estimates when could this feature be implemented? Is it matter of weeks, months? This is really crucial functionality for multiple projects. Thank you for your answer.

**Comment by tdmowrer** [comment]
We are looking at implementing this for 5.0 as it requires a breaking API change, so months is more likely than weeks, unfortunately.

If you like, you may be able to hack it in by accessing the ARSession pointer and updating the configuration yourself. There's a [new sample](https://github.com/Unity-Technologies/arfoundation-samples#arkitgeoanchors) that shows how to get this pointer and interact with it in Objective-C.

**Comment by antonsem** [comment]
Any updates on this issue? Should we expext it in the 5.0 release? Is there an eta for 5.0?

**Comment by YordDev** [comment]
Yep, don't want to be annoying but any estimation or release day guess would be nice. It would allow us to plan accordingly. Thanks

**Comment by tdmowrer** [comment]
We are trying to get this into 4.2 which will be verified for 2021.2 (and available as a prerelease package before that).

**Comment by tdmowrer** [comment]
4.2 was released yesterday, and it includes this feature. See `XRReferenceObjectLibrary.Add`.

**Comment by AkhilRaja** [comment]
@tdmowrer Is there a sample on how to do this please ? Documentation is a little difficult to follow and implement

**Comment by oliverellmers** [comment]
Hi all,

I have asked a similar question [here](https://github.com/Unity-Technologies/arfoundation-samples/issues/938#issue-1122551535) - hoping somebody might be able to shed some light??

Best,

O.

**Comment by IsaacBerman** [comment]
@oliverellmers, did not figure it out, moved away from Unity and started implementing app directly in iOS native with ARKit.

**Comment by oliverellmers** [comment]
@IsaacBerman that is a shame... Perhaps @tdmowrer might be able to provide some insight?

**Comment by tdmowrer** [comment]
> @IsaacBerman that is a shame... Perhaps @tdmowrer might be able to provide some insight?

I no longer work at Unity, and I doubt you'll get a response on a closed issue. Creating a new issue is the right thing to do, and it looks like you've got a response on https://github.com/Unity-Technologies/arfoundation-samples/issues/938
