### ISSUE TITLE
Model edges are jagged using AR Occlusion

### ISSUE THREAD

**Issue by craig026** [Unity-Technologies/arfoundation-samples#537]
I have used the AR Occlusion Manager in a few projects and I seem to be getting a 'jagged' look to model edges (see screenshot) instead of smoothed edges that I have seen in other examples.

I am using a Samsung Galaxy Note 10. Any ideas?

Thanks.

![OcclusionScreenshot2](https://user-images.githubusercontent.com/54131430/86871027-112ab000-c10c-11ea-9686-5188f9f40713.jpg)

**Comment by mdurand42** [comment]
Could you tell us what your quality setting is for Environment Depth in the AROcclusionManager?

**Comment by craig026** [comment]
I have tried all three quality settings for Environment Depth in the AROcclusionManager and the same effect happens. The screenshot is using the 'Best' Environment Depth Mode.

**Comment by mdurand42** [comment]
OK. We will try with a Note 10 or similar and try to observe whether there is a similar result.

**Comment by craig026** [comment]
Great, thanks for looking into it.

**Comment by creativehims** [comment]
I also noticed the same issue.

**Comment by craig026** [comment]
Hi,

Did you manage to take a look into this issue?

Thanks.

**Comment by tdmowrer** [comment]
The raw depth image has a much lower resolution than the camera image. We try to smoothly upsample it; however, the ability to do this depends on GPU feature support, and certain GPUs do not support this.

For instance, a Samsung S9 with a Qualcomm GPU allows for smooth upscaling, whereas an S9 with a Mali GPU does not. The "jagged" rendering artifacts you see are likely a result of your device specs, and there's not much that can be done to improve the result. Have you tried the same scene on any other device?

**Comment by craig026** [comment]
Thanks for the explanation. I've only tried it with a Galaxy S10 and Note 10 - the same effect happens on both devices but as they were bought in Australia, they both appear to have a Mali GPU.

I'll see if I can test it on a device with a better GPU, but for now it seems like it's just down to the device I'm using.

Thanks for looking into it!

**Comment by stents** [comment]
Is this issue really due to device support? Older versions of ARCore depth lab (eg 1.1.1) had very smooth occlusion, however the same devices have jagged occlusion as in the above screenshot.

environmentDepthTemporalSmoothingSupported returns supported, and Depth images are nicely smoothed when environmentDepthTemporalSmoothingRequested is set to true, however occlusion always has jagged edges.

I have tested on a number of Samsung devices and all have the same issue.

**Comment by tdmowrer** [comment]
@stents you may want to open a new issue. I no longer work at Unity, and it's unlikely anyone else will see your comment on this closed issue.

**Comment by stents** [comment]
Ah yes, sorry @tdmowrer, had not noticed it was closed before I posted. Thanks for the reply. In case anyone else is looking for smoother occlusion on devices with this issue, my current solution is to use a custom ARCameraBackground material with a shader that does a gaussian blur on the Environment Depth texture.

**Comment by ethanfischer** [comment]
Has anyone found a solution for this? I can't find anyone else talking about this issue and I'm seeing the exact same thing

**Comment by ethanfischer** [comment]
Update: Looks like the degree of jaggyness is related to the quality settings in project settings. After switching to ultra quality, it's no longer jagged for me

<img width="336" alt="image" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/6758736/414d4f59-e211-478e-9f55-7acc5663cb10">


<img width="286" alt="image" src="https://github.com/Unity-Technologies/arfoundation-samples/assets/6758736/f229e3fb-7202-498f-8852-ab57abbf2b66">
