### ISSUE TITLE
No occlusion happening in build

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#538]
I've upgraded to ARFoundation version 4.1.0 - preview.2 as well as both ARCore and ARKit.

I'm using Unity 2019.4 (LTS).

I've added the AR Occlusion Manager to my AR Camera (see screenshot below).

When I build my app and try to test it on the iPad, there is not occlusion, neither environment nor human.

Could it be because I am using Anchors? 

![Screen Shot 2020-07-08 at 10 15 12 AM](https://user-images.githubusercontent.com/18481583/86894917-079d4a00-c104-11ea-8200-44422525e4a9.png)

**Comment by doukasd** [comment]
This worked on my iPad. But you need the following:

- does your iPad have the LIDAR?
- is your iPad running iOS14 beta?
- try disabling the human segmentation settings on that screenshot

**Comment by Sterling-Malory-Archer** [comment]
> This worked on my iPad. But you need the following:
> 
> * does your iPad have the LIDAR?
> * is your iPad running iOS14 beta?
> * try disabling the human segmentation settings on that screenshot

Hi,

Unfortunately, I don't think my iPad has LIDAR, I know for a fact I'm not using iOS14 Beta. My iPad is the 6th Generation, running on 12.3.1.

But in that case, how can I enable occlusion on this particular device? Or is it not possible?

**Comment by DavidMohrhardt** [comment]
@Sterling-Malory-Archer Occlusion for ARKit requires a device with an A12 chip or later as per the [docs](https://developer.apple.com/documentation/arkit/occluding_virtual_content_with_people)
```
"People occlusion is supported on Apple A12 and later devices. Before attempting to enable people occlusion, verify that the user’s device supports it."
```

The 6th generation iPads have an A10 chip which means that Occlusion is incompatible with that particular iPad.  You can confirm whether your device supports occlusion by checking the subsystem descriptor on the manager.

```
var arOcclusionManager = GetComponent<AROcclusionManager>();
if (!arOcclusionManager.descriptor. supportsHumanSegmentationDepthImage && arOcclusionManager.descriptor. !supportsHumanSegmentationDepthImage)
{
    Debug.Log("This device does not support occlusion.");
    arOcclusionManager.enabled = false;
    // Other handling...
}
```
