### ISSUE TITLE
Light estimation and direction shows unavailable

### ISSUE THREAD

**Issue by rezonated** [Unity-Technologies/arfoundation-samples#539]
Unity 2019.3.14f1
ARFoundation 4.1.0 preview 2
iPhone 7 iOS 13.5.1
Latest samples
![IMG_3774](https://user-images.githubusercontent.com/37521206/86903998-48b05100-c13a-11ea-95de-4054418634ec.PNG)

Hi, there.
Is this kind of behavior normal on iPhone 7 device? I'm trying to see how the light estimation and direction functionality works. Before this all the text fields are showing 'unavailable' and then I looked around in the AR Camera game object, inside the AR Camera Manager component that the Light Estimation option could be set to everything, thus I selected that option. The only thing that has changed is the brightness value. 
![image](https://user-images.githubusercontent.com/37521206/86904239-9af17200-c13a-11ea-8de3-a332906345dc.png)

Is there something else that I've probably missed? Or is it normal on iPhone 7? Since I saw the Readme.md file for this repo and I saw that a virtual arrow (I assume it is for showing the light's direction) requires camera that is equipped with TrueDepth that is not present in iPhone 7's camera.

![image](https://user-images.githubusercontent.com/37521206/86904462-f3287400-c13a-11ea-8298-61048fb12bdb.png)

#466 I also see this issue where as @tdmowrer stated that ARKit only returns intensity and temperature, but oddly enough the color temperature does not showing any value at all.

![image](https://user-images.githubusercontent.com/37521206/86904788-64682700-c13b-11ea-839a-0f21abd8137a.png)

So yeah, is this normal? Or is there something that i might have missed? 

Thank you in advance.

**Comment by mdurand42** [comment]
This looks like a bug. We will investigate.

**Comment by christougher** [comment]
Same on iphone 6s but works fine on an XR

**Comment by mdurand42** [comment]
This has been addressed in the newly updated Light Estimation sample.

https://github.com/Unity-Technologies/arfoundation-samples/commit/37a47c95e161fb9857e4b8375ddd3ab64a4e782d
