### ISSUE TITLE
Unity 2019.4.1f1 RuntimeReferenceImageLibrary and CreateRuntimeLibrary not found

### ISSUE THREAD

**Issue by mosx92** [Unity-Technologies/arfoundation-samples#540]
Dear,
I'm trying to use RuntimeReferenceImageLibrary and CreateRuntimeLibrary but when I write the code my visual studio code does not recognize it. 
My os is macOS Catalina 10.15.4
Unity 2019.41f1
ArFoundation 2.1.8 -> 4.0.2 (Published Date April 16, 2020)

There are some other that have the same problem? How can I fix it?

**Comment by tdmowrer** [comment]
You need to include using directives for UnityEngine.XR.ARFoundation and UnityEngine.XR.ARSubsystems. if you are using asmdefs then you'll need to add referenced to the ARFoundation and ARSubsystem assemblies too.

VSCode often struggles to understand valid code in my experience. Is it just VSCode complaining, or does it fail to compile in Unity? If so, what is the error message?

> ArFoundation 2.1.8 -> 4.0.2 (Published Date April 16, 2020)

That's a large range of versions. Which one are you using?
