### ISSUE TITLE
[Bug] SimpleAR is using a different interaction scheme than other samples

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/arfoundation-samples#542]
**Describe the bug**
The Simple AR example scene has an ifdef for Unity Editor and then only reacts to mouse input, not touches.
This breaks a) touchscreens on Desktop devices b) frameworks that simulate touches in Unity, and all other samples behave properly (don't have such "editor-hacks").

Would be great if you can remove that ifdef; it's not good practice anyways and seems to be there just so the first scene works with the mouse in editor? At least touches should not be excluded, if you must keep that mouse fallback.

**To Reproduce**
- Use a Windows Touchscreen
- Open the SimpleAR scene
- Press play
- Click to place

**Expected behavior**
Cube is placed

**Actual behavior**
Nothing happens because the ifdef guards against the touch input

**Comment by tdmowrer** [comment]
Thanks for pointing this out. We'll look at making this more consistent.

**Comment by mdurand42** [comment]
@tropicdragon Addressed this in the following change: https://github.com/Unity-Technologies/arfoundation-samples/commit/e8cc924b12262ac505c6d3bc074e3dcb342f6b4a

**Comment by hybridherbst** [comment]
🙏 Thank you!
