### ISSUE TITLE
How to show a facemesh of current user ?

### ISSUE THREAD

**Issue by Starsky-Synlitec** [Unity-Technologies/arfoundation-samples#543]
I can now display the facemesh of current user, and I can also get the image of current phone's camera.
But when I use the texture of current phone's camera as the texture of the facemesh, the uv seems not correct.
I checked the uv and found that they are static values.

Wo how to create a face mesh of current user's face ?

can we get the dynamic uv based on the input camera frame? Or the key point position based on the camrea frame space ?

**Comment by Starsky-Synlitec** [comment]
I figured out a way to solve this, but I don't think it is the best way:
1.  Blit camera materila to rendertexture
2. set facemesh texture as the render texture
3. transform facemesh vertices' positions to world space, then to screen space
4. normalize screen space position to [0,1], set it as the uv for each vertex

**Comment by tdmowrer** [comment]
This seems like it might be a better question for https://forum.unity.com/forums/handheld-ar.159/. This issues page is better suited for reporting problems with the samples or the ARFoundation packages.
