### ISSUE TITLE
How to Hide Instantiated object in Image Tracking?

### ISSUE THREAD

**Issue by KiDeokKim** [Unity-Technologies/arfoundation-samples#544]
before Read, sorry about my english.
i want hide Instantiated object in Image Tracking.
i tried hide Instantiated object but if i hiding or closing Target Image, i can't hiding and remain Object.

if i hiding or closing Target Image, TrackingState is Limited.
so i create script and OnTrackedImagesChanged Function, if state is TrackingState.Limited, i set TrackedManager.trackedImagePrefab.SetActive(false).

but it doesn't work.
so how do i hide Instantiated object? or how can i get Instantiated Object?

**Comment by tdmowrer** [comment]
You need to `SetActive(false)` on the instantiated object.

```csharp
TrackedManager.trackedImagePrefab.SetActive(false);
```

sets the _prefab_ (which hasn't yet been instantiated) to inactive.

To get the instantiated object, you can 
1. Subscribe to [`ARTrackedObjectManager.trackedObjectsChanged`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackedObjectManager.html#UnityEngine_XR_ARFoundation_ARTrackedObjectManager_trackedObjectsChanged)
2. Enumerate all existing tracked objects with the [`trackables`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackableManager-4.html#UnityEngine_XR_ARFoundation_ARTrackableManager_4_trackables) property.

**Comment by KiDeokKim** [comment]
That's not the answer I want....
i'm using Image tracking, not Tracking object.

it is my code, attatched 'AR Session Origin'

`	void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
	{
		try
		{
			foreach (var trackedImage in eventArgs.updated)
			{
				if (trackedImage.trackingState == TrackingState.Tracking)
				{
					if(TrackedManager.trackedImagePrefab != null)
					{
						Debug.Log("Active True");
						TrackedManager.trackedImagePrefab.SetActive(true);
					}
					else
					{
						Debug.Log("TrackedManager.trackedImagePrefab null");
					}
				}
				else if (trackedImage.trackingState == TrackingState.None)
				{
					Debug.Log("Tracking State is None");
					TrackedManager.trackedImagePrefab.SetActive(false);
				}
				else
				{
					Debug.Log("Tracking State is " + trackedImage.trackingState);
					if (TrackedManager.trackedImagePrefab != null)
					{
						TrackedManager.trackedImagePrefab.SetActive(false);
						Debug.Log("Active false");
					}
					else
					{
						Debug.Log("TrackedManager.trackedImagePrefab null");
						TrackedManager.trackedImagePrefab = Prefab;
					}
				}
			}
		}
		catch(Exception e)
		{
			Debug.Log("Exception : " + e.Message);
		}
`

**Comment by KiDeokKim** [comment]
i think 'TrackedManager.trackedImagePrefab.SetActive(false)' is not work..
my prefab added tag 'Test' and using FindGameObjectWithTag, find Instantiated object, and SetActive(false) is work.
it is correct way? i upload my function in script.
![Image](https://user-images.githubusercontent.com/40253618/87264040-eff60500-c4f9-11ea-8c2d-7b1085344a06.PNG)

i'm using Unity -2019.3.8f1 and All Package Version is your project version(preview, 4.1.0)
and My Test Device is Android(Samsung Galaxy Tab S6).

i want if i remove my image, Object is hiding on Tracked Image.
please check and tell me correct way.

**Comment by tdmowrer** [comment]
Whoops, I read "object" in the title and assumed you were doing object tracking. My bad. But everything I said is exactly the same for image tracking. `ARObjectTrackingManager` and `ARImageTrackingManager` work in the same way.

**Comment by KiDeokKim** [comment]
Thanks for your comment.
but above in my scripts, i tried **SetActive(false)**, but that's not work in android...
TrackedManager is ARImageTrackingManager. so i tried findwithTag to instantiated object, and hiding.

**Comment by tdmowrer** [comment]
As I said [initially](https://github.com/Unity-Technologies/arfoundation-samples/issues/544#issuecomment-656926806), you are calling `SetActive` on a _prefab_ before it is instantiated. You need to call it on the _instantiated_ GameObject.

```csharp
foreach (var img in TrackedManager.trackables)
{
    img.gameObject.SetActive(false);
}
```

Would hide them all, for example.

**Comment by KiDeokKim** [comment]
i understand your comment. Attach above script to target prefab.. i was attached in AR Session Origin..
so your example code, if i hiding target image, it is work. but if i retracking  target image, it is now showing. so how do i reshow my target prefab?

**Comment by tdmowrer** [comment]
> so how do i reshow my target prefab?

Same, but with

```csharp
SetActive(true)
```

**Comment by pinnakkkk** [comment]
Hey could u upload the full script? im stuck on same problem
