### ISSUE TITLE
[Bug] Redmi K30 with AR foundation sample

### ISSUE THREAD

**Issue by ChrisAn2203** [Unity-Technologies/arfoundation-samples#546]
I'm using a Redmi K30. It is already listed as arcore supported device. But when I download ar foundation sample, build to apk and install the apk in K30, the app cannot open camera. Is that a common problem? And is there any way to fix?

**Comment by tdmowrer** [comment]
I've not tried a Redmi K30. What is the `adb logcat` output when you run the samples?

**Comment by ChrisAn2203** [comment]
I have run the sample app, then choose CPU Images.
I think this is what you're asking: 
<img width="960" alt="Capture1" src="https://user-images.githubusercontent.com/68139571/87219464-94a30600-c385-11ea-9492-c5364464474e.PNG">

Also, this is a screenshot of the K30
![z1969440650530_5af0ca16ded5b17de5dae1d06ab731ed](https://user-images.githubusercontent.com/68139571/87219470-a5ec1280-c385-11ea-80af-56f3886fd180.jpg)

**Comment by tdmowrer** [comment]
Please provide the full output as a text file, not a screenshot.

**Comment by ChrisAn2203** [comment]
Sorry for not answering because it was midnight in my place. 
I have try this: "adb logcat -s Unity"
Then here's the result:
`--------- beginning of system
--------- beginning of crash
--------- beginning of main
07-12 10:26:57.160 25149 25173 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5427mb
07-12 10:26:57.160 25149 25173 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
07-12 10:26:57.166 25149 25173 I Unity   : ApplicationInfo com.unity.arfoundation.samples version 0.1 build b1eaecd6-823e-4848-b94e-8da904897d65
07-12 10:26:57.166 25149 25173 I Unity   : Built from '2019.4/release' branch, Version '2019.4.1f1 (e6c045e14e4e)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
07-12 10:26:57.305 25149 25173 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
07-12 10:26:57.305 25149 25173 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
07-12 10:26:57.305 25149 25173 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather
07-12 10:26:57.748 25149 25173 I Unity   : XRGeneral Settings awakening... 
07-12 10:26:57.748 25149 25173 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-12 10:26:57.748 25149 25173 I Unity   : 
07-12 10:27:07.507 25149 25173 E Unity   : [XRInputSubsystem] A device disconnection with the id 0 has been reported but no device with that id was connected. 
07-12 10:27:07.507 25149 25173 E Unity   : (Filename:  Line: 329)
07-12 10:27:07.507 25149 25173 E Unity   : 
07-12 10:27:20.034 25149 25180 E Unity   : Curl error 6: Could not resolve host: config.uca.cloud.unity3d.com
07-12 10:27:20.034 25149 25180 E Unity   :  
07-12 10:27:20.034 25149 25180 E Unity   : (Filename:  Line: 813)
07-12 10:27:20.034 25149 25180 E Unity   : 
07-12 10:29:32.836 26024 26084 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5427mb
07-12 10:29:32.836 26024 26084 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
07-12 10:29:32.836 26024 26084 I Unity   : ApplicationInfo com.DefaultCompany.Hahahihihuhu version 0.1 build ec7bc379-273d-484f-9ab9-37de6f4be272
07-12 10:29:32.836 26024 26084 I Unity   : Built from '2019.3/staging' branch, Version '2019.3.12f1 (84b23722532d)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
07-12 10:29:32.982 26024 26084 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
07-12 10:29:32.982 26024 26084 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
07-12 10:29:32.982 26024 26084 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather
07-12 10:31:27.293 26458 26482 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5427mb
07-12 10:31:27.293 26458 26482 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
07-12 10:31:27.293 26458 26482 I Unity   : ApplicationInfo com.DefaultCompany.Hahahihihuhu version 0.1 build ec7bc379-273d-484f-9ab9-37de6f4be272
07-12 10:31:27.293 26458 26482 I Unity   : Built from '2019.3/staging' branch, Version '2019.3.12f1 (84b23722532d)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
07-12 10:31:27.413 26458 26482 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
07-12 10:31:27.413 26458 26482 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
07-12 10:31:27.413 26458 26482 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather
07-12 10:37:09.023 28193 28217 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5427mb
07-12 10:37:09.023 28193 28217 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
07-12 10:37:09.023 28193 28217 I Unity   : ApplicationInfo com.DefaultCompany.Hahahihihuhu version 0.1 build ec7bc379-273d-484f-9ab9-37de6f4be272
07-12 10:37:09.023 28193 28217 I Unity   : Built from '2019.3/staging' branch, Version '2019.3.12f1 (84b23722532d)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
07-12 10:37:09.136 28193 28217 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
07-12 10:37:09.137 28193 28217 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
07-12 10:37:09.137 28193 28217 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather
07-12 10:39:34.129 28462 28487 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 5427mb
07-12 10:39:34.129 28462 28487 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
07-12 10:39:34.130 28462 28487 I Unity   : ApplicationInfo com.unity.arfoundation.samples version 0.1 build b1eaecd6-823e-4848-b94e-8da904897d65
07-12 10:39:34.130 28462 28487 I Unity   : Built from '2019.4/release' branch, Version '2019.4.1f1 (e6c045e14e4e)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
07-12 10:39:34.254 28462 28487 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
07-12 10:39:34.254 28462 28487 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
07-12 10:39:34.254 28462 28487 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather
07-12 10:39:34.647 28462 28487 I Unity   : XRGeneral Settings awakening... 
07-12 10:39:34.647 28462 28487 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-12 10:39:34.647 28462 28487 I Unity   : 
`
Is that what I have to find? The text shows that since I open the app, and there's nothing more when I enter some modes like (Anchors, CPU Images,...)
I have tried just "adb logcat" but I seems to be to much lines.

**Comment by tdmowrer** [comment]
Sorry, I need the full `adb logcat` (it contains internal ARCore output as well as output from our plugin not captured by `-s Unity`). You can dump it to a file and attach it here by dragging and dropping it into a comment.

**Comment by ChrisAn2203** [comment]
Hi @tdmowrer , I'm not familiar with this so please tell me if I did something wrong.
This is the txt file when I run: adb logcat > C:\...\log.txt.
Hope this is the one you're asking for.
Also, I opened the AR sample app at the timestamp of around 7-13 0:16. While the adb logcat shows all system (like 7-11,....) so I think all the lines before 7-13 0:16 is not neccesary. But I'm not sure if I should delete anything, so I keep them all, then the txt file is quite large.
[log.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/4908937/log.txt)

**Comment by tdmowrer** [comment]
That's perfect, thanks.

I noticed a couple of things:

1. Looks like it is crashing when permission is initially requested. Once you grant permission, this shouldn't happen again. This is not the source of the problem you are reporting here, but it was a bug that was fixed recently in the ARCore package version 4.1.0-preview.3.
2. This is the real problem -- looks like ARCore has an internal error:
```
07-13 00:17:57.209 21690 21714 E native  : ################ ARCore Native Error ##################
07-13 00:17:57.209 21690 21714 E native  : BUILD_CHANGELIST:317371218
07-13 00:17:57.209 21690 21714 E native  : BUILD_BASELINE_CHANGELIST:314554407
07-13 00:17:57.209 21690 21714 E native  : ################### Stack Trace Begin ################
07-13 00:17:57.209 21690 21714 E native  : ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc:1978	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc?g=0&l=1978
07-13 00:17:57.209 21690 21714 E native  : ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation.cc:264	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation.cc?g=0&l=264
07-13 00:17:57.209 21690 21714 E native  : ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation.cc:348	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation.cc?g=0&l=348
07-13 00:17:57.209 21690 21714 E native  : ################### Stack Trace End #################
07-13 00:17:57.209 21690 21714 E native  : 
07-13 00:17:57.209 21690 21714 E native  : session_manager.cc:56 ArPresto::ArCore session creation failed.
```

I also noticed a little further up there are messages like this one:
```
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: Post-install failed
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: java.lang.IllegalArgumentException: Unknown authority com.google.ar.core.services.arcorecontentprovider
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: 	at android.content.ContentResolver.call(ContentResolver.java:2055)
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: 	at android.content.ContentResolver.call(ContentResolver.java:2038)
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: 	at com.google.ar.core.a.a(ArCoreApk.java:8)
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: 	at com.google.ar.core.k.a(ArCoreApkImpl.java:81)
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: 	at com.google.ar.core.k.requestInstall(ArCoreApkImpl.java:64)
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: 	at com.google.ar.core.k.requestInstall(ArCoreApkImpl.java:59)
07-13 00:17:57.145 21690 21714 I ARCore-SetupContentResolver: 	at com.google.ar.core.ArCoreApkJniAdapter.requestInstall(ArCoreApkJniAdapter.java:25)
```

Which suggests it tried, but was unable to install Google Play Services for AR (something it has to go get from the Play Store the first time the app runs). Do you get a prompt to install ARCore when you run the app?

**Comment by tdmowrer** [comment]
I understand there are a few variants of the Redmi K30. Are you using the "K30 Pro", "K30 5G", or "K30 Racing"? (Or something else?)

**Comment by ChrisAn2203** [comment]
Hi @tdmowrer ,
1. The phone I'm using to test is the K30 Racing. There are some differents in chipset, RAM, ROM, but I think they're quite similar in software support.
2. The Redmi K30 is the product for China market only, then the Google Play Store is not originally installed. The default app store for it named "Xiaomi app store" or "Getapps", then I can download Google Play Store from that. I have checked. When I search for Google Play Service for AR, in Xiaomi app store, it has already been installed, while in the downloaded Google Play Store, it said that the device is not compatible :( 
Hope it's not a problem, because in the ARCore supported devices list, it contains the K30, and I think it's suffered the same problem with my K30 racing.

**Comment by chaosemer** [comment]
Hello from the ARCore team at Google!

ARCore currently supports the K30 (4G) and K30 Pro (lmi) models. The K30 Racing 5G is not supported. We're fixing our supported devices page to make this distinction clear.

**Comment by ChrisAn2203** [comment]
Hi @chaosemer , I think this is the answer I need, I have try to contact developer team for this but I don't know how. Could you tell me if the K30 5G or K30 Racing is going to be supported in the near future? Or not?

**Comment by chaosemer** [comment]
I have communicated this feedback to the ARCore device scaling team so that it is on their radar. I don't have any particular date that I can share for 5G variants to be supported.

**Comment by ChrisAn2203** [comment]
@chaosemer , Thank you for replying. Guest I need to find another model :'( Hope to get your notification if the support for 5g variant is available.
