### ISSUE TITLE
how to move and rotate the robot from HumanBodyTracking3D? [how to]

### ISSUE THREAD

**Issue by joexusun** [Unity-Technologies/arfoundation-samples#547]
I'm trying to place the robot from "human body tracking 3d" (Unity-Technologies/arfoundation-samples/blob/latest-preview/Assets/Scenes/HumanTracking/HumanBodyTracking3D.unity) into my game. The idea is that the player can use their body to control the robot (similar to kinect games). I think the "human body tracking" is the gameobject that I should manipulate. I tried transforming it, it does not move.. How can I transform the robot? I need it to move and rotate.

**Comment by joexusun** [comment]
I ended up with transforming all other objects and camera and achieved what I wanted .. but still like to know, is it possible to transform the robot? 
I also tried make it a prefab and instantiate, but it didn't work either. Is it just different than a normal gameobject?

**Comment by tdmowrer** [comment]
> I tried transforming it, it does not move.. How can I transform the robot? I need it to move and rotate.

What did you do exactly? Can you share some code here?

**Comment by joexusun** [comment]
At first, I changed the location in GUI. 
![image](https://user-images.githubusercontent.com/9424030/87857549-3dd79680-c95a-11ea-90d6-283dbe2c6034.png)
but that didn't work. then I realized that this is just an gameobject that somehow instantiates the robot. 

I think my problem was that when the program runs, the tracked human isn't always in the middle of the frame. I'd like to transform the whole "game world" based on the "game world location" of the newly instantiated robot, so that I can always have the robot at the correct spot in my game.

How do I get the location of the robot? It doesn't look like an instantiated gameobject as what I saw before ..

Thanks.

**Comment by joexusun** [comment]
I think I still don't quite understand how does this "human body tracker" component work after reading the scripts.. It uses "AR Session Origin" as the human body manager, (with prefab defined in the same script)
![image](https://user-images.githubusercontent.com/9424030/87857713-69a74c00-c95b-11ea-948a-76bdedfcd17b.png)

but then in "AR Session Origin"'s "AR Human Body Manager", the "Human Body Prefab" was left blank. When should a prefab be used here?
![image](https://user-images.githubusercontent.com/9424030/87857742-a83d0680-c95b-11ea-85c1-9a3d38ac74ce.png)

**Comment by tdmowrer** [comment]
> I'd like to transform the whole "game world" based on the "game world location"

You can do that be setting the transform of the `ARSessionOrigin`. It effectively moves the entire AR world.

> How do I get the location of the robot?

The human body is a trackable, so you can get it from the [`ARHumanBodyManager.trackables`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackableManager-4.html#UnityEngine_XR_ARFoundation_ARTrackableManager_4_trackables) collection.
