### ISSUE TITLE
How to use Deep Neural Network in unity with ML-Agent

### ISSUE THREAD

**Issue by marcomameli1992** [Unity-Technologies/arfoundation-samples#548]
I would like to use Deep Neural Network in unity for example for object recognition with a printing of the name of the object on the screen using a bounding box around the screen.
With research, I saw that it is possible to use: https://github.com/apple/turicreate for apple devices. This framework requires to insert swift code in unity.
I would like to do something like this with the use of ML-Agent. Can anyone has some knowledge if it is possible or not?

**Comment by tdmowrer** [comment]
This seems off-topic for this issues page. You can use Swift in a Unity-based project. [This article](https://medium.com/@kevinhuyskens/implementing-swift-in-unity-53e0b668f895) uses Core ML, Swift, and ARKit.

If you are asking about Unity's ML Agents, https://github.com/Unity-Technologies/ml-agents might be a more appropriate place to ask your question.

**Comment by tdmowrer** [comment]
Also,

> for object recognition with a printing of the name of the object on the screen using a bounding box around the screen.

If that is all you want to do, ARKit is capable of object tracking and this repo contains a [sample](https://github.com/Unity-Technologies/arfoundation-samples#objecttracking).
