### ISSUE TITLE
Breaks Screen Mirroring ios [Bug]

### ISSUE THREAD

**Issue by FriskyBishop** [Unity-Technologies/arfoundation-samples#549]
**Describe the bug**
The latest version of ARFoundation breaks screen mirroring.
Does not matter which sample scene is used. 
It worked fine on previous versions. 

**Expected behavior**
Screen mirroring should work at all times

**Actual behavior**
When the app is launched screen mirroring stops working (TV screen goes black), when the app is stopped screen mirroring starts working again

iPhone 11 pro ios 13.5.1 + iPad Pro 2nd gen ios 14
ARFoundation 4.1 preview 1
Unity 2020.2.0a15

**Comment by tdmowrer** [comment]
This appears to be a bug in Unity 2020.2 affecting all applications, not just AR. Please [report a bug](https://unity3d.com/unity/qa/bug-reporting).

**Comment by tdmowrer** [comment]
This was [fixed](https://issuetracker.unity3d.com/issues/ios-black-screen-is-mirrored-when-using-airplay) in 2020.2.0b3
