### ISSUE TITLE
[Bug] XRCameraImage doesn't work

### ISSUE THREAD

**Issue by Scheshi** [Unity-Technologies/arfoundation-samples#553]
After upgrading to version 4.0.2, XRCameraImage stopped working. I looked at issues with the same problem, and then try to install the preview version. Eventually:
![image](https://user-images.githubusercontent.com/47576867/87928460-b9f4db80-ca39-11ea-81f1-9d33d5b1e5fb.png)

Because:

![image](https://user-images.githubusercontent.com/47576867/87928606-ec9ed400-ca39-11ea-8c84-e21b4fad91ab.png)

If this is my mistake, please tell me where I am wrong.

 - Unity version: 2019.4.2f1
 - ARFoundation version: 4.0.2 - preview 4.1.0

**Comment by tdmowrer** [comment]
Please see [the migration guide](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/migration-guide-3.html#xrcameraimage-is-now-xrcpuimage)'s "XRCameraImage is now XRCpuImage" section.

**Comment by tdmowrer** [comment]
The [sample](https://github.com/Unity-Technologies/arfoundation-samples/blob/latest-preview/Assets/Scripts/CpuImageSample.cs) has also been updated.
