### ISSUE TITLE
AR CPUImage scene crash

### ISSUE THREAD

**Issue by meihkkkkkkk** [Unity-Technologies/arfoundation-samples#554]
Hi,
I'm trying to make an app like this: using the CPUImage scene in the sample project to get the Texture2D from AR camera, then using ZXing library to read QR code from that image/texture. (#527)
Then I have a problem: the app always crashed after around 10-20sec. I have also tried the CPUImage scene of sample project and it worked normally.
Here's my adb logcat. I don't know if it's about my code or my device which is to weak to handle the app. Hope you can check and show me my problem (and solution if possible)
[adb_logcat.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/4950195/adb_logcat.txt)

Thank you

**Comment by tdmowrer** [comment]
Can you post your code?

**Comment by meihkkkkkkk** [comment]
Hi @tdmowrer ,


> Can you post your code?

I have make some changes and I figured out that my issue is not related to QR/ZXing library. I have disabled all QR function, then my project is just like a merge version of "Anchors" scene and "CPUImage" scene (I think so), but it still crashses. Moreover, when I try the "CPUImage" scene (the sample project), it runs smoothly (not crash after few minutes).. Here's my project: [https://drive.google.com/drive/folders/1ciHdAWNghqbSHZZN-YeGii_PrXK5WmrV?usp=sharing](url)
Can you help me to check if anything wrong?

Furthermore, I have some more problems related to Anchors:

- In sample project Anchors scene, there are some "yellow dots" (I think they are detected points in space, right?). In the project I sent above, I have deleted most unnecessary assets, then those "yellow dots" are disabled (not affect any function). Can you suggest me which asset that I should not delete in order to display those "yellow dots"?

- In AnchorCreator.cs -> line 90, if you enable the function "ScanQR" for QR Scanning function, and scan QR code to get text like "This_is_QR_1", then an anchor spawns, but not stable in size and rotation (changing every time). If the anchor spawn by touching (just like Anchors scene in sample project), then the size and rotation are normal. Can you suggest me some changes to solve that?

**Comment by meihkkkkkkk** [comment]
> Furthermore, I have some more problems related to Anchors:
> 
> * In sample project Anchors scene, there are some "yellow dots" (I think they are detected points in space, right?). In the project I sent above, I have deleted most unnecessary assets, then those "yellow dots" are disabled (not affect any function). Can you suggest me which asset that I should not delete in order to display those "yellow dots"?
> * In AnchorCreator.cs -> line 90, if you enable the function "ScanQR" for QR Scanning function, and scan QR code to get text like "This_is_QR_1", then an anchor spawns, but not stable in size and rotation (changing every time). If the anchor spawn by touching (just like Anchors scene in sample project), then the size and rotation are normal. Can you suggest me some changes to solve that?

These are just some side questions, please tell me if I should delete them and re-post in another thread.
