### ISSUE TITLE
Dynamically added images are not tracked on Android Devices. 

### ISSUE THREAD

**Issue by cplus98** [Unity-Technologies/arfoundation-samples#556]
First, I tested "ImageTracking" sample.

I've added images to MutableRuntimeReferenceImageLibrary in runtime mode dynamically on Android devices.
There are two issues.

1. Printed images are not recognized well.
- Very slow

2. Rectangular (Non-square) images are not recognized at all.
- Only works on square images.

But on iOS devices work both well and statically(Non-runtime) added images were well recognized.

**Comment by tdmowrer** [comment]
> Rectangular (Non-square) images are not recognized at all.

Please check your import settings. If you are importing the image as a `Texture2D`, it is rounded to the nearest power of 2 dimension, which can stretch the image provided to ARCore.
