### ISSUE TITLE
CpuImage rotate Texture2D preview in portrait

### ISSUE THREAD

**Issue by D3m0n92** [Unity-Technologies/arfoundation-samples#559]
How do I...
Hi, I noticed that several other developers have encountered the same problem, so maybe it would be useful to integrate a solution directly into ARFoundation. The problem concerns the CpuImage demo scene, setting the scene in portrait and writing on a common RawTexture the result of the captured image frame by frame, an incorrect rotation of the camera is obtained. My goal is not to rotate the preview itself, but rather the Texture2D, since this is then passed on TensorFlow to carry out the recognition. I also noticed that the "preview" has a "zoom" totally different from the standard background of ARCore, and this clearly creates an alignment problem with some contents. How can I solve this problem too?

**Comment by tdmowrer** [comment]
The purpose of the XRCpuImage API is to provide "raw" access to the image coming from the camera sensor, hence the reason it is always in the same orientation. Rotations and other transformations required for displaying the pass through video on screen are applied in a shader.

While the XRCpuImage API can do some limited transformations like mirror the image, or crop to a subrectangle, it is not intended as a general purpose image manipulation library. If your ML model requires a particular orientation, you will have to transform the image before passing it to TensorFlow. You can look at the shader included in the package (`ARCoreBackground.shader`) to see how the image is transformed. The data it is using comes from the `ARCameraFrameEventArgs` struct, e.g., [`displayMatrix`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_displayMatrix), which you can get by subscribing to [`ARCameraManager.frameReceived`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_frameReceived)

**Comment by D3m0n92** [comment]
> The purpose of the XRCpuImage API is to provide "raw" access to the image coming from the camera sensor, hence the reason it is always in the same orientation. Rotations and other transformations required for displaying the pass through video on screen are applied in a shader.
> 
> While the XRCpuImage API can do some limited transformations like mirror the image, or crop to a subrectangle, it is not intended as a general purpose image manipulation library. If your ML model requires a particular orientation, you will have to transform the image before passing it to TensorFlow. You can look at the shader included in the package (`ARCoreBackground.shader`) to see how the image is transformed. The data it is using comes from the `ARCameraFrameEventArgs` struct, e.g., [`displayMatrix`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_displayMatrix), which you can get by subscribing to [`ARCameraManager.frameReceived`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_frameReceived)

Would it be possible to have an example script? I really don't know how to get started. The desired orientation is clearly that recovered by the device. (But since the background automatically adjusts, I think it's all in the shader already.) I assume it may be a very good "Utility" script to have in the ARFoundation package.

**Comment by tdmowrer** [comment]
Lines 54-55 of `ARCoreBackground.shader`, for instance, look like this:

```hlsl
                // Remap the texture coordinates based on the device rotation.
                textureCoord = (_UnityDisplayTransform * vec4(gl_MultiTexCoord0.x, 1.0f - gl_MultiTexCoord0.y, 1.0f, 0.0f)).xy;
```

`_UnityDisplayTransform` is the [`displayMatrix`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_displayMatrix) you get from the `ARCameraManager` [event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_frameReceived) I mentioned.

**Comment by mdurand42** [comment]
Closing due to lack of response. Please re-open if @tdmowrer 's explanation did not resolve the issue.

**Comment by michalek-marcin** [comment]
Hi,

I have a similar problem. I need portrait orientation in application. I'm using WebCamTexture to get image from iPhone back camera to display preview on RawImage. I use texture also for image recognition (barracuda and yolov2-tiny). When application is in landscape mode everything works (preview and recognition), but in portrait mode doesn't. I need to rotate texture somehow.

**Comment by dyc081818** [comment]
save problem

**Comment by bllnzr** [comment]
You can do some thing like this 


/// Use this func to convert to Texture2D

private static void UpdateRawImage(RawImage rawImage, XRCpuImage cpuImage)
	{
		// Get the texture associated with the UI.RawImage that we wish to display on screen.
		var texture = rawImage.texture as Texture2D;

		// If the texture hasn't yet been created, or if its dimensions have changed, (re)create the texture.
		// Note: Although texture dimensions do not normally change frame-to-frame, they can change in response to
		//    a change in the camera resolution (for camera images) or changes to the quality of the human depth
		//    and human stencil buffers.
		if (texture == null || texture.width != cpuImage.width || texture.height != cpuImage.height)
		{
			texture = new Texture2D(cpuImage.width, cpuImage.height, cpuImage.format.AsTextureFormat(), false);
			rawImage.texture = texture;
		}

		Debug.Log("Format" + cpuImage.format.AsTextureFormat().ToString());
		// For display, we need to mirror about the vertical access.
		var conversionParams = new XRCpuImage.ConversionParams(cpuImage, cpuImage.format.AsTextureFormat(), XRCpuImage.Transformation.MirrorY);

		//Debug.Log("Texture format: " + cpuImage.format.AsTextureFormat()); -> RFloat

		// Get the Texture2D's underlying pixel buffer.
		var rawTextureData = texture.GetRawTextureData<byte>();

		// Make sure the destination buffer is large enough to hold the converted data (they should be the same size)
		Debug.Assert(rawTextureData.Length == cpuImage.GetConvertedDataSize(conversionParams.outputDimensions, conversionParams.outputFormat),
			"The Texture2D is not the same size as the converted data.");

		// Perform the conversion.
		cpuImage.Convert(conversionParams, rawTextureData);

		// "Apply" the new pixel data to the Texture2D.
		texture.Apply();

		
	}

//Rotate the Texture2D using this function before using it for image detection or what ever you want to do with it

	public Texture2D rotateTexture(Texture2D originalTexture, bool clockwise)
	{
		Color[] original = originalTexture.GetPixels();
	    Color[] rotated = new Color[original.Length];
		int w = originalTexture.width;
		int h = originalTexture.height;

		int iRotated, iOriginal;

		for (int j = 0; j < h; ++j)
		{
			for (int i = 0; i < w; ++i)
			{
				iRotated = (i + 1) * h - j - 1;
				iOriginal = clockwise ? original.Length - 1 - (j * w + i) : j * w + i;
				rotated[iRotated] = original[iOriginal];
			}
		}

		Texture2D rotatedTexture = new Texture2D(h, w);
		rotatedTexture.SetPixels(rotated);
		rotatedTexture.Apply();
		return rotatedTexture;
	}
