### ISSUE TITLE
Can't place an object in front of user (ARRaycastManager problem)

### ISSUE THREAD

**Issue by AytoMaximo** [Unity-Technologies/arfoundation-samples#560]
Hello! I'm trying to raycast feature points in front of user:

```
public (Vector3 position, Quaternion rotation) GetSpawnPointInFrontOfUser()
    {
        Debug.Log("Searching for an anchor");

        List<ARRaycastHit> s_Hits = new List<ARRaycastHit>();
        Pose pose = new Pose();
        Transform player = ARCam.transform;

        pose = new Pose(player.position + Vector3.forward, Quaternion.LookRotation(player.position));

        var screenCenter = ARCam.ViewportToScreenPoint(new Vector3(0.5f, 0.5f));
        
        if (_arRaycastManager.Raycast(screenCenter, s_Hits, TrackableType.FeaturePoint))
        {
            if (s_Hits.Count > 0)
            {
                var distance = s_Hits[0].distance;
                ARRaycastHit hit = s_Hits[0];
                foreach (var item in s_Hits.Where(item => item.distance > distance))
                {
                    hit = item;
                }
                pose = hit.pose;
            }
        }

        var lookPos = player.position - pose.position;
        lookPos.y = 0;

        Debug.Log("Anchor is: " + pose.position);

        return (position: pose.position, rotation: Quaternion.LookRotation(lookPos));
    }
```

...but facing the following issues:

1. ARRaycastManager.Raycast() doesn't work good enough. In many cases it can't find feature points by the center of screen. I feel confused a little bit, because there is one more argument for this method in the documentation, but in fact it is missing:
<img width="1197" alt="Снимок экрана 2020-07-24 в 14 19 20" src="https://user-images.githubusercontent.com/14392087/88386760-bce52880-cdb9-11ea-8cda-ccdae94b8598.png">

2. I had an idea to place an object in 1 meter in front of the user if raycast returns false, however I've found out that AR camera doesn't rotate with its axis, so Vector3.Forward doesn't work as expected too. 
<img width="575" alt="Снимок экрана 2020-07-24 в 14 32 00" src="https://user-images.githubusercontent.com/14392087/88387145-8bb92800-cdba-11ea-9875-07f03b8dbd16.png">

The feature a want to implement looks like this: https://www.youtube.com/watch?v=RjIbiAC8cBk

Thank you in advance for your help and advices :)

**Comment by tdmowrer** [comment]
1. I think that documentation is just using an out-of-date code snippet. In this case, the width of the angle used is test against each point is up to the underlying AR framework (ARCore or ARKit).

2. [`Vector3.forward`](https://docs.unity3d.com/ScriptReference/Vector3-forward.html) is a global constant equal to `(0, 0, 1)`. I think you want the camera's [`transform.forward`](https://docs.unity3d.com/ScriptReference/Transform-forward.html).

**Comment by AytoMaximo** [comment]
> I think that documentation is just using an out-of-date code snippet. In this case, the width of the angle used is test against each point is up to the underlying AR framework (ARCore or ARKit).

I think there is for sure has to be an angle, because you can't find anything if you check one pixel of the screen only. That's why changing this angle for setting the accuracy of raycast scanning looks like a nice thing for me. 

> Vector3.forward is a global constant equal to (0, 0, 1). I think you want the camera's transform.forward.

Omg, it works! Working in Unity even for years can be surprising by very common things. Thank you!

**Comment by tdmowrer** [comment]
> I think there is for sure has to be an angle, because you can't find anything if you check one pixel of the screen only. 

It isn't just a single pixel, but you can't adjust it, either. On iOS, for example, that raycast method maps to [`hitTest:types:`](https://developer.apple.com/documentation/arkit/arframe/2875718-hittest?language=objc). The documentation doesn't say exactly how it performs this test, but I'm sure it isn't a point-line intersection test because you would never hit anything that way.

> > Vector3.forward is a global constant equal to (0, 0, 1). I think you want the camera's transform.forward.
> 
> Omg, it works! Working in Unity even for years can be surprising by very common things. Thank you!

Thats great; are you still having problems with the hit test not returning results that you think it should, or are you good now?

**Comment by AytoMaximo** [comment]
> Thats great; are you still having problems with the hit test not returning results that you think it should, or are you good now?

Yeah, works as expected :) Thx again for your time and explanations!
