### ISSUE TITLE
Xcpuimage async convert 

### ISSUE THREAD

**Issue by astaikos316** [Unity-Technologies/arfoundation-samples#561]
How do I properly use async convert to be able to get the data bytes to pass to another process that needs the bytes to transmit the frame over a WebRTC implementation? Right now when I try to use it when I check the status of the conversion it is always in pending and after a few minutes the app crashes.

**Comment by astaikos316** [comment]
I am actually not getting any crash dumps that I can tell. The async conversion is always in pending state. I added logic to not try a new convert unless the async conversion is in ready state but always get it as pending

**Comment by DavidMohrhardt** [comment]
I see, well this sounds like a bug.  Please [log the bug](https://unity3d.com/unity/qa/bug-reporting) and post the case number so we can find it and track it faster.

**Comment by astaikos316** [comment]
Wanted to clarify a little more here. I am running latest ARFoudation 4.1 preview building the samples for an Android Galaxy Tab 5Ae running Android Pie. Using the base CPUImages example, that works on the tablet. But when I try to adapt the script to do Async Conversion, the system never leaves the Pending state. I tried to you the Convert already in the script but I have not been able to ready the native byte data of the converted image that I can feed to another script that creates an ARGB32 video frame.

**Comment by DavidMohrhardt** [comment]
Would you be able to provide the code snippet?

**Comment by astaikos316** [comment]
I am not sure if it is classified as a bug.  I can provide the code snippet I am using.  I may just not understand the async conversion function correctly.

This is my script:

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using Microsoft.MixedReality.WebRTC;
using Microsoft.MixedReality.WebRTC.Unity;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Collections;
using UnityEngine.Rendering;
using UnityEngine.UI;


public class ARVideoSource : CustomVideoSource<Argb32VideoFrameStorage>
{
	private VideoFrameQueue<Argb32VideoFrameStorage> _frameQueue = new VideoFrameQueue<Argb32VideoFrameStorage>(3);
	private Texture2D m_CameraTexture;
	private NativeArray<byte> rawTextureData;
	private XRCpuImage image;
	private XRCpuImage.AsyncConversion convertedImage;
	private bool m_Status = false;

	[SerializeField]
	[Tooltip("The ARCameraManager which will produce frame events.")]
	ARCameraManager m_CameraManager;

	/// <summary>
	/// Get or set the <c>ARCameraManager</c>.
	/// </summary>
	public ARCameraManager cameraManager {
		get => m_CameraManager;
		set => m_CameraManager = value;
	}

	[SerializeField]
	RawImage m_RawCameraImage;

	/// <summary>
	/// The UI RawImage used to display the image on screen.
	/// </summary>
	public RawImage rawCameraImage {
		get => m_RawCameraImage;
		set => m_RawCameraImage = value;
	}

	[SerializeField]
	[Tooltip("The AROcclusionManager which will produce human depth and stencil textures.")]
	AROcclusionManager m_OcclusionManager;

	public AROcclusionManager occlusionManager {
		get => m_OcclusionManager;
		set => m_OcclusionManager = value;
	}

	[SerializeField]
	RawImage m_RawHumanDepthImage;

	/// <summary>
	/// The UI RawImage used to display the image on screen.
	/// </summary>
	public RawImage rawHumanDepthImage {
		get => m_RawHumanDepthImage;
		set => m_RawHumanDepthImage = value;
	}

	[SerializeField]
	RawImage m_RawHumanStencilImage;

	/// <summary>
	/// The UI RawImage used to display the image on screen.
	/// </summary>
	public RawImage rawHumanStencilImage {
		get => m_RawHumanStencilImage;
		set => m_RawHumanStencilImage = value;
	}

	[SerializeField]
	RawImage m_RawEnvironmentDepthImage;

	/// <summary>
	/// The UI RawImage used to display the image on screen.
	/// </summary>
	public RawImage rawEnvironmentDepthImage {
		get => m_RawEnvironmentDepthImage;
		set => m_RawEnvironmentDepthImage = value;
	}

	[SerializeField]
	RawImage m_RawEnvironmentDepthConfidenceImage;

	/// <summary>
	/// The UI RawImage used to display the image on screen.
	/// </summary>
	public RawImage rawEnvironmentDepthConfidenceImage {
		get => m_RawEnvironmentDepthConfidenceImage;
		set => m_RawEnvironmentDepthConfidenceImage = value;
	}

	[SerializeField]
	Text m_ImageInfo;

	/// <summary>
	/// The UI Text used to display information about the image on screen.
	/// </summary>
	public Text imageInfo {
		get => m_ImageInfo;
		set => m_ImageInfo = value;
	}


	protected new void OnEnable()
	{
		if (m_CameraManager != null)
		{
			m_CameraManager.frameReceived += OnCameraFrameReceived;
		}
	}

	protected new void OnDisable()
	{
		if (m_CameraManager != null)
		{
			m_CameraManager.frameReceived -= OnCameraFrameReceived;
		}
	}


	unsafe void UpdateCameraImage()
	{
		// Attempt to get the latest camera image. If this method succeeds,
		// it acquires a native resource that must be disposed (see below).
		if (!cameraManager.TryAcquireLatestCpuImage(out image))
		{
			return;
		}

		// Display some information about the camera image
		m_ImageInfo.text = string.Format(
			"Image info:\n\twidth: {0}\n\theight: {1}\n\tplaneCount: {2}\n\ttimestamp: {3}\n\tformat: {4}",
			image.width, image.height, image.planeCount, image.timestamp, image.format);

		// Once we have a valid XRCpuImage, we can access the individual image "planes"
		// (the separate channels in the image). XRCpuImage.GetPlane provides
		// low-overhead access to this data. This could then be passed to a
		// computer vision algorithm. Here, we will convert the camera image
		// to an RGBA texture and draw it on the screen.

		// Choose an RGBA format.
		// See XRCpuImage.FormatSupported for a complete list of supported formats.
		var format = TextureFormat.BGRA32;

		if (m_CameraTexture == null || m_CameraTexture.width != image.width || m_CameraTexture.height != image.height)
		{
			m_CameraTexture = new Texture2D(image.width, image.height, format, false);
		}

		// Convert the image to format, flipping the image across the Y axis.
		// We can also get a sub rectangle, but we'll get the full image here.
		var conversionParams = new XRCpuImage.ConversionParams(image, format, XRCpuImage.Transformation.MirrorY);

		// Texture2D allows us write directly to the raw texture data
		// This allows us to do the conversion in-place without making any copies.
		var rawTextureData = m_CameraTexture.GetRawTextureData<byte>();

		

		if(m_Status == false)
		{
			convertedImage = image.ConvertAsync(conversionParams);
			m_Status = true;
		}
		

		//if (XRCpuImageAsyncConversionStatusExtensions.IsDone(XRCpuImage.AsyncConversionStatus.Ready))
		//{
		if(m_Status == true)
		{
			OnSceneFrameReady(convertedImage);
			m_Status = false;
		}
			
		//}

		//try
		//{
			
			//image.Convert(conversionParams, new IntPtr(rawTextureData.GetUnsafePtr()), rawTextureData.Length);
			
		//}
		//finally
		//{
			// We must dispose of the XRCpuImage after we're finished
			// with it to avoid leaking native resources.
			//OnSceneFrameReady();
			image.Dispose();
		//}

		// Apply the updated texture data to our texture
		m_CameraTexture.Apply();
		//OnSceneFrameReady(m_CameraTexture);

		// Set the RawImage's texture so we can visualize it.
		m_RawCameraImage.texture = m_CameraTexture;
	}

	void UpdateHumanDepthImage()
	{
		if (m_RawHumanDepthImage == null)
			return;

		// Attempt to get the latest human depth image. If this method succeeds,
		// it acquires a native resource that must be disposed (see below).
		if (occlusionManager && occlusionManager.TryAcquireHumanDepthCpuImage(out XRCpuImage image))
		{
			using (image)
			{
				UpdateRawImage(m_RawHumanDepthImage, image);
			}
		}
		else
		{
			m_RawHumanDepthImage.enabled = false;
		}
	}

	void UpdateHumanStencilImage()
	{
		if (m_RawHumanStencilImage == null)
			return;

		// Attempt to get the latest human stencil image. If this method succeeds,
		// it acquires a native resource that must be disposed (see below).
		if (occlusionManager && occlusionManager.TryAcquireHumanStencilCpuImage(out XRCpuImage image))
		{
			using (image)
			{
				UpdateRawImage(m_RawHumanStencilImage, image);
			}
		}
		else
		{
			m_RawHumanStencilImage.enabled = false;
		}
	}

	void UpdateEnvironmentDepthImage()
	{
		if (m_RawEnvironmentDepthImage == null)
			return;

		// Attempt to get the latest environment depth image. If this method succeeds,
		// it acquires a native resource that must be disposed (see below).
		if (occlusionManager && occlusionManager.TryAcquireEnvironmentDepthCpuImage(out XRCpuImage image))
		{
			using (image)
			{
				UpdateRawImage(m_RawEnvironmentDepthImage, image);
			}
		}
		else
		{
			m_RawEnvironmentDepthImage.enabled = false;
		}
	}

	void UpdateEnvironmentDepthConfidenceImage()
	{
		if (m_RawEnvironmentDepthConfidenceImage == null)
			return;

		// Attempt to get the latest environment depth image. If this method succeeds,
		// it acquires a native resource that must be disposed (see below).
		if (occlusionManager && occlusionManager.TryAcquireEnvironmentDepthConfidenceCpuImage(out XRCpuImage image))
		{
			using (image)
			{
				UpdateRawImage(m_RawEnvironmentDepthConfidenceImage, image);
			}
		}
		else
		{
			m_RawEnvironmentDepthConfidenceImage.enabled = false;
		}
	}

	static void UpdateRawImage(RawImage rawImage, XRCpuImage cpuImage)
	{
		// Get the texture associated with the UI.RawImage that we wish to display on screen.
		var texture = rawImage.texture as Texture2D;

		// If the texture hasn't yet been created, or if its dimensions have changed, (re)create the texture.
		// Note: Although texture dimensions do not normally change frame-to-frame, they can change in response to
		//    a change in the camera resolution (for camera images) or changes to the quality of the human depth
		//    and human stencil buffers.
		if (texture == null || texture.width != cpuImage.width || texture.height != cpuImage.height)
		{
			texture = new Texture2D(cpuImage.width, cpuImage.height, cpuImage.format.AsTextureFormat(), false);
			rawImage.texture = texture;
		}

		// For display, we need to mirror about the vertical access.
		var conversionParams = new XRCpuImage.ConversionParams(cpuImage, cpuImage.format.AsTextureFormat(), XRCpuImage.Transformation.MirrorY);

		// Get the Texture2D's underlying pixel buffer.
		var rawTextureData = texture.GetRawTextureData<byte>();

		// Make sure the destination buffer is large enough to hold the converted data (they should be the same size)
		Debug.Assert(rawTextureData.Length == cpuImage.GetConvertedDataSize(conversionParams.outputDimensions, conversionParams.outputFormat),
			"The Texture2D is not the same size as the converted data.");

		// Perform the conversion.
		cpuImage.Convert(conversionParams, rawTextureData);

		// "Apply" the new pixel data to the Texture2D.
		texture.Apply();

		// Make sure it's enabled.
		rawImage.enabled = true;
	}

	protected override void OnFrameRequested(in FrameRequest request)
	{
		// Try to dequeue a frame from the internal frame queue
		if (_frameQueue.TryDequeue(out Argb32VideoFrameStorage storage))
		{
			var frame = new Argb32VideoFrame
			{
				width = (uint)storage.Width,
				height = (uint)storage.Height,
				stride = (int)storage.Width * 4
			};
			unsafe
			{
				fixed (void* ptr = storage.Buffer)
				{
					// Complete the request with a view over the frame buffer (no allocation)
					// while the buffer is pinned into memory. The native implementation will
					// make a copy into a native memory buffer if necessary before returning.
					frame.data = new IntPtr(ptr);
					request.CompleteRequest(frame);
				}
			}
			
			// Put the allocated buffer back in the pool for reuse
			_frameQueue.RecycleStorage(storage);
		}

	}

	private void OnSceneFrameReady(XRCpuImage.AsyncConversion request)
	{

		// Read back the data from GPU, if available
		if (request.status != XRCpuImage.AsyncConversionStatus.Ready)
		{

			Debug.Log(request.status);
			return;
		}


		NativeArray<byte> rawData = request.GetData<byte>();
		Debug.Log(rawData.Length);

		unsafe
		{
			byte* ptr = (byte*)NativeArrayUnsafeUtility.GetUnsafePtr(rawData);

			// Enqueue a frame in the internal frame queue. This will make a copy
			// of the frame into a pooled buffer owned by the frame queue.
			var frame = new Argb32VideoFrame
			{
				data = (IntPtr)ptr,
				stride = image.width * 4,
				width = (uint)image.height,
				height = (uint)image.width
			};
			//Debug.Log(frame.width + " " + frame.height + " " + frame.data);
			_frameQueue.Enqueue(frame);
		}
	}

	void OnCameraFrameReceived(ARCameraFrameEventArgs eventArgs)
	{
		UpdateCameraImage();
		UpdateHumanDepthImage();
		UpdateHumanStencilImage();
		UpdateEnvironmentDepthImage();
		UpdateEnvironmentDepthConfidenceImage();
	}
}

**Comment by tdmowrer** [comment]
Hi @astaikos316,

> Right now when I try to use it when I check the status of the conversion it is always in pending and after a few minutes the app crashes.

You are claiming to be experiencing incorrect behavior followed by a crash. That is a bug, and it needs to be logged as such. Even if the problem is entirely on our end, it may be difficult to reproduce without your specific project.

Please log a bug by following the instructions at https://unity3d.com/unity/qa/bug-reporting and post the case ID here. Thanks in advance!

**Comment by astaikos316** [comment]
I started out asking how to properly use the async convert.  Then I just described the behavior.  I posted my script above to show my logic and to ask here whether it is correct or not.  I started this as a how-to thread because I haven't come across any examples using the AsyncConvert.

**Comment by mdurand42** [comment]
The best way for us to help you is to provide a minimum repro project and submit that via the Unity Issue Tracker. Pasting the code you provided into a project of our own is not a reliable way to do this since project settings could be different. Thanks.

**Comment by astaikos316** [comment]
The repro project comes out to be fairly large when I tried to include the whole thing due to the size of webrtc.  Only project settings config changes I had to do was building to IL2CPP and AMR64 processor.  I am not sure how to proceed here and get some assistance.

**Comment by mdurand42** [comment]
Our Issue Tracker is capable of handling very large repro projects. If you would like further assistance with this issue then that is the proper way forward.
