### ISSUE TITLE
XRCpuImage with WindowsMixedReality Plugin for Hololens 2 

### ISSUE THREAD

**Issue by andnovar** [Unity-Technologies/arfoundation-samples#562]
I am trying to acquire frames from Hololens 2. I am wondering if this feature is enable for the Windows Mixed Reality Plugin ?

The code works with the ARCore Plugin on an Android phone but not when deployed to Hololens 2.

Thanks !

**Comment by tdmowrer** [comment]
> I am wondering if this feature is enable for the Windows Mixed Reality Plugin ?

No, the [XRCpuImage API](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/cpu-camera-image.html) is not implemented for HoloLens.
