### ISSUE TITLE
In ARKIT 4.1.0, how to properly set up face tracking on the front camera while using the world camera simultaneously?

### ISSUE THREAD

**Issue by elnazta** [Unity-Technologies/arfoundation-samples#563]
Creating a new thread based on our discussion @tdmowrer 
I am using ARKIT XR Plugin 4.1.0, I also have the same version ARKIT Face Tracking installed in Unity. I am using AR Foundation 4.1.0 and unfortunately I can't find out how to activate face tracking on the front camera while looking at the world tracking camera. 
Most references discuss ARWorldTrackingConfiguration with userFaceTrackingEnabled, and I'm not sure how to enable both simultaneously while looking at the rear camera in my AR experience. 
Additionally, what is the correct way of getting the face position, rotation and eye positions of the user facing camera while having the world camera active? 
The tutorials I can find about ARKIT seem to be mainly based on the ARKIT deprecated plugin. I would appreciate advice on getting started with this.

**Comment by tdmowrer** [comment]
> Creating a new thread based on our discussion @tdmowrer

Thank you.

> I am using AR Foundation 4.1.0 and unfortunately I can't find out how to activate face tracking on the front camera while looking at the world tracking camera.

We have a [sample](https://github.com/Unity-Technologies/arfoundation-samples#worldcamerawithuserfacingfacetracking) that demonstrates this. Here's how it works:

You want the world-facing camera, so make sure you've selected the world-facing camera in the ARCameraManager component:

![Screen Shot 2020-07-28 at 9 14 42 AM](https://user-images.githubusercontent.com/4934281/88692466-ef8d6a80-d0b2-11ea-996d-4e20f23c24b5.png)

You also want face tracking enabled, so make sure you have an `ARFaceManager` (and that it is enabled) on the `ARSessionOrigin`:

![Screen Shot 2020-07-28 at 9 16 35 AM](https://user-images.githubusercontent.com/4934281/88692601-1ba8eb80-d0b3-11ea-9466-bb2de19ae6ab.png)

> Additionally, what is the correct way of getting the face position, rotation and eye positions of the user facing camera while having the world camera active?

The `ARFaceManager` creates `ARFace`s when a face is detected. The `ARFaceManager` has an [event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARFaceManager.html#UnityEngine_XR_ARFoundation_ARFaceManager_facesChanged) you can subscribe to whenever a face is added or updated, and you can also enumerate them at any time using the `ARFaceManager.trackables` collection.

Note that only some devices can do this. In a [development player build](https://docs.unity3d.com/Manual/BuildSettings.html), ARFoundation logs debug output to the Xcode console that will tell you what features were requested, which it was able to satisfy, and which could not be satisfied. Note also that if you enable other features, it may decide to choose a different configuration that is able to satisfy more of the features you've requested. There are more details on how configurations are chosen [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/migration-guide-3.html#camera-and-tracking-mode-selection).

**Comment by mdurand42** [comment]
Closing due to lack of response. Please re-open if @tdmowrer 's message did not resolve the issue.

**Comment by elnazta** [comment]
@tdmowrer Everything worked out, but when I'm trying to get the position of the face, left eye and right eye, this is for example one of the results I am getting: Left eye (0.0, 0.1, -0.3), Right eye (0.0, 0.1, -0.4), and Face position is (0.0, 0.0, -0.3). Is that a normal position to get for these components? When I look at the diagrams from ARKIT that show Face and eyes, the position seem to be the center point of each, not the way I'm getting my results. 

In order to get these positions, I used Debug.Log() in the OnBeforeRender class using the existing DisplayFaceInfo script. Am I doing something wrong? Below is my script to show you what I'm doing:

void OnBeforeRender()
    {
        if (m_FaceControlledObject == null)
            return;

        foreach (var face in m_FaceManager.trackables)
        {
            if (face.trackingState == TrackingState.Tracking)
            {
                m_FaceControlledObject.transform.rotation = face.transform.rotation;
                var camera = m_CameraManager.GetComponent<Camera>();
                m_FaceControlledObject.transform.position = camera.transform.position + camera.transform.forward * 0.5f;
                Debug.Log("left eye method 2 location is " + m_FaceManager.TryGetFace(face.trackableId).leftEye.transform.position.ToString());
                Debug.Log("Face location method 2 is" + m_FaceManager.TryGetFace(face.trackableId).transform.position.ToString());
                Debug.Log("right eye method 2 location is " + m_FaceManager.TryGetFace(face.trackableId).rightEye.transform.position.ToString());
            }
        }
    }
