### ISSUE TITLE
Is it possible to have AR Camera inside an object to create a dome effect?

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#564]
Hi,

I wanted to ask this question as my next project will involve (if possible) having a dome effect when the user clicks on an object.

I wanted to ask if it's possible to do that, knowing that the Camera won't render something if it's not in front of it.

What my project is aiming to do is have an Earth object which when clicked would expand to include the user in it.

I will kindly appreciate any help!

EDIT:

To better explain what I would like to do, I'm attaching a screenshot underneath. I would like to (somehow) cover the camera around with objects that would reflect the earth globe (maybe even instead of using planes, to somehow use 1 singular sphere)

![Screen Shot 2020-07-29 at 5 06 02 PM](https://user-images.githubusercontent.com/18481583/88818822-6e6fc980-d1bf-11ea-9696-4c3de8a5253f.png)

**Comment by mdurand42** [comment]
Hi @Sterling-Malory-Archer. This kind of question is best asked on the Unity forums since it does not relate to AR.

I will close this issue but you may want to have a look at this https://docs.unity3d.com/Manual/class-Skybox.html
