### ISSUE TITLE
How to get correct position of ARTrackedImage in Android

### ISSUE THREAD

**Issue by daoth90** [Unity-Technologies/arfoundation-samples#567]
Hi everyone, I'm making a very simple app that spawns a 3D game object at where the device determined the target image. And I don't want to set that prefab to TrackedImagePrefab in ARTrackedImageManager.

For example: In IOS, the position of the ARTrackedImage is .5 .5 .5. But in Android, it always returns 0 0 0. It makes the position of the 3D object I want to spawn manually incorrectly (not at where the device found the target image).

I don't know why.

I tested with a 3D cube and set it as TrackedImagePrefab, the cube spawned correctly at the target image but its position always 0 0 0

AR Foundation 2.1.8
ARCore XR plugin 2.1.8
ARKit XR Plugin 2.1.9
Unity 2019.4.1f1
Google Pixel 3

**Comment by mdurand42** [comment]
Could you verify that the tracking state is in TrackingState.Tracking when you observe that the values are 0 0 0? We recommend that you check the tracking state before relying on the tracked image.

**Comment by daoth90** [comment]
> Could you verify that the tracking state is in TrackingState.Tracking when you observe that the values are 0 0 0? We recommend that you check the tracking state before relying on the tracked image.

Thank @mdurand42, I was able to get the correct position of ARTrackedImage in Android.
The first time it goes to the callback, it always returns 0 0 0 so I put it into a Coroutine to wait for the TrackedImage ref state changes to Tracking.
