### ISSUE TITLE
[Android]Set different physic width for the reference image,the prefab's size doesn't change accordingly

### ISSUE THREAD

**Issue by CindyCYQ** [Unity-Technologies/arfoundation-samples#573]
this is a issue only happens on android platform,it's okay on ios,and it's okay with static(non-runtime) referenceImageLibrary,only with runtime reference image library on android,I have set different physical width when call ScheduleAddImageJob method,and the reference image's width has been changed to the value I set when the image has been detected,but the prefab created stays in a fixed scale.
ARFoundation: 4.0.2
unity version:2019.4.6f1 LTS

**Comment by tdmowrer** [comment]
Please [log a bug](https://unity3d.com/unity/qa/bug-reporting) and attach a project that reproduces the issue.

**Comment by CindyCYQ** [comment]
> Please [log a bug](https://unity3d.com/unity/qa/bug-reporting) and attach a project that reproduces the issue.
I have downgraded the ARFoundation version to 3.1.3 to solve the issue.I can attach a project later,but to reproduce the issue,u can create a project to test image tracking with runtime marker,then u can compare the prefab's size on android and ios,OR u can modify the physical width when add texture to runtime library to check the prefab's size on both android and ios.
