### ISSUE TITLE
How can I change the TrackedImagePrefab during runtime?

### ISSUE THREAD

**Issue by Westycoot** [Unity-Technologies/arfoundation-samples#575]
Hi all,

I have got image tracking working and it displays the initial prefab that I give it.
I want to be able to change the prefab that is shown during runtime.

I have tried using this arTrackingImageManager.trackedImagePrefab = GameObjectPrefab;

This works the first time it assigned, but then cannot be updated to a new prefab to show.

Do I need to somehow reset the image tracker to recognise this trackedImagePrefab change?

Many thanks.

**Comment by tdmowrer** [comment]
The purpose of the prefab assigned to the `ARTrackedImageManager` is to customize the GameObject that is created to represent its position in the world. Typically, you should leave it unassigned. It should not be used to instantiate content in response to a detected image.

If that is your goal, simply instantiate your prefab as a child of the detected `ARTrackedImage`. Subscribe to the [`ARTrackedImageManager.trackedImagesChanged` event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged) to be notified when a new image is detected.

The [`ARFoundation Demos` repo](https://github.com/Unity-Technologies/arfoundation-demos) contains a sample that shows how to instantiate different prefabs in response to different images.

**Comment by Westycoot** [comment]
Hi tdmowrer,

Many thanks for your reply.

That is close to what I am trying to do, however in this case I just want to be able to change the prefab that is on the same tracked image. I am not looking to instantiate different prefabs in response to different images, rather I want to be able to change the prefab that is shown on top of the AR tracked image after a button press or another event. 

To do this, could I just directly change the prefab that is a child of the detected ARTrackedImage programatically?  If I can do it this way, what would be the best way to access the tracked image component?

Many thanks.

**Comment by tdmowrer** [comment]
> To do this, could I just directly change the prefab that is a child of the detected ARTrackedImage programatically?

Sure. ARFoundation will only affect the `ARTrackedImage` and the `Transform` of the GameObject it is on. If you have something parented to do that, simply `Destroy` your GameObject and `Instantiate` something else with the same tracked image as parent.

> what would be the best way to access the tracked image component?

You can get a list of all of them from the `ARTrackedImageManager`'s `trackables` property. All the managers work this way; see ["Enumerating Trackables"](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/trackable-managers.html#enumerating-trackables).

**Comment by Westycoot** [comment]
Hi tdmowrer,

Thank you very much for your help, I have now got this working by using the trackables property to access the gameobject that is on the ARTrackedImage transform and assigning the initial prefab using the ARTrackedImageManager.trackedImagesChanged event as you suggested rather than trying to manipulate trackedImagePrefab.

Many thanks for all the help you have given to me and others here :)
