### ISSUE TITLE
How to get the colors of the feature points in an efficient way ?

### ISSUE THREAD

**Issue by handrianj** [Unity-Technologies/arfoundation-samples#576]
Hi everyone !

How can I get the feature points colors ? ARKit and ARcore have these functions natively but the data doesn't seem available in ARfoundation.

Right now it looks like the easiest way would be to get the current background as a texture and project each point on the background to get the color corresponding to the point. I can implement it this way but I would like to know if there is another approach?

Thank you !

**Comment by tdmowrer** [comment]
> ARKit and ARcore have these functions natively

Can you point me to the documentation for this? I don't see that in the ARKit documentation for their point cloud, for instance:

https://developer.apple.com/documentation/arkit/arpointcloud?language=objc

Each point just has a position and unique identifier. Same for ARCore:

https://developers.google.com/ar/reference/c/group/frame

**Comment by handrianj** [comment]
> 
> 
> > ARKit and ARcore have these functions natively
> 
> Can you point me to the documentation for this? I don't see that in the ARKit documentation for their point cloud, for instance:
> 
> https://developer.apple.com/documentation/arkit/arpointcloud?language=objc
> 
> Each point just has a position and unique identifier. Same for ARCore:
> 
> https://developers.google.com/ar/reference/c/group/frame

My bad, I thought I saw it in the old ARkit unity SDK... I can't find it again now but after checking around it looks like it's not done natively. I was probably blinded by this [video](https://www.youtube.com/watch?v=Pb4uv4FSWKI).

**Comment by tdmowrer** [comment]
It is possible to obtain a color associated with each feature point, but there is no API for this. You could, for example, compute the screen space coordinate of each feature point and then obtain the color of the pixel at that point. This is probably along the lines of what the app in the video does.
