### ISSUE TITLE
iOS freezes upon loading other scene and sometimes at random

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#58]
Unity 2018.2.14, xcode 10.1 (aswel as older versions). 

Happens about half the time when loading a scene from the ARKit scene, across different devices and ios versions (ipads/iphones)

Comes with a complimentary 'EXC_BAD_ACCESS (code=1, address=0xf000000011d7097f)' 

Not always in the same file, but usualy in something cameratexture related. In the attached pastebin it happened in CameraImageApi::ImageManager::~ImageManager()

https://pastebin.com/QF47c9sb

**Comment by tdmowrer** [comment]
This is due to [this known issue](https://issuetracker.unity3d.com/issues/ios-android-ar-foundation-project-crashes-when-having-more-than-one-ar-scene). A fix is on the way.
