### ISSUE TITLE
[Bug] Android crash due to AR Core 64-bit only as of Aug2020

### ISSUE THREAD

**Issue by Feddas** [Unity-Technologies/arfoundation-samples#583]
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.
Case 1271697
(This process is frustrating with a slow upload speed)

**Describe the bug**
App crashes on an Android Pixel 3 after loading a scene that uses the camera (such as the Simple AR scene). Due to the project being set to a 32-bit Android ARMv7 build.

**To Reproduce**
1. "Build and Run" to a Pixel 3.
2. On the phone tap on "Simple AR". 
3. Observe, app force quits due to a crash.

The crash is due to an 64-bit requirement update Google pushed in August 2020. More details on the forum at https://forum.unity.com/threads/whats-new-in-unitys-ar-foundation.939693/#post-6216014  That thread also mentions the fix, switching it to target only ARM64 Android phones.

**Expected behavior**
To not force quit the application on the phone with a crash.

**Actual behavior**
Force quits the application on the phone with a crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: probably Android 10.0
 - 2018.4.81
 - ARFoundation version 2.1.8

**Comment by tdmowrer** [comment]
I'm not sure I understand the ask here. ARFoundation supports 64 bit Android, and the "force quit" sounds like something enforced at the OS level when building for 32 bit. Are you suggesting that we simply disallow 32 bit builds?

However, I don't think this is the cause of the crash. I can run this samples repo on a Pixel 3 running Android 10 with a 32 bit build. Additionally, that forum posts also mentions

> I tried the HelloAR scene from https://developers.google.com/ar/develop/unity/quickstart-android. This also crashed.

I can also run the HelloAR scene from Google's plugin without issue.

**Comment by Feddas** [comment]
Yes, I'm suggesting targeting 32-bit builds be disabled by default in this project.

I'm trying to think of why mine is crashing when any AR Core scene is targeting ARMv7 and yours is not. I wonder if my crashes are due to a fresh install of Unity that also did a fresh install of the latest Android support. The SDK's there could be what was enforcing 64bit only requirement mentioned on https://developers.google.com/ar/64bit

**Comment by tdmowrer** [comment]
> Yes, I'm suggesting targeting 32-bit builds be disabled by default in this project.

Okay, I think that makes sense for this repo.

> I'm trying to think of why mine is crashing when any AR Core scene is targeting ARMv7 and yours is not.

It may depend on whether or not you had Google Play Services for AR (i.e., the ARCore APK) installed prior to a certain date.

**Comment by tdmowrer** [comment]
Relevant links for posterity:

https://github.com/google-ar/arcore-unity-sdk/issues/751

https://github.com/google-ar/arcore-unity-sdk#upcoming-breaking-change-affecting-previously-published-32-bit-only-apps

> ## Upcoming breaking change affecting previously published 32-bit-only apps
> In **August 2020**, _Google Play Services for AR_ (ARCore) will remove support
for 32-bit-only ARCore-enabled apps running on 64-bit devices. Support for
32-bit apps running on 32-bit devices is unaffected.
> 
> If you have published a 32-bit-only (`armeabi-v7a`) version of your
ARCore-enabled app without publishing a corresponding 64-bit (`arm64-v8a`)
version, you must update your app to include 64-bit native libraries before
August 2020. 32-bit-only ARCore-enabled apps that are not updated by this time
may crash when attempting to start an augmented reality (AR) session.

**Comment by tdmowrer** [comment]
The `latest-preview` branch now targets both 32 and 64 bit architectures on Android.

**Comment by Feddas** [comment]
Commit 87d8531 looks good to me. Thanks @tdmowrer ! Here's hoping this prevents other that could have been dumbfounded by crashes.
