### ISSUE TITLE
How to adjust the apparent scale of content in an AR scene and use AROcclusionManager at the same time.

### ISSUE THREAD

**Issue by smallfly** [Unity-Technologies/arfoundation-samples#584]
Hi,

Is there away to both adjust the rotation/scale of the ARSessionOrigin and use AROcclusionManager at the same time?

Thank you!

**Comment by tdmowrer** [comment]
This looks like a bug. We'll look into it.

**Comment by smallfly** [comment]
Thank you!

**Comment by dtaddisF42** [comment]
I got around this by making a custom ARCameraBackground material (shamelessly copied from the PackageCache), and applying the same scale to the depth value used for occlusion as that applied to ARSessionOrigin. I would love an official fix though!

**Comment by smallfly** [comment]
@dtaddisF42 Thanks for sharing. Could you give a bit more details on how you implemented it?

@tdmowrer any idea about when this will be fixed? Thank you.

**Comment by fsal-code** [comment]
We would appreciate if an urgent fix is submitted ASAP.

**Comment by tdmowrer** [comment]
> @tdmowrer any idea about when this will be fixed? Thank you.

No ETA yet, no.

**Comment by fsal-code** [comment]
Any suggested workarounds for the time being? We need to submit a retail demo to Apple and we have a deadline from them. Thank you.

**Comment by dtaddisF42** [comment]
@smallfly More details on a workaround here: https://forum.unity.com/threads/using-arocclusionmanager-and-scaled-arsessionorigin-occludes-everything.934815/

I hope it's useful in the meantime.

**Comment by tdmowrer** [comment]
This was fixed in 4.1.0-preview.9 of [ARCore](https://docs.unity3d.com/Packages/com.unity.xr.arcore@4.1/changelog/CHANGELOG.html#fixes-1) and [ARKit](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.1/changelog/CHANGELOG.html#fixes).
