### ISSUE TITLE
AR Image Tracking in arfoundation for ios device does not track the plane of the image like native ios arkit app

### ISSUE THREAD

**Issue by MohsinKhan-dev** [Unity-Technologies/arfoundation-samples#585]
**Describe the bug**
When a AR ios app using arkit 2 is build natively(not using Unity 3d), the tracked image location is perfectly aligned with the plane of physical image to be tracked but when we use AR foundation for the same purpose, the ARtracked Image position is not on the plane of the physical image to be tracked. And when we move the camera(ipad or phone device compatible with arkit 2.0), the tracked image position also changes

**To Reproduce**
1. Build ios app using arfoundation-samples
2. Run app on IOS device running ios 12 or above
3. Click on Image tracking tab from menu
4. Try to track the image you provided in the reference Image Library in your unity project

**Test Case Specification**
 - Device: Ipad 7th generation (A2197)
 - OS: iOS 13
 - Unity version 2019.4.4
 - ARFoundation 4.1.0

**Comment by tdmowrer** [comment]
This was resolved under a separate professional services engagement.
