### ISSUE TITLE
Error: linker command failed with exit code 1 (use -v to see invocation) when Archive in Xcode

### ISSUE THREAD

**Issue by HuuLinhDra** [Unity-Technologies/arfoundation-samples#588]
I'm using Unity 2020.1.3f1, Xcode Version 11.6 (11E708), and MacOS Catalina version 10.15.6 (19G2021). when I build .ipa file in Xcode, Step Archive this project has error: 
Ld /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnityFramework.framework/UnityFramework normal arm64
    cd /Users/macbook/Downloads/arfoundation-samples-latest-preview/build
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk -L/Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -L/Users/macbook/Downloads/arfoundation-samples-latest-preview/build/Libraries -L/Users/macbook/Downloads/arfoundation-samples-latest-preview/build/Libraries/com.unity.xr.arkit/Runtime/iOS/Xcode1200 -L/Users/macbook/Downloads/arfoundation-samples-latest-preview/build/Libraries/com.unity.xr.arkit-face-tracking/Runtime/iOS/Xcode1200 -F/Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -filelist /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp /Users/macbook/Downloads/arfoundation-samples-latest-preview/build/Libraries/baselib.a -lUnityARKit -lUnityARKitFaceTracking -framework ARKit -framework MetalPerformanceShaders -framework MultipeerConnectivity -weak_framework Metal -weak_framework GameController -Xlinker -dependency_info -Xlinker /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/macbook/Library/Developer/Xcode/DerivedData/Unity-iPhone-fmwgidamrlokazczbyshgjjrxybu/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnityFramework.framework/UnityFramework
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1200.0.26.2.0_0' Reader: '1103.0.32.62_0')', using libLTO version 'LLVM version 11.0.3, (clang-1103.0.32.62)' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing All Issues
: Could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1200.0.26.2.0_0' Reader: '1103.0.32.62_0')', using libLTO version 'LLVM version 11.0.3, (clang-1103.0.32.62)' for architecture arm64

Thanks,
Linh

**Comment by mdurand42** [comment]
If you are using the 4.1.0-preview packages then you must build your project using Xcode 12 beta. If you need to use Xcode 11 to build your project you should use the 4.0.x verified packages.
