### ISSUE TITLE
[Bug] Camera feed is upside down

### ISSUE THREAD

**Issue by angecroft** [Unity-Technologies/arfoundation-samples#589]
**Unity bug report case number**
1273490

**Describe the bug**
The camera is upside down when switching orientation from **_landscape left_** to **_landscape right_** directly or from **_portrait_** to **_portrait upside down_**.

**To Reproduce**
1. Create an AR project or start from the ARFoundation sample project
2. Set the default orientation to **Portrait** in Project Settings
3. Add the following code in _Awake()_ or _Start()_ of any script
```
Screen.orientation = ScreenOrientation.AutoRotation;
Screen.autorotateToLandscapeLeft = true;
Screen.autorotateToLandscapeRight = true;
Screen.autorotateToPortraitUpsideDown = true;
```

4. Build and launch the app on the device
5. Switch orientation from **_landscape left_** to **_landscape right_** directly or from **_portrait_** to **_portrait upside down_** quickly.
6. See that the camera is upside down

**Expected behavior**
The camera should update it's orientation like the rest of the app (the UI does)

**Actual behavior**
The camera is upside down when switching orientation from **_landscape left_** to **_landscape right_** directly or from **_portrait_** to **_portrait upside down_**.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi mix 2S, Samsung Galaxy Tab S4
 - OS: Android 10, Android 8.1.0
 - Unity version 2019.4.8f1
 - ARFoundation version 4.1.0 preview-6 
- ARCore XR Plugin version 4.1.0 preview-6

**Comment by mdurand42** [comment]
This is a bug in non-AR code as we have reproduced this without AR Foundation and associated packages. We have opened a bug internally for the mobile team to investigate.

**Comment by tdmowrer** [comment]
You can track the issue [here](https://issuetracker.unity3d.com/issues/android-screen-dot-orientation-does-not-change-if-rotating-device-from-one-landscape-to-the-other-or-from-portrait-to-upside-down).

**Comment by angecroft** [comment]
Thank you for the update
