### ISSUE TITLE
ARTrackedImagesChangedEventArgs update

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#593]
void ImageCheckEventHandler(ARTrackedImagesChangedEventArgs eventArgs)
        {
            foreach (var item in eventArgs.added)
            {
                Debug.Log("add - image - name :"+item.referenceImage.name);
            }

            foreach (var item in eventArgs.updated)
            {
                if(item.trackingState==TrackingState.Tracking)
                Debug.Log("add - image - name :" + item.referenceImage.name);
            }
        }

[IOS]  (item.trackingState==TrackingState.Tracking)  it can work

[ANDROID] it can't work, it will show all images that add before  event though  only one image is checking 

so, how can i do，thanks ！

**Comment by tdmowrer** [comment]
What is "it" and how do you define "working"?

**Comment by Arytes** [comment]
void ImageCheckEventHandler(ARTrackedImagesChangedEventArgs eventArgs)
        {
            foreach (var item in eventArgs.added)
            {
                Debug.Log("add - image - name :"+item.referenceImage.name);
                checkingName = item.referenceImage.name;
            }

            foreach (var item in eventArgs.updated)
            {
                if(item.trackingState==TrackingState.Tracking)
                {
                    if(checkingName!= item.referenceImage.name)
                    {
                        checkingName = item.referenceImage.name;
                    }
                }
                Debug.Log("add - image - name :" + item.referenceImage.name);
            }
        }

you can look this ，i want to check four images and get  current checkingName，but it will retern all image that added before
this code can work in ios， but android it can't work ，idon't why ，maybe you could check！

**Comment by Arytes** [comment]
> 什么是“它”以及如何定义“工作”？



> What is "it" and how do you define "working"?
void ImageCheckEventHandler(ARTrackedImagesChangedEventArgs eventArgs)
{
foreach (var item in eventArgs.added)
{
Debug.Log("add - image - name :"+item.referenceImage.name);
checkingName = item.referenceImage.name;
}

        foreach (var item in eventArgs.updated)
        {
            if(item.trackingState==TrackingState.Tracking)
            {
                if(checkingName!= item.referenceImage.name)
                {
                    checkingName = item.referenceImage.name;
                }
            }
            Debug.Log("add - image - name :" + item.referenceImage.name);
        }
    }
you can look this ，i want to check four images and get current checkingName，but it will retern all image that added before
this code can work in ios， but android it can't work ，idon't why ，maybe you could check！

**Comment by DavidMohrhardt** [comment]
ARCore (Android) maintains tracking information of images that are out of view.  This prints because it is still tracking images out of view.

Google's Docs

```
Once an image is detected, ARCore continues "tracking" the image's position and orientation, even when the image temporarily moves out of the camera view because the user has moved their device. In doing so, ARCore assumes that the image's position and orientation is static, and that the image is not itself moving through the environment.
```
