### ISSUE TITLE
[Bug] ARTrackedImage's name is empty while reinstantiate AR

### ISSUE THREAD

**Issue by chaoslife** [Unity-Technologies/arfoundation-samples#594]
Hello, our program will recognize the picture after entering AR, then exit AR to destroy the AR module.(ARSession and others)
When entering AR for the first time, call the mutableLibrary.ScheduleAddImageJob method to correctly pass in the name of the image, and then in the trackedImagesChanged callback, the name and the GUID have values.

After the AR is destroyed, enter again and instantiated, the name returned by ARTrackedImage is empty, and the GUID is 00000?
Almost no problem for the first two times, but the third time it returned empty

Is this what is the reason?

ar version is : 4.1.0-preview.7
unity: 2019.4.8f

**Comment by Hless** [comment]
Encountered the same bug, resolved it by resetting the ARSession between creating new mutable libraries, see comment here:
https://github.com/Unity-Technologies/arfoundation-samples/issues/385#issuecomment-650094655

**Comment by mdurand42** [comment]
Hello. What do you mean by "after the AR is destroyed". What is your app doing to destroy and restart AR functionality?

Also  (in case it's not clear from the documentation) the images added to the mutable image libraries do not persist between runs or between session restarts.

-Mike

**Comment by chaoslife** [comment]
> 你好。“ AR被摧毁后”是什么意思。您的应用程序在做什么以破坏并重新启动AR功能？
> 
> 同样（如果文档中不清楚），添加到可变图像库的图像在运行之间或会话重新启动之间也不会保留。
> 
> -麦克风

Hi, I mean Destroy ARSession and other ar relative objects(int our product means quit ar mode and reopen ar )

**Comment by mdurand42** [comment]
It might be helpful for you to log an issue for this via the Issue Tracker. Thanks.
