### ISSUE TITLE
[Bug] Asset import failed for arobjects. FormatException.

### ISSUE THREAD

**Issue by JoshuaHeim** [Unity-Technologies/arfoundation-samples#597]
When opening the project in 2020.1.4f1 I get the following error:

Asset import failed, "Assets/Scenes/Object Tracking/Cube.arobject" > FormatException: Input string was not in a correct format.
System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Single.Parse (System.String s) (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEditor.XR.ARKit.ARObjectInfo.GetWithDefault (System.Collections.Generic.Dictionary`2[TKey,TValue] dict, System.String key, UnityEngine.Quaternion defaultValue) (at Library/PackageCache/com.unity.xr.arkit@4.1.0-preview.7/Editor/ObjectTracking/ARObjectInfo.cs:118)
UnityEditor.XR.ARKit.ARObjectInfo..ctor (System.Xml.XmlDocument plist) (at Library/PackageCache/com.unity.xr.arkit@4.1.0-preview.7/Editor/ObjectTracking/ARObjectInfo.cs:39)
UnityEditor.XR.ARKit.ARObjectImporter.ReadInfo (System.String path) (at Library/PackageCache/com.unity.xr.arkit@4.1.0-preview.7/Editor/ObjectTracking/ARObjectImporter.cs:95)
UnityEditor.XR.ARKit.ARObjectImporter.ReadARObject (System.String path) (at Library/PackageCache/com.unity.xr.arkit@4.1.0-preview.7/Editor/ObjectTracking/ARObjectImporter.cs:45)
UnityEditor.XR.ARKit.ARObjectImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.xr.arkit@4.1.0-preview.7/Editor/ObjectTracking/ARObjectImporter.cs:28)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at /Users/builduser/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)

This happens for any .arobject that I try to import.

**Comment by JoshuaHeim** [comment]
Change Region settings on machine

**Comment by tdmowrer** [comment]
This looks like a bug. You shouldn't have to change the region settings on your machine.

**Comment by tdmowrer** [comment]
https://issuetracker.unity3d.com/product/unity/issues/guid/1276935/

**Comment by tdmowrer** [comment]
This was fixed in [4.1.0-preview.9](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.1/changelog/CHANGELOG.html#fixes).
