### ISSUE TITLE
Why does 'InvalidCastException: Specified cast is not valid.' occur for ARKitFaceSubsystem?

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#598]
Why does 'InvalidCastException: Specified cast is not valid.' occur for ARKitFaceSubsystem in the snippet below?

            var faceManager = FindObjectOfType<ARFaceManager>();
            if (faceManager != null)
            {
                m_ARKitFaceSubsystem = (ARKitFaceSubsystem)faceManager.subsystem;
            }

**Comment by tdmowrer** [comment]
It means `faceManager.subsystem` is not an `ARKitFaceSubsystem`. Are you running this on iOS?

```csharp
faceManager.subsystem.GetType().Name
```

will give you the name of the type.
