### ISSUE TITLE
Sloth is missing EyeSquintRight blendshape [Bug]

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#601]
Sloth is missing EyeSquintRight blendshape

**Comment by tdmowrer** [comment]
It does appear the artist who created this test asset omitted a deformer for the eye squint right. Is this really a bug (i.e., is the blendshape data for EyeSquintRight missing from the SDK)? This seems like a minor flaw a sample asset.

**Comment by yosun** [comment]
I think that it should be fixed in the samples, to fully visually demonstrate the ARKit face blendshapes. I am surprised it hasn't been fixed.

**Comment by mdurand42** [comment]
Tracking this issue on our backlog.

**Comment by yosun** [comment]
Are you accepting contributor pushes to fix this bug?
