### ISSUE TITLE
Reference to the plane hit by raycast

### ISSUE THREAD

**Issue by creativehims** [Unity-Technologies/arfoundation-samples#602]
How can we get a reference to the `ARPlane` object hit by raycast when using raycast manager?

**Comment by tdmowrer** [comment]
The `ARRaycastHit` contains a [trackableId](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARRaycastHit.html?q=arraycasthit#UnityEngine_XR_ARFoundation_ARRaycastHit_trackableId) property, which can be used to lookup the `ARPlane`.

Each [trackable manager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/trackable-managers.html) contains a [trackables](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackableManager-4.html#UnityEngine_XR_ARFoundation_ARTrackableManager_4_trackables) property which lets you [look up the trackable](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.TrackableCollection-1.html#UnityEngine_XR_ARFoundation_TrackableCollection_1_Item_UnityEngine_XR_ARSubsystems_TrackableId_) (an ARPlane in this case) by [TrackableId](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.0/api/UnityEngine.XR.ARSubsystems.TrackableId.html).

I believe you also wanted to know how to get the boundary points for the plane. You can do that with the [ARPlane.boundary](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARPlane.html#UnityEngine_XR_ARFoundation_ARPlane_boundary) property. There are [utility methods](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARPlaneMeshGenerators.html) for converting the boundary points into a [UnityEngine.Mesh](https://docs.unity3d.com/ScriptReference/Mesh.html).

**Comment by creativehims** [comment]
@tdmowrer  I managed to get the `ARPlane` with a call to `planeManager.GetPlane()` function passing in the `trackableId` as a parameter.

However, I'm getting an error `ArgumentNullException: Value cannot be null. Parameter name: mesh` when executing the following code to retrieve the boundary points for the plane. Can you please share an insight where I might be wrong? 

    ARPlane detectedPlane;
    Mesh planeMesh;

    void GetBoundaryPolygon()
    {
        List<Vector3> vertices = new List<Vector3>();

        if (ARPlaneMeshGenerators.GenerateMesh(planeMesh, new Pose(detectedPlane.center, Quaternion.identity), detectedPlane.boundary))
        {
            planeMesh.GetVertices(vertices);
        }
    }`

**Comment by creativehims** [comment]
I think I fixed it by initializing `planeMesh` to a new Mesh in Awake.

**Comment by creativehims** [comment]
The error is resolved, but the mesh that's generated is not correct. I tried spawning game objects on the vertices of the mesh, but they were floating in space irrespective of where the plane is found.

**Comment by tdmowrer** [comment]
What is your goal exactly? ARFoundation includes a component that [visualizes the mesh](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARPlaneMeshVisualizer.html) already, if that is your goal. You can also use it as a starting point to create your own if you want.

**Comment by creativehims** [comment]
I'm building a spawn mechanism where the items are spawned on the detected plane. I randomly select a vertex on the plane and then find a point between it and the center of the plane - which works as the position for the spawned item.

**Comment by tdmowrer** [comment]
In that case, you can randomly pick one of the 2d boundary vertices and then transform it into 3d:

```csharp
var boundary = plane.boundary;
var planeSpaceVertex = boundary[Random.Range(0, boundary.Length - 1)];
var worldSpaceVertex = plane.transform.TransformPoint(new Vector3(planeSpaceVertex.x, 0, planeSpaceVertex.y));
var worldSpaceCenter = plane.center; // already in world space
```

**Comment by creativehims** [comment]
Works like a charm! Thanks @tdmowrer. I think the mistake I made was in using the y value for the z component of the point and vice versa. That's why the point appeared above the plane.
