### ISSUE TITLE
Request New Feature : Multi-images tracking for a single target

### ISSUE THREAD

**Issue by X2Stone** [Unity-Technologies/arfoundation-samples#603]
Hi,
First of all, thanks for your amazing framework !
I would like to know if it would be possible to have an extension of the « image tracking » feature in ARFoundation : the ability to track multiple images for a single target, like a « box tracking », with its 6 faces images linked to the same AR object, and ARFoundation internally evaluate each frame the « best » image to use of the 6 available to accurately put the AR object in the right pose.
This feature would be really great, thanks you so much for having taking time to read me.

Nicolas

**Comment by tdmowrer** [comment]
> I would like to know if it would be possible to have an extension of the « image tracking » feature in ARFoundation : the ability to track multiple images for a single target

No, and this isn't a feature that we can add. ARFoundation relies on ARKit and ARCore, and those frameworks do not support this feature. You can create a feature request, e.g., with ARCore at https://github.com/google-ar/arcore-android-sdk

> ...like a « box tracking », with its 6 faces images linked to the same AR object, and ARFoundation internally evaluate each frame the « best » image to use of the 6 available to accurately put the AR object in the right pose.

That sounds more like object tracking, which is supported on ARKit. See the [ObjectTracking sample](https://github.com/Unity-Technologies/arfoundation-samples#objecttracking).

**Comment by X2Stone** [comment]
Ok, thanks for your quick answer.
So I stay with Vuforia which has more (and better) image tracking features.

**Comment by sharehuster** [comment]
hi @tdmowrer 
i'm new dev. i trying make a project  that can be track one  image  and show multi  ar-image corresponding.  this is done by button next and back  to change ar-image.
Ex. i have a pictute " car" . i want button left and right  ( back and next )   to change multi ar-image car 3d model 
Can you help me pls?
