### ISSUE TITLE
[Bug] Configuration properties now required for Multipeer in iOS 14+

### ISSUE THREAD

**Issue by robotconscience** [Unity-Technologies/arfoundation-samples#605]
The collaboration example and any apps that use the included Multipeer framework will crash unless ```NSLocalNetworkUsageDescription``` and ```NSBonjourServices``` keys are set in ```Info.plist```. 

This is using the official releases of iOS 14 and Xcode 12.

Steps to fix:
- Add ```NSLocalNetworkUsageDescription``` / "Privacy - Local Network Usage Description" key and text description to ```Info.plist```. Text entered will show in a pop-up after ARKit permission ask
- Add ```NSBonjourServices``` / "Bonjour services" key to ```Info.plist```
- Set the value of element 0 of key array to "_YOURSERVICE._tcp", i.e. "_ar-collab._tcp" for a service called "ar-collab" in Unity.
- Add a second element with the same pattern, but for UDP: "_YOURSERVICE._udp", i.e. "_ar-collab._udp"

[Apple documentation link](https://developer.apple.com/documentation/multipeerconnectivity) which includes key refs near top.

**Comment by tdmowrer** [comment]
Thanks for the details! On it.

**Comment by tdmowrer** [comment]
This should be fixed now.
