### ISSUE TITLE
Iphone 7+ and human body tracking

### ISSUE THREAD

**Issue by marad747** [Unity-Technologies/arfoundation-samples#607]
Does human body tracking will work at iphone 7+?

**Comment by mdurand42** [comment]
> Does human body tracking will work at iphone 7+?

Unfortunately not. Human body tracking requires an iOS device with an [A12 processor or later](https://developer.apple.com/documentation/arkit/capturing_body_motion_in_3d). The iPhone 7+ has an A10 processor.

**Comment by sam598** [comment]
On devices without native human body tracking, you could look into running something like posenet or blazepose on top of the AR camera image: https://github.com/asus4/tf-lite-unity-sample
