### ISSUE TITLE
Scanning and Detecting 3D Objects seems to be not supported

### ISSUE THREAD

**Issue by Leiong** [Unity-Technologies/arfoundation-samples#61]
Scanning and Detecting 3D Objects seems to be not supported

**Comment by Saicopate** [comment]
It is not supported by google's ARCore neither.. only ARkit supports this.

**Comment by tdmowrer** [comment]
It is true that only ARKit has support for this, but we are adding APIs to expose it in ARFoundation soon.

**Comment by HappySwede** [comment]
Any ETA on the object scanning for ARFoundation and ARCore?

**Comment by tdmowrer** [comment]
Object tracking support for ARKit was added in ARFoundation 2.2. ARCore does not support this yet. If/when it does, we will update ARFoundation.
