### ISSUE TITLE
Disabling planes should be collider + renderer and not gameobject [Bug]

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#610]
**Describe the bug**
For performance issues, 
            `plane.gameObject.SetActive(value);`
should be replaced with 
```
plane.gameObject.GetComponent<Renderer>().enabled = value; 
plane.gameObject.GetComponent<Collider>().enabled = value; 
```

https://github.com/Unity-Technologies/arfoundation-samples/blob/2.1/Assets/Scripts/PlaneDetectionController.cs#L57

**To Reproduce**
See https://github.com/Unity-Technologies/arfoundation-samples/blob/2.1/Assets/Scripts/PlaneDetectionController.cs#L57

**Comment by tdmowrer** [comment]
This particular sample exists because someone specifically asked how to do this. This is just sample code; you can modify it as you see fit in your own usage.
