### ISSUE TITLE
[Bug] UX Samples do not scale well on different portrait resolutions

### ISSUE THREAD

**Issue by ROBYER1** [Unity-Technologies/arfoundation-samples#611]
Please refer to this issue on the arfoundation-demos repository where this was fixed, can this be fixed here too please?
https://github.com/Unity-Technologies/arfoundation-demos/issues/33#issuecomment-700384242

Specifically this push
https://github.com/Unity-Technologies/arfoundation-demos/commit/9bedd2b32b5bb09878344451d52e4498852d87ef

Original bug notes from ARfoundation-demos:
Try 800 x 480 in Game view or 1280 x 720 and the bottom anchored overlay is off screen, also the Top of screen content is then simply huge and overlapping the bottom anchored content.

Iphone 7 is 1334 x 750 Pixels.

I am shocked this was released without a simple test of the resolutions in the Game view you can choose by default when making an IOS or Android project in Unity with ARFoundation.

The first device I tested on was an Iphone 7 which experienced these issues unfortunately this solution does not scale well.

Setting the Canvas Scaler to scale with screen size just means that the bottom anchored popups are off the screen always but scaling with it.

Not impressed with the scaling, however the icons are very nice and the presentation is great when it is on the right size phone screen.

**Comment by tdmowrer** [comment]
This repo is focused on providing examples of how to use the ARFoundation API. While the UX sample is more of a use case sample, it was created here before the [ARFoundation Demos](https://github.com/Unity-Technologies/arfoundation-demos) repo existed. As it seems more appropriate for that repo, and its presence in this one is redundant, so I've just removed it.

I have left [a note in the README](https://github.com/Unity-Technologies/arfoundation-samples#ux) that refers readers to the UX sample in the ARFoundation Demos repository.
