### ISSUE TITLE
How to make human foot trackable?

### ISSUE THREAD

**Issue by lvvova1** [Unity-Technologies/arfoundation-samples#612]
How to make a human leg trackable?

Like here:
https://www.youtube.com/watch?v=kcsCf4SlFLs

I would appreciate any tutorial/guidance/tips on how to make leg trackable in ar foundation.

**Comment by tdmowrer** [comment]
It looks like the app in the video uses a custom machine learning algorithm. ARFoundation on iOS supports [full body tracking](https://github.com/Unity-Technologies/arfoundation-samples#humanbodytracking3d) and human [segmentation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html?q=segmentation#UnityEngine_XR_ARFoundation_AROcclusionManager_requestedHumanStencilMode) & [occlusion](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html?q=segmentation#UnityEngine_XR_ARFoundation_AROcclusionManager_requestedHumanDepthMode).

**Comment by sam598** [comment]
On devices without native human segmentation, you could look into running something like tensorflow lite on top of the AR camera image: https://github.com/asus4/tf-lite-unity-sample

**Comment by dhaminitinAltran** [comment]
Hi, would it be possible to use Barracuda and Arcore? for tracking the feet of a user.
