### ISSUE TITLE
ARFoundation 4.1.0 Clarification on resetting an ARSession

### ISSUE THREAD

**Issue by AdamBursill-SV** [Unity-Technologies/arfoundation-samples#613]
Hi, 
Could I get some clarification on resetting an ARSession? (Completly destroying it and starting fresh as if I have just started the app)

I'm using ARFoundation 4.1.0-preview.9 and the documentation [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARSession.html?q=ARSession#UnityEngine_XR_ARFoundation_ARSession_Reset) states "Resets the AR Session. This destroys the current session, including all trackables, and then establishes a new session." but the migration guide [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/migration-guide-3.html) says "If you want to completely destroy the session, you need to destroy the subsystem. This means calling Deinitialize on an XRLoader from XR Plug-in Management." 

So does ARSession.Reset do that automatically or is the documentation wrong and should ARSession.Reset be removed?

**Comment by tdmowrer** [comment]
Well, that is embarrassingly out of date. Thanks for pointing that out.

"Reset" does not destroy the current session; it just clears all the existing trackables and resets the tracking. The language in the migration guide is correct.

> should ARSession.Reset be removed?

It is usually much faster to reset the session than completely destroy and recreate it. ARKit (Apple's API) has specific [flags](https://developer.apple.com/documentation/arkit/arsessionrunoptions/arsessionrunoptionremoveexistinganchors?language=objc) for this, for example.

**Comment by AdamBursill-SV** [comment]
ok good to know thanks, 

does the Simple AR sample scene need to be updated as well as the Reload and Reset options do the same thing now?

**Comment by tdmowrer** [comment]
We should remove Reload as it no longer does what it was intended to demonstrate. However, to be clear Reload and Reset are different. Reset is a method on the ARSession. "Reload" isn't a method -- the button in that sample removes the ARSession GameObject and recreates it. This will effectively pause and then restart the same session.

**Comment by AdamBursill-SV** [comment]
ok great thanks for clarifying
