### ISSUE TITLE
Error in iOS app when reload an AR scene

### ISSUE THREAD

**Issue by asevillanom** [Unity-Technologies/arfoundation-samples#614]
First time I load a Image tracking AR scene everything works fine but when I exit the ar scene, go to the menu scene (no AR) and load the AR scene a second time a black screen appears. How can I do to solve it?

AR Foundation 4.0.8 & ARkit 4.0.8
Iphone 8 (iOS 13.3)
Unity 2019.4 LTS

This is the error that Xcode shows:

NotSupportedException: Update requires a configuration.
  at UnityEngine.XR.ARKit.ARKitSessionSubsystem+ARKitProvider.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.ARSubsystems.XRSessionSubsystem.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.ARFoundation.ARSession.Update () [0x00000] in <00000000000000000000000000000000>:0

**Comment by mdurand42** [comment]
> First time I load a Image tracking AR scene everything works fine but when I exit the ar scene, go to the menu scene (no AR) and load the AR scene a second time a black screen appears. How can I do to solve it?
> 
> AR Foundation 4.0.8 & ARkit 4.0.8
> Iphone 8 (iOS 13.3)
> Unity 2019.4 LTS
> 
> This is the error that Xcode shows:
> 
> NotSupportedException: Update requires a configuration.
> at UnityEngine.XR.ARKit.ARKitSessionSubsystem+ARKitProvider.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0
> at UnityEngine.XR.ARSubsystems.XRSessionSubsystem.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0
> at UnityEngine.XR.ARFoundation.ARSession.Update () [0x00000] in <00000000000000000000000000000000>:0

We believe that this may the result of mixing package versions in an incompatible way. Could you please paste in your project manifest.json file under the Packages folder?

**Comment by asevillanom** [comment]
This is my manifest.json file:

"dependencies": {
    "com.kyrylokuzyk.arfoundationremote": "https://kuzykkirill:gXfNFPSZ1sfx3PsiMxPz@gitlab.com/kuzykkirill/arfoundationremote.git#25f50840fc84a2b2e630cf34f4b421b88b548f67",
    "com.ptc.vuforia.engine": "8.5.9",
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.ads": "3.4.9",
    "com.unity.analytics": "3.3.5",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.ext.nunit": "1.0.0",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.2.1",
    "com.unity.multiplayer-hlapi": "1.0.6",
    "com.unity.purchasing": "2.1.0",
    "com.unity.test-framework": "1.1.16",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.2.6",
    "com.unity.ugui": "1.0.0",
    "com.unity.xr.arfoundation": "4.1.0-preview.9",
    "com.unity.xr.arkit": "4.1.0-preview.9",
    "com.unity.xr.arkit-face-tracking": "4.1.0-preview.9",
    "com.unity.xr.interaction.toolkit": "0.9.4-preview",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}


Anyway, I think I just fixed the problem. I was using "SceneManager.LoadScene (scene, LoadSceneMode.Single);
LoaderUtility.Deinitialize ();" when I left the AR scene but I was not adding LoaderUtility.Initialize (); when loading again. Now it seems to work fine.
