### ISSUE TITLE
[Bug] ARKitBlendshapeCoefficient.coefficient cannot be assigned to, it is read only

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#617]
**Describe the bug**
ARKitBlendshapeCoefficient.coefficient cannot be assigned to, it is read only

**To Reproduce**
Why are the coefficients read-only? 
Why is it a sealed assembly that can't be modified, so that users can just add their own setters? 
This struct ought to be write-able? 

**Expected behavior**
.coefficient should allow assignment

**Actual behavior**
above error shows up when trying to assign a value to .coefficient
also for .blendShapeLocation

**Comment by tdmowrer** [comment]
Sorry, I don't think I grok the need for this to be writable. The coefficients are provided to you by ARKit. Modifying them would have no effect.

What are you trying to achieve?
