### ISSUE TITLE
How to set the WorldAlignment (e.g. gravityAndHeading)

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#618]
I want to set the world alignment to **gravityAndHeading**, but I don't know how to set it.

**Comment by tdmowrer** [comment]
We do not expose this setting in ARFoundation. However, you can [get the ARSession pointer](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/extensions.html), modify its [configuration](https://developer.apple.com/documentation/arkit/arconfiguration/2923550-worldalignment?language=objc), and call [runWithConfiguration](https://developer.apple.com/documentation/arkit/arsession/2865608-runwithconfiguration) from Objective-C.

**Comment by weacw** [comment]
Thank you for your reply.
Do you have more information or smaple  about ARSession pointer？

**Comment by tdmowrer** [comment]
This is ARKit's documentation for the ARSession: https://developer.apple.com/documentation/arkit/arsession?language=objc

**Comment by sam598** [comment]
@weacw I had tried to make a similar configuration change here: https://github.com/Unity-Technologies/arfoundation-samples/issues/517

It should be able to be modified for this use.

However it would be great for this to be officially supported, especially since ARKit and ARCore both support GPS anchors.

**Comment by tdmowrer** [comment]
We'll be adding this to the next 4.1 release.

**Comment by tdmowrer** [comment]
Support for this was added in [4.1.0-preview.11](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.1/api/UnityEngine.XR.ARKit.ARKitSessionSubsystem.html#UnityEngine_XR_ARKit_ARKitSessionSubsystem_currentWorldAlignment)
