### ISSUE TITLE
Specifying viewport ratio

### ISSUE THREAD

**Issue by vlobanov** [Unity-Technologies/arfoundation-samples#620]
I would like to know how to show full image coming from camera, without cropping it on the sides
E.g. when iPhone is in portrait mode and camera image is 1440x1920, instead of 1440 pixels we only show 886.

For my app I need to show whole image with horizontal black bars.
I researched ARFoundation's source code and found that `Screen.width`/`Screen.height` is passed in `ARKitCameraSubsystem` and in `ARSession`, however I'm pretty sure that underlying ARKit native implementation doesn't use them. 
I assume it's possible since [displayTransformForOrientation:viewportSize](https://developer.apple.com/documentation/arkit/arframe/2923543-displaytransformfororientation?language=objc) accepts viewport size

Is there any way around this? I know I could implement custom background renderer and update projection matrix, but would really love more elegant solution

Terrific work btw, keep it up!

**Comment by tdmowrer** [comment]
With ARFoundation, you have access to the raw [texture(s)](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_textures) and a ["display matrix"](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_displayMatrix) which is applied in a shader to render the textures on the screen. On ARKit, that display matrix is generated from `displayTransformForOrientation:viewportSize:`.

If you want to render the textures differently, then you need to use a different shader. You can provide a custom material to the [ARCameraBackground](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARCameraBackground.html#UnityEngine_XR_ARFoundation_ARCameraBackground_customMaterial):

![Screen Shot 2020-10-07 at 8 46 57 AM](https://user-images.githubusercontent.com/4934281/95354775-af4c2480-0879-11eb-8d78-86ce83e5dc3d.png)

Also, you can get the [raw camera image pixels](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/cpu-camera-image.html), which may be useful to you, depending on what you are trying to achieve.

**Comment by vlobanov** [comment]
But is there a way to change programmatically what viewportSize is passed to  [displayTransformForOrientation:viewportSize](https://developer.apple.com/documentation/arkit/arframe/2923543-displaytransformfororientation?language=objc) ?

**Comment by tdmowrer** [comment]
No, but you could call it yourself with a bit of Objective-C code.

**Comment by vlobanov** [comment]
Ok thanks, gotcha

**Comment by daverin** [comment]
Hi @tdmowrer 

We have implemented this as per your advice. Now we're struggling with the mapping between swift and unity for the projection and display matrices. 

If you could post the conversion thats used in the swift code of ARKit/ARFoundation this would be most helpful.
