### ISSUE TITLE
Request for Wide Angle Camera Support

### ISSUE THREAD

**Issue by YoHana19** [Unity-Technologies/arfoundation-samples#622]
I currently develop AR app that uses AR segmentation feature in landscape orientation with iPhone 11 pro.
And I'd like to capture a person's whole body in landscape frame. To do that the person needs to be about 3 m away from the iPhone but the problem is the segmentation gets more unstable when a person is far.

I found arfoundation camera seems to use 1x fov of built in camera app in a iPhone.
There is 0.5x fov option in the camera app, so What I request is to be able to use 0.5x fov camera in arfoundation.

**Comment by tdmowrer** [comment]
On iOS, ARFoundation uses ARKit, and on the iPhone 11, ARKit _does_ use the wide angle lens for AR calculations. However, the pass through video image you see is not from the wide angle lens.

I am not aware of any option to change the fov in the [ARKit framework](https://developer.apple.com/documentation/arkit) as you have described. Please let me know if I am wrong.

**Comment by YoHana19** [comment]
Thank u for immediate reply.
I understood it's matter of ARKit and nothing to do for ARFoundation for now.
I just hope Apple will offer the option to change fov.
Thank u anyway!
