### ISSUE TITLE
Not Install Google Play Services for AR Problem

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#624]
Hello there
If we do not install **Google Play Services for AR** ARFoundation will automatically download **Google Play Services for AR**,
But we are from China and we can not access Google Play, so how do we customize the download URL of **AR Google Play Services**?

**Comment by tdmowrer** [comment]
The URL is not customizable; it comes directly from the ARCore API (not ARFoundation). See https://developers.google.com/ar/discover/supported-devices#android_china for more information.

**Comment by fredsa** [comment]
`Session.RequestApkInstallation()` will ensure that:
1. **_Google Play Services for AR_ (ARCore) is installed an up to date**.
   If not, it will launch `market://details?id=com.google.ar.core`,
   which should launch the appropriate store depending on device.
2. **ARCore device profile data is up to date**.

**Comment by weacw** [comment]
> `Session.RequestApkInstallation()` will ensure that:
> 
> 1. **_Google Play Services for AR_ (ARCore) is installed an up to date**.
>    If not, it will launch `market://details?id=com.google.ar.core`,
>    which should launch the appropriate store depending on device.
> 2. **ARCore device profile data is up to date**.
> 
> Documentation: https://developers.google.com/ar/develop/unity-arf/enable-arcore

Thank you for your reply.
Yes it’s work. But we in China can not access the google play and can not download Google play services for AR, so we want to customize the ‘market://details?id=com.google.ar.core’ to our server’s url.

**Comment by fredsa** [comment]
`market://details?id=com.google.ar.core` should launch whatever app store is being used on the device. This URL is **not** specific to the Google Play Store.

The app stores in the China that should be able to handle the `market://details?id=com.google.ar.core` URL already are listed here: https://developers.google.com/ar/discover/supported-devices#android_china

**Comment by weacw** [comment]
Thank you fredas
