### ISSUE TITLE
ARKitCoachingOverlay delegate response for goal status?

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#625]
How do I get a return when a particular goal, such as tracking or plane, has been met for ARKitCoachingOverlay?

**Comment by tdmowrer** [comment]
We do not expose the relevant callbacks, but I will add this to a future version of 4.1.

**Comment by yosun** [comment]
Without a callback, it seems that ARKitCoachingOverlay isn't exactly functional? It never self-disables even after I've tracked the entire room...

**Comment by tdmowrer** [comment]
> It never self-disables even after I've tracked the entire room...

That should not happen (and it works as expected for me). It depends on the goal and your enabled features, though. For instance, if the goal is vertical plane detection, and you haven't enabled vertical plane detection, then it can never achieve the goal. What goal have you set? Does the [coaching overlay sample](https://github.com/Unity-Technologies/arfoundation-samples#arkitcoachingoverlay) work for you?

**Comment by tdmowrer** [comment]
In the next release of 4.1, we are adding callbacks for the coaching overlay's willActivate and didDeactivate.

**Comment by tdmowrer** [comment]
Support for the willActivate and didDeactivate callbacks was added in [4.1.0-preview.11](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.1/changelog/CHANGELOG.html#new)
