### ISSUE TITLE
[Bug] [iOS] ARFoundation ImageTracking on iOS hangs with invalid image target and there is no API call to ARKit native validate method

### ISSUE THREAD

**Issue by tarunpondicherry** [Unity-Technologies/arfoundation-samples#626]
**Unity bug report case number**
1285202
http://fogbugz.unity3d.com/default.asp?1285202_88j47iof4hsc9qib

**Describe the bug**
ARFoundation ImageTracking on iOS hangs with invalid image target

In applications where users can add image targets themselves (for example, take a photo of a target), there is no way to validate whether the image target will be valid on iOS. ARKit natively has a validate method that ARFoundation does not expose: https://developer.apple.com/documentation/arkit/arreferenceimage/3194594-validate

ARFoundation should provide a way to test for validity. For example, it can expose validate so it can be called before adding user defined targets or it can call validate internally when new targets are added and throw an exception when appropriate.

**To Reproduce**
The example AR Foundation project was modified to add an invalid target to the reference library.
1. Build to iOS
2. When run on iOS (click "Image Tracking")
3. ARSession will continuously throw exceptions and hang.

**Expected behavior**
Exception when image target is added or ability to call native ARKit validate for image target on iOS.

**Actual behavior**
ARSession will continuously throw exceptions and hang.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14
 - Unity version: 2020.1.9
 - ARFoundation version: 4.1

**iOS Error Log**
2020-10-14 17:53:17.455336-0700 samples[2845:1335027] UnityARKit: ARSession failed with error "Invalid reference image.". Attempting reset
2020-10-14 17:53:17.469399-0700 samples[2845:1334776] UnityARKit: Updating ARSession configuration with <ARWorldTrackingConfiguration: 0x281a61340 worldAlignment=Gravity lightEstimation=Disabled frameSemantics=None videoFormat=<ARVideoFormat: 0x280e1d8b0 imageResolution=(1920, 1440) framesPerSecond=(60)> autoFocus=Enabled environmentTexturing=None wantsHDREnvironmentTextures=Enabled planeDetection=None collaboration=Disabled userFaceTracking=Disabled sceneReconstruction=None detectionImages=[<ARReferenceImage: 0x28096d8c0 name="BadCode_F04B88C4-AA1E-0E48-A2B6-98CA9C8FA30C" physicalSize=(0.100, 0.100)>, <ARReferenceImage: 0x28096daa0 name="Rafflesia_E50B34F0-0E71-FF49-BC70-45F1315B9202" physicalSize=(0.254, 0.169)>, <ARReferenceImage: 0x28096d9e0 name="QRCode_2852E7AA-7319-C04D-B7A2-53D1566EE402" physicalSize=(0.050, 0.050)>, <ARReferenceImage: 0x28095d020 name="Logo_EDEE292C-5CD9-1141-B724-80F9FF10CE86" physicalSize=(0.100, 0.100)>] maximumNumberOfTrackedImages=4 automaticImageScaleEstimation=Disabled>

**Comment by tdmowrer** [comment]
Thanks for the report.

> ARSession will continuously throw exceptions and hang.

This is not an exception. The message

```
UnityARKit: ARSession failed with error "Invalid reference image.". Attempting reset
```

Is logic we have to handle cases where ARKit can spuriously fail when switching configuration types (e.g., from a user-facing to world-facing mode). However, as you've pointed out, there are other cases, such as an invalid image target, that can cause the session to fail.

In the next release of 4.1, we've added two features to mitigate this:
* The "reset" logic has been moved to C#. The default behavior is the same, but you can override this method and take different actions depending on the error.
* Adding images to mutable reference libraries now includes validation, so the image won't be added to the library unless it is valid. You also get back an object that you can use to determine the success or failure of the asynchronous add job.

**Comment by tarunpondicherry** [comment]
Thanks for the quick response. If there's an early build with these changes, we'd be happy to try it out and provide feedback.

**Comment by tdmowrer** [comment]
It's out now :) https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/changelog/CHANGELOG.html#new

**Comment by tarunpondicherry** [comment]
Thanks @tdmowrer , this solves one of our use cases.

We'd also like to be able to test an image and notify the user independent of adding it to the reference library (for example if it's the first step in a flow for creating something to overlay). Do you have a recommended way to do that? Is the only way to try to add it and detect status?

**Comment by tdmowrer** [comment]
Since it takes about the same amount of time to add a new reference image as it does to validate it, we decided to combine them into a single method.

> We'd also like to be able to test an image and notify the user independent of adding it to the reference library (for example if it's the first step in a flow for creating something to overlay)

We don't have a way to do that, no, but in this suggested flow, wouldn't the next step be to add the image? In what case would you want to be able to say "yes, this image is valid, but don't add it yet"?
