### ISSUE TITLE
Is there a configuration setting somewhere for marking ARFoundation as not required in iOS?

### ISSUE THREAD

**Issue by mgrider** [Unity-Technologies/arfoundation-samples#628]
I have a board game app that uses ARFoundation that I've put up on TestFlight, and everything is working more or less well, but I've heard from numerous folks with older devices that they cannot install the app. I believe it's because ARKit is somehow marked as required.

Does anyone know if this is a setting in xcode or in Unity somewhere?

**Comment by tdmowrer** [comment]
Yes, there is such a setting. Edit > Project Settings > XR Plug-in Management > ARKit > Requirement:

<img width="907" alt="Screen Shot 2020-10-15 at 9 17 45 AM" src="https://user-images.githubusercontent.com/4934281/96157630-6292ca00-0ec7-11eb-95b4-bd60d95f91f2.png">

See also ["Build settings"](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.0/manual/index.html#build-settings) in the documentation.

**Comment by mgrider** [comment]
I forgot to check back to say that this was definitely how to fix the issue. Thanks so much for your speedy reply!!!
