### ISSUE TITLE
Is it possible to get the position of human detected and also occlude them (perhaps different frames)

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#629]
How do I get the (world space) positions of humans detected and also have them occlude 3D objects (and particles) augmented? 

It seems that occlusion does not work with human segmentation 3D (?), so this can happen in separate frames, ideally it would be possible to switch between them fast.

**Comment by tdmowrer** [comment]
This is a current limitation of ARKit. I would also not recommend toggling occlusion and human body tracking rapidly, as this requires swapping configurations and is not fast (you will notice a momentary hitch as the session adapts to the new configuration).

**Comment by yosun** [comment]
Is it possible to raycast the stencil - say "bottom center" - to get a world position?

**Comment by yosun** [comment]
Yes, perhaps: 
- Identify each stencil blob contiguous entity.
- Identify bottom center point (assuming this is the near the foot of the real person) 
- Project this 2D point to 3D world point
