### ISSUE TITLE
Can occlusion settings be set at runtime? Such as prefer human vs environment occlusion?

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#630]
How do I change occlusion settings be set at runtime? Such as prefer human vs environment occlusion? Or, turn off occlusion all-together to enable human body 3d tracking, quickly?

**Comment by tdmowrer** [comment]
> How do I change occlusion settings be set at runtime? Such as prefer human vs environment occlusion?

You can set any of the AROcclusionManager's properties at runtime. See https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html#properties

> Or, turn off occlusion all-together

Disable the AROcclusionManager

> to enable human body 3d tracking

Enable the ARHumanBodyManager

**Comment by yosun** [comment]
Is this only supported with a certain version of ARFoundation? I haven't been able to "toggle" from body 3d to occlusion in the same session without restarting the app.

**Comment by tdmowrer** [comment]
Also, in a development build, there is debug output that tells you what features were requested, and which could not be satisfied. If you turn on a feature like human body tracking, and it does not appear to work, the debug output should provide more information.
