### ISSUE TITLE
Why does ARMeshManager have to be a child of ARSession while ARPlaneManager doesn't (or seems to require top level)? 

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#632]
How do I...
Why does ARMeshManager have to be a child of ARSession while ARPlaneManager doesn't (or seems to require top level)?

**Comment by tdmowrer** [comment]
Unlike the other managers, the ARMeshManager requires an additional transform separate from the session origin that determines where meshing will take place. This is not relevant on ARKit (that is, meshing is not restricted to a particular area), but HoloLens and Magic Leap require you to define an area where meshing will occur. If you select the ARMeshManager in the Editor, you should see a green box gizmo in the Scene View that indicates this.
