### ISSUE TITLE
How to use rear camera (back camera) to detect face with AR Face (Android)

### ISSUE THREAD

**Issue by hiangsui** [Unity-Technologies/arfoundation-samples#633]
on front camera is working fine but on back camera is nothing happened. so i'm not sure about rear camera can working with face tracking or not ?.

thank you

**Comment by tdmowrer** [comment]
This is not supported by ARCore (Google's AR SDK for Android).

It is possible to see what features are simultaneously supported at runtime. See [this bit](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/migration-guide-3.html#configuration-chooser) from the migration guide and [this API](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.0/api/UnityEngine.XR.ARSubsystems.XRSessionSubsystem.html#UnityEngine_XR_ARSubsystems_XRSessionSubsystem_GetConfigurationDescriptors_Unity_Collections_Allocator_) to get a list of all configuration descriptors (which enumerate the sets of features which work together).

In development builds, there is logcat output that will tell you what features were requested, and which could not be satisfied to help you debug why a particular feature is not enabled. You can filter logcat output to just messages from Unity:
```
adb logcat -s Unity
```

Or use the "Android Logcat" package available from the package manager.

**Comment by hiangsui** [comment]
> This is not supported by ARCore (Google's AR SDK for Android).
> 
> It is possible to see what features are simultaneously supported at runtime. See [this bit](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/migration-guide-3.html#configuration-chooser) from the migration guide and [this API](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.0/api/UnityEngine.XR.ARSubsystems.XRSessionSubsystem.html#UnityEngine_XR_ARSubsystems_XRSessionSubsystem_GetConfigurationDescriptors_Unity_Collections_Allocator_) to get a list of all configuration descriptors (which enumerate the sets of features which work together).
> 
> In development builds, there is logcat output that will tell you what features were requested, and which could not be satisfied to help you debug why a particular feature is not enabled. You can filter logcat output to just messages from Unity:
> 
> ```
> adb logcat -s Unity
> ```
> 
> Or use the "Android Logcat" package available from the package manager.

Thank you for confirm. actually i know it. but i need someone confirm for me because my boss need this option haha
