### ISSUE TITLE
[Bug] Memory leak when accessing cpu image on iOS

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#634]
**Describe the bug**
Memory leak when accessing cpu image.Here is our code to accessing cpu image:

**Code**
```C#
private void GetImageAsync(ARCameraFrameEventArgs _eventArgs)
{
    if (!cameraManager.TryAcquireLatestCpuImage(out XRCpuImage tmp_Image))
    {
        return;
    }

    tmp_Image.ConvertAsync(new XRCpuImage.ConversionParams
    {
        inputRect = new RectInt(0, 0, tmp_Image.width, tmp_Image.height),
        outputDimensions = new Vector2Int(tmp_Image.width / 2, tmp_Image.height / 2),
        outputFormat = TextureFormat.RGB24,
        transformation = XRCpuImage.Transformation.MirrorY
    }, ProcessImage);
    tmp_Image.Dispose();
}

private void ProcessImage(XRCpuImage.AsyncConversionStatus _status,
    XRCpuImage.ConversionParams _conversionParams, NativeArray<byte> _data)
{
    if (_status != XRCpuImage.AsyncConversionStatus.Ready)
    {
        Debug.LogErrorFormat("Async request failed with status {0}", _status);
        return;
    }


    if (CameraTexture == null)
    {
        CameraTexture = new Texture2D(_conversionParams.outputDimensions.x,
            _conversionParams.outputDimensions.y, _conversionParams.outputFormat, false);
    }

    CameraTexture.LoadRawTextureData(data: _data);
    CameraTexture.Apply();
}
```
**Devices**
|Device|OS|Unity version| ARF version|Leak|
|---|---|---|---|---|
|iPhone 6s|13.6.1|2020.1.6f1|4.0.8|YES|
|iPhone 11|14.0.1|2020.1.6f1|4.0.8|YES|

**I want**
Accessing the cpu image(Every Frame) then convert it to base64 send to our server and prediction it.

**Comment by tdmowrer** [comment]
The async conversion can take more than a single frame to process, depending on your conversion parameters. If you are calling this every frame, you are queuing up work faster than it can be processed, and eventually you run out of memory. You can mitigate this in two ways:

1. Do not start processing a CPU image until the previous one is finished.
2. The majority of the time is spent converting from the video format to RGB. Do you require a full RGB image? If not, conversion to one of the grayscale formats is almost free.

**Comment by weacw** [comment]
Is the grayscale image like this?

![image](https://user-images.githubusercontent.com/11573490/96668636-30cda780-138e-11eb-899c-beb14f0791ff.png)

**Comment by tdmowrer** [comment]
I'm not sure what you are asking. That is an example of a grayscale image, yes, but I don't know what your use case is.

> **I want**
> Accessing the cpu image(Every Frame) then convert it to base64 send to our server and prediction it.

What do you want to do with the resulting image. Can you elaborate on "prediction"?

**Comment by weacw** [comment]
I create a opencv feature macthing serving to finding the matching image.
Just like Vuforia cloud recognition. So we need access every frame.

**Client:**
1. accesing the cpu image(RGB24)
2. convert cpu image to base64 
3. send the base64 image data to server

**Server(Python):**

1. receive tcp data and convert to opencv image(np array)
2. convert the image to gray scale
3. k-NN matching
4. send matching prediction results to the client

**Comment by tdmowrer** [comment]
If your server only requires a grayscale image, then you are spending unnecessary time converting it to RGB24, unnecessary bandwidth transmitting it to your server, and unnecessary compute on the server to convert it to grayscale. One of the channels in the video data is just the luminosity channel, so there is no (or very little) conversion necessary which makes it extremely fast.

> TextureFormat.Alpha8 image save on server is black image.

How do you know it is black? Are all the bytes in the `_data` array 0?

Unity doesn't have a "grayscale" [TextureFormat](https://docs.unity3d.com/ScriptReferenceTextureFormat.html) so we use Alpha8 or R8 to indicate a single channel, i.e. "grayscale", image. In the code snippet you posted, you are creating a Texture2D (I assume as a debug preview), which may display differently than you are expecting. Try `TextureFormat.R8` if you are trying to visualize it for debug purposes.

**Comment by weacw** [comment]
Thank you for your reply.
R8 it's working and not out of memory .
Thank you very much!

**Comment by tdmowrer** [comment]
The XRCpuImage conversion produces an array of bytes, one byte per pixel, representing a grayscale image. How you choose to interpret that data is up to you.

That said, my guess is that your server assumes it is receiving an RGBA image and still needs to convert it to grayscale.

> The server will automatically grayscale

If you mean it is performing some conversion, what does it think it is converting from? The R8 you posted, for instance, looks like it is the result of averaging a red channel with nonexistent/zero green and blue values. This would also explain why the Alpha8 comes out black.
