### ISSUE TITLE
ARKit Wide angle lens camera texture for CPU processing

### ISSUE THREAD

**Issue by trandzik** [Unity-Technologies/arfoundation-samples#636]
Hello,
I would like to utilize wide angle camera data for AR application. I know ARKit currently doesn't support using this camera for AR (please correct me if I am wrong). This is kind of unfortunate as having wide angle lens AR support could open up a lot of possibilities for applications. Nevertheless I would like to ask whether it would be somehow possible to obtain just raw RGB data from wide angle camera? It would be great if one could get this texture to CPU for various computer vision processing. Is there a possibility of implementing such feature in the future or is it rather unlikely? Thanks.

**Comment by tdmowrer** [comment]
ARKit does use the wide angle lens to perform its AR computations, but it does not provide access to the raw video texture from the wide angle lens.

**Comment by trandzik** [comment]
I see, thanks for information. I guess ARKit would be the only way to access this camera texture and therefore without Apple support there is essentially no other way to access it inside of Unity, right?

**Comment by tdmowrer** [comment]
> I guess ARKit would be the only way to access this camera texture

If you aren't using AR, then you can use Unity's [WebCamTexture API](https://docs.unity3d.com/ScriptReference/WebCamTexture.html) to access different camera textures (e.g., front vs back). You may be able to access the wide angle lens this way.

However, when AR is enabled, ARKit gets an exclusive lock on the camera, so I don't think you would be able to access the wide angle camera feed at the same time.

**Comment by trandzik** [comment]
Thanks for information.

**Comment by VimalMollyn** [comment]
Has there been any new solutions to this problem? Does apple finally allow us to get the Raw Wide angle feed?
