### ISSUE TITLE
Why AR Camera is not at 0,0,0 position and rotation?

### ISSUE THREAD

**Issue by ufktvfk** [Unity-Technologies/arfoundation-samples#64]
Hi,

I noticed that in SampleScene, AR Camera transform is not at 0,0,0. Is there a reason to that? I mean it should be at the origin right?
![arcamera](https://user-images.githubusercontent.com/23186662/48249820-3fbf2780-e40d-11e8-8ed9-4e744f1809dc.PNG)

Thanks

**Comment by tdmowrer** [comment]
This is intentional, to show that you can place the camera at any starting position that you like. Detected trackables (e.g., planes and point clouds) will be placed relative to this initial starting position and orientation, so you are free to place the camera anywhere you like in your scene.
