### ISSUE TITLE
How do you properly save ARAnchors or other GameObjects with ARWorldMap

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#640]
How do I properly save ARAnchors or other GameObjects with ARWorldMap?

I'd like to be able to load these ARAnchors or GameObjects in the same position and rotation that they were created in on the map that was saved. 

How does one find the absolute position and rotation relative to the ARWorldMap that was saved or loaded?

**Comment by tdmowrer** [comment]
An `ARWorldMap` is an ARKit proprietary format that stores information about the environment and all anchors (in ARKit terminology, "anchors" includes what we call trackables in ARFoundation, like planes). However, it does not store any Unity specific information, like GameObjects.

All anchors do have unique identifiers (in ARFoundation, this is the [`trackableId`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackable-2.html#UnityEngine_XR_ARFoundation_ARTrackable_2_trackableId)) that you can use to associate data saved in an ARWorldMap to something specific to your app, like content.

> How does one find the absolute position and rotation relative to the ARWorldMap that was saved or loaded?

What do you mean by an _absolution_ position _relative_ to something else?

**Comment by yosun** [comment]
How does one load the ARAnchors once it's saved using ARWorldMap?

**Comment by tdmowrer** [comment]
You can apply it to the session using [ApplyWorldMap](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.0/api/UnityEngine.XR.ARKit.ARKitSessionSubsystem.html#UnityEngine_XR_ARKit_ARKitSessionSubsystem_ApplyWorldMap_UnityEngine_XR_ARKit_ARWorldMap_)

**Comment by yosun** [comment]
I notice the example for the anchors and worldmap are separate. 

How does ApplyWorldMap trigger the ARAnchors to load, or does it work with the ARAnchorManager to load ARAnchors? What kind of scene setup is needed for ARAnchors to load from a saved WorldMap?

**Comment by tdmowrer** [comment]
An ARWorldMap stores every ARAnchor and ARTrackable. When you ApplyWorldMap, we load that serialized world map into ARKit, and it reports new anchors, planes, etc. just as if they had been detected normally. Note that it has to "localize" to the world map, i.e., decide how what it currently sees matches up with the world map, before it can do this.

**Comment by Gold1010** [comment]
It is not saving the anchors when saving worldmap.
I couldnt load the anchors when I load worldmap

**Comment by michelepanegrossi** [comment]
The anchors trackables are being saved, same as the planes. If you are referring to the gameobjects which are spawned when an anchor is created (as in the anchors example scene) you need to spawn those again yourself at the anchors locations. You can retrieve the transform of the anchors trackables and apply it to your spawned prefabs.

**Comment by lmaxsmith** [comment]
Isn't there a way to serialize a specific collection for sharing between devices?

**Comment by tdmowrer** [comment]
A specific collection of anchors? ARWorldMaps are all-or-nothing; you can't serialize just a subset.

ARKit also supports "collaborative sessions" (see [this sample](https://github.com/Unity-Technologies/arfoundation-samples#ar-collaboration-data)) which limits the sharing to just ARAnchors and ARParticipants (not other types of trackables, like planes).

What is your use case and why do you need to limit the sharing to a specific collection?

**Comment by lmaxsmith** [comment]
Oh does that allow asynchronous? Meaning non-concurrent sessions? 
I'm just doing very large spaces and getting extremely slow relocalization when the map gets large (multiple minutes). My best guess is a slow matching algorithm when the dataset gets too large. I have good logic to query specific anchors but in order to do that, I need them to be serialized in isolation (or small groups). And I need to save for later sessions.

**Comment by tdmowrer** [comment]
Collaborative sessions are intended for concurrent sessions.

Thanks for the extra details. I don't think there's a good solution to your problem. As far as I know, there's no such thing as a partial world map.
