### ISSUE TITLE
Anchor gameobject to the tracked image position

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#642]
I have created a custom TrackedImageManager in which I have a method for spawning a GameObject on top of the position of the tracked image, however, sometimes the position of the GameObject gets displaced to be way above the marker, as seen in [this screenshot](https://prnt.sc/v5f92v).

What I would like to know if there's a way to anchor the GameObject to the position of the trackedImage, or is there an alternate way to spawn it on top of it.

This is the method I use:

```cs
void OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs)
    {

        foreach (var trackedImage in eventArgs.updated)
        {
            OnImageUpdated(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
        }

        foreach (var trackedImage in eventArgs.added)
        {
            OnImageAdded(trackedImage.referenceImage.texture.name, trackedImage.name, trackedImage);
        }
    }

 public void OnImageAdded(string textureName, string name, ARTrackedImage m_ARTrackedImage)
    {
        for (int i = 0; i < Images.Count; i++)
        {
            if (Images[i].go == null && string.Equals(Images[i].target.name, textureName))
            {
                //Destroy the existing object
                if (curobject != null) { Destroy(curobject); }
                GameObject go = GameObject.Find(name);
                GameObject prefab = Resources.Load($"{PREFABFOLDER}{Images[i].path}") as GameObject;

                //Instantiate the prefab with the position of the trackedImage
                GameObject target = Instantiate(prefab, go.transform.position, Quaternion.identity);

                curobject = target;
                curobject.name = Images[i].target.name;
                Images[i].go = go;
                target.transform.SetParent(go.transform);
                target.transform.localPosition = Vector3.zero;
            }
        }
    }
```

**Comment by tdmowrer** [comment]
It sounds like your physical dimensions are off. See https://github.com/Unity-Technologies/arfoundation-samples/issues/568#issuecomment-693735111

**Comment by Sterling-Malory-Archer** [comment]
> It sounds like your physical dimensions are off. See [#568 (comment)](https://github.com/Unity-Technologies/arfoundation-samples/issues/568#issuecomment-693735111)

Hi Tim, thanks for replying, I do not have a specified size for the Android build. 

I looked over the comment you linked and I have a question as to where should I attach the script you provided there? I have these markers as just regular sprites in my project and they are linked to the ReferenceImageLibrary.

**Comment by tdmowrer** [comment]
How are you updating your content's transform after it is instantiated? That is, what does `OnImageUpdated` do?

**Comment by Sterling-Malory-Archer** [comment]
> How are you updating your content's transform after it is instantiated? That is, what does `OnImageUpdated` do?

Hi Tim, OnImageUpdated is almost the exact same method that I use to control when another image is scanned.

As for content transform, I do not update it, as the markers associated with the content are static.

**Comment by tdmowrer** [comment]
> As for content transform, I do not update it, as the markers associated with the content are static.

That sounds like you only set the transform once, on add. It's possible the initial position is not exact and will be refined over time. I suggest updating it in your `OnImageUpdated` method.

**Comment by Sterling-Malory-Archer** [comment]
> > As for content transform, I do not update it, as the markers associated with the content are static.
> 
> That sounds like you only set the transform once, on add. It's possible the initial position is not exact and will be refined over time. I suggest updating it in your `OnImageUpdated` method.

Hi Tim, thanks for the answer, I am providing my OnImageUpdated method as well. I would appreciate any help with how to approach updating the position of the content.
```cs

public void OnImageUpdated(string textureName, string name, ARTrackedImage m_ARTrackedImage)
    {
        for (int i = 0; i < Images.Count; i++)
        {
            if (m_ARTrackedImage.trackingState != TrackingState.None && !string.Equals(curobject.name, Images[i].target.name) && string.Equals(Images[i].target.name, textureName))
            {
                // Destroy the current AR animation
                if (curobject != null) { Destroy(curobject); }
                GameObject go = GameObject.Find(name);
                GameObject prefab = Resources.Load($"{PREFABFOLDER}{Images[i].path}") as GameObject;
                target = Instantiate(prefab, go.transform.position, Quaternion.identity);
                target.transform.rotation = go.transform.rotation;
                curobject = target;
                curobject.name = Images[i].target.name;

                Images[i].go = go;
                target.transform.SetParent(go.transform);
                target.transform.localPosition = Vector3.zero;
            }
        }
    }
```

**Comment by Sterling-Malory-Archer** [comment]
> > As for content transform, I do not update it, as the markers associated with the content are static.
> 
> That sounds like you only set the transform once, on add. It's possible the initial position is not exact and will be refined over time. I suggest updating it in your `OnImageUpdated` method.

Hi Tim, I went and re-did my code a bit, would this work better than what I previously showed?

Thank you in advance.

```cs
    [SerializeField]
    private GameObject[] placeablePrefabs;

    private Dictionary<string, GameObject> spawnedPrefabs = new Dictionary<string, GameObject>();
    public ARTrackedImageManager trackedImageManager;

  private void Awake()
    {
        foreach (GameObject prefab in placeablePrefabs)
        {
            GameObject newPrefab = Instantiate(prefab, Vector3.zero, Quaternion.identity);
            newPrefab.name = prefab.name;
            spawnedPrefabs.Add(prefab.name, newPrefab);
        }
    }

    private void OnEnable()
    {
        trackedImageManager.trackedImagesChanged += ImageChanged;
    }

    private void OnDisable()
    {
        trackedImageManager.trackedImagesChanged -= ImageChanged;
    }

    private void ImageChanged(ARTrackedImagesChangedEventArgs obj)
    {
        foreach (ARTrackedImage trackedImage in obj.added)
        {
            UpdateImage(trackedImage);
        }

        foreach (ARTrackedImage trackedImage in obj.updated)
        {
            UpdateImage(trackedImage);
        }

        foreach (ARTrackedImage trackedImage in obj.removed)
        {
            spawnedPrefabs[trackedImage.name].SetActive(false);
        }
    }

    private void UpdateImage(ARTrackedImage trackedImage)
    {
        string name = trackedImage.referenceImage.name;
        Vector3 position = trackedImage.transform.position;

        GameObject prefab = spawnedPrefabs[name];
        prefab.transform.position = position;
        prefab.SetActive(true);

        foreach (GameObject go in spawnedPrefabs.Values)
        {
            if (go.name != name)
            {
                go.SetActive(false);
            }
        }
    }
}

```

**Comment by tdmowrer** [comment]
Well, you tell me :) -- does it work better for you?

The only thing that seems odd is that you disable all other GameObjects every time anything is updated:

```csharp
        foreach (GameObject go in spawnedPrefabs.Values)
        {
            if (go.name != name)
            {
                go.SetActive(false);
            }
        }
```

Is that intended?

**Comment by Sterling-Malory-Archer** [comment]
Hi Tim, fair point, unfortunately, my phone died so I cannot test it now.

Yes I want there to be only one GameObject active that matches the name of the tracked image.
