### ISSUE TITLE
Persistent ARAnchor trackable ID? 

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#643]
How do I identify a particular ARAnchor trackable ID that has been saved, loading it after the session has ended? It seems trackableID is session dependent... Is there a universal ID?

**Comment by tdmowrer** [comment]
If you are talking specifically about anchors that are loaded as part of an ARWorldMap, the trackableId will be the same as it was when you saved the map. (This is currently the only way to persist anchors of any kind in ARFoundation, so I assume that is what you mean.)

**Comment by yosun** [comment]
In the documentation it says the trackableID is session dependent, so I assume it resets every session?

**Comment by tdmowrer** [comment]
In _general_ all we can guarantee is that trackableIds are unique to a session, but for ARWorldMaps _specifically_ the IDs do not change between sessions.

In the ARKit package, the trackableId is generated from the ARAnchor's [identifier property](https://developer.apple.com/documentation/arkit/aranchor/2867972-identifier?language=objc) in Objective-C. These do not change when loaded from a world map.
