### ISSUE TITLE
[Bug] Environment Depth does not work with ARFoundation 4.1.0-preview 11

### ISSUE THREAD

**Issue by re-cheid** [Unity-Technologies/arfoundation-samples#645]
**Describe the bug**
Running the DepthImages Scene on iPad Pro 2020 states that environment depth is not available on the device. Downgrading to an earlier version of ARFoundation, Subsystems & XR Plugins (in my case 4.1.0-preview 2) makes the environment depth work

**To Reproduce**
1. Run the DepthImages Scene on an iOS device with LiDAR sensor

**Expected behavior**
Seeing the depth image.

**Actual behavior**
Depth image not available on device.

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2020
 - OS: iOS 14.0
 - Unity version 2019.4.13f1
 - ARFoundation version 4.1.0-preview 11

**Comment by todds-unity** [comment]
What is the exact iOS version?

Go into Settings -> General -> About -> Software Version and tap on the "14.0" text. It will change to display a longer string with numbers & letters in parentheses.  What is that full string?

**Comment by re-cheid** [comment]
Currently running 18A5301v (iOS 14 beta 1)
I can update to non-beta and test again next week

**Comment by tdmowrer** [comment]
This is almost certainly the issue. Please let us know whether you can reproduce this after updating to the iOS 14 release.

**Comment by re-cheid** [comment]
Ok I updated to iOS 14.1 (18A8395) and it works now, thanks
