### ISSUE TITLE
How to attach object to AR Camera

### ISSUE THREAD

**Issue by Schaggo** [Unity-Technologies/arfoundation-samples#647]
How do I correctly attach a game object to the ar camera?

My current approach is to attach the object via
`transform.position = Camera.main.transform.position + Camera.main.transform.forward * viewingDistance;`.

 I get some jitter on the y-axis when moving the device the app is running on. 

Am I missing something or is there a better approach?

**Comment by Schaggo** [comment]
Alright, 
I just changed the parent to the AR Camera and "et voilà".

**Comment by tdmowrer** [comment]
To explain why your original approach didn't work: the camera's transform is updated in an [Application.onBeforeRender](https://docs.unity3d.com/ScriptReference/Application-onBeforeRender.html) callback, so if you query the transform in, say, an `Update()` method, then you will get the previous frame's transform.

We do something similar in [this sample](https://github.com/Unity-Technologies/arfoundation-samples/blob/6ef4e8818d4b9797d579c1a5a75ab0d4d8ee3c1c/Assets/Scenes/LightEstimation/FacingDirectionManager.cs#L62-L70) to drive an object based on the camera position.

**Comment by Schaggo** [comment]
Thanks! I figured that there might be two objects pushing transform info. 

My current approach works but in order to execute a OnMouseDrag I needed to add/remove a rigidbody to the object. I figure that that’s probably bad for performance. 
So I’ll try to get a version of the scrip you posted working. 
Thanks again!

**Comment by tdmowrer** [comment]
You are subscribing to `onBeforeRender` each frame, so `onBeforeRender` is called N times where N is the number of frames since start.

You only need to subscribe once, e.g., in `OnEnable`. I would also unsubscribe in `OnDisable` to avoid being called after your behavior is disabled/destroyed.

**Comment by Schaggo** [comment]
Again, thank you!

Works like a charm!
