### ISSUE TITLE
[Bug] AR plane detection seems to crash on iOS

### ISSUE THREAD

**Issue by Dyonisian** [Unity-Technologies/arfoundation-samples#648]
I'm trying to implement AR plane detection in a way that's similar to how its used here and in the AR Foundation demos. It works fine on Android, but causes a crash when I try to do it on iOS.

This is the code I'm using - 

In Start():

```csharp
arPlaneManager.planesChanged += PlaneChanged;


private void PlaneChanged(ARPlanesChangedEventArgs args)
{
    if (args.added != null)
    {
        if (!foundPlane)
            instructionsText.text = instructionStrings[1];
        foundPlane = true;
    }
}
```

This works just fine on Android. On iOS, when I point my camera at the ground, it crashes immediately. 

Is there anything I could try here, or anything similar that has happened before? I'm not able to get a crash log because I'm relying on Unity Cloud build for building for iOS and don't have a Mac for debugging.

 - Device: iPad Pro 2020
 - OS: iOS 14.1
 - Unity 2020.1.6f1.
 - ARFoundation version 4.0.8 
 - AR Kit plugin 4.0.8. 

I'm attaching the crash log. Its not too readable so I've also attached a screenshot of the part of it that is readable and seems relevant.

[e7pViXUBOEtv_1nDn-WR_data.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/5476062/e7pViXUBOEtv_1nDn-WR_data.txt)
![Image 3](https://user-images.githubusercontent.com/15832176/97885914-e0f0c800-1d1f-11eb-8019-7a9992894a49.png)

**Comment by tdmowrer** [comment]
It looks like it tried to burst compile something and jumped to address 0 (i.e., it called a null function pointer). Although that is a job in the ARKit package, we don't use Burst. Do you have Burst in your project?

As a sanity check, I built the 4.0 branch of this repo using Unity Cloud Build and ran a plane detection sample (SimpleAR) without issue.

**Comment by Dyonisian** [comment]
Thanks for your help Tim. I've disabled the burst compiler for iOS and I'll try to see if that helps. Is there anything else that comes to mind that might cause iOS in particular to not work with this code?

I checked the samples again and they do work for me. But not in my own project. I'm inclined to believe that my project should work because it works on Android, but iOS doesn't seem to like it. Since this seems to be an issue with an AR Foundation feature rather than the samples, is there somewhere else I could bring this bug up (Rather than in this AR foundation samples repo) to see if its reproducible?

**Comment by tdmowrer** [comment]
Please [log a bug](https://unity3d.com/unity/qa/bug-reporting) and include your project.

**Comment by Dyonisian** [comment]
Hi Tim, thanks for your responses, they were extremely helpful. Turning off burst compile did in fact fix the issue. Any chance you would be able to highlight for me which line in the crash log indicated that burst compile was enabled and was causing the crash? I don't think I would have ever been able to figure out on my own that burst compile had to be turned off for this. 

I'll close the isssue now (Or you can).

**Comment by tdmowrer** [comment]
The top two calls in the callstack are `BurstCompilerServices::CompileAsync` followed by a jump to address `0x000000000000000 <unknown>` (which is what happens if you call a null function pointer).

> Turning off burst compile did in fact fix the issue.

The job it is dealing with is should not be Burst compiled; have you made any source modifications to the ARKit package? If you log a bug with an attached project, I can dig into it more.

**Comment by Dyonisian** [comment]
Right, I completely missed that. Also wouldn't have known about the jump to address since I've never looked at a crash log before. Thanks again. 

So I'm using AR Foundation in my own project, not in the samples project. I'm using plane detection in a script of my own. I did not modify any ARKit or ARFoundation package files though, and I did not use the [BurstCompile] attribute in any scripts of my own.

I assume what you're saying is that even with burst compile enabled in the project settings, this should not be an issue because ARKit and ARFoundation scripts are not using the [BurstCompile] attribute?

In that case let me know and I'll file the bug report.

Thanks once more.

**Comment by tdmowrer** [comment]
> I assume what you're saying is that even with burst compile enabled in the project settings, this should not be an issue because ARKit and ARFoundation scripts are not using the [BurstCompile] attribute?

Correct.

> In that case let me know and I'll file the bug report.

Yes, please do, and post the case ID here so that I can find it quickly.

Also, from where does your callstack come? The screenshot you posted, while helpful, is not from a tool I recognize, and you said you don't have a Mac for debugging. How are you running and debugging your app?
