### ISSUE TITLE
Download arcore-unity- SDK -v1.5.0.unitypackage package apk installation start black screen

### ISSUE THREAD

**Issue by webloverand** [Unity-Technologies/arfoundation-samples#65]
phone model : Huawei P20 Pro
Phone ARCore version : 1.5.180910096

Logout :
11-12 18:29:23.990 10718-10744/? E/native: session_c_api.cc:289 ArConfig_setUpdateMode: session was passed NULL.
    session_c_api.cc:272 ArConfig_setPlaneFindingMode: session was passed NULL.
    session_c_api.cc:237 ArConfig_setLightEstimationMode: session was passed NULL.
    session_c_api.cc:307 ArConfig_setCloudAnchorMode: session was passed NULL.
    session_c_api.cc:374 ArConfig_setFocusMode: session was passed NULL.
    session_c_api.cc:550 ArSession_configure: session was passed NULL.
    session_c_api.cc:1158 ArFrame_acquireCamera: session was passed NULL.
    session_c_api.cc:1027 ArCamera_getTrackingState: session was passed NULL.
    session_c_api.cc:1158 ArFrame_acquireCamera: session was passed NULL.
    session_c_api.cc:1027 ArCamera_getTrackingState: session was passed NULL.

Why is it so?I packed it according to the tutorial : https://developers.google.cn/ar/develop/unity/quickstart-android

**Comment by nilsk123** [comment]
You're not supposed to include the arcore sdk when using this package.

Just follow this https://github.com/Unity-Technologies/arfoundation-samples/blob/master/README.md
