### ISSUE TITLE
[Bug] ARSession CheckAvailability State is wrong

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#650]
**Describe the bug**
When I use `CheckAvailability` on a device where `Google Play Services for AR` is **not installed**, the detected status is always`Unsupported` instead of `NeedInstall`. The device is **supported ARCore**!

**To Reproduce**
```C#
public IEnumerator CheckAvailability()
{
   if ((ARSession.state == ARSessionState.None) ||
       (ARSession.state == ARSessionState.CheckingAvailability))
      {
          yield return ARSession.CheckAvailability();
      }
            
     Debug.Log($"Current AR Session State:{ARSession.state.ToString()}");
}
```

**Log**
```log
I/native: arpresto_api.cc:30 ArPresto::ArPresto_initialize
I/native: arpresto_api.cc:77 ArPresto::ArPresto_checkApkAvailability
I/chatty: uid=10180(com.cell.test) UnityMain identical 14 lines
E/SchedPolicy: set_timerslack_ns write failed: Operation not permitted
W/ARCore-InstallService: bindService returned false.
E/ARCore-InstallService: Play Store install service could not be bound.
```
**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9 SE
 - OS: Android 9
 - Unity version: 2020.1
 - ARFoundation version: 4.0.8 and 4.0.9

**Comment by tdmowrer** [comment]
Can you run this command and post the output here?

```adb shell getprop ro.build.fingerprint```

**Comment by weacw** [comment]
> Can you run this command and post the output here?
> 
> `adb shell getprop ro.build.fingerprint`

`Xiaomi/grus/grus:9/PKQ1.181121.001/V11.0.5.0.PFBCNXM:user/release-keys`
![image](https://user-images.githubusercontent.com/11573490/98356357-677a1200-205e-11eb-9e2b-c1ef43e80a8f.png)

**Comment by tdmowrer** [comment]
Thanks; it looks like your device is indeed supported. The "Play Store install service could not be bound" error message sounds like an issue with the phone's app store. Is an app store disabled or not installed? What app store do you use on this device?

**Comment by weacw** [comment]
> Thanks; it looks like your device is indeed supported. The "Play Store install service could not be bound" error message sounds like an issue with the phone's app store. Is an app store disabled or not installed? What app store do you use on this device?

Thank you for your reply. I can not install the `Goolge Play Store` because I'm in China. This device is using the `Xiaomi app store`(https://developers.google.com/ar/discover/supported-devices?hl=zh_cn#android_china). I don’t understand why I need to use the Play Store to check whether the ARCore service is installed?

**Comment by tdmowrer** [comment]
>  I don’t understand why I need to use the Play Store to check whether the ARCore service is installed?

You do not need the Google Play store, but you need _an_ app store, and the Xiaomi app store should work.

As a sanity check, have your tried [Google's ARCore plugin](https://github.com/google-ar/arcore-unity-sdk)? If that plugin has the same problem, then please post an issue on their GitHub issues page, as that means it is an issue with the ARCore SDK. If it does not have the same problem, then we will consider a bug in Unity's implementation.

**Comment by weacw** [comment]
> > I don’t understand why I need to use the Play Store to check whether the ARCore service is installed?
> 
> You do not need the Google Play store, but you need _an_ app store, and the Xiaomi app store should work.
> 
> As a sanity check, have your tried [Google's ARCore plugin](https://github.com/google-ar/arcore-unity-sdk)? If that plugin has the same problem, then please post an issue on their GitHub issues page, as that means it is an issue with the ARCore SDK. If it does not have the same problem, then we will consider a bug in Unity's implementation.

Thank you. Next I'll try Google's ARCore plugin.

**Comment by 4litasci-roofstacks** [comment]
Make sure your ARCore and ARKit Requirements are optional. It might be thinks your device is supported because you select requirement as "Required" Ideally you should not install apk to unsupported device and it shows you wrong information. 

<img width="722" alt="Screen Shot 2022-06-16 at 10 17 06" src="https://user-images.githubusercontent.com/87859674/174014839-87518bc8-fc66-4f77-a99e-25806f92c682.png">
