### ISSUE TITLE
Camera flickers green with Multithreading Rendering

### ISSUE THREAD

**Issue by josefgrunig** [Unity-Technologies/arfoundation-samples#652]
**Issue**
Camera flickers to green randomly after a certain number of frames

**To Reproduce**
1. Download Unity 2020.1
2. Download ARFoundation-Samples 3.1
3. Open Project, Select ARWorldAnchor (any scene), Build on Android Tablet

**Expected behavior**
Camera is expected not to flicker
Turning off Multithreading rendering resolves the issue, but performance drops drastically

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S5e
 - Android 10
 - Unity version: 2019.3.12f1 and 2020.1.11f1
 - ARFoundation version 3.1

Here you can find a video capture of the issue: 
ARFoundation: https://hoppar.app/files/ARFoundation-Issue.mov
HoppAR Game: https://www.hoppar.app/files/Game-Issue.mov

Attached Screenshots of my Game and reproduction in ARFoundation Samples
<img width="614" alt="Capture-Game-Issue" src="https://user-images.githubusercontent.com/32868530/98116049-03ade880-1ea8-11eb-9adf-90edaffa9a1c.png">

<img width="614" alt="Capture-ARFoundation-Issue" src="https://user-images.githubusercontent.com/32868530/98116034-fee93480-1ea7-11eb-95d9-07057a265dd4.png">

**Comment by DavidMohrhardt** [comment]
Would you be able to post the profiler frame time?  This looks like the background isn't finished rendering when the frame is displayed.

**Comment by josefgrunig** [comment]
Here the profile data captured from my game were it happens every 2 or 3 frames:
https://hoppar.app/files/profiler_game.data
Let me know if I can help with further information

**Comment by DavidMohrhardt** [comment]
Hello, sorry to get back to you so late.  I see the present spilling over into the next frame (which makes sense in a multithreaded rendering context) however there is a chance that the frame is presented before the background has finished rendering to the background.  The hint for that being that the green section is isn't attached to geometry and is rendering green with a little step.

We introduced a fix for this issue in the ARCore 4 release.  If you can update I would recommend updating to ARFoundation 4. and seeing if that fixes the issue.

**Comment by josefgrunig** [comment]
I made a quick and dirty test upgrading to v4 but the camera background is black. Probably I will need to get deeper into this and see what is wrong by checking out the updated samples too. Is upgrading to Unity 2020.2 mandatory?
This may take some time because I have ongoing work on the project that can't be rescheduled. I will let you know on this thread my outcomes.

**Comment by tdmowrer** [comment]
4.0/4.1 are 2019.4+ compatible, bit you need to enable ARCore in Player Settings > XR Plug-in Management. This probably explains the black screen issue.

**Comment by josefgrunig** [comment]
Thank you @tdmowrer,
I will need to upgrade unity too since I am on 2019.3. I will let you know as soon as possible.

**Comment by josefgrunig** [comment]
Thank you for the support, upgrading to ARFoundation V4.0.2 did fix the issue.
Black camera has been fixed by enabling ARCore in the XR Plugin-Management (wasn't aware of this addition)
Will later go through the migration guides for both Unity / ARFoundation and XR Plugin Management
Bests

**Comment by justin-pierce** [comment]
Is it possible to fix this on previous versions of Unity? I'm running 2018.4.13 with a GoogleARCore plugin that predates ARFoundation, but I'm experiencing this same issue. I'm not sure what caused the issue -- it wasn't a problem in the past and it doesn't seem to happen in every situation. Maybe related to an update with Google Play Services for AR? I'm not 100% sure how that interacts with apps. 

Since 2018 is still LTS, we weren't planning to upgrade Unity (at least not beyond 2018 LTS) until later. 

Thanks,

**Comment by tdmowrer** [comment]
The GoogleARCore plugin is maintained by Google over at https://github.com/google-ar/arcore-unity-sdk. You might try posting on their issues page.

**Comment by tdmowrer** [comment]
> i have a similar question , please help me take a look [https://github.com/Unity-Technologies/arfoundation-samples/issues/985](url) @tdmowrer

I no longer work for Unity, but you're in good hands :)
