### ISSUE TITLE
[Bug]About Removed in TrackedEventArgs

### ISSUE THREAD

**Issue by chaoslife** [Unity-Technologies/arfoundation-samples#654]
Hi,
In image and object detection, I use ARTrackedObjectsChangedEventArgs and ARTrackedImagesChangedEventArgs to handle if target is added and removed.
But it will be notified only when image or object be added device for the first time. When I move out the device, there is no remove callback. I want to do some logic when removing, but ARFoundation has no remove callback.

I do not know how to solve this?

**Comment by tdmowrer** [comment]
This is the expected behavior. "Removed" does not mean "removed from view". You might instead try checking the tracking state of the tracked image/object. See also https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html#tracking-state

**Comment by chaoslife** [comment]
> This is the expected behavior. "Removed" does not mean "removed from view". You might instead try checking the tracking state of the tracked image/object. See also https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html#tracking-state

Okay, when is the timing of Remove trigger?

**Comment by tdmowrer** [comment]
Sorry, I don't understand the question. What do you mean by the "timing"?

**Comment by chaoslife** [comment]
> Sorry, I don't understand the question. What do you mean by the "timing"?

When will the removed method be called? just as add method be called when first ar view tracked

**Comment by tdmowrer** [comment]
It is up to the underlying AR framework (e.g., ARKit or ARCore). Since the physical image that is being tracked can move around, ARCore/ARKit have no way of knowing if it is temporarily out of view of if it should be removed. In general, I find both are very reluctant to indicate the tracked image has been "removed".

> I want to do some logic when removing, but ARFoundation has no remove callback.

If you mean "removed from view", then responding to changes in the tracking state is probably your best bet. A change in the tracking state is considered "updated" for the purposes of the [trackedImagesChanged event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged).

**Comment by chaoslife** [comment]
I

> It is up to the underlying AR framework (e.g., ARKit or ARCore). Since the physical image that is being tracked can move around, ARCore/ARKit have no way of knowing if it is temporarily out of view of if it should be removed. In general, I find both are very reluctant to indicate the tracked image has been "removed".
> 
> > I want to do some logic when removing, but ARFoundation has no remove callback.
> 
> If you mean "removed from view", then responding to changes in the tracking state is probably your best bet. A change in the tracking state is considered "updated" for the purposes of the [trackedImagesChanged event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged).

I checked TrackingState, In ARTrackable class. it only has three states: None Limited and Tracking, so which state means "remove from view" ?

**Comment by tdmowrer** [comment]
> I checked TrackingState, In ARTrackable class. it only has three states: None Limited and Tracking, so which state means "remove from view" ?

Did you follow the link I posted earlier? https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html#tracking-state attempts to explain this.

**Comment by chaoslife** [comment]
> > I checked TrackingState, In ARTrackable class. it only has three states: None Limited and Tracking, so which state means "remove from view" ?
> 
> Did you follow the link I posted earlier? https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html#tracking-state attempts to explain this.

Thanks for the response. I will try this
