### ISSUE TITLE
Android Instant app with AR Foundation

### ISSUE THREAD

**Issue by creativehims** [Unity-Technologies/arfoundation-samples#655]
ARCore doesn't support OpenGLES2 graphics API and Instant App works with OpenGLES2 only. How can we develop instant apps with ARF? Any tips?

**Comment by creativehims** [comment]
@tdmowrer Have you come across any AR instant apps? I've found some material on how to develop them natively with ARCore, but couldn't find anything pertaining to ARF in Unity.

**Comment by tdmowrer** [comment]
I'm not aware of any Android Instant Apps that use ARFoundation specifically, but OpenGLES2 is not a requirement for Instant Apps, and ARCore in general can be used with Instant Apps.

Google has some information for setting up Unity for Instant App development [here](https://developer.android.com/topic/google-play-instant/getting-started/game-unity-plugin).

**Comment by creativehims** [comment]
Yeah, I've checked out the link and tried implementing the steps. As you can see, OpenGLES2 is a must. 

![opengl](https://user-images.githubusercontent.com/17825870/98590876-775f5380-22f5-11eb-80d3-8dcf383b71fc.png)

**Comment by tdmowrer** [comment]
The advice in that dialog appears to be outdated. You should be able to build OpenGLES3-based Instant Apps. The use of GLES2 is more of a general recommendation to reach more devices since more devices support GLES2 (but those are less likely to support AR).

**Comment by creativehims** [comment]
I tried OpenGLES3 - even before creating the issue. It just didn't work.

**Comment by tdmowrer** [comment]
What didn't work exactly?

The issue you are reporting seems to be unrelated to AR. It might be rephrased as "OpenGLES3 is not supported with Android Instant Apps", which it should be. If that is not the case, please provide more details.

**Comment by creativehims** [comment]
Yes, you got that right. "OpenGLES3 is unsupported with instant apps" or "OpenGLES2 support is not available with ARCore". If I remember correctly, OpenGLES2 was supported in earlier versions of ARCore.
