### ISSUE TITLE
How to determine whether landscape left/right or portrait is better for mesh tracking and plane-finding on ARKit? 

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#656]
Is this already known knowledge in some sort of documentation or chart somewhere? 
How to determine whether landscape left/right or portrait is better for mesh tracking and plane-finding on ARKit?

**Comment by tdmowrer** [comment]
There should be no difference between landscape left and right. Are you seeing an issue that suggests otherwise?
