### ISSUE TITLE
Throwing objects without ARPlanes

### ISSUE THREAD

**Issue by RamoramaInteractive** [Unity-Technologies/arfoundation-samples#658]
Is it possible in ARFoundation to use a depth mode to throw an object somewhere in the room without generating any planes?
I'm using an Android device and I want to create a board game.

**Comment by tdmowrer** [comment]
I'm not sure what you are asking. "Throwing" an object in Unity is not related to plane detection or environmental depth textures. Can you explain your use case in more detail? An example of what you want to do would be useful.

**Comment by RamoramaInteractive** [comment]
https://www.youtube.com/watch?v=EBLPsgz2mx0

In the 3:20 minute you can see, that the ARCore API lab can throw objects on the table or on the floor without generating an ARPlane. I want to generate with ARFoundation an invisible Depth Mesh to throw a dice on the floor or on the table.

**Comment by tdmowrer** [comment]
They are generating a collision mesh from the depth texture. You can see how they do this in [this example](https://github.com/googlesamples/arcore-depth-lab/blob/master/Assets/ARRealismDemos/Collider/Scripts/DepthMeshCollider.cs).

**Comment by RamoramaInteractive** [comment]
Yes, a collision mesh. Thank you. Is it also possible in the latest ARFoundation version to create a collision mesh?

**Comment by tdmowrer** [comment]
ARFoundation provides the [depth texture](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html#UnityEngine_XR_ARFoundation_AROcclusionManager_environmentDepthTexture) from ARCore, but you would have to do something similar to that sample in order to generate a collision mesh from it.

**Comment by RamoramaInteractive** [comment]
Thank you! This looks neccessary for me. 

Theoretically, I can adapt the colliderMesh code and replace some lines with the depth texture of ARCore, right?

**Comment by tdmowrer** [comment]
Theoretically, yes.

**Comment by RamoramaInteractive** [comment]
@tdmowrer thank you for your advice.

In will try to adapt the collisionmesh for ARFoundation.

**Comment by RamoramaInteractive** [comment]
It will take some time. I try to rewrite the collision mesh code for ARFoundation.

**Comment by ZFHung** [comment]
@RamoramaInteractive  Have Anything Progress?
