### ISSUE TITLE
uses-sdk:minSdkVersion 16 with arfoundation

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#660]
We embed ARFoundation into the Native app as a module. At present, the mini sdk requirement of our project is `16`.
Build Error:

```log
uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [ARPresto.aar] /Users/nswell/.gradle/caches/transforms-2/files-2.1/ff8123aadb9692586a64c4db60deaa62/jetified-ARPresto/AndroidManifest.xml as the library might be using APIs not available in 16
Suggestion: use a compatible library with a minSdk of at most 16,
or increase this project's minSdk version to at least 19,
or use tools:overrideLibrary="com.unity.xr.arpresto" to force usage (may lead to runtime failures)
```

**Comment by mdurand42** [comment]
> We embed ARFoundation into the Native app as a module. At present, the mini sdk requirement of our project is `16`.
> Build Error:
> 
> ```
> uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [ARPresto.aar] /Users/nswell/.gradle/caches/transforms-2/files-2.1/ff8123aadb9692586a64c4db60deaa62/jetified-ARPresto/AndroidManifest.xml as the library might be using APIs not available in 16
> Suggestion: use a compatible library with a minSdk of at most 16,
> or increase this project's minSdk version to at least 19,
> or use tools:overrideLibrary="com.unity.xr.arpresto" to force usage (may lead to runtime failures)
> ```

You will need to adjust the min SDK version of your project to 19.

**Comment by tdmowrer** [comment]
> We embed ARFoundation into the Native app as a module. At present, the mini sdk requirement of our project is `16`

19 is also the [min sdk version supported by Unity 2019.4+](https://docs.unity3d.com/ScriptReference/AndroidSdkVersions.html), so I imagine you would have this problem with any Unity application, not just when using ARFoundation.
