### ISSUE TITLE
ARKit Meshing (ARMeshManager) density

### ISSUE THREAD

**Issue by KirillKuzyk** [Unity-Technologies/arfoundation-samples#661]
**Is your feature request related to a problem? Please describe.**
ARMeshManager.density is not working with ARKit. The documentation says 'Not all platforms are supported' but it doesn't say which ones are.

**Describe the solution you'd like**
Add the support for ARMeshManager.density with ARKit.

**Describe alternatives you've considered**
Explicitly describe what platforms support setting density.

**Comment by tdmowrer** [comment]
I'll add better documentation to indicate what is supported by the ARKit package, but we cannot add support for the mesh density feature on iOS unless it is implemented by Apple.

**Comment by tdmowrer** [comment]
For what it's worth, it _is_ actually documented, albeit not quite as clearly as saying "density is not supported": https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.0/manual/arkit-meshing.html#other-armeshmanager-settings:

> For the ARKit implementation, only these 3 settings affect the performance and output of ARKit meshing.

We'll update it to be more explicit, though.

**Comment by NumaNumaNuma** [comment]
>we cannot add support for the mesh density feature on iOS unless it is implemented by Apple.

There are several iOS scanning apps which offer different density/resolution settings, is there a hard limitation preventing Unity from doing the same thing? I'm guessing they're reading the depth information and sampling that at different resolutions to generate their mesh.

**Comment by tdmowrer** [comment]
We do not generate the mesh; ARKit does. For some time, there have been ARKit-based apps that use custom solutions to generate the mesh based on ARKit's point cloud. There may be some that do something similar with the LiDAR sensor.

By contrast, ARFoundation's ARMeshManager relies entirely on [ARKit to generate the mesh](https://developer.apple.com/documentation/arkit/world_tracking/visualizing_and_interacting_with_a_reconstructed_scene?language=objc).

**Comment by NumaNumaNuma** [comment]
That makes sense thanks!

**Comment by tdmowrer** [comment]
[Documentation](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.0/manual/arkit-meshing.html#other-armeshmanager-settings) updated.
