### ISSUE TITLE
How to keep only one spawned object active when tracked image is detected

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#663]
I have this script where I instantiate an object on the tracked Image position, however, when I track the 2nd image after the 1st one, the GameObject associated with the first one doesn't become inactive.
```cs

    [SerializeField]
    private GameObject[] placeablePrefabs;

    private Dictionary<string, GameObject> spawnedPrefabs = new Dictionary<string, GameObject>();
    public ARTrackedImageManager trackedImageManager;

    GameObject animalPrefab;

 private void Awake()
    {
        foreach (GameObject prefab in placeablePrefabs)
        {
            GameObject newPrefab = Instantiate(prefab, Vector3.zero, Quaternion.identity);
            newPrefab.name = prefab.name;
            spawnedPrefabs.Add(prefab.name, newPrefab);
        }
    }

    private void Update()
    {
        trackedImageManager.trackedImagesChanged += ImageChanged;
    }

 private void ImageChanged(ARTrackedImagesChangedEventArgs obj)
    {
        foreach (ARTrackedImage trackedImage in obj.added)
        {
            switch (trackedImage.referenceImage.name)
            {
                case "Dolphin":
                    Instantiate(placeablePrefabs[0], trackedImage.transform);
                    break;
                case "Boa":
                    Instantiate(placeablePrefabs[1], trackedImage.transform);
                    break;
            }
        }
   foreach (ARTrackedImage trackedImage in obj.updated)
        {
            //UpdateImage(trackedImage);
            switch (trackedImage.referenceImage.name)
            {
                case "Dolphin":
                    animalPrefab = spawnedPrefabs["Dolphin"];
                    animalPrefab.transform.position = trackedImage.transform.position;
                    animalPrefab.SetActive(true);
                    break;
                case "Boa":
                    animalPrefab = spawnedPrefabs["Boa"];
                    animalPrefab.transform.position = trackedImage.transform.position;
                    animalPrefab.SetActive(true);
                    break;
             }
        }
    foreach (ARTrackedImage trackedImage in obj.removed)
        {
            spawnedPrefabs[trackedImage.referenceImage.name].SetActive(false);
        }
    }
```

I tried using this inside the foreach loop for obj.added and obj.removed
```cs
foreach (GameObject go in spawnedPrefabs.Values)
        {
            if (go.name != name)
            {
                go.SetActive(false);
           }
        }
```
However, this results in the app running super slow, almost unusable. 
How can I make it so that any other GameObject besides the one that matches the tracked image name is disabled?

Any help is kindly appreciated

**Comment by tdmowrer** [comment]
I'm not sure I understand what you are trying to achieve. If both "Dolphin" and "Boa" are being tracked, then they will both be in the `updated` list.

If your goal is to only ever have one prefab active at a time, then I would put your `SetActive(false)` logic in the `added` loop -- this would deactivate all GameObjects except the most recently detected one.

Also, you should put this

```csharp
private void Update()
{
    trackedImageManager.trackedImagesChanged += ImageChanged;
}
```

In an `OnEnable` or `Start` method. By doing this in `Update`, you are adding the same callback each frame, so `ImageChanged` will be called N times, where N is the number of frames your `MonoBehaviour` has been active.

**Comment by Sterling-Malory-Archer** [comment]
> I'm not sure I understand what you are trying to achieve. If both "Dolphin" and "Boa" are being tracked, then they will both be in the `updated` list.
> 
> If your goal is to only ever have one prefab active at a time, then I would put your `SetActive(false)` logic in the `added` loop -- this would deactivate all GameObjects except the most recently detected one.
> 
> Also, you should put this
> 
> ```cs
> private void Update()
> {
>     trackedImageManager.trackedImagesChanged += ImageChanged;
> }
> ```
> 
> In an `OnEnable` or `Start` method. By doing this in `Update`, you are adding the same callback each frame, so `ImageChanged` will be called N times, where N is the number of frames your `MonoBehaviour` has been active.

Hi Tim, thank you for your response.

Indeed, my goal is to only have one prefab active at the time. 

Would putting ImageChanged in the Start() work more than once? As in would detecting past the first image work as inteded.

**Comment by tdmowrer** [comment]
> Would putting ImageChanged in the Start() work more than once? As in would detecting past the first image work as inteded.

You only need to subscribe to the event once. I recommend [Microsoft's programming guide for events](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/) for more details.

**Comment by Sterling-Malory-Archer** [comment]
> > Would putting ImageChanged in the Start() work more than once? As in would detecting past the first image work as inteded.
> 
> You only need to subscribe to the event once. I recommend [Microsoft's programming guide for events](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/) for more details.

Hey Tim, I just tried putting SetActive(false) logic in the added loop. but I still get the same result of 2 Gameobjects being active at the same time.

Should I add it to the updated loop as well?

**Comment by tdmowrer** [comment]
Are you sure your GameObjects' have the same name as the reference images?

You could try iterating over the dictionary's KeyValuePairs instead, since you have used the reference image name as the key:

```csharp
foreach (var kvp in spawnedPrefabs)
{
    if (kvp.Key != name)
    {
        kvp.Value.SetActive(false);
    }
}
```

I would also suggest adding some debug logs to help track down what's going on.

**Comment by Sterling-Malory-Archer** [comment]
> Are you sure your GameObjects' have the same name as the reference images?
> 
> You could try iterating over the dictionary's KeyValuePairs instead, since you have used the reference image name as the key:
> 
> ```cs
> foreach (var kvp in spawnedPrefabs)
> {
>     if (kvp.Key != name)
>     {
>         kvp.Value.SetActive(false);
>     }
> }
> ```
> 
> I would also suggest adding some debug logs to help track down what's going on.

Hi Tim,

Yes, my GameObjects have the same names as the reference images?

I will try this, thank you.

**Comment by Sterling-Malory-Archer** [comment]
Hi Tim,

Even when using KeyValuePairs, both prefabs remain active.

**Comment by tdmowrer** [comment]
Hi Archer,

This issues page is really for questions about ARFoundation API usage. I can tell you how ARFoundation works, but I can't debug your code for you.

The [`trackedImagesChanged`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged) event is triggered whenever any [reference image](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.0/manual/image-tracking.html#terminology) is
1. Newly detected (`added` list)
1. Updated (`updated` list)
1. Removed* (`removed` list)

If any of these occur during a frame, the event is triggered _once_ during that frame with the appropriate `added`, `updated`, and `removed` lists.

You only need to subscribe (e.g., `+= ImageChanged`) to the event once. It might be more appropriate to call this method `ImagesChanged` (plural) as it tells you about _all_ the added, updated, and removed images once per frame.

The specific result you are trying to achieve is possible, and I think you generally have the right approach, but you will need to debug it to find out why it is not working the way you expect. I suggest `Debug.Log`ing the names of the reference images as they are added/updated so that you can get an idea for what is happening. You can find that log output using [logcat](https://developer.android.com/studio/command-line/logcat) -- you can access it via the command line and filter for Unity-specific messages with

```adb logcat -s Unity```

Or you can use the [logcat package](https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@latest) for a more integrated Unity experience.

\* Note that, since most AR frameworks can track moving images, they rarely consider images to be "removed" (i.e., cease to exist). Each tracked image also has a `trackingState` which is highly correlated with the device's ability to "see" it. See [these docs](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/tracked-image-manager.html#tracking-state) for details.

**Comment by Sterling-Malory-Archer** [comment]
Hi Tim,

Thank you for your answer, I am not here to ask you to debug, I am here to ask for help because the issue I am facing is not something I've encountered before.

An issue I have is if I move this code into a new method and then call this method in both obj.added and obj.removed,
the Animator component I have attached to both prefabs seems to stop working, even though both of them are enabled in the inspector.

This is quite strange, I will try to make a logcat file and see if I can figure something out.
```cs
private void UpdatedImage(ARTrackedImage trackedImage)
{
  switch (trackedImage.referenceImage.name)
            {
                case "Dolphin":
                    animalPrefab = spawnedPrefabs["Dolphin"];
                    animalPrefab.transform.position = trackedImage.transform.position;
                    animalPrefab.SetActive(true);
                    break;
                case "Boa":
                    animalPrefab = spawnedPrefabs["Boa"];
                    animalPrefab.transform.position = trackedImage.transform.position;
                    animalPrefab.SetActive(true);
                    break;
             }
    foreach (Gameobject go in spawnedPrefabs.Values)
      {
          if (go.name != trackedImage.referenceImage.name)
          {
               go.SetActive(false);
          }
      }
}


```

**Comment by tdmowrer** [comment]
> I will try to make a logcat file

You do not need to make a file. Just run `adb logcat -s Unity` from a terminal and you will get realtime debug log output.

**Comment by Sterling-Malory-Archer** [comment]
> > I will try to make a logcat file
> 
> You do not need to make a file. Just run `adb logcat -s Unity` from a terminal and you will get realtime debug log output.

Hey Tim,

I hope you don't mind helping me with this, I managed to solve the one prefab being active, but my animations (which came in a unitypackage) don't work (although they are connected and work in the editor).

I am attaching a logcat file.

[AQLogcat.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/5549162/AQLogcat.txt)

**Comment by tdmowrer** [comment]
```
:44.985 10927 10956 E Unity   : (Filename: <
11-16 20:15:45.017 10927 10956 E Unity   : NullReferenceException: Object reference not set to an instance of an object
11-16 20:15:45.017 10927 10956 E Unity   :   at ImageTracking.AssignGameObject (System.String name, UnityEngine.Vector3 newPosition, UnityEngine.XR.ARFoundation.ARTrackedImage trackedImage) [0x0005f] in <b49da9d50c8e4c55b6660efb61b1a459>:0
11-16 20:15:45.017 10927 10956 E Unity   :   at ImageTracking.UpdateARImage (UnityEngine.XR.ARFoundation.ARTrackedImage trackedImage) [0x0001a] in <b49da9d50c8e4c55b6660efb61b1a459>:0
11-16 20:15:45.017 10927 10956 E Unity   :   at ImageTracking.ImageChanged (UnityEngine.XR.ARFoundation.ARTrackedImagesChangedEventArgs obj) [0x0004e] in <b49da9d50c8e4c55b6660efb61b1a459>:0
11-16 20:15:45.017 10927 10956 E Unity   :   at UnityEngine.XR.ARFoundation.ARTrackedImageManager.OnTrackablesChanged (System.Collections.Generic.List`1[T] added, System.Collections.Generic.List`1[T] updated, System.Collections.Generic.List`1[T] removed) [0x00022] in <1d256d2d623f4dd591374dd0528295e4>:0
11-16 20:15:45.017 10927 10956 E Unity   :   at UnityEngine.XR.ARFoundation.ARTrackableManager`4[TSubsystem,TSubsystemDescriptor,TSessionRelativeData,TTrackable].Update () [0x001f6] in <1d256d2d623f4dd591374dd0528295e4>:0
```

Is telling you that you have a null reference exception in your `AssignGameObject` method. You will have to debug your app to find out why.

This issues page is for questions about ARFoundation. I cannot debug your specific app or your use of an asset from the asset store. However, there are excellent learning resources and other forums for Unity. I recommend you try one the many [Unity forums](https://forum.unity.com/).

**Comment by Sterling-Malory-Archer** [comment]
> ```
> :44.985 10927 10956 E Unity   : (Filename: <
> 11-16 20:15:45.017 10927 10956 E Unity   : NullReferenceException: Object reference not set to an instance of an object
> 11-16 20:15:45.017 10927 10956 E Unity   :   at ImageTracking.AssignGameObject (System.String name, UnityEngine.Vector3 newPosition, UnityEngine.XR.ARFoundation.ARTrackedImage trackedImage) [0x0005f] in <b49da9d50c8e4c55b6660efb61b1a459>:0
> 11-16 20:15:45.017 10927 10956 E Unity   :   at ImageTracking.UpdateARImage (UnityEngine.XR.ARFoundation.ARTrackedImage trackedImage) [0x0001a] in <b49da9d50c8e4c55b6660efb61b1a459>:0
> 11-16 20:15:45.017 10927 10956 E Unity   :   at ImageTracking.ImageChanged (UnityEngine.XR.ARFoundation.ARTrackedImagesChangedEventArgs obj) [0x0004e] in <b49da9d50c8e4c55b6660efb61b1a459>:0
> 11-16 20:15:45.017 10927 10956 E Unity   :   at UnityEngine.XR.ARFoundation.ARTrackedImageManager.OnTrackablesChanged (System.Collections.Generic.List`1[T] added, System.Collections.Generic.List`1[T] updated, System.Collections.Generic.List`1[T] removed) [0x00022] in <1d256d2d623f4dd591374dd0528295e4>:0
> 11-16 20:15:45.017 10927 10956 E Unity   :   at UnityEngine.XR.ARFoundation.ARTrackableManager`4[TSubsystem,TSubsystemDescriptor,TSessionRelativeData,TTrackable].Update () [0x001f6] in <1d256d2d623f4dd591374dd0528295e4>:0
> ```
> 
> Is telling you that you have a null reference exception in your `AssignGameObject` method. You will have to debug your app to find out why.
> 
> This issues page is for questions about ARFoundation. I cannot debug your specific app or your use of an asset from the asset store. However, there are excellent learning resources and other forums for Unity. I recommend you try one the many [Unity forums](https://forum.unity.com/).

I understand it gives me null reference, but I cannot see at what line, do you maybe know how to read which line it is from this

**Comment by tdmowrer** [comment]
IL2CPP doesn't provide line numbers. Try switching to the Mono backend.

You can also add null checks at various points in your method to see what is null.
