### ISSUE TITLE
Performance optimisation

### ISSUE THREAD

**Issue by Schaggo** [Unity-Technologies/arfoundation-samples#664]
I am currently exploring features for a game while keeping an eye on energy consumption.
The goal is to have life-like assets, which of cause uses a lot of resources.

The project is using the universal render pipeline.
Right now I am loading about 1GB of textures, 400MB of Meshes. Currently ending up with about 80 draw calls.
Reflections are being probed, enviornment light gets estimated. All of which leads to Xcode showing me an energy consumption of 70-80% CPU and 30-20% display (iPhoneX). 

I'm trying to get a grasp of what uses the most CPU/GPU and have several questions.

1) The XCode energy profiler is not showing any % on GPU. Is the app only using the CPU or am I missing something?

2) Is there a document on how to handle which feature (like reflection probing) optimally?

**Comment by tdmowrer** [comment]
This seems like a very general question. This issues page is best for specific questions or bug reports concerning ARFoundation (and AR-related packages). Do you have a question specific to ARKit?

**Comment by Schaggo** [comment]
Hmmm...
I think I will generate a table with which feature is demanding what kind of amount of energy depending.

If you would have a hint why I'm not seeing any GPU usage in the Xcode profiler, would really help for the moment.

**Comment by tdmowrer** [comment]
Please see Apple's [Using Metal System Trace in Instruments to Profile Your App](https://developer.apple.com/documentation/metal/using_metal_system_trace_in_instruments_to_profile_your_app?language=objc)

Unity also has a [profiler](https://docs.unity3d.com/Manual/ProfilerGPU.html) that may be useful.
