### ISSUE TITLE
ARTranslationInteractable acts like Wile E. Coyote [Bug]

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/arfoundation-samples#666]
When dragging objects in the **Interaction.unity** example scene, the object will always be placed at the height of the highest detected plane below the camera, even if a lower plane is being selected and is not occluded.

For example; if a plane is detected on the floor and another is on a table, objects will always be placed at the height of the table unless the phone is lower than the table.

This is happening because the function `GestureTransformationUtility.GetBestPlacementPosition` Raycasts against `TrackableType.Planes` instead of `TrackableType.PlaneWithinBounds` or even better `TrackableType.PlaneWithinPolygon`.

This means it treats all planes as infinite, and since `GetBestPlacementPosition` only checks against the first detected plane it creates a frustrating user experience. A temporary workaround is to modify **ARTranslationInteractable.cs** and **GestureTransformationUtility.cs**, but there probably needs to be a more robust solution to support multiple platforms.

This was tested with iOS 14 and AR Foundation 4.1.0-preview.13.

**Comment by chucknology** [comment]
meep meep

**Comment by chucknology** [comment]
_**meep meep**_

**Comment by chucknology** [comment]
### _**MEEP MEEP!!**_

**Comment by tdmowrer** [comment]
+1 for issue title

**Comment by mattdatwork** [comment]
We're looking into it. We'll post more info once we've confirmed whats going on.

**Comment by tropicdragon** [comment]
Hello! What iOS device are you using when you get this issue?

**Comment by sam598** [comment]
Hi @tropicdragon 

I have tested and experienced this issue in iOS 14 on an iPhone X, iPhone 12 Pro Max, and iPad Pro (4th gen).

I don't think the issue is phone specific, but rather a logical error with how the scripts handle raycasts. It is raycasting `TrackableType.Planes` which returns all planes including `TrackableType.PlaneWithinInfinity`. If all planes are infinite then the first received raycast is always the one closest to the camera.

There are a few other logical issues/difficulties with `ARTranslationInteractable`:

- Even though you can only drag on horizontal planes, vertical planes will still block translation once they are detected. Even worse these block infinitely as well, and can create an issue where half of a room is cut off from interaction because the corner of a wall or couch was detected.

- The interactable object always needs some an "anchor" parent object. This creates confusion when making scenes with pre-instantiated interactables.

- In the script there seems to be an attempt to create either a similar behavior to infinite planes (so a user can place an object anywhere) using the parent "anchor" object, or a "drop down" effect when placing an object at a different level. It's not clear what the intended behavior is because this code is never reached. It seems to be because `ARTranslationInteractable` only positions the object when `GestureTransformationUtility` returns `HasPlacementPosition` as true.

**Comment by sam598** [comment]
Tested with ARFoundation 4.1.1 on an iPhone 12 Pro Max where the issues are still present. On a Galaxy S8 objects can be placed at different heights, although it will sometimes it will rise to the height of a higher plane unexpectedly.

**Comment by sam598** [comment]
Bumping for stale bot.

**Comment by tropicdragon** [comment]
Hello,  just wanted to inform that there is a solution for the issue where translating an object causes it to go to the level of the highest plane. This fix should be available in `1.0.0-pre.2` of the xr interaction toolkit package, which will be released soon.
