### ISSUE TITLE
Face is Mirrored on Android (Scale X = -1) compared to iOS

### ISSUE THREAD

**Issue by andrewio** [Unity-Technologies/arfoundation-samples#667]
So let's take TriAxes.prefab. 
On iOS I have the same XYZ displaying as on the Editor in prefab scene view, but on Android I have the picture like X Scale of this prefab = -1.

Manual Scaling ar runtime is not correct because there is warning: _"BoxColliders does not support negative scale or size. The effective box size has been forced positive and is likely to give unexpected collision geometry. If you absolutely need to use negative scaling you can use the convex MeshCollider."_

So what is the best practice to handle the scaling issue? 
Different prefabs for iOS/Android is not convenient as I feel.

**Comment by tdmowrer** [comment]
> but on Android I have the picture like X Scale of this prefab = -1.

I do not understand this sentence. I think you are saying you've set a negative scale, but are you saying it is according to some recommendation? If so, from where?

Android does reverse the image, which requires that we invert the culling mode on Android, which is what you may be referring to.

Does your prefab require collision geometry?

**Comment by andrewio** [comment]
> Android does reverse the image, which requires that we invert the culling mode on Android, which is what you may be referring to.

So, yes, without any modifications from my side in "FacePose" scene I have mirrored/flipped/reversed view of face prefab instance on Android. On iOS, I have not mirrored instance.

This is looks like if I change the scale for X axis to -1, but I don't do that. It happens automatically.

So If I want universal view (I want, I think that all AR Foundation users want) for face prefab instance for both iOS/Android then I need to manually change the scale for X axis to -1. And here I have physics restriction mentioned above.

**Comment by tdmowrer** [comment]
What is your use case? For what is the collision geometry?

If you do need collision geometry, one solution would be to have the collision geometry on a GameObject with normal scale, then have the render mesh as a child with negative scale.

**Comment by andrewio** [comment]
> If you do need collision geometry, one solution would be to have the collision geometry on a GameObject with normal scale, then have the render mesh as a child with negative scale.

But ARFaceMeshVisualizer must be on the root of Face Prefab, the scale x of the root must be -1.... or no?
