### ISSUE TITLE
ARFoundation 3.1.0-preview.6 looks incorrect in IOS14 

### ISSUE THREAD

**Issue by SocttJame** [Unity-Technologies/arfoundation-samples#668]
With 
"com.unity.xr.arcore": "3.1.0-preview.6", 
"com.unity.xr.arfoundation": "3.1.0-preview.6", 
"com.unity.xr.arkit": "3.1.0-preview.6"
Unity2019.4.13f1,
and enable the human segmentation, light estimation, it can not see anything in real world in IOS14, but totally ok in IOS13.
May I upgrade the package to the latest version and the unity version to 2020.2?

**Comment by tdmowrer** [comment]
Preview versions are not supported after they become verified. Please use 3.1.x (non preview) or update to 4.1.1 (the latest verified release).

**Comment by SocttJame** [comment]
Thanks you!After updated to  3.1.x and use unity 2020.1.13f1, the problem is solved!
