### ISSUE TITLE
Cannot get AR Foundation to work.

### ISSUE THREAD

**Issue by blosmo** [Unity-Technologies/arfoundation-samples#670]
Hi I am trying to load the AR Foundation 4.1 sample scenes but cannot get it to work. I'm getting these errors:

`Assets/arfoundation-samples-latest-preview/Assets/Scenes/InputSystem/InputSystem_PlaceOnPlane.cs(5,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/arfoundation-samples-latest-preview/Assets/Scripts/ARKitBlendShapeVisualizer.cs(64,20): error CS0246: The type or namespace name 'ARKitBlendShapeLocation' could not be found (are you missing a using directive or an assembly reference?)
Assets/arfoundation-samples-latest-preview/Assets/Scenes/InputSystem/InputSystem_PlaceOnPlane.cs(35,31): error CS0246: The type or namespace name 'InputAction' could not be found (are you missing a using directive or an assembly reference?)
`

I am using Unity 2020.2.0b11.3484. From my research, this seems to be an issue with the version of AR Foundation being incompatible with the version of Unity. I have tried several versions and combinations of Unity and AR Foundation, but get similar namespace errors. Any help would be greatly appreciated!

**Comment by tdmowrer** [comment]
This repo is a complete Unity project. It looks like you have cloned or copied parts of this project into another project.

If you want to...

1. ...run these samples, simply clone this repo and open the project in Unity.
1. ...integrate ARFoundation into an existing project, you need to add the packages listed in the [Packages/manifest.json](https://github.com/Unity-Technologies/arfoundation-samples/blob/latest-preview/Packages/manifest.json) (or simply use the Package Manager UI: Window > Package Manager).
