### ISSUE TITLE
ARKit Restore AR Content After Relocalization

### ISSUE THREAD

**Issue by AlanBalderas** [Unity-Technologies/arfoundation-samples#672]
Hello, greetings to all

I've been having a hard time getting the 3D objects back in the correct position after downloading the ARWorldMap and applying it.
My first option was to place different anchors and make the 3D objects children of these anchors. But when I apply the map I print the anchors list and the planes list and sometimes only the planes are created and not the anchors.
My second option is to place at least one anchor as a reference to position them, but applying the ARWorldMap sometimes recreates the anchor and sometimes not. (An idea: maybe it's due to how long the area is scanned before loading the map.)
But trackable planes tend to appear more often than the anchors. So my third option is try to position the 3D objects from an instantiated plane. Is there a way to find that specific plane again?
Try looking for it with the TrackableId, but apparently when you download the ARWorldMap the TrackableId of the planes change.

I would appreciate your help and ideas.

**Comment by tdmowrer** [comment]
> My first option was to place different anchors and make the 3D objects children of these anchors. But when I apply the map I print the anchors list and the planes list and sometimes only the planes are created and not the anchors.

The planes and anchors are provided to ARFoundation by ARKit, so this should not happen, and I have not seen the behavior you describe. Are you certain you are comparing the same list of trackables (planes and anchors) from the point that you created the world map (and not added afterwards)?

> Try looking for it with the TrackableId, but apparently when you download the ARWorldMap the TrackableId of the planes change.

This should also not be the case. The trackableId comes directly from each ARAnchor's [identifier property](https://developer.apple.com/documentation/arkit/aranchor/2867972-identifier?language=objc), and they should persist in the world map (they do in our tests).

Do you have a repro project you can share?

**Comment by AlanBalderas** [comment]
To be quite clear about this, the ARWorldMap is uploaded to a server, so that any device with the app can use it later. 
I am going to try to extract the part of ARWorldMap to create a repo since it is part of a larger application.

Upgrade:
In the search to make the anchors work, I noticed that if at the time of saving the ARWorldMap the `worldMappingStatus `is `Mapped`. And then when downloading and applying it, if the `worldMappingStatus` is also `Mapped `the anchors are placed correctly again.
The problem is that out of 10 attempts only on one occasion the `worldMappingStatus `was `Mapped `at the time of applying it, the rest of the time it is in `Limited `and on those occasions the anchors are not placed again.

**Comment by AlanBalderas** [comment]
I'm going to check the identifiers of the ARAnchors again.

P.S. I am working on:
- Unity 2019.4.12f1
- AR Foundation 4.0.9

**Comment by tdmowrer** [comment]
The anchors contained in a loaded world map may not be appear right away -- the device still has to localize to it and decide whether what it sees can be reconciled with the data contained in the world map.

And yes, it is best to wait until the `worldMappingStatus` is `Mapped` before saving one. See descriptions for possible world mapping statuses [here](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.1/api/UnityEngine.XR.ARKit.ARWorldMappingStatus.html).

**Comment by lmaxsmith** [comment]
Is it possible save anchors independent of the large map? And then to apply them to a map that is in place?
