### ISSUE TITLE
Switching between User and World cameras breaks ARKit tracking when position tracking is enabled [Bug]

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/arfoundation-samples#673]
When switching between two scenes, one with the **Facing Direction** set to **User** and the other set to **World**, and with **Tracking Mode** set to **Position And Rotation**, ARKit seems to break and will stop updating the camera pose until the app is force quit.

If the **Tracking Mode** of the **User** facing scene is set to **Rotation Only** tracking will work fine. If `LoaderUtility.Deinitialize();` and `LoaderUtility.Initialize();` are called before loading the new scene tracking will work fine.

My assumption is that the subsystem resets when there is a change in the **Tracking Mode** but not **Facing Direction**. This was tested in iOS 14 on an iPhone 12 Pro Max and an iPad Pro (4th gen).

**Comment by tdmowrer** [comment]
This is a known issue in iOS 14. You can workaround it as described in the [resolution notes here](https://issuetracker.unity3d.com/issues/arfoundation-mobile-gameobjects-dont-disappear-when-deactivating-them-and-switching-cameras).

**Comment by sam598** [comment]
If you have no intention of preserving the AR session would changing the tracking mode configuration still be a better workaround than Deinitialize/Initialize?

**Comment by tdmowrer** [comment]
> If you have no intention of preserving the AR session would changing the tracking mode configuration still be a better workaround than Deinitialize/Initialize?

It's really up to you. Deinit/init has more overhead, but guarantees a "clean" state.

Also, to clarify:

> My assumption is that the subsystem resets when there is a change in the **Tracking Mode** but not **Facing Direction**.

There is no "reset" when changing the tracking mode or facing direction. We simply tell ARKit to keep the same ARSession, but use a different type of [ARConfiguration](https://developer.apple.com/documentation/arkit/arconfiguration?language=objc) (or the same configuration with different settings, if possible).

**Comment by sam598** [comment]
Thank you for the clarifications. In my project there are non-AR scenes loaded in between the User and World facing scenes, so holding on to the AR Session doesn't make sense in this case.
