### ISSUE TITLE
 hand recognition and foot recognition

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#674]
Hi, I was wondering now, arfundation, does it support hand recognition and foot recognition?If so, can you provide a link or case for reference?Thank you very much @

**Comment by tdmowrer** [comment]
ARFoundation on iOS supports

- Full body skeletal detection, which includes joints for hands and feet. See [here](https://github.com/Unity-Technologies/arfoundation-samples#humanbodytracking3d) for the sample in this repository.
- Depth and stencil textures for human body parts (even a partial leg or hand is usually enough). [Sample here](https://github.com/Unity-Technologies/arfoundation-samples#depthimages).

**Comment by sam598** [comment]
@Arytes If you are looking for cross platform finger tracking to add on top of AR Foundation, you might want to look at this project: https://github.com/asus4/tf-lite-unity-sample

**Comment by tdmowrer** [comment]
@Arytes do you have the information you need?
