### ISSUE TITLE
Collision detection with an image tracked object

### ISSUE THREAD

**Issue by RamoramaInteractive** [Unity-Technologies/arfoundation-samples#676]
Is it possible, to do an OnTriggerEnter-Event between a 3D object and an object generated by AR Tracked Image Manager?

**Comment by tdmowrer** [comment]
Sure -- the ARTrackedImageManager will spawn whatever prefab you assign it (or you can subscribe to its [event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged) to perform more complex logic).

You could, for example, use a prefab with a box collider and your own MonoBehaviour that updates the size of the collider according to the dimensions of the [ARTrackedImage](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackedImage.html).
