### ISSUE TITLE
ARKitFaceBlendShapes for ARCore

### ISSUE THREAD

**Issue by takeuphonic** [Unity-Technologies/arfoundation-samples#678]
Hi. I really love the ARKitFaceBlendShapes.
I know this is a feature for ARKit only, but I want to use it on ARCore too.

I am developing an app which uses this feature for the player`s avatar face. 
I am currently planning to publish this for iPhones, but I like to have it for Androids in the future.

Are there any hope of this in the future?
If there is, I would like to know when it will be, and about how many Android devices it will support.
Or are there any workarounds?

**Comment by tdmowrer** [comment]
On Android, ARFoundation relies on Google's ARCore SDK, so we will support this if and when Google does. You might try creating a feature request at https://github.com/google-ar/arcore-unity-sdk instead.

**Comment by takeuphonic** [comment]
Thank you for your kind response. I will make a request there.

**Comment by takeuphonic** [comment]
I have made a feature request in the bellow URL.
https://github.com/google-ar/arcore-unity-sdk/issues/768

**Comment by tdmowrer** [comment]
Great; I'll keep an eye on it. We'll add support in ARFoundation if and when this feature becomes available.

**Comment by emphaticaditya** [comment]
Hey guys
any progress on this? Can anyone comment.
