### ISSUE TITLE
Post processing v2 with LWRP causes artifacts on camera

### ISSUE THREAD

**Issue by Ursanon** [Unity-Technologies/arfoundation-samples#68]
Hey, 
When I add post processing v2 to my AR scene/camera it produces artefacts.
I'm using AR LWRP Rendering asset from [lwrp_support](https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp_support) branch.

(I have submitted it already via build-in bug report too) 

[log-iPhone6s.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/2580763/log.txt)

**Comment by jimmy-jam** [comment]
still working on lwrp_support to support more recent lwrp versions.  that might fix this issue.  will take a look after that.

**Comment by StewMcc** [comment]
Will LWRP support always require custom code, like in lwrp_support branch, or will it be built into ARFoundation package itself at some point?

**Comment by tdmowrer** [comment]
Support is built in. It's the sample that is on a separate branch because it brings in additional packages that requires a specific version of Unity.

**Comment by bitfabrikken** [comment]
@tdmowrer I don't think that is correct. I haven't been able to get LWRP + ARFoundation working with anything but 3.3.0 of LWRP and the custom camera scripts included in the [LWRP branch]([url](https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp_support)). But please tell me I'm wrong - I hope I am! :)

**Comment by bitfabrikken** [comment]
@tdmowrer Okay, I'm having a hard time understanding, sorry. It's fine if its just for the samples, they do say it's only for 3.3.0.

I did manage to get up and running with the latest LWRP and AR Foundation, but can't get the camera working properly - I think I need a background asset file, but the one from the 3.3.0 sample doesnt work. I've asked on the forums, but maybe theres an obvious solution I'm missing? Sorry for hijacking this..

**Comment by renaudbedard** [comment]
For what it's worth, I was able to port the current ARFoundation samples to LWRP 4.6, but some features are still broken : HDR and Post-Processing result in a blank screen. So it's possible to do intuitively, I could upload a sample project if you can't figure it out at all.

**Comment by jimmy-jam** [comment]
fwiw, i have been working on making the sample that will work with the next version of the LWRP package, and I've been waiting for that to be released (it contains the mechanism to fix the issue).  I'll check on that again next week.

**Comment by aviggiano** [comment]
Has anyone had any success using Post Processing with AR Foundation? We've been using LWRP 3.3 with success, however PP Layer doesn't work, as you all know.

From the latest thread (https://forum.unity.com/threads/arfoundation-now-supports-lwrp-4-8-0-preview.615109/) , jimmya said PostFX v2 was supposed to work, however we've updated our project to use ARFoundation with LWRP 4.8 and we found the same blank screen issue.

**Comment by jimmy-jam** [comment]
> Has anyone had any success using Post Processing with AR Foundation? We've been using LWRP 3.3 with success, however PP Layer doesn't work, as you all know.
> 
> From the latest thread (https://forum.unity.com/threads/arfoundation-now-supports-lwrp-4-8-0-preview.615109/) , jimmya said PostFX v2 was supposed to work, however we've updated our project to use ARFoundation with LWRP 4.8 and we found the same blank screen issue.

It should work - could you submit a bug using Unity Bugreporter with a sample project attached, and then let me us know the bug number here so that we can have a look at it.

**Comment by aviggiano** [comment]
Hello @jimmy-jam,

Thanks for the prompt reply. To demonstrate the issue, [this is the sample project](https://drive.google.com/file/d/1Abw7V5K1hBHbsb2tlFdqsB3XFCkfPcK6/view?usp=sharing) we're using with LWRP + ARFoudation + PPv2 (Ambient Occlusion active in this case at the LWRPSampleScene). The build platform was iOS.

Do you have any examples with ARFoudantion + LWRP + Post Processing V2 for us to see? It would be amazing to see all these great tools combined, especially because there aren't that many tutorials out there.

**Comment by mdurand42** [comment]
Here are instructions for setting up an ARFoundation project to use URP:
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/ar-camera-background-with-scriptable-render-pipeline.html
