### ISSUE TITLE
is posible get distance with TryAcquireEnvironmentDepthCpuImage?

### ISSUE THREAD

**Issue by Ivan547-arnus** [Unity-Technologies/arfoundation-samples#683]
I need measure estimate distance between user and selected point and i want to know if AROclussion manager works to me

**Comment by tdmowrer** [comment]
Yes, the AROcclusionManager can give this to you. There is a [sample](https://github.com/Unity-Technologies/arfoundation-samples#cpuimages) that shows how to get the raw depth images.

**Comment by Ivan547-arnus** [comment]
ok, but how to get point with position in real world for measure distance

**Comment by mdurand42** [comment]
> ok, but how to get point with position in real world for measure distance

This should be do-able at the application level and you might be able to get some suggestions for a solution on the Unity Forums. But the AR Foundation APIs for depth appear to be working as designed. Per-frame depth data in meters is available for each pixel.

**Comment by MTL2097** [comment]
Hi!!! I´m making use of CPU Image to work with computer vision algorithm. 
Now, I would like to try to get distance of a pixel selected in screen by using AR Occlussion Manager working out with image from CPU. I haven´t achieved this to work. Unfortunatelly If I have enabled de AROcclussionManager that is attached to the ARSessionOrigin, image from camera never is rendered on the screen. I followed everything exactly as indicated in the example of CPUImageSample.cs 
Any advice for this issue?? :D thanks a lot!.

**Comment by tdmowrer** [comment]
Does the [CpuImages](https://github.com/Unity-Technologies/arfoundation-samples#cpuimages) sample work without modification?

**Comment by MTL2097** [comment]
![image](https://user-images.githubusercontent.com/67283626/102557362-94bfd400-4090-11eb-9722-0184023fc070.png)
The sample from your repository works fine without any modification. 
So, I can realize in this escene you are working AR Oclussion Manager with 4 Raw Images. The question is:
can I apply this sample (Simple Occlussion) in the same Raw Image that I´m using for CPUImage method instead of 4 Raw Images?

**Comment by tdmowrer** [comment]
You don't need 4 raw images -- this sample just shows how to get various cpu images that may be available.

If the sample works but your own code doesn't, I suggest trying to narrow down the differences. Are any exceptions thrown? Is there any logcat output?

```
adb logcat -s Unity
```

May be useful, as well as the [logcat package](https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@latest).

**Comment by KirillKuzyk** [comment]
Here is an example script. It prints the depth in meters at the depth texture's center and works both with ARCore and ARKit:
https://forum.unity.com/threads/aro...ct-distance-information.1097842/#post-7069510

**Comment by KirillKuzyk** [comment]
> I need measure estimate distance between user and selected point and i want to know if AROclussion manager works to me

Here is an example script. It prints the depth in meters at the depth texture's center and works both with ARCore and ARKit:
https://forum.unity.com/threads/aro...ct-distance-information.1097842/#post-7069510

**Comment by Ivan547-arnus** [comment]
Thanks! altought works to me the R value from center pixel

**Comment by KirillKuzyk** [comment]
> Thanks! altought works to me the R value from center pixel

Yes, reading the R value from the depth texture is also possible, but the TryAcquireEnvironmentDepthCpuImage method is far more efficient.
