### ISSUE TITLE
[Bug] When using SetAllPlanesActive(bool value) from PlaneDetectionController.cs, Feathered Planes come back unfeathered.

### ISSUE THREAD

**Issue by corbinyo** [Unity-Technologies/arfoundation-samples#684]
When using feathered planes with `AR Plane Manager` and  using `SetAllPlanesActive(bool value)` from the `PlaneDetectionController.cs` class - when `Value` is set to `true` after setting `Value` to `false` (hiding planes), feathered planes re-appear as unfeathered planes.

**Comment by mdurand42** [comment]
> When using feathered planes with `AR Plane Manager` and using `SetAllPlanesActive(bool value)` from the `PlaneDetectionController.cs` class - when `Value` is set to `true` after setting `Value` to `false` (hiding planes), feathered planes re-appear as unfeathered planes.

Can you share what branch of the samples you used when you encountered this issue and the version of Unity?

**Comment by corbinyo** [comment]
> > When using feathered planes with `AR Plane Manager` and using `SetAllPlanesActive(bool value)` from the `PlaneDetectionController.cs` class - when `Value` is set to `true` after setting `Value` to `false` (hiding planes), feathered planes re-appear as unfeathered planes.
> 
> Can you share what branch of the samples you used when you encountered this issue and the version of Unity?
I am using:
Unity 2019.4.15f1
AR Foundation Version 4.1.1 - November 17, 2020

**Comment by tropicdragon** [comment]
Just to make sure, when the feathered planes re-appear are they only un-feathered for the first couple of frames after re-appearing or does it seem like they are permanently un-feathered once they re-appear?
