### ISSUE TITLE
Access to smoothedSceneDepth values from ARKit

### ISSUE THREAD

**Issue by rdtredinnick** [Unity-Technologies/arfoundation-samples#685]
Curious if there are any plans to be able to access the underlying smoothedSceneDepth values (temporally smoothed) from ARKit.  I tried using a native plugin to adjust the ARWorldTrackingConfiguration within objective-c to modify the frameSemantics variable, but it appears that Unity ARFoundation then over-writes this at some point, as the frameSemantics variable is back to what it was the next frame.  Changing other variables on the configuration does "stick".

Perhaps another type exposed in the environment image type (Fastest/Best, etc.)?

Otherwise, if there is a suggested way to enable them via objective-c in conjunction with Unity ARFoundation that would also be helpful.

Many thanks!

**Comment by mdurand42** [comment]
> Curious if there are any plans to be able to access the underlying smoothedSceneDepth values (temporally smoothed) from ARKit. I tried using a native plugin to adjust the ARWorldTrackingConfiguration within objective-c to modify the frameSemantics variable, but it appears that Unity ARFoundation then over-writes this at some point, as the frameSemantics variable is back to what it was the next frame. Changing other variables on the configuration does "stick".
> 
> Perhaps another type exposed in the environment image type (Fastest/Best, etc.)?
> 
> Otherwise, if there is a suggested way to enable them via objective-c in conjunction with Unity ARFoundation that would also be helpful.
> 
> Many thanks!

Thanks for the request. We will discuss further internally and update the thread.

**Comment by tdmowrer** [comment]
This is available in 4.2.0-pre.8 (see "temporal smoothing" in the AROcclusionManager).
