### ISSUE TITLE
Black Screen Error(ARCore, ARFoundation) (session_manager.cc:124 ArPresto::ArSession_update failed with status -2) [Bug]

### ISSUE THREAD

**Issue by sahilpma** [Unity-Technologies/arfoundation-samples#686]
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**
I tried with other unity versions too, 2020.1.10f1, 2020.1.7f1. Tried with URP as well as default. But still same problem. 
When I use ARFoundation & ARCore of versions 2.\*.\* , it worked. But still there are errors, but playable.

**To Reproduce**
1.Build
2. See error

**Expected behavior**

**Actual behavior**
Just black screen

**Smartphone (please complete the following information):**
 - Device: Mi A3
 - OS: Android 9
 - Unity version: 2020.2.0b14
 - ARFoundation/ARCore version: 4.0.9
![image](https://user-images.githubusercontent.com/38884892/101278173-b5aa3e80-37df-11eb-9a66-478b967d1cef.png)
![image](https://user-images.githubusercontent.com/38884892/101278189-d1154980-37df-11eb-8368-be6b91715d93.png)
![image](https://user-images.githubusercontent.com/38884892/101278193-dffbfc00-37df-11eb-8bcb-3ed2e02b68a1.png)
![image](https://user-images.githubusercontent.com/38884892/101278199-eab69100-37df-11eb-88f5-66f6332a912c.png)
![image](https://user-images.githubusercontent.com/38884892/101278205-f86c1680-37df-11eb-8fb3-c3f4f3fb7cd8.png)
![image](https://user-images.githubusercontent.com/38884892/101278220-0c177d00-37e0-11eb-9c8c-ef3c1b30fbf2.png)
[com.JelloStudio.DinoAR-logcat.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/5648641/com.JelloStudio.DinoAR-logcat.txt)

**Comment by tdmowrer** [comment]
Error -2 is a [fatal error](https://github.com/google-ar/arcore-android-sdk/blob/master/libraries/include/arcore_c_api.h) in ARCore.

Are you able to reproduce the problem using this samples repo?

Can you provide the device fingerprint? That is, the output of `adb shell getprop ro.build.fingerprint`

**Comment by sahilpma** [comment]
Yes... tried that too with sample repo...
(I used 2.1.1 version of arfoundation & arcore. It was working well on my phone. But the versions that are used bt xr management in new unity installs 2020.1.\* are generating black screen)

Microsoft Windows [Version 10.0.20270.1]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\AndroidSdk\platform-tools>adb shell getprop ro.build.fingerprint
* daemon not running; starting now at tcp:5037
* daemon started successfully
google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys

C:\AndroidSdk\platform-tools>

**Comment by mdurand42** [comment]
@sahilpma Did you make certain to follow these instructions for configuring an AR Foundation project to use URP? https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/ar-camera-background-with-scriptable-render-pipeline.html

**Comment by sahilpma** [comment]
Yes...
This error is there, even if default pipeline is used.

**Comment by tdmowrer** [comment]
Is this still an issue? If so, we'll need to see your project to investigate further. Please [log a bug](https://unity3d.com/unity/qa/bug-reporting) with your project attached and post the issue number here.

**Comment by Schaggo** [comment]
I'm having the same problem with 2020.2f11 and arfoundation 4.1.1, arkit 4,1,1
