### ISSUE TITLE
Hololens 2 white screen issue

### ISSUE THREAD

**Issue by syedali1621** [Unity-Technologies/arfoundation-samples#687]
I am trying to run AR foundation samples in HoloLens 2 but when i run sample scene it display something white in hololens 2. Kindly let me know do I need to do some settings in unity for HoloLens build ?

Thank you

**Comment by mdurand42** [comment]
> I am trying to run AR foundation samples in HoloLens 2 but when i run sample scene it display something white in hololens 2. Kindly let me know do I need to do some settings in unity for HoloLens build ?
> 
> Thank you

Hello. Can you let me know what sample(s) you are attempting to run? The meshing sample should be a good choice but many of the features demonstrated in the samples will not work on Hololens due to platform limitations.

-Mike
