### ISSUE TITLE
How to update enviroment cubemap every frame

### ISSUE THREAD

**Issue by FantasyTianyu** [Unity-Technologies/arfoundation-samples#688]
When I place AREnviromentProbe automatically,it works fine,but the enviroment cubemap does not update every frame,it always update after a few moment,so I want to know how to update the enviroment cubemap in realtime?
for example,I put a sphere that can show the reflection of the enviroment,when I put my hand near the sphere,my hand will not show on the sphere immediately,it will show after a few moment.I hope it can show immediately.

**Comment by tdmowrer** [comment]
Environment probes are updated by the underlying AR framework (e.g., ARKit or ARCore). There is no way to control the frequency, and they generally do not update in realtime.

Can you explain your use case a bit more?

**Comment by FantasyTianyu** [comment]
in this video https://www.bilibili.com/video/av244949139/ you can see that the reflection on the car paint is realtime,it's made by unreal engine,I also think the enviroment probes are updated by the underlying AR framework,so if 
It can be implemented in unreal engine,I think mabe it can be implemented in unity too.
My use case also hopes to be similar to car paint, which can be update in realtime

**Comment by tdmowrer** [comment]
I don't know what that was made with (other than Unreal, of course), but ARCore & ARKit do not update in realtime, so I suspect that the demo was made using something else, or a custom solution. Do you have any more details or evidence to suggest this was using data from a specific AR framework?

**Comment by FantasyTianyu** [comment]
I guess it was made with arkit because the video's title said it was made with arkit.mabe it has some else or custom solution.
Now that I know arkit do not update in realtime, I'll find another way,thank you for your reply.
