### ISSUE TITLE
[Bug] Crash after a few minutes in AR with image tracking enabled

### ISSUE THREAD

**Issue by kjyv** [Unity-Technologies/arfoundation-samples#689]
**Describe the bug**
The attached crash report is from a crash that happens repeatably at least with ARFoundation 4.0.9 to 4.1.1 on Unity 2019.4.17 (and earlier).
Our app is starting a world tracking AR session with plane detection and image tracking enabled. After that the device is put on the table and after a few minutes of sitting there, crashes. Not enabling image tracking will not result in a crash.
[crash.zip](https://github.com/Unity-Technologies/arfoundation-samples/files/5659900/crash.zip) (in the archive is a .crash file and a screenshot of the same crash with Xcode attached). 

**Smartphone (please complete the following information):**
 - Device: iPad mini 2019 ("5th generation"), not on iPhone 6s and apparently iPad Pro 2019
 - OS: iOS 14.3
 - Unity version 2019.4.17
 - ARFoundation version 4.1.1

**Comment by tdmowrer** [comment]
Does this happen with one of the image tracking scenes from this repo? If not, please [submit a bug](https://unity3d.com/unity/qa/bug-reporting) with a project attached that reproduces the issue, and post the case ID here.

**Comment by kjyv** [comment]
It doesn't seem to happen there, but no scene has both plane detection and image tracking enabled it seems. I'm trying to put together an example where it happens.

**Comment by kjyv** [comment]
I can actually also reproduce the issue with the samples project from this repo if I add plane detection to the basic image detection scene. Please reopen this issue

**Comment by tdmowrer** [comment]
Are there any specific repro steps beyond "add an ARPlaneManager to the `BasicImageTracking` scene"? How long do I need to run it? How consistent does the issue reproduce?

**Comment by kjyv** [comment]
These are probably not relevant but to be exact: I added the plane manager to AR Session Origin, set the "AR Feathered Plane" prefab on it and set the detection mode to Horizontal. The I built the project in release mode, ran it on the iPad mini and opened the basic image tracking scene using the button. It didn't matter if I looked for a plane or an image or just left the device after pressing the button. It might take 10-20 minutes for the crash to happen, sometimes much less. Just leave it attached to the Xcode debugger.

**Comment by tdmowrer** [comment]
This appears to be a problem introduced in iOS 14. We expect it to be fixed in a future iOS release.

**Comment by kjyv** [comment]
Ok, that is unfortunate in a sense or good in another. Is that a known issue to apple (I couldn't find anything about it) or did you only notice it does not happen with <14?

**Comment by MarcoLavoro** [comment]
My app if opened more than 8 minute stop working please reopen the issue

**Comment by tdmowrer** [comment]
Please submit a bug report at https://unity3d.com/unity/qa/bug-reporting
