### ISSUE TITLE
In IPhoneX incorrect tracking plane [Bug]

### ISSUE THREAD

**Issue by mskalash** [Unity-Technologies/arfoundation-samples#691]
The plane is incorrectly recognized on the iPhoneX. Namely, after recognition, it binds and moves with the camera on other iPhones and android everything is fine.
Unity: 2019.4.10f1
Device: IPhoneX
    "com.unity.xr.arcore": "4.0.8",
    "com.unity.xr.arfoundation": "4.0.8",
    "com.unity.xr.arkit": "4.0.2",
    "com.unity.xr.arkit-face-tracking": "4.0.8",
    "com.unity.xr.arsubsystems": "4.0.1",

**Comment by mskalash** [comment]
On IPhone11 pro  iOS 14.2 this bug too

**Comment by KirillKuzyk** [comment]
May be related to this '6 degrees of freedom bug':
https://forum.unity.com/threads/af-foundation-camera-switching-not-working.972897/

**Comment by mskalash** [comment]
I'll try

**Comment by tdmowrer** [comment]
I agree; I don't think plane detection is broken on iPhoneX/11 only -- the difference between iPhoneX and iPhone11 and earlier devices is that those phones support face detection while using the rear camera and 6dof tracking while using the front camera. This is a known issue in iOS, and @KirillKuzyk has pointed out the workaround.

This issue tracker link explains the issue in more detail: https://issuetracker.unity3d.com/issues/arfoundation-mobile-gameobjects-dont-disappear-when-deactivating-them-and-switching-cameras
