### ISSUE TITLE
Reconstruction 3d object

### ISSUE THREAD

**Issue by moheydy** [Unity-Technologies/arfoundation-samples#693]
I think ARcore it now has the ability to scan a model in 3D if you  provided a solution to make reconstruction a scene with an approach like SFM its be possible to make a 3d object with RGBD and RGB, I saw a solution for this in this link:  https://github.com/bookhahn/arcoreDepthTo3D  or a solution with open3d

**Comment by tdmowrer** [comment]
ARCore does not support this (3d mesh reconstruction) as a first class API, but it does have some of the necessary pieces, e.g., depth and rgb imagery. Please see the discussion [here](https://github.com/Unity-Technologies/arfoundation-samples/issues/658#issuecomment-724287458) for more details on how you might implement this with the current API.

**Comment by tdmowrer** [comment]
Since AR Foundation only exposes existing functionality in ARCore, and this is a feature request for something in ARCore, it might be more appropriate for https://github.com/google-ar/arcore-unity-sdk.
