### ISSUE TITLE
[Bug] arfoundation causes unitywebrequest to never complete on iOS 14.2

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#694]
After resetting an arsession on iOS 14.2.x, unitywebrequests start to mysteriously get stuck

More info here:

https://forum.unity.com/threads/unitywebrequests-on-ios-sometimes-get-stuck-indefinitely-even-with-timeout-set.1012276/#post-6621598

 - Device: alle iOS devices
 - OS: 14.2.x
 - 2020.1
 - latest stable packages

**Comment by tdmowrer** [comment]
Hmm, neither ARFoundation nor ARKit XR Plugin make any web requests, and I don't see how they could impact with this functionality. Reading the thread, it sounds like a bit of a heisenbug. We will need a repro case in order to investigate further.

**Comment by nilsk123** [comment]
Thanks, gonna work some more on trying to make a repro case. What a strange issue.

**Comment by Carlo-Gezapp** [comment]
Is there any news from here? How can we help?

**Comment by tdmowrer** [comment]
> Is there any news from here? How can we help?

We will need a repro case in order to investigate further.

**Comment by nilsk123** [comment]
> > Is there any news from here? How can we help?
> 
> We will need a repro case in order to investigate further.

would it help to send you an xcode project? or do you need the unity source

**Comment by Carlo-Gezapp** [comment]
Case 1299301

**Comment by Carlo-Gezapp** [comment]
Someone says they "solved the problem by switching to HttpClient". I have not checked, it can be useful to understand.

**Comment by Carlo-Gezapp** [comment]
Is there any news from here? My Repo Helped?

**Comment by Carlo-Gezapp** [comment]
hi stale, you are a bot, i know, but are you kidding me????

**Comment by tdmowrer** [comment]
This issue is still being investigated.

**Comment by Carlo-Gezapp** [comment]
This issue is still being investigated.

**Comment by Saicopate** [comment]
The same issue here. Support needed.

**Comment by tdmowrer** [comment]
We've been able to reproduce this issue. You can track its progress here: https://issuetracker.unity3d.com/issues/ios-unitywebrequest-doesnt-work-when-using-a-14-dot-2-plus-ios-device

A workaround suggested by one of the people who reported this issue is to make a single line change to a native function called `UnityCreateWebRequestBackend`. You can find this function in the generated Xcode project by pressing Cmd+Shift+O and typing (or pasting) UnityCreateWebRequestBackend into the search box.

Immediately following the lines

```objc
webOperationQueue = [[NSOperationQueue alloc] init];
webOperationQueue.name = @"com.unity3d.WebOperationQueue";
```

Add

```objc
webOperationQueue.qualityOfService = NSQualityOfServiceUserInteractive;
```

Hope that helps.

**Comment by msftradford** [comment]
thanks @tdmowrer!

`                webOperationQueue.qualityOfService =     NSQualityOfServiceUtility;`

should also avoid the issue and might be a better choice for certain tasks, like networking

**Comment by tdmowrer** [comment]
Thanks @msftradford -- we are still investigating the proper fix, but hopefully this should unblock folks.

**Comment by tdmowrer** [comment]
Thanks for following up! Closing issue.

**Comment by mksbamford** [comment]
I still appear to be experiencing this issue in our app in unity 2019.4.28f1.

**Comment by tdmowrer** [comment]
@mksbamford This issue is considered resolved. If you are still experiencing it, please log a bug (https://unity3d.com/unity/qa/bug-reporting).
