### ISSUE TITLE
Camera passthrough image blocking rendered 3d objects.

### ISSUE THREAD

**Issue by AzadNezamdoust** [Unity-Technologies/arfoundation-samples#696]
Camera passthrough image blocking rendered 3d objects. I see only camera Camera passthrough on top of the UI in the game view. In scene view 3d models exist but camera image passthrough blocks all. It is urgent please help plugin is useless if I can't see the result.

**Comment by AzadNezamdoust** [comment]
Sorry it was for a plugin called AR foundation remote they redirected here in the page I notice it is not their repository :D

**Comment by tdmowrer** [comment]
No problem. The author probably have a support or github issues page where you can report an issue or ask for help.
