### ISSUE TITLE
[Question] AR Foundation preview editor testing (like ARCore instant preview) release Unity 2020.2?

### ISSUE THREAD

**Issue by ThimoVBE** [Unity-Technologies/arfoundation-samples#697]
Hello,

I followed the progress on the Unity AR forums about the AR Foundation playmode testing feature that is being developed for a long time now. The latest news about that feature was that it would launch in Unity 2020.2. I couldn't find any information in the release notes or in the youtube video's about this feature. I would really like to know if you can give a status update for this feature. 

Also do you know if this feature will eventually release for free? I would love to know that!

Kind regards,

**Comment by tdmowrer** [comment]
We conducted some closed alpha user studies with the current state of the feature using 2020.2, but it was not planned to release with 2020.2. We're currently iterating on the feedback we received and will continue to do so until we feel the feature is ready for a public preview.

In the meantime, there are similar solutions on the Asset Store that you may find helpful.

**Comment by ThimoVBE** [comment]
Thank you for the explanation! Do you know if this feature will be released as a free additional package or will it be included behind the MARS 600 dollar paywall?

**Comment by tdmowrer** [comment]
The ARFoundation remoting solution will be separate from MARS, and we do not have any plan to charge for it.
