### ISSUE TITLE
how can i get the timestamp of devicepose

### ISSUE THREAD

**Issue by ar4ds** [Unity-Technologies/arfoundation-samples#698]
camera pose data update each frame, we need the accuracy timestamp of the current pose, thanks

**Comment by ar4ds** [comment]
the camera object update on each frame, we need the accuracy to 0.001s, thanks

**Comment by KirillKuzyk** [comment]
https://forum.unity.com/threads/how-to-get-the-timestamp-of-the-each-pose-in-arfoundation-or-arsubsystems.1023679/#post-6631558
