### ISSUE TITLE
ARKit confidenceMap

### ISSUE THREAD

**Issue by trandzik** [Unity-Technologies/arfoundation-samples#699]
Please is it possible to access [confidenceMap](https://developer.apple.com/documentation/arkit/ardepthdata/3566295-confidencemap) (provided by ARKit) whithin arfoundation?
I have been wondering whether it would be possible to build something similar to point cloud demo from this [video](https://developer.apple.com/videos/play/wwdc2020/10611/) - at 21:27. It seems like confidenceMap is used to determine distribution of point cloud. Thanks.

**Comment by todds-unity** [comment]
See AROcclusionManager.environmentDepthConfidenceTexture for the GPU texture.
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html#UnityEngine_XR_ARFoundation_AROcclusionManager_environmentDepthConfidenceTexture

And AROcclusionManager.TryAcquireEnvironmentDepthConfidenceCpuImage to access the texture on the CPU.
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html#UnityEngine_XR_ARFoundation_AROcclusionManager_TryAcquireEnvironmentDepthConfidenceCpuImage_UnityEngine_XR_ARSubsystems_XRCpuImage__

**Comment by trandzik** [comment]
I must have missed in the docs, thank you very much.
