### ISSUE TITLE
How do I render a part of an ARPlane?

### ISSUE THREAD

**Issue by Berenice2018** [Unity-Technologies/arfoundation-samples#700]
Hi, 
I want to render just a part of an ARPlane. Let's say I got an ARPlane of 60 m2 size, but want to make a part of that plane invisible and the other part (that is within a radius of 3 m from the camera) visible, how should I achieve this, in case it is possible at all? 
Thanks in advance for any idea and input.

**Comment by tdmowrer** [comment]
You could do this in a shader by varying the alpha channel based on distance from the camera.

**Comment by Berenice2018** [comment]
Many thanks @tdmowrer for your reply. I am quite new to shader programming. I will take a look at your ARFeatheredPlaneMeshVisualizer.cs and do some research how to do that
