### ISSUE TITLE
Possibility of cloud database in image recognition

### ISSUE THREAD

**Issue by midopooler** [Unity-Technologies/arfoundation-samples#701]
Hello everyone, I am aware of Vuforia and Wikitude providing cloud database option in the image tracking. But I can't find any such option in ARfoundation or ARcore. I want to link my image database with the one I'm having on AWS S3 bucket. 

I know this is easy in vuforia but I want to reduce my costings, That's why I'm here

**Comment by tdmowrer** [comment]
ARFoundation does not have a "cloud database option", but you can download images and add them to a reference image library at runtime. See [this sample](https://github.com/Unity-Technologies/arfoundation-samples#imagetracking) for an example.

**Comment by midopooler** [comment]
I know that it is not available in ARfoundation, but anyhow I want to build it myself. Could you give me any hints/tips? @tdmowrer

**Comment by tdmowrer** [comment]
Yep, like I said, you can download images at runtime and create a new (or add to an existing) reference image library. The sample I mentioned shows how to add novel images to an existing reference image library. There is also documentation [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/tracked-image-manager.html#adding-new-reference-images-at-runtime).
