### ISSUE TITLE
Segmentation fault on iOS in AR

### ISSUE THREAD

**Issue by RLangridge** [Unity-Technologies/arfoundation-samples#702]
Hi all. Having a very inconsistent issue using AR foundation and our company iPad. Having seg faults on 
- [ARSession _sessionDidUpdateAnchors:]

Unfortunately it's so wildly inconsistent as to when it happens, it's hard to sort of pin down what may be causing this from our app. In terms of information of our app:

Using AR Foundation 4.0.9
Unity version 2020.1.14f

The use case for the app is just scanning images and creating objects where the images are. We do make the objects orbit the point where it has found the images but nothing too complex. The last crash happened after an image was scanned (we create an object at this point and give it the same position/rotation as the detected image). I've attached the crash log that came out of the iPad. 

I found one other person that had a similar issue but that was two years back:
https://forum.unity.com/threads/arkit-2-0-beta-support.534639/page-4

We were using ARAnchors, however when we started getting this error popping up I commented all of them out. It stopped for a while but it ended up popping up again. 

Not entirely certain what is causing this because it's so inconsistent in terms of when it happens. Any ideas/suggestions for this?

[crashreport.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/5713714/crashreport.txt)

**Comment by tdmowrer** [comment]
I've never seen this before. Would you please [log a bug](https://unity3d.com/unity/qa/bug-reporting) with a repro project attached and post the case ID here?

**Comment by tdmowrer** [comment]
For the benefit of future search results, here is the relevant callstack:

```
Thread 33 name:  Dispatch queue: com.unity.xr.arkit
Thread 33 Crashed:
0   libobjc.A.dylib               	0x00000001a2ad1de0 objc_release + 16
1   UnityFramework                	0x00000001057a4138 0x1049ec000 + 14385464
2   ARKitCore                     	0x00000001b78f923c __38-[ARSession _sessionDidUpdateAnchors:]_block_invoke + 124
3   libdispatch.dylib             	0x000000018ed3b298 _dispatch_call_block_and_release + 24
4   libdispatch.dylib             	0x000000018ed3c280 _dispatch_client_callout + 16
5   libdispatch.dylib             	0x000000018ece4dcc _dispatch_lane_serial_drain$VARIANT$mp + 612
6   libdispatch.dylib             	0x000000018ece58a8 _dispatch_lane_invoke$VARIANT$mp + 424
7   libdispatch.dylib             	0x000000018ecef338 _dispatch_workloop_worker_thread + 712
8   libsystem_pthread.dylib       	0x00000001d4b025a4 _pthread_wqthread + 272
9   libsystem_pthread.dylib       	0x00000001d4b05874 start_wqthread + 8
```

**Comment by RLangridge** [comment]
Yep I'll see what I can do to reproduce this in another project and then provide it. Thanks!

**Comment by ixs-koki-sonoda** [comment]
I'm facing same issue even if I use AR Foundation sample project. (Scene: Basic Image Tracking)

#### To Reproduce
Steps to reproduce the behavior:

- Clone https://github.com/Unity-Technologies/arfoundation-samples/tree/4.1
- Build and run using Xcode 13.2 and iPad OS 15.3.1 (Model: iPad 7th generation)
- After some time the app crashes.

environment:
Unity version 2021.1.13f
AR Foundation 4.1.7


> For the benefit of future search results, here is the relevant callstack:
> 
> ```
> Thread 33 name:  Dispatch queue: com.unity.xr.arkit
> Thread 33 Crashed:
> 0   libobjc.A.dylib               	0x00000001a2ad1de0 objc_release + 16
> 1   UnityFramework                	0x00000001057a4138 0x1049ec000 + 14385464
> 2   ARKitCore                     	0x00000001b78f923c __38-[ARSession _sessionDidUpdateAnchors:]_block_invoke + 124
> 3   libdispatch.dylib             	0x000000018ed3b298 _dispatch_call_block_and_release + 24
> 4   libdispatch.dylib             	0x000000018ed3c280 _dispatch_client_callout + 16
> 5   libdispatch.dylib             	0x000000018ece4dcc _dispatch_lane_serial_drain$VARIANT$mp + 612
> 6   libdispatch.dylib             	0x000000018ece58a8 _dispatch_lane_invoke$VARIANT$mp + 424
> 7   libdispatch.dylib             	0x000000018ecef338 _dispatch_workloop_worker_thread + 712
> 8   libsystem_pthread.dylib       	0x00000001d4b025a4 _pthread_wqthread + 272
> 9   libsystem_pthread.dylib       	0x00000001d4b05874 start_wqthread + 8
> ```

I got almost same call stack that was shared above.

**Comment by NJMnm** [comment]
We experienced the same crash once in a while (iOS 14.4, Unity 2021.3.27f1):

```
Thread 48 name:  Dispatch queue: com.unity.xr.arkit
Thread 48 Crashed:
0   libobjc.A.dylib               	0x00000001a6c86de0 objc_release + 16
1   UnityFramework                	0x0000000107769254 0x102800000 + 83268180
2   ARKitCore                     	0x00000001bbe740d8 __38-[ARSession _sessionDidUpdateAnchors:]_block_invoke + 124
3   libdispatch.dylib             	0x000000019251b298 _dispatch_call_block_and_release + 24
4   libdispatch.dylib             	0x000000019251c280 _dispatch_client_callout + 16
5   libdispatch.dylib             	0x00000001924c4dcc _dispatch_lane_serial_drain$VARIANT$mp + 612
6   libdispatch.dylib             	0x00000001924c58a8 _dispatch_lane_invoke$VARIANT$mp + 424
7   libdispatch.dylib             	0x00000001924cf338 _dispatch_workloop_worker_thread + 712
8   libsystem_pthread.dylib       	0x00000001da4495a4 _pthread_wqthread + 272
9   libsystem_pthread.dylib       	0x00000001da44c874 start_wqthread + 8
Thread 48 crashed with ARM Thread State (64-bit):
    x0: 0x000000012665fb50   x1: 0x0000000170ae6758   x2: 0x0000000000000018   x3: 0x0000000000000018
    x4: 0x0000000000000010   x5: 0x0000000000000010   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x000165a1e9e8f215  x11: 0x0000000000000000
   x12: 0x0000000000000001  x13: 0x0000000000000002  x14: 0x0000000000000000  x15: 0x0000000000000001
   x16: 0x00000001a6c86dd0  x17: 0x0000000025400000  x18: 0x0000000000000000  x19: 0x0000000111ea8750
   x20: 0x00000002827e2e10  x21: 0x0000000282586cc0  x22: 0x00000002827e2e10  x23: 0x0000000000000000
   x24: 0x000000028256dde0  x25: 0x0000000281ed5ad0  x26: 0x0000000282586cc0  x27: 0x0000000000000001
   x28: 0x0000000000000001   fp: 0x0000000170ae6890   lr: 0x0000000107769254
    sp: 0x0000000170ae6750   pc: 0x00000001a6c86de0 cpsr: 0x20000000
   esr: 0x92000006 (Data Abort) byte read Translation fault
```

Any solution/updates found?
