### ISSUE TITLE
How do you have a Loaded ARWorldMap also load the ARAnchors? 

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#703]
How do you have a loaded ARWorldMap also load the associated ARAnchors?

**Comment by yosun** [comment]
Hello?

**Comment by RatkoJ** [comment]
I think you have to manually save and load the anchors. Take a look at this:
https://forum.unity.com/threads/how-to-save-3d-objects-position-and-rotation-and-load-them-at-the-exact-place-using-arkit-in-unity.736424/#post-6401623

**Comment by yosun** [comment]
> https://forum.unity.com/threads/how-to-save-3d-objects-position-and-rotation-and-load-them-at-the-exact-place-using-arkit-in-unity.736424/#post-6401623

I thought the ARAnchors were saved in ARWorldMap?

See https://github.com/Unity-Technologies/arfoundation-samples/issues/640

**Comment by KirillKuzyk** [comment]
> > https://forum.unity.com/threads/how-to-save-3d-objects-position-and-rotation-and-load-them-at-the-exact-place-using-arkit-in-unity.736424/#post-6401623
> 
> I thought the ARAnchors were saved in ARWorldMap?
> 
> See #640

Anchors should be saved automatically when you serialize the ARWorldMap. Then they will be automatically restored after you call the ApplyWorldMap() function.

**Comment by yosun** [comment]
> > > https://forum.unity.com/threads/how-to-save-3d-objects-position-and-rotation-and-load-them-at-the-exact-place-using-arkit-in-unity.736424/#post-6401623
> > 
> > 
> > I thought the ARAnchors were saved in ARWorldMap?
> > See #640
> 
> Anchors should be saved automatically when you serialize the ARWorldMap. Then they will be automatically restored after you call the ApplyWorldMap() function.

So I tried that before posting her - I don't see the anchors showing up. I also notice there is no example showing how to load anchors from an ARWorldMap.

**Comment by tdmowrer** [comment]
There is a sample here: https://github.com/Unity-Technologies/arfoundation-samples#arworldmap

Note that ARKit has to localize to the saved world map, i.e., figure out how the saved world map corresponds to what it currently sees, before it can load the anchors. It is also best to ensure that the [worldMappingStatus](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.1/api/UnityEngine.XR.ARKit.ARKitSessionSubsystem.html#UnityEngine_XR_ARKit_ARKitSessionSubsystem_worldMappingStatus) is [Mapped](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.1/api/UnityEngine.XR.ARKit.ARWorldMappingStatus.html) before saving a world map.
