### ISSUE TITLE
[Bug] Periodic EXC_BAD_ACCESS on iOS when using WorldCameraWithUserFacingFaceTracking

### ISSUE THREAD

**Issue by allensanderlin** [Unity-Technologies/arfoundation-samples#707]
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.
Case 1301265

**Describe the bug**
I was getting a EXC_BAD_ACCESS periodically in a project, so I decided to just start with a fresh clone of the ar foundation samples and see if I could reproduce it.  It happens pretty consistently after a minute or so once you switch the camera to the world view.

**To Reproduce**
1. Deploy the WorldCameraWithUserFacingFaceTracking scene to iOS.
2. Verify that the face tracking is working properly with the user facing camera
3. Touch the screen to switch to the world camera
4. Verify that the box rotates with the user's head.
5. Let it run for a few minutes and you should see the EXC_BAD_ACCESS error in Xcode

**Expected behavior**
It shouldn't trigger a EXC_BAD_ACCESS when running.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.2
 - Unity version: 2020.2.0f1
 - ARFoundation version: 4.1.1

<img width="493" alt="Screen Shot 2020-12-22 at 2 44 54 PM" src="https://user-images.githubusercontent.com/8376496/102940868-269b5880-4466-11eb-9ccf-7cd6ed5f1fd7.png">
<img width="1133" alt="Screen Shot 2020-12-22 at 2 45 13 PM" src="https://user-images.githubusercontent.com/8376496/102940882-2dc26680-4466-11eb-80bf-eb21e1a45d0d.png">

**Comment by allensanderlin** [comment]
Has anyone else come across this issue?

**Comment by tdmowrer** [comment]
We have not seen this before; will investigate.

**Comment by tdmowrer** [comment]
This appears to be a problem introduced in iOS 14. We expect it to be fixed in a future iOS release.

**Comment by allensanderlin** [comment]
Is this to be fixed in a future version of the examples?  Or of the AR Foundation Package?

**Comment by tdmowrer** [comment]
This is an issue with iOS, and there is no way to address it in AR Foundation.
