### ISSUE TITLE
Toggle Extended Reality in ARfoundation Image tracking?

### ISSUE THREAD

**Issue by midopooler** [Unity-Technologies/arfoundation-samples#709]
I have 2 image targets, and I want them to be detected one by one. but when my first image target goes out of frame, the prefab stays at the position which causes trouble when I want to get my second image detected. How do I disable the first prefab once the image isn't visible anymore to the camera?

https://stackoverflow.com/questions/61457300/how-to-display-different-prefabs-with-image-tracking-in-arfoundation-with-unity

**Comment by tdmowrer** [comment]
Please see https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/tracked-image-manager.html#determining-when-an-image-is-visible
