### ISSUE TITLE
How to view game in in 2nd camera that is not the AR Camera

### ISSUE THREAD

**Issue by jameslin101** [Unity-Technologies/arfoundation-samples#710]
Hi,

I'm looking for a way to switch to a 2nd camera view while in the using the AR Camera to do body tracking with ARKit on iphone 12. Is this possible? I tried placing the 2nd camera with a higher priority but the game is still showing the view of the rear facing camera

My goal is to place the robot from ARFoundation 3DBodytracking into a game controlled by body tracking without seeing the AR Camera stuff on screen. 

Thanks!

**Comment by ti-hardikshah** [comment]
Just use layer , It should work definitely, remove a layer from the AR camera and on the second camera depth only with only one selected layer. 

Body tracking working in iOS only using AR kit.

**Comment by tdmowrer** [comment]
> My goal is to place the robot from ARFoundation 3DBodytracking into a game controlled by body tracking without seeing the AR Camera stuff on screen.

If you don't want to see the pass through camera video, simply remove the `ARCameraBackground` component from your camera.
