### ISSUE TITLE
How to load Reference Image Library from addressable system ?

### ISSUE THREAD

**Issue by zicas2000** [Unity-Technologies/arfoundation-samples#711]
Need to load ReferenceImageLibrary from addressable system so I can modify it remotely after building the app, is there any way to do that ?

**Comment by KirillKuzyk** [comment]
As far as I know, you can't modify the XRReferenceImageLibrary after the build.
To be able to add new images to ARTrackedImageManager at runtime, there is a [ScheduleAddImageJob](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.MutableRuntimeReferenceImageLibraryExtensions.html#UnityEngine_XR_ARFoundation_MutableRuntimeReferenceImageLibraryExtensions_ScheduleAddImageJob_MutableRuntimeReferenceImageLibrary_Texture2D_System_String_System_Nullable_System_Single__JobHandle_) API.

**Comment by tdmowrer** [comment]
Like @KirillKuzyk says, you can add individual images to an `XRReferenceImageLibrary` at runtime, but you cannot load a novel `XRReferenceImageLibrary`. This is because the actual image library data is built into the Player at build time.

**Comment by zicas2000** [comment]
Thanks @KirillKuzyk  and @tdmowrer
