### ISSUE TITLE
Pointcloud problems on iPhone 12 Pro

### ISSUE THREAD

**Issue by trandzik** [Unity-Technologies/arfoundation-samples#712]
I am not sure if this is a problem related to ARFoundation or directly to ARKit. Nevertheless I thought I might let you know about it. I have noticed quite a difference in point cloud precision between an older and newer iPhones. Pointcloud generated by iPhone 6S seems to be much "cleaner" than the one from latest iPhone 12 Pro.

**To Reproduce**
This could be observed when running pointcloud example (select *All*, not *Current frame*) on both models - side by side. Try to frame some object that could provide enough tracking features, move around it for a while and then step back to see the point cloud. While iPhone 6S pointcloud is quite precise with just a couple of points floating in space, pointcloud from iPhone 12 Pro is much more messy (many points seem to be just floating around).

**Expected behavior**
I would expect that iPhone 12 Pro would perform much better in terms of tracking features precision.

**Actual behavior**
Tracking features seem to be incorrectly placed in camera frustrum producing pointcloud with many points floating in space.
Feel free to take a look at attached video to see what I mean. I have tried to extract color for each point in pointcloud in order to better visualize it. Both point clouds show the same scene, even thought it isn't perfectly aligned. I have performed roughly the same movement with both phones. (Video starts with pointcloud from iPhone 6S {which is very precise} and then switches to iPhone 12 Pro.)
https://drive.protonmail.com/urls/XJKPE7FF7W#toJMvTv13aN5

 - Device: iPhone 12 Pro
 - OS: iOS 14.3
 - Unity version: 2020.2.1f1
 - ARFoundation version: 4.1.1

**Comment by tdmowrer** [comment]
As you suggest, it is not surprising that there is a difference between devices with a LiDAR sensor and those without. However, I'm not really sure what your video is demonstrating. In our tests, the results are comparable between an iPhone 6 and 12, with the 12 generally providing a few more feature points.

Any differences are likely to be due to the device; AR Foundation just gets an array of points from ARKit.

**Comment by trandzik** [comment]
Video demonstrates two point clouds made by capturing points (tracking features) from both devices. Maybe it is hard to see the problem since I haven't attached picture of actual space they were framing - I might do that to better illustrate the "ground truth".

I mean even without this kind of visualization it is obvious that there is something wrong with the tracking features on new iPhone. 
There are many points just floating around - not tracking any actual feature in the image (causing the mess in accumulated point cloud).

I will do a better a visualization to demonstrate there is clearly something wrong. I am not saying it is problem with AR Foundation, maybe core of the problem is in ARKit itself.

Nevertheless it just doesn't seem right. How come that old camera system does such a good job and the new one (even with LIDAR) performs so "badly" in terms of tracking features?

**Comment by trandzik** [comment]
I have tried to create a better visualization of described problem by running screen capture on both phones while framing the same objects.
This way you can clearly observe the high amount of points floating in space (above objects) on iPhone 12 Pro. Even though the same thing happens also on iPhone 6S, there definitely aren't as many incorrectly placed points as on iPhone 12 Pro.

Please feel free to close this issue if you think this isn't related to AR Foundation. I just wanted to let you know this is happening in case there could be something wrong with the way AR Foundation is reading the array of points from ARKit. Thanks.

https://drive.protonmail.com/urls/PPAVW3FQE8#n1z7DgbGtSbx
