### ISSUE TITLE
Hollow effect in Image Tracking

### ISSUE THREAD

**Issue by hami159** [Unity-Technologies/arfoundation-samples#713]
I was very curious to see if anyone has an idea on how Google managed to pull off the effect featured in the showcase video in their ARCore documentation for Image Tracking?

Tried to replicate it but could not manage... Is such an effect actually feasible in terms of Unity's and AR Foundation's capabilities? 

https://developers.google.com/ar/develop/unity-arf/augmented-images

Thanks!

**Comment by ti-hardikshah** [comment]
It's just depth buffer shader and a little animation. That can be achieved using stencil shader

**Comment by hami159** [comment]
Really interesting, thank you for sharing! 👍
