### ISSUE TITLE
ARFoundation and ARCore compatibility

### ISSUE THREAD

**Issue by mpyrk** [Unity-Technologies/arfoundation-samples#714]
Hello!
I have recently started to do some tutorials on AR in Unity and have found two major problems while completing the "AR Hello World" tut from Unity's website. First of all, the tutorial doesn't instruct you to install ARFoundation (so I did not do it) but without I do not have any XR options in the hierarchy window other than "Convert Main Camera to XR Rig". On the other hand, when I install the ARFoundation it conflicts with ARCore and doesn't allow me to build any apps. Unchecking the ARCore results in the app not using my phone's camera for the build. I am getting really confused about all that, and wanted to know if there is some way to get those XR options in ARCore without Foundation, or to get Foundation to use the camera/work properly with ARCore? 
All of the feedback is greatly appreciated!
PS. Below are some screenshots from the errors that the editor throws at me with both Foundation and ARCore. 
![image](https://user-images.githubusercontent.com/64896564/103319822-6bf5f200-4a33-11eb-99c4-c8aab3adee8a.png)

**Comment by ti-hardikshah** [comment]
Little confused by your question !! what do you want to do? 
AR Foundation is a Framework that combines multi-platform SDK into one code. 
AR core and AR kit both working fine.

**Comment by tdmowrer** [comment]
Hmm, it does seem like that tutorial needs some work. Thanks for pointing this out!

As the error message says, you should not check the "ARCore Supported" checkbox in Player Settings (this is for [Google's plugin](https://github.com/google-ar/arcore-unity-sdk), which is separate and not compatible with ARFoundation).

Have you tried the samples in this repository? They should work out-of-the-box without any additional setup.

**Comment by mpyrk** [comment]
I haven't actually, and I have to do that! I do realize, that they are separate, but just using one or the other doesn't yield a working app for my smartphone. Without the AR Foundation I have no options for creating AR cameras and such. But using only foundation doesn't use my camera when I open the app on the phone. Using both makes the error appear. I will try some resources from this repository and will try to figure it out somehow! Thanks!

**Comment by tdmowrer** [comment]
Google's ARCore SDK for Unity is a separate plugin that cannot be combined with AR Foundation. To use AR Foundation, you need to completely remove these folders from your project: https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets.

If you clone this samples repository, you should be able to build the samples for Android without modification.

**Comment by Dweeh** [comment]
@tdmowrer Can you elaborate on that?
On the Unity page "Setting Up AR Foundation" it says that I need ARCore?

**Comment by tdmowrer** [comment]
You need the ARCore XR Plugin, which is a Unity package (instructions for installing it are in the tutorial). You should not check the "ARCore Supported" checkbox.

**Comment by Dweeh** [comment]
Sorry - my head is spinning...
 Google's ARCore SDK for Unity is one plugin
 and ARCore XR Plugin is something else?

**Comment by tdmowrer** [comment]
Yes, exactly. Google makes the "ARCore SDK for Unity" which does not use AR Foundation. It is a standalone plugin they maintain.

Unity provides the ARCore XR Plugin, which works with AR Foundation and is provided as a package.

**Comment by Dweeh** [comment]
Oh...   
That might save me some headache.
Thanks a lot!  :)

**Comment by Prashant29** [comment]
Hi @tdmowrer,

I have one project in ARCore (ARCore SDK in Unity) and now I wanted to convert it to ARfoundation ARcore project. How Can I?
I do not have prior knowledge of ARCore, But I'm practicing AR Foundation. Please help me out.

Thanks

**Comment by Prashant29** [comment]
let me ask Specific.

I don't know how to convert the below code:

1. if(Session.Status != SessionStatus.Tracking)

2.  if (planeGen.m_NewPlanes.Count > 0) {
				DetectedPlane first= planeGen.m_NewPlanes [0];
} // Here planeGen is DetectedPlaneGenerator 

3. using (var image = Frame.CameraImage.AcquireCameraImageBytes())


Can you help me, if there is any documentation or demo kind for Migration process?

**Comment by tdmowrer** [comment]
@Prashant29 This closed issue seems unrelated. Could you open a new issue for your questions, please?

**Comment by Prashant29** [comment]
Thanks for your Comment and guidance for new issue @tdmowrer,

Can you please draw your attention here: https://github.com/Unity-Technologies/arfoundation-samples/issues/781
