### ISSUE TITLE
face skin color

### ISSUE THREAD

**Issue by shacharoz** [Unity-Technologies/arfoundation-samples#715]
**Is your feature request related to a problem? Please describe.**
when adding items on top of the user's head, I am dependant of their haircut. i would like to paint over it. 

**Describe the solution you'd like**
if I could get the color of the face skin I could cover the head scalp with that color, in order to hide the existing hair while inserting new hair on top of the user's. this will allow more immersiveness for hair style simulators.

**Comment by tdmowrer** [comment]
The underlying AR SDKs (e.g., ARCore/ARKit) do not provide an estimate for skin color. I suspect this would be very difficult to convincingly hide the user's hair (i.e., make them appear bald).

**Comment by shacharoz** [comment]
yeah... thanks :)
i was just playing with face tracking features for the past week, and now I agree with you on that...

perhaps what I could do is to "remove" the head entirely, replace it with a 3d model, and leave only the face mesh itself with the AR Face Mesh Visualizer that has the face texture. but this is still not realistic enough (since i can sense the delay in the video).

the practical solution I have is to ask the user to pull the hair backwards to a pony tail... that's the only thing I guess I can do now.

**Comment by kyrollos356** [comment]
ARCore is very weak, and ARKit needs iphone is there any ar for skin and hair recognition that works with unity
