### ISSUE TITLE
Image tracking 

### ISSUE THREAD

**Issue by Pieprima22** [Unity-Technologies/arfoundation-samples#717]
From the the PrefabImagePairManager.cs, if i want one prefab to be appear at a time, how do I hide the one that is not being tracked and unhide it when the image is being tracked?

**Comment by tdmowrer** [comment]
You can hide any GameObject by setting it to inactive. See [GameObject.SetActive](https://docs.unity3d.com/ScriptReference/GameObject.SetActive.html). You could do this for any instantiated GameObject associated with an ARTrackedImage whose [trackingState](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackable-2.html#UnityEngine_XR_ARFoundation_ARTrackable_2_trackingState) not Tracked.

**Comment by Pieprima22** [comment]
![1609918007679@2x](https://user-images.githubusercontent.com/77018314/103744016-9d704e00-502f-11eb-82d9-aba24c66fe86.jpg)
It shows this error:
![messageImage_1609919032210](https://user-images.githubusercontent.com/77018314/103744077-bb3db300-502f-11eb-8743-1004a51bccbd.jpg)

**Comment by Pieprima22** [comment]
I found the solution thank you so much for your help

**Comment by newyellow** [comment]
It seems to me that the way AR Foundation manages image trackers is kinda awkward. The best thing about Unity is you can manage content visually, which AR Foundation seemed not support.

So I'm here to say I had developed a small tool to improve the workflow of Tracker Images:
https://github.com/newyellow/arfoundation-helper

Maybe @Pieprima22 or other unity official developers would be interested?

**Comment by pinnakkkk** [comment]
> I found the solution thank you so much for your help

could u please tell me how did u fix it? I'm facing the same issue. seems like event.update gets stuck in the loop even so cant really find a way to disable other gameobjects except the current one
