### ISSUE TITLE
PlaceOnPlane

### ISSUE THREAD

**Issue by Proteanindustries** [Unity-Technologies/arfoundation-samples#718]
**Unity bug report case number**
Case 1303952

https://user-images.githubusercontent.com/73073621/103730050-d8cb3800-4faf-11eb-9863-071fc91d51ef.mp4

**Describe the bug**
The PlaceOnPlane & PlaceOnPlane Editor are acting as raycast image recognition elements. The raycaster is not placing the selected GameObject on the plane, it is projecting it as if it were a recognized image. 

**To Reproduce**
1. Go to Configure the Place On Plane component to the AR Session Origin GameObject
2. Click on Place On Plane 
3. Play the Scene in the game window and attempt to click/touch the object onto the plane. 
4. See error where the object does not generate, and only generates when scrolling over the plane or clicking/tapping and dragging the cursor over the plane.

https://user-images.githubusercontent.com/73073621/103729248-057e5000-4fae-11eb-96a5-d5ae11888519.mp4

**Expected behavior**
Utilize the PlaceOnPlane Editor to generate an object onto an AR Session Plane. 

**Actual behavior**
The PlaceonPlane Editor acts as an image recognition raycaster and only deploys the Gameobject when the trackpad/finger cursor moves over the collider of the plane. 

**Smartphone (please complete the following information):**
 - Device: Kyocera Dual Force Pro
 - OS: Android Api 25 / Windows
 - Unity version 2019.4.15f1
 - ARFoundation version 2.1.10

**Comment by tdmowrer** [comment]
This doesn't sound like a feature of ARFoundation or a sample in this repo. Are you using another package or asset store asset?

**Comment by Proteanindustries** [comment]
I got it as a download from classes with the sample package, it seems to be from KairosXR. Sorry for the confusion.
