### ISSUE TITLE
[Bug] URP with ARFoundation-ARKit in Unity2020.2.1f1 metal error!

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#719]
**Describe the bug**
Using ARFoundation ARKit with URP 10.2.2
Camera is black and XCode log
```log
metal: Error creating pipeline state (Unlit/ARKitBackground): depthAttachmentPixelFormat is not valid and shader writes to depth
(null)You can only call cameraDepthTarget inside the scope of a ScriptableRenderPass. Otherwise the pipeline camera target texture might have not been created or might have already been disposed.
UnityEngine.Rendering.Universal.ScriptableRenderer:get_cameraDepthTarget()
UnityEngine.XR.ARFoundation.ARBackgroundRendererFeature:AddRenderPasses(ScriptableRenderer, RenderingData&)
UnityEngine.Rendering.Universal.ScriptableRenderer:AddRenderPasses(RenderingData&)
UnityEngine.Rendering.Universal.ForwardRenderer:Setup(ScriptableRenderContext, RenderingData&)
UnityEngine.Rendering.Universal.UniversalRenderPipeline:RenderSingleCamera(ScriptableRenderContext, CameraData, Boolean)
UnityEngine.Rendering.Universal.UniversalRenderPipeline:RenderCameraStack(ScriptableRenderContext, Camera)
UnityEngine.Rendering.Universal.UniversalRenderPipeline:Render(ScriptableRenderContext, Camera[])
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, List`1)
```

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 14.3
 - Unity version:Unity2020.2.1f1
 - ARFoundation version:4.1.1
 - URP version:10.2.2

**Comment by tdmowrer** [comment]
The message you posted is just a warning and should not cause a black screen. We will fix the warning (see [issue tracker](https://issuetracker.unity3d.com/issues/urp-ar-foundation-warning-message-regarding-cameradepthtarget-with-urp-slash-ar-foundation-projects)) but that is not the issue here.

Have you followed [these steps](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/ar-camera-background-with-scriptable-render-pipeline.html) to setup ARFoundation for URP?

**Comment by weacw** [comment]
> The message you posted is just a warning and should not cause a black screen. We will fix the warning (see [issue tracker](https://issuetracker.unity3d.com/issues/urp-ar-foundation-warning-message-regarding-cameradepthtarget-with-urp-slash-ar-foundation-projects)) but that is not the issue here.
> 
> Have you followed [these steps](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/ar-camera-background-with-scriptable-render-pipeline.html) to setup ARFoundation for URP?

Thank you for your reply!

It works normally when I return to version 2019. Use 2029.2.1 to black screens!

Does URP need more memory than builtin ? I'm testing AR Foundation on URP with UAAL, and the memory is maintained at about 400m when I unload  the unity (Used ARSession, etc.)

**Comment by Schaggo** [comment]
Same problem here. 2019.x works. 2020.1f1 black screen.

**Comment by todds-unity** [comment]
The "cameraDepthTarget" is a known warning message that appears with URP 10.2.
https://issuetracker.unity3d.com/issues/urp-ar-foundation-warning-message-regarding-cameradepthtarget-with-urp-slash-ar-foundation-projects

This is just a warning message and does not affect rendering, apart from the per-frame warning message.


The "Error creating pipeline state" message is a separate issue and most likely the source of your problem. Are you trying to render the background to a separate RenderTexture in your project?

**Comment by weacw** [comment]
> The "cameraDepthTarget" is a known warning message that appears with URP 10.2.
> https://issuetracker.unity3d.com/issues/urp-ar-foundation-warning-message-regarding-cameradepthtarget-with-urp-slash-ar-foundation-projects
> 
> This is just a warning message and does not affect rendering, apart from the per-frame warning message.
> 
> The "Error creating pipeline state" message is a separate issue and most likely the source of your problem. Are you trying to render the background to a separate RenderTexture in your project?

Thank you for your reply.

`render the background to a separate RenderTexture in your project`
No. I m used default setting in urp. It's working on Unity 2019.4.xf1, Not working in 2020.x. It's `Black Screen`!

**Comment by tdmowrer** [comment]
We have not been able to reproduce this issue. Please [log a bug](https://unity3d.com/unity/qa/bug-reporting) with an project that reproduces the issue and post the case ID here.

**Comment by weacw** [comment]
I seem to have discovered the cause of the black screen.
I use `Camera stacking`

```C#
uiCamera = GameObject.FindWithTag(ConstKey.CONST_UI_CAMERA_TAG).GetComponent<Camera>();
var tmp_MainCamera = Camera.main;
var tmp_MainAdditionalCameraData = tmp_MainCamera.GetUniversalAdditionalCameraData();
tmp_MainAdditionalCameraData.cameraStack.Add(uiCamera);
```

**Comment by creativewax** [comment]
I to have the same problem with the camera stacks, why would this cause such an issue?

**Comment by creativewax** [comment]
just worked out how to solve my problem, basically I wanted two cameras, one for UI and one for the AR Stuff, the Overlay camera stack causes the black screen problem, since I am new to URP I have just noticed you can set the priority flag, on setting the UI camera back to base and setting priority to 1 they both now render fine

**Comment by weacw** [comment]
> just worked out how to solve my problem, basically I wanted two cameras, one for UI and one for the AR Stuff, the Overlay camera stack causes the black screen problem, since I am new to URP I have just noticed you can set the priority flag, on setting the UI camera back to base and setting priority to 1 they both now render fine

Thank you! I returned to the 2019 version. 2020 is not yet stable

**Comment by creativewax** [comment]
actually this only solved it in the editor, building for iOS shows the same problem with multiple cameras

**Comment by natzke** [comment]
That's unfortunate. Heading back to 2019 from 2020.3.2 (LTS). Even as a Salient error I was still getting most of what I needed in 2019. Will check back with the next update.

**Comment by sebastianewak** [comment]
> That's unfortunate. Heading back to 2019 from 2020.3.2 (LTS). Even as a Salient error I was still getting most of what I needed in 2019. Will check back with the next update.

I had the same issue in Unity 2020.3.1f1. Updating AR Foundation (4.0.12 -> 4.1.7) and URP (10.3.2 -> 10.4.0) solved the black screen problem.

However, a new issue popped up as the stacked cameras' perspective didn't match the AR camera, even though they had the same settings in the editor.

It turns out the AR camera's settings are updated at runtime, possibly once the session is initialized. Manually setting FOV of the stacked cameras once the AR session state changes to SessionTracking helped and now the stacked cameras work as expected.

**Comment by tdmowrer** [comment]
We just published 4.1.7, which should fix the issue. Looks like it did for @sebastianewak :)

**Comment by mksbamford** [comment]
This is still broken in 2019.4.19f1

**Comment by tdmowrer** [comment]
> This is still broken in 2019.4.19f1, AR Foundation 4.1.7, URP 7.5.3

This issue was specific to URP 10+, so it sounds like you are seeing a different, possibly unrelated issue. Please file a bug by following the instructions at https://unity3d.com/unity/qa/bug-reporting.
