### ISSUE TITLE
How to change plane tracking shape ?

### ISSUE THREAD

**Issue by ti-hardikshah** [Unity-Technologies/arfoundation-samples#721]
How do I...
Hello, Anyone knows how to change the plane tracking shape? right now it detects and generates plane asymmetric shapes.  I need a Complete Square or rectangle. is there any solution ??

**Comment by tdmowrer** [comment]
You can use a different plane prefab. For example, you could use a scaled cube or rectangular plane. An ARPlane has a [size](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARPlane.html#UnityEngine_XR_ARFoundation_ARPlane_size) property as well as the convex hull geometry.

**Comment by ti-hardikshah** [comment]
Still not figure out the way !! Is there any example or working demo that will help much faster?
I had tried to change plane mesh type to plane but no luck !!
