### ISSUE TITLE
[Bug] Flip arcamerabackground on some devices such as samsung galaxy note 8

### ISSUE THREAD

**Issue by justinduynguyen** [Unity-Technologies/arfoundation-samples#722]
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13]
 - Unity version
 - ARFoundation version

**Comment by tdmowrer** [comment]
Closing as this issue looks like it was created by mistake.
