### ISSUE TITLE
[Bug] Meshing sample does not work with the Universal Render Pipeline (URP)

### ISSUE THREAD

**Issue by SamSeidenberg** [Unity-Technologies/arfoundation-samples#723]
**Unity bug report case number**
Case 1304446
ARFoundation meshing does not work with URP.

1. What happened

Meshing examples for ARFoundation/ARKit do not work with the URP.

The attached project is simply the ARFoundation Samples found here: https://github.com/Unity-Technologies/arfoundation-samples

I updated the project to 2020.2.0f1 (from 2020.1.13f1, the source version) and built. The meshing examples worked fine on my iPhone 12 Pro Max.

I then updated to the Universal Rendering Pipeline and configured for ARFoundation using the steps found here: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html

The project built successfully to my iPhone, but the meshing examples no longer worked (no meshes appeared over scanned areas). Additionally, this warning is continually logged in Xcode:

----------
You can only call cameraDepthTarget inside the scope of a ScriptableRenderPass. Otherwise the pipeline camera target texture might have not been created or might have already been disposed.
UnityEngine.Rendering.Universal.ScriptableRenderer:get_cameraDepthTarget()
UnityEngine.XR.ARFoundation.ARBackgroundRendererFeature:AddRenderPasses(ScriptableRenderer, RenderingData&)
UnityEngine.Rendering.Universal.ScriptableRenderer:AddRenderPasses(RenderingData&)
UnityEngine.Rendering.Universal.ForwardRenderer:Setup(ScriptableRenderContext, RenderingData&)
UnityEngine.Rendering.Universal.UniversalRenderPipeline:RenderSingleCamera(ScriptableRenderContext, CameraData, Boolean)
UnityEngine.Rendering.Universal.UniversalRenderPipeline:RenderCameraStack(ScriptableRenderContext, Camera)
UnityEngine.Rendering.Universal.UniversalRenderPipeline:Render(ScriptableRenderContext, Camera[])
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, List`1)
----------

I have tried this with 2020.2.1f1 and 2021.1.0b1 as well, same issue. Also, it is not possible to follow the URP/ARFoundation configuration process described in the documentation in version 2020.2.1f1—the scriptable object properties for the URP assets are much different than version 2020.2.0f1.

**Comment by tdmowrer** [comment]
> Meshing examples for ARFoundation/ARKit do not work with the URP.

The meshing examples use a legacy render pipeline shader that is not compatible with URP. The meshing feature still works, but you will need to use a prefab with a URP-supported shader to see the result.

> Also, it is not possible to follow the URP/ARFoundation configuration process described in the documentation in version 2020.2.1f1—the scriptable object properties for the URP assets are much different than version 2020.2.0f1.

Thanks for pointing this out. We will look into it.

**Comment by nikitashokhov** [comment]
AR Foundation, could you please just create a NormalOverlay shader for meshing for URP? Everyone is going to use it anyway. I need this right now.
