### ISSUE TITLE
Update Environment Depth Image in iOS.

### ISSUE THREAD

**Issue by MTL2097** [Unity-Technologies/arfoundation-samples#725]
Hi everyone!! 
Well now I´m testing depth texture information to get the distance from the Pixel located in the middle of the Screen to me. All testing goes well in Android when compiling the APK in Unity but unfortunatelly, I don´t have the same behaviour in iOS. 
Does somebody knows if I have to do an extra configuration in Xcode to get the Depth texture works? 
The method I´m using is : TryAcquireEnvironmentDepthCpuImage. 
Thanks in advance for your answers!!.

**Comment by tdmowrer** [comment]
Environment depth on iOS requires a device with a LiDAR sensor. What device are you using?
