### ISSUE TITLE
CpuImages sample question

### ISSUE THREAD

**Issue by astaikos316** [Unity-Technologies/arfoundation-samples#730]
I am having trouble with figuring out why when using the CpuImages sample project, i do not see holograms I place on the screen in the RawImage object when getting the XRCPUImage out. I added some objects from the SimpleAR sample to be able to place cubes, but all I see on the RawImage is the non-augmented camera feed.  I am running Unity 2019.4.8f1.

**Comment by tdmowrer** [comment]
The purpose of the XRCpuImage is to provide you with access to the raw camera texture pixels. It does not capture anything rendered by Unity. Can you elaborate on your use case?

**Comment by astaikos316** [comment]
I am trying to basically be able to mimick a Mixed Reality Capture so I can send a video stream of the ARCamera with rendered objects to a remote PC using WebRTC. I am using Mixed-Reality WebRTC and i have to get to be able to grab the video via raw byte data to transmit the video

**Comment by tdmowrer** [comment]
If you need rendered objects, then the XRCpuImage does not satisfy your use case. If you want to get the pixels rendered on screen, have a look at [ReadPixels](https://docs.unity3d.com/ScriptReference/Texture2D.ReadPixels.html). Note you can also render a camera to a [RenderTexture](https://docs.unity3d.com/ScriptReference/RenderTexture.html).
