### ISSUE TITLE
How to proper light up an FBX in ARFoundation ?

### ISSUE THREAD

**Issue by alexs7** [Unity-Technologies/arfoundation-samples#733]
I am exporting a FBX model (and a DAE model) from Sketchup and the model looks fine in the Scene Viewer.
The moment I render it in AR on a tracked image it gets really dark.

Do I have to code anything extra related to light ?

Thanks

**Comment by tdmowrer** [comment]
This doesn't sound like it is related to AR. What happens if you place the model in an otherwise empty scene and build the Player (that is, without AR enabled)?

**Comment by alexs7** [comment]
I think I got it. I added a bunch of directional lights and the model lights up now. But I was wondering if there is an ambient solution. The closest thing I could find was a light called "point light"

**Comment by tdmowrer** [comment]
> But I was wondering if there is an ambient light solution.

Yes; please see https://docs.unity3d.com/Manual/lighting-ambient-light.html

**Comment by alexs7** [comment]
Ok great!
