### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Immerence** [Unity-Technologies/arfoundation-samples#734]
**Unity bug report case number**
Case 1312541

**Describe the bug**
Unity 2020.2.1f1, AR Foundation Package 4.0.10, ARKit XR Plugin 4.0.10 & Universal RP 10.2.2 throws following warning:

"No active UnityEngine.XR.ARSubsystems.XRSessionSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.XR.ARFoundation.ARSession:OnEnable () (at Library/PackageCache/com.unity.xr.arfoundation@4.0.10/Runtime/AR/ARSession.cs:344)"

ARKit is checked in the XR Plug-in Management.

**To Reproduce**
Start a new project. 

Switch platform to iOS.

From package manager install the following:

-AR Foundation Package 4.0.10
-ARKit XR Plugin 4.0.10
-Universal RP 10.2.2 

Open "Project Settings" & go to XR Plug-in Management. 

Under Plug-in Providers check the "ARKit" box. Exit settings.

Create a new Universal Render Pipeline Asset, 

"Create > Rendering > Universal Render Pipeline > Pipeline Asset (Forward Renderer)".

Two assets is created. "UniversalRenderPipelineAsset" & "UniversalRenderPipelineAsset_Renderer".

Go to "UniversalRenderPipelineAsset_Renderer" & click "Add Renderer Feature" > "New AR Background Renderer Feature".

Now go to "Project Settings", find the Graphics tab & add the Pipeline Asset you created before, "UniversalRenderPipelineAsset". Exit settings.

Remove the Main Camera in the Sample Scene. 

Right-click & add "AR Session Origin" & " AR Session" from the XR menu.

Press "Play". See warning:
No active UnityEngine.XR.ARSubsystems.XRSessionSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.XR.ARFoundation.ARSession:OnEnable () (at Library/PackageCache/com.unity.xr.arfoundation@4.0.10/Runtime/AR/ARSession.cs:344)

**Expected behaviour**
AR development with AR Foundation has not thrown this warning before using URP.

**Actual behaviour**
Editor throws a warning.

**Smartphone (please complete the following information):**
 - Device: Macbook Pro
 - OS: macOS Mojave (10.14.6)
 - Unity version 2020.2.1f1
 - ARFoundation version 4.0.10

**Comment by tdmowrer** [comment]
This is the expected behavior. AR Foundation does not provide an implementation of the XRSessionSubsystem that runs in the Editor in Play Mode, so the warning is correct.

**Comment by Immerence** [comment]
I figured, but had a hard time finding documentation regarding the warning, so no way of verifying for sure. For extra polish, one could implement exceptions in Play Mode. But some user might need the prompt.

**Comment by Chico3001** [comment]
What about a clarification? for months i had been searching the cause of this warning (with a hunch that this was only on editor) until now. if you change the warning to something like this:

No active UnityEngine.XR.ARSubsystems.XRSessionSubsystem is available **when running on editor**

i think it can be more clear and more noobs like me will suffer less when testing...

Just a suggestion

**Comment by tdmowrer** [comment]
That isn't true, though; there are session subsystems available for the editor (you can write one yourself for testing, for example). And if you were to build a Player, say, for iOS, but forgot to install the ARKit XR Plugin package, then you would want this warning to appear in the Xcode console (this is the original motivation for this warning message).

**Comment by ChrisJRock** [comment]
You can still add clarification like "(if you are running in the Unity Editor without a custom subsystem, this is expected)". Improving the log requires less effort than replying to this thread.

At least I found this fairly quickly. Sounds like it cost others a lot of time.

**Comment by cecarlsen** [comment]
> This is the expected behavior.

Setting up a plain AR project should not prompt warnings. I've wasted hours discovering the cause of these warnings, instead of being productive. What a horrible user experience.

"Please ensure that a valid loader configuration exists in the XR project settings."
The warning is prompting me to take action when no action needs to be taken.

**Comment by LattVines** [comment]
Agreed. Needs better wording. I'm hunting down a different problem that only occurs on the device and this message in the Unity editor appears to have led me astray.

**Comment by cc-michael-x** [comment]
I fell into the same trap as well. For beginners, this warnings really are confusing.

**Comment by KirillKuzyk** [comment]
> That isn't true, though; there could be a session subsystem available in the Editor

And there is one :)
I developed the [AR Foundation Remote](https://assetstore.unity.com/packages/tools/utilities/ar-foundation-editor-remote-168773) plugin that supports testing AR Foundation in the Editor.


I agree with other commentators that the wording of this warning can be improved to indicate that ARKit/ARCore providers are designed to work only on real AR devices.
