### ISSUE TITLE
WorldCameraWithUserFacingFaceTracking on IPad Pro 12.9[Bug] 

### ISSUE THREAD

**Issue by nara6500** [Unity-Technologies/arfoundation-samples#737]
I wanted to test the WorldCameraWithUserFacingFaceTracking Scene on my iPad Pro 12.9. 
By using the WorldCamera the FaceControlledCube appeared, but it stops rotating and the Error  "Face tracking in world facing camera mode is not supported"  appears on Screen.

1. Deploy the WorldCameraWithUserFacingFaceTracking scene to iOS.
2. Verify that the face tracking is working properly with the user facing camera
3. Touch the screen to switch to the world camera
4. See the error "Face tracking in world facing camera mode is not supported" and the FaceControlledCube doesn't move.

In my opinion the Cupe shout show the Rotation of the FaceTracking of my head. 
I tried it also with a iPhone XR (iOS 14.3) and there it works pretty well. But I need it also on my iPad!

 - Device: iPad Pro 12.9 (4. Generation)
 - OS: iOS 14.3 and iOS 14.4
 - Unity version: 2020.2.1f1
 - ARFoundation version: 4.1.3

**Comment by nara6500** [comment]
It seems like iPad Pro 2020 has a hardware limitation... 

https://developer.apple.com/forums/thread/131006

Can you write this fact in your readme?

**Comment by tdmowrer** [comment]
The hardware requirements are listed in the README for this sample:

> This feature requires a device with a TrueDepth camera and an A12 bionic chip running iOS 13.

**Comment by nara6500** [comment]
IPad Pro 2020 does have exactly this hardware (https://support.apple.com/kb/SP815?viewlocale=en_US&locale=de_DE)

**Comment by tdmowrer** [comment]
Ah, the iPad Pro 2020 is a bit of a special case. Even though it has an A12 bionic chip, it does not support this particular feature. The check for this that we use in AR Foundation is [ARFaceTrackingConfiguration.supportsWorldTracking](https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration/3175412-supportsworldtracking?language=objc).

**Comment by amir989** [comment]
I have the same problem on my iPad pro too. My concern is that if the same problem happens to the new iPhone pros with LiDAR as well? I have an iPhone XS which works fine with this feature. Can someone please confirm if this feature works on  iPhone pro with LiDAR as well? 

Thanks
