### ISSUE TITLE
AR Foundation with PC Webcam

### ISSUE THREAD

**Issue by DrouSoft** [Unity-Technologies/arfoundation-samples#739]
Is ti possible to develop AR application with  AR Foundation  using pc webcam ?

**Comment by tdmowrer** [comment]
Not out-of-the-box, but you could create a plugin compatible with AR Foundation if have a solution that implements some AR features using a web cam (e.g., using [OpenCV](https://opencv.org/)). It would involve implementing one or more subsystems, e.g., the [XRSessionSubsystem](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.XRSessionSubsystem.html) and [XRCameraSubsystem](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.XRCameraSubsystem.html) depending on what you want to do.
