### ISSUE TITLE
[Bug]Since update to Android 11, app requests the latest "Google Play Services for AR" version, but I already have it

### ISSUE THREAD

**Issue by paBlury** [Unity-Technologies/arfoundation-samples#740]
**Unity bug report case number**
1313471

**Describe the bug**
After updating my phone to Android 11 I cannot use the Augmented Reality functionalities on an app I created using Unity and AR foundation. I get a message indicating that I have to update to the latest version of Google Play Services for AR, but I already have the latest version. If I ignore the message the screen stays black and the video is not showing. The app seems to be working appart from that, since I implemented functionality for the "back" button and that works. It´s either not reading the camera or not displaying the camera image.

Using Unity 2019.3.12f1, ARFoundation 3.1.3. Testing on a Xiaomi A3. The app worked fine until I updated my phone to Android 11 last week. It works on phones with Android 10.

**To Reproduce**
Launch an app created with ARFoundation 3.1.3 on an Android 11 phone.

**Expected behavior**
When using the AR functionality, the camera image should be showing in the background.

**Actual behavior**
No camera image on the background. Just a black screen.

**Smartphone (please complete the following information):**
 - Device: Xiaomi A3
 - OS: Android 11
 - Unity version:  2019.3.12f1
 - ARFoundation version: 3.1.3

**Comment by tdmowrer** [comment]
> I get a message indicating that I have to update to the latest version of Google Play Services for AR, but I already have the latest version. If I ignore the message the screen stays black and the video is not showing.

What happens if you don't ignore the message and click the button to update?

**Comment by paBlury** [comment]
I get taken to Google Play Store, to the "Google Play Services for AR" app, but there´s not a button for updating. I´ve checked and I have the latest version of the services. Just in case I deleted all the installed versions and got them again, but no luck.

**Comment by tdmowrer** [comment]
The [ARCore XR Plugin package](https://docs.unity3d.com/Packages/com.unity.xr.arcore@3.1) version 3.1.3 was built with an earlier version of the ARCore SDK that did not support Android 11. The latest patch release (3.1.10) was built with a later version that does support Android 11. I suspect this may be the issue; could you try updating to 3.1.10? This is just a patch release, so there are no API changes.

**Comment by paBlury** [comment]
Sorry, my package manager´s highest 3.1.X version is 3.1.5. How can I get 3.1.10?
Thank you.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/9hYNNCQ/Captura.png" alt="Captura" border="0"></a>``

**Comment by tdmowrer** [comment]
You'll need Unity 2019.4. This is the Long Term Support (LTS) version based off 2019.3, so you should upgrade to it anyway :)

**Comment by paBlury** [comment]
I will and I will let you know. Thank you very much.

**Comment by paBlury** [comment]
Hi again,

I´ve updated to 2019.4.19f and I´ve downloaded the 3.1.10 version of ARCore.
I´ve been asked to use Gradle 5.6.4 and I´ve done so following the steps on this web: https://developers.google.com/ar/develop/unity/android-11-build

Now I´m getting the following errors when I try to build
<a href="https://ibb.co/2FGXnG5"><img src="https://i.ibb.co/WHmSxms/Captura.png" alt="Captura" border="0"></a>

**Comment by paBlury** [comment]
Please ignore my previous message.

**Comment by paBlury** [comment]
It works!. Thank you very much Tim.

For future reference if someone else finds the thread, you'll need to update your Android SDK to version 30. If that fails it might be because your JDK version is too recent and it cannot find some classes. I had to instal JDK8 for it to work.

Thanks again for the help.

**Comment by tdmowrer** [comment]
Great! Glad that worked for you.
