### ISSUE TITLE
How Do I Switch Bewtween Multiple Tracked Image Prefabs with the Same Image Target?

### ISSUE THREAD

**Issue by EmilioJAngeles** [Unity-Technologies/arfoundation-samples#742]
I'm currently trying to switch between 4 different models with the same reference image, showing one at a time, using a button press action to trigger the switch.

Through referencing some tutorials on having different tracked images with different reference images and what I found in this closed issue #575 I've tried adding this script to my AR Session Origin (which already has an attached AR Tracked Image Manager).

`public class ClothingLineController : MonoBehaviour
{`

    [SerializeField]
    private GameObject[] clothingModels;

    private ARTrackedImageManager trackedImageManager;
    private int index = 0;

    private void Awake()
    {
        trackedImageManager = FindObjectOfType<ARTrackedImageManager>();
    }

    public void NextButton()
    {
        if (index < clothingModels.Length - 1)
        {
            index++;
        }
        else
        {
            index = 0;
        }
        Debug.Log(index);
        trackedImageManager.trackedImagesChanged += ImageChanged;
    }

    public void PreviousButton()
    {
        if(index > 0)
        {
            index--;
        } else
        {
            index = clothingModels.Length - 1;
        }
        Debug.Log(index);
        trackedImageManager.trackedImagesChanged += ImageChanged;
    }

    private void ImageChanged(ARTrackedImagesChangedEventArgs eventArgs)
    {
        foreach(var trackedImage in eventArgs.updated)
        {
            foreach(GameObject clothing in clothingModels)
            {
                if(Array.IndexOf(clothingModels, clothing) == index)
                {
                    clothing.SetActive(true);
                    Debug.Log(clothing.name + "is now active");
                } else
                {
                    clothing.SetActive(false);
                    Debug.Log(clothing.name + "is now inactive");
                }
            }
        }
    }
`}`

I initialize the array by dragging in the objects into the script's field in the Unity Editor.
![hierarchy+inspector](https://user-images.githubusercontent.com/38303278/107565979-26335a00-6b99-11eb-944c-db2a5c4f5d33.png)

The NextButton() and PreviousButton() are tied to their respective button firing. In the Unity Editor when I run this, I get the index changing but the two log statements showing with clothing gameobject is active/inactive do not print. I'm assuming this is because I am using trackedImageManager.trackedImagesChanged incorrectly. So My biggest question is just how does trackedImageManager.trackedImagesChanged work? 

Also, maybe I am way off from a solution for what I am trying to do, so any point in the right direction would be really helpful.

**Comment by tdmowrer** [comment]
We have a sample that does something similar. See https://github.com/Unity-Technologies/arfoundation-samples#imagetrackingwithmultipleprefabs

**Comment by mauriciokwt** [comment]
I've been able to switch between game objects at runtime with button clicks by passing a gameobject parameter into a function which is called from the buttons, so in the button I pass which game object I want to spawn and instantiate that object as I destroy the 'old one'.  My only problem is that I would like to access the object that is spawned by default and make that functionality work with that, but i can't seem to find how to reference it

**Comment by tdmowrer** [comment]
> My only problem is that I would like to access the object that is spawned

Do you mean the prefab on the ARTrackedImageManager or the instantiated objects? There's an [event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackedImageManager.html#UnityEngine_XR_ARFoundation_ARTrackedImageManager_trackedImagesChanged) fired whenever images are added, updated, or removed.

**Comment by sharehuster** [comment]
@EmilioJAngeles have you switched multi prefab yet?  can you repost code for me  or send me email : zinmonno1@gmail.com. thank you
