### ISSUE TITLE
[ARKit Human Tracking] If Lidar is available is it get used automatically?

### ISSUE THREAD

**Issue by FrankSpalteholz** [Unity-Technologies/arfoundation-samples#743]
Hey there,

i'm currently working on a prototype where i try implementing ARKit human tracking (based on the ARFoundation example). The tracking is "ok"-ish but for serious purposes it needs to be improved. I have access to either using a latest iPadPro (with Lidar) or an iPhone12Pro (with Lidar). I've read that Lidar improves the tracking a lot but i haven't found any options on any component in the unity-example so i'm asking if Lidar is getting used automatically if available or if i have to implement it myself somehow? Thanks again for your awesome package! 

Best wishes 
Frank

**Comment by tdmowrer** [comment]
> I've read that Lidar improves the tracking a lot...

Apple [says](https://www.apple.com/newsroom/2020/03/apple-unveils-new-ipad-pro-with-lidar-scanner-and-trackpad-support-in-ipados/) that it does:

> Every existing ARKit app automatically gets instant AR placement, improved motion capture and people occlusion.

> ...but i haven't found any options on any component in the unity-example so i'm asking if Lidar is getting used automatically if available or if i have to implement it myself somehow?

Nope; there is nothing special that you need to do. ARKit will use LiDAR if it is available.
