### ISSUE TITLE
How do I... I need if you smile, a message  Debug.Log("");

### ISSUE THREAD

**Issue by mrsho0t** [Unity-Technologies/arfoundation-samples#745]
How do I...
Hi, I apologize for the message, but I need your help
I need if you smile, a message appears that I smiled, and if my face is not on the camera, a message appears. Where is your face
Please tell me how to do this on this project
"ARKitBlendShapeVisualizer.cs"

**Comment by tdmowrer** [comment]
You can use the blend shape locations `ARKitBlendShapeLocation.MouthSmileLeft` and `ARKitBlendShapeLocation.MouthSmileRight` to detect smiles. If the face is not on camera, then it's [tracking state](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackable-2.html#UnityEngine_XR_ARFoundation_ARTrackable_2_trackingState) should change from [TrackingState.Tracking](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.TrackingState.html?q=trackingstate).

**Comment by mrsho0t** [comment]
I knew the solution to this "tracking state"
But this is "ARKitBlendShapeLocation.MouthSmileLeft" I didn't know how to link it to Sloth_Head2

**Comment by tdmowrer** [comment]
Sorry; I'm not sure what you mean. I thought you wanted to log a debug message when a smile is detected. You can use the smile-related blend shape values to detect this. I'm not sure what you mean by "link it to Sloth_Head2" (a sample asset).
