### ISSUE TITLE
[Bug] UnityGfxDeviceWorker EXC_RESOURCE RESOURCE_TYPE_MEMORY

### ISSUE THREAD

**Issue by mrsho0t** [Unity-Technologies/arfoundation-samples#746]
**Unity bug report case number**
**I don't know why the app suddenly freezes and crashes**
IPhone gets very hot. I tried all the methods, I do not know where the problem is
[
![Screenshot_7](https://user-images.githubusercontent.com/77662206/108603882-77bebe80-73bb-11eb-8cf2-e35215168691.png)
](url)

**Actual behavior**
After 5 minutes, the error stared

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XS 12.2]
 - OS: [e.g. iOS 12.2]
 - Unity version 2020.2.2
 - ARFoundation version 4.0.12

**Comment by tdmowrer** [comment]
This looks like a memory leak leading to an out of memory crash. How much memory is in use when this happens?

**Comment by mrsho0t** [comment]
> This looks like a memory leak leading to an out of memory crash. How much memory is in use when this happens?

I do not know, but I cannot complete the application because of this problem, the application freezes and the iPhone mobile becomes hot.
Please give me what is the solution in your opinion?

**Comment by tdmowrer** [comment]
Xcode can show you how much memory your app is using:

![Screen Shot 2021-02-25 at 10 25 27 AM](https://user-images.githubusercontent.com/4934281/109199132-ea30f500-7753-11eb-9c89-b15e07069da0.png)

There's generally a limit of 2GB, so if you go over that, it would appear to crash.

**Comment by mrsho0t** [comment]
I will send you the project here and see what is wrong with my iPhone xs 12.1 

I only use the front camera that tracks the face movement and the name Sense :**ARsmile1**
[https://drive.google.com/file/d/1nC6xy3SuGpT_US9J3FtckK3egBhgWyho/view?usp=sharing](url)

Unity version 2020.2.2
ARFoundation version 4.0.13

![Screenshot_5](https://user-images.githubusercontent.com/77662206/109225136-ec379a00-77cd-11eb-800b-8c571504b742.png)

![Screenshot_7](https://user-images.githubusercontent.com/77662206/109225637-96afbd00-77ce-11eb-850f-25930bce79ff.png)


![Screenshot_8](https://user-images.githubusercontent.com/77662206/109225675-a3ccac00-77ce-11eb-802d-a851374ccbf7.png)

**Comment by tdmowrer** [comment]
> I will send you the project here and see what is wrong with my iPhone xs 12.1

You can log a bug with an attached project by following [these instructions](https://unity3d.com/unity/qa/bug-reporting).

**Comment by javierpal** [comment]
i'm experiencing the same problem, but yeah in my case is using memory, not all but something bigger than usual, and I cant seem to find a fix or an answer.

**Comment by DirtyFreddie** [comment]
Hi guys,

I also have this issue. I cannot find a fix for it, and sometimes it happens on android as well

**Comment by cobaltplay** [comment]
hey all. same problem here.

![image](https://github.com/Unity-Technologies/arfoundation-samples/assets/34491781/606a04af-b00a-4293-8c77-d5fda2230cc5)

After I click the 'metal capture' button. Memory usage just keeps on climbing until it hits the 2GB limit:
![image](https://github.com/Unity-Technologies/arfoundation-samples/assets/34491781/c2922d66-2724-49f8-8850-b588cfe0d552)

And then errors out:
![image](https://github.com/Unity-Technologies/arfoundation-samples/assets/34491781/dab24293-a76f-49bd-97e4-a3e54ab10482)

The only way I've managed to get the metal debugger to work is to have a very basic scene with a few game objects in and try to profile shaders that way. Not ideal as its not the full scene.

Did anyone find a workaround for this? An Xcode downgrade perhaps?
