### ISSUE TITLE
Avoid black reflections on iOS when using AREnvironmentProbeManager

### ISSUE THREAD

**Issue by D33pTh0ught** [Unity-Technologies/arfoundation-samples#749]
When I launch the environment probe example scene on iOS the reflective spheres initially are black and only show environment reflections after some time/camera movement. Android does not have this issue.
Would it be possible to avoid this behavior by choosing a fixed skybox to use for light probes as long as no information is provided by the AREnvironmentProbeManager?
Any hints on how this could be achieved?

**Comment by tdmowrer** [comment]
> Would it be possible to avoid this behavior by choosing a fixed skybox to use for light probes as long as no information is provided by the AREnvironmentProbeManager?

That sounds reasonable.

> Any hints on how this could be achieved?

You can subscribe to the [environmentProbesChanged event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.AREnvironmentProbeManager.html#UnityEngine_XR_ARFoundation_AREnvironmentProbeManager_environmentProbesChanged) to be notified when an environment probe is added.

**Comment by D33pTh0ught** [comment]
> ... choosing a fixed skybox to use for light probes ...
i meant reflection probe here but I guess you got that from the rest of the description

Could you elaborate a bit more. I am still rather confused about how I would achieve this by subscribing to this event. What would i need to do upon receiving it?

I did some more testing and it seems that independent of whether i set the [blending](https://docs.unity3d.com/2020.2/Documentation/Manual/UsingReflectionProbes.html) on the object to 'blend probes' or 'blend probes and skybox' the original skybox appears in the reflection for a brief moment when starting the scene before being replaced by the reflection probes from the environment map estimation.
The problem is that the reflection probes set by ARKit are black at the beginning. This does also only happen when first launching the scene on a fresh install of the app. When launching the scene again it already holds the estimation information from before. (So it appears you need to reinstall the app each time to reproduce this behavior. This also happens in the environment probe sample scene of this repo.)

So the current default behaviour appears as if the AREnvironmentProbeManager initially sets black environment probes or the blending with the skybox is disabled as soon as the AREnvironmentProbeManager is set up.

**Comment by D33pTh0ught** [comment]
Can I please get a response before closing this issue again?

**Comment by D33pTh0ught** [comment]
The linked commits by marwie mentioning this issue suggest that this should now be fixed, however I just tested it (Unity 2020.3.2, ARFoundation 4.1.7, arfoundation samples repo branch 4.1) and the behavior is still the same:
When first launching the AR app and opening a scene with environment probe estimation on iOS the reflections are black.

**Comment by tdmowrer** [comment]
Just reverified the fix and it works as expected for us. Can you please log a bug by following the instructions here https://unity3d.com/unity/qa/bug-reporting and reply with the case ID?

**Comment by D33pTh0ught** [comment]
I'm having a hard time believing that this works for you. When you say "it works as expected" you mean that on iOS on a **fresh install(!)** of the app the reflections in the environment probes are never black?
If this is indeed the case, can you provide which version of the arfoundation samples repo, unity and iOS you were using?

**Comment by D33pTh0ught** [comment]
Can someone clarify the current state for me?
I have tried the current ARFoundation sample on multiple iOS devices and all have the issue of black reflections upon first installation of the app.

So if this should be indeed fixed could you provide more info about a setup where you get this to work?
And if this is expected bahavior can you specify the approach you suggested as a workaround in the first response?

**Comment by tdmowrer** [comment]
Please log a bug (https://unity3d.com/unity/qa/bug-reporting). This will allow us to reproduce the exact issue(s) you are seeing.

**Comment by D33pTh0ught** [comment]
I reported this bug: (Case 1341768) Estimated reflections in AR are black when first starting the app on iOS

**Comment by D33pTh0ught** [comment]
I got a helpful response from my bug report:
"I was able to reproduce the same behavior on my end. However, this is actually working the way it is intended. The reflections are generated when the Scene loads in, and if the camera permissions have not yet been granted, they will reflect the black Screen that is shown before gaining access to the Camera.

The second time you load into the Scene, the App no longer needs to request Camera permission and can generate the reflections from the surroundings instantly.

The same kind of behavior can be achieved by completely covering the Camera of the device when loading the Scene (for instance, by placing the device on a table). The reflections will be completely black as well in this scenario.

One potential solution to this you could implement in a project would be to request the Camera permission before actually loading in any of the Spheres that should reflect the environment."
