### ISSUE TITLE
Image Tracking - Precise location with QR Code

### ISSUE THREAD

**Issue by livpasdiora** [Unity-Technologies/arfoundation-samples#750]
Hello everyone!! 

I am developing an application for civil construction, where I instantiate a model (1: 1 scale) through a QR Code.
But most of the time, the model's location is not accurate. Does anyone know how to fix this?

Thanks! 

![image](https://user-images.githubusercontent.com/61844578/109194209-f9c23500-7777-11eb-8e91-a58da348433b.png)

**Comment by tdmowrer** [comment]
Hard to tell from the description, but some things to try:

* Check your model's pivot. Is it exactly where "THIS POINT" is?
* Make sure you've correctly put in the physical size of the QR code in the reference image library.

**Comment by livpasdiora** [comment]
Hi!! Thanks for answering me.
The size of the QR code is right.
The pivot is at the QR code location (I had to do this to have control of the exact position of the QR code).
It seems that the inclination of the smartphone is interfering with the instantiation of the model. Is that a possibility?

**Comment by mauriciokwt** [comment]
I'm just beginning to code in unity but I THINK that yes, the inclination and position of the smartphone is interfering in the position of the objects. I'm also facing this issue. What I'm trying to do is to put the values of the QR code/image position in a variable and manipulate that, but I'm not quite there yet.

**Comment by livpasdiora** [comment]
> I'm just beginning to code in unity but I THINK that yes, the inclination and position of the smartphone is interfering in the position of the objects. I'm also facing this issue. What I'm trying to do is to put the values of the QR code/image position in a variable and manipulate that, but I'm not quite there yet.

Do you have the code to show me how to do this? Thanks!
