### ISSUE TITLE
Add AR occlusion  component to ARCamera at runtime, not working

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#751]
**Describe the bug**
```C#
AROcclusionManager occlusionManager
void Start()
{
   occlusionManager = _abstractAlgorithm.Camera.gameObject.AddComponent<AROcclusionManager>();
   occlusionManager.requestedEnvironmentDepthMode = _configures.EnvironmentDepthMode;
   occlusionManager.requestedHumanDepthMode = _configures.HumanSegmentationDepthMode;
   occlusionManager.requestedHumanStencilMode = _configures.HumanSegmentationStencilMode;
   occlusionManager.requestedOcclusionPreferenceMode = _configures.OcclusionPreferenceMode;
   occlusionManager.enabled = false;
}

void OnGUI()
{
   //Button trigger
   if(GUI.Button(new Rect(0,100,130,45),"Start Occlusion")
        occlusionManager.enabled = true;
}
```

**Smartphone (please complete the following information):**
 - Device: iPhone12 pro
 - OS: iOS 14.4
 - Unity version 2019.4f15
 - ARFoundation version 4.1.3

**Comment by tdmowrer** [comment]
Can you be more specific about what isn't working? Is there an exception or a crash? What configuration have you requested?

**Comment by weacw** [comment]
> _**Can you be more specific about what isn't working?**_

 No human or Environment occlusion run on iPhone 12 pro

> **_Is there an exception or a crash?_**

Not

> **_What configuration have you requested?_**

configuration by default

here is xcode log :
https://drive.google.com/file/d/1pO1TZU6KnLrjYSeZZXJcle15DzDwMJsd/view?usp=sharing

Add AR Occlusion Manager to AR Camera
```C#
void Start()
{
    // All requested is Fastest
    occlusionManager = _abstractAlgorithm.CameraGameObject.AddComponent<AROcclusionManager>();
    occlusionManager.requestedEnvironmentDepthMode = EnvironmentDepthMode.Fastest;
    occlusionManager.requestedHumanDepthMode = HumanDepthMode.Fastest;
    occlusionManager.requestedHumanStencilMode = HumanStencilMode.Fastest;
    
    //PreferEnvironmentOcclusion
    occlusionManager.requestedOcclusionPreferenceMode = OcclusionPreferenceMode.PreferEnvironmentOcclusion;
    occlusionManager.enabled = false;
}
void OnGUI()
{
   //Button trigger
   if(GUI.Button(new Rect(0,100,130,45),"Start Occlusion")
        occlusionManager.enabled = true;
}
```

**Comment by tdmowrer** [comment]
Could you [file a bug](https://unity3d.com/unity/qa/bug-reporting), please? (And post the case ID here)

**Comment by weacw** [comment]
> Could you [file a bug](https://unity3d.com/unity/qa/bug-reporting), please? (And post the case ID here)
Emmm. I m using URP 7.x
I think this is not a Unity bug. The AR occlusion manager has allocated memory and is running (affects FPS), But no occlusion is performed when rendering.

**Comment by tdmowrer** [comment]
> Sorry I dont know how to report the bug.

From https://unity3d.com/unity/qa/bug-reporting:

> When running Unity choose **Help->Report a Bug** in the menu

**Comment by weacw** [comment]
> > Sorry I dont know how to report the bug.
> 
> From https://unity3d.com/unity/qa/bug-reporting:
> 
> > When running Unity choose **Help->Report a Bug** in the menu

Thank you！

**Comment by weacw** [comment]
Hi @tdmowrer  the case id is 1325978

**Comment by Ayfel** [comment]
Any updates? Finding the same issues. Furthermore:

 I have a setup where I enable an AR camera (with the whole AR setup) in my app and disable my original camera. This step requires moving the AR camera around which causes the AROcclusionManager to not work properly, simply removing the step where I move postition and rotation of the AR camera things work properly.

What is worse is that after disabling AR mode the occlusion seems to stay on and all my standard shader assets are invisible in the regular camera. So there is obvious some buggy behaviour there.

Again everything works peachy without the occlusion enabled. Also it seems like I have no access to methods that would reset the behaviour of the occlusion as everything seems to be protected or private (ResetTextureInfos())

Any help on how to properly work with occlusion and be able to move the AR camera. What it feels like it that the occlusion works in the original position the AR camera was, as soon as I move the AR parent root, all is off.

**Comment by tdmowrer** [comment]
The bug was closed as we could not reproduce the issue as submitted by @weacw (https://github.com/Unity-Technologies/arfoundation-samples/issues/751#issuecomment-811564773). I think the only reason this issue is still open because the stale bot appears to be broken.

@Ayfel If you have a reproducible project, please submit a bug by following https://unity3d.com/unity/qa/bug-reporting

**Comment by nikhilsawlani** [comment]
We're seeing a similar Crash on iOS devices when occlusion manager is attached to ARCamera

here is stack stace:
Crashed: UnityGfxDeviceWorker

0  libobjc.A.dylib                0x3970 objc_retain + 16
1  UnityFramework                 0x9cb358 TexturesMetal::AddCreatedTexture(TextureID, id<MTLTexture>, bool) + 32
2  UnityFramework                 0x917a24 GfxDeviceWorker::RunCommand(ThreadedStreamBuffer&) + 23240
3  UnityFramework                 0x99ec3c GfxDeviceWorkerAutoreleasePoolProxy + 68
4  UnityFramework                 0x919e50 GfxDeviceWorker::RunExt(ThreadedStreamBuffer&) + 92
5  UnityFramework                 0x911c5c GfxDeviceWorker::RunGfxDeviceWorker(void*) + 12
6  UnityFramework                 0x466598 Thread::RunThreadWrapper(void*) + 196
7  libsystem_pthread.dylib        0x19ac _pthread_start + 148
8  libsystem_pthread.dylib        0xe68 thread_start + 8

Unity - 2021.3.1f1
iOS - 15.4.1
iPhone 13 Pro and 12 Pro
ARFoundation version 4.2.3

The crash happens most of the times post we render 3d models and images in the AR Scene

**Comment by isakdiaz** [comment]
We're also seeing this bug. Does anyone have a solution for it? AR Occlusion Manager causes UnityGfxDeviceWorker errors whenever attached to an AR Session Origin or AR Camera.

**Comment by pavelsamoylenko** [comment]
![Screenshot 2023-11-08 at 12 23 39](https://github.com/Unity-Technologies/arfoundation-samples/assets/46072520/d6892cee-e8c9-44c4-8ab2-096a4e5a30c1)

From what I found out that AR occlusion will work only if you have AROcclusionManager instantiated on AR Camera gameobject before you instantiate ARCameraBackground component because it tries to get m_occlusionManager on Awake stage.
