### ISSUE TITLE
Errors when adding ARFoundation Sample in unity

### ISSUE THREAD

**Issue by vestri** [Unity-Technologies/arfoundation-samples#752]
I am trying to install and test AR Foundation samples but get errors at installation. I am using Unity 2020.2.6f1 and AR Foundation and ARCore XR Plugin 4.0.12 (the verified versions).
I tried two ways for installing plugins but it did not work:
(1) with package manager by adding package using git and https://github.com/Unity-Technologies/arfoundation-samples.git
![image](https://user-images.githubusercontent.com/4747304/109410974-eb099700-799e-11eb-8759-9385bf0ee739.png)
(2) by dowloading github package (branch 4.0 but I got the same with master) and Drag&Drop the directory to project packages.
![image](https://user-images.githubusercontent.com/4747304/109411355-c4992b00-79a1-11eb-982e-954de44f95b7.png)

I then try to add simpleAR scene and build it, I have the following errors:
![image](https://user-images.githubusercontent.com/4747304/109411414-31acc080-79a2-11eb-9de2-3c790dceb0bd.png)

Please tell me how to correctly install and test samples.
Thanks

ps: Building a simple AR Foundation scene from start worked so AR foundation is well installed (https://learn.unity.com/tutorial/configuring-plane-detection-for-ar-foundation)

**Comment by tdmowrer** [comment]
This samples repo is a Unity project. Clone it and open it as a project; it is not a package that you can add to an existing project.

**Comment by vestri** [comment]
It worked, thanks a lot. I misunderstood the way to test it.
