### ISSUE TITLE
Broken ImageTargetLibrary does not throw error. How to validate?

### ISSUE THREAD

**Issue by D33pTh0ught** [Unity-Technologies/arfoundation-samples#753]
Sometimes the ImageTargetLibrary seems to get corrupted when saving. Recreating the Library fixes the issue. According to my observation m_GuidLow and m_GuidHigh seem to be at the core of the problem:
- I have had wrong guids for images under m_Images in the library.asset file leading to the wrong image being recognized even though the editor showed the correct image in the Inspector.
- Recently I had an issue where the m_GuidLow and m_GuidHigh of the library itself were 0 leading to an Exception at runtime where it stated that the library was empty. The library in the inspector however looked fine. Re-adding and deleting an additional image so the library got saved again also solved this issue. (I did not manually manipulate the library.asset file)

So it seems that sometimes unity corrupts the library.asset without this problem becoming visible in the editor (no build error) or in the inspector of the library itself.

Would it be possible to notify the user if m_GuidLow and m_GuidHigh get corrupted or is there a way to check those values for validity myself?

**Comment by tdmowrer** [comment]
I have not seen that happen before. Could you [file a bug](https://unity3d.com/unity/qa/bug-reporting), please? (And post the case ID here)

**Comment by D33pTh0ught** [comment]
I reported the issue (Case 1318970)
