### ISSUE TITLE
Get landmark points for Face mesh[ARCore and ARKit]

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#754]
I want to get the landmark points of the face mesh and paste the 2D stickers to the corresponding places (for example: glasses try on, eyebrows, nose etc)

![HBa8z](https://user-images.githubusercontent.com/11573490/109521608-72aeed00-7ae8-11eb-9539-e07c406cc65b.jpg)

Or
Is there a better solution?

**Comment by tdmowrer** [comment]
ARKit provides [blend shapes](https://docs.unity3d.com/Packages/com.unity.xr.arkit-face-tracking@4.1/api/UnityEngine.XR.ARKit.ARKitFaceSubsystem.html#UnityEngine_XR_ARKit_ARKitFaceSubsystem_GetBlendShapeCoefficients_UnityEngine_XR_ARSubsystems_TrackableId_Unity_Collections_Allocator_) and ARCore provides [face regions](https://docs.unity3d.com/Packages/com.unity.xr.arcore@4.1/api/UnityEngine.XR.ARCore.ARCoreFaceSubsystem.html#UnityEngine_XR_ARCore_ARCoreFaceSubsystem_GetRegionPoses_UnityEngine_XR_ARSubsystems_TrackableId_Unity_Collections_Allocator_Unity_Collections_NativeArray_UnityEngine_XR_ARCore_ARCoreFaceRegionData___).

However, those don't tell you exactly where the eyebrows and nose are, for example. Other people have either hard-coded indices for those. This may work on a specific device, but the face mesh can vary across different devices. Others have used [OpenCV](https://opencv.org/) to extract facial landmarks.

**Comment by weacw** [comment]
thank you for your reply.

**Comment by weacw** [comment]
Oh sorry. I want to know how to know whether the user is opening or closing the mouth (eye etc)

**Comment by tdmowrer** [comment]
On ARKit, you can use blend shapes for that. There is a sample in this repo that shows how to use them: https://github.com/Unity-Technologies/arfoundation-samples#arkitfaceblendshapes
