### ISSUE TITLE
[Bug] iOS build of Image Tracking scenes not working - Tracking images seemingly not recognized

### ISSUE THREAD

**Issue by DeaconDP** [Unity-Technologies/arfoundation-samples#755]
**Unity bug report case number**
n/a

**Describe the bug**
Sample app's Image Tracking scenes don't seem to work on iPad Air 4th Gen. Camera seems fine, but it doesn't recognize the "1", "2" or "Rafflesia" sample images.

**To Reproduce**
1. Build to iOS
2. Copy to MacBook
3. chmod +x on build
4. import into xcode
5. set up auto-certificate signing
6. set destination to iPad (Air 4th Gen)
7. Run
8. All scenes seem functional except the image tracking scenes (single tracker & multi-tracker)

**Expected behavior**
Camera scans image - 3D asset laid over the tracker image (Android build seems fine)

**Actual behavior**
Camera scans image(s) but doesn't seem to recognize the images

**Smartphone (please complete the following information):**
 - Device: iPad (Air 4th Gen)
 - OS: latest
 - Unity version 2020.2.1f1
 - ARFoundation version 4.1.3

**Comment by tdmowrer** [comment]
Since you "Copy to MacBook" in step 2, on what machine do you "Build to iOS" in step 1?

**Comment by DeaconDP** [comment]
Sorry for the delayed response, and thanks for an amazing template! I built the app on a PC and transferred the build to a mac. Building the app on the mac itself seemed to resolve the issue. Maybe this is just a disclaimer to add to the documentation.

Side note: I'm a die-hard PC dev, and was asked to port our Android AR app to iOS. I was under the impression this was possible without buying a Mac. No matter the VM hoops I jumped through, I couldn't make it happen without knuckling down and getting a mac in the end. Wiped out a significant chunk of profit, but I guess we got a halfway decent asset out of it.

**Comment by tdmowrer** [comment]
You _should_ be able to generate the Xcode project on Windows, copy it to a Mac, and build it; I've tested this myself many times. While you may be able to compile for iOS on Window, you need a Mac in order to sign your application, so you'll need to have one in order to ship anything, ultimately.
