### ISSUE TITLE
How to get texture from ARCamera in portrait mode (iOS)

### ISSUE THREAD

**Issue by michalek-marcin** [Unity-Technologies/arfoundation-samples#756]
Hi,

How can I get texture from ArCamera? I need texture in portrait orientation to use it in my neural network (image recognition with yolov2 and Barracuda).

I tried TryAcquireLatestCpuImage, but it always returns image in landscape orientation.
I use ArCameraBackground for preview and it works great, but also I need to analyse every frame captured by camera.
I know there is a way to copy ARBackgroundTexture to render texture, but problem is the same.

I tried CpuImages sample scene from this repo, and in portrait mode images are rotated.

**Comment by tdmowrer** [comment]
The XRCpuImage is the raw image from the camera, so no rotation is applied. The goal of this API is to provide direct access to the CPU pixels so they can be passed to another algorithm. If you require a particular orientation, you will need to apply that transformation yourself.

**Comment by michalek-marcin** [comment]
Hi @tdmowrer, thanks for fast response. I need the same image which is presented on ARCameraBackground. Could you share example how can I transform landscape texture (XRCpuImage) to portrait format?

**Comment by tdmowrer** [comment]
The transformation for the pass through video happens in a shader specific to each package. [This script](https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/DisplayDepthImage.cs#L300-L344) shows how to compute a similar transformation matrix in C#.

**Comment by michalek-marcin** [comment]
@tdmowrer I tried that code, but I think I need shader too for this, and I'm not sure if with that I will get portrait texture. As I mentioned, I have correct fullscreen preview in app in portrait mode right now. I need texture which looks same as picture on screen. Is it possible to get texture from ARCameraBackground?

**Comment by michalek-marcin** [comment]
I found an example of using a Graphics.Blit function. Now I can get texture with correct orientation. I will investigate my case with image recognition tommorow.

Here is my code:
`private void CopyArCameraBackground()
{
    if (_renderTexture == null)
    {
        _renderTexture = new RenderTexture(416, 416, 24, RenderTextureFormat.ARGB32);
    }

    Graphics.Blit(null, _renderTexture, _arCameraBackground.material);

    var activeRenderTexture = RenderTexture.active;
    RenderTexture.active = _renderTexture;

     if (_texture == null)
     {
        _texture = new Texture2D(_renderTexture.width, _renderTexture.height, TextureFormat.RGB24, true);
     }

     _texture.ReadPixels(new Rect(0, 0, _renderTexture.width, _renderTexture.height), 0, 0);
     _texture.Apply();
     RenderTexture.active = activeRenderTexture;
}`

**Comment by TomDeFord** [comment]
> The XRCpuImage is the raw image from the camera, so no rotation is applied. The goal of this API is to provide direct access to the CPU pixels so they can be passed to another algorithm. If you require a particular orientation, you will need to apply that transformation yourself.

Hi, does this mean that TryAcquireLatestCpuImage is not appropriate for cross platform/device use? Surely without the the orientation of the image being guaranteed to be consistent across platforms/devices then it would be impossible to know if the image need rotating/flipping or not - as each device/platform could render the image differently depending on hardware? Is there maybe a call to get information about the camera to know how it returns the raw image to TryAcquireLatestCpuImage?

**Comment by tdmowrer** [comment]
That information is provided by the [displayMatrix](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html?q=displaymatrix) (used in the code snippet I mentioned earlier). The only gotcha is that the row-major vs column-major order of the matrix is different on iOS and Android.
