### ISSUE TITLE
Create reference object from mesh + material and add to object library during runtime

### ISSUE THREAD

**Issue by Matt-Tanti** [Unity-Technologies/arfoundation-samples#757]
Hi,

Is it possible to create a reference object using the mesh and materials which are obtained externally during runtime (node server) and then add the newly created reference object into a XR Reference Object Library?

If this cannot be done, is there another way which would allow this to happen during runtime?

**Comment by tdmowrer** [comment]
ARKit's reference objects must be created using their [scanning app](https://developer.apple.com/documentation/arkit/content_anchors/scanning_and_detecting_3d_objects). You cannot create one from a mesh.
