### ISSUE TITLE
AR Samples new project many errors

### ISSUE THREAD

**Issue by InfinityCoder88** [Unity-Technologies/arfoundation-samples#758]
Hi I'm using **Unity 2020.2.3f1** and the latest **AR Packages 4.0.12** : 

1. I made a new clean project
2. Imported all AR packages (AR Foundation, ARCore XR Plugin, ARKit Face Tracking)
3. I get all these errors, how can fix this?

Assets/AR_Samples/Scenes/ImageTracking/DynamicLibrary.cs(104,78): error CS1061: 'DynamicLibrary.ImageData' does not contain a definition for 'jobState' and no accessible extension method 'jobState' accepting a first argument of type 'DynamicLibrary.ImageData' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/DisplayARSessionInformation.cs(139,81): error CS1061: 'AROcclusionManager' does not contain a definition for 'requestedEnvironmentDepthMode' and no accessible extension method 'requestedEnvironmentDepthMode' accepting a first argument of type 'AROcclusionManager' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/DisplayARSessionInformation.cs(140,79): error CS1061: 'AROcclusionManager' does not contain a definition for 'currentEnvironmentDepthMode' and no accessible extension method 'currentEnvironmentDepthMode' accepting a first argument of type 'AROcclusionManager' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/UX/CheckRuntimeDepth.cs(48,82): error CS1061: 'XROcclusionSubsystemDescriptor' does not contain a definition for 'supportsEnvironmentDepthImage' and no accessible extension method 'supportsEnvironmentDepthImage' accepting a first argument of type 'XROcclusionSubsystemDescriptor' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scenes/ARKit/ThermalState/Scripts/FeaturesReporting.cs(181,108): error CS1061: 'AROcclusionManager' does not contain a definition for 'currentEnvironmentDepthMode' and no accessible extension method 'currentEnvironmentDepthMode' accepting a first argument of type 'AROcclusionManager' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scenes/ARKit/ThermalState/Scripts/ThermalStateHandling.cs(195,32): error CS1061: 'AROcclusionManager' does not contain a definition for 'requestedEnvironmentDepthMode' and no accessible extension method 'requestedEnvironmentDepthMode' accepting a first argument of type 'AROcclusionManager' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scenes/ARKit/ThermalState/Scripts/ThermalStateHandling.cs(195,73): error CS0103: The name 'EnvironmentDepthMode' does not exist in the current context

Assets/AR_Samples/Scenes/ARKit/ThermalState/Scripts/ThermalStateHandling.cs(195,101): error CS0103: The name 'EnvironmentDepthMode' does not exist in the current context

Assets/AR_Samples/Scripts/DisplayDepthImage.cs(233,55): error CS1061: 'XROcclusionSubsystemDescriptor' does not contain a definition for 'supportsEnvironmentDepthImage' and no accessible extension method 'supportsEnvironmentDepthImage' accepting a first argument of type 'XROcclusionSubsystemDescriptor' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/DisplayDepthImage.cs(252,53): error CS1061: 'AROcclusionManager' does not contain a definition for 'environmentDepthTexture' and no accessible extension method 'environmentDepthTexture' accepting a first argument of type 'AROcclusionManager' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/AnchorCreator.cs(50,21): error CS1061: 'ARRaycastHit' does not contain a definition for 'trackable' and no accessible extension method 'trackable' accepting a first argument of type 'ARRaycastHit' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scenes/ImageTracking/DynamicLibrary.cs(170,39): error CS1061: 'DynamicLibrary.ImageData' does not contain a definition for 'jobState' and no accessible extension method 'jobState' accepting a first argument of type 'DynamicLibrary.ImageData' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scenes/ImageTracking/DynamicLibrary.cs(170,65): error CS1061: 'MutableRuntimeReferenceImageLibrary' does not contain a definition for 'ScheduleAddImageWithValidationJob' and no accessible extension method 'ScheduleAddImageWithValidationJob' accepting a first argument of type 'MutableRuntimeReferenceImageLibrary' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scenes/ImageTracking/DynamicLibrary.cs(193,36): error CS1061: 'DynamicLibrary.ImageData' does not contain a definition for 'jobState' and no accessible extension method 'jobState' accepting a first argument of type 'DynamicLibrary.ImageData' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/UX/CheckAvailableFeatures.cs(387,95): error CS1061: 'XRCameraSubsystemDescriptor' does not contain a definition for 'supportsColorCorrection' and no accessible extension method 'supportsColorCorrection' accepting a first argument of type 'XRCameraSubsystemDescriptor' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/CpuImageSample.cs(246,54): error CS1061: 'AROcclusionManager' does not contain a definition for 'TryAcquireEnvironmentDepthCpuImage' and no accessible extension method 'TryAcquireEnvironmentDepthCpuImage' accepting a first argument of type 'AROcclusionManager' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/CpuImageSample.cs(248,24): error CS0165: Use of unassigned local variable 'image'

Assets/AR_Samples/Scripts/CpuImageSample.cs(266,54): error CS1061: 'AROcclusionManager' does not contain a definition for 'TryAcquireEnvironmentDepthConfidenceCpuImage' and no accessible extension method 'TryAcquireEnvironmentDepthConfidenceCpuImage' accepting a first argument of type 'AROcclusionManager' could be found (are you missing a using directive or an assembly reference?)

Assets/AR_Samples/Scripts/CpuImageSample.cs(268,24): error CS0165: Use of unassigned local variable 'image'

Thanks in advance!
<img width="802" alt="Screen Shot 2021-03-05 at 15 28 58" src="https://user-images.githubusercontent.com/6507433/110138455-ea6f6700-7dc9-11eb-8040-c516a4e3136d.png">
<img width="2041" alt="Screen Shot 2021-03-05 at 15 46 34" src="https://user-images.githubusercontent.com/6507433/110138558-02df8180-7dca-11eb-8618-764184dabff9.png">

**Comment by tdmowrer** [comment]
That isn't a clean project; the errors come from scripts in a folder in your project called `AR_Samples`. I'm guessing you copied the samples in this repo but for a different version of the packages.

**Comment by InfinityCoder88** [comment]
Hi tdmowrer,

I installed the latest version of Unity 2020.2.7f1 made a new project imported the samples, now it's fine. Thanks!
