### ISSUE TITLE
How to add Images from project folder to XR Reference Image library during runtime?

### ISSUE THREAD

**Issue by DavidRaptor** [Unity-Technologies/arfoundation-samples#759]
How do I assign one image to XR Reference image library at runtime, whenever i am loading a scene, other than that image which is already assigned to XR Reference image library from unity editor, from project folder to be able to update every time a new image marker to be scanned in app. How to achieve this?
I hope my question is making sense here, 
I will try to explain more in points below:
1. Create an XR Reference image library from editor and assign an image to it, this library is assigned to tracked image manager.
2. I have like 4 images in my assets folder, i want to assign each time a new image to this XR Reference Image Library, when i have to scan marker image.
3. I have to get a new image every time, i have to scan a marker image. Hope my question makes sense and pls guide me to achieve this state.

**Comment by tdmowrer** [comment]
The image tracking sample in this repo does this: https://github.com/Unity-Technologies/arfoundation-samples#basicimagetracking

See also the section called "Adding new reference images at runtime" from https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/tracked-image-manager.html
