### ISSUE TITLE
Problem with XRCpuImage.ConversionParams when dealing with depth images

### ISSUE THREAD

**Issue by AndreNicolai** [Unity-Technologies/arfoundation-samples#761]
Hey there,

I discovered a problem when I was trying to access depth images on the CPU, which only seems to work when setting XRCpuImage.Transformation to MirrorY.

How to reproduce: Try to build the 'CPUImages.unity' scene for iOS/Android after changing the transformation to either 'MirrorX' or 'None' in the 'CPUImageSample' class line '295'.
When running the sample on the phone, much of the depth image data seems to get lost along the way, somewhere.

I tested this on iOS, only, so far, with both Unity 2019 + 2020 and ARFoundation 4.1.5 respectively 4.1.3.

Can anybody confirm this is happening?

Best regards,

André

**Comment by tdmowrer** [comment]
Could you please log a bug by following the directions at https://unity3d.com/unity/qa/bug-reporting and post the case ID here?

**Comment by AndreNicolai** [comment]
Sorry for the delay, but here is the case ID: 1321178.

By now I was also able to do some testing on Android and can report that this issue does not occur.

**Comment by tdmowrer** [comment]
Thanks; we've reproduced it on iOS. Will look into it.

**Comment by artoonie** [comment]
Hi, I'm experiencing the same bug. I heard that it's already on the internal bug tracker but not on the public issues list. Can it be added there?

**Comment by tdmowrer** [comment]
The public issue tracker link will be available shortly here: https://issuetracker.unity3d.com/product/unity/issues/guid/1321178/

**Comment by tdmowrer** [comment]
This was fixed in a recent release (4.2.0-pre.8).
