### ISSUE TITLE
Spawned object not anchoring to the tracked image

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [Unity-Technologies/arfoundation-samples#764]
I have an app where if the user detects an animal image, it spawns the animal GameObject associated with that image.

The GameObject has the transform position of 0,0,0. 

But when we test the image tracking, the GameObject appears way above the marker instead of spawning on top of it. (If we move the camera it also gets displaced) The image below demonstrates the problem

![Penguin](https://user-images.githubusercontent.com/18481583/110944756-28760900-833d-11eb-9732-46d4474134e5.jpg)

My code for ImageTracking is this
```cs
private void AddARImage(ARTrackedImage trackedImage)
    {
        AssignGameObjectOnAdded(trackedImage.referenceImage.name, trackedImage.transform.position, trackedImage);
    }
    void AssignGameObject(string name, Vector3 newPosition, ARTrackedImage trackedImage)
    {
        if (trackedImage.trackingState == TrackingState.Tracking)
        {
            if (jSONController.animalToDetect == name)
            {
                if (placeablePrefabs != null)
                {
                    animalPrefab = spawnedPrefabs[name];
                    animalPrefab.SetActive(true);
                    animalPrefab.transform.position = newPosition;
                    StartCoroutine(TurnOnAnimator(animalPrefab.GetComponentInChildren<Animator>()));
                }
            }
      }
}
```

**Comment by tdmowrer** [comment]
Couple things to try:

* It looks like you are placing the object when the image is first detected. The image's position is refined over time, so you might need to update your object periodically when the detected image is updated.
* If the reference image dimensions are not exactly correct, then the position will be slightly above or below the image. This is because if you tell the system the reference image is bigger than it actually is, then it will just assume it is viewing your reference image from far away. Given your screen shot, this is my best guess as to what is going on.

**Comment by Sterling-Malory-Archer** [comment]
> Couple things to try:
> 
> * It looks like you are placing the object when the image is first detected. The image's position is refined over time, so you might need to update your object periodically when the detected image is updated.
> * If the reference image dimensions are not exactly correct, then the position will be slightly above or below the image. This is because if you tell the system the reference image is bigger than it actually is, then it will just assume it is viewing your reference image from far away. Given your screen shot, this is my best guess as to what is going on.

Hi Tim,

I have a method that fires up when the image is updated, the code is pretty much the same as when the image is first detected:

```cs
void AssignGameObjectUpdated(string name, Vector3 newPosition, ARTrackedImage trackedImage)
    {
        if (trackedImage.trackingState == TrackingState.Tracking)
        {
            if (jSONController.animalToDetect == name)
            {
                if (placeablePrefabs != null)
                {
                    animalPrefab = spawnedPrefabs[name];
                    animalPrefab.SetActive(true);
                    animalPrefab.transform.position = newPosition;
                    StartCoroutine(TurnOnAnimator(animalPrefab.GetComponentInChildren<Animator>()));
                }
            }
      }
```

I will try and see what dimensions of the image are my colleagues using for testing. Thanks a lot.

Quick question, would making animalPrefab the child of a GameObject that would spawn at the center of the targetImage fix this problem?

**Comment by tdmowrer** [comment]
> Quick question, would making animalPrefab the child of a GameObject that would spawn at the center of the targetImage fix this problem?

If you mean a child of the generated ARTrackedImage, then that should be effectively the same as what you have, so I don't think so. Might be easier to maintain, though, as the positional update would happen automatically.

**Comment by Sterling-Malory-Archer** [comment]
> > Quick question, would making animalPrefab the child of a GameObject that would spawn at the center of the targetImage fix this problem?
> 
> If you mean a child of the generated ARTrackedImage, then that should be effectively the same as what you have, so I don't think so. Might be easier to maintain, though, as the positional update would happen automatically.

Hi Tim, 

Thank you for the response, unfortunately, I still am experiencing the issue even though my reference image dimension matches the ones I input in the AR Reference Image Library.

**Comment by farfanRogerBrandon** [comment]
Could you fix it?
