### ISSUE TITLE
For ARKit HumanBodyTracking, is it possible for the camera feed to zoom out or in?

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#765]
For ARKit HumanBodyTracking, is it possible for the camera feed to zoom out or in?

**Comment by tdmowrer** [comment]
No; ARKit does not expose APIs to control the zoom.

**Comment by yshean** [comment]
Hi @tdmowrer, this is an important feature for my project to capture the AR scene with a little zoom out.
Do you have any suggestion or workaround to achieve that?
Hello @yosun, did you manage to do that in the end? Would love to hear your ideas even if it's not done via ARKit.

**Comment by tdmowrer** [comment]
I no longer work at Unity but I don't believe you can control physical camera zoom (though maybe that's changed in more recent versions of ARKit?).

However, if you just want to adjust the camera image that is displayed on screen, you can provide a custom material to do so. Your virtual content would no longer line up with the camera feed, though. Depends on your needs.
