### ISSUE TITLE
[Camera Projection Matrices / Intrinsics] how do you get those?

### ISSUE THREAD

**Issue by FrankSpalteholz** [Unity-Technologies/arfoundation-samples#766]
Hello, i'm wondering how do you calculate the intrinsics/projection matrices for various mobile phones and their cams (front/back)? I mean when i try to match a custom video-live-stream with 3D i'd have to first get the intrisics by shoting some chess-pattern-images first -> using matlab in a next step and let matlab calculate the camera-matrix so that i can use it later to match with opengl for example. I was alreay using ar foundation with a lot of different mobiles (iphone and android) and i was always wondering how do you guys are able to match screen-space, camera-space and projection-space (if i can call the pipeline this way)? Is the ar-foundation-system checking which device is running and using some custom "ar-foundation-build-in-matrices" or how do you do it? If this is a secret you can't tell then keep it but i'm pretty curious about it! 

Thanks again for your great work and instant response!

**Comment by tdmowrer** [comment]
The underlying AR SDK (e.g., ARKit or ARCore) computes the projection matrix. I believe they use knowledge of the specific hardware they are running on to do this, but it is opaque to AR Foundation. The specific functions we use are

* ARCore: [`ArCamera_getProjectionMatrix`](https://developers.google.com/ar/reference/c/group/ar-camera#group___ar_camera_1ga70f4fa2329d2f241a88db7b9b8dff802)
* ARKit: [`projectionMatrixForOrientation:viewportSize:zNear:zFar:`](https://developer.apple.com/documentation/arkit/arcamera/2923539-projectionmatrixfororientation?language=objc)

We use these to generate the [ARCameraFrameEventArgs.projectionMatrix](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_projectionMatrix) provided by the [ARCameraManager.frameReceived](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_frameReceived) event

**Comment by FrankSpalteholz** [comment]
Thank you Tim, this is helpful.
