### ISSUE TITLE
For ARKit Body Tracking, determine if hands are pointed up or down (holding and dropping something) 

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#769]
How do I  determine if hands are pointed up or down (holding and dropping something)?

I've tried just tracking the transform.up of the LeftHand and RightHand in the robot for 3D body tracking, but that doesn't seem to update consistently. Is there something that is more consistent for determining of a hand is pointed up (holding something) or down ( dropping something)

**Comment by yosun** [comment]
Update: in the robot example, it seems that the rotation of the LeftHand and RightHand never updates even as the wrist are turning

**Comment by tdmowrer** [comment]
I suspect this is a limitation of ARKit's body tracking feature; how do the results compare to Apple's [native app](https://developer.apple.com/documentation/arkit/content_anchors/capturing_body_motion_in_3d?language=objc)?
