### ISSUE TITLE
ARFoundation architecture

### ISSUE THREAD

**Issue by AdrianGodlewski** [Unity-Technologies/arfoundation-samples#771]
Hello,

I'm trying to understand the ARFoundation architecture. 

![image](https://user-images.githubusercontent.com/43793163/112110118-c1fdb000-8bb2-11eb-82de-0b4a2496cd3a.png)

As I understand subsystems are just some kind of interfaces that providers (provides - ARCore, ARKit) implement. So I would call ARFoundation a wrapper of those providers that talks to multiplatform API. The thing I'm wondering and I'm not 100% sure yet is the manager classes. Am I correct that the managers classes are bound to ARFoundation and they are talking to concrete providers and trackables? Why would we need subsystems then if we got manager classes? 
If You could please explain me how the architecture works, I would love to understand it.

Greetings!

**Comment by tdmowrer** [comment]
> As I understand subsystems are just some kind of interfaces that providers (provides - ARCore, ARKit) implement. So I would call ARFoundation a wrapper of those providers that talks to multiplatform API.

Yes, that's right.

> Am I correct that the managers classes are bound to ARFoundation and they are talking to concrete providers and trackables? 

I'm not sure what you mean by "bound to ARFoundation". Let's take an example:

The `ARPlaneManager` is a MonoBehaviour in AR Foundation. It manages `ARPlane`s (another AR Foundation type) by talking to the `XRPlaneSubsystem`. The `XRPlaneSubsystem` is the interface that providers like ARCore & ARKit implement.

> Why would we need subsystems then if we got manager classes?

Put another way, the subsystems are the interfaces implemented by providers while the "manager classes" are MonoBehaviours you can add in your scene.

**Comment by AdrianGodlewski** [comment]
Thanks alot, I think I understand it. 

Have a great day!
