### ISSUE TITLE
kCGColorSpaceLinearGray in unityARKit.a caused our app to crash

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#772]
Our app was support iOS9 , there are some users use it.
ARFoundation is part of our app. And it's an option feature.
**We mean ARFoundation does not need to support iOS9.**

Let iOS9 ignore `kCGColorSpaceLinearGray`! Because we found `kCGColorSpaceLinearGray` is start `iOS10+`.
> How did we discover that `kCGColorSpaceLinearGray` is in `unityARKit.a` 
> We used the `nm` and `grep` commands
```log
nm UNITY_LIBUNITYARKIT.A_PATH  -arch arm64 | grep '_kCGColorSpaceLinearGray'
Binary file ./Libraries/com.unity.xr.arkit/Runtime/iOS/Xcode1200/libUnityARKit.a matches
```

![iShot2021-03-23 17 58 49](https://user-images.githubusercontent.com/11573490/112129656-97d3de80-8c02-11eb-96c4-49ea2a617dba.jpg)

Closed issue:
https://github.com/Unity-Technologies/arfoundation-samples/issues/706#issue-772025813

**Comment by tdmowrer** [comment]
The only place this is used is already guarded by an `API_AVAILABLE` macro (which would normally be the fix for an issue like this). I also suspect `kCGColorSpaceLinearGray` is not the only problem, just the first one you are hitting.

Since we have no plans to formally support iOS 9, and we are already using the normal compatibility guards, there is not much else we can do.

**Comment by weacw** [comment]
Thank you for your reply.
Launching app was crashed, and throw exception for 'kCGColorSpaceLinearGray'.
![image](https://user-images.githubusercontent.com/11573490/112239673-df4d7f80-8c81-11eb-999e-c00810b39ddc.png)


Can we using `On-demand reference` to load `unityarkit.a` ?

**Comment by tdmowrer** [comment]
> Can we using `On-demand reference` to load `unityarkit.a` ?

Do you mean an [on-demand _resource_](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html)? libUnityARKit.a is a static library; it is linked into the app executable and cannot be installed or loaded on demand.

**Comment by weacw** [comment]
> > Can we using `On-demand reference` to load `unityarkit.a` ?
> 
> Do you mean an [on-demand _resource_](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html)? libUnityARKit.a is a static library; it is linked into the app executable and cannot be installed or loaded on demand.

Emmmm... What can we sovle this problem.
I found this post [https://www.programmersought.com/article/3081601659/] 
Does it help me？
