### ISSUE TITLE
[Bug] Can't track image after session reset.

### ISSUE THREAD

**Issue by Silverbugi** [Unity-Technologies/arfoundation-samples#774]
**Describe the bug**
When you're tracking an Image and reset the Scene via arSession.Reset(), you can't start tracking again. 
The Image is still existing in the ReferenceImageLibrary but you can't add it again to trackables. 

Look like it works on 3.1.10 but not anymore in 4.1.5

**To Reproduce**
1. Use Image Tracking sample scene
2. Track an Image successfully
3. Reset the scene with ARSession.Reset();
4. Delete Placed Gameobject
5. Try to Track the Image again

**Expected behavior**
The image should be trackable again and the prefab should instantiate

**Actual behavior**
After reset you can't track the image anymore

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 11
 - Unity version: 2020.2.1f1
 - ARFoundation version: 4.1.5

**Comment by tdmowrer** [comment]
This works fine for me. We will need a project that reproduces the issue to investigate. Please submit a bug report by following the instructions at https://unity3d.com/unity/qa/bug-reporting and post the case ID here.

**Comment by Silverbugi** [comment]
My apologies, I forgot to add one step. And I'm kind of not sure anymore if its a bug or on purpose.
I am not only reseting the scene via ARSession.Reset, I'm also destroying the instantiated prefab. 
On iOS after the reset the prefab gets instantiated again, but not on Android. 
Is that a ARCore limitation or is that really a bug?
Also, what can I do to instantiat the prefab again on Android?
If thats really a bug I will submit a bug report tomorrow

**Comment by tdmowrer** [comment]
> I am not only reseting the scene via ARSession.Reset, I'm also destroying the instantiated prefab.

That was my test as well, and I tested on Android.

> If thats really a bug I will submit a bug report tomorrow

See https://unity3d.com/unity/qa/bug-reporting. Please post the case ID here when you do.

**Comment by elliotstronge** [comment]
@Silverbugi did you find a fix for this? We're also experiencing this issue on Android.

**Comment by jackviatick** [comment]
I'm still getting this issue on android

**Comment by DavidMohrhardt** [comment]
@elliotstronge @jackviatick 

Can you provide us some details on the devices you are seeing this issue on?
