### ISSUE TITLE
Placed object lost its poition

### ISSUE THREAD

**Issue by vinayvidhani0804** [Unity-Technologies/arfoundation-samples#776]
You can use SimpleAR, Place the object over the plane, Move little far example 8-10fts, come close to object, Object drifts sometime little sometimes more about 10-12fts.

**Comment by tdmowrer** [comment]
This sounds like you are describing a general limitation of most AR frameworks. You might try placing an [ARAnchor](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARAnchor.html) at the position you are interested in tracking.

**Comment by vinayvidhani0804** [comment]
If I am not wrong you want me to use some trackable target(marker). I tried with it and also used Anchors, but no luck. May be I am not managing this correctly. I want to create one app which allow user to place some objects for example in a house user  is placing table on hall, bed in bedroom. When I go into the bedroom then bed should be at the place where I have place it and table should be at the same place where I have placed. For now I have placed table only and When I am coming from bedroom to hall then I can see the table is not exactly the same position where I have placed. Any clue on this?

**Comment by tdmowrer** [comment]
That's a difficult problem in general. ARKit supports a feature called ["world maps"](https://github.com/Unity-Technologies/arfoundation-samples#arworldmap), which lets you save an area and relocalize to it later. This may be useful depending on your exact use case. ARCore supports "cloud anchors" (available via an [extensions package](https://developers.google.com/ar/develop/unity-arf)) which also solve a similar problem.
