### ISSUE TITLE
how to get the whole tracking line of my camera pose

### ISSUE THREAD

**Issue by ar4ds** [Unity-Technologies/arfoundation-samples#778]
1. i try to tick current camera pose each frame to generate a tracking line, but always get a large gap;
2. i try to add anchor each frame, the gap fixed, but get a very low frameRate;
is there some api to get the tracking points, help~

**Comment by tdmowrer** [comment]
> i try to tick current camera pose each frame to generate a tracking line, but always get a large gap;

Sorry, I don't understand the problem you are describing. What is a "tracking line"?

> i try to add anchor each frame, the gap fixed, but get a very low frameRate;

Anchors are not lightweight objects, and I would not recommend generating one every frame.

> is there some api to get the tracking points

Do you mean the point cloud (aka feature points)? If so, see [this sample](https://github.com/Unity-Technologies/arfoundation-samples#allpointcloudpoints).

**Comment by ar4ds** [comment]
thanks @tdmowrer , "tracking line" means the historical path the user has moved, if can get more historical data like imu will be better, thank you!

**Comment by tdmowrer** [comment]
Can you describe your use case a bit more? I'm not sure what you are trying to accomplish. A diagram or video might help as well.

**Comment by ar4ds** [comment]
> Can you describe your use case a bit more? I'm not sure what you are trying to accomplish. A diagram or video might help as well.
thank you @tdmowrer , sorry for my poor description, i need the blue path, thanks!
![1_ZZRQKdFnmgU808A2zuq3fQ](https://user-images.githubusercontent.com/8132995/113394556-0830eb80-93cb-11eb-9141-5b97f0b97ca2.png)

**Comment by ar4ds** [comment]
how can i get the Movement Trajectory

**Comment by tdmowrer** [comment]
Sorry, I don't know what I'm looking at. I see blue marks with cyan lines between them. What do these represent?

**Comment by ar4ds** [comment]
![OfflineSLAMExample_01](https://user-images.githubusercontent.com/8132995/113954092-c630fb00-984b-11eb-8327-1d1c3d06eca0.png)
@tdmowrer in the picture, when the user moved from START to END, can i get the Movement Trajectory by ARCore API?

**Comment by tdmowrer** [comment]
This is not enough information for me to answer your question. I have a very vague understand of what you want to do: record the user's movement through a space. I do not understand exactly what you want to achieve or why what you have tried does not work for you.

**Comment by ar4ds** [comment]
> This is not enough information for me to answer your question. I have a very vague understand of what you want to do: record the user's movement through a space. I do not understand exactly what you want to achieve or why what you have tried does not work for you.

yes, we want reappear the user's movement, "record the user's movement through a space" is what i mean, i try record it myself, but the record data always not exactly correct,  and we tried another way, and lost frameRate.
i think there's some offical api to get the exactly correct records, but i can't fount it yet.
thanks @tdmowrer
