### ISSUE TITLE
LWRP Support could not find LightWeightPipeline

### ISSUE THREAD

**Issue by Shubham555** [Unity-Technologies/arfoundation-samples#78]
The type or namespace name 'LightweightPipeline' could not be found (are you missing a using directive or an assembly reference?)

**Comment by tdmowrer** [comment]
Can you provide more information, such as version of Unity and branch of this repo? Do you have any local modifications? I just pulled the [`lwrp_support`](https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp_support) branch and opened it in Unity 2018.3.0f2 without any warnings or errors in the Editor.

**Comment by bitfabrikken** [comment]
My guess is he's not running it with 3.3.0 of LWRP. That's one of the errors you get if you're not using 3.3.0.

**Comment by tdmowrer** [comment]
ARFoundation 3.0 provides much improved support for LWRP (now called Universal Render Pipeline). Instructions [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html).
