### ISSUE TITLE
How to convert project From Google ARCore to ARfoundation ARCore (unity.xr.arcore)

### ISSUE THREAD

**Issue by Prashant29** [Unity-Technologies/arfoundation-samples#781]
How do I...
Hello Professionals, 

I have one project in ARCore (ARCore SDK in Unity) and now I wanted to convert it to ARfoundation ARcore project. How Can I?
I do not have prior knowledge of ARCore, But I'm practicing AR Foundation. Please help me out.

let me ask Specific.

I don't know how to convert the below code:

```csharp
if(Session.Status != SessionStatus.Tracking)

if (planeGen.m_NewPlanes.Count > 0) {
    DetectedPlane first= planeGen.m_NewPlanes [0];
} // Here planeGen is DetectedPlaneGenerator

using (var image = Frame.CameraImage.AcquireCameraImageBytes())
```

Can you help me, if there is any documentation or demo kind for the Migration process?

Thanks

**Comment by ti-hardikshah** [comment]
There is no direct way to convert AR core to AR foundation !! 
1) Just list out which functionality used in AR core project.
2) Then Search "AR Foundation sample"
There are sample available for Plane tracking , Image tracking , face tracking etc !! 

Now learn that and Copy your AR Core Business logic into New AR Foundation logic. 

If you still not understand how to do !! simple hire person who do it for you !!

**Comment by tdmowrer** [comment]
> ```cs
> if(Session.Status != SessionStatus.Tracking)
> ```

```cs
ARSession.state != ARSessionState.SessionTracking
```

See the documentation [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARSession.html#UnityEngine_XR_ARFoundation_ARSession_state). There is also an [event](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARSession.html#UnityEngine_XR_ARFoundation_ARSession_stateChanged) that fires when the state changes.

> ```cs
> if (planeGen.m_NewPlanes.Count > 0) {
>     DetectedPlane first= planeGen.m_NewPlanes [0];
> } // Here planeGen is DetectedPlaneGenerator
> ```

You can enumerate all planes with the [`ARPlaneManager`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARPlaneManager.html)'s [trackables](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackableManager-4.html#UnityEngine_XR_ARFoundation_ARTrackableManager_4_trackables) property. This works for any trackable manager.

> ```cs
> using (var image = Frame.CameraImage.AcquireCameraImageBytes())
> ```

See ["Accessing the device camera image on the CPU"](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/cpu-camera-image.html) and the [CpuImages sample](https://github.com/Unity-Technologies/arfoundation-samples#cpuimages).

**Comment by Prashant29** [comment]
Thanks so much, @tdmowrer, You are a lifesaver :), Also Thanks @ti-hardikshah for the right direction.
