### ISSUE TITLE
What is the Pass-through video

### ISSUE THREAD

**Issue by weacw** [Unity-Technologies/arfoundation-samples#782]
![image](https://user-images.githubusercontent.com/11573490/112970518-dcbac080-9180-11eb-8886-08ae280c1be5.png)

I dont know what is the `Pass-through video`
1. When to use it? 
2. What can it be used for?

**Comment by KirillKuzyk** [comment]
It means these devices have cameras and AR Foundation can access the video stream.

**Comment by weacw** [comment]
> It means these devices have cameras and AR Foundation can access the video stream.

Thank you!
