### ISSUE TITLE
How to determine when tracked images are not visible

### ISSUE THREAD

**Issue by kordou** [Unity-Technologies/arfoundation-samples#784]
Hi I am trying to make an app for android and Ios with image tracking. 

I have made a script to control many targets with many objects and it works (overlay content over different images) but the content never hides (even when the target is not in the frame

I am listening to the ARTrackedImageManager.trackedImagesChanged in order to see if the image is added/updated/removed

the added and the update works but the removed does not show my target never hides ( i do than in remove) 

How can I solve this? 

I have read in a forum that I need to listen to listen the tracking state of the image but i cannot find how to do this
and if i build for two platforms (Ios and Android) Do i have to do it with different ways ?

thank you

**Comment by tdmowrer** [comment]
Have you seen https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/tracked-image-manager.html#determining-when-an-image-is-visible ?

**Comment by kordou** [comment]
Hi tdmowrer
yes That was what I have read, but still, it does not have a simple example to understand the event that I have to register to

**Comment by kordou** [comment]
Finally, i found the solution... 

for anyone else that have the same issue here is the answer

OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs eventArgs) {
      // this is triggered when a new image is adde to the library
      foreach (var trackedImage in eventArgs.added)
      { 
              UpdateARObjects(ARTrackedImage trackedImage) 
      } 
      
      // this is triggered when a new image is updated to the library
      foreach (var trackedImage in eventArgs.updates)
      { 
              UpdateARObjects(ARTrackedImage trackedImage) 
      } 

      // this is triggered when a new image is removed fro the library
      foreach (var trackedImage in eventArgs.removed){} 
}

void UpdateARObjects(ARTrackedImage trackedImage)
{
    if (trackedImage.trackingState != TrackingState.Tracking) 
    {
        // here is the code when the targer image is not visible   
    } else
    {
         // here is the code when the target image is visible
    }
}

**Comment by tdmowrer** [comment]
> it does not have a simple example to understand the event that I have to register to

Did you see the code example titled ["Responding to detected images
"](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/tracked-image-manager.html#responding-to-detected-images) on the same page? It looks very similar to the code you posted.
