### ISSUE TITLE
Assets\Scenes\ARCore\ARCoreSessionRecorder.cs(57,9): error CS0246: The type or namespace name 'ArStatus' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by Vignesh-J07** [Unity-Technologies/arfoundation-samples#787]
Mm Like Iam missing some reference . Can anyone knows how to fix this error
![Capture](https://user-images.githubusercontent.com/65885151/113487953-a363b700-94d8-11eb-9352-d583f1cd2b7f.PNG)

**Comment by tdmowrer** [comment]
Those types are in the latest SDK. Perhaps you copied some sample scripts from this repo without grabbing the latest packages?

**Comment by marcusx2** [comment]
It solved the problem, but none of this is obvious. When we install the ARFoundation package, it points to this github repo, but then after dragging the assets folder to the project we get tons of errors because it's not supported! Each version of ARFoundation should point to a supported sample package...we don't expect to face a wall of errors after importing the samples.

**Comment by Vignesh-J07** [comment]
In Unity 2020 there is no tracked pose manager class, But its available in XR legacy input helpers package in 2019.4. So can I find that Class in 2020 version

**Comment by Vignesh-J07** [comment]
Thank you for the reply, But this is AR core sdk which I have used here
showing up these errors it's not in ARFoundation Package

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tdmowrer** [comment]
> In Unity 2020 there is no tracked pose manager class, But its available in XR legacy input helpers package in 2019.4. So can I find that Class in 2020 version

The [Legacy Input Helpers package](https://docs.unity3d.com/Packages/com.unity.xr.legacyinputhelpers@2.1/manual/index.html) is available in Unity 2019 LTS and later, and it is an indirect dependency of AR Foundation. I'm not sure what you are looking for, though. Can you be more specific (e.g., a class name or specific error message)?

> Thank you for the reply, But this is AR core sdk which I have used here showing up these errors it's not in ARFoundation Package

Sorry, I don't know what that means. This repository is a complete Unity project. It is meant to be cloned and opened as a standalone project. Can you describe what you are trying to do?

**Comment by Vignesh-J07** [comment]
Thank you the problem is with the version of the ar foundation package and the versions of the samples downloaded in the githb repo is not the same. Downloaded the correct version solved my error. Thank you

**Comment by tdmowrer** [comment]
There is a branch of this samples repo for each verified version of AR Foundation, as well as a [table in the README](https://github.com/Unity-Technologies/arfoundation-samples#what-version-should-i-use).

**Comment by Vignesh-J07** [comment]
yeah thank you @tdmowrer

**Comment by hgoel012** [comment]
Hie, I am getting the following error, after installing and upgrading all AR settings as well.

Assets\arfoundation-samples-main\ARF Assets\Scenes\ARCore\ARCoreSessionRecorder.cs(57,9): error CS0246: The type or namespace name 'ArStatus' could not be found (are you missing a using directive or an assembly reference?)

Any suggestions?
