### ISSUE TITLE
ARFoundation Unity Workshop tutorial

### ISSUE THREAD

**Issue by whitequill** [Unity-Technologies/arfoundation-samples#788]
I started to do a tutorial from [The Unity Workbench for ARFoundation](https://www.youtube.com/watch?v=Ml2UakwRxjk).
It is dated and the script written in the video isn't representative of what is currently in Unity. I have updated the script [ARTapToPlaceObject](https://gist.github.com/whitequill/b46dbf3ac378cabea840d881a2a3eef0) to work in the current version of Unity. 
The script isn't working right!
I am stuck on why I'm getting the following error:`Assets/ARTapToPlaceObject.cs(11,50): error CS1001: Identifier expected`.

I have included a zip file with my scene: https://mega.nz/file/EQ5w2CBA#iXCL6wSy_KTmxcNtbeWS3lfo_GZr1QM_z1gwj4OfJ1E

The model is freely available here: [Toy plane](https://sketchfab.com/3d-models/toy-plane-9b4e13700da14d31b9d923c499e18f64)

**Comment by tdmowrer** [comment]
That tutorial isn't by Unity. It appears to be associated with this GitHub project: https://github.com/TheUnityWorkbench/tuw-arfoundation-demo. I would suggest creating an issue on their GitHub page, but it doesn't look like it is actively maintained.

Have you tried the samples in this repo? The SimpleAR sample has "tap to place" style logic.

**Comment by whitequill** [comment]
should I post this question on stackoverflow? The only reason I posted it here is someone else posted a different question:
[Error updating ARSessionOrigin to ARRaycastManager
](https://github.com/Unity-Technologies/arfoundation-samples/issues/226). So I felt it was relevant to post here.

**Comment by tdmowrer** [comment]
If you are new to AR Foundation and trying to learn, there are official Unity Learn resources here: https://learn.unity.com/tutorial/setting-up-ar-foundation, and the samples in this repo are meant to demonstrate the use of specific SDK features. An unmaintained 3rd party tutorial from a couple years ago doesn't seem like the best place to start unless there is something very specific you are trying to achieve, in which case I'd like to understand what it is so we can make our resources better.

If you want to pursue the "Unity Workbench" tutorial, you might try the [Unity AR forum](https://forum.unity.com/forums/ar.161/) for community support. These GitHub Issues are more appropriate for issues related to the AR Foundation SDK or questions regarding the samples in this repo.

**Comment by whitequill** [comment]
@t-oshita thank you. I'll check the **Unity AR forum** for help. As the link you gave me didn't tell me anything that I don't already know.
I'm trying to find the new C# API calls that are in XR because all the calls are outdated and most don't exist in the tutorial anymore.

**Comment by whitequill** [comment]
Thank you for suggesting the AR forum.
