### ISSUE TITLE
How to add to CollaborationData Queue

### ISSUE THREAD

**Issue by methot-ilya-3ds** [Unity-Technologies/arfoundation-samples#790]
In order to expand on the current features of CollaborationSession it would be useful to be able to add our own events to be transmitted over a network. I've created my own instances of ARCollaboration data that I would like to send across the network using MCSession.SendToAllPeers(), however I would prefer to add the collaboration data to the existing CollaborationData Queue.

Given the current samples that have been provided, it is unclear exactly where or how to add data to the collaboration queue. 

Is there any reason why I would not be able to add my own custom information to the queue? If this is possible, where is the method for adding data to the queue?

**Comment by tdmowrer** [comment]
What do you mean by your "own instances of ARCollaboration data"? [ARCollaborationData](https://developer.apple.com/documentation/arkit/arcollaborationdata) is a data type specific to ARKit's collaborative session feature, so it doesn't make sense to have a "custom" `ARCollaborationData`.

If your intent is to send your own data specific to your application, you can use the MCSession to do so. `MCSession.SendToAllPeers()` lets you send arbitrary [NSData](https://developer.apple.com/documentation/foundation/nsdata?language=objc), which is just a binary data blob. You can use MCSession to send whatever you like in this way (see, for example, [NSData.CreateWithBytesNoCopy](https://github.com/Unity-Technologies/arfoundation-samples/blob/189f6cff825520a39a0608e6f8674d2cdb9e1859/Assets/Scripts/Multipeer/NSData.cs#L28)).

The "collaboration data queue" is just a list of unconsumed `ARCollaborationData`s that ARKit has provided. It has nothing to do with the data sent using MCSession.

**Comment by methot-ilya-3ds** [comment]
I understand that I have to create my own packaged data to be sent over the network. I also understand that MCSession.SendToAllPeers() is the way to go about doing that.

What is not clear is how you are sending this data in the CollaborativeSession example.

In the CollaborativeSession example the primary data that is being sent over the network is:

1. The worldspace information
2. The transform information of the created anchors.

Yet nowhere in the code is there a reference to either of these being sent over a network using the MCSession. I wanted to use your technique for sending the information as a reference but I can't seem to find the point where you package and send the anchors or the worldspace information.

In the example, the only point that I can identify where collaboration data is being sent from is in the CollaborativeSession.cs script. The script references the subsystem.DequeueCollaborationData() and uses that queue to send and receive data. 

Where in the example do the AR Anchors or worldspace information get packaged and sent over the network?

CollaborativeSession.cs:

```
// Check for new collaboration data
            while (subsystem.collaborationDataCount > 0)
            {
                using (var collaborationData = subsystem.DequeueCollaborationData())
                {
                    CollaborationNetworkingIndicator.NotifyHasCollaborationData();

                    if (m_MCSession.ConnectedPeerCount == 0)
                        continue;

                    using (var serializedData = collaborationData.ToSerialized())
                    using (var data = NSData.CreateWithBytesNoCopy(serializedData.bytes))
                    {
                        m_MCSession.SendToAllPeers(data, collaborationData.priority == ARCollaborationDataPriority.Critical
                            ? MCSessionSendDataMode.Reliable
                            : MCSessionSendDataMode.Unreliable);

                        CollaborationNetworkingIndicator.NotifyOutgoingDataSent();

                        // Only log 'critical' data as 'optional' data tends to come every frame
                        if (collaborationData.priority == ARCollaborationDataPriority.Critical)
                        {
                            Logger.Log($"Sent {data.Length} bytes of collaboration data.");
                        }
                    }
                }
            }
```

**Comment by tdmowrer** [comment]
> Where in the example do the AR Anchors or worldspace information get packaged and sent over the network?

That information is encoded into the ARCollaborationData produced by ARKit. It is an opaque type; there is no way to manipulate an instance of ARCollaborationData. Only ARKit "knows" how to extract that information.

We do serialize the ARCollaborationData to a byte array (the call to `ToSerialized`); however, this doesn't require any understanding of the data format and can be be done with any Objective-C type that conforms to the [NSCoding protocol](https://developer.apple.com/documentation/foundation/nscoding?language=objc), which ARCollaborationData does (see also [NSKeyedArchiver](https://developer.apple.com/documentation/foundation/nskeyedarchiver?language=objc) & [NSKeyedUnarchiver](https://developer.apple.com/documentation/foundation/nskeyedunarchiver?language=objc)).

All we're doing in this sample is retrieving the ARCollaborationData from ARKit, serializing it to a byte array using an NSKeyedArchiver, and then passing it to the MCSession. If you want to use MCSession with your own data, you will need to come up with a scheme to serialize it to a byte array. The BinaryFormatter may help; see https://answers.unity.com/questions/1320236/what-is-binaryformatter-and-how-to-use-it-and-how.html. There are also solutions available on the [Asset Store](https://assetstore.unity.com/).

**Comment by methot-ilya-3ds** [comment]
@tdmowrer Thank you for the advice from earlier. I've restarted this process using a BinaryFormatter like you suggested. I then use the ARCollaborationData methods to serialized the byte[] that I've created and attempt to send that through MCSession.

It seems that I am close to success, however when I go to create the ARCollaborationData using my byte array, the created ARCollaborationData.valid is always false. I can't track down exactly where the process is failing. I understand that the problem may be related to how I am serializing the class...but I've found that at least in the editor I am able to serialize and de-serialize the class with no loss of data. 

I can't seem to find why my ARCollaborationData is false!

```
[System.Serializable]
public class BoxSender
{
    public float x, y, z;

   private void Start()
   {
       GameObject Box = GameObject.FindWithTag("Box");
       x = Box.transform.position.x;
       y = Box.transform.position.y;
       z = Box.transform.position.z;
       Debug.Log("Position is: " + x + y + z);
    }

   public byte[] Serialize()
   {
       using (MemoryStream m = new MemoryStream())
       {
           using (BinaryWriter writer = new BinaryWriter(m))
           {
               writer.Write(x);
               writer.Write(y);
               writer.Write(z);
            }
           return m.ToArray();
       }
   }

   public static BoxSender Deserialize(byte[] data)
   {
       BoxSender result = new BoxSender();
       using (MemoryStream m = new MemoryStream(data))
       {
           using (BinaryReader reader = new BinaryReader(m))
           {
               result.x = reader.ReadInt32();
               result.y = reader.ReadInt32();
               result.z = reader.ReadInt32();
            }
       }
       return result;
   }
```
```
 BoxSender NewSender = new BoxSender();
Debug.Log("BoxSender being sent:" + NewSender);
byte[] CollabBoxByte = NewSender.Serialize();
Debug.Log("Bytes to convert" + CollabBoxByte);
ARCollaborationData CollabBoxAR = new ARCollaborationData(CollabBoxByte);
if (CollabBoxAR.valid)
{
    SerializedARCollaborationData CollabBoxARSerialized = CollabBoxAR.ToSerialized();
    NSData CollabBoxAR_NSData = NSData.CreateWithBytesNoCopy(CollabBoxARSerialized.bytes);
    m_MCSession.SendToAllPeers(CollabBoxAR_NSData, CollabBoxAR.priority == ARCollaborationDataPriority.Critical
                                            ? MCSessionSendDataMode.Reliable
                                            : MCSessionSendDataMode.Unreliable);
}
else
{
    Debug.Log(CollabBoxAR + "is not valid");
}
```

**Comment by tdmowrer** [comment]
> when I go to create the ARCollaborationData using my byte array, the created ARCollaborationData.valid is always false.

I think you are confusing `ARCollaborationData` and `MCSession`. `ARCollaborationData` is a specific type in ARKit. Your serialized `BoxSender` bytes can be wrapped in an `NSData` and passed to the `MCSession`. You shouldn't try to construct an `ARCollaborationData`.

Also, you are leaking the `NSData` object that you create. Consider using a `using` statement.

**Comment by methot-ilya-3ds** [comment]
I understand that the ARCollaborationData type is not necessary for my data, however I am having so much difficulty converting the Class -> byte[] -> NativeSlice<T> -> NSData and back again that I thought it might be best to use the ARCollaborationData methods for the data processing.

When I go ahead and try to run the conversions myself I have trouble understanding exactly what is going on, especially because I am unable to follow the debugging process very closely through the XCode build. 

You mention that I should simply wrap the serialized bytes in NSData yet to me the process seems more involved and I can't wrap my head around it. Do you have any advice on that front as well?

Thank you very much for your time and help.

```
byte[] CollabBoxByte = NewSender.Serialize();
            var byteArr = new NativeArray<byte>(CollabBoxByte, Allocator.Temp);
            var slice = new NativeSlice<byte>(byteArr).SliceConvert<byte>();
            using (NSData CollabBoxAR_NSData = NSData.CreateWithBytes(slice)) {

                        m_MCSession.SendToAllPeers(CollabBoxAR_NSData, 0);
                        byteArr.Dispose();
            }
```

**Comment by tdmowrer** [comment]
> I thought it might be best to use the ARCollaborationData methods for the data processing.

ARCollaborationData can't be used generically. Only ARKit can produce a new one, and you can only convert raw bytes to an ARCollaborationData if those bytes were serialized from an existing ARCollaborationData.

Let's forget that it's an AR app for the moment. The problem you're trying to solve is to serialize an instance of your class into bytes and then transmit those bytes using an MCSession; ARCollaborationData won't help you here :)

> I am having so much difficulty converting the Class -> byte[] -> NativeSlice -> NSData and back again

A `NativeSlice<T>` is just a view into raw memory. It stores a pointer and a length, but it doesn't own the memory. It's sort of like a [`Span<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-5.0).

MCSessions work with NSData, so you need to construct an NSData from your bytes. All the MCSession and NSData stuff is just sample code, not AR Foundation, so feel free to add or modify methods as it makes sense. If you want to use the existing methods provided by the sample, the simplest way is probably to create a NativeSlice directly from your byte array, which can be done using [`NativeSliceUnsafeUtility.ConvertExistingDataToNativeSlice`](https://docs.unity3d.com/ScriptReference/Unity.Collections.LowLevel.Unsafe.NativeSliceUnsafeUtility.ConvertExistingDataToNativeSlice.html):

```cs
fixed (byte* ptr = CollabBoxByte)
{
    var slice = NativeSliceUnsafeUtility.ConvertExistingDataToNativeSlice<byte>(ptr, 1, CollabBoxByte.Length);
    using var data = NSData.CreateWithBytesNoCopy(slice);
    m_MCSession.SendToAllPeers(data, 0);
}
```

Alternatively, you could change the existing private NSData method that takes a raw pointer and length to public:

```cs
[DllImport("__Internal", EntryPoint="UnityMC_NSData_createWithBytesNoCopy")]
static extern unsafe IntPtr CreateWithBytesNoCopy(void* bytes, int length, bool freeWhenDone);
```

And then you wouldn't need to deal with NativeSlices at all.

**Comment by methot-ilya-3ds** [comment]
Thank you for the advice! I was finally able to get my data to send correctly between the two devices!

It seems like using the _fixed_ for the ptr solved a lot of the NullData errors that I was encountering.

Thanks for your time and support!
