### ISSUE TITLE
Is it possible to detect hand gesture in AR mode?

### ISSUE THREAD

**Issue by peterchen2001** [Unity-Technologies/arfoundation-samples#791]
With AR Foudation in andriod, is it to detect hand gesture? My scenario is like this, I place a dinosaur on the plane in front of my cellphoe, then I do a 'push' behavior with my right hand(the hand is in the camera view), how to make my app know that i do a 'push' behavior and then push the virtual dinosaur. Any clue to make this function using AR Foudation?

**Comment by tdmowrer** [comment]
AR Foundation does not support this, no. For Android specifically, AR Foundation relies on ARCore, so ARCore would need to support this. You might try creating a feature request at https://github.com/google-ar/arcore-unity-sdk/issues

**Comment by peterchen2001** [comment]
Thanks for your reply.
