### ISSUE TITLE
How to send Position/orientation of each device on another device using ARCollaborationExampleScene.

### ISSUE THREAD

**Issue by muxavir** [Unity-Technologies/arfoundation-samples#793]
While using 2 testing devices I want to display position/orientation of each device on other device. I can see the anchors being shared in a same session, however I want to go one step ahead by sending/receiving position/orientation of Mobile Device (Probably Camera) in Real World Space. 
Can you please point out specific class or function where I can write this specific code? 
Thanks

**Comment by tdmowrer** [comment]
The pose of each device in a collaborate session is managed by the [ARParticipantManager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/participant-manager.html). In the `ARCollaborationDataExample` scene, the ARSessionOrigin has an ARParticipantManager that instantiates and updates a prefab for each participant.

To programmatically access this information, you can subscribe to the [`participantsChanged`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARParticipantManager.html#UnityEngine_XR_ARFoundation_ARParticipantManager_participantsChanged) event or enumerate all participants with the `[trackables](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackableManager-4.html#UnityEngine_XR_ARFoundation_ARTrackableManager_4_trackables)` property.
