### ISSUE TITLE
AR Image Tracking with transparent image

### ISSUE THREAD

**Issue by stetttho** [Unity-Technologies/arfoundation-samples#794]
It would be nice to be able to use pngs with transparency as tracked image. only the non transparent areas should be used for the tracking, making it possible to detect the image with any content in the transparent areas.

Example:

<img src="https://user-images.githubusercontent.com/32513612/114393227-1389d100-9b9a-11eb-8534-d6454e2fb76f.png" width="200">

should be recognized on:
<img src="https://user-images.githubusercontent.com/32513612/114393317-2bf9eb80-9b9a-11eb-91ca-276ffd3f4a90.png" width="200">

or is this not possible from ARKit / ARCore side?

**Comment by tdmowrer** [comment]
Neither ARCore nor ARKit support this; both ignore transparent pixels.

Image tracking is feature point-based, meaning it isn't necessarily looking for the exact image, but rather the feature points it is likely to extract from what the ARSession "sees" in the environment. With this in mind, it seems to me that it would be very difficult to handle transparency in the way you expect it to work.

You could try making this feature request at https://github.com/google-ar/arcore-unity-sdk and/or https://developer.apple.com/bug-reporting/ to let Google and Apple know you are interested in this feature.

**Comment by stetttho** [comment]
Thanks a lot for your insightful reply.
