### ISSUE TITLE
I'm trying to learn VR, And the XR plugin Management isn't working. I'm using unity 2019.3.8.f1

### ISSUE THREAD

**Issue by Phoenixnigh** [Unity-Technologies/arfoundation-samples#795]
When I go to download XR plugin management but, it says downloading but then it freezes and looks nothing like the tutorial I'm watching, any suggestions? 
![2021-04-14 (1)](https://user-images.githubusercontent.com/82551456/114797541-6661b500-9d61-11eb-9848-b6625c77142f.png)

**Comment by tdmowrer** [comment]
What tutorial are you watching? 2019.3 is no longer supported. I suggest using either 2019.4 LTS* or 2020.3 LTS.

You mentioned trying to learn VR -- this GitHub issues page is specifically for AR Foundation, an AR SDK. If you do mean VR and not AR, then I suggest trying this forum: https://forum.unity.com/forums/vr.160/

\* LTS stands for "long-term support"

**Comment by Phoenixnigh** [comment]
Thank you. I'll go check that out now.
