### ISSUE TITLE
[Bug] Iphone Depth Image for hand stencil does not line up with camera feed vs Ipad

### ISSUE THREAD

**Issue by ROBYER1** [Unity-Technologies/arfoundation-samples#796]
Description
When testing the AR Foundation Samples repo on an ipad and iphone (as well as using the depth images in our own apps), we noticed that the Hand stencil never lines up with the camera feed in AR properly on Iphones, but on Ipad the hand stencil matches the camera feed perfectly.

I have made a video of this below, you can easily see this if you overlay the hand stencil texture with the AR Camera background itself or if you simply pay attention to where my fingers are near the edges of the screen, the stencil is quite far off on Iphone and it is causing us issues in our apps.

I made an example video of this below

1. Build the Depth Images sample scene to an iphone 11 and any supported ipad separately
2. Using the human hand stencil sample, try the different resolutions on iphone vs ipad and move your fingers to the edge of the screen to see that the Ipad stencil matches the onscreen ar camera background perfectly but the Iphone 11 stencil fingers are quite far off from the screen edge vs the onscreen AR Camera background feed of your hand.

**Expected behavior**
This is causing real issues in an app where we are using these depth maps for cutouts, where on ipad during development it has worked fine but our iphone testers very quickly pointed out that the hand cutout was not lining up with their hand onscreen at all.

**Actual behavior**
Iphone hand stencil does not match AR Camera background feed at all, works perfectly fine on Ipad though

Example:
https://user-images.githubusercontent.com/10745594/115007100-88fae780-9ea1-11eb-99d3-fcdb10f56dd2.mov

**Smartphone (please complete the following information):**
 - Device: Iphone 11
 - OS: iOS 14.4
 - Unity version 2020.3.0f1
 - ARFoundation version 4.1.5

**Comment by KirillKuzyk** [comment]
I think this is an expected behavior:
https://forum.unity.com/threads/iphone-depth-image-for-hand-stencil-does-not-line-up-with-camera-feed-vs-ipad.1094218/#post-7046194

**Comment by ROBYER1** [comment]
> I think this is an expected behavior:
> https://forum.unity.com/threads/iphone-depth-image-for-hand-stencil-does-not-line-up-with-camera-feed-vs-ipad.1094218/#post-7046194

That is my forum post there asking about this, I was just about to post it back here. If it is an expected behaviour, what can be done to make the stencil texture usable as a cutout or overlay on top of the AR Camera feed if the two do not match up very well?

**Comment by ROBYER1** [comment]
If Unity staff do reply here, the main thing I am doing is:

I currently have a shader graph where I nab the AR Camera Background renderer texture using:

Code (CSharp):
Graphics.Blit(null, targetRenderTexture, m_ARCameraBackground.material);

Then separately, using the DisplayDepthImage.cs script from ARF samples, I save out that onscreen hand stencil texture to the same shader graph and overlay them buuut... obviously things do not line up on iphone. It works fantastic on ipad which is annoying.

**Comment by tdmowrer** [comment]
As @KirillKuzyk points out, the raw camera image is not the same aspect ratio as the screen, though it is probably closer to an iPad's aspect ratio than to an iPhone's. This explains why it appears to "work" on your iPad.

There are a few discussions of this here; see, for example, https://github.com/Unity-Technologies/arfoundation-samples/issues/756

For help with shader graph specifically, you might try the shader graph forum: https://forum.unity.com/forums/shader-graph.346/

**Comment by ROBYER1** [comment]
> As @KirillKuzyk points out, the raw camera image is not the same aspect ratio as the screen, though it is probably closer to an iPad's aspect ratio than to an iPhone's. This explains why it appears to "work" on your iPad.
> 
> There are a few discussions of this here; see, for example, #756
> 
> For help with shader graph specifically, you might try the shader graph forum: https://forum.unity.com/forums/shader-graph.346/

Thanks for the reply, effectively I just want to know how to use the Matrix 4x4 from the AR Camera Background with Shader Graph? As I assume AR Foundation is fully supporting URP already and going forward, is there no working example already of how to recreate the AR Camera Background material in shader graph as I have already seen it is written in normal old school shader code which is difficult to translate to shader graph

**Comment by ROBYER1** [comment]
It also raises the question of how useful are the samples if they provide a depth image that never matches up properly with the camera feed on IOS iphone devices where one would ideally use the stencil mask to apply effects over the hand segmented out by the stencil or apply cutout effects? I just want to line the stencil up with the AR camera Background image to cut out the hand as an effect in our apps

**Comment by tdmowrer** [comment]
The sample you are looking at is designed to show the raw depth image. The shaders that we include in the ARCore and ARKit packages use the display matrix to correctly transform the depth image for stencil and occlusion; you just need to add the AROcclusionManager to the camera (the SimpleAR scene does this, for example).

We do not have an example that uses shader graph to achieve this same effect. However, it sounds like what we do provide should do what you want. Is there a reason the shaders we include do not work for your use case?

**Comment by ROBYER1** [comment]
Currently I am taking the Texture2D displayTexture from https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/DisplayDepthImage.cs, running it through a chroma key cutout asset using the black colour as the alpha then  assigning it to a 'background' (used as cutout/opacity)texture slot on my shadergaph for the stencil to use as opacity leaving just the red cutout as full colour and black masked as opacity.

For the actual hand from the camera feed, I take the AR Camera Background renderer texture using : Graphics.Blit(null, targetRenderTexture, m_ARCameraBackground.material) to pump the AR camera background texture into a rendertexture assigned to the main texture slot on my shadergraph

This material is just used on a RawImage component on some UI over the top of various other things in the UI that the hand cutout needs to be over the top of for pointing, making hand gestures etc.

<img width="585" alt="Screenshot 2021-04-17 at 17 37 30" src="https://user-images.githubusercontent.com/10745594/115120195-1161b100-9fa4-11eb-9c97-8f472dfb207e.png">

I can see later in DisplayDepthImage.cs script you do this in UpdateRawImage() -  
`// Update the raw image dimensions and the raw image material parameters.
            m_RawImage.rectTransform.sizeDelta = rectSize;`

Which I have commented out anyway - I was thinking more about this just now as even if I uncomment out that to allow the rawimage with my shader graph material to be scaled by the depth script, it will still be wrong as the textures going into my shadergraph from both of those sources do not line up on an iphone at all as you can see below from the depth sample scene in this samples repo. when my hand is near the edge of the screen, in the AR Camera Background material texture onscreen, it is cropped off on the sides while in the stencil image texture, my hand is nowhere near as cropped and my thumb is fully visible.

I hope this makes sense, I am just trying to find out the best way to get these two textures to line up on Iphones as they already line up fine on Ipad due to the aspect ratio already, preferably just on the texture level as we are using shader graph for various other features in the app to hide/show masks or switch out from the current hand stencil effect to a different one on other devices.

![Handy1](https://user-images.githubusercontent.com/10745594/115120336-da3fcf80-9fa4-11eb-8a6a-9f7877c95902.gif)

**Comment by ROBYER1** [comment]
You can also see here I took some screenshots, this is just the original samples scene- the Rawimage texture on the top left of the stencil is always far off what the hand on screen is like aspect-ratio wise, that is where I am saying the textures I am grabbing in the methods from my post above do not line up at all. 

What can I do about this? I am using Shader Graph as it is quick to change things there and see what the nodes in the shader are doing, however it is quite tough to figure out a good way to handle a hand cutout using ARKit Hand Stencil if the textures for AR Camera Background and ARKit Hand Stencil are so far off from lining up well on Iphones only while they match up on Ipad.

I made this comparison to show the three different sizes I get on an Iphone 11 and none of the stencils match what AR Camera Background is showing me on screen in the Samples repo scene for this.

![Handz](https://user-images.githubusercontent.com/10745594/115124085-4841c200-9fb8-11eb-876a-edc5d996a429.jpg)

**Comment by tichise** [comment]
This problem does not appear to have been resolved in the latest version of ARFoundation.

**Comment by tichise** [comment]
I probably solved this problem because the image I could get from TryAcquireHumanStencilCpuImage contained a wider range of information than the screen size in my case.In both cases, I solved the problem by doing the following.

The humanStencil needs to be the same ratio as the ScreenSize, and the outputDimensions needs to be changed to match the aspect ratio of the ScreenSize, and the width or height needs to be passed to the outputDimensions.

Since there is too much information in the humanStencil, it is necessary to obtain the information for the screen size from it, and this can be done with inputRect. I performed this process in a horizontal layout, so I adjusted the second and fourth arguments of RectInt.

おそらく私はこの問題を解決しました。TryAcquireHumanStencilCpuImageから取得できる画像は私のケースの場合画面サイズより広範囲の情報を含んでました。humanStencilとDepthどちらのケースでも、以下のようにすることで解決しました。

humanStencilはScreenSizeと同じ比率にする必要がある。outputDimimensionsではScreenSizeの縦横比率に合わせた値に変えて、widthかheightを渡してあげる必要がある。

humanStencilは情報量が多すぎるので、その中からスクリーンサイズ分の情報を取得する必要があり、その処理はinputRectで行える。私は横レイアウトで今回の処理を行ったので、RectIntの第二引数と第四引数を調整した。

My Code
```
		if (!occlusionManager.TryAcquireHumanStencilCpuImage(out XRCpuImage humanStencilCpuImage)) {
            return;
        }

		XRCpuImage.Transformation imageTransformation = GetImageTransformation();

        int adjustedCpuImageHeight = (int)((float)humanStencilCpuImage.width / (float)Screen.width * (float)Screen.height);

		int startY = (humanStencilCpuImage.height - adjustedCpuImageHeight) / 2;

		var conversionParams = new XRCpuImage.ConversionParams
        {
            inputRect = new RectInt(0, startY, humanStencilCpuImage.width, adjustedCpuImageHeight),
            outputDimensions = new Vector2Int(humanStencilCpuImage.width, adjustedCpuImageHeight),
            outputFormat = humanStencilCpuImage.format.AsTextureFormat(),
            transformation = imageTransformation
        };

        int size = humanStencilCpuImage.GetConvertedDataSize(conversionParams);
```

I hope this comment helps someone.

**Comment by dogadogan** [comment]
@tichise, could you please also share the `GetImageTransformation()`? :)
