### ISSUE TITLE
Assets\Scripts\CameraController.cs(8,22): error CS0234: The type or namespace name 'ARExtensions' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by DaphiFluffi** [Unity-Technologies/arfoundation-samples#797]
Versions:
- Unity 2019.4.8f1
- AR Core XR Plugin: 3.0.1
- AR Foundateion: 3.0.1
- AR Subsystems 3.0.0
- XR Plugin Management: 3.2.13
- Visual Studio Code Editor: 1.1.4

I have cloned this repository https://github.com/shaqian/TF-Unity-ARFoundation and wanted to start the Demo Scene. But no matter which versions I install, I get the Error in the title. 

All help is appreachiated.

**Comment by tdmowrer** [comment]
The error looks like a sample script was authored for an earlier version of AR Foundation while the project is using later (incompatible) packages.

This GitHub issues page is for issues related to AR Foundation packages or the samples in this repo. If you're having trouble with a third party repo, I suggest creating an [issue on their project](https://github.com/shaqian/TF-Unity-ARFoundation/issues).

If you are new to AR Foundation, I recommend the samples in this repo as a starting point. If you are trying to learn a specific aspect of AR Foundation that isn't covered by our samples, please let us know what it is.

**Comment by tdmowrer** [comment]
See also https://github.com/shaqian/TF-Unity-ARFoundation/issues/5

**Comment by DaphiFluffi** [comment]
Hi @tdmowrer, 

Thank you for answering. For anyone else having trouble with this ,downloading Unity 2018.3.6f1 and installing AR Foundation 1.0.0 preview 22 solved the error as mentioned here:  [shaqian/TF-Unity-ARFoundation#5.](url) 
Unfortunately, this just brought up new errors, but I would consider this issue to be closed.
