### ISSUE TITLE
Prevent the real object while plane tracking 

### ISSUE THREAD

**Issue by Pankaj68** [Unity-Technologies/arfoundation-samples#798]
https://user-images.githubusercontent.com/82649539/115231683-75ff4600-a133-11eb-8234-8e2637821828.mov

Hi

how can i prevent the real object while the plane tracking. if i am tracking the plane (Both Vertical and horizontal) then real object like Laptop, Chair ,TV and AC on this object the plane will not draw but it will draw plane around them
i am attaching the the reference video so you can understand what i mean to say.

**Comment by tdmowrer** [comment]
I'm not sure that I understand your question; are you asking how to turn off occlusion? If so, simply disable the AROcclusionManager component on the camera. See the "Automatic occlusion" section of https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/index.html#scene-setup for more details.

**Comment by Pankaj68** [comment]
i just want to track the plane and changes its materials but when i am tracking the plane and changes its materials at the time the real object of the world will exclude from that. i have also attached the video for that for you better understanding.

if you saw in the video it only changes the color of wall not the switch board so i want to do that in which people can scan the wall or floor and change the plane materials on that but object like switchboard, AC and Laptop on that the plane material exclude them and change the materials around them.

**Comment by tdmowrer** [comment]
Is the video demonstrating what you want to achieve, or is it the behavior you want to avoid?

In other words, is the desired behavior
1. That the switches would also also become green OR
2. That only the wall changes color (like in the video)

**Comment by Pankaj68** [comment]
Yes 
in the video which demonstrating that what  i want to achieve.
how can i do that?

**Comment by tdmowrer** [comment]
The `AROcclusionManager` which I mentioned earlier performs depth test with real objects in the scene so they can occlude virtual content in your app. There is a sample in this repo: https://github.com/Unity-Technologies/arfoundation-samples#simpleocclusion

Do you know what technology was used to create the app in the video? I noticed it updates the wall color infrequently (perhaps about once per second) which suggests they are doing additional processing to achieve a good result.

**Comment by Pankaj68** [comment]
Hi,
I don't know which technology they used in the app i also noticed the same.
but with the help of you i can find the similar kind of result.
i will look into this SimpleOcclusion Repo and update you the same.

Thank you so much for your reply, it's help me a lot.

**Comment by moheydy** [comment]
this vido use openCv not Arcore or Arfundation
