### ISSUE TITLE
Show a canvas prefab on tracked image using AR tracked Image.

### ISSUE THREAD

**Issue by liam1908** [Unity-Technologies/arfoundation-samples#799]
I want to show a canvas prefab on tracked image (QR code image). I am using AR tracked Image of AR foundation to get position of the QR code Image. I created canvas prefab with render mode is World Space and event camera is AR Camera. When I test my application with my phone, my canvas prefab doesn't show on QR code Image position and sometimes my canvas prefab moves when I move my camera (I want it to be fixed position of QR code). I think position (z) of QR code image is not a distance from my camera to QR code image but I don't know to get a right position in world space of QR code image to place my canvas prefab. I hope someone can help me. Thank you so much.
I have posted this problem on Unity Forum but I haven't gotten solution yet. I have attached my code with Unity Forum Post here:
https://forum.unity.com/threads/ar-foundation-show-a-canvas-prefab-on-tracked-image-ar-tracked-image.1095061/

**Comment by tdmowrer** [comment]
Our [image tracking samples](https://github.com/Unity-Technologies/arfoundation-samples#imagetracking) do something very similar with a world-space canvas. Have you looked at those?

**Comment by liam1908** [comment]
> Our [image tracking samples](https://github.com/Unity-Technologies/arfoundation-samples#imagetracking) do something very similar with a world-space canvas. Have you looked at those?

Thank you for your suggestion. I have looked at image tracking samples of AR foundation samples on Github. I want my app detect the position of QR code in world space and place a canvas prefab at that position. I try to get position of QR code by "trackedImage.position" and set my canvas prefab position that position but the canvas prefab doesn't have a fixed position sometimes it moves follow the camera. Have you ever met this issue? Thank you.

**Comment by liam1908** [comment]
@tdmowrer  This is demo of AR app I want to build. Canvas Prefab (Gauge) is always show on a fixed position. Can you suggest how to do that? Thank you.

https://user-images.githubusercontent.com/61672720/115527088-ed131680-a2ba-11eb-8825-b85651adfd6c.mp4

**Comment by tdmowrer** [comment]
If I understand correctly, you want to position the canvas at the tracked image, but rotate it so that it always faces the camera. In that case, [Quaternion.LookRotation](https://docs.unity3d.com/ScriptReference/Quaternion.LookRotation.html) might be useful.

**Comment by liam1908** [comment]
@tdmowrer thank you for your suggestion. I want to detect the position of the QRCode and place one Object on that position and that Object not moving when I move camera and QRCode disappears. For example the video below. When I detected QRCode I place a sphere on QRCode position and I quit the QRCode and moving the camera, the sphere are not in the position which I placed. Could you show me how to do that? Thank you very much.


https://user-images.githubusercontent.com/61672720/115804871-12646980-a40e-11eb-86ca-17b087acb437.mp4

**Comment by liam1908** [comment]
@tdmowrer I want to create an anchor point  in tracked image, is it possible to do that with AR foundation? If it is possible, could you show me how?

**Comment by tdmowrer** [comment]
It looks like the physical dimensions of the image are incorrectly specified.

If they are wrong, then the object is positioned such that it appears correct in screen space, but actually might be much further away. For example, imagine you told it to look for a billboard-sized QR code; it would assume the relatively small sized QR code that it sees must just be very far away and therefore positions the green sphere in the distance. That's what it appears is happening here. You need to make sure the physical dimensions you specify in the XRReferenceImageLibrary exactly match the size of the image in the real world.

**Comment by liam1908** [comment]
@tdmowrer I am very appreciated.
