### ISSUE TITLE
Combine ARFoundation with Vuforia

### ISSUE THREAD

**Issue by oliverellmers** [Unity-Technologies/arfoundation-samples#8]
Helloo,

I am trying to integrate Vuforia functionality into a project also containing the ARFoundation.

So far everything seems to be running fine in editor, and comiled fine, but I recieve a black screen.

My thoughts here are that both SDK's are trying to acces the camera at the same time - I could be completely wrong.

So I am wondering if there is a way to supply the ARFoundation the same camera feed that Vuforia is receiving?

Alternatively - is it possible to access ARKit 1.5/2 or ARCore 1.2 image tracking (and other functionality) via the ARFoundation?

Thankyou in advance!

Oliver

***EDIT***

Okay I eat my words,

It seems as though I can successfully get the vuforia SDK to start by attahcig the Vuforia scripts to the ARFoundation Camera.

The ARFoundation functionality all seems to work fine, but the issue now is that although Vuforia has initialized and the console says the sessions has started - no tracking is recognized.

So unless anybody has anything they might want to add to point me in the right direction with getting the tracking to work with vuforia correctly - then I would assume this is an issue to post to the Vuforia forums (god forbid...), and this can be closed?

If anybody is interested in havign a look at the poject I have up and running in case they might have some ideas you can find it here: https://github.com/oliverellmers/arfoundation-samples/tree/Testing

Cheers

**Comment by timm-unity** [comment]
There can only be one AR Session, so if you enable the `ARSession` in ARFoundation, then Vuforia won't have access to it (and vice versa). If you want to use Vuforia as a fallback on platforms that do not support ARCore/ARKit, you can make AR optional on those platforms, detect if it is supported, then use Vuforia if it isn't. See [these docs](https://docs.unity3d.com/Packages/com.unity.xr.arcore@1.0/manual/index.html#build-settings) to see how to do this on ARCore and the [Requires ARKit support](https://docs.unity3d.com/Manual/class-PlayerSettingsiOS.html) Player Setting on iOS.
