### ISSUE TITLE
LWRP branch: Screwy shadows on iOS

### ISSUE THREAD

**Issue by bitfabrikken** [Unity-Technologies/arfoundation-samples#80]
I can't get shadows working with the example project in the [LWRP branch](https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp_support), specifically the scene called SampleLWRPScene.unity

As soon as anything with shadows is in view, the camera background goes absolutely nuts.

I'm hoping someone might have had more luck than me, and if so, what you did to get shadows + camera background working.

Non-exhaustive list of things I've tried:
1. Adding/removing LightweightAdditionalCameraSettings to camera and enabling shadows. This does get disabled at runtime for some reason, but I've tried turning it on via code later. Works on Android.
2. Adding LWRP shaders manually to project settings > always included shaders
3. Materials with Enable GPU instancing on/off (materials are set to receive shadows + mesh renderers are set to cast shadows)
4. Almost all possible combinations of options within LightweightRP.asset 
5. Graphics Jobs on/off, Multithreaded rendering on/off, force Metal hard shadows on/off.
6. Various Xcode settings such as build target to 11 instead of 9, 
7. Tried all kinds of settings on scene's directional light. 
8. Light estimation on/off - light estimation works fine, but still no shadows.
9. Various versions of ARKit and ARFoundation

Looks like this, but the messed up artifacts in the background are moving around very fast.

![image](https://user-images.githubusercontent.com/2039652/50513821-6c510080-0a9a-11e9-98cf-d11117deed06.png)

**Comment by Raixur** [comment]
Same issue

**Comment by tdmowrer** [comment]
ARFoundation 3.0 provides much improved support for LWRP (now called Universal Render Pipeline). Instructions [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/manual/ar-camera-background-with-scriptable-render-pipeline.html).

I'll close this old issue for now, but please reopen it if it continues to be a problem in more recent releases.
