### ISSUE TITLE
How do I add multiplayer support?

### ISSUE THREAD

**Issue by orrburgel** [Unity-Technologies/arfoundation-samples#800]
How do I...
Which demo project will be the best for starting to use multiplayer features?

**Comment by tdmowrer** [comment]
AR Foundation in general doesn't do anything specific to "multiplayer" -- that can mean a lot of things. However, ARKit supports [collaborative sessions](https://github.com/Unity-Technologies/arfoundation-samples#arcollaborationdata) and ARCore lets you share anchors with Cloud Anchors available with their [extensions package](https://developers.google.com/ar/develop/unity-arf).
