### ISSUE TITLE
Git克隆完毕后，使用2020.1.6f1c1打开工程,就抱错

### ISSUE THREAD

**Issue by Timor666** [Unity-Technologies/arfoundation-samples#801]
打开工程后，就报错了。.
啥也没有操作。

![image](https://user-images.githubusercontent.com/35324214/115517376-a96bdd00-a2b9-11eb-97d1-96ed7b76dd4f.png)

**Comment by Timor666** [comment]
然后更新了所有ar的package   还是有两个报错,吐了。

![image](https://user-images.githubusercontent.com/35324214/115519578-e933c400-a2bb-11eb-9360-ba5e3a6024a4.png)

**Comment by Timor666** [comment]
使用Git恢复初始下载状态，然后使用2019.4.8f1打开 工程还是不行 服了。

![image](https://user-images.githubusercontent.com/35324214/115522902-1a61c380-a2bf-11eb-999e-623d84ef9451.png)

**Comment by tdmowrer** [comment]
Please update Unity to the latest 2019 or 2020 LTS (long-term support).

The reason this happens is a minor change to one of AR Foundation's dependencies, which makes it incompatible with versions prior to 2019.4.15f1 and all versions of 2020.1 (which is no longer supported now that 2020 LTS is available).

Additionally, 2.2.0-preview.3 should not be used (2.1 is the verified version for 2019.4).
