### ISSUE TITLE
[Bug] Occlussion Manager occludes every object. Occluding the AR Plane which renders shadows.

### ISSUE THREAD

**Issue by mbethke3dqr** [Unity-Technologies/arfoundation-samples#802]
**Unity bug report case number**
Case 1331289

**Describe the bug**
I need to draw shadows on a transparent AR Plane and also be able to occlude the object which projects shadows.

**To Reproduce**
1) Use this shader and apply it to the AR Plane for shadows in AR:
https://gist.github.com/DanMillerDev/96f9a157d56cd6c0480e0e1838d99df6

2) Add AR Occlusion Manager to the AR Camera. 
3) AR Occlusion Manager occludes the AR Plane and no shadows are rendered.

It is also reproduceable by: 
1) Use this shader and apply it to a plane which must be positioned underneath the AR Model. (It will act as a shadow plane without being the AR Plane). 
2) Same step from above.
3) Same error from above. (Even if the plane is way bigger than the object). 

**Expected behavior**
The object that is placed on the AR plane should render shadows on the plane and also be occluded.

**Actual behavior**
The AR Occlusion Manager occludes the AR Plane and do not let it cast its shadows.

**Smartphone (please complete the following information):**
 - Device: S9+
 - OS: Android 10.
 - Unity version: 2020.3.1f1
 - ARFoundation version 4+
 
 ***Whishes***
 Hopefully the AR Occlusion Manager could have an option to skip some objects of being Occluded by other objects. It should still render the shadows.

**Comment by KirillKuzyk** [comment]
https://forum.unity.com/threads/ar-occlusion-environment-arplane-flickering-how-to-fix-it.1006303/#post-6531179

**Comment by mbethke3dqr** [comment]
> 
> 
> https://forum.unity.com/threads/ar-occlusion-environment-arplane-flickering-how-to-fix-it.1006303/#post-6531179

I already tried changing the offset ! 
But the shader is only occluding itself and not the object.

**Comment by tdmowrer** [comment]
> But the shader is only occluding itself and not the object.

Can you elaborate on this? What does it mean for a shader to occlude itself?

**Comment by mbethke3dqr** [comment]
> 
> 
> > But the shader is only occluding itself and not the object.
> 
> Can you elaborate on this? What does it mean for a shader to occlude itself?

I replied to this while testing Occlusion shaders and see if I could create Occlusion instead of using the AR Occlusion Manager. It worked but the desired result is to have a shadow plane shader with the AR Occlusion Manager enabled.

If I apply the offset to the shadow plane and enable the AR OM, it produces the same bad results. No shadows.

**Comment by AytoMaximo** [comment]
I'm sorry, back to this old topic: I have the same issue. Any solution for this nowadays?
