### ISSUE TITLE
Meshing option greyed out on Android build[Bug]

### ISSUE THREAD

**Issue by peachpieproductions** [Unity-Technologies/arfoundation-samples#803]
When I build the project to android, the Meshing option is unavailable. (greyed out) 

I have found in the code where the button is greyed out and it looks like something to do with XR Mesh Subsystem 
![image (3)](https://user-images.githubusercontent.com/22354428/116555057-efccc780-a8c9-11eb-987e-df4bc950f17e.png)

Do you know if "XR Mesh Subsystem" is included in the package "XR Plugin Management"? I have that installed.

![image (4)](https://user-images.githubusercontent.com/22354428/116555199-1985ee80-a8ca-11eb-8a7c-256f54a3bc0b.png)

I am using a Google Pixel 2 XL, maybe this is only available on 2020+ devices? 

Any ideas?

Thanks
Ben

**Comment by todds-unity** [comment]
Android devices do not support meshing. The menu is greyed out to reflect the lack of functionality on that device.
