### ISSUE TITLE
Namespace errors in ARCoreSessionRecorder.cs

### ISSUE THREAD

**Issue by brollsroyce** [Unity-Technologies/arfoundation-samples#804]
![Errors](https://user-images.githubusercontent.com/50242741/116792751-f1adab00-aac2-11eb-9c88-b7a8dfe15687.PNG)

Any help with these errors?

**Comment by tdmowrer** [comment]
It looks like you may have copied some sample code from this repository that relies on a newer version of the packages than you have in your project. You can try updating your packages to match [this project's manifest](https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Packages/manifest.json#L8).

Note that this repository is a complete Unity project, and, in general, copying or cloning it into an existing project will probably not work as expected.
