### ISSUE TITLE
Object Tracking Not Functional

### ISSUE THREAD

**Issue by KCoulter14** [Unity-Technologies/arfoundation-samples#805]
Downloaded and built out the AR Foundation project for the latest GitHub Unity project 4.2.0. and I have had no luck with any of the Object Tracking registering/ working at all. I printed out and folded the Unity cube object and tried my own with the latest AR object scanning app and added that to the Reference Object and that does not work either.

I used this previously in other releases of AR Foundation without any issues. Has anyone had success with this? I saw that someone else had this issue in Issue #179 but it was closed with no resolution or solution mentioned.

In the attached image you can see that the app was built fine and working but no .arobject is syncing.

![IMG_6568](https://user-images.githubusercontent.com/39064021/116926146-4bbf8500-ac17-11eb-9e92-399fdf3fb83b.PNG)

Tried using:
AR Foundation 4.2.0
Unity 2021.1.5f1
Unity 2020.3.6f1
Xcode 12.5
iPhone 11 Pro iOS 14.4.2

**Comment by KCoulter14** [comment]
I needed to use AR Foundation 4.1.7 - for anyone else who might make this mistake...

**Comment by KirillKuzyk** [comment]
I can also confirm that the Object Tracking is not working in AR Foundation 4.2.0. The latest version that seems to work is indeed 4.1.7.

**Comment by tdmowrer** [comment]
This has been fixed in 4.2.0-pre.7.
