### ISSUE TITLE
Set image/object in detected vertical plane to face the camera, and be oriented straight

### ISSUE THREAD

**Issue by brollsroyce** [Unity-Technologies/arfoundation-samples#806]
When I tap to place objects on a wall, for example a painting on a wall, how do I set its orientation such that it seems like it is mounted on the wall? I tried this: 
 `if (_aRRaycastManager.Raycast(touchPos, hits, TrackableType.PlaneWithinPolygon))
        {
            Pose hitPose = hits[0].pose;

            if (spawnedObject == null)
            {
                
                spawnedObject = Instantiate(gameObjectToInstantiate, hitPose.position, hitPose.rotation);
                spawnedObject.transform.Rotate(-90, 0, 0, Space.Self);

            }
            else
            {
                spawnedObject.transform.position = hitPose.position;
            }`

The position of the spawned object is correct, it spawns on the detected plane. But I need to fix the rotation. Any ideas how to do that?

**Comment by tdmowrer** [comment]
You can set the spawnedObject's rotation to something like

```cs
Quaternion.LookRotation(Vector3.up, plane.normal);
```

If the trackable is a plane, then you can downcast the hit.trackable to an ARPlane in order to get its normal. See also https://docs.unity3d.com/ScriptReference/Quaternion.LookRotation.html

**Comment by brollsroyce** [comment]
Still doesn't work. I hope I've used the correct plane calling here though: 

` if (_aRRaycastManager.Raycast(touchPos, hits, TrackableType.PlaneWithinInfinity))
        {
            Pose hitPose = hits[0].pose;

            var plane = _arPlaneManager.GetPlane(hits[0].trackableId);
            
            if (spawnedObject == null)
            {
                spawnedObject = Instantiate(gameObjectToInstantiate, hitPose.position, Quaternion.LookRotation(Vector3.up, plane.normal));
                //spawnedObject = Instantiate(gameObjectToInstantiate, hitPose.position, hitPose.rotation);

            }
            else
            {
                spawnedObject.transform.position = hitPose.position;
            }
        }`

When I do the above, absolutely nothing happens when I tap the screen. The gameObjectToInstantiate only spawns upon tap if I set its rotation to hitpose.rotation as seen in the commented line below the LookRotation line.
