### ISSUE TITLE
[Bug] Image Tracking: Position slightly off

### ISSUE THREAD

**Issue by stetttho** [Unity-Technologies/arfoundation-samples#807]
**Unity bug report case number**
1333921

**Describe the bug**
The overlay image is slightly off to the bottom and to the right.

<img src="https://user-images.githubusercontent.com/32513612/117140063-3c724000-adad-11eb-9a45-01cdc0d0dd61.jpg" width="200">

**To Reproduce**
Can be reproduced with the sample project 'BasicImageTracking' .

**Expected behavior**
Overlay image should be placed exactly on the trigger image

**Actual behavior**
slightly offset to the right and bottom. As a temporary fix, I use this:

```
    // temporary fix for slightly off position
    position += overlayGameObject.transform.right * 0.00035f;
    position += overlayGameObject.transform.forward * 0.00035f;
```

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPad (not tested with Android)
 - OS: iOS 14.4.2
 - 2020.2.4 and 2020.3.4
 - ARFoundation version 4.0.12 and 4.1.7

**Comment by tdmowrer** [comment]
This doesn't look like a bug -- it looks like a very slight (0.35 mm) error in detection. That seems within expected tolerance to me. What use case do you have that requires accuracy higher than that?

**Comment by stetttho** [comment]
I think that might have something to do with the scaling of my prefabs, have not tested my temporary fix with the sample project. It is definatly more than 0.35mm, probably 2-3mm as far as I can tell. So it is noticable and parts of the trigger image can always be seen behind the overlay.

I also wouldn't call it a bug if it wouldn't always be the same offset. But as it is (tested not only with my 2 devices but also by other iOS users) I think it would be worth looking into it.
