### ISSUE TITLE
App Store rejects ALL apps using AR Foundation (Face Tracking included but not used)

### ISSUE THREAD

**Issue by bitfabrikken** [Unity-Technologies/arfoundation-samples#81]
Had an app rejected yesterday because it included some code for the TrueDepth API / Face Tracking.

If you're not using face tracking at all, but just the regular AR Kit features, it seems it's still included, and thus Apple will reject your app.

This means anyone anyone building and submitting non-facetracking apps with the current version of AR Foundation + AR Kit will have their app rejected.

The people working on the AR Kit plugin seems to have it sorted out, [see this thread on the unity forums](https://forum.unity.com/threads/submitting-arkit-apps-to-appstore-without-face-tracking.504572/page-2), but those fixes haven't made it to the AR Foundation package version yet.

Build info for the app I had rejected:
* macOS 10.14
* Xcode 10.1 (10B61)
* Unity 2018.3.0f2
* ARKit XR Plugin 1.0.0-preview.20
* ARCore 1.0.0-preview.24
* AR Foundation 1.0.0-preview.22. 

ARKitSettings asset:
* AR Kit Requirement: Optional
* AR Kit Face Tracking Enabled: False

**Comment by tdmowrer** [comment]
Thank you for reporting. A fix is in the works.

**Comment by bitfabrikken** [comment]
@tdmowrer it was just approved by app review. I think it might have been that facetracking was in my Assets/link.xml. Seems like removing it did the trick the second time around. No idea how it got there though as I've never messed with face tracking in this project.

**Comment by Leiong** [comment]
@tdmowrer Hi，my app was also rejected，is solve ？

**Comment by tdmowrer** [comment]
@Leiong Yes, an updated ARKit package was published today, 1.0.0-preview.23. That should fix the app validation issue.

**Comment by aviggiano** [comment]
Hello,
My app was also rejected due to it not including Face Tracking features. 
Is there a permanent fix for this?

**Comment by tdmowrer** [comment]
@aviggiano Yes, the fix is in 1.0.0-preview.23. You have to make sure you are not actually using face tracking features, and that you've unchecked the face tracking checkbox in the [ARKit Settings](https://docs.unity3d.com/Packages/com.unity.xr.arkit@1.0/manual/index.html#face-tracking).
