### ISSUE TITLE
ARHuman Body Manager Scale Issues

### ISSUE THREAD

**Issue by genereddick** [Unity-Technologies/arfoundation-samples#811]
It is not clear what "Pose 3D Scale Estimation" checkbox on the AR Human Body Manager is supposed to do. When unchecked the skeleton alignment and scale is pretty good (when mapping either a short or tall person). When checked the skeleton appears much larger than the person it is supposed to be tracking.

I see the same behavior as this person: https://forum.unity.com/threads/pose-3d-scale-toggle-in-ar-foundation-with-ar-kit-3.809163/

However, in both cases, checked and unchecked, and tracking two people with different heights, the estimatedHeightScaleFactor, and the scale values for each joint's localScale and anchorScale, are all Vector3(1.0f, 1.0f, 1.0f) in every case. 

Is this scale data stored somewhere else? Not getting passed back to the model? Is the alignment done by adjusting the skeleton position instead of scale?

**Comment by tdmowrer** [comment]
It maps to this flag in ARKit: https://developer.apple.com/documentation/arkit/arbodytrackingconfiguration/3255163-automaticskeletonscaleestimation?language=objc

**Comment by genereddick** [comment]
@tdmowrer I would assume, perhaps incorrectly, that when checked the humanBody.estimatedHeightScaleFactor would get whatever value was calculated? But for a 1.2 meter tall person and a 1.8 meter tall person the value is 1.0 as are every other joint scale value.

**Comment by genereddick** [comment]
OK, so it seems enabling it doesn't automatically populate the field, you have to actual tell the ARHumanBodyManager to request the data:

humanBodyManager.pose3DScaleEstimationRequested = true;

With that I'm getting scale data back.
