### ISSUE TITLE
Adding Images: Mutable Runtime Reference Image Library Persistant?

### ISSUE THREAD

**Issue by wileyknight** [Unity-Technologies/arfoundation-samples#812]
I want to know if adding an image to the MutableRuntimeReferenceImageLibrary will store that image data with persistence?

I need to be able to call a www get to read json with the image data. Compare that data to the existing Library and add new or updated images during runtime. I don't want to have to update the XR library every time the application is run I need the data to persist. If the images are not persistent how would one go about adding the images as resources to be persistent?

Thank you.

**Comment by tdmowrer** [comment]
You cannot save a reference image library that you've generated at runtime, but recreating one from source images is parallelized and usually takes < 2 frames per image.

> I don't want to have to update the XR library every time the application is run I need the data to persist.

I agree this is a bit cumbersome, but is this causing any other problem?

**Comment by wileyknight** [comment]
Yes, this is a problem. I don't want to have to republish the app and up my version every time I add new images to my library. I am creating new images and adding them constantly in preparation for an event. I will have hundreds of images to add over a year before the event. Ideally I want to have the app look for new images on my website, add them, update the database and continue. That's potentially a lot of load time every time someone opens the app or the opposite of a lot of work adding every new image manually and uploading, approving and releasing a new version.

This is also a yearly event and the app will be updated every year for the new designs to work with the new years AR designs.

I need a better solution.

**Comment by tdmowrer** [comment]
If you are pulling image information from a json file, you don't need to republish your app. You can reconstruct the image library at startup from JPEGs or PNGs. That isn't great for hundreds of images, but it also doesn't mean you have to republish your app.

Also, most image tracking solutions don't support "hundreds of images" so I don't think it is feasible to have that many in the first place.

**Comment by wileyknight** [comment]
Documentation for ARCore says image databases support up to 1000 images. I suppose I'll be testing those limitations.

"Each Augmented Image database can store information up to 1,000 reference images."
https://developers.google.com/ar/develop/unity-arf/augmented-images

I don't remember reading anything on ARKit.

Do you know if it's possible to import an already created XRReferenceImageLibrary as an asset? I might be able to save that to the device and read in from the site, compare sizes and update as needed.

**Comment by wileyknight** [comment]
I found this bit of documentation

"...you can include an XRReferenceImageLibrary in an asset bundle and use it in an app that was not built with that reference image library present."
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/tracked-image-manager.html

Now I just have to figure out how to do that.

Thanks for the feedback. It's been helpful to get me to this point.

**Comment by tdmowrer** [comment]
Asset bundle support is a recent addition; see, in particular, this utility class: https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.2/api/UnityEditor.XR.ARSubsystems.ARBuildProcessor.html

**Comment by subramanian42** [comment]
@wileyknight how did you get around this issue, I am trying to implement the same thing and I am facing the same issue.
