### ISSUE TITLE
Human Body Tracking

### ISSUE THREAD

**Issue by PROCW** [Unity-Technologies/arfoundation-samples#813]
Hi.
I think, they used ARFoundation for Human Body Tracking in this sample, and support iOS.
But I wanna Android project of Human Body Tracking, isn't possible?
Can you tell me why this is not possible on Android?
Thanks.

**Comment by tdmowrer** [comment]
AR Foundation uses [ARCore](https://developers.google.com/ar) on Android. ARCore does not support body tracking.

**Comment by PROCW** [comment]
thanks, but why can't support body tracking in android device?
Can you tell me reason?

**Comment by tdmowrer** [comment]
Because body tracking is a feature implemented by Apple for ARKit. On Android, it would need to be implemented by Google. You might try requesting this feature from Google here: https://github.com/google-ar/arcore-android-sdk

**Comment by PROCW** [comment]
Thanks.

**Comment by ROBYER1** [comment]
Requested this here because I didn't see anyone else do it, feel free to help chase Google ARCore team on this https://github.com/google-ar/arcore-android-sdk/issues
