### ISSUE TITLE
How to clip vertical plane when it's detected?

### ISSUE THREAD

**Issue by peterchen2001** [Unity-Technologies/arfoundation-samples#816]
Hello everyone, the Plane tracking feature is very nice in ARFoundation. My question is that any way to get the bouding box coordinates once a vertical plane is found? if it's possible, what's next what i want is to clip the bouding box(such as a real existing wall) and then i can see the virtual model(such as a monster) that locates on the other side of the wall. Any clues to make these? Any code sample or code snippet? Thanks in advance.

**Comment by tdmowrer** [comment]
An ARPlane has a [size](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARPlane.html#UnityEngine_XR_ARFoundation_ARPlane_size) property which can be used to generate a bounding box. The (x, y) dimensions of `size` refers to the local X and Z directions of the plane.

**Comment by peterchen2001** [comment]
Thanks very much, I will have a try.
