### ISSUE TITLE
Where is the Cloud Anchor sample here? Is it not supported by ARFoundation?

### ISSUE THREAD

**Issue by iAmJuan550** [Unity-Technologies/arfoundation-samples#817]
Does your library not support cloud anchors? It is an essential feature from Google ARCore that is missing here.

**Comment by KirillKuzyk** [comment]
The ARCore Cloud Anchors feature is developed and maintained by Google and comes as an extension to AR Foundation:
https://github.com/google-ar/arcore-unity-extensions
