### ISSUE TITLE
How to hide or replace the real hand with virtual hand gesture?

### ISSUE THREAD

**Issue by peterchen2001** [Unity-Technologies/arfoundation-samples#818]
Hi expert,
Using ARFoundation, i find that the real hand always locates behind the virtual monster, even though the monster is far away. Is it possible to make my real hand sit in front of the monster? Any clues to make this?

Or is it possible to hide or replace the real hand with virtual hand gesture?

**Comment by tdmowrer** [comment]
Some iOS devices can identify the part(s) of the camera image that contains a human and provides textures to perform occlusion. In AR Foundation, this is exposed via the AROcclusionManager:

![Screen Shot 2021-05-26 at 10 38 01 AM](https://user-images.githubusercontent.com/4934281/119706201-8085bd00-be0e-11eb-8f0d-57c736dc7495.png)
