### ISSUE TITLE
face detection and tracking not working on (Android) xiaomi poco f1

### ISSUE THREAD

**Issue by miscrealitystudios** [Unity-Technologies/arfoundation-samples#82]
hello sir i am testing ar foundations's sample project on my android phone and it seems that some of features like face tracking and face blend shapes are not working. Can you please fix the issue

**Comment by tdmowrer** [comment]
ARFoundation exposes the functionality of ARCore (on Android) and ARKit (on iOS). ARCore does not currently support face tracking, so it is unavailable in ARFoundation on Android. If and when ARCore does support face tracking, we will add support for it in ARFoundation.

**Comment by miscrealitystudios** [comment]
ok so can you suggest any face tracking sdk for now

**Comment by tdmowrer** [comment]
Some people have had success with OpenCV. You can feed it the image you get from the [Camera Image API](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/manual/cpu-camera-image.html).

**Comment by ra94** [comment]
Hi dear.
i opened this project with unity 2019.1.0f1 and build for android then open in android 5 but everything is black why? 
Help me please

**Comment by tdmowrer** [comment]
@ra94 Face tracking in ARFoundation is not yet supported on Android. Additionally, ARCore requires a minimum API level of 24, which means Android 7.0. ARCore will not work on Android 5.

**Comment by timneill40** [comment]
Hi,

This may seem like a repeat question but.....

Looking for Face Tracking on Unity AR Foundation building to Android (Honor 8X Api 25). 

Able to do it fine with Augmented Faces (ARCore).

AR Foundation seems not to be rendering face mesh as directed per Unity [manual](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/manual/face-tracking.html).

I am missing something obvious?

Any advice or help will be greatly appreciated,

tim

**Comment by tdmowrer** [comment]
ARFoundation does not yet support ARCore 1.7 (which is when face detection was added). Support is coming soon.

**Comment by timneill40** [comment]
Thank you

**Comment by SameelNawaz** [comment]
AR Foundation Face Mesh sample for Android renders the material over eyes and mouth, any ways to fix that ?
![Screenshot_20190611-223311](https://user-images.githubusercontent.com/26695360/59293914-aead7900-8c99-11e9-8f34-5e44a4575fc2.png)

**Comment by tdmowrer** [comment]
> AR Foundation Face Mesh sample for Android renders the material over eyes and mouth, any ways to fix that ?
> ![Screenshot_20190611-223311](https://user-images.githubusercontent.com/26695360/59293914-aead7900-8c99-11e9-8f34-5e44a4575fc2.png)

Not that I'm aware of. This is the mesh ARCore give us.

In the [AugmentedFaces sample in Google's ARCore SDK for Unity](https://github.com/google-ar/arcore-unity-sdk/tree/master/Assets/GoogleARCore/Examples/AugmentedFaces/Scenes), they use the mesh mostly for occlusion, so it's not as noticeable in that example. The ARFoundation sample is just showing you the raw mesh produced by their face detection API.

**Comment by Cross22** [comment]
Create a texture with alpha channel to exclude the eyes.

**Comment by andrewio** [comment]
> Create a texture with alpha channel to exclude the eyes.

Mesh is generated by script "AR Face Mesh Visualizer" & there is single material with single texture for whole face.  Do you have an example?

**Comment by SameelNawaz** [comment]
Any news on this one ? Do we have a working fix ?

**Comment by SameelNawaz** [comment]
@Cross22 ,  would you like to explain your suggestions please ?

**Comment by miscrealitystudios** [comment]
yes it's working fine now

**Comment by SameelNawaz** [comment]
@miscrealitystudios ,  I meant the issue where ArCore mesh renders above Eyes and mouth.

**Comment by miscrealitystudios** [comment]
yes the arcore doesn't support eye tracking in pocof1 device

**Comment by 21-Kameswaran-N** [comment]
> hello sir i am testing ar foundations's sample project on my android phone and it seems that some of features like face tracking and face blend shapes are not working. Can you please fix the issue

In ARCamera Game Object you can find ARCameraManager. in that chage the facing direction to user. only front cam support arcore face tracking

**Comment by tdmowrer** [comment]
Also note that blend shapes are an ARKit-only feature (you need to downcast the [face subsystem](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.XRFaceSubsystem.html) to the [ARKit specific one](https://docs.unity3d.com/Packages/com.unity.xr.arkit-face-tracking@4.1/api/UnityEngine.XR.ARKit.ARKitFaceSubsystem.html) in order to access them), so they are not supported on Android.

**Comment by 21-Kameswaran-N** [comment]
Thank you for your support. Just few hours before I used arcore unity
samples from GitHub. It's solved my problem.

Thanks for your support keep rocking🎸🎶🎶
