### ISSUE TITLE
Is there a way to get camera image in GPU

### ISSUE THREAD

**Issue by orangeagain** [Unity-Technologies/arfoundation-samples#820]
I want to use camera image as rendertexture in compute shader
how to get camera image in GPU? to instead of getcpuimage()
----edit----
ARKit seem to use Ycbcr format,How to visit Ycbcr in computeshader?

**Comment by tdmowrer** [comment]
Please see https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/index.html#scene-setup. Look for the section titled "Copying the Camera Texture to a Render Texture when accessing the camera image on the GPU".
