### ISSUE TITLE
Is "exposureOffset" avaible on iOS?

### ISSUE THREAD

**Issue by orangeagain** [Unity-Technologies/arfoundation-samples#821]
ARCameraFrameEventArgs.exposureOffset always return 0.
Is iOS support this propertie? or my use it incorrect?

**Comment by tdmowrer** [comment]
It is supported on iOS but requires iOS 13+. What device and iOS version are you testing on?

**Comment by orangeagain** [comment]
> It is supported on iOS but requires iOS 13+. What device and iOS version are you testing on?

iPad Pro 2020.
"exposureOffset" seem to rely on "lightEstimate",
Is this attribute for 3D model, not for camera?

**Comment by tdmowrer** [comment]
It maps to this value on ARKit: https://developer.apple.com/documentation/arkit/arcamera/3194569-exposureoffset?language=objc

> If your app displays an AR experience using a custom Metal renderer, use this value to light your scene during its post-processed lighting stage.
> 
> Lighting a scene using exposureOffset is normally more performant than scaling each light source in your scene based on the value of the frame's lightEstimate.

As far as I know, it doesn't depend on light estimation being enabled. If you think it isn't working as you expect, could you please log a bug (https://unity3d.com/unity/qa/bug-reporting) with a project that reproduces the issue?
