### ISSUE TITLE
How to place 3D object/prefab at position in real space and it can be covered by real object

### ISSUE THREAD

**Issue by liam1908** [Unity-Technologies/arfoundation-samples#822]
I am using raycast with feature points to detect where touch points and put the prefab at that point (video is attached). The position of prefab is right and everything is ok. However, when I put my hand in front of the camera, my hand supposed to cover the prefab but the prefab is always in front of my hand (video attached). I have try with simple 3D object like Cube and it happens again. I am newbie in Unity and AR foundation. I hope someone can help me. Thank you.
(This app runs on Android).

https://user-images.githubusercontent.com/61672720/120571523-839f2f80-c444-11eb-852c-055e7b51558e.mp4

**Comment by tdmowrer** [comment]
The [AROcclusionManager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html) can do this where supported (support may depend on device/hardware/OS version). Some of our samples do this (SimpleAR uses an occlusion manager).

In a Development Player, there will be debug output (on Android, you can see this using `adb logcat` from the command line) that tells you which features were requested and satisfied, which may also help track down issues.

**Comment by liam1908** [comment]
> The [AROcclusionManager](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html) can do this where supported (support may depend on device/hardware/OS version). Some of our samples do this (SimpleAR uses an occlusion manager).
> 
> In a Development Player, there will be debug output (on Android, you can see this using `adb logcat` from the command line) that tells you which features were requested and satisfied, which may also help track down issues.

Thank you very much. It's very helpful information for me to complete my project.
