### ISSUE TITLE
ARMap

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#823]
1,arkit and arcore boths of them  support ARMap?
2,how to use ARMap？Could you Give me a  tutorial？

**Comment by tdmowrer** [comment]
> 1,arkit and arcore boths of them support ARMap?

[ARWorldMaps](https://developer.apple.com/documentation/arkit/arworldmap) are specific to ARKit. ARCore supports [cloud anchors](https://developers.google.com/ar/develop/unity-arf/cloud-anchors/overview) which are different but can be used to solve a similar class of problems.

> 2,how to use ARMap？Could you Give me a tutorial？

There is a sample in this repo: https://github.com/Unity-Technologies/arfoundation-samples#arworldmap
