### ISSUE TITLE
AR Session Origin and AR Input Manager

### ISSUE THREAD

**Issue by AdrianGodlewski** [Unity-Technologies/arfoundation-samples#824]
Hello,
I'm struggling to understand **ARInputManager** compared to **ARSessionOrigin** object. 
Let me quote documentation about **ARInputManager**:  

> Add one of these to any GameObject in your scene if you want device pose information to be available.

Isn't **ARSessionOrigin** responsible for tracking device pose and instantiating tracked objects underneath and relative to it?
If I'm correct **ARSession** is responsible for managing scene lifecycle and **ARSessionOrigin** creates something like coordinate system with camera attached to it. 
So why do we need **ARInputManager** if **ARSessionOrigin** kinda does its job?

**Comment by tdmowrer** [comment]
The ARSessionOrigin is not responsible for the device pose, no. The ARInputManager makes the pose available (it essentially "turns on" the feature). The [ARPoseDriver](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARPoseDriver.html?q=ARPoseDriver) then consumes the pose information and applies it to its GameObject, for example, the camera.

**Comment by AdrianGodlewski** [comment]
> It is important to keep the Camera and detected features in the same space relative to each other (otherwise, detected features like planes won't appear in the correct place relative to the Camera). We call the space relative to the AR device's starting position "session space" or "device space". For example, when the AR session begins, the device may report its position as (0, 0, 0). Detected features, such as planes, will be reported relative to this starting position. The purpose of the ARSessionOrigin is to convert the session space to Unity world space.

If ARSessionOrigin is essentialy converting session space to Unity world space, then it is somehow a center point in the coordinate system. If AR Foundation uses depth sensing, then isn't the center point (ARSessionOrigin) enough to track device pose relative to other objects?

By tracking device pose you mean gathering data from accelerometer and gyroscope and feeding that in app? I though that AR Foundation uses depth sensing.

**Comment by tdmowrer** [comment]
While devices that have a depth sensor (e.g., LiDAR or time-of-flight infrared sensor) generally provide better quality pose tracking, "depth sensing" as a feature has nothing to do with pose tracking. How a pose is generated is an implementation detail specific to each AR API (e.g., ARCore or ARKit).

The input manager makes the device's raw pose information _available_ to anyone who wants it. The ARPoseDriver reads that pose and applies it to its GameObject, which is typically another GameObject under the session origin. The ARSessionOrigin is just a node in the scene graph which provides a transform from session space to Unity world space.
