### ISSUE TITLE
Trying to add Markerless Image Tracking to AR-Foundation using Custom Plugin for HoloLens

### ISSUE THREAD

**Issue by ArtemiusT** [Unity-Technologies/arfoundation-samples#825]
Hi, I am trying to create a custom Image Tracking Subsystem for AR Foundation, to use together with the available features on HoloLens and other devices that dont support Image Tracking. In version 2 of AR Foundation i could create a Custom Loader for managing the extension and on the Hololens the WindowsMR loader would Initialize, my custom loader would load the settings and my submodule would be registered.

After updating to version 4 each loader is responsible for loading the submodules and only one of the loaders is getting initialized. This is not a problem in the editor since only the custom loader is active. but in the build on the Hololens i still get the warning that no Subsystem is available for the session, input and meshing subsystems, which should be loaded by the windowsMR loader. This causes the Application to display nothing, but still excecute my custom Image Tracking correctly.
I assume that this is due to using 2 loaders at the same time and the custom loader being initialized first.

My question is: How can I use 2 different loaders at the same time to initialise subsystems that combine the functionality of both loaders. Or what is the best way to extend the already available plugins using the subsystem I created.

**Comment by tdmowrer** [comment]
AR Foundation 4 relies on the current active loader from XR Management (previously, it used whatever it could find). You can write a custom loader to initialize the subsystems that you want. See https://docs.unity3d.com/Packages/com.unity.xr.management@4.0/manual/Provider.html for details.

**Comment by ArtemiusT** [comment]
Does that mean, that if I want to use my submodule with WindowsMR and for example Leap Motion, i need to create a loader that combines the WindowsMR loader functionality and my custom submodule **and** a loader that does the same with LeapMotion?

**Comment by tdmowrer** [comment]
Yes, that is correct.

**Comment by ArtemiusT** [comment]
Well, I guess I'll just do that.
Thanks for the help.
