### ISSUE TITLE
Destroy region prefab if not face detected in scene

### ISSUE THREAD

**Issue by moncio** [Unity-Technologies/arfoundation-samples#828]
Hi to everyone. I'm quite beginner using ArFoundation and ArCore. Right now I'm running the sample scene _**ARCoreFaceRegions.unity**_ from branch 2.1 using **_Unity 2019.4.27f1_**. Openning the scene, I observe when there is no face detected, the attached prefab with the trackable face persists in the scene and I dont find the way to remove or hide or destroy this prefab when that happens. How can I do that?

Thanks in advance

**Comment by tdmowrer** [comment]
You can subscribe to the ARFaceManager's facesChanged event. When a face is not in the frame, it will either be in the list of removed faces, or its tracking state will change. See https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/face-manager.html
