### ISSUE TITLE
[Question] What's currently supported?

### ISSUE THREAD

**Issue by Alexees** [Unity-Technologies/arfoundation-samples#83]
I started evaluating AR Foundation, running it on an Android phone first and on Microsofts Hololens second. Not surprisingly, the Hololens did not render surfaces or allowed for tab input placing the red cube from the SimpleAR scene as possible on the Phone.
I then tried to find what exactly IS supported by the kit (I guess ARKit, ARCore, that's it).

So my question is, is there a list of SDKs / Devices, showing what's possible and if the samples SHOULD be working on the Hololens?

Thanks

**Comment by tdmowrer** [comment]
Currently, only ARCore and ARKit are supported. However, it allows for additional "backends", such as Hololens, to be supported in the future. This [blog post](https://blogs.unity3d.com/2018/12/18/unitys-handheld-ar-ecosystem-ar-foundation-arcore-and-arkit/) explains in more detail what features are currently supported.

**Comment by farzad-salimijazi** [comment]
Hi Tim,
I am using 2018.3 and when I add this I get so many errors like this.

Assets/arfoundation-samples-master/Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs(4,22): error CS0234: The type or namespace name `ARFoundation' does not exist in the namespace `UnityEngine.XR'. Are you missing an assembly reference?

The only thing in XR is XR.WSA and nothing else ... :(

I tried the package manager and there are no plugins to install including ARkit XR plugin and ARCore XR plugin like 2018.1 .

Any idea how can I get ARFoundation namespace ?

**Comment by farzad-salimijazi** [comment]
Hi Tim,

I am so sorry, I am still learning in this space, I figure it out, when I open the project as a new project unity install all packages but I wanna add this to my existing project and It does not add required packages there :(
How can I add or use one of them in existing project ?

Thanks
Farzad

**Comment by tdmowrer** [comment]
In the Package Manager (Windows > Package Manager), make sure you have enabled "Show preview packages" from the Advanced menu:
![2019-01-06 14_04_30-](https://user-images.githubusercontent.com/4934281/50742145-21329e00-11bc-11e9-89d5-123a0fe46b40.png)

Then you can find and add ARCore, ARKit, and ARFoundation to your project.

**Comment by farzad-salimijazi** [comment]
Tom, You are awesome , I had no idea I should enable that and Nothing about it anywhere to tell me that. I spend so much time on this.
Thank you so much!
