### ISSUE TITLE
[Bug] Your persistent cloud anchor app does not work with keyless option

### ISSUE THREAD

**Issue by iAmJuan550** [Unity-Technologies/arfoundation-samples#833]
**Unity bug report case number**
1343616_p5mcbai2q5itrmio

**Describe the bug**
"Error Not Authorized" when hosting anchors using the persistent cloud anchors app

**To Reproduce**
Run the persistent cloud anchor app with the keyless option

**Expected behavior**
I should be able to host and resolve anchors

**Actual behavior**
I am unable to host anchors

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android version 10 with OxygenOS version 10.3.11
 - Unity version: 2020.3.11f1
 - ARFoundation version: 4.1.5

**Comment by tdmowrer** [comment]
Cloud anchor support is provided by a Google extension package. You might try creating an issue here instead: https://github.com/google-ar/arcore-unity-sdk
