### ISSUE TITLE
systemStateChanged callback in Unity 2021.1 with ARFoundation 4.1.7 and  XR Plugin Management 4.0.3

### ISSUE THREAD

**Issue by Maapel** [Unity-Technologies/arfoundation-samples#834]
How can i implement systemStateChanged for AR subSystemManager in  ARFoundation scripting. Thank You for the Help

**Comment by tdmowrer** [comment]
I'm not sure what you are asking. Are you looking for the [ARSession.stateChanged](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARSession.html#UnityEngine_XR_ARFoundation_ARSession_stateChanged) event?

**Comment by Maapel** [comment]
Thank you so much for helping. It worked . If anyone wants how to do it here is an example this worked.
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.ARFoundation;

public class ARInteraction : MonoBehaviour
{
   
    void onChange(ARSessionStateChangedEventArgs eventArgs)
    {
        //Debug.Log(eventArgs.state);
        
}
    // Start is called before the first frame update
    void Start()
    {
    ARSession.stateChanged+= onChange;

    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
`
