### ISSUE TITLE
ARFoundation camere freeze after ad (AdMob)

### ISSUE THREAD

**Issue by Archi97** [Unity-Technologies/arfoundation-samples#836]
Hello. I have an application where users can add more than one AR model on the ground.
App work flow is this :
1. Open Models List
2. Select one
3. Place on the ground
4.Press "ADD/PLUS" button
5. Select another model
6. Place on the ground next to the previous model.

Some of the models are unlockable with ads. So when selecting a model with an ad (on step 5), after watching the ad Step 6 starts, but the AR Camera is freeze. I can still interact with the model but the camera background (my real space) is freeze.

What can be the problem?
This problem happens only on IOS. Android works fine.
Thanks.

**Comment by tdmowrer** [comment]
The repro steps you provided sound like they are specific to your application. If you believe there is a bug in AR Foundation, please log a bug (https://unity3d.com/unity/qa/bug-reporting) and provide a project that reproduces the issue. Post the case ID here when you do.

**Comment by Archi97** [comment]
> roduces th

yeah. it was.  strange.  i just reinstalled plugins, and now it works.  )
