### ISSUE TITLE
[Bug] Black Screen on Samsung Galaxy S8 (SM-G950F)

### ISSUE THREAD

**Issue by Deeeeeeeeeevon** [Unity-Technologies/arfoundation-samples#839]
**Describe the bug**
When opening any other of the ar scenes, instead of showing the camera, a black screen is displayed. However, the camera is displayed on a another device i.e. Nokia 8

**To Reproduce**
1. Open 'AR Foundation Samples'
2. Click on 'Simple AR' (or any other menu item)
3. Black screen will be displayed

**Expected behavior**
Camera is meant to be displayed

**Actual behavior**
Black screen is displayed

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8 (SM-G950F)
 - OS: Android 9
 - Unity version: 2021.1.12f1
 - ARFoundation version: 4.2.0-pre.9

**Comment by tdmowrer** [comment]
Please submit a bug (https://unity3d.com/unity/qa/bug-reporting) and post the case ID here.
