### ISSUE TITLE
[Bug][AR Foundation 4.1.7][Unity 2020.3.12f1] Black screen on iOS but works fine on Android

### ISSUE THREAD

**Issue by dzak83** [Unity-Technologies/arfoundation-samples#841]
**Unity bug report case number**
(Case 1345857) Black screen from AR Foundation ARKit when targetTexture is used

**Describe the bug**
We hit that regression after updating Unity from 2018 to 2019 and with AR Foundation version update. It seems like AR Camera is broken when Camera.targetTexture is set to RenderTexture. Calling this breaks video and RenderTexture will not receive video.

The same code worked fine on previous versions AND works fine on Android.

**To Reproduce**
(In the Unity bug attachment there is a sample project with everything but here are steps too)
1. Setup: AR Foundation 4.1.7, Unity 2020.3.12f1
2. New 3D project. Install AR Foundation with ARKit and ARCore. Mark check boxes in the XR settings. Set scripting define: UNITY_XR_ARKIT_LOADER_ENABLED.
3. Add AR Sessions and AR Session Origin to the project
4. Add script that will override targetTexture
5. Add render texture and material to the project

![image](https://user-images.githubusercontent.com/27939815/123473621-a937d880-d5ad-11eb-9c31-d21953f3d569.png)

![image](https://user-images.githubusercontent.com/27939815/123472584-31b57980-d5ac-11eb-8cb1-b5e1b142e727.png)

![image](https://user-images.githubusercontent.com/27939815/123472617-409c2c00-d5ac-11eb-8329-e445582c76d8.png)

From Awake, call logic that will set targetTexture. For debug, I am then displaying it in the OnGUI:
![image](https://user-images.githubusercontent.com/27939815/123472802-7ccf8c80-d5ac-11eb-9bd4-43845c5d1ae7.png)

**Expected behavior**
AR Camera video should be saved into RenderTexture. OnGUI should show RenderTexture video. This works on Android and previous version of AR Foundation.

**Actual behavior**
The moment we set Camera.targetTexture, video is broken on iOS. OnGUI is rendering black screen.

** Workaround**
There is a way to fix if we use coroutine and wait few seconds before we set Camera.targetTexture = RenderTexture;. It would mean AR Camera is doing something with targetTexture or assigning it from Awake to camera is breaking AR Camera state.

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: 14.6 but repros on others
 - Unity version: 2020.3.12f1
 - ARFoundation version: 4.1.7

**Comment by stevenbajer** [comment]
I have the same problem in AR Foundation 4.17 version. According to the offical arfound samples, there is AR Subsystems packages in current project. But now I can not find AR Subsystems package in Unity Registery.

**Comment by ankur-unity** [comment]
> I have the same problem in AR Foundation 4.17 version. According to the offical arfound samples, there is AR Subsystems packages in current project. But now I can not find AR Subsystems package in Unity Registery.

@stevenbajer - Please file a bug via [https://unity3d.com/unity/qa/bug-reporting](https://unity3d.com/unity/qa/bug-reporting)

You can also follow the progress on the bug filed by @dzak83 on our [issue tracker](https://issuetracker.unity3d.com/issues/ios-arkit-ar-camera-does-not-update-the-target-texture-when-the-it-is-set-immediately-after-loading-the-scene).
