### ISSUE TITLE
Turn off camera stream / Set face mesh position

### ISSUE THREAD

**Issue by gilsunshine** [Unity-Technologies/arfoundation-samples#844]
In the ARKiteFaceBlendShapes example, would there be a way to turn off the camera stream or at least hide it without also hiding the face mesh? Also, would there be a way to fix the position of the mesh prefab on the screen even when the position of a tracked face moves around?

Thanks

**Comment by todds-unity** [comment]
You should be able to disable the ARCameraBackground to disable camera background rendering.

The game object for the face mesh has a transform that is updated by AR Foundation, but you should be able to subsequently changed the position of the game object to your fixed location.
