### ISSUE TITLE
[Question] AddBeforeBackgroundRenderHandler With Custom Renderer

### ISSUE THREAD

**Issue by GiantSox** [Unity-Technologies/arfoundation-samples#846]
Hi!

I'm using a custom rendering script in my app instead of ARCameraBackground, and have been a slightly confused by how `AddBeforeBackgroundRenderHandler` is supposed to be used/implemented. 

- If I understand correctly, the subsystem's `OnBeforeBackgroundRender` function is supposed to be called before any rendering that uses the camera texture is performed?

- If I am not rendering using a CommandBuffer, I should be able to just call `GL.IssuePluginEvent(s_BeforeBackgroundRenderHandlerFuncPtr, 0);` before `Graphics.Blit`ing with the texture, right? (I copied the code for the function pointer acquisition stuff into its own class)

 - I am blitting the AR Foundation camera texture to a temporary RenderTexture each frame, and using that texture later (potentially multiple frames later), so I should call the handler before rendering to the temporary texture, not before the temporary texture is rendered to the screen, right?

Thanks!

**Comment by DavidMohrhardt** [comment]
If you are attempting to write similar functionality to `ARCameraBackground.cs` then the goal of `AddBeforeBackgroundRenderHandler` is to simply add an additional `IssuePluginEvent` to the command buffer we bulid to draw the camera background to the screen.  This is really only utilized on `ARCore` as there is some native work that needs to be done to appropriately prepare for rendering the background.  So looking at the command buffer we build we do the following:

1. IssuePluginEvent
2. Set the invert culling state
3. Clear the render target
4. Blit the Camera background texture to the Unity camera target (IE the back buffer) using the attached material

As long as your GL commands follow something similar then you shouldn't need to use a `CommandBuffer`.  However it should be noted that the command buffer is executed at very specific times in the given frame.  You can see this in the `s_DefaultCameraEvents` array in `ARCameraBackground.cs` where we actually try and execute our command buffer.

About the `OnBeforeBackgroundRender` callback function.  It's a PInvoke function that gets filled out by the native platform provider (IE `ARCore`, `ARKit`, etc...).  Not all platforms actually supply this callback and thus it's not always necessary.  You can get the expected functionality by querying the relevant function from the camera subsystem.

```csharp
// Must be a PInvoke callback as the plugin event will be called from native code
[MonoPInvokeCallback(typeof(Action<int>))] 
static void BeforeBackgroundRenderHandler(int eventId)
{
    if (s_CameraSubsystem != null)
    {
           // The camera subsystem has a handle to the appropriate provider before camera background render
            s_CameraSubsystem.OnBeforeBackgroundRender(eventId);
    }
}
```

**Comment by DavidMohrhardt** [comment]
As for the Temporary render texture.  If you are using the actual `RenderTexture.GetTemporary()` method then it's important to note that the render texture might actually be "destroyed"/reclaimed by unity a few frames later.  See the documentation here:

https://docs.unity3d.com/ScriptReference/RenderTexture.GetTemporary.html

Otherwise you would want to follow a similar pattern to what ARCameraBackground is doing except instead of blitting to the camera you'd simply blit to your cached RenderTexture.

**Comment by DavidMohrhardt** [comment]
Feel free to reopen if you have additional questions.

**Comment by GiantSox** [comment]
Late reply, but just wanted to say thanks! I seem to have things working nicely.

Yeah, I ended up implementing my own simple "RenderTexturePool" class to work around the caveat with `RenderTexture.GetTemporary()`.
