### ISSUE TITLE
Enable Vertex colors and get simple "texturing" for mesh

### ISSUE THREAD

**Issue by dzak83** [Unity-Technologies/arfoundation-samples#848]
I am looking for a simple way to get a mesh of the environment with some texturing on iOS LIDAR. I know I can't get real texturing so I was wondering if I can read the colors from video frames and just set them for the mesh vertex colors. Is there any sample or some kind of similar code anyone can share with me?

On the AR mesh manager there is an option to enable "colors". Is it available on iOS and how can I use it?

**Comment by todds-unity** [comment]
iOS/ARKit does not support vertex colors on meshes.
