### ISSUE TITLE
A better way to occlusion GameObject

### ISSUE THREAD

**Issue by orangeagain** [Unity-Technologies/arfoundation-samples#851]
**Is your feature request related to a problem? Please describe.**
Use Mesh self occlusion to instead ARKit depth images implementation.

**Describe the solution you'd like**
just use scene meshs render like a normal game!
If device support ARMeshingManager, let game engine to render it.
this method without any performance cost compared with ARKit depth images.

The only drawback is that require you device support ARMeshingManager,and can not occlusion human.

**Comment by todds-unity** [comment]
We have a AR Foundation sample that demonstrates how this works.
https://github.com/Unity-Technologies/arfoundation-samples#occlusionmeshes
