### ISSUE TITLE
[Bug] No active UnityEngine.XR.XRInputSubsystem is available

### ISSUE THREAD

**Issue by marcinwalus** [Unity-Technologies/arfoundation-samples#854]
**Describe the bug**
I imported AR Foundation in my project and configured XR Plug-in management to initialise on startup and tuned on provider for ARKit. After cloning repo with project (repo contains XR folder with corresponding loaders and settings) and building iOS Player from build script, by calling BuildPipeline.BuildPlayer(buildPlayerOptions); and running generated iOS project on device I'm getting following errors and no AR Session is started:

No active UnityEngine.XR.XRInputSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
No active UnityEngine.XR.ARSubsystems.XRCameraSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
No active UnityEngine.XR.ARSubsystems.XRRaycastSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
No active UnityEngine.XR.ARSubsystems.XRDepthSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
No active UnityEngine.XR.ARSubsystems.XRPlaneSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
No active UnityEngine.XR.ARSubsystems.XRAnchorSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings. 

The point is that after **second build** it works correctly.
In scenario when building projects using CI it is very annoying.

**To Reproduce**
1. Configure AR Foundation in project
2. Build iOS Player from build script (ie. /Applications/Unity/Hub/Editor/2020.3.13f1/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -logFile editor_ios.log -projectPath <project-path> -buildTarget iOS -executeMethod BuildScript.PerformIOSBuild)
3. Run exported iOS project
4. AR Session is not starting and  "No active UnityEngine.XR.XRInputSubsystem is available" message is logged.

**Expected behavior**
AR Session should start correctly.

**Actual behavior**
AR Session is not starting.

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: 14.6
 - Unity version: 2020.3.13 (macOS 11.4)
 - ARFoundation version: 4.1.7, XR Plug-in Management 4.0.6

![ARIssue01](https://user-images.githubusercontent.com/1926917/126300655-ab58b782-054e-42c9-9d24-c73d3c914df7.png)
![ARIssue02](https://user-images.githubusercontent.com/1926917/126300673-45f8a4c2-ea2d-400c-9743-4d8929793c99.png)
![ARIssue03](https://user-images.githubusercontent.com/1926917/126300693-f8f5d7a4-9715-4c7e-95c0-2683c2dc3e52.png)

**Comment by todds-unity** [comment]
Please file a bug at [https://unity3d.com/unity/qa/bug-reporting](https://unity3d.com/unity/qa/bug-reporting) .
