### ISSUE TITLE
ARCollaboration in iOS 14 

### ISSUE THREAD

**Issue by Hamza004** [Unity-Technologies/arfoundation-samples#855]
How do I run ARCollaboration in iOS 14 iPad's.

I built the project on XCode 12.4 (12D4e), I ran the app in 2 different iPad's (iOS 14.6 and iOS 14.4.2). Accessed the particular scene 'AR Collaboration'. It did ask me for Camera and Local Network Access permissions. After all this the data is not transferred. The 'send' and 'recv' stays red the whole time and upon clicking only 'local' anchors gets created. 
I also edited the info.plist for 'Privacy - Location When In Use Usage Description' and 'Bonjour services' both Tcp and Udp, they follow the syntax guidelines but still no luck. I'm running both the iPad's on the same wifi with bluetooth on.

What exactly is going wrong. ??
****

**Comment by DavidMohrhardt** [comment]
I am unable to reproduce this against iOS 14.5 and 14.6 (iPhone XS and iPhone 12 Pro).  Try ensuring that your devices are on the same iOS version and trying again.  If that still doesn't work then it likely has to do with your LAN.

**Comment by stevenbajer** [comment]
Not bug, only one question. Could you help me explain the ARHumanBody's field？ I am wondering that what's the archor pose? Thanks you very much!

**Comment by ankur-unity** [comment]
> Not bug, only one question. Could you help me explain the ARHumanBody's field？ I am wondering that what's the archor pose? Thanks you very much!

@stevenbajer - Please refer to the ARKit documentation on rigging the character for animation.
https://developer.apple.com/documentation/arkit/content_anchors/rigging_a_model_for_motion_capture?language=objc

**Comment by Hamza004** [comment]
I solved it by edititng the following, i don't know if it's the right thing to do, but it worked.
Under the Script "CollaborationNetworkingIndicator.cs", under Update function, set the following variables accordingly:
s_IncomingDataReceived = true;
s_OutgoingDataSent = true;
s_HasCollaborationData = false;

It worked for me. The connection was successful.
