### ISSUE TITLE
How to track more Faces while the World camera is engaged?

### ISSUE THREAD

**Issue by sallywuzhere** [Unity-Technologies/arfoundation-samples#857]
Greetings Devs,

My goal is to track the Maximum number of faces on iOS (currently 3) while simultaneously displaying imagery from the World camera as a RenderTexture.

Using the WorldCameraWithUserFacingFaceTracking.unity example scene, I notice that when I toggle to the World Camera, the number of Maximum tracked faces drops from 3 to 1.

What is responsible for this limitation, and is there any way around it?

Alternatively, is there some other way to grab textures from the World camera in realtime? I've noticed Apple's "Multicam" PIP example could perhaps do this, but I haven't found a corresponding implementation in ARFoundation yet (https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/avmulticampip_capturing_from_multiple_cameras).

Thank you for your support,
Sally

**Comment by DavidMohrhardt** [comment]
The limitation is on `ARKit`'s side.  In the native plugin we check the [supportedNumberOfTrackedFaces](https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration/3194575-supportednumberoftrackedfaces?language=objc) value on the current configuration and enforce that as the maximum number of simultaneous faces.

As for `AVMultiCamPiP` we haven't attempted to implement this with ARKit running so it's unknown whether that would work.  You could try using a [WebCamTexture](https://docs.unity3d.com/ScriptReference/WebCamTexture.html) against the [backfacing device camera](https://docs.unity3d.com/ScriptReference/WebCamDevice.html)

```csharp
backTex = new WebCamTexture(backCamName, width, height, fps);
if (backTex.isPlaying)
{
    // Sample
}
```
