### ISSUE TITLE
OPPO F11 (Non-Pro) ARCore Installed but not detected running.

### ISSUE THREAD

**Issue by egdose** [Unity-Technologies/arfoundation-samples#858]
[Background Info]
My device is technically not supported by ARCore, but the Pro variant of this same model does support ARCore. I've checked the detailed specifications of both these variants, their camera is the same.

So the play store doesn't allow me to install google services for AR on my phone.

[Solutions I've Tried]
I downloaded the APK and got it running on my phone.

[The Problem]
With the API running, the AR still doesn't work. Log files of check support page are:
"Checking for AR support...
Your device supports AR, but requires a software update.
Attempting install..."

Now if I don't have the APK installed indirectly, this would lead me to the play store page where I would see that I cannot install it.

But if the APK is installed, I see the screen that I've attached.
![image](https://user-images.githubusercontent.com/57728907/127849415-1d872c3a-f7c7-421b-b714-0bb006d588c4.png)

Is there a way I can bypass this check and get ARCore running on my device?

**Comment by tdmowrer** [comment]
You cannot run ARCore on an unsupported device. If you side load the "Google Play Services for AR" APK onto an unsupported device, and ARCore is listed as "required" in your app manifest, then the behavior you describe is expected; see [Google's documentation](https://developers.google.com/ar/reference/c/group/ar-core-apk#group___ar_core_apk_1ga448092e9b601bc6f87d13d05317413f1) for more details.

**Comment by egdose** [comment]
Understandable.

Somethings I would like to add is that my app manifest marks AR Core as optional. Also, I've tested on another unsupported phone. This side loading method works there. I was really hoping it could work on mine too but I'm out of luck IG.

Any thing else I can do other then buying a different phone?

**Comment by tdmowrer** [comment]
You will need a [supported device](https://developers.google.com/ar/discover/supported-devices) in order to develop with ARCore.
