### ISSUE TITLE
How to Dynamically add ARObjects to an XRReferenceObjectLibrary

### ISSUE THREAD

**Issue by AkhilRaja** [Unity-Technologies/arfoundation-samples#859]
How do I use the XRReferenceObjectLibrary.Add() from the ARFoundation 4.2 version  to add a .arobject to the reference library. I am able to add an empty XRReferenceObject(name) with XRReferenceObjectLibrary.Add() to the reference library, but how do i create the entry dynamically and link it to a .arobject ??

**Comment by tdmowrer** [comment]
You need to add an "entry" to the `XRReferenceObject`. See [`AddEntry(XRReferenceObjectEntry)`](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.2/api/UnityEngine.XR.ARSubsystems.XRReferenceObject.html#UnityEngine_XR_ARSubsystems_XRReferenceObject_AddEntry_UnityEngine_XR_ARSubsystems_XRReferenceObjectEntry_).

An entry is the provider-specific asset; in this case, an [`ARKitReferenceObjectEntry`](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.2/api/UnityEngine.XR.ARKit.ARKitReferenceObjectEntry.html).

**Comment by AkhilRaja** [comment]
Hi @tdmowrer 
Appreciate the quick reply. 

I did try adding an entry to the XRReferencrObject, but here is my problem. 


I am creating an ARKitReferenceObjectEntry using the Create(NativeSlice<byte>) but it always returns a null. 

Here are the steps I followed:
1. File.ReadAllBytes(path) to get a byte[]
2. Convert the byte[] to a NativeArray<byte> with Allocator.Temp
3. Converting the NativeArray to NativeSlice<byte>(NativeAaray<byte>).SliceConvert<byte>()


I am not sure why it isn't getting deserialized to an ARReferenceObject.

**Comment by tdmowrer** [comment]
If it fails to deserialize, an error message is logged to the Xcode console. It will be of the form

```
ARReferenceObject initWithArchiveURL failed: <reason>
```

Do you see anything like that?

**Comment by AkhilRaja** [comment]
I was testing this on the Editor, it doesnt work on the Unity editor ?

**Comment by tdmowrer** [comment]
`ARReferenceObject`s are an iOS concept and can only be deserialized from raw bytes on iOS. However, each `.arobject` file in your project will get imported as an `ARKitReferenceObjectEntry` (the raw bytes of the file are stored and deserialized at runtime).

If you are trying to build a reference object library in the Editor, you can use the APIs defined in [`XRReferenceObjectLibraryExtensions`](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.2/api/UnityEditor.XR.ARSubsystems.XRReferenceObjectLibraryExtensions.html), notably `Add` and `SetReferenceObjectEntry`.

For a code reference, see the reference object library editor at `Editor/XRReferenceObjectLibraryEditor.cs` in the ARSubsystems package.

Note you can build reference object libraries in the Editor in all versions of AR Foundation that support object tracking; it is not new in 4.2.

**Comment by AkhilRaja** [comment]
@tdmowrer Thankyou so much for the explanation. I built my project to device and everything works as expected. Closing the issue with this comment. Thanks again.

**Comment by tomires** [comment]
Hello @AkhilRaja !
I just wanted to check on whether you were able to successfully deserialize an arobject file into ARReferenceObject and use it at runtime. If so, would you mind sharing a code snippet? I have been trying to do the same to no avail.

Thank you and have a nice day.

**Comment by AkhilRaja** [comment]
For everyone facing problems with this, this is how I did it. 
`
var byteData = System.IO.File.ReadAllBytes(filePath);
            Debug.Log("Created byte array" + byteData.Length);
            var byteArr = new NativeArray<byte>(byteData, Allocator.Temp);
            Debug.Log("Created native array" + byteArr.Length);

            aR = ARKitReferenceObjectEntry.Create(byteArr);
            aR.name = "Name";

            Debug.Log("Created XR Reference Object");

            if (aR == null)
            {
                Debug.Log("Reference Object Entry is null");
            }

            var referenceObject = new XRReferenceObject(GameManager.Instance.DRIP_ID);
            Debug.Log("Name of reference object is : " + referenceObject.name);
            referenceObject.AddEntry(aR);
            referenceLibrary.Add(referenceObject);
            
            aRTrackedObjectManager = gameObject.AddComponent<ARTrackedObjectManager>();
            aRTrackedObjectManager.referenceLibrary = referenceLibrary
            `

**Comment by tomires** [comment]
@AkhilRaja Works like a charm, thanks for the quick reply :)
