### ISSUE TITLE
[Bug] Sample Project crashes on start (iOs)

### ISSUE THREAD

**Issue by Silverbugi** [Unity-Technologies/arfoundation-samples#860]
**Describe the bug**
I don't know what could cause this but when I download the sample project, build it to iOS and start it, many sample scenes crash directly. For Example SimpleAR, CPU Images and Simple Occlusion.

The Error I get in Xcode is:
`2021-08-12 17:42:34.320794+0200 ARFoundationSamples[1222:516996] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ARFrame smoothedSceneDepth]: unrecognized selector sent to instance 0x100ee5ff0'
*** First throw call stack:
(0x188c6ac68 0x18898279c 0x188b75f90 0x188c6d7f0 0x188c6fae0 0x103c90078 0x103c8e6d8 0x1041596d4 0x10416b190 0x10413a48c 0x10413a368 0x1030887a0 0x103c4d75c 0x1035483cc 0x103553a58 0x103561214 0x1033cb614 0x10347a040 0x10347a080 0x10347a34c 0x1038017ac 0x1030187cc 0x103018734 0x1906a9c70 0x19077d2ec 0x188bc4fac 0x188be88c4 0x188be7e18 0x188be22b4 0x188be1630 0x1949bb818 0x18d36ea38 0x18d374928 0x103018204 0x10053be1c 0x188a6d38c)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ARFrame smoothedSceneDepth]: unrecognized selector sent to instance 0x100ee5ff0'
terminating with uncaught exception of type NSException`

**Smartphone:**
 - Device: iPad Pro 11"
 - OS: iPad OS 14
 - Unity version 2020.3.14f1
 - ARFoundation version, AR Core, ARKit - 4.2.0-pre.12

**Comment by tdmowrer** [comment]
Hi. I noticed you closed this without comment. What was the cause of this issue?

**Comment by Silverbugi** [comment]
> Hi. I noticed you closed this without comment. What was the cause of this issue?

The OS Version, with the newest update on the iPad the scenes work again.

**Comment by tdmowrer** [comment]
That [particular API](https://developer.apple.com/documentation/arkit/arframe/3674209-smoothedscenedepth?language=objc) was introduced in iOS 14, so it should not be a problem. Additionally, even if you were on an earlier version, like iOS 13, its usage is appropriately guarded by iOS version checks.

Out of curiosity, what version of Xcode are you using?

**Comment by Silverbugi** [comment]
It's the newest version from the App Store, Xcode 12.5.1.

The only thing I can say is that every scene, which had a feature included to place something on a plane, crashed instantly, also scenes like the CPU Image. Every other scene, for example for Light estimation was fine. So i can't really tell which feature or component caused the crashes
