### ISSUE TITLE
The front camera can't open in 2D and 3D human body tracking samples

### ISSUE THREAD

**Issue by stevenbajer** [Unity-Technologies/arfoundation-samples#861]
In humanbody tracking 2D and 3D samples of ARFoundation, I found that camera do not switch to User direction when I switch the facing direction of AR camera Manager from World to User.  These two samples always used the rear camera . Could you have other ways to switch rear camera  to front camera ?  Thanks!

**Comment by stevenbajer** [comment]
I readed the apple arkit document and find only the rear carema support this feature.....

**Comment by KirillKuzyk** [comment]
> In humanbody tracking 2D and 3D samples of ARFoundation, I found that carema do not switch to User direction when I switch the facing direction of AR Carema Manager from World to User. These two samples always used the rear carema. Could you have other ways to switch rear carema to front carema? Thanks!

ARKit doesn't support Human Body Tracking on a user-facing camera.

**Comment by stevenbajer** [comment]
The ARKit also support a feature that can detecting Human Body poses in Images through VNDetectHumanBodyPoseRequest, an image-based request type that detects key body points. If ARFoundation support this feature, I can using front camera to detect the 2D human body pose. If not support now, could you give me some advice how to add this feature or when ARFoundation support this feature ? Thanks a lot!

**Comment by DavidMohrhardt** [comment]
You would need to acquire the camera background texture to feed into `VNDetectHumanBodyPoseRequest`.  You can do this by acquiring the [CPU Camera Image](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/cpu-camera-image.html) to get the raw pixel buffer and then feed that into the API.
