### ISSUE TITLE
How to do QR Anchor in ARFoundation 5o align models in real world.

### ISSUE THREAD

**Issue by ajinkya446** [Unity-Technologies/arfoundation-samples#862]
How do I create QR Anchors support to align the BIM models in real world.

Platform: 
Unity editor 2019.4.21f and above
Android: Android 9 and above

**Comment by DavidMohrhardt** [comment]
ARFoundation doesn't support QR codes directly but you could use [image tracking](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/tracked-image-manager.html) to accomplish this.
