### ISSUE TITLE
BlendShape on ARCore (Android)

### ISSUE THREAD

**Issue by hiangsui** [Unity-Technologies/arfoundation-samples#863]
on Android or ARCore have any Feature like BlendShape on ARKit ?

on this video at 0 : 15 s.
https://www.youtube.com/watch?v=VetSQdmiT8g

**Comment by KirillKuzyk** [comment]
Hi Jatuphon,

No, unfortunately, Face Blendshapes is an ARKit exclusive feature and it's
not available on Android/ARCore.

**Comment by KirillKuzyk** [comment]
> on Android or ARCore have any Feature like BlendShape on ARKit ?
> 
> on this video at 0 : 15 s.
> https://www.youtube.com/watch?v=VetSQdmiT8g

No, unfortunately, Face Blendshapes is an ARKit exclusive feature and it's not available on Android/ARCore.

**Comment by hiangsui** [comment]
> > on Android or ARCore have any Feature like BlendShape on ARKit ?
> > on this video at 0 : 15 s.
> > https://www.youtube.com/watch?v=VetSQdmiT8g
> 
> No, unfortunately, Face Blendshapes is an ARKit exclusive feature and it's not available on Android/ARCore.

Thank you sir.
i have a second question. is have any way to do it like blendshape on android ?
not just on unity 3d.

**Comment by DavidMohrhardt** [comment]
This is not supported by `ARFoundation` w/`ARCore`.
