### ISSUE TITLE
About the Meshing and PointCloud

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/arfoundation-samples#865]
Does ARFoundation contain the following features?
1. [Displaying a Point Cloud Using Scene Depth](https://developer.apple.com/documentation/arkit/environmental_analysis/displaying_a_point_cloud_using_scene_depth)
2. [Export],[Scan with Texture] and [Point Cloud] in this [repo](https://github.com/TokyoYoshida/ExampleOfiOSLiDAR)
3. Based on those above, can I export the obj/fbx ,and even PLY file in Unity?

Thank you in advance!

**Comment by DavidMohrhardt** [comment]
The following docs should lead you in the right direction.  You could use the environment depth texture to generate your own point cloud based on the per pixel depth.

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html#UnityEngine_XR_ARFoundation_AROcclusionManager_environmentDepthTexture

**Comment by guoguoguilai** [comment]
Thanks for your response. Is there any detailed tutorial on this?

**Comment by guoguoguilai** [comment]
> The following docs should lead you in the right direction. You could use the environment depth texture to generate your own point cloud based on the per pixel depth.
> 
> https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/api/UnityEngine.XR.ARFoundation.AROcclusionManager.html#UnityEngine_XR_ARFoundation_AROcclusionManager_environmentDepthTexture

Thanks for your response. Is there any detailed tutorial on this?
