### ISSUE TITLE
ImageCheck of android device

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#866]
Recently I made an app that uses image recognition to generate different 3D objects on top of the recognition map.
1,when I use Samsung note10 to identify the image on the computer, the recognition speed is very fast, but when I identify the entity image, the recognition speed is very slow...That's why I'm confused.
2,When I use huawei p30 pro, the recognition speed is faster than that of Samsung note10, whether it is to recognize electronic images or physical images, and the recognition will not be long.
3,After the recognition of the two devices, will there be the phenomenon of 3D objects floating?
4,This app works perfectly on Apple using ArKit...
5, so how should I deal with these issues on Androd
![14](https://user-images.githubusercontent.com/47556504/129691694-6a950b2c-7ed6-42b9-8182-d79d988cf9f3.jpg)
![16](https://user-images.githubusercontent.com/47556504/129691752-df369e06-e664-4e6a-818c-568e899fc21c.jpg)
6，This is my test picture

**Comment by DavidMohrhardt** [comment]
Different android devices will have different levels of performance.  The floating 3D objects sounds like the devices might be losing tracking of the image causing the anchors to float.  You can use the [ARSession.stateChanged](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/api/UnityEngine.XR.ARFoundation.ARSession.html#UnityEngine_XR_ARFoundation_ARSession_stateChanged) event to determine when the tracking results are poor.
