### ISSUE TITLE
Image Tracking not working

### ISSUE THREAD

**Issue by DeveloperAugustus** [Unity-Technologies/arfoundation-samples#867]
How do I make image tracking work with one of the scenes provided within sample repo?
WorldCameraWithUserFacingFaceTracking  -- In this, I added AR Tracked Image Manager to AR Session Origin.
Assigned on XR lib also, assigned image to XR lib, still prefab not showing up on World Camera being selected.
Using Android.
How can I achieve it?

**Comment by ankur-unity** [comment]
Is the configuration that is being chosen for the device supports image tracking? You can find out the current configuration using [XRSessionSubsystem.currentConfigration](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.2/api/UnityEngine.XR.ARSubsystems.XRSessionSubsystem.html#UnityEngine_XR_ARSubsystems_XRSessionSubsystem_currentConfiguration)

Please also take a look at [configuration chooser](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/migration-guide-3.html#configuration-chooser).

**Comment by DeveloperAugustus** [comment]
Yes, I have previously used image tracking in my phone, OnePlus 6, worked on many prototypes.

**Comment by DeveloperAugustus** [comment]
So, I tried WorldCameraWithUserFacingFaceTracking Scene in iOS build, working pretty neat.
Don't know why not working in Android.

**Comment by tdmowrer** [comment]
Face tracking while using the world facing camera is an ARKit 
(iOS) specific feature and not supported by ARCore (Android). See also https://github.com/Unity-Technologies/arfoundation-samples#worldcamerawithuserfacingfacetracking
