### ISSUE TITLE
How to change the camera sensor ?

### ISSUE THREAD

**Issue by Morgan-6Freedom** [Unity-Technologies/arfoundation-samples#869]
On the Ipad 12 there is two camera, a wide angle and a normal angle.
By default, ARFoundation use the wide angle one.
How can I change to the other camera ?

![image](https://user-images.githubusercontent.com/49686866/130826466-1e38a52f-f679-4098-a260-ba9e2ed63a35.png)

**Comment by Morgan-6Freedom** [comment]
Thank you for the answer. You can close the issue.

**Comment by XtroTheArctic** [comment]
Hello, @DavidMohrhardt.

Can I kindly ask what you mean by enumerate the XRCameraConfigurations? Like getting the list of available camera configs from AR Foundation? Can you give me an idea about how to do it please?

I tried this but unfortunately, this collection contains zero element when I run the app on my iPad.

```
        var Configurations = ArCameraManager.GetConfigurations(Allocator.Temp);
```

**Comment by XtroTheArctic** [comment]
Now I tried it this way but the count of configs is still zero :(

```
        List<XRCameraSubsystem> Subsystems = new();
        SubsystemManager.GetSubsystems(Subsystems);

        var XRCameraSubsystem = Subsystems.First();
        var Configurations = XRCameraSubsystem.GetConfigurations(Allocator.Temp);
        print("Config count: " + Configurations.Length);
```
