### ISSUE TITLE
Proper way to switch between world and user tracking?

### ISSUE THREAD

**Issue by dmq-ar** [Unity-Technologies/arfoundation-samples#871]
Hello! 

For example, I've started my gameplay from scanning planes and placing AR objects on it. Classics.
But there is also a Face tracking feature in my app too, the user may have some fun with AR masks. 

What can I do for correct switching between world tracking and face tracking stuff?

I've already tried ToggleCameraFacingDirection.cs from the examples, however when you return back to world after face tracking the world objects turned out to be lost their old positions, AR Session became broken :(

**Comment by dmq-ar** [comment]
Seems I've found the [same question](https://forum.unity.com/threads/consistent-world-upon-switching-between-front-and-back-cameras.624364/) on Unity forum. Any update since 2019?

**Comment by tdmowrer** [comment]
The situation hasn't changed; swapping the camera facing direction effectively starts a new session.

However, on iOS only, you could create a world map just before you switch to user facing mode, then load it after you switch back to world facing mode. It would take a few moments to relocalize, but it should restore all anchors.

**Comment by dmq-ar** [comment]
> However, on iOS only, you could create a world map just before you switch to user facing mode, then load it after you switch back to world facing mode. It would take a few moments to relocalize, but it should restore all anchors.

Thank you, nice idea! 

Just to be sure:
1. I save my anchors to the world map
2. Hide all world objects
3. Do the ToggleCameraFacingDirection.cs stuff
4. Show an AR mask to the user
5. Go back again as in ToggleCameraFacingDirection.cs
6. Do the world map restoring
7. Show all my world objects.

Is this the proper algorithm for the case?

**Comment by ankur-unity** [comment]
> > However, on iOS only, you could create a world map just before you switch to user facing mode, then load it after you switch back to world facing mode. It would take a few moments to relocalize, but it should restore all anchors.
> 
> Thank you, nice idea!
> 
> Just to be sure:
> 
> 1. I save my anchors to the world map
> 2. Hide all world objects
> 3. Do the ToggleCameraFacingDirection.cs stuff
> 4. Show an AR mask to the user
> 5. Go back again as in ToggleCameraFacingDirection.cs
> 6. Do the world map restoring
> 7. Show all my world objects.
> 
> Is this the proper algorithm for the case?

@dmq-ar - Yes, these are the right steps.
