### ISSUE TITLE
Screen corner points in 3d

### ISSUE THREAD

**Issue by vinayvidhani** [Unity-Technologies/arfoundation-samples#872]
How I can get the screen corner points (3d)?
In order to share more details, Let say I am holding the camera at 45 degrees and I want to place 4 spheres in the world with respect to the screen or can throw a ray from my augmented object to the view which is visible from mobile.

Thanks for reading my question, If my question is not clear please do let me know. I will be looking forward to your reply.

Thanks

**Comment by tdmowrer** [comment]
Are you looking for ScreenToWorldPoint? https://docs.unity3d.com/ScriptReference/Camera.ScreenToWorldPoint.html

I'm not sure what you mean by 

> throw a ray from my augmented object to the view which is visible from mobile.

But there is also a similar API to turn a screen point into a ray.

**Comment by DavidMohrhardt** [comment]
Alternatively, you could just place your augmented objects at the corners of the Frustum Near Plane.  See [Camera.CalculateFrustumCorners](https://docs.unity3d.com/ScriptReference/Camera.CalculateFrustumCorners.html) for an example.  You will likely want to replace `camera.farClipPlane` with `camera.nearClipPlane`.

**Comment by vinayvidhani** [comment]
@tdmowrer  Thanks for the reply, Actually I want to record a video and then process the video for that I want to make my augmented object as an origin, and from the augmented object I need to throw a ray(to get the screen corner point in real-world), or I can say I want to calculate r and ϴ r will be the direction from the augmented object(origin) to 4 screen corner which is, of course, should be in 3d to better understand please refer the image. Please do let me know If I am clear https://github.com/vinayvidhani/ImageGallary/blob/main/problem.png

**Comment by vinayvidhani** [comment]
@DavidMohrhardt  thanks for the replay, I tried the same example but I will give it a try by using camera.nearClipPlane My actual problem is https://github.com/vinayvidhani/ImageGallary/blob/main/problem.png I will be very lucky If you could guide me a little. Thanks :)

**Comment by DavidMohrhardt** [comment]
If I understand your problem correctly then you are trying to compute a ray or rays from augmented object to camera corner in your augmented object's local space.  You can do this by using [Transform.InverseTransformPoint](https://docs.unity3d.com/ScriptReference/Transform.InverseTransformPoint.html).  

Something like the following might work:

```csharp
Ray[] CalculateLocalRaysFromObjectToNearFrustumCorners(Camera camera, Rect viewport, GameObject originObject)
{
    var frustumCorners = new Vector3[4];
    camera.CalculateFrustumCorners(viewport, camera.nearClipPlane, Camera.MonoOrStereoscopicEye.Mono, 
    frustumCorners);

    var cornerRays = new Ray[4];
    for (int i = 0; i < 4; ++i)
    {
        var objectToCameraCorner = originObject.transform.InverseTransformPoint(frustumCorners[i]);
        cornerRays[i] = new Ray(Vector3.Zero, objectToCameraCorner);
    }

    return cornerRays;
}
```

**Comment by vinayvidhani** [comment]
@DavidMohrhardt Thanks for the help, I  become very happy to see your post. I am trying to play with your suggestion and example but let me explain by taking an example. Please refer to the image from the below URL I need green points. I am dealing with 3d view. 
https://github.com/vinayvidhani/ImageGallary/blob/main/problem_1.png

Assume you have placed a 3d cube on the floor, If you see in your mobile phone, Maybe top corners are pointing towards the wall's and the bottom corners are pointing close to your feet. Think about this example and refer to the image. How I can get the green points. Hope this helps you to understand.

**Comment by ankur-unity** [comment]
> @DavidMohrhardt Thanks for the help, I become very happy to see your post. I am trying to play with your suggestion and example but let me explain by taking an example. Please refer to the image from the below URL I need green points. I am dealing with 3d view.
> https://github.com/vinayvidhani/ImageGallary/blob/main/problem_1.png
> 
> Assume you have placed a 3d cube on the floor, If you see in your mobile phone, Maybe top corners are pointing towards the wall's and the bottom corners are pointing close to your feet. Think about this example and refer to the image. How I can get the green points. Hope this helps you to understand.

@vinayvidhani - If you would to get the coordinates in the session space, you can use [Transform.InverseTransformPoint](https://docs.unity3d.com/ScriptReference/Transform.InverseTransformPoint.html) on the session origin.

**Comment by vinayvidhani** [comment]
Thanks, @ankur-unity @tdmowrer @DavidMohrhardt  for helping me. Actually, I am a bit tired and frustrated but still changed to fix my issue. Please refer to the image from the link below. Is the Sphere in the image(corner of camera view) is pointing to the camera corner in the real world? Can I say this? Can I say Sphere's position is the corner point of the real world with respect to camera view?

https://github.com/vinayvidhani/ImageGallary/blob/main/is_this_correct.png

**Comment by DavidMohrhardt** [comment]
We don't understand this use-case.

**Comment by vinayvidhani** [comment]
It's ok no problem, By the way, you guys are awesome, you took time to understand my problem, It's my bad I was unable to explain the problem.  Thanks for the help. I am closing this thread with a smile. :)
