### ISSUE TITLE
tracking image :  one picture - multi ar-image,   button "next and back" to change ar-images

### ISSUE THREAD

**Issue by sharehuster** [Unity-Technologies/arfoundation-samples#873]
i'm new dev. i trying make a project that can be track one image and show multi ar-image corresponding. this is done by button next and back to change ar-image.
Ex. i have a pictute " car" . i want button left and right ( back and next ) to change multi ar-image car 3d model
Can you help me pls?

**Comment by DavidMohrhardt** [comment]
https://forum.unity.com/threads/track-one-picture-show-multi-ar-image-arfoundation-arcore.1164001/#post-7462198

The forums are a better place for this kind of question.
