### ISSUE TITLE
How to reinitialize ARMeshManager after session Destruction and Creation

### ISSUE THREAD

**Issue by AdamBursill-SV** [Unity-Technologies/arfoundation-samples#874]
In our app, we have the option to kill and create a new AR session to make sure we know we are in a clean state. We are on version 4.1.7 of AR Foundation so this is done through the API of:
LoaderUtility.Deinitialize();
and 
LoaderUtility.Initialize();
We disable and reenabled all of the AR systems we are using so they reinitialize (ARCameraBackground, AR Input Manager, etc) but it appears the ARMeshingManager is written a little differently (inheriting directly from MonoBehavour) and so after session destruction and creation we get spammed with these errors:

ArgumentNullException: Value cannot be null.
Parameter name: _unity_self
  at UnityEngine.XR.ARFoundation.ARMeshManager.UpdateMeshInfos () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.ARFoundation.ARMeshManager.Update () [0x00000] in <00000000000000000000000000000000>:0

What is the correct way to reinitialize the ARMeshManager after manual session destruction and creation?

Versions:
AR Foundation 4.1.7
ARKit 4.1.7
ARSubsystems 4.1.7
XRManagement 4.0.1
Unity 2020.3.14f1

Testing on iPhone 12 Pro

**Comment by DavidMohrhardt** [comment]
This is a bug.  Please file a bug https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Comment by ankur-unity** [comment]
This has been fixed through [another issue](https://issuetracker.unity3d.com/issues/arf-mesh-manager-trying-to-access-subsystem-after-shutdown). The fix will be released in ARFoundation versions 4.2.2 and 5.0.0-prev.4.
