### ISSUE TITLE
How increase stability of a placed GameObject in ARFoundation ?

### ISSUE THREAD

**Issue by Sami-AlEsh** [Unity-Technologies/arfoundation-samples#876]
How do I increase stability of a placed Object on AR plane ?
Sometimes it just keeps jiggling, or flies a little higher, or it moves with device movement.

Suggestions:
Does placing object on a plane that has a bigger area is better ?
Does adding ARReferencePoint then placing objects under it (as child) is better ?

Project info:
Unity 2020.1.17f1
ARFoundation 4.1.1
ARCore XR Plugin 4.1.1

**Comment by ankur-unity** [comment]
> Does adding ARReferencePoint then placing objects under it (as child) is better ?

@Sami-AlEsh - You suggestion to add an AR Anchor should work okay. You can refer to the following sample for adding anchors.
https://github.com/Unity-Technologies/arfoundation-samples#anchors

You can also find further documentation on anchors at https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/anchor-manager.html
