### ISSUE TITLE
Android Error

### ISSUE THREAD

**Issue by MRLesile** [Unity-Technologies/arfoundation-samples#877]
zl@ZLdeMacBook-Pro MediaPipeUnityPlugin % python build.py build --desktop cpu --android arm64 -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: android_sdk_repository requires that at least one Android SDK Platform is installed in the Android SDK. Please install an Android SDK Platform through the Android SDK manager.
INFO: Elapsed time: 3.205s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (26 packages loaded, 22 targets configured)
    currently loading: @rules_foreign_cc//foreign_cc/private/shell_toolchain/toolchains ... (3 packages)
    Fetching @local_config_sh; fetching
Traceback (most recent call last):
  File "/Users/zl/data/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/zl/data/MediaPipeUnityPlugin/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/Users/zl/data/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.
zl@ZLdeMacBook-Pro MediaPipeUnityPlugin % 

How to Build Android aar，Someone Can Help?

**Comment by tdmowrer** [comment]
MediaPipe is a separate, unrelated technology. You might try creating an issue here: https://github.com/google/mediapipe
