### ISSUE TITLE
[Bug] XRCpuImage is constructed with the wrong XRCpuImage.Api in XROcclusionSubsystem.TryAcquireEnvironmentDepthConfidenceCpuImage

### ISSUE THREAD

**Issue by KirillKuzyk** [Unity-Technologies/arfoundation-samples#878]
**Describe the bug**
XRCpuImage is constructed with the wrong XRCpuImage.Api in XROcclusionSubsystem.TryAcquireEnvironmentDepthConfidenceCpuImage:
https://github.com/needle-mirror/com.unity.xr.arsubsystems/blob/master/Runtime/OcclusionSubsystem/XROcclusionSubsystem.cs#L298

**Expected behavior**
XRCpuImage is constructed with XROcclusionSubsystem.Provider.**environmentDepthConfidenceCpuImageApi**.

**Actual behavior**
XRCpuImage is constructed with XROcclusionSubsystem.Provider.**environmentDepthCpuImageApi**.

**Reproducible with**
AR Foundation 4.1.7, 4.2.0.

This bug doesn't cause issues with ARKit and ARCore because these providers use singleton XRCpuImage.Api for all CPU image types. But it causes an issue in a case of a custom AR provider that uses different instances of XRCpuImage.Api for different CPU image types.

**Comment by ankur-unity** [comment]
It will be fixed in the next release.

**Comment by ankur-unity** [comment]
A fix was released in AR Foundation version [5.0.0-pre.5](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/changelog/CHANGELOG.html#fixed) and will be backported to an upcoming release of 4.2.2.
