### ISSUE TITLE
Unity 2018.3 build failed if multi-threaded rendering is active

### ISSUE THREAD

**Issue by FDDdan** [Unity-Technologies/arfoundation-samples#88]
In the Unity 2018.3 changelog is mentioned that "XR: Android apps that use ARCore can now use multi-threaded rendering.", but using XR ARCore plugin and AR Foundation the build fails and through this error "Multithreaded Rendering and Graphics Jobs (Player Settings > Other Settings) are not supported for ARCore.".

I think that the XR ARCore plugin needs an update to check what version of Unity is using, to exclude this restriction from Unity 2018.3 and newer versions.

Any idea if this will be done in a future update, and if it is, when will that update be released?

**Comment by Tostifrosti** [comment]
https://fogbugz.unity3d.com/default.asp?1110363_jp82vbohnuibek4j

**Comment by Inspyro** [comment]
Any Updates on this?

**Comment by Berenice2018** [comment]
I am urgently looking for a solution concerning this problem. Has anyone heard of any updates? The last feedback in the above linked thread is 7 weeks old.

**Comment by Soorya611** [comment]
@tdmowrer any update on this?
When will the ARFoundation support multithreaded rendering?

**Comment by tdmowrer** [comment]
According to the [changelog](https://docs.unity3d.com/Packages/com.unity.xr.arcore@3.0/changelog/CHANGELOG.html#210-preview4---2019-05-08), multithreaded rendering support was added in May in version 2.1.0-preview.4. This is compatible with 2018.3+

**Comment by mdurand42** [comment]
FYI, we are working with Google on incorporating a new ARCore API that should improve rendering performance. We will update in a forum post when that ships.
