### ISSUE TITLE
How to completely disable/stop AR Plane manager to stop tracking planes after planes have been detected once?

### ISSUE THREAD

**Issue by DeveloperAugustus** [Unity-Technologies/arfoundation-samples#880]
How do I completely disable/stop AR Plane manager to stop tracking planes after planes have been detected once?

I have tried this code -- 

foreach (var plane in planeManager.trackables)
{
    plane.gameObject.SetActive(false);
}

but this only disable the tracked planes, further planes are getting detected.

is this code correct to work with? --       
planeManager.GetComponent<ARPlaneManager>().planePrefab.SetActive(false);

i tried this also, but its not working.

Please help, thanks.

**Comment by tdmowrer** [comment]
Disable the ARPlaneManager component to disable plane detection. So something like this:

```cs
planeManager.enabled = false;
```

**Comment by DeveloperAugustus** [comment]
> Disable the ARPlaneManager component to disable plane detection. So something like this:
> 
> ```cs
> planeManager.enabled = false;
> ```

So, that won't cause any problem is tracked planes?

**Comment by tdmowrer** [comment]
If you disable the plane manager, existing planes will remain but will not be updated. I'm not sure this answers your question though -- what problem are you concerned about?

**Comment by DeveloperAugustus** [comment]
Hi,
What i am trying to achieve is -- 
1. User opens app
2. user scans floor(that time mesh visualizer should show plane detection)
3. then, user places an object there, that time, mesh visualizer shouldn't be visible(should be disabled), no more further AR Plane scanning.
4. its more like this apps mechanism(pls watch this video) --- https://youtu.be/fNoB2Yf2gQs?list=PLEfj-Rw2SMk7QDBmqKVTKB3uKX9NAz5Vp

in this when user first scans the floor, there mesh visualizer is shown, then on point placement, its gone. 
That kind of behavior i want to achieve. 

5. I want to achieve similar mechanism, with mesh visualizer , point placement part already achieved

I hope you are understanding my point.
Thanks

**Comment by tdmowrer** [comment]
Alright, so to accomplish number 3, it sounds like you want to

1. Hide already detected planes (which you've done)
2. Disable plane detection (disable the ARPlaneManager)

And the rest is up to your app's logic.

**Comment by DeveloperAugustus** [comment]
So, 
Like this?-- 

foreach (var plane in planeManager.trackables)
{
    plane.gameObject.SetActive(false);

   planeManager.enabled = false;

}

If this is correct, won't that cause any issue ?

**Comment by tdmowrer** [comment]
You only need to disable the plane manager once, so you can move it outside the loop.

**Comment by DeveloperAugustus** [comment]
Alright, got it.
Thank a ton!
