### ISSUE TITLE
About Project Settings Differences with Default New Unity Project

### ISSUE THREAD

**Issue by andrewio** [Unity-Technologies/arfoundation-samples#881]
Hi, I noticed that the next settings in samples project are different from settings in New Unity Project (2021.1.20):

Physics:

- m_AutoSyncTransforms: 1
- m_ReuseCollisionCallbacks: 0

Project Settings: 

- androidUseSwappy: 0

Please comment each of them, why is it critical for AR Foundation to set these settings in these states. 
How are they affected to AR Camera or Trackables (Planes, Image Markers, Faces)?
 
Thank you.

**Comment by DavidMohrhardt** [comment]
None of these are critical to AR.

**Comment by tdmowrer** [comment]
Yeah, I think these are just minor differences between 2020 LTS and 20201.2's default project settings.

**Comment by andrewio** [comment]
So I guess you need to invert all of this.

Because In Docs said that your current state is deprecated: 
https://docs.unity3d.com/ScriptReference/Physics-autoSyncTransforms.html
https://docs.unity3d.com/ScriptReference/Physics-reuseCollisionCallbacks.html
