### ISSUE TITLE
Issue with MutableRuntimeReferenceImageLibrary.ScheduleAddImageWithValidationJob

### ISSUE THREAD

**Issue by jiungerich** [Unity-Technologies/arfoundation-samples#882]
**Unity bug report case number**
Case 1368240

**Describe the bug**
previously added images causes issues with adding more images to a MutableRuntimeReferenceImageLibrary.  As a result when the image starts to track it returns a null result for its name when it starts to track.

**To Reproduce**
1. Adds some tracked images to a tracked image session using MutableRuntimeReferenceImageLibrary.ScheduleAddImageWithValidationJob
2. Leave the session, disable it, leave the scene - do everything one can think of to reset it including ARSession.Reset.
3. Come back to the session, set a new referenceImageLibrary and add a set of images to it using MutableRuntimeReferenceImageLibrary.ScheduleAddImageWithValidationJob (this may contain some overlapping images from previously)
4. Several of the images when tracked now only return null for ARTrackedImage.referenceImage.name even though they caused no exceptions during the add image job.
5. Exit the app - start it again and everything loads fine 
6. try to add another image - it breaks 
**Expected behavior**
Expecting setting a different lIbrary or resetting the ARSession would wipe all preprevious library information allowing new images to be loaded without issue.

**Actual behavior**
Returns a new library name for the mutable library on return.  Even though all images have been loaded into this library, there is some interference with trackimages in other libraries that never seem to clear out.

**Smartphone (please complete the following information):**
 - Device: iPhone XR and Samsung Galaxy 7
 - OS: iOS 14.2 and Android 8.0.0
 - Unity version 2020.3.18f1
 - ARFoundation version 4.1.7

**Comment by jiungerich** [comment]
Regarding this bug.  If I put in code that tracks if Image was loaded at any time by ScheduleAddImageWithValidationJob after the app has started I can avoid getting a null return.  However, I can only do this if I do not change scenes.  If I place the ARSession in its own scene, then leave the scene and come back then even if I track which images were previously loaded I will get a null exception intermittently upon the scene loading.  This is even if the scene loaded fine previously.  This happens on the second or third scene reload.  On the first AR Session scene loading, all images will load fine.   With the scene change, it seems that error occurs right away and the null error occurs with any newly loaded image even though it is not duplicate.

**Comment by eusebiu** [comment]
Any solutions to this issue? The images can be registered only the first time; Afterwards the status is ErrorUnknown.

**Comment by gruprojekt** [comment]
This still exists, is there any workaround? Cause this we are loosing possibility to identify images from mutable library on scene loaded second time. The same setup on android works fine.

**Comment by Unity3D-Hardik** [comment]
Facing same issue with latest version , is there any solution ??

**Comment by Unity3D-Hardik** [comment]
@ankur-unity  Do you have any solution for this ? Its blocker for me....

**Comment by jiungerich** [comment]
As the OP there is no solution for this - this bug just timed out.  The issues are fundamental to memory structure that the image libraries are stored in and the only way to actually reset them is to close the app completely for everything to refresh.  I am not sure if there will be a solution for this as I haven't heard anyone approaching this.

**Comment by gilsonjess9851** [comment]
m_TrackedImageManager = GameObject.FindObjectOfType<ARTrackedImageManager>();

    if (m_TrackedImageManager == null)
    {
        m_TrackedImageManager = new GameObject().AddComponent<ARTrackedImageManager>();
        DontDestroyOnLoad(m_TrackedImageManager);
    }
   
Try this
It worked for me.
It is important not to delete the ARTrackedImageManager and keep it as only one object.

**Comment by jiungerich** [comment]
umm - you were able to reset the image manager's persistent memory doing this?  because that is what this bug is.

**Comment by Unity3D-Hardik** [comment]
Manually initialize and deinitialize works, Still, this is in the testing phase will update you once the test case is complete.

**Comment by gilsonjess9851** [comment]
> umm - you were able to reset the image manager's persistent memory doing this? because that is what this bug is.

For my project, yes, I don't see the Texture memory stacking.
Also, I see Texture being unloaded during the unload scenes.

But be aware that 
UnityWebRequestTexture.GetTexture()
nonReadable must be true

The main problem I had before was that the ARTrackedImagesChangedEventArgs would return null after switching scenes two or three times

DontDestroyOnLoad(m_TrackedImageManager)
At least it helps me to use ARTrackedImages across scenes

**Comment by Unity3D-Hardik** [comment]
I was facing the same issue, sometimes we get null in the name while tracking the image, but now I did not see this kind of issue..
