### ISSUE TITLE
World Camera and AR mask

### ISSUE THREAD

**Issue by amir989** [Unity-Technologies/arfoundation-samples#883]
Hi All,

I know iPad pros with LiDAR camera don't support "World Camera and AR mask" due to the power consumption of the depth sensor, But I was wondering if the iPhone pros with LiDAR also have the same problem? I couldn't find anything on internet about it and I only have iPhone XS. I would appreciate if someone who has an iPhone pro with LiDAR can test and confirm if the " face mask with world camera" feature works. 

Thanks

**Comment by tdmowrer** [comment]
What's a "World Camera and AR mask"?

![Screen Shot 2021-09-27 at 4 31 12 PM](https://user-images.githubusercontent.com/4934281/134998971-a1b370c0-84c7-4641-899a-ca81d8fb2fc7.png)

If you mean [world-facing camera with user-facing face tracking enabled](https://github.com/Unity-Technologies/arfoundation-samples#worldcamerawithuserfacingfacetracking), that works with an iPhone 12 Pro, and you can query for support at runtime.

**Comment by tdmowrer** [comment]
The session exposes a set of available [configuration descriptors](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.2/api/UnityEngine.XR.ARSubsystems.XRSessionSubsystem.html#UnityEngine_XR_ARSubsystems_XRSessionSubsystem_GetConfigurationDescriptors_Allocator_); each descriptor tells you which features are simultaneously available.

It's also described at a high level in a [migration guide](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.2/api/UnityEngine.XR.ARSubsystems.ConfigurationChooser.html) and this Unite talk https://youtu.be/jBRxY2KnrUs?t=699
