### ISSUE TITLE
2d texture

### ISSUE THREAD

**Issue by jayp84847** [Unity-Technologies/arfoundation-samples#885]
How do I track face in Image with this. Like I want to track face from image(2D texture).

**Comment by jayp84847** [comment]
I want to track face in image. Like when user upload face can ar foundation track face in the image.

**Comment by tdmowrer** [comment]
You can add any image to a reference image library and start tracking it as an image. So, in your example, you could add a picture of a face and then track that exact picture. I'm still not sure I understand your use case, though.

**Comment by jayp84847** [comment]
I want to do something like,
1> add photo
2> ar foundation track face from added image
3> code will crop the face 
4> croped face texture will use for ar foundation live face 
     
![facial-landmarks-summary](https://user-images.githubusercontent.com/81388248/135899463-1358f3fc-e0ae-4cc9-91b5-f119267bc93c.png)
 filter

**Comment by tdmowrer** [comment]
You can't use face tracking on an in-memory image. It might work in some cases if you printed out the photo (and are okay with having to use the user-facing camera). iPhones, however, rely on a TrueDepth camera; that is, they expect a 3D face, not a 2D photo, so I'm not sure how well that would work.

If I understand you correctly, this doesn't sound like something for which AR is well suited. There are other face detection frameworks that might be a better fit, e.g., OpenCV.

**Comment by jayp84847** [comment]
Okkkkk thank you for sich a reply

**Comment by tdmowrer** [comment]
You're welcome :)
