### ISSUE TITLE
Fixation Point 2D Visualizer

### ISSUE THREAD

**Issue by simonbrtrnd** [Unity-Technologies/arfoundation-samples#889]
Hi,

I try the FixationPoint scene from arfoundation-samples.
The reticule shows on the screen, however it doesn’t seems to be position where I am looking at on the screen. Is it the expected behaviour ?

In the attached video I am looking at each corner of my screen, one after the other. As you can see the reticule seems to move accordingly but stay in the “middle” part of the screen.
Is there a way to “calibrate” the reticule position to match with the screen ?

https://user-images.githubusercontent.com/20772024/137722399-acaabdc0-9e84-408b-b8d6-a208d67a65b1.mp4

Everything seems to be happening in this function inside the FixationPoint2DVisualizer.cs script but I don’t really know what should I do to make it works.

```
    void UpdateScreenReticle()
    {
      var mainCamera = Camera.main;

      var fixationInViewSpace = mainCamera.WorldToViewportPoint(m_Face.fixationPoint.position);

      // The camera texture is mirrored so x and y must be changed to match where the fixation point is in relation to the face.
      var mirrorFixationInView = new Vector3(1 - fixationInViewSpace.x, 1 - fixationInViewSpace.y, fixationInViewSpace.z);

      if (m_FixationReticleGameObject != null)
      {
        m_FixationReticleGameObject.GetComponent<RectTransform>().anchoredPosition3D = mainCamera.ViewportToScreenPoint(mirrorFixationInView);
      }
    }
```
Device: iPhone X
OS: iOS 14.7.1
Unity version 2020.0.3.f1

Thanks for your help.

**Comment by DavidMohrhardt** [comment]
The fixation point is based on the [ARKit lookAtPoint](https://developer.apple.com/documentation/arkit/arfaceanchor/2968192-lookatpoint?language=objc).  This value is entirely based on where the device thinks you are looking in 3D which doesn't necessarily mean the device screen.  We don't have control over what the device is reporting but you may have more luck by moving the phone a little further away from your face.
