### ISSUE TITLE
How to get the ARplane Boundary in World Space

### ISSUE THREAD

**Issue by lck666666** [Unity-Technologies/arfoundation-samples#892]
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARPlane.html?q=plane

It seems like we can only get boundary points in plane space as a 2D vector. How can I get ARplane's boundary points in world space like the center? The description of the plane space makes me feel confused.  "The plane's boundary points, in plane space, that is, relative to this ARPlane's local position and rotation."

**Comment by lck666666** [comment]
> > But I sometimes get normals whose three coordinates are not zero
> 
> It won't always be exact. In my experience, planes can deviate up to 10 degrees from pure vertical or horizontal. That's what the underlying AR engine is giving us (e.g., ARKit / ARCore).
> 
> > Besides, can we get the intersection between the ARplane and the 2d surface on screen in screen space?
> 
> You can use [Camera.WorldToScreenPoint](https://docs.unity3d.com/ScriptReference/Camera.WorldToScreenPoint.html) to get the screen space coordinates, but you'll need to compute intersections yourself. There are a number of methods to do this; it is commonly needed for collision detection, so you might look into [Minkowski sums](https://en.wikipedia.org/wiki/Minkowski_addition) or [separating axis](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem#Use_in_collision_detection).

Sorry, I still don't know how to get the world space coordinates of a plane boundary point. So I cannot use  Camera.WorldToScreenPoint to get the screen space coordinates.  How is the local space of ARplane established?

**Comment by lck666666** [comment]
> > But I sometimes get normals whose three coordinates are not zero
> 
> It won't always be exact. In my experience, planes can deviate up to 10 degrees from pure vertical or horizontal. That's what the underlying AR engine is giving us (e.g., ARKit / ARCore).
> 
> > Besides, can we get the intersection between the ARplane and the 2d surface on screen in screen space?
> 
> You can use [Camera.WorldToScreenPoint](https://docs.unity3d.com/ScriptReference/Camera.WorldToScreenPoint.html) to get the screen space coordinates, but you'll need to compute intersections yourself. There are a number of methods to do this; it is commonly needed for collision detection, so you might look into [Minkowski sums](https://en.wikipedia.org/wiki/Minkowski_addition) or [separating axis](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem#Use_in_collision_detection).

I want to know what kind of rules do you use to set up plane's coordinates?  For the plane space of a ARplane, I can create an infinite number of two-dimensional x-y coordinate systems. If I can only get the coordinates of the plane coordinate system, this coordinate has nothing to do with world space, then what is the meaning of this coordinate? These two dimensional coordinates make no sense.

**Comment by tdmowrer** [comment]
> Sorry, I still don't know how to get the world space coordinates of a plane boundary point.

Did you try this? https://github.com/Unity-Technologies/arfoundation-samples/issues/892#issuecomment-951457427

If so, what was the result?

**Comment by lck666666** [comment]
> > Sorry, I still don't know how to get the world space coordinates of a plane boundary point.
> 
> Did you try this? [#892 (comment)](https://github.com/Unity-Technologies/arfoundation-samples/issues/892#issuecomment-951457427)
> 
> If so, what was the result?

I did some tests, and it turns out that all the y-coordinates of these points are 0 in world space. But the normals are not always (x=0, y=1, z=0), the y-coordinates of the center in world space is also not 0. I don't think this transformation is right.

For some examples:
{"boundarys":{"x":-0.285279810428619,"y":0.0,"z":-0.136438250541687},
"centerInPlaneSpace":{"x":0.0750000476837158,"y":-0.0500000081956387},
"centerInWorld":{"x":0.0416899248957634,"y":-0.0939753949642181,"z":0.901597261428833},
"normal":{"x":0.178143694996834,"y":0.0239517688751221,"z":-0.983713030815125}}.

{"boundarys":{"x":-0.173648566007614,"y":0.0,"z":-0.223262563347816},
"centerInPlaneSpace":{"x":0.00310090184211731,"y":-0.0217060744762421},
"centerInWorld":{"x":0.0668447762727737,"y":-0.247549951076508,"z":0.383341193199158},
"normal":{"x":0.0,"y":1.0,"z":0.0}}

{"boundarys":{"x":-0.285279810428619,"y":0.0,"z":-0.136438250541687},
"centerInPlaneSpace":{"x":0.0750000476837158,"y":-0.0500000081956387},
"centerInWorld":{"x":0.0416899248957634,"y":-0.0939753949642181,"z":0.901597261428833},
"normal":{"x":0.178143694996834,"y":0.0239517688751221,"z":-0.983713030815125}},

**Comment by tdmowrer** [comment]
This is how the ARPlane calculates the center in world space:

```cs
public Vector3 center => transform.TransformPoint(new Vector3(centerInPlaneSpace.x, 0, centerInPlaneSpace.y));
```

Whose `transform` are you using? (It should be the ARPlane's.)

**Comment by lck666666** [comment]
> This is how the ARPlane calculates the center in world space:
> 
> ```cs
> public Vector3 center => transform.TransformPoint(new Vector3(centerInPlaneSpace.x, 0, centerInPlaneSpace.y));
> ```
> 
> Whose `transform` are you using? (It should be the ARPlane's.)
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARPlane.html?q=plane
![image](https://user-images.githubusercontent.com/45345893/139781404-9fff3a66-a201-4b82-bf1e-7b6dd18aa54b.png)
I do not use transform, it seems like we can get the center in world space directly in the doc.
![image](https://user-images.githubusercontent.com/45345893/139781503-cd97025c-1a06-4ce8-81a0-6a64b6f9c024.png)

**Comment by lck666666** [comment]
> This is how the ARPlane calculates the center in world space:
> 
> ```cs
> public Vector3 center => transform.TransformPoint(new Vector3(centerInPlaneSpace.x, 0, centerInPlaneSpace.y));
> ```
> 
> Whose `transform` are you using? (It should be the ARPlane's.)

The doc of ARPlane says that we can get the center in world space directly. 
So I just use plane.center. 

But in this way, the result shows that the center and boundary  points are no longer in the same plane......

**Comment by tdmowrer** [comment]
> The doc of ARPlane says that we can get the center in world space directly.
> So I just use plane.center.

I'm not suggesting you do anything different. You said `transform.TransformPoint(x, 0, y)` did not work for you, so I was just pointing out this is how the ARPlane converts the 2D plane-space center point into the 3D world-space center point.

I don't know what `transform` is in the context of your code snippet, but you need to use the ARPlane's transform. Maybe try this instead:

```cs
plane.transform.TransformPoint(new Vector3(pos.x, 0, pos.y));
```

**Comment by lck666666** [comment]
> > The doc of ARPlane says that we can get the center in world space directly.
> > So I just use plane.center.
> 
> I'm not suggesting you do anything different. You said `transform.TransformPoint(x, 0, y)` did not work for you, so I was just pointing out this is how the ARPlane converts the 2D plane-space center point into the 3D world-space center point.
> 
> I don't know what `transform` is in the context of your code snippet, but you need to use the ARPlane's transform. Maybe try this instead:
> 
> ```cs
> plane.transform.TransformPoint(new Vector3(pos.x, 0, pos.y));
> ```

Thx!! It works for me. I'm sorry I  do not use 
```python
 Vector3 center = plane.transform.TransformPoint(new Vector3(pos.x, 0, pos.y));
````

I use 
```python
 Vector3 center = transform.TransformPoint(new Vector3(pos.x, 0, pos.y));
````
instead, so it is wrong.
