### ISSUE TITLE
Infinite Planes on Android?

### ISSUE THREAD

**Issue by dxt298** [Unity-Technologies/arfoundation-samples#893]
I've known a long time ago when setting up our project that infinite planes didn't play well in ARCore due to 
https://github.com/Unity-Technologies/arfoundation-samples/issues/135

However today in testing I decided to try it out on a whim (while using AR Foundation Editor Remote from the Asset Store to see plane positions relative to our trigger image), and it seemed to work perfectly fine.
<img width="399" alt="Screen Shot 2021-10-27 at 4 05 28 PM" src="https://user-images.githubusercontent.com/7322280/139146914-eb4562d3-7f1e-427c-9359-75aea58242ec.png">

We raycast from the trigger image straight downwards, and attempt to hit a plane, and even in the case of planes not being below the image, the raycast succeeded in getting a hit.

However the same doesn't seem to be occurring when I build the app and run it normally -- in fact, it seems even harder to get a raycast from the scanned image to successfully hit a plane below it.

So:

- Do infinite planes work in ARCore?  Or the status of issue 135 still hold true (that ARCore doesn't really support it)
- Why is it that it works "in the editor" (though I assume this isn't question for here and is more a question for the asset creator)
- What happens when attempting to raycast and trying to use PlaneWithinInfinity on android?  What does it "default" to if ARCore doesnt support it?

**Comment by Juanamsnk** [comment]
@KirillKuzyk Hi, I have some doubts about how to use the function, from where do you call this function? and second, on the line "return new ARRaycastHit (hit, distanceInWorldSpace, trackablesParent, planeManager.GetPlane (hit.trackableId));" ARRaycastHit appears to me in red underlined. All the best.
