### ISSUE TITLE
How to map colors from XRCpuImage to points in 3D space and avoid delay?

### ISSUE THREAD

**Issue by dzak83** [Unity-Technologies/arfoundation-samples#895]
Hi,
I am using TryAcquireLatestCpuImage to get CPU image. Then I am trying to map the color value for the points in the 3D space. I would usually do it by calling "Camera.main.WorldToViewportPoint(pointIn3D)" and then I would map it to CPU image position. 

However, even if I am calling TryAcquireLatestCpuImage(out XRCpuImage image) and then image.Convert(..), which should be sync operation, I think I am still getting an image that is delayed and won't be align with current Camera.main position.

I noticed there is _projectionMatrix_ available in the ARCameraFrameEventArgs object but to simulate WorldToViewportPoint, I also need _worldToCameraMatrix_ which is not available.

How can I get WorldToViewportPoint method equivalent with AR Foundation CPU image APIs or "Matrix4x4 mvp = Camera.main.projectionMatrix * Camera.main.worldToCameraMatrix" co I can call on it MultiplyPoint later?

Is there anything big I am missing? Right now, when I am move the device quicker, every scan is overriding colors.

**Comment by MoritzSkowronski** [comment]
@dzak83 Currently struggling with the same thing. As soon as I start to move the device a bit faster, everything drifts. Did you ever come up with a solution for that?

**Comment by manwithsteelnerves** [comment]
@dzak83 Did you find a solution?

**Comment by dzak83** [comment]
Yes. In my case it was a problem with camera frustum. CPU image has a different width/height ratio than what I see on the screen = 3D points on the screen. If I tried to match CPU image that is coming from the camera to my screen view, it was incorrect, my screen was e.g. wider than CPU image.

I am not sure how to explain it better. I noticed it because the middle of the screen was mapped correctly, but the further I mapped colors from the screen center, the more incorrect it would be. That's when I noticed my mistake. 

API is fine, once I fixed above, colors are ok

**Comment by manwithsteelnerves** [comment]
> 

Yes, the cpu image is having the default original captured resolution (usually 640x480) and is different from what ar background shows up (as it covers full screen).

May I know how you mapped it pick the right color?
You took a world point, transformed it to screen position and then did a color pick on the texture? If so how you mapped the cpuImage dimensions as visually the background image is full screen.
