### ISSUE TITLE
Tracking Broken on iOS 12

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/arfoundation-samples#9]
Tested on an iPhone 6s and 7+, iOS 12 beta 1 and beta 2.

After a few seconds Unity will stop receiving updates from ARKit and all graphical elements (camera, detected planes, pointcloud, hit test object) will be frozen on the screen. The color background image will keep updating.

There are repeated messages that "World tracking performance is being affected by resource constraints" every few seconds leading up to the freeze. No error messages are present in XCode.

This is running the AR Foundation sample scene with no additions or changes. AR Foundation does not freeze in iOS 11.4. The standalone UnityARKitPlugin runs fine on both devices in iOS 12.

**Comment by sam598** [comment]
Appears to have been solved by adding the following line to the Awake() function of ARCameraBackground.cs

`Application.targetFrameRate = 60;`

It's possible that running Unity at 30fps causes some kind of bottleneck on the GPU that prevents ARKit from running it's tracking algorithms properly. Doing more tests and leaving the issue open for now.

**Comment by timm-unity** [comment]
Thanks for reporting. We'll look into it.

**Comment by mimminito** [comment]
Anyone else having this issue on latest public iOS 12? Having real bad tracking issues and the camera rendering if very glitchy.

**Comment by josefgrunig** [comment]
Same issue, but using the Unity-ARKit-Plugin. ([see issue](https://bitbucket.org/Unity-Technologies/unity-arkit-plugin/issues/36/frequent-performance-issue-technique-world))

Symptoms
- Xcode Console logs "[Technique] World tracking performance is being affected by resource constraints"
- Camera "freezes" for few frames every 3-5 seconds

My only solution was to switch to an iPad Pro for the boot. 
Right now on lower hardware the plugin is not production ready.
