### ISSUE TITLE
why arcore.depth is added to my build

### ISSUE THREAD

**Issue by shacharoz** [Unity-Technologies/arfoundation-samples#900]
i made a build of the face tracking demo.
on the phone it looks great.
but when uploading to the play store, it identifies this suitable for 250 devices, since it has the arcore.depth library...

the Arcore is marked required, and the Depth as optional.
any ideas why that is?

**Comment by tdmowrer** [comment]
Depth is required by default, but you can change it in Project Settings:

<img width="855" alt="Screen Shot 2021-11-01 at 4 52 35 PM" src="https://user-images.githubusercontent.com/4934281/139757262-f1e48abc-ff33-4400-8500-830a99c5fb24.png">

**Comment by shacharoz** [comment]
but i have the depth marked Optional in this screen.
when uploading to the Play store, the google team tells me it exists in the list of required packages in the manifest... :(

**Comment by tdmowrer** [comment]
Hmm, I don't know then. Please log a bug here: https://unity3d.com/unity/qa/bug-reporting

**Comment by shacharoz** [comment]
hi @tdmowrer (Tim).
just to close this ticket (and open a new one...), i will write what happened.

i do not know exactly what solved it, but I have removed he XR Interactions package, moved back to the OLD Input system, of unity, and changed some Player settings (attached is my current settings with unity 2020.3).

the new issue now is that the app crashes the second it starts up. but I will open a new issue.

**Comment by tdmowrer** [comment]
> the new issue now is that the app crashes the second it starts up...Give me another day and I will update. I think it is related to ARM64 and ARM7.

You're probably right. See https://developers.google.com/ar/64bit:

> 32-bit-only ARCore-enabled apps that aren't updated will fail to create an ARCore session and might crash when attempting to start an augmented reality (AR) session on affected 64-bit devices.
