### ISSUE TITLE
Are 3D Body tracking and world maps incompatible?

### ISSUE THREAD

**Issue by Patrick-WA** [Unity-Technologies/arfoundation-samples#901]
I am testing an ARFoundation project on ARKit, using an iPad Pro 2020.
Unity version : 2020.3.20f1
AR packages version : 4.1.7

In one of my Unity scene, I have the AR Human Body Manager script on my AR session origin and the Human Body tracking object from the 3D human body tracking template and it works fine when I build and run this scene on my iPad.

However, in my main scene, I want to use world maps and image tracking in addition to 3D Body tracking. Therefore, I have on my AR Session Origin : the AR Tracked image manager, the AR Anchor Manager and the AR Plane Manager in addition to the AR Human Body Manager. I also have an ARMeshManager set as child of my AR Session Origin. And last but not least, the Human Body Tracker object.
When I build my main scene, although I do not get any error, body tracking just won't work : people in front of the camera are never recognized and I never get the "Adding a new skeleton" debug log.

Are 3D Body tracking and world maps incompatible? Do you have any lead on why this won't work?

**Comment by ankur-unity** [comment]
This appears to be a configuration issue.  Not all features are supported in each configuration.  You can find additional details in [this video](https://youtu.be/jBRxY2KnrUs?t=677).
