### ISSUE TITLE
AR foundation black screen unity(2019.x-2021.x) 

### ISSUE THREAD

**Issue by illuminat146** [Unity-Technologies/arfoundation-samples#903]
hello, I don't know what to do anymore, nothing helps, I created the AR Foundation ARcore project and created a project with tracking tags. everything worked, but suddenly it stopped for no reason, created already 1 in 1 as in the tutorials, ticked everything but still gives out a black screen. and if I download someone's AR project, obviously a working one, I open it in the same version, then all the same a black screen (and I have such garbage both on my computer and on my laptop), sometimes it gives an errors

1) No active UnityEngine.XR.ARSubsystems.XRSessionSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.XR.ARFoundation.ARSession:OnEnable () (at Library/PackageCache/com.unity.xr.arfoundation@4.1.7/Runtime/AR/ARSession.cs:341) 
2) No active UnityEngine.XR.XRInputSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.XR.ARFoundation.ARInputManager:OnEnable () (at Library/PackageCache/com.unity.xr.arfoundation@4.1.7/Runtime/AR/ARInputManager.cs:24)
3) No active UnityEngine.XR.ARSubsystems.XRCameraSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.XR.ARFoundation.SubsystemLifecycleManager`3<UnityEngine.XR.ARSubsystems.XRCameraSubsystem, UnityEngine.XR.ARSubsystems.XRCameraSubsystemDescriptor, UnityEngine.XR.ARSubsystems.XRCameraSubsystem/Provider>:OnEnable () (at Library/PackageCache/com.unity.xr.arfoundation@4.1.7/Runtime/AR/SubsystemLifecycleManager.cs:87)

I reviewed a bunch of videos and sites, I could not find an answer to my question anywhere. this is my last hope

**Comment by ankur-unity** [comment]
Did it stop working on the same device that you were testing successfully before or on another device?

This appears to be a configuration issue. Not all features are supported in each configuration.  Make sure the device on which you are testing, supports ARCore and the feature configuration.  You can find additional details on configurations in [this video](https://youtu.be/jBRxY2KnrUs?t=677) and a list of ARCore supported devices can be found here: https://developers.google.com/ar/devices

**Comment by illuminat146** [comment]
he stopped, in principle, everywhere to work, including on devices where he initially worked successfully. my phone is on the list

**Comment by ankur-unity** [comment]
Can you try building the SimpleAR sample from this repository?
https://github.com/Unity-Technologies/arfoundation-samples#simplear

**Comment by illuminat146** [comment]
> Можете ли вы попробовать собрать образец SimpleAR из этой репозитории? https://github.com/Unity-Technologies/arfoundation-samples#simplear
but how to do it? just download the file, throw it into Unity and building?

**Comment by ankur-unity** [comment]
> but how to do it? just download the file, throw it into Unity and building?

https://github.com/Unity-Technologies/arfoundation-samples#instructions-for-installing-ar-foundation

**Comment by illuminat146** [comment]
does not work-black screen =( Google Play Services for AR reinstall
![Screenshot_2021-11-10-21-49-01-415_com unity arfoundation samples](https://user-images.githubusercontent.com/93773517/141166115-c0f41a6a-b216-420f-825d-7451d255f3fb.jpg)
ed

**Comment by illuminat146** [comment]
![image](https://user-images.githubusercontent.com/93773517/141166238-1621078e-e963-4092-a271-50cb258fba5e.png)
![image](https://user-images.githubusercontent.com/93773517/141166291-c27c04df-4dc0-4c22-93b1-9d3af2d21c73.png)
![image](https://user-images.githubusercontent.com/93773517/141166311-2e1d0e7f-15e6-414b-8773-e17fb62d180d.png)
![image](https://user-images.githubusercontent.com/93773517/141166336-9b8232d0-5963-4750-9c77-d8c81e921115.png)
![image](https://user-images.githubusercontent.com/93773517/141166520-4b000845-5351-44f3-bfcd-422d47b7443b.png)

**Comment by illuminat146** [comment]
I solved the problem, it was just that AR applications did not work on my phone, due to a system error, the restart helped, now everything works :D
