### ISSUE TITLE
[Bug] Memory leak due to AROcclusionManager confirmed on Android devices

### ISSUE THREAD

**Issue by nathantstevens** [Unity-Technologies/arfoundation-samples#904]
Case 1379235

**Describe the bug**
Anytime the AROcclusionManager component is attached to the camera, a memory leak occurs in which memory will constantly rise. Within just 10 minutes, memory usage went from around 300mb to 2GB. This occurs in 2020.3 with AR packages 4 and the new 2021.2 with the preview v5 AR packages as well. This occurred on a Samsung Galaxy S10+ using Android 11

**To Reproduce**
Build the repo onto device and run the simple depth scene. Taking memory snapshots will show the memory continuously rises even if the user does nothing. This does not occur in scenes that do not have the AROcclusionManager enabled

**Expected behavior**
Memory usage should stay fairly consistent

**Actual behavior**
Memory usage increases almost 7X within 10 minutes from 300mb to 2GB

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 11
 - 2020.3.21 & 2021.2.0
 - 4.1.7/4.2.1/preview 5

**Comment by aditakacs** [comment]
Same problem on iPhone 13 Pro. If I use AR Occlusion it throws and error after 5-10 seconds:
UnityGfxDeviceWorker (32): EXC_BAD_ACCESS (code=1, address=0x130e17e0)

**Comment by ankur-unity** [comment]
> Same problem on iPhone 13 Pro. If I use AR Occlusion it throws and error after 5-10 seconds: UnityGfxDeviceWorker (32): EXC_BAD_ACCESS (code=1, address=0x130e17e0)
> 
> -Device: iPhone 13 Pro
> -OS: iOS 15.0.2 & 15.1
> -2020.3.15f1 & 2020.3.22f1
> -4.1.7 & 4.2.1

@aditakacs - This issue is unrelated to the original issue of memory leak listed in [1379235](https://issuetracker.unity3d.com/issues/arcore-android-memory-leak-in-xr-application-when-using-arocclusionmanager-component). Can you file a bug report and open a separate issue for this?
https://unity3d.com/unity/qa/bug-reporting.

**Comment by ankur-unity** [comment]
The fix for this issue will be released in AR Core XR Plug-in Package versions 4.2.3 and 5.0.0-pre.8.
https://issuetracker.unity3d.com/issues/arcore-android-memory-leak-in-xr-application-when-using-arocclusionmanager-component
