### ISSUE TITLE
ARParticipant is not working now

### ISSUE THREAD

**Issue by yuchenz27** [Unity-Technologies/arfoundation-samples#905]
In ARCollaborationData example, the participant prefab is not working now.

From my understanding, after another player join the session and get synced, the participant prefab should be spawned and keep following that player's iPhone.

I did that once a few months ago and it worked, but now it is not working. How could I make it work again?

Here is what I did:

First I created a cube prefab and add an ARParticipant component to it

![image](https://user-images.githubusercontent.com/44870300/141262874-c4be9ccb-950d-4b93-be8d-d84e0ac66696.png)

Then I dragged that prefab to the participant prefab slot of ARParticipantManager component.

![image](https://user-images.githubusercontent.com/44870300/141262984-5370bca9-bfa6-4de3-94e9-f3386bc8e1a1.png)

Could anyone tell me why this is not working? Thanks!

**Comment by tdmowrer** [comment]
Could you provide us with the versions of...

- Unity
- AR Foundation and AR Kit packages
- iPhone models
- iOS versions (for each phone)

FWIW I just ran the latest version of this repo (AR Foundation 4.2 + Unity 2020.3) on an iPhone 12 and iPhone SE running iOS 15.0 and 14.2, respectively, and it generally seemed to work okay.

You said you aren't getting participants -- are the anchors being shared or are those missing too?

**Comment by yuchenz27** [comment]
Thank you for your help. I really appreciate it!

Here is my environment:

- Unity 2021.2.0f1 Silicon version
- AR Foundation package 4.2.0 and ARKit package 4.2.0
- iPhone 13 Pro and iPhone 13 Pro Max with iOS 15.1 and iOS 15.2, respectively

In my situation, the normal static ```ARAnchor```s were perfectly shared in the right positions, only the ```ARParticipentAnchor```s were missing. (Ideally, the prefab in ```ARParticipantManager``` component should be spawned and keep following the other peer's iPhone)

I ran this Apple Official example https://developer.apple.com/documentation/arkit/creating_a_collaborative_session?language=obj and got the same problem. After a peer had joined the Collaboration session, the delegate function ```session:didAddAnchors:``` was called and the added anchor was indeed of the class ```ARParticipantAnchor```. When I tried to print its transform matrix, I found that all values of the 4x4 transform matrix were NaN (not a number). After the ```ARParticipantAnchor``` was added, the delegate function ```session:didUpdateAnchors:``` was called every frame but the transform matrix was always NaN. Therefore, I think the problem is not from Unity but from ARKit.

It is very weird to me. From my understanding, one of the major points of the delegate function ```session:didUpdateAnchors:``` is to represent the real-time position and orientation of the other peer's iPhone, through the transform matrix of the ```ARParticipantAnchor```. If its value is always NaN, what is the point to share this data through the network in such high frequency (nearly every frame)?

I also posted this problem in Apple Developer Forum https://developer.apple.com/forums/thread/694478, but haven't got an answer yet.

**Comment by yuchenz27** [comment]
I just found a very interesting thing.

I have 3 devices:

- Device A: iPhone 13 Pro with iOS 15.1
- Device B: iPhone 13 Pro with iOS 15.1
- Device C: iPhone 13 Pro Max with iOS 15.2

When I was using device A and device B, I could not see ```ARParticipantAnchor``` on both devices.

When I was using device A and device C, I could see device C's ```ARParticipantAnchor``` on device A's screen, but not vice versa (I could not see device A's ```ARParticipantAnchor``` on device C's screen).

When I was using device B and device C, the situation was the same. I could see device C's ```ARParticipantAnchor``` on device B 's screen but not vice versa.

So, it seems that the problem is due to iOS version, iOS 15.2 works but iOS 15.1 doesn't. I will upgrade my devices and have another try.

**Comment by yuchenz27** [comment]
Ok, after I upgraded all my devices to iOS Beta 15.2, it worked perfectly! I even didn't rebuild the app, just upgraded the system.

**Comment by yuchenz27** [comment]
I have tested this on 4 devices, in all cases, iOS 15.1 didn't work and iOS 15.2 worked.
