### ISSUE TITLE
[Bug] ARCorePermissionManager should handle requesting and onpause situation

### ISSUE THREAD

**Issue by flankechen** [Unity-Technologies/arfoundation-samples#908]
**Describe the bug**
When requesting permission with ARCorePermissionManager  by ARCorePermissionManager.RequestPermission(String, Action<String, Boolean>), if user click home button and resume back to app. Permission requesting window is gone and No granted callback is called. We have no ways to resume permission request or raise another permission request. if call RequestPermission() again, exception like :
if (s_CurrentCallback != null)
                throw new InvalidOperationException("Cannot start a new permissions request before the current one finishes.");
happened.

**To Reproduce**
1.equesting permission with ARCorePermissionManager  by ARCorePermissionManager.RequestPermission(String, Action<String, Boolean>)
2.user click home button go to home screen and resume back to app
3.Permission requesting window is gone and No granted callback is called

**Expected behavior**
permission request window keeps when onpause and onresume. or a callback is called.

**Smartphone (please complete the following information):**
 - Device: Android ARCore
 - OS: Android 11
 - Unity version: 2019.4.29
 - ARFoundation version: 4.1.1

**Comment by DavidMohrhardt** [comment]
Could you file a bug for this: https://unity3d.com/unity/qa/bug-reporting.

**Comment by flankechen** [comment]
@DavidMohrhardt  done reporting it in unity. it should be easy to reproduce. thanks

**Comment by ankur-unity** [comment]
@flankechen - Can you post the bug id here?

**Comment by ankur-unity** [comment]
The bug has been reproduced. Use the following link to follow the progress on a fix:
https://issuetracker.unity3d.com/issues/arfoundation-camera-request-permission-window-is-not-shown-when-app-is-minimized-and-opened-again-on-android-device

**Comment by andyb-unity** [comment]
Added a new API to cancel permission request in Google ARCore XR Plug-in 5.0.0-pre.12: https://docs.unity3d.com/Packages/com.unity.xr.arcore@5.0/changelog/CHANGELOG.html#added-1
