### ISSUE TITLE
[Bug] AR Camera Manager - Auto Focus does not work on iPhone SE 2020 with iOS 15.x 

### ISSUE THREAD

**Issue by mrwellmann** [Unity-Technologies/arfoundation-samples#909]
**Describe the bug**
`AR Camera Manager` `Auto Focus` does not work on iPhone SE 2020 with iOS 15.x.
The camera will only focus once when activating auto focus or when enabling AR Core with active auto focus setting.
It does work as expected on iPhone Pro 12.

**To Reproduce**
I created a small repro case at https://github.com/firedrill-gmbh/arfoundation-samples/tree/ios15-autofocus-bug
1. Build App
2. Launch SimpleAR scene `switch focus` button will be _Green_ indicating that auto focus is on
3. On iPhone SE 2020 the focus will not change after the initial focusing. Best viewable if it the camera pointed to a near object and then moving to a far object.
4. The camera will refocus when disabling and enabling the auto focus by tapping twice on the switch focus button.

**Expected behavior**
The camera focuses automatically like on any other devices.

**Actual behavior**
The camera will only focus when activating auto focus or when enabling AR Core with active auto focus setting.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020 (MX9R2ZD/A)
 - OS: iOS 15.x
 - Unity version: 2020.3.11f1
 - ARFoundation version: 4.2.0

**Comment by tdmowrer** [comment]
Thank you for the repro project. This appears to be an issue in iOS 15.x.

It worked fine on my iPhone SE (A2275) running iOS 14.2 (18B92), then stopped working when I updated to iOS 15.1. It's also reproducible in [this Swift example from Apple](https://developer.apple.com/documentation/arkit/content_anchors/tracking_and_visualizing_planes).

Since this seems to be an Apple issue, could you report the issue using their feedback assistant? https://feedbackassistant.apple.com/

**Comment by mrwellmann** [comment]
Sent feedback as suggested https://feedbackassistant.apple.com/feedback/9762722

**Comment by mrwellmann** [comment]
![image](https://user-images.githubusercontent.com/247111/142176447-b6b3c6e3-5be9-4b8a-8651-49b127f4db75.png)

**Comment by whiteghost233** [comment]
In an Android environment,the camera will only focus once when activating auto focus or when enabling AR Core with active auto focus setting.
It does work as expected on iPhone Pro 14.
This problem persists when I use two different two Android devices.
I find when I close the screen and then open it,It's refocused. When the program hangs and then recuts to the foreground it also refocused.
I try to restart ARSession and other services，but failed to refocus.
Anyone know the reason or have idea?Please help me!
Thanks!

**Comment by whiteghost233** [comment]
> In an Android environment,the camera will only focus once when activating auto focus or when enabling AR Core with active auto focus setting. It does work as expected on iPhone Pro 14. This problem persists when I use two different two Android devices. I find when I close the screen and then open it,It's refocused. When the program hangs and then recuts to the foreground it also refocused. I try to restart ARSession and other services，but failed to refocus. Anyone know the reason or have idea?Please help me! Thanks!


see:[autofocus not working in pixel6 ](https://github.com/google-ar/arcore-android-sdk/issues/1312)
