### ISSUE TITLE
World map is not available in ios15[Bug]

### ISSUE THREAD

**Issue by figoche** [Unity-Technologies/arfoundation-samples#911]
**Describe the bug**
When the iPhone is upgraded to ios15, the world map cannot be used.   The ios14 device will crash when it loads world map scanned by ios15 device ,and when the ios15 device loads world map scanned by ios 14 device,it will not crash but not work at all.

**To Reproduce**
1、Modify the world map scene in the arfoundation-samples and add an interaction - place an object when clicking the screen.
2、Start the application with a device upgraded to ios15.
3、Save world map, reset world map, then click load world map.
4、We will find that the object does not appear in the location when it is saved.

 - Device: iPhone 12、iPhone 13 pro
 - OS: iOS15.02、iOS15.1.1
 - Unity version: 2020.3.22
 - ARFoundation version:4.2

**Comment by ankur-unity** [comment]
ARKit WorldMap are managed by Apple. You can file a bug report with Apple
https://developer.apple.com/bug-reporting/

**Comment by figoche** [comment]
Thank you very much for your reply. I have submitted bug feedback to apple. We try to package the arworld map example officially provided by apple, which works normally on ios15.
