### ISSUE TITLE
How to extract Face image from camera feed after face detection ? 

### ISSUE THREAD

**Issue by ti-hardikshah** [Unity-Technologies/arfoundation-samples#913]
1) I want to know the possibilities of extracting only face texture from the camera feed, is that possible using AR Foundation? 
For example, see that feature of Lens [studio](https://lensstudio.snapchat.com/templates/face/face-in-picture/) 

2) Background segmentation possible using AR foundation? For example 
https://lensstudio.snapchat.com/templates/face/segmentation/

**Comment by ankur-unity** [comment]
I will recommend asking this question on Unity's AR Forum.
https://forum.unity.com/forums/ar.161/
