### ISSUE TITLE
[Bug] Memory Not released when change scene with AR foundation

### ISSUE THREAD

**Issue by hardybbs123** [Unity-Technologies/arfoundation-samples#915]
**Unity bug report case number**
 
Case 1384307

**Describe the bug**
Memory Not released when change scene with AR foundation

**To Reproduce**

1 load sample Image tracking scene ,and load images for 100 pcs at runtime .
2 exit current scene and load empty scene , SceneManager.LoadScene("empty", LoadSceneMode.Single);
3 check memory with Profiler API at new scene .
systemMemoryRecorder = ProfilerRecorder.StartNew(ProfilerCategory.Memory, "System Used Memory");

**Expected behavior**
Load a empty Scene , memory should be released

**Actual behavior**
Load a empty Scene , memory not be released

**Smartphone (please complete the following information):**
 - Device: Redmi note 8 pro and iphone XR 
 - OS: Android and IOS
 - Unity 2020.3 LTS
 - ARFoundation version 4.21

**Comment by ankur-unity** [comment]
This is expected behavior. Starting with ARFoundation 4, the ARSession stays active on scene changes. If you want to free the memory, you will have to deinitialize the ARSession using `LoaderUtility.Deinitialize();`. Destroying the ARSession will only pause the underlying AR session and resumes it on another scene load.

More details at the following link:
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/migration-guide-3.html#runtime

**Comment by hasionerin** [comment]
> 
when i jump to a empty scene from AR scene ， i just do it like this :
SceneManager.LoadScene(0, LoadSceneMode.Single);
LoaderUtility.Deinitialize();

Then , i jump to AR scene from the empty scene. someting error like this:
"NotSupportedException: Update requires a configuration.
  at UnityEngine.XR.ARKit.ARKitSessionSubsystem+ARKitProvider.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.ARSubsystems.XRSessionSubsystem.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.ARFoundation.ARSession.Update () [0x00000] in <00000000000000000000000000000000>:0"

so i try to add " LoaderUtility.Initialize();" when AR scene loaded. but it don't work. the error disapper again .

**Comment by hasionerin** [comment]
> This is expected behavior. Starting with ARFoundation 4, the ARSession stays active on scene changes. If you want to free the memory, you will have to deinitialize the ARSession using `LoaderUtility.Deinitialize();`. Destroying the ARSession will only pause the underlying AR session and resumes it on another scene load.
> 
> More details at the following link: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/migration-guide-3.html#runtime


when i jump to a empty scene from AR scene ， i just do it like this :
SceneManager.LoadScene(0, LoadSceneMode.Single);
LoaderUtility.Deinitialize();

Then , i jump to AR scene from the empty scene. someting error like this:
"NotSupportedException: Update requires a configuration.
at UnityEngine.XR.ARKit.ARKitSessionSubsystem+ARKitProvider.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARSubsystems.XRSessionSubsystem.Update (UnityEngine.XR.ARSubsystems.XRSessionUpdateParams updateParams) [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.XR.ARFoundation.ARSession.Update () [0x00000] in <00000000000000000000000000000000>:0"

so i try to add " LoaderUtility.Initialize();" when AR scene loaded. but it don't work. the error disapper again .

**Comment by ankur-unity** [comment]
The AR scene is calling Update on XRSessionSubsystem but the subsystems are not initialized, hence it's not able to find an active AR configuration. Try initializing before loading the AR scene. In your case the process should be:
- Load Empty scene
- Deinitialize
...
- Initialize
- Load ARScene

**Comment by hasionerin** [comment]
> 



> The AR scene is calling Update on XRSessionSubsystem but the subsystems are not initialized, hence it's not able to find an active AR configuration. Try initializing before loading the AR scene. In your case the process should be:
> 
> * Load Empty scene
> * Deinitialize
>   ...
> * Initialize
> * Load ARScene

thanks for your quick reply !
i try to call Initialize on empty scene then jump to AR Scene.  it works,  the error  never disapper again.
but the memory not  reduced . i do empty scene -> AR scene -> empty scene -> AR scene . cycle sometimes,
then the  Memory explosion . 
somethings wrong i do?  waiting for your reply

**Comment by hasionerin** [comment]
solved !!! thanks

**Comment by ankur-unity** [comment]
@hasionerin - What was the issue and how did you solve it?

**Comment by thornebrandt** [comment]
@hasionerin what was the solution?

**Comment by hasionerin** [comment]
> @hasionerin - What was the issue and how did you solve it?
after listen the memeory,  , i found that the runtime library don't add too large memory, but my resources add. so i  optimize program flow and reduce my resources . memory additions also exist, but they are within our acceptable range.

**Comment by ankur-unity** [comment]
Thank you for the update. Closing the issue.

**Comment by VanIseghemThomas** [comment]
I can't figure this out. So from what I understand, once an AR session is launched, it retains somewhere. But how does this relate to scene loading and what is even the point? And why does it work for plane tracking without deinitializing but not for image tracking. Seems like broken behaviour/ a bug than a feature to me. I tried many things but keep encountering problems

My situation:

### Main menu (normal Unity scene with canvas and some buttons calling a simple scene loader)
- AR Scene 1 (image tracking)
- AR Scene 2 (plane tracking)
- Settings page
- About page


The following describes switching between the AR scene -> Main menu -> back to AR scene
### AR Scene 1 (image tracking)
- Image tracking only works like expected when **using** LoaderUtility Initialize and Deinitialize between scene loads.

### AR Scene 2 (plane tracking)
- Plane tracking only works like expected when **NOT using** LoaderUtility Initialize and Deinitialize between scene loads.

So what am I supposed to do? Why does plane tracking just work out of the box but image tracking not?
