### ISSUE TITLE
How to make an Automatic Measuring of Objects in Augmented Reality with ARFoundation?

### ISSUE THREAD

**Issue by romsondxr** [Unity-Technologies/arfoundation-samples#917]
How do I make an Automatic Measuring of Objects in Augmented Reality with ARFoundation?

similar to this video?

https://youtu.be/lp-MfrrmTR0

**Comment by ankur-unity** [comment]
The arfoundation-samples are a good place to start with ARFoundation. I will recommend asking this question on Unity's AR Forum.
https://forum.unity.com/forums/ar.161/
