### ISSUE TITLE
Multi-peer connectivity how-to

### ISSUE THREAD

**Issue by skynard** [Unity-Technologies/arfoundation-samples#918]
So we are creating a mobile app using Unity/ ARkit which will be deployed on iOS.  If we use ARkit's Multipeer collaboration framework, does that mean 2 phones can experience the same arworldmap at the same time?  In this case we have gameobjects with audio files so when triggered both phones would hear the same sound simultaneously?  Some of the documentation from apple states that we can determine a host.  I am assuming that means that one phone dedicated as the host can do the triggering?

**Comment by ankur-unity** [comment]
We have an ARKit specific sample in AR Foundation for this use case.
https://github.com/Unity-Technologies/arfoundation-samples#arcollaborationdata

**Comment by skynard** [comment]
👍. Thank you
