### ISSUE TITLE
UnityARSessionNativeInterface depreciated

### ISSUE THREAD

**Issue by skynard** [Unity-Technologies/arfoundation-samples#919]
We are building a demo project in Unity utilizing ARkit.  If we were using UnityARSessionNativeInterface in our AR Unity build and its been depreciated, and still want to utilize ARkit CollaborativeSession, how do we go about creating that build without it.

**Comment by DavidMohrhardt** [comment]
You may want to refer to the supported ARFoundation package and the relevant collaboration sample https://github.com/Unity-Technologies/arfoundation-samples#arcollaborationdata
