### ISSUE TITLE
[Bug] ARKit Body tracking neck joint(s) incorrectly reports rotation

### ISSUE THREAD

**Issue by genereddick** [Unity-Technologies/arfoundation-samples#920]
**Unity bug report case number**
Case 1386787

**Describe the bug**
When Body Tracking and using the code from the AR Foundation Samples project, it seems like at least one of the Neck joints is reporting an incorrect rotation. Looking to the side, left or right, instead causes a head tilt (as you can see in the attached image). This seems to be coming in specifically from the Neck4 joint. It is possible it is an accumulation of errors across all the neck joints.

My fix. to swap the x and y rotations sort of works, but feels extremely sketchy:

neck4.rotation = Quaternion.Euler(-neck4.y, neck4.x, neck4.z);

**To Reproduce**
1. Load the sample project.
2. Open body tracking.
3. Look left or right

**Expected behavior**
The robot head should rotate not tilt

**Actual behavior**
The robot head tilts

**Smartphone (please complete the following information):**
 - Device: iPhone and iPads
 - OS: iOS 15
 - Unity version: 2020.3.24f1 and previous 2020.3 branches (at least)
 - ARFoundation version 4.1.7
 - 
![IMG_0077](https://user-images.githubusercontent.com/1033793/145143187-43ad7ec1-26d4-49e2-9a3c-b681ad53f962.PNG)

**Comment by andyb-unity** [comment]
We were able to reproduce visibly inaccurate neck tracking in a variety of body poses using ARKit; however, these values come from ARKit itself, and ARFoundation makes no modifications to the joint transforms. Please direct further questions to Apple for this issue.
