### ISSUE TITLE
No active UnityEngine.XR.ARSubsystems.XRCameraSubsystem is available. ARSession.state = Unsupported on iOS

### ISSUE THREAD

**Issue by BlueSpiritbox** [Unity-Technologies/arfoundation-samples#923]
Hello,

We're running into some issues with ARFoundation on iOS. It shows the warning "No active UnityEngine.XR.ARSubsystems.XRCameraSubsystem is available" and it returns "Unsupported" when I log ARSession.state, and shows a black screen.

The weird thing is that we're running 2 Unity Cloud Builds for iOS; a dev build internal testing and a build for TestFlight. Both builds are using the exact same settings and code. AR works fine on the dev build, but for some reason it doesn't work for the TestFlight build.

We've been creating TestFlight builds with UCB for over a year now and never had any issues until a few weeks ago.

- Unity 2020.1.17
- ARFoundation 4.1.7
- ARKit 4.1.7
- ARKit is enabled in the XR Plug-in Management settings
- Tested on iPhone 10, 11, 13

We've tried updating Unity to 2020.3.23 and updating ARFoundation and ARKit to 4.2.1, but no luck either.

Any ideas what's causing this?

Thanks!

**Comment by KirillKuzyk** [comment]
https://forum.unity.com/threads/no-active-unityengine-xr-arsubsystems-xrcamerasubsystem-is-available-arsession-state-unsupported.1211631/

**Comment by ankur-unity** [comment]
Closing because it's been answered in the forum post.
