### ISSUE TITLE
trackingState always on "None"

### ISSUE THREAD

**Issue by Banzai99** [Unity-Technologies/arfoundation-samples#924]
Hi,

I would first like to mention that I'm pretty new to Unity and AR, so I might have missed something when reading docs.
I'm working on a project where I'm trying to refill a bar everytime a picture appears on camera.
I was planning on using the trackingState variable and checking if it is on limited or tracking in order to call the function that fills the bar.
However it seems that everytime I manage to track and update my picture, the trackingState always stays on "None" for some obscure reason...

``` C#
public void OnChanged(ARTrackedImagesChangedEventArgs eventArgs)
{
    foreach (var trackedImage in eventArgs.added)
    {
        Debug.Log(trackedImage.trackingState);
        if (fuel.GetComponent<Slider>().value == 0)
        {
            fuel.GetComponent<Fuel>().SetFuel(100);
        }
    }

    foreach (var trackedImage in eventArgs.updated)
    {
        if (trackedImage.trackingState == UnityEngine.XR.ARSubsystems.TrackingState.Tracking)
        {
            if (fuel.GetComponent<Slider>().value == 0)
            {
                fuel.GetComponent<Fuel>().SetFuel(100);
            }
        }
        Debug.Log("Updated");
        Debug.Log(trackedImage.trackingState);
    }
}
```
Here's what I am doing, the line that is printing the state of the tracked image always prints "None" when it should be printing "Tracking" or "Limited " and I have no idea why.

Edit : After thinking about it a bit, it seems that using the fact that the "OnChange" method is called only when there is an update is enough for what I want to do, but it still seems weird to me that the trackingState never goes to "Tracking" when it should.

Thanks for your help !

**Comment by DavidMohrhardt** [comment]
Can you try the sample scene detailed here: https://github.com/Unity-Technologies/arfoundation-samples#imagetracking

If the sample also displays an issue where the updated trackables are never reporting as tracked, please file a bug and post the bug number here: https://unity3d.com/unity/qa/bug-reporting

**Comment by Banzai99** [comment]
I just tested the BasicImageTracking sample scene and it does seem to work normally.
By normally I mean that the meta data shown on the picture is "limited" or "tracking" when it should be so the problem is probably in my code.
