### ISSUE TITLE
[ARKit & ARCore] ARKit recording and playback support

### ISSUE THREAD

**Issue by Phantomxm2021** [Unity-Technologies/arfoundation-samples#929]
I found that ARCore recording and playback is supported, but I did not find the ARKit recording and playback API on Unity ARFoundation

Here is ARKit recording and playback api:
https://developer.apple.com/documentation/arkit/arsession/recording_and_replaying_ar_session_data

**Comment by tdmowrer** [comment]
ARKit does not have an API for recording and playback. 

As described in the article you linked, it is possible to record a session using Reality Composer and then play it back by specifying the recorded session in Xcode. However, there is no runtime API, and you do not need to make changes to your app to take advantage of this feature.
