### ISSUE TITLE
Multiplayer AR is not Working properly please help for god sake

### ISSUE THREAD

**Issue by miscrealitystudios** [Unity-Technologies/arfoundation-samples#93]
Hello Sir,
I created a streetfighter multiplayer game using photon in AR Foundation. I tested the app on both ios and android device. Everything is working properly but the only problem is that the players are not spawning correctly. one player that is spawning is a little above the plane.
I used Photon Unit Networking as a server.
 Here's the video that will give you the exact look of the above problem. Please do watch it! @tdmowrer 
https://youtu.be/twJAkQYm5tk

**Comment by tdmowrer** [comment]
Sorry, I can't diagnose a complex problem in your application by watching a video. Let's start with the multi-user aspect -- how are you synchronizing positions across devices? The only support for this in ARFoundation is via the ARKit-specific `ARWorldMap`.

**Comment by tdmowrer** [comment]
There's now a [sample](https://github.com/Unity-Technologies/arfoundation-samples/tree/master/Assets/Scenes/ARCollaborationData) demonstrating [session collaboration](https://developer.apple.com/documentation/arkit/arcollaborationdata) introduced in iOS 13.

**Comment by orrburgel** [comment]
the sample is not working @tdmowrer

**Comment by tdmowrer** [comment]
Can you be more specific. What does "not working" mean?

**Comment by orrburgel** [comment]
@tdmowrer you attached a sample on your last comment, it's not working, you can't access the link

**Comment by tdmowrer** [comment]
Try this instead: https://github.com/Unity-Technologies/arfoundation-samples#arcollaborationdata
