### ISSUE TITLE
WorldToScreenPoint using XRCpuImage from ARCameraManager

### ISSUE THREAD

**Issue by varunbachalli** [Unity-Technologies/arfoundation-samples#930]
Hello,

I have been trying for a while to reproject the position of a game object onto the Texture2D that can be retrieved from XRCpuImage  in ARCameraManager.TryAcquireLatestCpuImage. 

using Camera.WorldToScreenPoint(Vector3 position); Doesn't work because this projects the point onto the image that's rendered on the screen and not the Image that is acquired from ARCameraManager.TryAcquireLatestCpuImage. 

I am aware that the image that is rendered on the screen is scaled rotated and offset using the displayMatrix. 

So I tried implementing the CameraProjection on my own. But it doesn't seem to be working.

The function that I used to reproject the points is as follows 

```

    [SerializeField]
    private ARCameraManager m_CameraManager;

    [SerializeField]
    private Camera ARCamera;

  public Vector2 GetPixelPosition(Matrix4x4 projectionMatrix,
                                    Matrix4x4 displayMatrix,
                                    Matrix4x4 viewMatrix,
                                    float pixelWidth,
                                    float pixelHeight,
                                    Vector3 position)
    {
        Vector4 pos = new Vector4(position.x, position.y, position.z, 1);

        Matrix4x4 transformation = displayMatrix * projectionMatrix * viewMatrix;

        pos = transformation * pos;

        pos /= pos.w;

        pos.x = (pos.x + 1.0f) * 0.5f;
        pos.y = (pos.y + 1.0f) * 0.5f;

        pos.x *= pixelWidth;
        pos.y *= pixelHeight;

        return new Vector2(pos.x, pos.y);
    }

    GameObject testObject;
    unsafe void UpdateCameraImage_(ARCameraFrameEventArgs eventArgs)
    {

        if (!m_CameraManager.TryAcquireLatestCpuImage(out XRCpuImage image))
        {
            return;
        }


        Vector2 pixelPosition = GetPixelPosition((Matrix4x4)eventArgs.projectionMatrix,
                                                (Matrix4x4)eventArgs.displayMatrix,
                                                ARCamera.worldToCameraMatrix,
                                                image.width,
                                                image.height,
                                                testObject.transform.position
                                                );
    }
```

I then go on to save the the XRCpuImage image into a png and also the pixelPosition. But the pixel Position isn't what it's meant to be.

The goal for this project is to later get the pixel coordinates of the 4 corners of a plane AR Object and extract the image from it. 

Can someone help me correct the code? Or suggest an alternative path?

**Comment by AlanWuJinliang** [comment]
i also want to know this .

**Comment by AMMAS1** [comment]
Any updates on this? were you able to get the correct positions?

**Comment by FrighteningFunction** [comment]
Any updates on this? I would also like to know this.
