### ISSUE TITLE
[Bug] About ARCore Facemesh 

### ISSUE THREAD

**Issue by Phantomxm2021** [Unity-Technologies/arfoundation-samples#931]
**Describe the bug**
When using the ARCore Facemesh algorithm, `facesChanged` no longer runs when the face is lost.

**Comment by todds-unity** [comment]
When the tracked face leaves the camera frame, you will get one last face change event where the ARFace.trackingState changes to Limited. Subsequently, the face change event will not fire again until the face enters the camera frame again.
