### ISSUE TITLE
3D Body Tracking for Humanoid Rigs Sample Request

### ISSUE THREAD

**Issue by korzen** [Unity-Technologies/arfoundation-samples#933]
Many people report problems with a non-standard character rig, which Apple uses for their 3D body tracking API and which was adapted by Unity in sample scene. 

Would it be possible to provide us with a sample scene or script, which demonstrates a proper use of  Humanoid Avatars with ARKits' 3D Body Tracking?

This issue still wasn't properly solved by anyone yet. The only working solution is to reskin the existing models to rig provided by Apple in external 3D software such as Blender or Maya. This is not always possible though. For example, in our fashion app we need to load avatars .fbx on the runtime, which are provided online by external providers. They work great with Humanoid rig for animation but to use them in AR they would require runtime reskinnning, which is far from ideal.

**Comment by todds-unity** [comment]
We don't have a sample, but you can look into animation retargeting.
https://docs.unity3d.com/Manual/Retargeting.html
