### ISSUE TITLE
Detect when a 3D human body being tracked

### ISSUE THREAD

**Issue by jonathanahern** [Unity-Technologies/arfoundation-samples#934]
Hi,

I'm trying to find a way to detect when a human body is being tracked, and when it can't find a body to be tracked whether because it's off screen or can't detect it. I thought about just checking if it has been awhile since it has been "updated" last, but if the human and camera operator is not moving then this doesn't work. 

Thanks!

**Comment by jonathanahern** [comment]
I've decided to check the trackingState variable in the update. If I get 60 consecutive Nones, I consider it not detected. If there's a better way I'm all ears, but I'll close this for now.

**Comment by tdmowrer** [comment]
There's also an event that fires every time the state _changes_, which may be useful.
