### ISSUE TITLE
Changing camera aspect ratio

### ISSUE THREAD

**Issue by xBambusekD** [Unity-Technologies/arfoundation-samples#935]
Hi, is there some possibility to change the camera's aspect ratio? Current AR Camera Background stretches the camera image to fullscreen, resulting in cropping it on its sides. Most of the smartphones support different aspect ratios of their cameras, e.g.:

![aspect_ratio](https://user-images.githubusercontent.com/26470087/150812866-e99e0ec4-5faa-4f30-a52a-47f9f78e92c7.png)
 [1] Left - aspect ratio of 3:4
 [2] Right - fullscreen aspect ratio of 9:19.5

For my application, I need to have the smartphone work in a portrait mode, while seeing most of the non-cropped camera image (ideally in the aspect ratio of 3:4). Is there any possibility to use different aspect ratios in the AR Foundation than the fullscreen one? 

Thanks!

**Comment by todds-unity** [comment]
You can query a device's available camera configurations using the ARCamera.GetConfigurations() API.
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_GetConfigurations_Allocator_

And then set the ARCamera.currentConfiguration to change the camera configuration.
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_currentConfiguration

Some of the available camera configurations may have alternate aspect ratios, but only the configurations obtained from the GetConfigurations() API are valid on that device.

**Comment by xBambusekD** [comment]
That didn't help at all. Using this [snippet of code](https://github.com/Unity-Technologies/arfoundation-samples/blob/582a8f722e134155560e8b04acf56327e66da2a7/Assets/Scripts/CameraConfigController.cs#L84), I only got three possible configurations on my Xiaomi Mi Mix 3: 
640x480 at 30 Hz
1280x720 at 30 Hz
1920x1080 at 30 Hz

When I tried to set them one by one to the ARCamera.currentConfiguration, they all were stretched to the fullscreen and no difference in aspect ratio nor camera image dimensions was visible. 

Is there another way to achieve the use case [1]? (To see the whole camera image without zooming and cropping on sides?)

**Comment by AliSaidov98** [comment]
> That didn't help at all. Using some variant of [this code](https://github.com/Unity-Technologies/arfoundation-samples/blob/582a8f722e134155560e8b04acf56327e66da2a7/Assets/Scripts/CameraConfigController.cs#L84), I only got three possible configurations on my Xiaomi Mi Mix 3: 640x480 at 30 Hz 1280x720 at 30 Hz 1920x1080 at 30 Hz
> 
> When I tried to set them one by one to the ARCamera.currentConfiguration, they all were stretched to the fullscreen and no difference in aspect ratio nor camera image dimensions was visible.
> 
> Is there another way to achieve the use case [1]? (To see the whole camera image without zooming and cropping on sides?)

Hi, Have you solved that?
