### ISSUE TITLE
[Bug] Real objects from camera feed have strange white edges/borders

### ISSUE THREAD

**Issue by AytoMaximo** [Unity-Technologies/arfoundation-samples#936]
We have a strange bug on some specific devices and it's NOT depends on its model. Look at picture below please. Has anybody ever faced such an issue? I can't find any information or screenshots in Google with such camera feed effect.

![image](https://user-images.githubusercontent.com/14392087/151339152-80487727-d2bd-4c6d-9d7c-fb6819240bf7.png)

**Comment by todds-unity** [comment]
Please file a bug.
https://unity3d.com/unity/qa/bug-reporting
