### ISSUE TITLE
Link to CollaborativeSession.cs in the README is broken

### ISSUE THREAD

**Issue by dgileadi** [Unity-Technologies/arfoundation-samples#937]
Scenes/ARCollaborationData was moved under the ARKit subfolder but the link to CollaborativeSession.cs [under README.md](https://github.com/Unity-Technologies/arfoundation-samples#arcollaborationdata) wasn't updated to match so it gives a 404. The link needs an `/ARKit` inserted.

**Comment by ankur-unity** [comment]
Thanks, @dgileadi. The README.md has been updated.
