### ISSUE TITLE
AR Scene Switches crash AR(Black screen)

### ISSUE THREAD

**Issue by m3rt32** [Unity-Technologies/arfoundation-samples#94]
When we are using AR Foundation, while trying to switch between AR Scenes, we see black screen in 2nd,3rd... scenes. AR only works in first scene( in terms of order, not a scene specific issue). So when we look through logs, it appears to be arsubsystems crash when we change scenes on iOS only. It works on ARCore(Android) regardless. We think sessions are not restarted between scene switches. We need a fix.

**Comment by tdmowrer** [comment]
> when we look through logs, it appears to be arsubsystems crash when we change scenes on iOS only
Have you got a callstack for the crash?

**Comment by m3rt32** [comment]
Yeah,we got a script called "ARObjectManager" and it subscribes to system state and camera subsystem this is how it crashes:
`(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
default	13:11:31.819171 +0000	Kwest	Uploading Crash Report
default	13:11:31.819687 +0000	Kwest	NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.MonoBehaviour.StopCoroutine (System.Collections.IEnumerator routine) [0x00000] in <00000000000000000000000000000000>:0 
  at Kwest.AR.ARObjectManager.ARSubsystemManager_systemStateChanged (UnityEngine.XR.ARFoundation.ARSystemStateChangedEventArgs obj) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.ARFoundation.ARSession+<Initialize>d__11.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.GameObject.AddComponent[T] () [0x00000] in <00000000000000000000000000000000>:0 
`

**Comment by tdmowrer** [comment]
Looks like you are calling `StopCoroutine(null);` in
```
Kwest.AR.ARObjectManager.ARSubsystemManager_systemStateChanged
```

What does that do?

**Comment by m3rt32** [comment]
We are starting a coroutine which is responsible from waiting until arsystemstate turns to tracking to be able to spawn objects.
This is that method:
![image](https://user-images.githubusercontent.com/3215742/52005634-3c52ae00-24db-11e9-8531-32ab92bb000c.png)

And in that coroutine, we are counting for a while in case off ar is not working we display that error to screen for users.

![image](https://user-images.githubusercontent.com/3215742/52005719-6906c580-24db-11e9-89d5-18c6a338e2df.png)

**Comment by m3rt32** [comment]
I think problem not happens in this particular part. We've tested in a simpler project and we had the same problem regardless without having a specific script.

**Comment by m3rt32** [comment]
@tdmowrer  Did you guys reproduce it as well ?

**Comment by BikutaAnkuta** [comment]
@m3rt32 @tdmowrer I'm having this problem with my project right now as well. I put LoadScene in OnApplicationFocus and have the same results. Seems to happen in the sample scenes as well.

**Comment by m3rt32** [comment]
Well the thing is, when I updated my Unity version, this issue gone away(at least I couldn't address it again,yet). Which version of Unity are you using @BikutaAnkuta ?

**Comment by BikutaAnkuta** [comment]
I'm currently on 2018.3.0f2. I haven't tried to replicate the issue on another copy of unity yet, that may be something to check.

**Comment by m3rt32** [comment]
@BikutaAnkuta Yes, I think this is the problem. Try latest version which is right now 2018.3.12 , I don't know exactly but this issue seems to be fixed. But I think you should upgrade an give it a shot to confirm.

**Comment by BikutaAnkuta** [comment]
@m3rt32 Seems like upgrading to 2018.3.7 fixes the issue. I haven't tried anything between 3.0 and 3.7 to see if its fixed any sooner. Thanks for providing a solution!

**Comment by samuelmorais** [comment]
I've experienced this problem with Unity 2019.1.
To make the problem reproduced, I've added a button "Reload" the "SimpleAR" sample scene that just load the same "SimpleAR" scene. After reloading, the screen becomes black.

**Comment by d3m3tr105** [comment]
Same here. Seems issue was not solved  Unity 2019.1.

**Comment by karstenvoigt81** [comment]
Same here. Seems issue was not solved Unity 2019.2

**Comment by silverua** [comment]
Experiencing the same issue with 2019.2. Tried to resolve by resetting ARSession or destroying/re-instantiating the ARSession object in Start(). Did not work.

**Comment by makled** [comment]
I had a temporary fix by making the gameobject with the ARSession a singleton that does not destroy on load. It fixed the issue, however it is a bit unstable. Using Unity 2019.2.0f1.
`DontDestroyOnLoad(this);`

**Comment by ehsanwwe** [comment]
i test every methods at this page
is there any other way to fixt this bug

**Comment by makled** [comment]
@ehsanwwe
I'd suggest trying to always keep one ARsession and one ARsession origin through out the entire game. As in the very first scene has the ARsession and ARsession origin in a game object. Then move this game object with you in between scenes (very important not to put other ARsession and ARsession origins in the "next" scene.)

**Comment by WangChaolun** [comment]
I have same problem [#340](https://github.com/Unity-Technologies/arfoundation-samples/issues/340)
any idea?

**Comment by mavc18** [comment]
same problem here in 2020 may :S

**Comment by tdmowrer** [comment]
@mavc18 there are several issues discussed here, and there are correctly no known issues with scene switching; could you describe your issue in more detail?

**Comment by sael-you** [comment]
@tdmowrer  i got unity 2020.2 and and get a black screen after switching between scenes, the project is small i start in a scene with AR camera Background enabled with material and "facing direction manager"(the one you used for LightEstimation sample) activated (everything works fine), then press a button i switch to another scene without ar camera background ( it works so far), then if press the button again to switch back the scene with the background enabled all i see is black with my object and even the Script "Facing Direction manager" doesn't work correctly anymore.

it would be amazing if i could get some help (y)
