### ISSUE TITLE
Access to frontal camera feed, when running AR Foundation on rear camera

### ISSUE THREAD

**Issue by MarkiianAtUCU** [Unity-Technologies/arfoundation-samples#940]
Is it possible to get a frontal camera feed (without any AR features, only video feed), while at the same time running AR Foundation on the rear camera? 

I am using ARKit (ARKit 4.1.9 plugin version) and looks like it overrides my access to the frontal camera via WebCamTexture, when AR Foundation initializes, even if I am not using any features which require a frontal camera

**Comment by ankur-unity** [comment]
Neither ARKit nor ARCore support this use case.
