### ISSUE TITLE
What are the attributes of an Ideal Image Target?

### ISSUE THREAD

**Issue by Sami-AlEsh** [Unity-Technologies/arfoundation-samples#943]
I want to know the principles that makes an image better for detection in ARFoundation package.

Also, I have these questions :
1- Does image size matters ? does 512x512 image is as good as 1024x1024 image ?
2- Does colors matters ? does it turned to gray scale to be used for detection ?
3- Which is best for detection square or rectangle images ? or it doesn't matter!
4- (according to a comment in a thread I read before) Why the QR codes images are not recommended ?!

Thanks in advance!

**Comment by ankur-unity** [comment]
You can find the recommended guidelines here:
https://developers.google.com/ar/develop/augmented-images#best_practices
