### ISSUE TITLE
ARFoundation Fuzzy recognition

### ISSUE THREAD

**Issue by hasionerin** [Unity-Technologies/arfoundation-samples#944]
Hello,
I have a question about image tracking in Ar Foundation.
Is there a way to get some kind of "threshold" for the recognized image? For example, I have 2 different / similar looking reference images and I would like to see how many percent the respective image applies to the reference.
At the moment I can't find a way to do this, except for the Enum: Tracked, Limited and None...
Is there no exact float value or similar?

Many thanks in advance and greetings

**Comment by ankur-unity** [comment]
Neither ARCore nor ARKit provide this information.

**Comment by hasionerin** [comment]
> Neither ARCore nor ARKit provide this information.

thanks for your respose !
i take a photo , use this photo as marker , then use arfoundation to track this , when i track the photo ,it tracked quick,but when i track the real world , on ios devices, it tracked quick too , but on android devices , it tracked hard .  so i think is there exits some api to reduce the tracked percent . or is there a way to quickly identify real scenes . thanks !
