### ISSUE TITLE
Publishing an AR face tracking app on Google store, no face tracked

### ISSUE THREAD

**Issue by eisenWu** [Unity-Technologies/arfoundation-samples#946]
I made an app with ar face tracking, it works fine with local build, but when I publish it to the Google store.

1 use customs keystore -> and check Release under Minify the app will crash after built.
2 use customs keysore -> and uncheck Release under Minify the app works but the ar face tracking not work
3 no keystore -> everything works fine

Any help would be thankful !!!

**Comment by andyb-unity** [comment]
Please file a bug: https://unity3d.com/unity/qa/bug-reporting
