### ISSUE TITLE
[Bug] iOS Cloud Builds not working? XR.ARSubsystems warning & Black Camera Feed

### ISSUE THREAD

**Issue by BlueSpiritbox** [Unity-Technologies/arfoundation-samples#949]
AR Foundation in iOS builds doesn't work anymore using Unity Cloud Build. We're getting a bunch of XR.ARSubsystems warnings and the camera feed is black. Logging ARSession.state returns "Unsupported".

![IMG_0004](https://user-images.githubusercontent.com/2314852/156558364-6ae26343-52cc-48a3-81cf-8137d84b0c67.PNG)

AR does work when we make local builds.

We tested cloud builds using:
- Unity 2020.3.23 and 2020.1.17
- ARFoundation / AR Subsystems / ARKit 4.19 and 4.2.2
- UCB Xcode 13.2.1 and 13.0.0
- Force defined "UNITY_XR_ARKIT_LOADER_ENABLED" symbol in UCB config
- Tested a blank project with ARFoundation Samples, but getting the same issues
- Tested on several ARKit compatible iOS devices
- We are not using URP

Any ideas?

**Comment by todds-unity** [comment]
Please file a bug.
https://unity3d.com/unity/qa/bug-reporting

**Comment by DTsoukalos** [comment]
I have the same issue! 

When I use cloud build for my iOS AR app the camera not working. It doesn't even appear the camera permissions.
When I make the build with my Mac everything works well.

Unity 2021.3.27f1 
ARFoundation/ARKit 4.2.8

**Comment by mnbnthdegree** [comment]
Worked for me with xcode 14
