### ISSUE TITLE
Is MakeContentAppearAt removed on ARFoundation 5.0

### ISSUE THREAD

**Issue by Phantomxm2021** [Unity-Technologies/arfoundation-samples#950]
I'm upgrade from 4.2 version of ARFoundation to 5.0, but I can not found `MakeContentAppearAt` API.
Has it been removed?

**Comment by andyb-unity** [comment]
MakeContentAppearAt has been removed in AR Foundation 5, but in a subsequent patch we'll update our Migration Guide with better assistance for users upgrading a project from version 4.x

**Comment by Phantomxm2021** [comment]
> MakeContentAppearAt has been removed in AR Foundation 5, but in a subsequent patch we'll update our Migration Guide with better assistance for users upgrading a project from version 4.x

Thank you for your reply.

**Comment by andrewio** [comment]
> MakeContentAppearAt has been removed in AR Foundation 5, but in a subsequent patch we'll update our Migration Guide with better assistance for users upgrading a project from version 4.x

I can't find any notice [here](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/migration-guide-5-x.html) . When you plan to update it?

**Comment by ankur-unity** [comment]
The docs will be updated with the release of the next 5.0.0 pre-release version update. It's under QA right now. We will update this thread when it's out and the docs are updated.

**Comment by ankur-unity** [comment]
We have updated our docs to provide a migration guide for this API.

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/migration-guide-5-x.html#removal-of-arsessionoriginmakecontentappearathttpsdocsunity3dcompackagescomunityxrarfoundation42apiunityenginexrarfoundationarsessionoriginhtmlunityenginexrarfoundationarsessionoriginmakecontentappearatunityenginetransformunityenginequaternion

**Comment by ankur-unity** [comment]
Closing this as resolved. Feel free to re-open if there are more questions.

**Comment by Tommy-Elliott** [comment]
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/version-history/migration-guide-5-x.html#removal-of-arsessionoriginmakecontentappearathttpsdocsunity3dcompackagescomunityxrarfoundation42apiunityenginexrarfoundationarsessionoriginhtmlunityenginexrarfoundationarsessionoriginmakecontentappearatunityenginetransformunityenginequaternion

The updated link (added `/version-history` in the url).

**Comment by makakaorg** [comment]
File missed. Link is not working: https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/XROriginExtensions.cs

Please provide the file.

**Comment by ulrikdamm** [comment]
This is the correct link (working as of November 2023): [https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/Runtime/XROriginExtensions.cs](https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/Runtime/XROriginExtensions.cs)

**Comment by Han-star01-ux** [comment]
> We have updated our docs to provide a migration guide for this API.
> 
> https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/migration-guide-5-x.html#removal-of-arsessionoriginmakecontentappearathttpsdocsunity3dcompackagescomunityxrarfoundation42apiunityenginexrarfoundationarsessionoriginhtmlunityenginexrarfoundationarsessionoriginmakecontentappearatunityenginetransformunityenginequaternion

**Comment by andyb-unity** [comment]
Here's the migration guide link: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/version-history/migration-guide-5-x.html#removal-of-arsessionoriginmakecontentappearat

It basically just points you to our provided extension methods, which @ulrikdamm correctly linked here in 2023: https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/Runtime/XROriginExtensions.cs
