### ISSUE TITLE
Can not load  ARReferenceObjecet from assetbundle

### ISSUE THREAD

**Issue by Phantomxm2021** [Unity-Technologies/arfoundation-samples#951]
ARFoundation 5.0.0-pre.8

How to load ARReferenceObjecet from assetbundle?

I try https://github.com/Unity-Technologies/arfoundation-samples/issues/890#issuecomment-947395116, but not working!

This is error log:
```log
ARReferenceObject initWithArchiveURL failed: File IO failed.
```

```c#
//referenceObjectLibrary load from assetbundle
arTrackedObjectManager.referenceLibrary = referenceObjectLibrary;
```
<img width="537" alt="image" src="https://user-images.githubusercontent.com/82647748/157589020-2c57e683-c42a-4d8e-8321-96b98721e89c.png">

**Comment by DavidMohrhardt** [comment]
Please log a bug: https://unity3d.com/unity/qa/bug-reporting
