### ISSUE TITLE
How to build cross-platform AR experience for hololens2 without MRTK(only ARFoundation) 

### ISSUE THREAD

**Issue by Phantomxm2021** [Unity-Technologies/arfoundation-samples#952]
I can not found any tutorial for it. Or ARFoundation just support handle AR?

**Comment by ankur-unity** [comment]
AR Foundation does not implement its own SLAM. You will need Microsoft's OpenXR plugin along with AR Foundation. This might help:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/xr-project-setup?tabs=openxr
