### ISSUE TITLE
[Bug] ARKit ARWorldMap save and restore makes app crash

### ISSUE THREAD

**Issue by wangyugod** [Unity-Technologies/arfoundation-samples#953]
Hi there,
I have a function that saves and restores ARWorldMap in my App, my operation flow:
1. open my app and scan around
2. save ARWorldMap to ipad local storage
3. load to restore ARWorldMap
After repeat step 2 and 3 several times, my App crashed. I thought it was my code issue but cannot find any clue, actually my code is copied from ARFoundationSample. Then I downloaded official ARWorldMap Pesistent demo from https://developer.apple.com/documentation/arkit/data_management/saving_and_loading_world_data, repeat the operation as above, it also crashed. My iPad version is iPad Pro 15.3.1, my xcode version is 13.2.1, and the error log said dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection.dylib blahblah, please check it from attachment. Any help is appreciated.
![error-min](https://user-images.githubusercontent.com/449121/159050271-7ee6287b-aafb-463e-af6d-08df8c296a66.png)
![error](https://user-images.githubusercontent.com/449121/159050393-d419c935-7b4f-4846-ae76-5ae8927c6636.png)

**Comment by wangyugod** [comment]
Update for more information, I enabled plane visualization for detected plane, when I save and load the ARWorldMap, the planes became denser and denser, and app became much slower.

**Comment by tdmowrer** [comment]
> Then I downloaded official ARWorldMap Pesistent demo from https://developer.apple.com/documentation/arkit/data_management/saving_and_loading_world_data, repeat the operation as above, it also crashed.

If you are able to reproduce this with Apple's sample, then it isn't a Unity-related bug and it's unlikely they will be able to help. I recommend that you report this to Apple here:

https://developer.apple.com/bug-reporting/
