### ISSUE TITLE
[Bug] Overlay Camera (URP) does not align with AR Camera

### ISSUE THREAD

**Issue by D33pTh0ught** [Unity-Technologies/arfoundation-samples#954]
**Unity bug report case number**
Case 1412375

**Describe the bug**
When performing camera stacking on the ARCamera, the Overlay Camera does not align with the ARCamera.

**To Reproduce**
1. In your URP Unity Project add an Overlay Camera as child of your AR Camera.
2. Write a script that applies the FoV of the ARCamera to the Overlay Camera.
3. Observe that even when both Cameras render the same objects, they do not align. 

**Expected behavior**
It should be possible to align the Overlay Camera with the AR Camera the same way it does when not using ARFoundation

**Actual behavior**
It is not possible to align the view rect of an Overlay Camera to a Camera controlled by ARFoundation

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: Android 12
 - Unity 2021.2.12f1
 - ARFoundation 4.2.2

**Comment by D33pTh0ught** [comment]
Ah of course thanks, that worked!

**Comment by ROBYER1** [comment]
Is there an example of the working script for this?
