### ISSUE TITLE
Screen flickers and strobes on launch

### ISSUE THREAD

**Issue by UnityEQ** [Unity-Technologies/arfoundation-samples#955]
Using Unity 2021.2.15f1 (same problem in 2021.2.17) on iOS with a fresh install of arfoundation-samples in the "HumanBodyTracking3d" scene. (I did add the AR Background Render feature to the URP asset.)

When built, this is what I see on my iOS screen. Any advice?

https://youtu.be/fekf4q4VPPU

**Comment by ankur-unity** [comment]
Do you mind filing a bug and then posting the bug number here:
https://unity3d.com/unity/qa/bug-reporting

**Comment by UnityEQ** [comment]
> Do you mind filing a bug and then posting the bug number here: https://unity3d.com/unity/qa/bug-reporting

Case 1415835, thx~

**Comment by andyb-unity** [comment]
Closed due to lack of activity
