### ISSUE TITLE
if there are several people in camera，how arfoundation  determine which one to track with?

### ISSUE THREAD

**Issue by Leonbupt** [Unity-Technologies/arfoundation-samples#956]
How do I...

**Comment by DavidMohrhardt** [comment]
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/index.html#platform-support

Apple ARKit is the only supporter of Human Body Tracking currently. As for how the selection is made, the underlying platform API (Apple ARKit) is the one that makes the decision on which body to track which is an opaque decision to AR Foundation.

If you want broaden your understanding, more details are provided in the following WWDC Conference Discussion:
https://developer.apple.com/videos/play/wwdc2019/607

**Comment by Leonbupt** [comment]
thank you for the answer
