### ISSUE TITLE
[Bug] Ambient-light estimation: Wrong parameter assigned?

### ISSUE THREAD

**Issue by seyfeb** [Unity-Technologies/arfoundation-samples#957]
**Describe the bug**
In the ARFoundation HDR ambient-light estimation demo scene you assign [here](https://github.com/Unity-Technologies/arfoundation-samples/blob/31fe4cb91b6fa8e68d562623c669bfafae3bc65f/Assets/Scripts/HDRLightEstimation.cs#L179) the intensity

```
            if (args.lightEstimation.mainLightIntensityLumens.HasValue)
            {
                mainLightIntensityLumens = args.lightEstimation.mainLightIntensityLumens;
                m_Light.intensity = args.lightEstimation.averageMainLightBrightness.Value;
            }
```

You are checking the `args.lightEstimation.mainLightIntensityLumens` value but are assigning the `args.lightEstimation.averageMainLightBrightness` value. Is this a typo or the correct way to do this (and if so, why?)

**Comment by seyfeb** [comment]
Not stale

**Comment by andyb-unity** [comment]
Hi @seyfeb -- as you have probably noticed, our team is not structured to respond to GitHub issues in a timely manner. I can tell you that assigning `mainLightIntensityLumens` to a Light's `intensity` value would be clearly incorrect. `intensity` is measured on a scale of 0 to 8, as noted here: https://docs.unity3d.com/ScriptReference/Light-intensity.html

Lumens for real-world directional lights are measured in the thousands. If you plugged a value measured in lumens into a field expecting intensity on a scale of 0-8, you would likely get very poor results.

Is `averageMainLightBrightness.Value` strictly correct? I think this ultimately depends on your use case, but it's an acceptable value for us to use in our sample project. Hope that helps.

I'm trying to close out these old issues. Feel free to re-open this one if you have further questions.
