### ISSUE TITLE
Errors when project is opened!

### ISSUE THREAD

**Issue by nsmith1024** [Unity-Technologies/arfoundation-samples#962]
Using unity version 2020.3.32f

I get the following errors when i simply open your project in the editor, can you please help!

Library\PackageCache\com.unity.xr.arfoundation@5.0.0-pre.8\Runtime\ARSubsystems\HelpUrls.cs(8,30): error CS0509: 'HelpURLAttribute': cannot derive from sealed type 'HelpURLAttribute'

Library\PackageCache\com.unity.xr.arfoundation@5.0.0-pre.8\Runtime\ARSubsystems\ImageTrackingSubsystem\XRReferenceImageLibrary.cs(23,6): error CS0616: 'HelpURLAttribute' is not an attribute class

Library\PackageCache\com.unity.xr.arfoundation@5.0.0-pre.8\Runtime\ARSubsystems\ObjectTrackingSubsystem\XRReferenceObjectEntry.cs(20,6): error CS0616: 'HelpURLAttribute' is not an attribute class

**Comment by tdmowrer** [comment]
AR Foundation 5.0 requires Unity 2021.2+. Try upgrading to 2021.2 or later.
