### ISSUE TITLE
Hoeto get the world camera position ?

### ISSUE THREAD

**Issue by alexs7** [Unity-Technologies/arfoundation-samples#964]
How do I get the world camera position ?

Is it as simple as getting the position and rotation of the camera game object that is a child of the AR Session Origin?

If so which one will give me the world position ?

```
Vector3 wPos = arSessionOrigin.camera.transform.position;
Vector3 lPos = arSessionOrigin.camera.transform.localPosition;
```

Do I need to attach an AR Pose Driver script to that camera game object ? Does it make a difference ?

Thanks!

**Comment by DavidMohrhardt** [comment]
Assuming you mean real world then you should use the `localPosition` of the camera parented to the `AR Session Origin` that will get you the camera position relative to the session origin and handle any cases where the session origin has been translated, rotated, or scaled.

**Comment by alexs7** [comment]
Does that pose correspond to https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getDisplayOrientedPose() in ARCore or https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getPose() ?

**Comment by DavidMohrhardt** [comment]
Yes, I mis-phrased it.  Edited the comment to reflect the proper phrasing.

**Comment by DavidMohrhardt** [comment]
> Does that pose correspond to https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getDisplayOrientedPose() in ARCore or https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getPose() ?

It would be the `DisplayOrientedPose`

**Comment by alexs7** [comment]
From debugging, it seems that z-axis in unity is flipped compared to the android poses.. What is the expected coordinate system in Unity ? I mean for the local camera one (not the world.)

**Comment by DavidMohrhardt** [comment]
Unity is left-handed, Y-Up whereas ARCore is right-handed Y-Up so a conversion must happen to get the ARCore pose in Unity space.

**Comment by alexs7** [comment]
@DavidMohrhardt  Ok this makes sense!  So this `arSessionOrigin.camera.transform` will be a  left-handed coordinate system but 
https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getDisplayOrientedPose() this in a right-handed coordinate system ?

**Comment by DavidMohrhardt** [comment]
That is correct.  Under the hood the ARCore Provider Plug-In performs the conversion before reporting to the input subsystem.  The input subsystem then surfaces that information to the Unity input system from which the `XROrigin` `TrackedPoseDriver` or the legacy `ARPoseDriver` will drive the camera pose in the scene.

**Comment by alexs7** [comment]
`ARPoseDriver` is not legacy is it ? `TrackedPoseDrive` is if I recall ?

**Comment by alexs7** [comment]
@DavidMohrhardt Ok `XROrigin` is a 5.0 version class. I am still at 4.1

Great! Thanks a lot for the links! :)

**Comment by hejinxin0** [comment]
Is it necessary to enable ARPoseDriver when using ARSessionOrigin to obtain the camera pose? I want to obtain the camera pose but not automatically apply it to the virtual object. What should I do?
