### ISSUE TITLE
How to convert XRCpuImage to PointCloud?

### ISSUE THREAD

**Issue by tabeaeggler** [Unity-Technologies/arfoundation-samples#966]
I try to extract the complete point cloud from the XRCpuImage in CpuImageSample.cs: https://github.com/Unity-Technologi...es/blob/main/Assets/Scripts/CpuImageSample.cs. How do I have to extend this class?

**Comment by tdmowrer** [comment]
Do you mean this? https://github.com/Unity-Technologies/arfoundation-samples#allpointcloudpoints

**Comment by tabeaeggler** [comment]
Hi @tdmowrer. No, this only detects the feature points. I need the full point cloud out of the depth map with around 50'000 points per frame.

**Comment by tdmowrer** [comment]
I'm not sure what you are asking for. A feature point is a point in the point cloud; where do you expect to get 50k points per frame?

**Comment by andyb-unity** [comment]
AR Foundation does not provide an interface to convert an `XRCpuImage` to a point cloud, but for community support for your inquiry you could try our forums: https://forum.unity.com/forums/ar.161/
