### ISSUE TITLE
Change camera source to an USB camera connect with Android

### ISSUE THREAD

**Issue by lookoutking** [Unity-Technologies/arfoundation-samples#967]
I have an AR glasses connect with the Android phone by usb type-c. 
Is it possible to change the camera source from the phone camera to the additional glasses camera in AR foundation?

**Comment by andyb-unity** [comment]
ARCore does not support this use case, but you could implement your own provider plug-in for AR Foundation to use the data from your device. https://docs.unity3d.com/Manual/xrsdk-provider-setup.html
