### ISSUE TITLE
How to get ar camera/preview view co-ordinates from CpuImage coordinates?

### ISSUE THREAD

**Issue by manwithsteelnerves** [Unity-Technologies/arfoundation-samples#972]
How do I...
CpuImage has totally different co-ordinate system compared to the camera view under AR Session Origin. Are there any available methods to do this conversion?

I'm currently detecting bounds for an object by passing CpuImage to my ML engine. Once the bounds are detected, they are in CpuImage coordinates. These are very different from the camera preview co-ordinates as CpuImage will be in a different resolution.

I'm looking for a way to convert a point in CpuImage to a point in Camera preview. Are there any built in api methods to do this?

**Comment by DavidMohrhardt** [comment]
There is no built-in API for converting the CPUImage to the same coordinates you'd see on your screen. You can look into the ARCore/ARKit background shader to see how the image is mapped to the phone screen however.  You'd need to apply the same texture transforms to your bounds to compute the coordinates on the phone screen.

An alternative approach would be to [blit the background](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/index.html#scene-setup#copying-the-camera-texture-to-a-render-texture-when-accessing-the-camera-image-on-the-gpu) using the current background material and inject an [RequestAsyncReadback](https://docs.unity3d.com/ScriptReference/Rendering.CommandBuffer.RequestAsyncReadbackIntoNativeArray.html) then use that in you ML engine. This may be a little easier overall.

**Comment by manwithsteelnerves** [comment]
Thanks for the details. I will check the shader code once.
Also wondering if the matrices info passed in the frameReceived event args can help in transforming the point from cpuImage. Where can I find better information about the displaymatrix. It would be great if anyone here can explain.

**Comment by manwithsteelnerves** [comment]
@DavidMohrhardt @tdmowrer Any thoughts?

**Comment by tdmowrer** [comment]
> Also wondering if the matrices info passed in the frameReceived event args can help in transforming the point from cpuImage. Where can I find better information about the displaymatrix. It would be great if anyone here can explain.

See https://github.com/Unity-Technologies/arfoundation-samples/blob/d71529a1767efbaeb78732f4b23046e6e19c2717/Assets/Scripts/DisplayDepthImage.cs#L328-L370 for an example.

> Only problem I see with the blitting approach is the final image format. I need the format to be YUV_420_888(or atleast NV21) provided by cpuImage by default but RequestAsyncReadback doesn't allow me to specify that format. If cpuImage internally does the conversion (most likely it won't as cpu images seems to be part of arcore native c api feature which gives data directly in YUV_420_888 format), then I can avoid conversion on my end.

On Android, the XRCpuImage should already be in YUV_420_888 (for the camera image; depth formats are different). See [XRCpuImage.Format](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.2/api/UnityEngine.XR.ARSubsystems.XRCpuImage.Format.html). That's what the [ARCore C API](https://developers.google.com/ar/reference/c/group/ar-image) provides as well.

**Comment by manwithsteelnerves** [comment]
Looks like I need to explore more on the display matrix part. I tried with display matrix but unfortunately It didn't work the way I expected. Most likely I could be doing it wrong.

**Comment by FrighteningFunction** [comment]
# More issues with DisplayMatrix

I have the exact same issue. For some reason, when I apply the displaymatrix to my coordinates, it does not seem to help. Overall the pose looks correct, but the coordinates are shrunken on each side after applying the displaymatrix. I verified that the input coordinates are not shifted.

![Image](https://github.com/user-attachments/assets/e38326da-cfe6-4fce-a40c-d584132a6e7e)

I transposed the matrix as I am on Android platform as required. In theory, after casting rays using Camera.main.ScreenPointToRay().

I copy my conversion code in case someone has a spark:

```csharp
public Vector2 fromRawCpuToViewport(Matrix4x4 D, Vector2 cord)
{
    //camTex: Texture2D extracted from XRCpuImage as provided in documentation
    float u = cord.x / camTex.width;
    float v = cord.y / camTex.height;

    Vector4 uv = new Vector4(u, v, 1f, 0f);
    Vector4 mapped = D.transpose * uv

    //convert to screen

    mapped.x *= Screen.width;
    mapped.y *= Screen.height;


    Debug.Log($"mapped = {mapped}");

    return new Vector2(mapped.x, mapped.y);
}
```
I think this is a relatively serious issue and code that would be important for AR applications, and **it should be better documented** on precisely how to use displayMatrix and these transformations. I was not the only one not understanding / not being able to use this critical pipeline for my application, causing it to fail completely.

I know Displaymatrix was documented, more exactly it's derivation, however, I think more precise use-case and application documentation, including more example codes should be provided to users.

The upper example code you have attached **does not** show exactly how to map XRCpuImage coordinates to Screen coordinates as displayed by AR Camera Background.

@DavidMohrhardt @tdmowrer @andyb-unity
