### ISSUE TITLE
ARFoundation TryAcquireLatestCpuImage is not synchronized with ARCamera Pose?

### ISSUE THREAD

**Issue by a55987482** [Unity-Technologies/arfoundation-samples#978]
I use render streaming and AR foundation package to build my project, the purpose is to achieve the function of AR remote rendering.
The client side collects the modelview matrix, projection matrix, and timestamp, and sends it to the server for scene rendering, and then streaming it to the client side. The scene frame and camera frame will be matched through Timestamp, and the matched frame will be used Shader to merge.

I had the same problem as [this discussion thread](https://github.com/Unity-Technologies/arfoundation-samples/issues/679#issuecomment-738579769),  the model of the scene frame is not synchronized on the camera frame. The model seems to drift. I have tried all the suggested methods in it, but I still have the same problem. Is there any other solution?

The link is my code. (Client)
https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56
[PlaceOnPlane.cs](https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56#file-placeonplane-cs) is collects the modelview matrix, projection matrix, Timestamp, and sending them to the server.
[CameraFrame.cs](https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56#file-cameraframe-cs) is responsible for storing Camera frame in Dictionary.
[AnchorSample.cs](https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56#file-anchorsample-cs) is responsible for receiving server-side streaming images (each frame includes Timestamp), and uses Timestamp to extract the matching Camera frame, and finally merges through Shader.

**Comment by andyb-unity** [comment]
Closing this issue as your question is beyond the scope of this repository and the supported features of AR Foundation. Best of luck with your project though!

**Comment by hejinxin0** [comment]
> I use render streaming and AR foundation package to build my project, the purpose is to achieve the function of AR remote rendering. The client side collects the modelview matrix, projection matrix, and timestamp, and sends it to the server for scene rendering, and then streaming it to the client side. The scene frame and camera frame will be matched through Timestamp, and the matched frame will be used Shader to merge.
> 
> I had the same problem as [this discussion thread](https://github.com/Unity-Technologies/arfoundation-samples/issues/679#issuecomment-738579769), the model of the scene frame is not synchronized on the camera frame. The model seems to drift. I have tried all the suggested methods in it, but I still have the same problem. Is there any other solution?
> 
> The link is my code. (Client) https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56 [PlaceOnPlane.cs](https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56#file-placeonplane-cs) is collects the modelview matrix, projection matrix, Timestamp, and sending them to the server. [CameraFrame.cs](https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56#file-cameraframe-cs) is responsible for storing Camera frame in Dictionary. [AnchorSample.cs](https://gist.github.com/a55987482/49b9ede2ef1905e9a9f6e78f4b54fb56#file-anchorsample-cs) is responsible for receiving server-side streaming images (each frame includes Timestamp), and uses Timestamp to extract the matching Camera frame, and finally merges through Shader.

@a55987482 I encountered the same problem, the rendered model is not fixed with the real scene, how did you solve it? Thanks.
