### ISSUE TITLE
Pose Manager: GetRecentDevicePose failed. Passed timestamp is too old.

### ISSUE THREAD

**Issue by Tostifrosti** [Unity-Technologies/arfoundation-samples#98]
I'm not sure if this is Unity, AR Foundation or ARCore but i'm getting bombarded with these messages in the Logcat on Android (more than 1000 messages):

2019-02-18 14:24:17.929 11812-12389/com.company.example.project W/native: pose_manager.cc:61 GetRecentDevicePose failed. generic::invalid_argument: Passed timestamp is too old. Latest VIO t:881126.987531, latest IMU t:881127.128605, query t:881118.000196

Environment/Devices:
Samsung Galaxy S8
Unity 2018.3.6f1
AR Foundation Package 1.0.0-preview.22
ARCore XR Plugin Package 1.0.0-preview.24

**Comment by tdmowrer** [comment]
Thanks for reporting. This seems to be an issue in ARCore. I can reproduce it with https://github.com/google-ar/arcore-unity-sdk

Search through some ARCore issues, it sounds like this is a known issue.

**Comment by AkshayNaik033** [comment]
I am facing the same issue. Any luck with this?

**Comment by Tostifrosti** [comment]
I'm closing this issue as this problem seems to be resolved in the latest AR Foundation (package 2.1 on Unity 2019.1.3f1).
