### ISSUE TITLE
Access to the mesh generated from NormalMeshes

### ISSUE THREAD

**Issue by MarcoLavoro** [Unity-Technologies/arfoundation-samples#980]
How do I access to the mesh generated inside the scene NormalMeshes to save it?

**Comment by andyb-unity** [comment]
You can subscribe to the ARMeshManager's meshesChanged event: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/api/UnityEngine.XR.ARFoundation.ARMeshManager.html#UnityEngine_XR_ARFoundation_ARMeshManager_meshesChanged.

When you see that a MeshFilter has been added, you can access its mesh via the Mesh property: https://docs.unity3d.com/ScriptReference/MeshFilter-mesh.html
