### ISSUE TITLE
[Bug]Emergency help AROcculusionmanager and ARHumanbodymanager conflict,Cannot be used at the same time

### ISSUE THREAD

**Issue by sunrui19941128** [Unity-Technologies/arfoundation-samples#983]
1. 3dbodytrack cannot be used when humansegmentstencilmode is enabled
2.Human tracking will not work after human shielding is turned on
3.I want to make the virtual object follow the real person and keep the occlusion relationship
4.How to modify to make these two modules work
5. void OnHumanBodiesChanged(ARHumanBodiesChangedEventArgs eventArgs)  Another problem is that there is no event notification when 3D characters are lost,Only add and updateEvent
 - Unity version 2021.3.2LTS
 - ARFoundation version 5.0 pre 12

**Comment by tdmowrer** [comment]
These features cannot be used at the same time; it's a limitation of ARKit. See, for example:
 https://developer.apple.com/forums/thread/124944

**Comment by sunrui19941128** [comment]
> 这些功能不能同时使用；这是 ARKit 的限制。参见，例如： [https ://developer.apple.com/forums/thread/124944](https://developer.apple.com/forums/thread/124944)

Why can't I get the missing event of body tracking? OnHumanBodiesChanged(ARHumanBodiesChangedEventArgs eventArgs) Only add event and updatae event, remove event not Never triggered

**Comment by tdmowrer** [comment]
Check the tracking state. See https://github.com/Unity-Technologies/arfoundation-samples/issues/321

**Comment by andyb-unity** [comment]
Closing this issue as @tdmowrer has given the correct answers to both questions. Thanks Tim!
