### ISSUE TITLE
[Bug] Get the ARCamera image to a  RenderTexture, ReadPixels from the RenderTexture then set to a RawImage , flickers color ???

### ISSUE THREAD

**Issue by hasionerin** [Unity-Technologies/arfoundation-samples#985]
Unity Version : Unity2020.3.18
ARFoundation Version : 4.2.1
ARCore XR Plugin 4.2.1
Platform : Android

I Get the ARCamera Image Real-time, Render to a RenderTexture,  then ReadPixels from the RenderTexture ,and set to a RawImage , unfortunately, the RawImage flickers color .

follow is my code:

`   

    public Camera cam; 
    public RawImage img;
    
    private Texture2D renderResult = null;

    public RenderTexture camRT;

    #region GPU 

    private RenderTexture mRenderTexture;

    private void Update()
    {
        if (mRenderTexture == null)
        {
            RenderTextureDescriptor renderTextureDes = new RenderTextureDescriptor(480, 640, RenderTextureFormat.BGRA32);

            mRenderTexture = RenderTexture.GetTemporary(renderTextureDes);
        }

        cam.targetTexture = mRenderTexture;
        cam.Render();

        RenderTexture.active = mRenderTexture;

        if (renderResult == null)
            renderResult = new Texture2D(480, 640, TextureFormat.RGB24, false);

        renderResult.ReadPixels(new Rect(0, 0, mRenderTexture.width, mRenderTexture.height), 0, 0);
        renderResult.Apply();

        img.texture = renderResult;

        cam.targetTexture = null;
        RenderTexture.active = null;

    }

    #endregion`
it like flicker every few frames . It's too strange . and it works fine on ios devices. just error on android devices . has anyone had this problem? and how to solve this problem?

i take some photos : 

![微信图片_20220614155737](https://user-images.githubusercontent.com/30287459/173525280-140af135-a658-448e-ad83-b7ba22412f35.jpg)

![微信图片_20220614155745](https://user-images.githubusercontent.com/30287459/173525337-e04adc6d-6ef2-4648-95f0-e376fa2b5f1c.jpg)
![微信图片_20220614155754](https://user-images.githubusercontent.com/30287459/173525352-3efa3d05-fca1-4526-971e-99b4475a22c2.jpg)

**Comment by hasionerin** [comment]
@tdmowrer please helps me . This problem has puzzled me for a long time. thanks a lot !

**Comment by DavidMohrhardt** [comment]
I can't help but wonder if this might be a timing issue.

To validate it's not can you try just using [Graphics.Blit](https://docs.unity3d.com/ScriptReference/Graphics.Blit.html) or use a blit command buffer and add it to the [CameraEvent.AfterEverything](https://docs.unity3d.com/ScriptReference/Rendering.CameraEvent.AfterEverything.html) event like so:
```csharp
commandBuffer.clear();
commandBuffer.ClearRenderTarget(true, false, Color.clear);
commandBuffer.Blit(texture, myRenderTarget, material);
Camera.main.AddCommandBuffer(CameraEvent.AfterEverything, commandBuffer);
```
then read the texture [OnPostRender](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnPostRender.html).
