### ISSUE TITLE
[Bug] unity Application.Unload() doesn't work correctly on AR mode

### ISSUE THREAD

**Issue by moheydy** [Unity-Technologies/arfoundation-samples#987]
I build a Ar application, Everything is good but when
I use Applications.Unload() ( I want in future embedded my app in  a android studio Applications ) and back again in App , Ar camera have a lag and leak for about 10 second and many  times for always until Quite of App
(even in empty Ar app i have this issue)

 - Device: [Android]
 - OS: [Android 12, 11 , any Android]
 - Unity version 2021.2
 - ARFoundation 4.2

**Comment by DavidMohrhardt** [comment]
Can you provide a recording of the behavior?

**Comment by DavidMohrhardt** [comment]
A possible workaround would be to deinitialize your loader during the `Application.unloading` callback manually.

**Comment by moheydy** [comment]
Tanks  I fixed this by manually calling StartXR function in Awake and StopXR before Unload

    private void Awake()
    {
        Application.unloading += OnUnload;

        FindObjectOfType<ManualXRControl>().StartXR();
   }

    static void OnUnload()
    {
        Debug.Log("Unloading the Player");
      FindObjectOfType<ManualXRControl>().StopXR();
    }

Just don't forget to remove tick Initialize XR on startup in PlayerSetting (This function doesn't work correctly after first unload even if you call StopXR() )
