### ISSUE TITLE
[Bug] ObjDetQueue.thread crash when using Object Tracking with ARFoundation for iOS

### ISSUE THREAD

**Issue by AkhilRaja** [Unity-Technologies/arfoundation-samples#991]
**Unity bug report case number**
Case 1287297

**Describe the bug**
Unity crashes when using ARFoundation Object Tracking for iOS and resetting the ARSession. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an ARFoundation Object Tracking app
2. Reset the ARSession
3. Load a different ARObject into the reference library
4. The app crashes on the ObjDetQueue (Thread 379 Queue : ObjDetQueue (serial))
<img width="1440" alt="Screenshot 2022-06-29 at 5 11 29 PM" src="https://user-images.githubusercontent.com/8157457/176428992-a69be3f4-0658-40fb-8da3-3ef9d397af35.png">

`dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib`

**Expected behavior**
You should be able to load different ARObjects into a reference library and the app should not crash

**Actual behavior**
The app is crashing randomly 

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15
 - Unity version - 2022.1.1f1
 - ARFoundation version - 4.3 (I tried the same on 5+ prerelease versions and it is reproducible there too)

**Comment by ankur-unity** [comment]
As noted in the issue tracker, the issue is in ARKit code and cannot be fixed by Unity.
https://issuetracker.unity3d.com/issues/objdetqueue-dot-thread-crash-when-using-object-tracking-artrackedobjectmanager-and-ar-foundation

We communicated this to Apple at the time. You can look into their developer forums for directly reporting it to Apple.
https://developer.apple.com/forums/tags/arkit

**Comment by AkhilRaja** [comment]
Thanks @ankur-unity . Is there any eta on ARKit 6 with ar foundation? They claim to have improved object detection in it and I’m hoping that would fix this bug.

**Comment by ankur-unity** [comment]
> Thanks @ankur-unity . Is there any eta on ARKit 6 with ar foundation? They claim to have improved object detection in it and I’m hoping that would fix this bug.

@AkhilRaja - Sorry for the delayed response. We are working on ARKit 6 feature integration but don't have an ETA yet.

For object detection, there are no API changes that I'm aware of. You can try building your project with the Xcode 14 beta to test the improvements in object detection in ARKit 6.

**Comment by AkhilRaja** [comment]
@ankur-unity no problem, thanks for responding. I was hoping they would have fixed this problem with arkit6, I too dont think there is any API change. Thanks for pointing out that I could try it out with Xcode 14 beta. I will test it out and see if this bug is reproducible.

**Comment by ankur-unity** [comment]
Closing this due to lack of response. The original issue was a third party issue in ARKit Framework and cannot be fixed by Unity.

Feel free to re-open if you have additional questions.
