### ISSUE TITLE
[Bug] Unity crashes when running XR Simulation on Apple Silicon (M1)

### ISSUE THREAD

**Issue by ajayns** [Unity-Technologies/arfoundation-samples#994]
**Describe the bug**
For even the most basic AR setup in Unity, the app almost instantly hangs or does so when you interact with it once when in play mode.

It seems to be a macOS error, particularly even an M1 chipset thing cause I run the same thing on windows and it works fine.
Possibly related: https://forum.unity.com/threads/macbook-pro-m1-oculus-crash.1017730/

**To Reproduce**
1. Run any of the example scenes even in this repo
2. Setup XR Simulation Environments
3. Enable AR Environments and enter play mode
4. Interact with the app once or twice and wait for it to hang.

**Expected behavior**
Runs simulation smoothly.

**Actual behavior**
Unity Crashed

**Smartphone (please complete the following information):**
 - Device: MacBook Pro (16" M1 Max)
 - OS: macOS 12.3.1
 - Unity version: 2021.3.5f1
 - ARFoundation version: 5.0.0-pre.12

**Comment by andyb-unity** [comment]
Please file a bug. https://unity3d.com/unity/qa/bug-reporting

**Comment by DennisDeRykeUnity** [comment]
@ajayns Thank you for bringing this to our attention!  Unity QA staff encountered this issue this week, and one of our AR Devs was able to reproduce this bug.  We do not see the crash if we use the Intel version of the Unity Editor on an M1 Mac.  We are continuing to investigate.

**Comment by JanOwiesniak** [comment]
I experience the same problem on my MacBook Pro (16" M1 Max). All AR Foundation scenes freeze as soon as I press the "Run" button in the Unity Editor Silicon Edition.

**Workaround**

Install Unity Editor **Intel** Edition and ran it with **Rosetta**

**Comment by KirillKuzyk** [comment]
Several AR Foundation Remote plugin users also experience crashes on the M1 chip with similar symptoms.

**Comment by ankur-unity** [comment]
We have created a public issue tracker for this bug: https://issuetracker.unity3d.com/issues/simulation-hangs-on-arm-macs-with-silicon-editor-build

**Comment by andyb-unity** [comment]
Fixed in AR Foundation 5.0.2: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/changelog/CHANGELOG.html

**Comment by ajayns** [comment]
Verified fix! Thanks a bunch guys!

**Comment by tichise** [comment]
Do you plan to resolve this issue in the AR Foundation 4?
