### ISSUE TITLE
Roomplan Arkit

### ISSUE THREAD

**Issue by moheydy** [Unity-Technologies/arfoundation-samples#995]
Please Add a example about  Roomplan Arkit and export file

**Comment by andyb-unity** [comment]
Hi @moheydy,

AR Foundation allows you to work with augmented reality platforms in a multi-platform way within Unity, using ARCore on Android and ARKit on iOS. RoomPlan is a new Framework available on iOS and OSX, separate from ARKit and thus not a part of AR Foundation's current developer offering.

Are you willing to share more about your use case?

**Comment by moheydy** [comment]
Hi @andyb-unity  I wanted to create a platform for real estate consultants, with the help of which the house maps can be modelled in 3D and shown to the users

**Comment by AytoMaximo** [comment]
+1 here. We also would like to try the new RoomPlan feature from Apple. Will there be the offical Unity support of this feature (as a part of ARFoundation or something else) in the future? If yes, when? 

Any info on this issue is appreciated!

**Comment by andypoly** [comment]
This may not be 'core' AR functionality, but is something that would be great to access from a Unity app - particular as mentioned, for interior design, real estate etc. but probably for AR also. So, if not here, then via another API

**Comment by MarcoLavoro** [comment]
> Hi @moheydy,
> 
> AR Foundation allows you to work with augmented reality platforms in a multi-platform way within Unity, using ARCore on Android and ARKit on iOS. RoomPlan is a new Framework available on iOS and OSX, separate from ARKit and thus not a part of AR Foundation's current developer offering.
> 
> Are you willing to share more about your use case?

There is any external package (Maybe on asset store) to use the RoomPlan api?

**Comment by simonobi** [comment]
I was able to integrate an AR Foundation Unity project with LIDAR mesh generation in a native iOS app which features the Room Scanning feature and to transfer the room data to Unity code.
My desired use case would be to generate meshes and the room plan simultaneously.

Please implement it in AR Foundation! 

:)

**Comment by MarcoLavoro** [comment]
> ny external package (Maybe on asset store) to use the RoomPlan api?

can you share the code please?

**Comment by AlexTrofim88** [comment]
Try [RoomPlan for Unity Kit](https://assetstore.unity.com/packages/tools/utilities/roomplan-for-unity-kit-255058)

**Comment by andyb-unity** [comment]
Hi all,

I'm excited to share that Unity has revamped the XR roadmaps, including the ability to request and vote for features: https://unity.com/roadmap/unity-platform/arvr

Please use the official road map for feature requests. Go the **AR Foundation** tab, scroll down and select **Submit a New Idea**. I'm closing this issue as GitHub is not a suitable place for Unity to accept feature requests.
