### ISSUE TITLE
ARCore Geospatial API sample

### ISSUE THREAD

**Issue by annachiu7** [Unity-Technologies/arfoundation-samples#997]
It'll be really nice to have an ARCore Geospatial API sample in addition to the existing ARKitGeoAnchors sample that demonstrates how to put anchors/objects in a real-world location

**Comment by ankur-unity** [comment]
Currently, AR Foundation does not support ARCore Geospatial APIs. You can look into the [ARCore Extensions package](https://github.com/google-ar/arcore-unity-extensions) which is maintained by Google and works on top of AR Foundation to provide ARCore features that are not yet integrated into AR Foundation. 
https://github.com/google-ar/arcore-unity-extensions

**Comment by ankur-unity** [comment]
Closing as answered. The samples are available in the ARCore Extension package as stated above. Feel free to re-open to the issue if you have additional questions.
