### ISSUE TITLE
[Bug] Plane tracking not stable even android devices supports ARCore  | Oneplus Nord2 5G

### ISSUE THREAD

**Issue by dhruvaura** [Unity-Technologies/arfoundation-samples#998]
**Describe the bug**
I tried ground tracking on my android device Oneplus Nord2 5G. Tracking is not stable, after some plane tracks, it goes away. So basically plane tracking not working on supported android phone.

**To Reproduce**
Just run basic plane tracking application on Android Phone OnePlus Nord2 5G, which already listed as arcore supported device

**Expected behavior**
Plane tracking should be stable. What can be solution for smooth plane tracking on my Oneplus Nord2 5G phone?
On my other android phones app works smoothly as expected, tracking is also stable.

**Actual behavior**
Plane tracking not stable, very slow. After detect some  planes, tracking lost and planes goes far away
Google’s sample app also not working I tried ARCore elements app, that also not working 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X] Android Oneplus Nord 2 5G
 - OS: [e.g. iOS 13] Android 12 Oxygen 12 
 - Unity version 2020.3.11f1 LTS
 - ARFoundation version : Compatible to Unity 2020.3.11f1 Version I’ve verified used

**Comment by ankur-unity** [comment]
Is it only happening with the planes or is it happening with other trackables as well, like Anchors?

Can you also provide a recording of the behavior that you're seeing on the device?

**Comment by lampyr** [comment]
Hello and if i need to make another ticket but i have the same problem.
It is random when it works.
And for the face recognition it work better with the few test i made it at the moment.

Device: [e.g. iPhone X] Android Oneplus Nord 2 5G
OS: [e.g. iOS 13] Android 12 Oxygen 12
Unity version 2021.3.8f1 LTS

[video on google drive](https://drive.google.com/drive/folders/1gI28CO64o8u0QzbpEXtUNJ2n9J9NliTm?usp=sharing)

**Comment by dhruvaura** [comment]
Yes same issues happening to on my OnePlus Nord2 5G. 
Thanks for all videos. I think this is helpful for debug @ankur-unity

**Comment by mschult2** [comment]
Any update here? 

I have a couple mid-tier Android ARCore devices, and the vertical plane detection doesn't work most of the time. When walls are detected, they are never labeled properly, just "Other". (Horizontal floor plane seems fine)

Would a different phone do labeled vertical planes?

-----
-2020 Lume Pad, 2016 Google Pixel (ARCore Depth API Supported)
-Unity 2022.1
-ARFoundation 5.0.5

**Comment by andyb-unity** [comment]
AR Foundation is a cross-platform AR interface, but does not implement AR tracking. ARCore tracking quality is generally worse than ARKit, and tracking quality on both platforms relies on the detection of feature points in the environment. Monochromatic featureless planes such as the table in your example video are difficult for these platforms to track.

I'm closing this issue as the expected behavior of ARCore, but feel free to re-open it if you have more specific questions.
