### ISSUE TITLE
 ARKit Object Capture support?

### ISSUE THREAD

**Issue by Arytes** [Unity-Technologies/arfoundation-samples#999]
does it support  ARKit Object Capture or when did it support？

**Comment by ankur-unity** [comment]
Object Capture API is part of RealityKit and not ARKit Framework. AR Foundation does not support RealityKit. 

Unity has a AR Companion package which support the use case of Object Capture. It uses Apple's Object Capture under the hood. See https://docs.unity3d.com/Packages/com.unity.ar-companion-core@1.0/manual/object-capture-workflow.html

**Comment by ankur-unity** [comment]
Note that ARKit support Object Tracking which is different than Object Capture. AR Foundation support object tracking. The documentation on AR Foundation and ARKit package will be a good place to start for object tracking.

- AR Foundation: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/tracked-object-manager.html
- ARKit: https://docs.unity3d.com/Packages/com.unity.xr.arkit@5.0/manual/arkit-object-tracking.html

**Comment by ankur-unity** [comment]
Closing this issue as answered and due to lack of activity from user. Feel free to re-open if there are follow-up questions.
